### ISSUE TITLE
sentry_flutter:mergeReleaseResources

### ISSUE THREAD

**Issue by mehrdadmmb2** [getsentry/sentry-dart#1008]
### Description

I get this issue when I want to build an APK
dependency version: 6.9.1
sdk: ">=2.11.0 <3.0.0"

--------------------------------

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':sentry_flutter:mergeReleaseResources'.
> Could not resolve all files for configuration ':sentry_flutter:releaseRuntimeClasspath'.
   > Failed to transform lifecycle-process-2.2.0.aar (androidx.lifecycle:lifecycle-process:2.2.0) to match attributes {artifactType=android-res, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Could not find lifecycle-process-2.2.0.aar (androidx.lifecycle:lifecycle-process:2.2.0).
        Searched in the following locations:
            https://dl.google.com/dl/android/maven2/androidx/lifecycle/lifecycle-process/2.2.0/lifecycle-process-2.2.0.aar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 44s

------------------------------

**Comment by marandaneto** [comment]
You need to add `google()` under your `repositories` block in the `build.gradle` files.

**Comment by mehrdadmmb2** [comment]
> You need to add `google()` under your `repositories` block in the `build.gradle` files.

thank you,
actually, id did it before

**Comment by DipperTheViper** [comment]
hi i still get this error while google() is added already

**Comment by DipperTheViper** [comment]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugAssets'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform lifecycle-runtime-2.5.1.aar (androidx.lifecycle:lifecycle-runtime:2.5.1) to match attributes {artifactType=android-assets, org.gradle.status=release}.
      > Could not find lifecycle-runtime-2.5.1.aar (androidx.lifecycle:lifecycle-runtime:2.5.1).
        Searched in the following locations:
            https://dl.google.com/dl/android/maven2/androidx/lifecycle/lifecycle-runtime/2.5.1/lifecycle-runtime-2.5.1.aar

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by DipperTheViper** [comment]
pubspec.yaml:


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.1.1+1
  carousel_slider: ^4.1.1
  flutter_launcher_icons: ^0.10.0
  logger: ^1.1.0
  http: ^0.13.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^6.0.0
  flutter_native_splash: ^2.2.6
  dotted_line: ^3.1.0
  device_preview: ^1.1.0
  connectivity_plus: ^3.0.2
  open_settings: ^2.0.2
  webview_flutter: ^3.0.4
  url_launcher: ^6.1.6
  local_auth: ^2.1.2
  local_auth_android: ^1.0.15
  uuid: ^3.0.6
  syncfusion_flutter_charts: ^20.2.46
  just_the_tooltip: ^0.0.12
  expandable: ^5.0.1
  digit_to_persian_word: ^2.0.0
  shamsi_date: ^1.0.1
  dropdown_button2: ^1.8.2
  package_info_plus: ^3.0.1
  device_info_plus: ^8.0.0
  sentry_flutter: ^6.15.1

build.gradle :

buildscript {
    ext.kotlin_version = '1.6.10'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.1.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}
