### ISSUE TITLE
[BUG] Scope.dart Incorrect Cloning of The Scope User

### ISSUE THREAD

**Issue by andyweng0424** [getsentry/sentry-dart#1010]
_Platform:_
- [x]  Dart
- [ ]  Flutter Android or iOS
- [ ]  Flutter Web

_IDE:_
- [ ]  VSCode
- [ ]  IntelliJ/AS
- [ ]  XCode
- [x]  Other, which one? (Android Studio)

_split-debug-info and obfuscate (Flutter Android or iOS) or CanvasKit (Flutter Web):_
- [ ]  Enabled
- [x]  Disabled

_Platform installed with:_
- [x] pub.dev
- [ ] GitHub

Output of the command `flutter doctor -v` below:

```
[✓] Flutter (Channel stable, 3.3.2, on macOS 12.6 21G115 darwin-x64, locale en-US)
    • Flutter version 3.3.2 on channel stable at /Users/andyweng/Desktop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e3c29ec00c (6 days ago), 2022-09-14 08:46:55 -0500
    • Engine revision a4ff2c53d8
    • Dart version 2.18.1
    • DevTools version 2.15.0

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/andyweng/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.59.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.27.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.6 21G115 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```
The version of the SDK (See pubspec.lock):
**6.9.1**

---
**I have the following issue:**
Currently there is an issue with the Scope.clone function in scope.dart where the user is not copied correctly for the clone. I believe was introduced in this [PR](https://github.com/getsentry/sentry-dart/commit/6c06153c3248c773b54dcac65d6c0762320a0882#diff-11bd4997e4de9777b6188b30cd3a7a597ce01d681f72a29716cf1f0aadc9f030) where `_setUserSync(user);` was added instead of `clone._setUserSync(user);`. This causes the scope user to be empty when the `captureException` is called with the `withScope` parameter. 

**Steps to reproduce:**
-Set the Sentry User at init.
-Call `Sentry.captureException` method with the withScope function specified and add a random tag in ScopeCallback.
-Observe that the user is not set for that exception on Sentry. 

**Actual result:**
- There is no Sentry user for that exception.

**Expected result:**
- The Sentry user for that exception should be the user you set in step 1.

**Comment by marandaneto** [comment]
@andyweng0424 thanks for reporting, we will take a look at it.
