### ISSUE TITLE
how to set PROXY when use sentry dio

### ISSUE THREAD

**Issue by philos3** [getsentry/sentry-dart#1015]
https://sentry.deepcoin.ski/share/issue/d70827b5df54497d8c4e51d456fa467c/

here is my code: 
i can't get SentryDioClientAdapter,please tell me how to set PROXY when use sentry dio 
```
 setHttpProxy() {
    if (Application.instance.isDebug != 0 && SPSetting.getProxy().isNotEmpty) {
      if (Application.instance.openSentry) {
        ((_dio.httpClientAdapter as SentryDioClientAdapter).innerClient)
            .onHttpClientCreate = (client) {
          // config the http client
          client.findProxy = (uri) {
            //proxy all request to localhost:8888
            return "PROXY ${SPSetting.getProxy()}";
          };
          //代理工具会提供一个抓包的自签名证书，会通不过证书校验，所以我们禁用证书校验
          client.badCertificateCallback =
              (X509Certificate cert, String host, int port) => true;
          return client;
        };
      } else {
        (_dio.httpClientAdapter as DefaultHttpClientAdapter)
            .onHttpClientCreate = (client) {
          // config the http client
          client.findProxy = (uri) {
            //proxy all request to localhost:8888
            return "PROXY ${SPSetting.getProxy()}";
          };
          client.badCertificateCallback =
              (X509Certificate cert, String host, int port) => true;
          return client;
        };
      }
    }
  }
```

**Comment by ueman** [comment]
You should setup Sentry for Dio after you have set the proxy. That's also mentioned in the Readme:

> Call dio.addSentry(). This __must__ be the last initialization step of the Dio setup, otherwise your configuration of Dio might overwrite the Sentry configuration.

**Comment by marandaneto** [comment]
As @ueman said.

**Comment by philos3** [comment]
@marandaneto 
![image](https://user-images.githubusercontent.com/8424317/204218801-9faa8c2e-e884-4b33-a99c-6a2dd694333e.png)
I had call dio.addSentry() already，my question is how can I get SentryDioClientAdapter,it is undefined and I can't import it
if I can get innerClient, i can use findProxy to override it 

```
innerClient.onHttpClientCreate = (client) {
            // config the http client
            client.findProxy = (uri) {
              //proxy all request to localhost:8888
              return "PROXY ${SPSetting.getProxy()}";
            };
}
```

**Comment by marandaneto** [comment]
Sentry does not provide any proxy config, you should make this question to `dio` folks, it's not part of the Sentry adapter.
