### ISSUE TITLE
Missing or deprecated fields on the event protocol

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-dart#1028]
### Description

Relates to https://github.com/getsentry/team-mobile/issues/56

`DebugImage` missing `cpu_subtype` and `cpu_type`.
`Mechanism` field `meta` [isn't correctly typed](https://develop.sentry.dev/sdk/event-payloads/types/#typedef-MechanismMeta), but it should be fine since it's iOS specific.
`SentryApp` missing `app_memory`, we likely set this one on `SentryDevice`, likely a confusion here between App's sandbox memory and Device memory.
`SentryDevice` Relay is missing `screen_height_pixels` and `screen_width_pixels`
`SentryEvent` deprecate `culprit`, missing `errors` but ideally not needed for SDKs, maybe useful for E2E tests.
`SentryGpu` missing `graphics_shader_level`, `max_texture_size`, `supports_compute_shaders`, `supports_draw_call_instancing`, 
`supports_geometry_shaders`, `supports_ray_tracing`.
`SentryRequest` missing `fragment`, `inferred_content_type`, and SDK should deprecate/drop `other`.
`SentryRuntime` missing `build`, Relay is missing `compiler`.
`SentryStackFrame` missing `stack_start`, `symbol`, `vars` should be `<string, any>`, Relay is missing `addr_mode`, and `frames_omitted`.
`SentryStackTrace` missing `lang`, and `snapshot`.
`SentryTraceContext` missing `client_sample_rate`, `exclusive_time`, do we actually need them on the SDK?
`SentryTransactionInfo`, missing `changes`, `original`, `propagations`, do we actually need them on the SDK?
`SentryUser`, missing `data` <string, any>, `geo`, `name`.

**Comment by ueman** [comment]
Related: https://github.com/getsentry/sentry-dart/issues/842
