### ISSUE TITLE
I want specific error should not be reported by Sentry and "IgnoreErrors" is not present in Sentry for flutter. 

### ISSUE THREAD

**Issue by harishkthedeveloper** [getsentry/sentry-dart#1032]
Can any one tell how to ignore Specific Errors from sentry ? which is there in JS sentry

**Comment by harishkthedeveloper** [comment]
for example errors which are happening from certains plugins and i want to ignore them

**Comment by harishkthedeveloper** [comment]
I have a specific requirement :

My Application is IoT based and it has local server and Actual live server communication.
Whenever app starts we start a polling service,  which keeps hitting the local server every 3sec and the local server will be available only untill i come to the local network of My Home WIFI.

When i am on my mobile data the polling service  through Time out Exception and i want to exclude these exceptions how can i do that

**Comment by kuhnroyal** [comment]
You can use the `beforeSend` callback to filter specific events.

**Comment by marandaneto** [comment]
https://docs.sentry.io/platforms/flutter/configuration/options/#before-send if Dart/Flutter errors.
If its errors are thrown in other layers such as Native code, https://docs.sentry.io/platforms/flutter/native-init/
Then you can set the `beforeSend` also in the Native SDKs.
