### ISSUE TITLE
Support `ignoredExceptionsForType`

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-dart#1046]
### Description

Similar to https://docs.sentry.io/platforms/android/configuration/options/#ignored-exceptions-for-type
A little bit more user-friendly in case you wanna ignore specific error types rather than `if error is type` checks on `beforeSend` callback.
Consider using the "right" naming, See https://github.com/getsentry/sentry-java/issues/1532

**Comment by denrase** [comment]
Think we should go with `AddExceptionFilterForType` naming from .net, as this is also present on Android.
