### ISSUE TITLE
Set `fragment` in the dio and http integrations

### ISSUE THREAD

**Issue by ueman** [getsentry/sentry-dart#1054]
### Description

This came out of this comment: https://github.com/getsentry/sentry-dart/pull/1038/#discussion_r985250223

**Comment by marandaneto** [comment]
`inferredContentType` is inferred by the server, no need of setting it.

**Comment by marandaneto** [comment]
Consider doing it with https://github.com/getsentry/sentry-dart/issues/969

**Comment by ueman** [comment]
@marandaneto I guess this is done, correct?
