### ISSUE TITLE
Replace `sdkInfo` on iOS

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-dart#1056]
### Description

https://github.com/getsentry/sentry-dart/blob/fe217baa64bf65dac702f8ef5acd8a267f02b46c/flutter/ios/Classes/SentryFlutterPluginApple.swift#L174-L176

`sdkInfo` is deprecated https://github.com/getsentry/sentry-cocoa/pull/1960

The current alternative is the Private class but I can't add a new package https://github.com/getsentry/sentry-cocoa/blob/be47c6c37e25c3c5d92cceb875c6f408f76017f8/Sources/Sentry/PrivateSentrySDKOnly.m#L80-L99

This leads to warns during build https://github.com/getsentry/sentry-dart/issues/1055

Similar to https://github.com/getsentry/sentry-react-native/issues/2530

**Comment by marandaneto** [comment]
@brustolin @philipphofmann is there any other way of adding `packages` now?

**Comment by brustolin** [comment]
instead of this:

 ```swift
 if let sdkInfo = self.sentryOptions?.sdkInfo { 
     infos["package"] = ["version": sdkInfo.version, "sdk_name": "cocoapods:sentry-cocoa"] 
 } 
 ```
 
 Do this
 ```swift
 infos["package"] = ["version": PrivateSentrySDKOnly.getSdkVersionString(), "sdk_name": "cocoapods:sentry-cocoa"]
 ```

**Comment by marandaneto** [comment]
@brustolin I don't follow, where does `infos` come from?

**Comment by brustolin** [comment]
`infos` is a `SentryFlutterPluginApple.swift` local dictionary.

**Comment by marandaneto** [comment]
Oh yeah that makes sense, my bad.
Since Dart also adds the new package in the Dart layer
https://github.com/getsentry/sentry-dart/blob/fe217baa64bf65dac702f8ef5acd8a267f02b46c/flutter/lib/src/default_integrations.dart#L299-L310
[This](https://github.com/getsentry/sentry-dart/issues/1056#issuecomment-1272960676) works for now.
