### ISSUE TITLE
Sync users geoloaction to native layer

### ISSUE THREAD

**Issue by ueman** [getsentry/sentry-dart#1065]
The geolocation is not available yet as a class in the native layers, and therefore it can't be synced. As soon as it's available in the native layers, this should be added.

**Comment by marandaneto** [comment]
Android partially done by https://github.com/getsentry/sentry-dart/pull/1102
Should be replaced by calling their setters once this is done on Android as well.

**Comment by marandaneto** [comment]
We can actually add the `geo` bits directly on Native, upgrade the deps and replace the workaround by https://github.com/getsentry/sentry-dart/pull/1102
