### ISSUE TITLE
sentry_flutter depends on package_info_plus ^1.0.0 and app depends on package_info_plus ^2.0.0, sentry_flutter from path is forbidden

### ISSUE THREAD

**Issue by vlazdra** [getsentry/sentry-dart#1066]
_Platform:_
- [ ]  Dart
- [x]  Flutter Android or iOS
- [ ]  Flutter Web

_IDE:_
- [x]  VSCode
- [ ]  IntelliJ/AS
- [ ]  XCode
- [ ]  Other, which one?

_split-debug-info and obfuscate (Flutter Android or iOS) or CanvasKit (Flutter Web):_
- [ ]  Enabled
- [ ]  Disabled

_Platform installed with:_
- [x] pub.dev
- [ ] GitHub

Output of the command `flutter doctor -v` below:

- Not relevant to this issue

The version of the SDK (See pubspec.lock):
**6.12.1**

---
I have the following issue:
Because app depends on sentry_flutter ^6.12.1 which depends on package_info_plus ^1.0.0, package_info_plus ^1.0.0 is required.
So, because app depends on package_info_plus ^2.0.0, version solving failed.
pub get failed (1; So, because app depends on package_info_plus ^2.0.0, version solving failed.)

The description goes here ...

**Steps to reproduce:**
- add sentry 6.12.1
- add package_info_plus 2.0.0

**Actual result:**
- pub get fails

**Expected result:**
- pub get succeeds

**Comment by marandaneto** [comment]
@vlazdra thanks for reporting.

You can use `dependency_overrides` for now.

```
dependency_overrides:
  package_info_plus: ^2.0.0
```

`package_info_plus` v2 only adds a new field, so it's compatible, it's just a dependency resolution issue.
[v2 has just been released](https://pub.dev/packages/package_info_plus/changelog), we'll wait a bit more till upgrading it, otherwise we will get issues with people using v1 and our SDK v2.

**Comment by marandaneto** [comment]
@ueman that could be just a minor =D

**Comment by ueman** [comment]
Since it's compatible, you can change the dependency constraints in Sentry to 
```yaml
dependencies:
  package_info_plus: '>=1.0.0 <3.0.0'
  package_info_plus: * # or this, since there's basically no chance of the fields Sentry is using being removed
```

I didn't make the choice to go for a major bump in package_info_plus :D

**Comment by marandaneto** [comment]
Good point, the range makes more sense.
