### ISSUE TITLE
Node.js 12 actions are deprecated

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-dart#1069]
### Description

Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: VeryGoodOpenSource/very_good_coverage

**Comment by marandaneto** [comment]
Also:

> Please update the following actions to use Node.js 16: actions/upload-artifact

**Comment by marandaneto** [comment]
@vaind the last one is from the metrics, is that builtin into the Sentry workflow right? I can't upgrade directly here.

**Comment by vaind** [comment]
> @vaind the last one is from the metrics, is that builtin into the Sentry workflow right? I can't upgrade directly here.

I've already updated, just need to do a release - it will get used automatically here.
