### ISSUE TITLE
Support package_info_plus 2.0.0

### ISSUE THREAD

**Issue by khoafornia** [getsentry/sentry-dart#1074]
_Platform:_
- [ ]  Dart
- [x]  Flutter Android or iOS
- [ ]  Flutter Web

_IDE:_
- [ ]  VSCode
- [x]  IntelliJ/AS
- [ ]  XCode
- [ ]  Other, which one?

_split-debug-info and obfuscate (Flutter Android or iOS) or CanvasKit (Flutter Web):_
- [ ]  Enabled
- [x]  Disabled

_Platform installed with:_
- [x] pub.dev
- [ ] GitHub

Output of the command `flutter doctor -v` below:

[✓] Flutter (Channel stable, 3.3.4, on macOS 12.6 21G115 darwin-arm, locale en-US)
    • Flutter version 3.3.4 on channel stable at /Users/USER_NAME/fvm/versions/3.3.1
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision eb6d86ee27 (7 days ago), 2022-10-04 22:31:45 -0700
    • Engine revision c08d7d5efc
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/khoa/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.71.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (3 available)
    • iPhone SE (3rd generation) (mobile) • DEVICE_ID • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-0 (simulator)
    • macOS (desktop)                     • macos                                • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)                        • chrome                               • web-javascript • Google Chrome 106.0.5249.103

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

The version of the SDK (See pubspec.lock):
6.9.1
---
I have the following issue:

The description goes here ...

**Steps to reproduce:**
- Step: Paste `sentry_flutter: ^6.12.1` into pubspec.yaml

**Actual result:**
- Actual: ERR : Because sentry_flutter >=5.0.0 depends on package_info_plus ^1.0.0 and APP_NAME depends on package_info_plus ^2.0.0, sentry_flutter >=5.0.0 is forbidden.

**Expected result:**
- Result: FINE: Resolving dependencies finished

**Comment by marandaneto** [comment]
https://github.com/getsentry/sentry-dart/pull/1068
