### ISSUE TITLE
Some issue with obfuscated title

### ISSUE THREAD

**Issue by miguelslemos** [getsentry/sentry-dart#1078]
_Platform:_
- [ ]  Dart
- [x]  Flutter Android or iOS
- [ ]  Flutter Web

_IDE:_
- [ ]  VSCode
- [x]  IntelliJ/AS
- [x]  XCode
- [ ]  Other, which one?

_split-debug-info and obfuscate (Flutter Android or iOS) or CanvasKit (Flutter Web):_
- [x]  Enabled
- [ ]  Disabled

_Platform installed with:_
- [x] pub.dev
- [ ] GitHub

The version of the SDK (See pubspec.lock):
**6.12.2**

---

Why some issues have obfuscated titles on the Sentry dashboard? It could impact on issue group, right? Because every release the symbols changes.

Some examples:
![image](https://user-images.githubusercontent.com/11746181/195721452-4e9a242e-ea61-42a9-b3ec-5b136e553d05.png)

looking for `zua` on obfuscation-map it points to `RiverpodUsedAfterDisposalException` equals to issue description

**Steps to reproduce:**
```bash
flutter -v --no-version-check build appbundle --flavor minapi21prod  \ 
--build-name 8.59.0 --build-number 1000006285 \ 
--no-pub --target-platform android-arm,android-arm64 --obfuscate \
--split-debug-info /symbols/prod/21 \
--extra-gen-snapshot-options=--save-obfuscation-map=/symbols/prod/21/obfuscation_map.json \
--dart-define=ENVIRONMENT=prod --dart-define=RELEASE_NAME=8.59.0 \
--dart-define=DISTRIBUTION=1000006285 --dart-define=API_LEVEL=21
```
It's an Android Issue.

**Actual result:**
![image](https://user-images.githubusercontent.com/11746181/195723435-993da533-127d-43e2-b7dc-a4b01418c023.png)

**Expected result:**
I would like something like that:
![image](https://user-images.githubusercontent.com/11746181/195723557-602ffb72-59a8-4b94-85b3-8176af849aa7.png)

**Comment by marandaneto** [comment]
See https://docs.sentry.io/platforms/flutter/troubleshooting/#known-limitations

> Issue titles might be obfuscated as we rely on the runtimeType, but they may not be human-readable. See the [Obfuscate Caveat](https://flutter.dev/docs/deployment/obfuscate#caveat).

**Comment by miguelslemos** [comment]
> See https://docs.sentry.io/platforms/flutter/troubleshooting/#known-limitations
> 
> > Issue titles might be obfuscated as we rely on the runtimeType, but they may not be human-readable. See the [Obfuscate Caveat](https://flutter.dev/docs/deployment/obfuscate#caveat).

I understand, but `obfuscation_map.json`  contains the original class name, couldn't we use it to obfuscate the title?


obfuscation_map.json content

```json
[
    "RiverpodUsedAfterDisposalException",
    "zua"
]
```

**Comment by marandaneto** [comment]
@miguelslemos yep its technically possible, but sentry does not symbolicate a few properties of the event, such as the type, breadcrumbs, etc, this feedback should go to https://github.com/getsentry/sentry because it affects every SDK
