### ISSUE TITLE
Exception parsing screen dimensions in sentry_flutter

### ISSUE THREAD

**Issue by oravecz** [getsentry/sentry-dart#1079]
_Platform:_
- [x]  Dart
- [x]  Flutter Android or iOS
- [ ]  Flutter Web

_IDE:_
- [ ]  VSCode
- [x]  IntelliJ/AS
- [ ]  XCode
- [ ]  Other, which one?

_split-debug-info and obfuscate (Flutter Android or iOS) or CanvasKit (Flutter Web):_
- [ ]  Enabled
- [x]  Disabled

_Platform installed with:_
- [ ] pub.dev
- [ ] GitHub

Output of the command `flutter doctor -v` below:

<details>
[✓] Flutter (Channel beta, 3.4.0-17.2.pre, on macOS 12.5.1 21G83 darwin-arm, locale en-US)
    • Flutter version 3.4.0-17.2.pre on channel beta at /Users/jimcook/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d6260f127f (3 weeks ago), 2022-09-21 13:33:49 -0500
    • Engine revision 3950c6140a
    • Dart version 2.19.0 (build 2.19.0-146.2.beta)
    • DevTools version 2.16.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/jimcook/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 70.0.5
    • Dart plugin version 222.4167.21

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
    • iPhone 14 Pro Max (mobile) • 7AD961F4-7448-4C6D-8412-EE94538CEAC7 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-0 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 12.5.1 21G83 darwin-arm
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 106.0.5249.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
<details>

The version of the SDK (See pubspec.lock):
**6.11.2**

---
I have the following issue:

On iOS, the `_LoadContextsIntegrationEventProcessor` receives an event and begins to parse the `ContextMaps` from its JSON payload. The `device` type is detected and `SentryDevice` has its chance to parse the JSON payload. The `screenHeightPixels` is defined as `int?`, and the string in the JSON payload is a `double`. 

This results in the following exception

```
[sentry] [error] loadContextsIntegration failed
         type 'double' is not a subtype of type 'int?'
         #0      new SentryDevice.fromJson (package:sentry/src/protocol/sentry_device.dart:229:33)
         #1      new Contexts.fromJson (package:sentry/src/protocol/contexts.dart:40:26)
         #2      _LoadContextsIntegrationEventProcessor.apply (package:sentry_flutter/src/default_integrations.dart:179:35)
         <asynchronous suspension>
         #3      SentryClient._processEvent (package:sentry/src/sentry_client.dart:353:26)
         <asynchronous suspension>
         #4      SentryClient.captureTransaction (package:sentry/src/sentry_client.dart:305:27)
         <asynchronous suspension>
         #5      Hub.captureTransaction (package:sentry/src/hub.dart:489:22)
         <asynchronous suspension>
         #6      SentryTracer.finish (package:sentry/src/sentry_tracer.dart:123:7)
         <asynchronous suspension>
         #7      new SentryTracer.<anonymous closure> (package:sentry/src/sentry_tracer.dart:62:9)
         <asynchronous suspension>
```

I am running iOS simulator
```
iOS 14 Pro Max, iOS 16.0
Version 14.0.1 (986.3)
SimulatorKit 624
CoreSimulator 857.7
```

**Actual result:**

Here is the `data` json showing the string for screen_width_pixels (and screen_height_pixels) as a double value.

```
result = {_InternalLinkedHashMap} size = 3
 0 = {map entry} "os" -> [_InternalLinkedHashMap]
 1 = {map entry} "device" -> [_InternalLinkedHashMap]
  key = "device"
  value = {_InternalLinkedHashMap} size = 14
   0 = {map entry} "boot_time" -> "2022-10-03T12:57:05Z"
   1 = {map entry} "model_id" -> "simulator"
   2 = {map entry} "free_memory" -> 329793536
   3 = {map entry} "storage_size" -> 994662584320
   4 = {map entry} "family" -> "iOS"
   5 = {map entry} "screen_height_pixels" -> 932.0
   6 = {map entry} "simulator" -> true
   7 = {map entry} "free_storage" -> 344491159552
   8 = {map entry} "screen_width_pixels" -> 430.0
   9 = {map entry} "locale" -> "en_US"
   10 = {map entry} "arch" -> "arm64"
   11 = {map entry} "memory_size" -> 17179869184
   12 = {map entry} "model" -> "iPhone15,3"
   13 = {map entry} "usable_memory" -> 8835383296
 2 = {map entry} "app" -> [_InternalLinkedHashMap]
```

**Expected result:**
No Exception

**Comment by marandaneto** [comment]
Already fixed since https://github.com/getsentry/sentry-dart/releases/tag/6.12.0
