### ISSUE TITLE
Replace StackTrace.empty with StackTrace.current

### ISSUE THREAD

**Issue by ueman** [getsentry/sentry-dart#1083]
When a user passes `StackTrace.empty` Sentry should automatically use `StackTrace.current` instead. An empty stacktrace doesn't contain any frames so you get pretty useless stacktraces. By using the current stacktrace instead, you can at least get a frame of whereever it was passed to Sentry.

An empty stacktrace is for example sometimes passed into the onError callback of stream listeners.

**Comment by marandaneto** [comment]
@ueman makes sense, wondering if somebody is passing `StackTrace.empty` purposely tho.

**Comment by ueman** [comment]
Yeah, I do wonder that too, but at least I only see instances where I don't want an empty stacktrace. Maybe hide it behind an option?

**Comment by marandaneto** [comment]
@ueman can you link me to examples where `StackTrace.empty` was purposely passed? I'm interested in learning why this is even a thing, the most important part of an error event is the stack trace, so I'm unsure if this has to be fixed here rather than where `StackTrace.empty` is being passed.

**Comment by ueman** [comment]
I'm seeing that for [`stream.handleError`](https://api.dart.dev/stable/2.18.3/dart-async/Stream/handleError.html):

```dart
stream.handleError((Object exception, StackTrace stackTrace) {
  // stackTrace is StackTrace.empty sometimes
});
```

And then you don't even know it's coming from that callback

**Comment by marandaneto** [comment]
> The stack trace argument may be [StackTrace.empty](https://api.dart.dev/stable/2.18.3/dart-core/StackTrace/empty-constant.html) if this stream received an error without a stack trace.

I see, that makes sense.

> you can at least get a frame of whereever it was passed to Sentry.

If this is the case, I am all in for this change.
Feel free to submit a PR :D

**Comment by marandaneto** [comment]
This would probably be done here https://github.com/getsentry/sentry-dart/blob/b47809a5f032149d70c9c8cdc226a1b71189ae88/dart/lib/src/sentry_exception_factory.dart#L30-L37
So if stack trace is `StackTrace.empty` and the flag is enabled, we also fallback to `StackTrace.current`
