### ISSUE TITLE
Device details are not appearing in the context of the issue. We are not using split-debug-infoe and obfuscate

### ISSUE THREAD

**Issue by brunobls** [getsentry/sentry-dart#1085]
_Platform:_
- [ ]  Dart
- [X]  Flutter Android or iOS
- [ ]  Flutter Web

_IDE:_
- [X]  VSCode
- [ ]  IntelliJ/AS
- [ ]  XCode
- [ ]  Other, which one?

_split-debug-info and obfuscate (Flutter Android or iOS) or CanvasKit (Flutter Web):_
- [ ]  Enabled
- [X]  Disabled

_Platform installed with:_
- [X] pub.dev
- [ ] GitHub

Output of the command `flutter doctor -v` below:
[√] Flutter (Channel stable, 3.3.4, on Microsoft Windows [Version 10.0.22000.1098], locale en-US)
    • Flutter version 3.3.4 on channel stable at C:\Users\USER\fvm\default
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision eb6d86ee27 (2 weeks ago), 2022-10-04 22:31:45 -0700
    • Engine revision c08d7d5efc
    • Dart version 2.18.2
    • DevTools version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\USER\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2021.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] VS Code (version 1.72.2)
    • VS Code at C:\Users\bruno\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.50.0

[√] Connected device (4 available)
    • AOSP on IA Emulator (mobile) • emulator-5554 • android-x86    • Android 9 (API 28) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.22000.1098]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 106.0.5249.119
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 106.0.1370.47

[√] HTTP Host Availability
    • All required HTTP hosts are available

The output goes here...

The version of the SDK (See pubspec.lock):
**6.13.0**

---
I have the following issue:
Device details are not appearing in the context of the issue. We are not using split-debug-infoe and obfuscate. 

**Steps to reproduce:**
  await Sentry.init(
    (options) {
      options.dsn = ...
    },
  );

  try {
    throw Exception("Exception");
  } catch (exception, stackTrace) {
    await Sentry.captureException(
      exception,
      stackTrace: stackTrace,
    );
  }

**Actual result:**
- Device details are not appearing in the context of the issue. 

**Expected result:**
- Result

**Comment by ueman** [comment]
Are you using `sentry` or `sentry_flutter`?

**Comment by marandaneto** [comment]
https://docs.sentry.io/platforms/flutter/#configure
You have to use `SentryFlutter.init`

**Comment by brunobls** [comment]
No, I was using Sentry.init. Thanks @marandaneto
