### ISSUE TITLE
About data collect

### ISSUE THREAD

**Issue by anchaoLu** [getsentry/sentry-dart#1096]
### Description

After import Sentry_flutter, our app was rejected by China XiaoMi market. This is the reason
<img width="891" alt="MicrosoftTeams-image" src="https://user-images.githubusercontent.com/106209730/198427464-7d81bdd7-c666-40e4-a4b8-027c8f52e5aa.png">
Why Sentry collect sensor?
How do I resolve this?

**Comment by marandaneto** [comment]
@anchaoLu can you translate for us and give more context?
See our docs page related to that https://docs.sentry.io/product/security/mobile-privacy/

**Comment by marandaneto** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
