### ISSUE TITLE
Transactions do not get finished

### ISSUE THREAD

**Issue by Wizzel1** [getsentry/sentry-dart#1103]
_Platform:_
- [ ]  Dart
- [x]  Flutter Android or iOS
- [ ]  Flutter Web

_IDE:_
- [x]  VSCode
- [ ]  IntelliJ/AS
- [ ]  XCode
- [ ]  Other, which one?

_split-debug-info and obfuscate (Flutter Android or iOS) or CanvasKit (Flutter Web):_
- [ ]  Enabled
- [x]  Disabled

_Platform installed with:_
- [x] pub.dev
- [ ] GitHub

Output of the command `flutter doctor -v` below:

[✓] Flutter (Channel stable, 3.3.7, on macOS 12.6 21G115 darwin-x64, locale de-DE)
    • Flutter version 3.3.7 on channel stable at /Users/chris/fvm/versions/3.3.7
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e99c9c7cd9 (3 days ago), 2022-11-01 16:59:00 -0700
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/chris/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.73.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.52.0

[✓] Connected device (3 available)
    • iPad (mobile) • 00008027-000C58A13487002E • ios            • iOS 15.7 19H12
    • macOS (desktop)             • macos                     • darwin-x64     • macOS 12.6 21G115 darwin-x64
    • Chrome (web)                • chrome                    • web-javascript • Google Chrome 107.0.5304.87

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

The version of the SDK (See pubspec.lock):
**4.x.x**

---
I have the following issue:

I am trying to use transactions to test my Flutter App's performance: 

```dart

class SentryService {
  void init(){
    await SentryFlutter.init(
      (options) {
      options.dsn = 'mydns';
      });
  }

  ISentrySpan startTransaction(String name, String operation){
    return Sentry.startTransaction(name, operation);
  } 
}
```

but when I do something like this and check transaction.finished, it returns false. 

```dart 
final transaction = SentryService.startTransaction('Test','test');
await transaction.finish();
print(transaction.finished); //false
````

Why does the transaction not get finished?

EDIT: I am using this setup to capture exceptions which works as expected, so I guess there is nothing wrong with the initialization.

**Comment by marandaneto** [comment]
@Wizzel1 can you provide the version of the SDK?
Are you creating child spans out of the transaction? Such as `transaction.startChild('...')`?

**Comment by Wizzel1** [comment]
@marandaneto I am using sentry_flutter 6.14.0.

I have tried both 

```dart
final transaction = Sentry.startTransaction();
await transaction.finish();
print(transaction.finished); //false
``` 
and 

```dart
final parent = Sentry.startTransaction();
final child = parent.startChild();
await child.finish();
print(child.finished); //false
```

**Comment by marandaneto** [comment]
@Wizzel1 can you provide a minimal reproducible example?
I can't reproduce this.
Worth checking that your Sentry SDK init code snippet does not set a `tracesSampleRate` so the performance feature is even disabled in the first place.
https://docs.sentry.io/platforms/flutter/performance/

**Comment by Wizzel1** [comment]
@marandaneto there you go. 

```dart
import 'package:flutter/material.dart';
import 'package:sentry_flutter/sentry_flutter.dart';

Future<void> main() async {
  await SentryFlutter.init(
    (options) {
      options.dsn = mydsn;
    },
  );
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              'Test',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () async {
          final transaction = Sentry.startTransaction('Test', 'test');
          await transaction.finish();
          print(transaction.finished);
        },
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}
```

**Comment by Wizzel1** [comment]
@marandaneto well, I guess my setup is wrong... 
Leaves me wondering why the error capturing works. 

Anyways, thanks for looking into my request. Closing this.
