### ISSUE TITLE
Checks in some tests are broken

### ISSUE THREAD

**Issue by vaind** [getsentry/sentry-dart#1122]
I've noticed while working on recent PRs that test code sometimes uses `expect()` and other types of assertions in callbacks to Sentry. E.g. Sentry.init() - these are broken and are actually not being checked at all because Sentry swallows these errors (doesn't propagate them). Minimal repro - the following test passes:

```dart
  test('should fail', () async {
    await Sentry.init((options) {
      fail('hello there');
    }, options: SentryOptions(dsn: fakeDsn));
  });
```

Besides a testing issue, this may also be a design problem - naively, as a User, I'd expect exceptions in user-provided code to be propagated.

**Comment by ueman** [comment]
Related https://github.com/getsentry/sentry-dart/pull/990

**Comment by marandaneto** [comment]
@vaind Sentry should swallow every exception when a user makes a mistake in the callbacks, that's intended and by design.
We'd need to fix those tests for sure, mind checking this out? or giving an example (a test's name)?

**Comment by marandaneto** [comment]
> Related #990

Likely an oversight because of PRs related to this, indeed.

**Comment by marandaneto** [comment]
> @vaind Sentry should swallow every exception when a user makes a mistake in the callbacks, that's intended and by design. We'd need to fix those tests for sure, mind checking this out? or giving an example (a test's name)?

@vaind in case you remember where you have seen this.

**Comment by vaind** [comment]
e.g. multiple calls to `await Sentry.init(` in `sentry_test.dart` have test assertions inside the callback

**Comment by vaind** [comment]
I'd suggest having a test-mode/dev-mode setting where exceptions are not captured in callbacks. This would could also help users if they're having trouble with reporting some errors, as it's much easier to find errors this way than look for logs.
