### ISSUE TITLE
No way to disable Android inegration (`TempSensorBreadcrumbsIntegration`), making app rejected

### ISSUE THREAD

**Issue by fzyzcjy** [getsentry/sentry-dart#1129]
_Platform:_
- [ ]  Dart
- [x]  Flutter Android or iOS
- [ ]  Flutter Web

_IDE:_
- [ ]  VSCode
- [ ]  IntelliJ/AS
- [ ]  XCode
- [ ]  Other, which one?

_split-debug-info and obfuscate (Flutter Android or iOS) or CanvasKit (Flutter Web):_
- [ ]  Enabled
- [ ]  Disabled

_Platform installed with:_
- [ ] pub.dev
- [ ] GitHub

Output of the command `flutter doctor -v` below:

The output goes here...

The version of the SDK (See pubspec.lock):
**4.x.x**

---
I have the following issue:

The `TempSensorBreadcrumbsIntegration` is reading BODY_SENSORS information (while I do not need it), and the app is rejected by stores due to reading privacy data. Therefore, I would appreciate it if there is a way to disable this integration.

The description goes here ...

**Steps to reproduce:**
- Step

**Actual result:**
- Actual

**Expected result:**
- Result

**Comment by marandaneto** [comment]
@fzyzcjy you can disable it on Android directly https://docs.sentry.io/platforms/android/enriching-events/breadcrumbs/#disable-automatic-breadcrumbs
See the `io.sentry.breadcrumbs.system-events` entry, or `enableAutoNativeBreadcrumbs` on Flutter directly.
Which store is rejecting it? the temperature should not be PII.

**Comment by fzyzcjy** [comment]
> Which store is rejecting it? the temperature should not be PII.

Tencent store (with ~1 billion target users where google play is banned). It says sentry is reading BODY_SENSORS (though I think indeed it is not), and provides this stack trace:

```
android.hardware.SensorManager.getSensorList(int)
android.hardware.SensorManager.getDefaultSensor(SensorManager.java:490)
io.sentry.android.core.TempSensorBreadcrumbsIntegration.register(SourceFile:9)
io.sentry.Sentry.init(SourceFile:24)
io.sentry.Sentry.init(SourceFile:6)
io.sentry.android.core.SentryAndroid.init(SourceFile:7)
io.sentry.android.core.SentryAndroid.init(SourceFile:3)
io.sentry.flutter.SentryFlutterPlugin.initNativeSdk(SourceFile:6)
io.sentry.flutter.SentryFlutterPlugin.onMethodCall(SourceFile:2)
io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(SourceFile:2)
io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(SourceFile:2)
io.flutter.embedding.engine.dart.DartMessenger.a(SourceFile:2)
io.flutter.embedding.engine.dart.DartMessenger.b(Unknown Source:0)
i.a.a.b.b.a.run(Unknown Source:12)
android.os.Handler.handleCallback(Handler.java:873)
java.lang.reflect.Method.invoke(Native Method)

**Comment by fzyzcjy** [comment]
> See the io.sentry.breadcrumbs.system-events entry

Thanks! However, will this also remove many other types of events as well? I only want to remove that one, while other many events should still exist

**Comment by marandaneto** [comment]
Yes, it will remove all the system events crumbs, so `PhoneStateBreadcrumbsIntegration` and `SystemEventsBreadcrumbsIntegration` won't work either, we don't have a specific flag for `TempSensorBreadcrumbsIntegration`, maybe we can introduce one specifically for this case if this is more of a general problem, more granular fields is fine if its needed.
You can also do this https://docs.sentry.io/platforms/flutter/native-init/
and remove the `SystemEventsBreadcrumbsIntegration` from the integrations list manually on the Android SDK.

**Comment by fzyzcjy** [comment]
Thank you. So when will we ave that flag? Looking forward to it!

**Comment by fzyzcjy** [comment]
> maybe we can introduce one specifically for this case if this is more of a general problem, more granular fields is fine if its needed

@marandaneto Hi I am going to make a PR to introduce this when having time :)
