### ISSUE TITLE
How to set SocketTimeout longer

### ISSUE THREAD

**Issue by philos3** [getsentry/sentry-dart#1149]
Caused by: java.net.SocketTimeoutException: failed to connect to XXXX/XX.XX.130.150 (port 443) from /XX.XX.3.122 (port 41780) after 5000ms

how can I set SocketTimeout longger

**Comment by marandaneto** [comment]
@philos3 are you using `sentry` or `sentry_dart`?
If `sentry`, that's not possible since https://pub.dev/packages/http does not support this configuration.
If `sentry_flutter`, we'd need to expose these 2 configs on the Dart SDK first.
https://github.com/getsentry/sentry-java/blob/4a9c176e62e67746928d2d4ab455330cdb879c83/sentry/src/main/java/io/sentry/SentryOptions.java#L241
Would you like to submit a PR?

**Comment by marandaneto** [comment]
I suspect iOS does not have such configurations, it might be needed to be exposed first (`NSURLSessionConfiguration`).
@philipphofmann or @brustolin to confirm.

**Comment by brustolin** [comment]
We will need to expose this property first in Cocoa SDK. But its possible.

**Comment by philipphofmann** [comment]
I would like to understand your underlying problem, @philos3. When do you get the error? Why do you think you can solve it by increasing the socket timeout?

**Comment by marandaneto** [comment]
> SocketTimeoutException

Well if you have an unstable connection, maybe 5s (default) isn't enough for a big portion of your customers, it's a known problem worldwide, so it should be at least configurable, obviously, this is remediation.

**Comment by philipphofmann** [comment]
> Well if you have an unstable connection, maybe 5s (default) isn't enough for a big portion of your customers, it's a known problem worldwide, so it should be at least configurable, obviously, this is remediation.

I think we should come up with a solution that works out of the box. We should guarantee that the SDKs send the events to Sentry under such conditions. I think we shouldn't solve this problem by making it configurable.

**Comment by marandaneto** [comment]
@philipphofmann I'm not sure I follow your comment, we cannot do much, the problem isn't in the SDK, it's in people's connection.
This is the OS trying to connect to the host.

**Comment by philos3** [comment]
>5000ms  was too short in unstable connection ,and  my network is fine. It's just because of a timeout, so i wish I can set the timeout config myself

**Comment by philipphofmann** [comment]
> the problem isn't in the SDK, it's in people's connection.

Yes, but we could use a longer socket timeout if we get a `SocketTimeoutException`, or maybe retry.

**Comment by philos3** [comment]
this SocketTimeoutException is cause by the sentry sdk when in unstable connection. Sentry fail to report after 5000ms,and throw SocketTimeoutException(default 5000ms,I can't do anything) ,it is not my business code SocketTimeoutException，so  I wish to set sentry SDK  SocketTimeout longer ,maybe 7s can avoid receiving a lot of SocketTimeoutException

**Comment by marandaneto** [comment]
Created https://github.com/getsentry/sentry-cocoa/issues/2658

**Comment by philipphofmann** [comment]
The default timeout of NSURLSession is 60 seconds. So I don't think this is an issue on iOS. Can't we increase the default value on Java to solve this issue for all users instead of exposing options to configure? The option has the downside of users having to be aware of it and we need to maintain it.

**Comment by marandaneto** [comment]
We can add those 2 values on `SentryFlutterOptions` and add property docs that this is Android only, iOS is 60s by default.
