### ISSUE TITLE
Min Dart SDK version

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dart#115]
We're releasing 4.0.0 which is a big major version so it's time to discuss the min Dart SDK version we want to support on the `sentry` package.

Important notes:

* Dart just released 2.10
* Extension methods were [introduced on 2.7](https://dart.dev/guides/language/extension-methods)
* [2.7 was introduced in December 2019](https://github.com/dart-lang/sdk/blob/master/CHANGELOG.md#270---2019-12-11)
* Flutter's new releases often update to the latest Dart SDK version
  * i.e: _Version note: As of Flutter 1.21, the Flutter SDK includes the full Dart SDK. This site’s documentation and examples use version 2.10.0 of the Dart SDK._

I'd propose we set the min version to 2.7:

https://github.com/getsentry/sentry-dart/blob/cc913bf8902fbd0e41d39af9c7235a0f246d9dd1/dart/pubspec.yaml#L9

To clarify: What would we leaving behind? Is there a reason folks using AngularDart can't be on Dart 2.7?

**Comment by rxlabz** [comment]
FYI Angular is now using Dart >= 2.8.4 https://github.com/dart-lang/angular/blob/master/angular/pubspec.yaml
I think we can/should upgrade to 2.7 (at least).
And as we started to prepare the NNBD, we'll need to move to the last SDK version if we want to use it.

**Comment by marandaneto** [comment]
> we'll need to move to the last SDK version if we want to use it.

this goes heavily against https://develop.sentry.dev/sdk/philosophy/#compatibility-is-king

I'm all in for new features, but if it breaks a good amount of people, I prefer to keep using https://pub.dev/packages/meta at least for a few more months after NNBD being GA, and also checking how NNBD deals with 3rd parties that are not NNBD ready, I guess this will be common for a while

**Comment by bruno-garcia** [comment]
> but if it breaks a good amount of people,

Please confirm this claim. My understanding is that we will not break a good amount of people.

**Comment by bruno-garcia** [comment]
> we'll need to move to the last SDK version if we want to use it.

Yeah, last version is just not an option.

I noticed other packages have a second package name with `nullability` on the name or something?

Sounds easier for us to just wait out on this, it seems.

**Comment by bruno-garcia** [comment]
I opened a poll, lets see if we get enough data:

https://twitter.com/brungarc/status/1318947753620348934?s=20

**Comment by rxlabz** [comment]
almost all the Dart team packages (http, meta, path, ...) are now  >= 2.10 and are prepared to NNBD https://pub.dev/dart/packages?sort=popularity

**Comment by bruno-garcia** [comment]
That's a very compelling reason to go for 2.10 🤐

**Comment by marandaneto** [comment]
https://github.com/getsentry/sentry-dart/releases/tag/4.0.0-alpha.2
Breaking changes section states the minSDK for Dart and Flutter
