### ISSUE TITLE
Flutter web source maps - file structure and files showing in chrome console

### ISSUE THREAD

**Issue by kenNg1** [getsentry/sentry-dart#1153]
_Platform:_
- [x]  Flutter Web

CanvasKit (Flutter Web) enabled

Not exactly a bug but more of a data sensitivity issue. Sentry flutter web currently uploads the source maps e.g. below, and you can see every filename in our repo. Is there any way to prevent this from happening while ensuring errors can be traced in Sentry issues viewer?

Chrome sources tab:

![image](https://user-images.githubusercontent.com/25297786/204002774-dcaae477-0080-44c3-8fb5-6048455b0528.png)

**Comment by marandaneto** [comment]
@kenNg1 if you want to see symbolicated (demangled) names with proper class, function, and line numbers, you need source maps, unfortunately.
Maybe try to check if Flutter web has a build type without minification.
