### ISSUE TITLE
how to test verify , i have no idea to make an error

### ISSUE THREAD

**Issue by yogithesymbian** [getsentry/sentry-dart#1154]
as mention on documentation
```
import 'package:sentry/sentry.dart';

try {
  aMethodThatMightFail();
} catch (exception, stackTrace) {
  await Sentry.captureException(
    exception,
    stackTrace: stackTrace,
  );
}
```
we can use the code, but when i tried , my flutter doesnt or cannot compile for undefined method. its throw on auto reload of flutter. any other solution ???

**Comment by marandaneto** [comment]
https://docs.sentry.io/platforms/dart/ should be all you need or even https://pub.dev/packages/sentry/install
In case you find any issues, please reopen the issue but first fill up the issue description with all the required info from the template https://github.com/getsentry/sentry-dart/issues/new?assignees=&labels=Platform%3A+Dart%2Cbug&template=BUG_REPORT.md
