### ISSUE TITLE
Migrate Cocoa to v8

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-dart#1161]
### Description

Latest is https://github.com/getsentry/sentry-cocoa/releases/tag/8.0.0-beta.3
There are a few breaking changes and it requires a major bump.

**Comment by marandaneto** [comment]
@philipphofmann @brustolin ideas for the `effort` label here?
Looking forward to getting a [migration page](https://docs.sentry.io/platforms/apple/migration/) so its easier to estimate that.

**Comment by philipphofmann** [comment]
I would say small to medium. We are going to create a migration page next week.

**Comment by marandaneto** [comment]
https://sentry-docs-git-fork-kevinrenskers-feat-sentry-cocoa-mig-fe5a3d.sentry.dev/platforms/apple/migration/

**Comment by marandaneto** [comment]
@denrase I've opened this PR on top of yours https://github.com/getsentry/sentry-dart/pull/1222
