### ISSUE TITLE
Bump Flutter min to 3.0.0 and Dart to 2.17.0

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-dart#1162]
### Description

We can unblock features such as https://github.com/getsentry/sentry-dart/issues/1053#issuecomment-1336485647 and use the new features of the language and framework.

**Comment by marandaneto** [comment]
Ideally, we check if new features from the Dart language can be used now and apply them in case that makes our code better/easier to use, better `enums` are one of them.

**Comment by ueman** [comment]
There's also some Flutter code which can be cleaned up, for example:
https://github.com/getsentry/sentry-dart/blob/6325c3bc20de79b73cce63c9391d768e47d33d87/flutter/lib/src/sentry_asset_bundle.dart#L177-L192
