### ISSUE TITLE
Option to discard uncatched issues

### ISSUE THREAD

**Issue by Simon-PumpAndUp** [getsentry/sentry-dart#1164]
Hey ! 

I've been using Flutter and Sentry together and it works very well, thank you! 

I'm using Amplify and it triggers a lot of PlatformExceptions and ApiExceptions that are not handled even though in my main I have the following to catch everything not caught by my code: 

```
FlutterError.onError = (details) {
      FlutterError.presentError(details);
}

 PlatformDispatcher.instance.onError = (e, stacktrace) {
      return true;
};
```

Therefore my Sentry issues are flooded with these types of events (with no stacktrace whereas all my try catch send the stacktrace). Would it be possible to init Sentry with a flag to not send uncaught errors?

Cheers !

**Comment by marandaneto** [comment]
You can filter them using https://docs.sentry.io/platforms/flutter/configuration/filtering/
Or you can also remove these integrations from the options by doing `options.removeIntegration(...)`.
