### ISSUE TITLE
`sentry_asset_bundle` uses `loadStructuredBinaryData` which has a breaking change in latest master channel

### ISSUE THREAD

**Issue by mario-jerkovic** [getsentry/sentry-dart#1166]
_Platform:_
- [ ]  Dart
- [x]  Flutter Android or iOS
- [ ]  Flutter Web

_IDE:_
- [ ]  VSCode
- [x]  IntelliJ/AS
- [ ]  XCode
- [ ]  Other, which one?

_split-debug-info and obfuscate (Flutter Android or iOS) or CanvasKit (Flutter Web):_
- [ ]  Enabled
- [X]  Disabled

_Platform installed with:_
- [X] pub.dev
- [ ] GitHub

Output of the command `flutter doctor -v` below:

```
[✓] Flutter (Channel master, 3.7.0-3.0.pre.37, on macOS 13.0.1 22A400 darwin-arm64, locale en-HR)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
```

The version of the SDK (See pubspec.lock):
**6.17.0**

---
I have the following issue:

After upgrading to latest flutter version from "master"  channel `3.7.0` application fails to compile and output error in console:
```
Could not build the precompiled application for the device.
Error (Xcode): ../../.pub-cache/hosted/pub.dev/sentry_flutter-6.17.0/lib/src/sentry_asset_bundle.dart:37:7: Error: The non-abstract class 'SentryAssetBundle' is missing implementations for these members:
```

Same thing happens on iOS and Android

**Steps to reproduce:**
- switch flutter channel to master `flutter channel master` and run `flutter upgrade`
- try to build the app on iOS or Android

**Actual result:**
- Error launching application

**Expected result:**
- Successful application build

**Comment by ueman** [comment]
This time it's https://master-api.flutter.dev/flutter/services/AssetBundle/loadStructuredBinaryData.html at fault.

I wonder if there's a way to somehow avoid failure die to interface changes in the future.

**Comment by marandaneto** [comment]
Yeah, that's hard to keep up, not sure if there's any alternative as well.
@mario-jerkovic as of now, you can either patch yourself manually or wait for this change to come at least into the beta channel, we can't maintain 3 versions of the SDK (per channel), it's quite a bit of work.

**Comment by ueman** [comment]
I think this can be fixed just like this method: https://github.com/getsentry/sentry-dart/blob/6325c3bc20de79b73cce63c9391d768e47d33d87/flutter/lib/src/sentry_asset_bundle.dart#L194-L235 That way it should be compatible with the current stable as well was with the master channel

**Comment by marandaneto** [comment]
I tried but linter didnt allow me, let me double check.

**Comment by ueman** [comment]
Something like the following should work
```dart
 @override 
 // This is an override on Flutter greater than xxx
 // ignore: override_on_non_overriding_member 
 Future<T> loadStructuredBinaryData(String key, FutureOr<T> Function(ByteData data) parser) async { 
   final span = _hub.getSpan()?.startChild( 
         'file.read', 
         description: 'AssetBundle.loadStructuredBinaryData: ${_fileName(key)}', 
       ); 
  
   span?.setData('file.path', key); 
  
   T data; 
   try { 
     data = await _loadStructuredBinaryData(key, parser); 
     _setDataLength(data, span); 
     span?.status = SpanStatus.ok(); 
   } catch (exception) { 
     span?.throwable = exception; 
     span?.status = SpanStatus.internalError(); 
     rethrow; 
   } finally { 
     await span?.finish(); 
   } 
   return data; 
 } 
 
 // helper method to have a "typesafe" method
 Future<ImmutableBuffer> _loadStructuredBinaryData(String key, FutureOr<T> Function(ByteData data) parser) { 
     // maybe add some error handling here
     // but it's probably not needed, as you wouldn't call this method on earlier flutter versions
     return (_bundle as dynamic).loadStructuredBinaryData(key, parser); 
 } 
```
or the following would also work by not calling the inner asset bundle:

```dart
 @override 
 // This is an override on Flutter greater than xxx
 // ignore: override_on_non_overriding_member 
Future<T> loadStructuredBinaryData<T>(String key, FutureOr<T> Function(ByteData data) parser) async {
     final span = _hub.getSpan()?.startChild( 
         'file.read', 
         description: 'AssetBundle.loadStructuredBinaryData: ${_fileName(key)}', 
       ); 
  
   span?.setData('file.path', key); 
  
   T data; 
   try { 
     final ByteData data = await load(key);
     if (data == null) {
       throw FlutterError('Unable to load asset: $key');
     }
     data = await parser(data);
     _setDataLength(data, span); 
     span?.status = SpanStatus.ok(); 
   } catch (exception) { 
     span?.throwable = exception; 
     span?.status = SpanStatus.internalError(); 
     rethrow; 
   } finally { 
     await span?.finish(); 
   } 
   return data; 
}
```

**Comment by marandaneto** [comment]
Thanks @ueman 
@mario-jerkovic would you like to open a PR and try this out?

**Comment by marandaneto** [comment]
`loadStructuredBinaryData` has been removed already.
https://github.com/flutter/flutter/commit/7673108d7eeebd9d1558535ea7a1cf94877a0c4e
So closing it for now.

**Comment by ueman** [comment]
I bet it's coming back soon

**Comment by ueman** [comment]
It's about to be re-landed https://github.com/flutter/flutter/pull/116684

**Comment by volgin** [comment]
I see this issue today on a master channel. Tried with both 6.20.1 and sentry 7.0.0-beta.4:

`Error (Xcode): ../../.pub-cache/hosted/pub.dev/sentry_flutter-6.20.1/lib/src/sentry_asset_bundle.dart:37:7: Error: The non-abstract class 'SentryAssetBundle' is missing implementations for these members:`
