### ISSUE TITLE
Set RN metadata to `sentry_client` on Native SDKs

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-dart#1185]
### Description

Context https://github.com/getsentry/team-mobile/issues/48
iOS should use `PrivateSentrySDKOnly#setSdkName` and Android `Options#setSentryClientName`
For iOS, it requires upgrading to [v8](https://github.com/getsentry/sentry-dart/issues/1161)

**Comment by marandaneto** [comment]
The goal is that the Native SDKs use the SDK name and version from the Hybrid SDK.

**Comment by krystofwoldrich** [comment]
I think this should be reopened as the way how we name the native SDKs changed.
- https://github.com/getsentry/team-mobile/issues/48#issuecomment-1425726754
