### ISSUE TITLE
Doc s/example for new `http` API `runWithClient`

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-dart#1192]
### Description

https://pub.dev/documentation/http/latest/http/runWithClient.html
Example: https://pub.dev/packages/cupertino_http

So you can technically create a single Sentry HTTP Client and set it as global.

**Comment by ueman** [comment]
According to https://github.com/dart-lang/http/issues/828 it doesn't quite work that well for Flutter. It still works for pure Dart though.
