### ISSUE TITLE
Can I get transaction figures from the app?

### ISSUE THREAD

**Issue by myeongseop-sofit** [getsentry/sentry-dart#1195]
Can I get transaction figures from the app?

**Comment by marandaneto** [comment]
What do you mean? Mind explaining?

**Comment by marandaneto** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!

**Comment by myeongseop-sofit** [comment]
@marandaneto 
I wonder if there is an Api that receives log information such as transactions from the Performance tab.

**Comment by ueman** [comment]
There's https://docs.sentry.io/api/ but I don't know whether it covers your use case.

**Comment by myeongseop-sofit** [comment]
I saw the API document, but I couldn't find the API. @ueman

**Comment by marandaneto** [comment]
I don't think we have some similar to https://docs.sentry.io/api/events/ but only for transactions.
Maybe you can use https://docs.sentry.io/api/discover/query-discover-events-in-table-format/ with the `query` param.
Please raise an issue on https://github.com/getsentry/sentry for APIs or API docs questions.
