### ISSUE TITLE
Allow sentry user to control resolution of captured Flutter screenshots

### ISSUE THREAD

**Issue by cstavitsky** [getsentry/sentry-dart#1200]
Feature request: Allow Sentry users to control the resolution at which Flutter [screenshots are captured by Sentry](https://docs.sentry.io/platforms/flutter/enriching-events/screenshots/), allow the Sentry user to control the resolution at which screenshots are captured.

For example, Sentry's Unity SDK currently allows users to select among:
- as is
- high - 1920p
- medium - 720p
- low - 420p

The request is to allow similar choice in resolution for Flutter screenshots. 

- There is concern that larger-resolution screenshots may cause bandwidth problems for events captured on low-end mobile devices and regions with poor cellular connectivity. The thought is that being able to adjust resolution would help with this.

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-1695) by [Unito](https://www.unito.io)

**Comment by marandaneto** [comment]
We can add the max resolution to `SentryFlutterOptions` and allow users to change it during SDK init.
https://api.flutter.dev/flutter/rendering/RenderRepaintBoundary/toImage.html
Maybe the `pixelRatio` is enough, if not, we can likely manipulate the returned `Image`.
IIRC Unity has this already, so let's align on the naming and format @bitsandfoxes if possible.

**Comment by bitsandfoxes** [comment]
> IIRC Unity has this already, so let's align on the naming and format @bitsandfoxes if possible.

The Unity SDK went with [`ScreenshotQuality`](https://github.com/getsentry/sentry-unity/blob/03c8db1c80eb40c6fd2ec3bf57ada1b738667301/src/Sentry.Unity/SentryUnityOptions.cs#L268)
```
public enum ScreenshotQuality
{
    Full,
    High,
    Medium,
    Low
}
```
Which [translates](https://github.com/getsentry/sentry-unity/blob/d1c049150eae6a3f6fe0a530e24a3fe8ef84c3cf/src/Sentry.Unity/ScreenshotAttachment.cs#L41) into max dimension while keeping the aspect ratio
```
return quality switch
{
    ScreenshotQuality.High => 1920,     // 1080p
    ScreenshotQuality.Medium => 1280,   // 720p
    ScreenshotQuality.Low => 854,       // 480p
    _ => 854                            // Fallback
};
```
