### ISSUE TITLE
Investigate FFI based libs for APM Support

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-dart#1204]
### Description

Example https://pub.dev/packages/realm and https://pub.dev/packages/isar
The goal is to find out if there's a way to hook up into the FFI system and intercept before & after calls via FFI.

**Comment by marandaneto** [comment]
The idea would be to do something similar to `BinaryMessenger` for [MethodChannels](https://github.com/ueman/sentry-dart-tools/blob/main/sentry_flutter_plus/lib/src/method_channel/sentry_binary_messenger.dart), but for FFI.

**Comment by marandaneto** [comment]
@ueman any ideas if this is even possible? I've not dug thru the code yet, just collecting ideas.

**Comment by ueman** [comment]
No clue, but I'm guessing that it's not possible

**Comment by marandaneto** [comment]
I've not found any way either, the only option is offering 1st class support for each library
