### ISSUE TITLE
Allow to access installationId

### ISSUE THREAD

**Issue by M123-dev** [getsentry/sentry-dart#1205]
From the docs https://docs.sentry.io/platforms/dart/enriching-events/identify-user/

> If you don't provide an id, the SDK falls back to installationId, which the SDK randomly generates once during an app's installation

It would be great if there'd be a way to access thid id. If I understood it correctly, it is possible to set a own SentryUser with a custom uuid instead, but this would destroy all previous user records.

**Comment by marandaneto** [comment]
If you set an user without the "id", the installationId is merged with your user before the event is sent, its a quick workaround for now.

**Comment by M123-dev** [comment]
That would be good, sadly this doesn't seem to work for me

``` dart
    String? sentryId = 'error';
    await Sentry.configureScope((Scope s) => s.setUser(SentryUser()));
    await Sentry.captureMessage('Test message');
    await Sentry.configureScope((Scope s) => sentryId = s.user?.id.toString());
    print(sentryId);
```
`I/flutter (12272): null`

**Comment by kuhnroyal** [comment]
Try to inspect it in the `beforeSend` callback, thats when it should be there.

**Comment by marandaneto** [comment]
Relates to https://github.com/getsentry/team-mobile/issues/11 as well since the data is not in the `beforeSend` for Android.

**Comment by marandaneto** [comment]
Closing in favor of https://github.com/getsentry/sentry-dart/issues/1556 which will address this.
