### ISSUE TITLE
Upgrade intl dependency

### ISSUE THREAD

**Issue by blaneyneil** [getsentry/sentry-dart#1206]
sentry_flutter: ^6.18.1 currently depends upon intl ^0.17.0 but the latest version is 0.18.0.  This is blocking other package upgrades.

**Comment by marandaneto** [comment]
Related to https://github.com/getsentry/sentry-dart/pull/1202#discussion_r1054372011

**Comment by marandaneto** [comment]
https://github.com/getsentry/sentry-dart/releases/tag/6.19.0
