### ISSUE TITLE
Package interoperability with Apple Watch targets

### ISSUE THREAD

**Issue by stx** [getsentry/sentry-dart#1211]
_Platform:_
- [ ]  Dart
- [x]  Flutter Android or iOS
- [ ]  Flutter Web

_IDE:_
- [x]  VSCode
- [ ]  IntelliJ/AS
- [ ]  XCode
- [ ]  Other, which one?

_split-debug-info and obfuscate (Flutter Android or iOS) or CanvasKit (Flutter Web):_
- [ ]  Enabled
- [x]  Disabled

_Platform installed with:_
- [x] pub.dev
- [ ] GitHub

Output of the command `flutter doctor -v` below:

```
[✓] Flutter (Channel stable, 3.3.10, on macOS 13.1 22C65 darwin-arm, locale en-US)
    • Flutter version 3.3.10 on channel stable at /Users/james/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (2 weeks ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/james/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.74.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.52.0

[✓] Connected device (3 available)
    • Apollo (mobile) • 00008110-0004752E3AB8801E • ios            • iOS 16.2 20C65
    • macOS (desktop) • macos                     • darwin-arm64   • macOS 13.1 22C65 darwin-arm
    • Chrome (web)    • chrome                    • web-javascript • Google Chrome 108.0.5359.71

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

The version of the SDK (See pubspec.lock):
**6.18.1**

---
I have the following issue:

We have both Flutter code and non-Flutter code that we want to be covered by Sentry. Sentry is installed with sentry_flutter via pub.dev and works perfectly.

When using `import Sentry` in `AppDelegate.swift`, Xcode will give the error `No such module 'Sentry'`.

When explicitly including the module via `pod 'Sentry'` in the Runner target in Podfile, the above error disappears. However, Xcode will throw an error `Multiple commands produce 'Sentry.framework'` error during compile.

How can we use Sentry in both Flutter and Swift?

**Steps to reproduce:**

1. Install sentry_flutter via pub.dev
2. Write `import Sentry` in AppDelegate.swift
3. Get `No such module` error

**Comment by marandaneto** [comment]
@stx this [example](https://github.com/getsentry/sentry-dart/blob/main/flutter/example/ios/Runner/AppDelegate.swift) does exactly that and it works normally, mind providing a minimal reproducible example? I believe its an environment issue.

**Comment by stx** [comment]
@marandaneto Thanks for providing that example repo, it helped narrow down the issue. The problem appears to be isolated to Apple Watch Xcode targets.

Reproduction @ https://github.com/stx/sentry-dart

Steps:
1. Clone sentry-dart repo.
2. Add Watch App target to Flutter example project.
3. Write `import Sentry` in WatchApp.swift.
4. Try to run the Watch App scheme on any device.
5. Get `No such module 'Sentry'`.

To fix `No such module 'Sentry'`, you can add this to `Podfile` and run `pod install`:

```
target 'Watch App' do
  platform :watchos, '7.0'
  use_frameworks!
  pod 'Sentry'
end
```

Now, Runner and Watch App will both run, but won't compile for distribution:

```
> flutter build ipa

Error (Xcode): Multiple commands produce
'[...]/Runner/IntermediateBuildFilesPath/Uninstalled Products/iphoneos/Sentry.framework'
```

**Comment by stx** [comment]
Fix found! The trick is to use `Sentry/HybridSDK`:

```
target 'Watch App' do
  platform :watchos, '7.0'
  use_frameworks!
  pod 'Sentry/HybridSDK'
end
```
