### ISSUE TITLE
options.beforeSend is the top level to control sending event or not

### ISSUE THREAD

**Issue by philos3** [getsentry/sentry-dart#1213]
I had set  captureFailedRequests  ture in dio.addSentry ,and  I also ignore  DioError in kReleaseMode with options.beforeSend by return null，but i still can  receive many DioError report in  sentry.  in my opinion， options.beforeSend is the top level to control sending event or not.

 
dio.addSentry(
            maxRequestBodySize: MaxRequestBodySize.always,
            maxResponseBodySize: MaxResponseBodySize.always,
            captureFailedRequests: true);

options.beforeSend = (
          SentryEvent event, {
          dynamic hint,
        }) {
          if (event.throwable is DioError) {
            if (kReleaseMode) {
              return null;
            }
}}

**Comment by marandaneto** [comment]
@philos3 this should work unless you or another library is wrapping the `DioError` into another error.
Can you provide a link to a sentry issue that demonstrate an error that should be ignored?

**Comment by philos3** [comment]
https://sentry.deepcoin.ski/share/issue/23fce3591cbf4cef99f7ddc195733c52/

**Comment by marandaneto** [comment]
@philos3 you are probably wrapping the exception into `AppHttpException` so that's why `DioError` won't work.
Try to do: `if (event.throwable is DioError || event.throwable is AppHttpException) {`

It's not an SDK issue, but rather a beforeSend business logic.

**Comment by philos3** [comment]
I finally figured out what the problem was because I was sending Sentry.captureException event direct，even though I was already return null  in options.beforeSend both for AppHttpException and DioError.

<img width="677" alt="image" src="https://user-images.githubusercontent.com/8424317/213899183-fbb92bbe-a3b3-44fb-88c2-de4263d1a49b.png">
<img width="650" alt="image" src="https://user-images.githubusercontent.com/8424317/213899210-decbaf4f-7860-4d47-91e0-afc057106107.png">

in my opinion，options.beforeSend  is the top level to control sending event @marandaneto
<img width="941" alt="image" src="https://user-images.githubusercontent.com/8424317/213899149-d0fbb1d1-41d1-4fc6-a911-95ebc89b1ae7.png">

https://sentry.deepcoin.ski/share/issue/cf72060543e54911855e2990b0652f53/
