### ISSUE TITLE
`sentry_file` should use Sentry publisher

### ISSUE THREAD

**Issue by ueman** [getsentry/sentry-dart#1214]
### Description

The file integration isn't published via the Sentry verified publisher. That should probably be changed.

**Comment by marandaneto** [comment]
Indeed, its published technically with the same token, not sure what happened, will take a look.

**Comment by ueman** [comment]
One can't directly upload packages to a verified publisher. They have to be transferred and then it works. But I don't know why it is like that.

**Comment by marandaneto** [comment]
https://pub.dev/packages/sentry_file done.
it was accidentally published with a personal ACC instead of the sentry.io ACC.
