### ISSUE TITLE
Stacktrace is unreadable for Flutter released app

### ISSUE THREAD

**Issue by abdo400** [getsentry/sentry-dart#1215]
_Platform:_
- [x]  Dart: 2.18.6
- [x]  Flutter Android or iOS: 3.3.10
- [ ]  Flutter Web

_IDE:_
- [x]  VSCode
- [ ]  IntelliJ/AS
- [ ]  XCode
- [ ]  Other, which one?

_split-debug-info and obfuscate (Flutter Android or iOS) or CanvasKit (Flutter Web):_
- [ ]  Enabled
- [x]  Disabled

_Platform installed with:_
- [x] pub.dev
- [ ] GitHub

Output of the command `flutter doctor -v` below:
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.3.10, on Microsoft Windows [Version 10.0.19041.804], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.1)
[√] Android Studio (version 4.0)
[√] VS Code (version 1.74.2)
[√] Connected device (3 available)
[√] HTTP Host Availability

• No issues found!

The version of the SDK (See pubspec.lock):
6.18.1

---
I have the following issue:
The errors stacktrace is unreadable for the released Android build. It was working during development. 
My build.gradle file looks like this
`buildTypes {
       release {
           signingConfig signingConfigs.release

            // Enables code shrinking, obfuscation, and optimization for only
            // your project's release build type.
            minifyEnabled true

            // Enables resource shrinking, which is performed by the
            // Android Gradle plugin.
            shrinkResources true

            // Includes the default ProGuard rules files that are packaged with
            // the Android Gradle plugin. To learn more, go to the section about
            // R8 configuration files.
            proguardFiles getDefaultProguardFile(
                    'proguard-android-optimize.txt'),
                    'proguard-rules.pro'

            ndk {
                debugSymbolLevel 'SYMBOL_TABLE'
            }
       }
   }`

I have uploaded the proguard mapping.txt file and ran `flutter packages pub run sentry_dart_plugin` as well, it uploaded the debug symbols to Sentry. However, the stacktraces are still not updated.
How it looks:
![image](https://user-images.githubusercontent.com/17462579/211202246-7929d045-2e26-4dde-8b2b-88f3c9d973d6.png)

**Comment by marandaneto** [comment]
@abdo400 this is a Dart error I believe, did you compile your app with `split-debug-info and obfuscate`?
Check if you have not missed anything in the [docs](https://docs.sentry.io/platforms/flutter/upload-debug/).

**Comment by abdo400** [comment]
I didn't compile with `split-debug-info and obfuscate`. I only had proguard, I think this is the main reason since it was working fine for iOS. I will try it out.

**Comment by marandaneto** [comment]
> I didn't compile with `split-debug-info and obfuscate`. I only had proguard, I think this is the main reason since it was working fine for iOS. I will try it out.

The proguard mapping file is only for Java/Kotlin minified events, the screenshot isn't a Java/Kotlin event.
Can you link me to a sentry.io event so I can take a look?

**Comment by abdo400** [comment]
It's locked behind the org account, not sure how to link it and you will be able to take a look?

**Comment by abdo400** [comment]
Ex: 1
https://sentry.io/share/issue/5a84c16198af4043aebe7be386ab90b3/

Ex: 2
https://sentry.io/share/issue/654d712ab9274c5f8cd3a30a7bde5ba0/

**Comment by marandaneto** [comment]
@abdo400 hard to tell, maybe you are using a pre-compiled library that is already obfuscated?

**Comment by abdo400** [comment]
I don't think so, this is everywhere inside the app. I have released another build but with the obfuscated flags. And uploaded the symbols to Sentry. Waiting to see the results.

**Comment by marandaneto** [comment]
@abdo400 if you create a new app (using the template), and add sentry, do you experience the same issue?
a minimal reproducible example would help here since apps are not minified by default, so it should not be an issue at all.

**Comment by abdo400** [comment]
Could it be because I set `minifyEnabled true` in by build.gradle script?

**Comment by marandaneto** [comment]
Nope, as mentioned.

> The proguard mapping file is only for Java/Kotlin minified events, the screenshot isn't a Java/Kotlin event.

**Comment by abdo400** [comment]
After making the build with `split-debug-info and obfuscate`, and uploading the debug symbols. The errors are now decoded, but its not how it used to be though (it doesn't show the app stacktrace).

This is how it looks now (latest prod with obfuscate enabled) (The build is decoded but no stacktrace)
https://sentry.io/share/issue/cd4f94be561741df874b3116549c6d13/

This is how it used to be for older builds (dev)
https://sentry.io/share/issue/7596260a96334aa6a77485c0214b3680/

Older prod build with no obfuscation (It used to show the stacktrace but its encoded)
https://sentry.io/share/issue/654d712ab9274c5f8cd3a30a7bde5ba0/

**Comment by marandaneto** [comment]
1st. When you enable `split` and `obfuscate`, the stack traces look like this, this is not Sentry's fault, but rather how the Flutter tooling works https://docs.flutter.dev/deployment/obfuscate
Try to throw an error that happens within your App's code, for this one, everything is system frames, can you share the code snippet of this error? how did you throw and where in the app?

2nd. That's the standard way if `split` and `obfuscate` are not enabled, there's something in your setup/environment messing this up (we need a minimal reproducible example).

3rd. that's how it should be.

**Comment by abdo400** [comment]
So, after testing with a fresh app with the `flutter build apk`, it didn't show the encrypted stack trace it used to show before. But with `split-debug-info and obfuscate` and debug symbols uploaded, the end result is close to what we had before but with the in-app stack trace available.

Fresh app with obfuscation (You can see the in-app stack trace in the first 3 lines):
https://sentry.io/share/issue/3d68345952114fdd887911b73981ad62/

However, the main production app doesn't show this stack trace:
https://sentry.io/share/issue/5de5c7e524ef4f8db9b576a57b42ac7d/

**Comment by abdo400** [comment]
So, after some digging (Thank you for suggestion btw, appreciate it!)
 
I found out that this:
https://sentry.io/share/issue/654d712ab9274c5f8cd3a30a7bde5ba0/
Was actually caused by this line `extra-gen-snapshot-options=--obfuscate` in `android/gradle.properties`. (You can reproduce in a fresh project by only adding this line)
Which is good, now I can stack trace my errors again!

However, if I want to build with `split-debug-info and obfuscate`. 
I still get this:
https://sentry.io/share/issue/6cbe95d01c1f4bbbbc67fcd312f3980a/
Which is unfortunately not good as its not showing my dart stack trace.

For an idea of how I think it should like, this is the same error but with no obfuscation:
https://sentry.io/share/issue/e18ced471a454e8db85f6bce5e4cca39/

**Comment by marandaneto** [comment]
> Which is good, now I can stack trace my errors again!

That's on the Flutter tooling, not on Sentry's, if you enable the obfuscation features, the stack traces will look like native code (C/C++), because that's how the Dart and Flutter tooling work internally.
There's an issue with the Dart language to make it possible (revert back to Dart stack traces) but AFAIK there's no progress yet.

So removing the `--obfuscate` should work, or enabling `split-debug-info and obfuscate` but then you know about the stack traces, closing this issue, thanks for figuring it out.
