### ISSUE TITLE
Change method signature for `Sentry.captureException()`

### ISSUE THREAD

**Issue by ueman** [getsentry/sentry-dart#1219]
### Description

The method signature is currently:
```dart
Future<SentryId> captureException(
  dynamic throwable, {
  dynamic stackTrace,
  dynamic hint,
  ScopeCallback? withScope,
}) { ... }
```

Ideally, the method signature will be changed to 
```dart
Future<SentryId> captureException(
  Object? throwable, {
  StackTrace? stackTrace,
  dynamic hint,
  ScopeCallback? withScope,
}) { ... }
```

Maybe the `throwable` and `stackTrace` can even be made non-nullable? 
I guess this could be a good candidate for v7.

Other tools like Sentry do it like I suggest, in a more strongly typed fashion:
- Crashlytics: https://pub.dev/documentation/firebase_crashlytics/latest/firebase_crashlytics/FirebaseCrashlytics/recordError.html
- Dynatrace: https://pub.dev/packages/dynatrace_flutter_plugin#a-namecrashreportingacrash-reporting
- Bugsnag https://docs.bugsnag.com/platforms/flutter/reporting-handled-errors/#basic-usage

**Comment by marandaneto** [comment]
`throwable` could be, but it has to change to `Object` indeed.
`StackTrace` has to be nullable, because sometimes it is, and then we fall back to the current stack trace.
I'd add it to v8, since we already scoped v7 and this is a nice improvement but everything works as it is already.

**Comment by marandaneto** [comment]
Changing the stack trace from `String` to `StackTrace` might force people to use/know the `StackTrace.fromString` util, because some error handlers actually just give you a `String`, such as the `RawReceivePort` for `Isolate#addErrorListener`.

**Comment by brustolin** [comment]
Because of Manoel explained, we choose not to go ahead with this change.
By changing the method signature we would degrade user experience.
