### ISSUE TITLE
Allow app hangs from flutter

### ISSUE THREAD

**Issue by danielgomezrico** [getsentry/sentry-dart#1223]
It would be cool to have this feature on flutter:
https://docs.sentry.io/platforms/apple/configuration/app-hangs/

**Comment by marandaneto** [comment]
Makes sense, we just need to expose the flag and the internal and sync it to the iOS SDK.
Would you like to submit a PR?

**Comment by marandaneto** [comment]
I'll check if the stack trace provided by the iOS SDK in case of app hangs actually is useful for Flutter developers, is it actionable or just internal frames? we have to understand if it makes sense.

**Comment by danielgomezrico** [comment]
I apologize for not answering, I'm not sure which kind of traces does it show but on flutter it would be wonderful to have something related, one thing that we do manually is creating spans for some widget `build` methods to measure how much time does it take, and seen this I thought that maybe there's a chance to automate it and share that with everyone, to use it has give a lot of value to understand how to prioritize performance fixes over product features

**Comment by marandaneto** [comment]
> I apologize for not answering, I'm not sure which kind of traces does it show but on flutter it would be wonderful to have something related, one thing that we do manually is creating spans for some widget `build` methods to measure how much time does it take, and seen this I thought that maybe there's a chance to automate it and share that with everyone, to use it has give a lot of value to understand how to prioritize performance fixes over product features

Reading your message feels like this is not related to App hang error events but actually automatic instrumentation for Application performance monitoring, can you elaborate?

**Comment by marandaneto** [comment]
@danielgomezrico can you provide more info?

**Comment by marandaneto** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
