### ISSUE TITLE
APM/crumbs support for `hive`

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-dart#1226]
### Description

`hive` seems to be super popular https://pub.dev/packages/hive

https://github.com/getsentry/sentry-dart/issues/1203 would help but would not give access to the CRUD statements, richer span context, etc.

https://docs.flutter.dev/packages-and-plugins/happy-paths/recommended#background-processing-

**Comment by denrase** [comment]
Reopened for crumbs
