### ISSUE TITLE
Bump Cocoa SDK to 8.0.0

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-dart#1232]
### Description

The Cocoa 8.0.0 release is out. We can update the dart SDK to use the latest Cocoa version. 

When updating, please adapt the [docs](https://github.com/getsentry/sentry-docs/blob/463a000850dbb8d20b06e1a65a924b300e0c5676/src/platforms/common/configuration/options.mdx?plain=1#L850-L864) on `enableOutOfMemoryTracking` accordingly that it's no longer available and is now renamed to `enableWatchdogTerminationTracking`.

**Comment by marandaneto** [comment]
Already done https://github.com/getsentry/sentry-dart/releases/tag/7.0.0-alpha.3

**Comment by philipphofmann** [comment]
@marandaneto, did you also adapt the docs as pointed out above?

**Comment by marandaneto** [comment]
> @marandaneto, did you also adapt the docs as pointed out above?

https://docs.sentry.io/platforms/flutter/migration/#migrating-from-sentry_flutter-618x-to-sentry-700
Will change everything else only when 7.x is GA.
