### ISSUE TITLE
Vendor `intl`

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-dart#1241]
### Description

Reason https://github.com/getsentry/sentry-dart/pull/1202
https://github.com/dart-lang/pub/issues/3747
Ps: Check the license permission.

**Comment by marandaneto** [comment]
The only class and method is:

```
    final formatter = NumberFormat('#.################');
    return formatter.format(sampleRate);
```

But the `NumberFormat` class references other classes and so on.

**Comment by denrase** [comment]
@marandaneto Maybe we can just implement this one method instead of pulling in all those classes from the `intl` package into our repo.

**Comment by denrase** [comment]
We could come up with some input/output data and write a tests + format method.

**Comment by marandaneto** [comment]
> @marandaneto Maybe we can just implement this one method instead of pulling in all those classes from the `intl` package into our repo.

Yep, we can vendor this method specifically as long as it has the same result.
