### ISSUE TITLE
ConcurrentModificationError when doing performance tracing

### ISSUE THREAD

**Issue by ueman** [getsentry/sentry-dart#1256]
_Platform:_
- [ ]  Dart
- [x]  Flutter Android or iOS
- [ ]  Flutter Web

_IDE:_
- [x]  VSCode
- [ ]  IntelliJ/AS
- [ ]  XCode
- [ ]  Other, which one?

_split-debug-info and obfuscate (Flutter Android or iOS) or CanvasKit (Flutter Web):_
- [ ]  Enabled
- [x]  Disabled

_Platform installed with:_
- [x] pub.dev
- [ ] GitHub

The version of the SDK (See pubspec.lock):
**6.18.1** (but it's also happening on 6.19.0)

---
I have the following issue:

Sometimes when tracing performance, I see a `ConcurrentModificationError`. It is thrown by the following code:

https://github.com/getsentry/sentry-dart/blob/8fa393466a5d478f281e46cbc11e66c2b3db12d8/dart/lib/src/sentry_tracer.dart#L90-L94

Unfortunately, I failed to create a minimal reproducible example. Therefore, I'm attaching some screenshots. The first one is the issue on Sentry.io itself, but unfortunately it's not helpful at all.

<img width="819" alt="Screenshot 2023-01-31 at 12 34 30" src="https://user-images.githubusercontent.com/1270149/215749210-ff87c05e-d2ff-488c-958e-be112337a4ed.png">

The second one come from debugging the issue, to show that it's indeed coming from Sentry. Unfortunately, the stacktrace of that error is the same as the one above.
<img width="714" alt="Screenshot 2023-01-31 at 12 34 56" src="https://user-images.githubusercontent.com/1270149/215749295-49d9ed02-e132-44db-80cd-d2bfec748485.png">

I'm assuming that it's caused by unfinished spans somehow. Roughly, the code in the (closed source) app is the following:

```
methodOne() {
 transaction{
   awaited spans (3 times)
   one unawaited span
   awaited spans (4 times)
 }
}

during the same time as methodOne is a web request running, which also attaches a span to the above mentioned transaction

After the above transaction is finished, another one is started. I don't know whether that's related or not.
``` 

I would expect Sentry to not throw a ConcurrentModificationError.

**Comment by ueman** [comment]
The bad stacktrace seemingly comes from `Future.forEach` which then internally calls `Future.doWhile` which does some Zone magic as seen in its documentation: 
```dart
// Copied for convenience from https://api.dart.dev/stable/2.19.0/dart-async/Future/doWhile.html
static Future doWhile(FutureOr<bool> action()) {
  _Future<void> doneSignal = new _Future<void>();
  late void Function(bool) nextIteration;
  // Bind this callback explicitly so that each iteration isn't bound in the
  // context of all the previous iterations' callbacks.
  // This avoids, e.g., deeply nested stack traces from the stack trace
  // package.
  nextIteration = Zone.current.bindUnaryCallbackGuarded((bool keepGoing) {
    while (keepGoing) {
      FutureOr<bool> result;
      try {
        result = action();
      } catch (error, stackTrace) {
        // Cannot use _completeWithErrorCallback because it completes
        // the future synchronously.
        _asyncCompleteWithErrorCallback(doneSignal, error, stackTrace);
        return;
      }
      if (result is Future<bool>) {
        result.then(nextIteration, onError: doneSignal._completeError);
        return;
      }
      // TODO(40014): Remove cast when type promotion works.
      keepGoing = result as bool;
    }
    doneSignal._complete(null);
  });
  nextIteration(true);
  return doneSignal;
}
```

**Comment by marandaneto** [comment]
Thanks @ueman 
I will try to reproduce it.

**Comment by ueman** [comment]
Interestingly enough, when I replace

https://github.com/getsentry/sentry-dart/blob/8fa393466a5d478f281e46cbc11e66c2b3db12d8/dart/lib/src/sentry_tracer.dart#L90-L94

with the following code

```dart
      for (final span in spansToBeFinished) {
        await span.finish(
          status: SpanStatus.deadlineExceeded(),
          endTimestamp: commonEndTimestamp,
        );
      }
```

the error is gone. Though, I can't explain why that's happening.
