### ISSUE TITLE
Unable to get slow frame data

### ISSUE THREAD

**Issue by itlwy** [getsentry/sentry-dart#1263]
_Platform:_
- [ ]  Dart
- [x]  Flutter Android or iOS
- [ ]  Flutter Web

_IDE:_
- [ ]  VSCode
- [x]  IntelliJ/AS
- [ ]  XCode
- [ ]  Other, which one?

_split-debug-info and obfuscate (Flutter Android or iOS) or CanvasKit (Flutter Web):_
- [ ]  Enabled
- [x]  Disabled

_Platform installed with:_
- [ ] pub.dev
- [x] GitHub

Output of the command `flutter doctor -v` below:

[✓] Flutter (Channel stable, 3.0.1, on Ubuntu 20.04.4 LTS 5.13.0-37-generic, locale zh_CN.UTF-8)
    • Flutter version 3.0.1 at /home/weiyeli/fvm/versions/3.0.1
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (9 months ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /home/weiyeli/Android/Sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: /home/weiyeli/software/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 2021.2)
    • Android Studio at /home/weiyeli/software/android-studio
    • Flutter plugin version 68.1.2
    • Dart plugin version 212.5744
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code
    • VS Code at /snap/code/current
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • 21091116C (mobile) • 4pwcwsqgifpb4xhq • android-arm64  • Android 12 (API 31)
    • Linux (desktop)    • linux            • linux-x64      • Ubuntu 20.04.4 LTS 5.13.0-37-generic
    • Chrome (web)       • chrome           • web-javascript • Google Chrome 109.0.5414.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

The version of the SDK (See pubspec.lock):
**6.18.1**

---
I have the following issue:

I used an animation example with slow frames to obtain performance data, but the data obtained are all 0.
The document address is [link](https://docs.sentry.io/platforms/flutter/performance/instrumentation/automatic-instrumentation/#slow-and-frozen-frames).
I found that Sentry uses native API FrameMetricsAggregator on the Android side to collect data. I guess this API can't get Flutter's FPS data, so I add the log print as shown below: 
![image](https://user-images.githubusercontent.com/14884951/216540211-a7553447-1f89-4a70-9fac-ee2cefbffcb6.png)

2023-02-03 15:01:54.949 28171-28171/io.sentry.samples.flutter I/System.out: ==================> total :0,slow :0 frozen :0

![image](https://user-images.githubusercontent.com/14884951/216540459-73321011-267f-4ed1-94d7-cf5de6986a9c.png)

The simplified code is as follows: 
`
class StaggerAnimation extends StatelessWidget {
  ...
  @override
  Widget build(BuildContext context) {
    return AnimatedBuilder(
      builder: (context,child){
        calculateMD5();
        return Container(
          alignment: Alignment.bottomCenter,
          padding: padding.value,
          child: Container(
            color: color.value,
            width: 50.0,
            height: height.value,
          ),
        );
      },
      animation: controller,
    );
  }

  void calculateMD5() {
    String content = "What a fine day, I can do a lot of funny stuffddd.";
    for (int i = 0; i < 18300; i++) {
      innerCalculateMd5(content);
    }
  }

  void innerCalculateMd5(String content) {
    List<int> contentConvert = utf8.encode(content);
    md5.convert(contentConvert);
  }
}
`

Looking forward to feedback, thanks.

**Comment by marandaneto** [comment]
@itlwy Indeed sometimes the Native integrations (Android and iOS) are not fully accurate with the slow and frozen frames, it depends on what you're doing and how Flutter does it as well.
We are changing this to use the FrameTiming approach, Follow [this](https://github.com/getsentry/sentry-dart/issues/513) issue.
