### ISSUE TITLE
Native code should request a scope sync before sending crash reports

### ISSUE THREAD

**Issue by ueman** [getsentry/sentry-dart#1275]
When native code crashes I don't any information from the Flutter side on the error report. I just get the native breadcrumbs and device information which are unfortunately not really helpful.

The crash which prompted this feature request is the following:
- Flutter app on an iPad has a `add to wallet` button
- Apple Wallet is unsupported on the iPad
- For some reason the case isn't handled properly and the app crashes
- The error report doesn't contain any information from the Flutter side as seen in the following screenshot

<img width="1145" alt="Screenshot 2023-02-08 at 19 17 05" src="https://user-images.githubusercontent.com/1270149/217617397-92bb8543-dfda-4e86-bfbd-b860527f2e5e.png">

Therefore, I would like to request the following feature:
When there's an error on the native side, the native side should ask the Flutter side for a scope sync.

**Comment by marandaneto** [comment]
@ueman Have you uploaded debug symbols? you should be able to read the stack trace on the native side at least.
https://docs.sentry.io/platforms/flutter/upload-debug/#uploading-for-ios-and-macos or https://docs.sentry.io/platforms/flutter/upload-debug/#sentry-dart-plugin

**Comment by marandaneto** [comment]
What would you expect to be synced from the scope? what is missing? native events should contain all the info from the Dart scope already if `enableScopeSync` is enabled.

**Comment by ueman** [comment]
> What would you expect to be synced from the scope? what is missing? native events should contain all the info from the Dart scope already if `enableScopeSync` is enabled.

Thanks! We're indeed missing the `enableScopeSync` option. Why is it disabled by default?

**Comment by marandaneto** [comment]
@ueman `enableScopeSync` is enabled by default, probably for a while already.
`enableNdkScopeSync ` isn't and -> https://github.com/getsentry/sentry-dart/pull/1276
