### ISSUE TITLE
how to set PROXY when use sentry dio

### ISSUE THREAD

**Issue by haozi5460** [getsentry/sentry-dart#1280]
In my App, I use Dio to make network requests, but when I integrate Sentry_dio to monitor, I cannot set the network proxy.

Error display:
_dio.httpClientAdapter is SentryDioClientAdapter , not sub type of DefaultHttpClientAdapter.

The code is like: [https://github.com/getsentry/sentry-dart/issues/1015](https://github.com/getsentry/sentry-dart/issues/1015)
as written.

String proxy = "PROXY ${ipController.text}:${portController.text}";

(dio?.httpClientAdapter as DefaultHttpClientAdapter).onHttpClientCreate =
    (client) {
  client.findProxy = (url) {
    return proxy;
  };

  //Trust certificate for https proxy
  client.badCertificateCallback = (cert, host, port){
    return true;
  };
  return client;
};

**Comment by haozi5460** [comment]
When I was looking for the answer, I didn't find anything useful. SentryDioClientAdapter is not exposed to the outside world and cannot be used.

[https://github.com/getsentry/sentry-dart/issues/1015](https://github.com/getsentry/sentry-dart/issues/1015) also said that there is no solution.

Later I found a way to replace it myself:
1. When you initialize Dio(), it will create a DefaultHttpClientAdapter instance for you by default and assign it to dio.httpClientAdapter.

2. We can create a field to save dio.httpClientAdapter in the tool class, such as:

late HttpClientAdapter httpClientAdapter;
httpClientAdapter = dio.httpClientAdapter;

Note: This step needs to be placed before dio.addSentry(), because addSentry will wrap httpClientAdapter as SentryDioClientAdapter.

3. In the place where the agent is set, you can first judge whether the dio.httpClientAdapter is the DefaultHttpClientAdapter type. If not, you can reassign the saved httpClientAdapter. After the agent is set, set dio.addSentry()
   if(!(dio?.httpClientAdapter is DefaultHttpClientAdapter)){
     dio?.httpClientAdapter = HttpRequest().httpClientAdapter;
   }

**Comment by haozi5460** [comment]
String proxy = "PROXY ${ipController.text}:${portController.text}";

    if(!(dio?.httpClientAdapter is DefaultHttpClientAdapter)){
      dio?.httpClientAdapter = HttpRequest().httpClientAdapter;
    }

    (dio?.httpClientAdapter as DefaultHttpClientAdapter).onHttpClientCreate =
        (client) {
      client.findProxy = (url) {
        return proxy;
      };

      //Trust certificate for https proxy
      client.badCertificateCallback = (cert, host, port){
        return true;
      };
      return client;
    };

    if(Channel.currentChannel == APPChannel.DEV){
      dio?.addSentry(
        captureFailedRequests: true,
        maxRequestBodySize: MaxRequestBodySize.always,
        maxResponseBodySize: MaxResponseBodySize.always,
      );
    }

[Here is how to dynamically add network proxy for Dio](https://www.jianshu.com/p/f62a54a7bb00)

**Comment by marandaneto** [comment]
@haozi5460 as mentioned here https://github.com/getsentry/sentry-dart/issues/1015
Proxy settings should be directly set on Dio if possible,`SentryDioClientAdapter` is just s wrapper on top of Dio.

**Comment by haozi5460** [comment]
> wrapper

I know this, but after addSentry adds extensions, DefaultHttpClientAdapter becomes SentryDioClientAdapter, and SentryDioClientAdapter is not open to the outside world and cannot be called externally.

**Comment by mikewolfd** [comment]
bump, this is still a problem
