### ISSUE TITLE
SentryAssetBundle implementation is missing

### ISSUE THREAD

**Issue by smishra4teva** [getsentry/sentry-dart#1286]
I am using 

```
dependencies:
  sentry_flutter: ^6.20.1
``` 

### Error: 
 
 The non-abstract class 'SentryAssetBundle' is missing implementations for these members:
sentry_asset_bundle.dart:37

 - AssetBundle.loadStructuredBinaryData

 
 this method `loadStructuredBinaryData` is not implemented by SentryAssetBundle. 

the abstract class `AssetBundle` has `loadStructuredBinaryData` method. But  `SentryAssetBundle` class is not overriding it.

**Comment by ueman** [comment]
There's already an open PR at https://github.com/getsentry/sentry-dart/pull/1272
