### ISSUE TITLE
Consider changing Breadcrumb.data from Map<String, String> to Map<String, dynamic>

### ISSUE THREAD

**Issue by kuhnroyal** [getsentry/sentry-dart#129]
Sentry accepts the breadcrumb data as complex JSON content.
This is currently not possible to send as the data field is currently `final Map<String, String> data;`.

Other SDKs also accept object types as values.
When the data fields are JSON objects, data scrubbing would work on the fields. Atm I have to transform objects to Strings and data scrubbing doesn't work.

Btw, the issue templates are still for the sentry_flutter package if anyone can change this.

**Comment by bruno-garcia** [comment]
Thanks for raising. We should consider changing it to <String, Object> and serialize the data. We're not using reflection so it might be a best effort there (i.e: Serialize only 1 level and basic types like String, Int etc)
