### ISSUE TITLE
Screenshot sample rate

### ISSUE THREAD

**Issue by JankoLancer** [getsentry/sentry-dart#1290]
It would be great to have the ability to set the screenshot sample rate, so we can set that we want only let's say 5% of all errors to have screenshots attached. 

The reason is that with the current approach, Sentry attachment limit is spent very fast when you have a lot of issues.

Let me know if I can help with something.

Flutter

**Comment by krystofwoldrich** [comment]
Before we discuss it internally. You could implement such behavior in the `beforeSend` option. 

You can remove the `screenshot` from the `hint` there.

**Comment by marandaneto** [comment]
As @krystofwoldrich said, you can use the `beforeSend` and the `hint` to filter out the screenshot attachment.
