### ISSUE TITLE
Add support for Dio 5.0.0

### ISSUE THREAD

**Issue by marcinFDT** [getsentry/sentry-dart#1292]
Please, add support for the new version of Dio, which includes many fixes in Dio lib. I have to choose to use sentry dio or have glitched dio like this https://stackoverflow.com/questions/73106834/flutter-dio-interceptor-error-bad-state-future-already-completed/73824643#73824643

**Comment by ueman** [comment]
I've already opened a PR for it https://github.com/getsentry/sentry-dart/pull/1282 and am now waiting for Sentry to merge and release it

**Comment by ueman** [comment]
Resolved by https://github.com/getsentry/sentry-dart/pull/1282
