### ISSUE TITLE
Is there any way to get device data from sentry

### ISSUE THREAD

**Issue by philos3** [getsentry/sentry-dart#1301]
I want to get these device data as the below picture .   Is there any way to get with sentry?

<img width="909" alt="image" src="https://user-images.githubusercontent.com/8424317/222023264-11c35dcc-3a38-4697-b467-0490de5f32ae.png">

**Comment by marandaneto** [comment]
Yes just use the [Flutter SDK](https://docs.sentry.io/platforms/flutter/).

**Comment by philos3** [comment]
As i know ,sentry had collect many useful data ,such as the user ip or some deveice data.   Now i want to get these data in my code ,whate can i do ? SentryFlutter has no api to get those device data ,can you show me the code or the link of doc ,thx

<img width="910" alt="image" src="https://user-images.githubusercontent.com/8424317/222638072-25df4002-f4fd-4a79-8687-ec06402a863d.png">
