### ISSUE TITLE
why sentry collect so many same bug at the same time 

### ISSUE THREAD

**Issue by philos3** [getsentry/sentry-dart#1302]
_Platform:_
- Flutter Android or iOS

_IDE:_
-  IntelliJ/AS

_split-debug-info and obfuscate (Flutter Android or iOS) or CanvasKit (Flutter Web):_
- Enabled

_Platform installed with:_
- pub.dev

Output of the command `flutter doctor -v` below:

[✓] Flutter (Channel stable, 3.3.9, on macOS 12.5 21G72 darwin-arm, locale zh-Hans-CN)
    • Flutter version 3.3.9 on channel stable at /Users/linzechi/fvm/versions/3.3.9
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (3 months ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/linzechi/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Library/Java/JavaVirtualMachines/temurin-11.jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment Temurin-11.0.16.1+1 (build 11.0.16.1+1)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[!] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Connected device (2 available)
    • iPhone (mobile) • f0ea0f65a6bc14b9560af0711361cbbc4e07ef37 • ios          • iOS 14.7.1 18G82
    • macOS (desktop) • macos                                    • darwin-arm64 • macOS 12.5 21G72 darwin-arm

[✓] HTTP Host Availability
    • All required HTTP hosts are available

The version of the SDK (See pubspec.lock):
  sentry:
    dependency: transitive
    description:
      name: sentry
      url: "https://pub.flutter-io.cn"
    source: hosted
    version: "6.18.1"
  sentry_dio:
    dependency: "direct main"
    description:
      name: sentry_dio
      url: "https://pub.flutter-io.cn"
    source: hosted
    version: "6.18.1"
  sentry_flutter:
    dependency: "direct main"
    description:
      name: sentry_flutter
      url: "https://pub.flutter-io.cn"
    source: hosted
    version: "6.18.1"
  sentry_logging:
    dependency: "direct main"
    description:
      name: sentry_logging
      url: "https://pub.flutter-io.cn"
    source: hosted
    version: "6.18.1"
  yaml:
    dependency: transitive
    description:
      name: yaml
      url: "https://pub.flutter-io.cn"
    source: hosted
    version: "3.1.1"
sdks:
  dart: ">=2.18.1 <3.0.0"
  flutter: ">=3.3.0"

---
I have the following issue:
https://sentry.deepcoin.ski/share/issue/f90a223390f44da281abee551e27f740/
as above share link showing, why sentry collect so many same bug at the same time 

[](https://sentry.deepcoin.ski/share/issue/f90a223390f44da281abee551e27f740/)

**Comment by marandaneto** [comment]
Sentry captures what's thrown by the framework or exceptions that you capture manually.
If you want to filter out something, use one of our [filtering](https://docs.sentry.io/platforms/flutter/configuration/filtering/) mechanisms.
