### ISSUE TITLE
Add the build version to the reports

### ISSUE THREAD

**Issue by kamil-hammouche** [getsentry/sentry-dart#131]
Hi,

Everytime I see crashes into the Sentry Console, I'm unable to know which app version has encountered the bug. The crash report doesn't specify the app version (build version).
I tried to manually specify it in the Sentry initialization but there are no methods for that yet.

Do you plan to add it in a near future ? This is very hard to know if the crash has been fixed in newer versions because we can't see which app version the user has got neither if it's an Android or Apple device.

Best regards,

**Comment by WasserEsser** [comment]
You can just specify it yourself by adding environmentAttributes on the SentryClient. Sentry will pick up on that. You can also specify things like platform, user etc. that way and filter in Sentry.
