### ISSUE TITLE
Enable screenshot capability for any Sentry event

### ISSUE THREAD

**Issue by vlazdra** [getsentry/sentry-dart#1316]
Hi, just wanted to pop-in here and ask a quick question / feature request for Flutter.
It's regarding the Screenshot capability.

At the moment, the capability of sending the Screenshot to Sentry is limited only when the user experiences an Exception with or without a StackTrace.
Based on the code here: https://github.com/getsentry/sentry-dart/blob/main/flutter/lib/src/screenshot/screenshot_attachment_processor.dart#L25

So my question / feature request is, why is it limited only to Exceptions and/or StackTraces and not possible to use a regular event to also have the screenshot attached by using the method `captureMessage()` for example?

Thanks in advance!

**Comment by marandaneto** [comment]
Hi, usually people use `captureMessage` for logging things, more often, and the screenshot feature has some overhead (that pays off if there's an error), that's the only reason.
You can do the screenshot manually yourself and pass it along with `captureMessage` using the latest RC version.

Something like:
`Sentry.captureMessage(message, hint: Hint.withScreenshot(SentryAttachment.fromScreenshotData(...)))`
