### ISSUE TITLE
Update sentry dio to last dio version

### ISSUE THREAD

**Issue by jaumard** [getsentry/sentry-dart#1321]
Getting some error when wanting to use last Dio version:

```
Because no versions of sentry_dio match >6.22.0 <7.0.0 and sentry_dio 6.22.0 depends on dio ^4.0.0, sentry_dio ^6.22.0 requires dio ^4.0.0.

```

Would be nice if sentry_dio can be migrated to Dio 5.
Thanks

**Comment by ueman** [comment]
The current beta already supports dio 5. See https://github.com/getsentry/sentry-dart/pull/1282

**Comment by marandaneto** [comment]
What @ueman said.
https://github.com/getsentry/sentry-dart/releases/tag/7.0.0-rc.2
