### ISSUE TITLE
DioError extractor extracts wrong stacktrace

### ISSUE THREAD

**Issue by ueman** [getsentry/sentry-dart#1322]
I have tested this change excessively over the last few days and the whole update from Sentry 6.x/Dio 4.x to Sentry 7.0/Dio 5.0 is a big step back regarding traceability of the `DioError`. This is in big part due to changes in `dio` which removed the whole source stacktrace. But due to the `DioErrorExtractor` there are now also cases where the inner stacktrace of `DioError.error.stacktrace` is completely missing in the event.

I think the `DioError.stacktrace` needs to be added by default, as it was the case in `6.x` and only the inner cause error/stacktrace should be extracted via the `DioErrorExtractor`.

Something like:
```dart
class DioErrorExtractor extends ExceptionCauseExtractor<DioError> {
  @override
  ExceptionCause? cause(DioError error) {
    if (error.error == null) {
      return null;
    }
    return ExceptionCause(
      error.error,
      error.error is Error ? (error.error as Error).stackTrace : null,
    );
  }
}
```

_Originally posted by @kuhnroyal in https://github.com/getsentry/sentry-dart/issues/1282#issuecomment-1462184777_

**Comment by ueman** [comment]
@kuhnroyal PR incoming? 😄

**Comment by kuhnroyal** [comment]
Yea sure but I think we need to solve the dio problem first, otherwise the `DioError.stackTrace` is almost always `null`.

**Comment by marandaneto** [comment]
@denrase can you take a look?
If the `stackTrace` is null, we can check if `error` is an `Error` and use the https://api.dart.dev/stable/2.19.4/dart-core/Error/stackTrace.html as mentioned.
Sounds like the right thing to do.
What if `stackTrace` isn't null but `error` also has the `error.stackTrace`, which one has precedence? I believe the original `stackTrace`.

**Comment by kuhnroyal** [comment]
> What if `stackTrace` isn't null but `error` also has the `error.stackTrace`, which one has precedence? I believe the original `stackTrace`.

From my understanding, the `DioError. stackTrace` should always be on the original error and has nothing to do with the cause being extracted here.

**Comment by kuhnroyal** [comment]
Here is an example, the issue is named `String DioError inner stacktrace`.
The stacktrace belongs to the original error which was extracted via `SentryDioClientAdapter` - the error simply has no cause.

![Bildschirm­foto 2023-03-09 um 21 47 31](https://user-images.githubusercontent.com/1260818/224153892-b1258a2a-169b-4ef6-b5ea-4be5b28cfb24.png)
![Bildschirm­foto 2023-03-09 um 21 47 47](https://user-images.githubusercontent.com/1260818/224153897-d2973dd6-fec9-43bb-a6f4-ab99d470dc52.png)

**Comment by kuhnroyal** [comment]
I think we are missing the original stacktrace here https://github.com/getsentry/sentry-dart/blob/v7.0.0/dio/lib/src/failed_request_interceptor.dart#L42

**Comment by kuhnroyal** [comment]
Hacked up a basic idea that should solve this, didn't test it yet.

**Comment by marandaneto** [comment]
> I think we are missing the original stacktrace here [`v7.0.0`/dio/lib/src/failed_request_interceptor.dart#L42](https://github.com/getsentry/sentry-dart/blob/v7.0.0/dio/lib/src/failed_request_interceptor.dart?rgh-link-date=2023-03-09T20%3A59%3A15Z#L42)

In this case, the `DioErrorExtractor` will do it automatically, its a matter of fixing `DioErrorExtractor`.
