### ISSUE TITLE
type 'SentryTransformer' is not a subtype of type 'BackgroundTransformer' in type cast

### ISSUE THREAD

**Issue by mminhlequang** [getsentry/sentry-dart#1329]
_Platform:_
- [ ]  Dart
- [x]  Flutter Android or iOS
- [ ]  Flutter Web

_IDE:_
- [x]  VSCode
- [ ]  IntelliJ/AS
- [ ]  XCode
- [ ]  Other, which one?

_split-debug-info and obfuscate (Flutter Android or iOS) or CanvasKit (Flutter Web):_
- [ ]  Enabled
- [x]  Disabled

_Platform installed with:_
- [x] pub.dev
- [ ] GitHub

Output of the command `flutter doctor -v` below:

The output goes here...

The version of the SDK (See pubspec.lock):
**4.x.x**

---
I have the following issue:

The description goes here ...

**Steps to reproduce:**
- Step

**Actual result:**
- Actual

**Expected result:**
- Result

**Comment by marandaneto** [comment]
@mminhlequang can you provide more context and fill up the issue template with all the information required?

**Comment by mminhlequang** [comment]
Simple 
dio: ^5.0.2
sentry_dio: ^6.22.0

**Comment by marandaneto** [comment]
For dio >= 5, please use the [latest v7](https://github.com/getsentry/sentry-dart/releases/tag/7.0.0-rc.2)
Its gonna be GA this week, or just wait for the GA version.

**Comment by mminhlequang** [comment]
oki thanks
