### ISSUE TITLE
Use `User` and `Breadcrumb` data classes from a Map

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-dart#1330]
### Description

Context https://github.com/getsentry/team-mobile/issues/59

**Comment by marandaneto** [comment]
@brustolin @philipphofmann can we cut a release on iOS?

**Comment by philipphofmann** [comment]
Sure, but I won't get to it today. So it will be next week. I hope that's not a problem.

**Comment by philipphofmann** [comment]
@marandaneto and @denrase, the [release 8.6.0](https://github.com/getsentry/sentry-cocoa/releases/tag/8.6.0) is out.
