### ISSUE TITLE
Change SDK name of Sentry Native for Flutter

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-dart#1333]
### Description

Right now it is `sentry.native.android` and this is set at compile time.
Ideally, this would be `sentry.native.android.flutter` or just `sentry.native.flutter`.

**Comment by vaind** [comment]
1. The right name would be `sentry.native.android.flutter` from what I remember doing this in Unity, see https://github.com/getsentry/sentry-unity/blob/8420c95a3def1d6b611f031070d6977f3e574397/Directory.Build.targets#L190
2. Unless there has been new development in changing this in sentry-native, it **must** be changed at compile time which means we cannot set it for Flutter specifically without building the android SDK. Currently, the flutter plugin just depends on package published by sentry-java https://github.com/getsentry/sentry-unity/blob/8420c95a3def1d6b611f031070d6977f3e574397/Directory.Build.targets#L190

**Comment by marandaneto** [comment]
Created https://github.com/getsentry/sentry-native/issues/821
Since `sentry-native` is transitioning from one team (former Native team) to the Mobile team (the one I work for), let me check what we can do.

**Comment by marandaneto** [comment]
https://github.com/getsentry/sentry-native/issues/821 is merged, now the Android SDK has to offer a public API or append `.android` automatically.

**Comment by marandaneto** [comment]
Now its possible to set the sentry-native SDK name at runtime https://github.com/getsentry/sentry-java/pull/2704
This is the last missing bit.
