### ISSUE TITLE
SentryUserInteractionWidget _lastTappedWidget unmounted

### ISSUE THREAD

**Issue by sstasi95** [getsentry/sentry-dart#1338]
_Platform:_
-  Flutter Android or iOS

_IDE:_
-  VSCode

_split-debug-info and obfuscate (Flutter Android or iOS) or CanvasKit (Flutter Web):_
-  Disabled

_Platform installed with:_
-  pub.dev

Output of the command `flutter doctor -v` below:

[✓] Flutter (Channel stable, 3.7.6, on macOS 13.2.1 22D68 darwin-arm64, locale en-IT)
    • Flutter version 3.7.6 on channel stable at /Users/simone/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 12cb4eb7a0 (2 weeks ago), 2023-03-01 10:29:26 -0800
    • Engine revision ada363ee93
    • Dart version 2.19.3
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/simone/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.76.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (4 available)
    • moto g 9 play (mobile) • ZY327PCSM5                • android-arm64  • Android 10 (API 29)
    • iPhone xS (mobile)     • 00008020-001A69240E29002E • ios            • iOS 15.6.1 19G82
    • macOS (desktop)        • macos                     • darwin-arm64   • macOS 13.2.1 22D68 darwin-arm64
    • Chrome (web)           • chrome                    • web-javascript • Google Chrome 109.0.5414.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

The version of the SDK (See pubspec.lock):
**7.0.0**

---
I have the following issue:

When _lastTappedWidget is no longer in the widget tree and tracing is enabled, tapping on a new widget causes a  'Null check operator used on a null value' on line 155 of sentry_user_interaction_widget.dart. I think the fix is to check if the element is mounted before accessing its widget.

**Steps to reproduce:**
- Run the example app given below, tap 'Page 1 button', then navigate to page2 and tap 'Page 2 button'

```dart
import 'package:flutter/material.dart';
import 'package:sentry_flutter/sentry_flutter.dart';

Future<void> main() async {
  final globalKey = GlobalKey();
  await SentryFlutter.init(
    (options) {
      options
        ..dsn = 'dsn'
        ..enableUserInteractionBreadcrumbs = true
        ..tracesSampleRate = 1;
    },
    appRunner: () {
      return runApp(
        SentryUserInteractionWidget(
          key: globalKey,
          child: const MyApp(),
        ),
      );
    },
  );
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      routes: {'page2': (context) => const Page2()},
      home: const Page1(),
    );
  }
}

class Page1 extends StatelessWidget {
  const Page1({super.key});

  void _goToPage2(BuildContext context) {
    // remove page1 from the widget tree
    Navigator.of(context).popAndPushNamed('page2');
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Padding(
          padding: const EdgeInsets.all(50),
          child: ListView(
            children: [
              MaterialButton(
                key: const ValueKey('Page1 button'),
                onPressed: () => {},
                color: Colors.green,
                child: const Text('Page1 button'),
              ),
            ],
          ),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () => _goToPage2(context),
        tooltip: 'page2',
        child: const Icon(Icons.navigate_next),
      ),
    );
  }
}

class Page2 extends StatelessWidget {
  const Page2({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Padding(
          padding: const EdgeInsets.all(50),
          child: ListView(
            children: [
              MaterialButton(
                key: const ValueKey('Page2 button'),
                onPressed: () => {},
                color: Colors.red,
                child: const Text('Page2 button'),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```
**Actual result:**
- A 'Null check operator used on a null value' exception is thrown

**Expected result:**
- No exception is thrown

Tested on Android and iOS.

Thanks,

Simone

**Comment by marandaneto** [comment]
@sstasi95 thanks for reporting, I will check this out.

**Comment by marandaneto** [comment]
@sstasi95 can you check if this [patch](https://github.com/getsentry/sentry-dart/pull/1339) works?

**Comment by sstasi95** [comment]
Yes, it works.

**Comment by marandaneto** [comment]
> Yes, it works.

thanks, will cut a release later.
