### ISSUE TITLE
Bad state: No element for `_NeedsSymbolication.needsSymbolication` with v7.1.0

### ISSUE THREAD

**Issue by dkobia** [getsentry/sentry-dart#1345]
_Platform:_
- [ ]  Dart
- [X]  Flutter Android or iOS
- [ ]  Flutter Web

_IDE:_
- [ ]  VSCode
- [X]  IntelliJ/AS
- [ ]  XCode
- [ ]  Other, which one?

_split-debug-info and obfuscate (Flutter Android or iOS) or CanvasKit (Flutter Web):_
- [ ]  Enabled
- [X]  Disabled

_Platform installed with:_
- [X] pub.dev
- [ ] GitHub

Output of the command `flutter doctor -v` below:

[✓] Flutter (Channel stable, 3.7.6, on macOS 13.2.1 22D68 darwin-arm64, locale en-US)
    • Flutter version 3.7.6 on channel stable at /Users/david/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 12cb4eb7a0 (2 weeks ago), 2023-03-01 10:29:26 -0800
    • Engine revision ada363ee93
    • Dart version 2.19.3
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/david/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Users/david/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9619390/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Users/david/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9514443/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] Android Studio (version 2022.1)
    • Android Studio at /Users/david/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9619390/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.3.2)
    • IntelliJ at /Users/david/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2022.3.1)
    • IntelliJ at /Users/david/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/223.8214.52/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2022.3.2)
    • IntelliJ at /Users/david/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/223.8617.56/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.76.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (4 available)
    • HD1907 (mobile)            • 5852279d                             • android-arm64  • Android 12 (API 31)
    • iPhone 14 Pro Max (mobile) • 1F876294-ADBC-4052-96E1-FA735AFE520B • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-2 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 13.2.1 22D68 darwin-arm64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 111.0.5563.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

The version of the SDK (See pubspec.lock):
**4.x.x**

---
I have the following issue:

When I start the app in debug mode I get a list of errors containing the following:

```
[sentry] [error] An exception occurred while processing event by a processor
         Bad state: No element
         #0      List.first (dart:core-patch/growable_array.dart:343:5)
         #1      _NeedsSymbolication.needsSymbolication (package:sentry_flutter/src/integrations/load_image_list_integration.dart:26:32)
         #2      _LoadImageListIntegrationEventProcessor.apply (package:sentry_flutter/src/integrations/load_image_list_integration.dart:40:15)
         #3      SentryClient._runEventProcessors (package:sentry/src/sentry_client.dart:423:29)
         <asynchronous suspension>
         #4      SentryClient.captureEvent (package:sentry/src/sentry_client.dart:90:21)
         <asynchronous suspension>
         #5      Hub.captureMessage (package:sentry/src/hub.dart:209:20)
         <asynchronous suspension>
```

It seems to happen for **NativeAppStartEventProcessor** and **ScreenshotEventProcessor**.

**Steps to reproduce:**
- Step

**Actual result:**
- Actual

**Expected result:**
- Result

**Comment by dkobia** [comment]
It seems to me that:

https://github.com/getsentry/sentry-dart/blob/68677de9e2f81479c18b887d8cc58d21d9d22e12/flutter/lib/src/integrations/load_image_list_integration.dart#L23 needs to be updated:

Calling `exceptions?.first` with an empty List results in `Bad state: No element`


```
 extension _NeedsSymbolication on SentryEvent {
   bool needsSymbolication() {
     if (this is SentryTransaction) return false;
+    if (exceptions == null || exceptions!.isEmpty) return false;
     final frames = exceptions?.first.stackTrace?.frames;
     if (frames == null) return false;
     return frames.any((frame) => 'native' == frame.platform);
   }
 }
```

**Comment by marandaneto** [comment]
@dkobia thanks for reporting, good catch.
https://github.com/getsentry/sentry-dart/pull/1347
