### ISSUE TITLE
Use scope set context

### ISSUE THREAD

**Issue by demoYang** [getsentry/sentry-dart#1346]
### Description

https://develop.sentry.dev/sdk/event-payloads/contexts/#example-os-context

i  want set os context

```
Sentry.configureScope((sc) {
      // sc.setContexts(key, value)
      sc.setContexts('os', {
        'name': Platform.operatingSystem,
        'type': 'ios',
      });
    });
```
but  not work

**Comment by marandaneto** [comment]
`os` is a reversed type.
See https://docs.sentry.io/platforms/dart/enriching-events/context/ and https://develop.sentry.dev/sdk/event-payloads/contexts/
You can do `contexts.operatingSystem = SentryOperatingSystem(...)`
If you are using the Flutter SDK, `operatingSystem` is already set automatically.

**Comment by demoYang** [comment]
> operatingSystem
Yes ,i use flutter sdk, but operatingSystem not set automatically when report exception . Version is 6.18.0
could you  show me  where operatingSystem  set auto ?

**Comment by demoYang** [comment]
<img width="612" alt="image" src="https://user-images.githubusercontent.com/7134823/226830853-d9a70de0-7b6c-4202-bb87-442b324608f4.png">
on iphone hasNativeIntegration return true, os, device .. is null , not set auto

**Comment by marandaneto** [comment]
@demoYang Because the iOS and Android SDK will add this information later on, see the comment above (L23-24).
Just install the Flutter SDK as mentioned and test it out, you will see the events with all the information under the dashboards (sentry.io).

**Comment by demoYang** [comment]
@marandaneto  
![image](https://user-images.githubusercontent.com/7134823/226851944-b68516f6-c9da-4bce-8396-426d7ca3989e.png)
this is my test，，no device  context,  no os  context ,no app context

**Comment by demoYang** [comment]
> Because the iOS and Android SDK will add this information later on

where it add ？

**Comment by marandaneto** [comment]
@demoYang can you share your SDK code snippet?
Are you following the correct steps? https://docs.sentry.io/platforms/flutter/#configure
Can you provide a Minimal reproducible example?

**Comment by demoYang** [comment]
@marandaneto  Thanks ,i check my code and my code is error , i use `Sentry.init` as `SentryFlutter.init`,  after change it work .
