### ISSUE TITLE
Make compressPayload for Web a NoOp instead of conditional import

### ISSUE THREAD

**Issue by rxlabz** [getsentry/sentry-dart#135]
https://github.com/getsentry/sentry-dart/pull/123#discussion_r510360432

**Comment by rxlabz** [comment]
@marandaneto @bruno-garcia  the compressPayload use `gzip` from `dart:io`, we need a conditional import here.
So can we remove the `options.compressPayload` and let the sdk automatically gzip if it's not in a browser context ?

**Comment by marandaneto** [comment]
ideally, we have a function called `encode` that does:

```
    headers['Content-Encoding'] = 'gzip';
    body = gzip.encode(body);
```

for non-web and does nothing (NoOp) for web, and the called function is imported dynamically with a conditional import.

so we dont need to repeat this line of the code `var body = utf8.encode(json.encode(data));` on the `bodyEncoder` method.
we can do this later as its not a breaking change for now and its already working.

**Comment by marandaneto** [comment]
#138
