### ISSUE TITLE
Duplicate breadcrumbs in transaction event

### ISSUE THREAD

**Issue by Maatteogekko** [getsentry/sentry-dart#1353]
_Platform:_
- [ ]  Dart
- [x]  Flutter Android or iOS
- [ ]  Flutter Web

_IDE:_
- [x]  VSCode
- [ ]  IntelliJ/AS
- [ ]  XCode
- [ ]  Other, which one?

_split-debug-info and obfuscate (Flutter Android or iOS) or CanvasKit (Flutter Web):_
- [ ]  Enabled
- [x]  Disabled

_Platform installed with:_
- [x] pub.dev
- [ ] GitHub

Output of the command `flutter doctor -v` below:

```
[✓] Flutter (Channel stable, 3.7.7, on macOS 13.2.1 22D68 darwin-arm64, locale en-IT)
    • Flutter version 3.7.7 on channel stable at /Users/gekko/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2ad6cd72c0 (2 weeks ago), 2023-03-08 09:41:59 -0800
    • Engine revision 1837b5be5f
    • Dart version 2.19.4
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/gekko/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.76.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (4 available)
    • sdk gphone arm64 (mobile)  • emulator-5554                        • android-arm64  • Android 11 (API 30) (emulator)
    • iPhone 14 Pro Max (mobile) • 54BE6178-C130-4FDD-BD57-5F0121018953 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-2 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 13.2.1 22D68 darwin-arm64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 111.0.5563.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

The version of the SDK (See pubspec.lock):
**7.2.0**

---
I have the following issue:

I am using a transaction in an onTap callback in the following way:

```dart
() async {
  final transaction = Sentry.getSpan()?.startChild(name) ??
      Sentry.startTransaction(
        name,
        operation,
        customSamplingContext: data,
        bindToScope: true,
      );

  await Future.delayed(const Duration(seconds: 2), transaction.finish);
}
```

When I go to inspect the transaction event on the dashboard I see duplicated breadcrumbs. This only happens for transaction events, normal issues are OK. This happens only on Android (tested on iOS simulator and Android emulator).

Checking the transaction in the `beforeSendTransaction` callback I don't see duplicated breadcrumbs, so I guess the issue is on the native SDK side? Turning on debug logs I see that the envelope sen to the server already contains duplicated breadcrumbs.

**Steps to reproduce:**

- generate some breadcrumbs
- start a transaction and finish it after some time
- check on sentry's dashboard (or debug logs) the breadcrumbs reported for the transaction's event

**Actual result:**
- I see duplicated breadcrumbs on sentry's dashboard (or debug logs)

**Expected result:**
- I don't see the duplicated breadcrumbs on the dashboard (and the logs)

**Comment by marandaneto** [comment]
Thanks for reporting @Maatteogekko we'll check it.
@denrase can you take a look since you did a fix related to that?

**Comment by denrase** [comment]
Thx @Maatteogekko, i will check this out.
