### ISSUE TITLE
Run `format` and `fix` on CI and commit directly

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-dart#1357]
### Description

Similar to https://github.com/getsentry/sentry-cocoa/blob/main/.github/workflows/format-code.yml

It should do for all the packages that run the analyzers.

**Comment by ueman** [comment]
You could additionally run `dart fix --apply`. That would also fix smaller issues, which can be automatically fixed. See https://dart.dev/tools/dart-fix. The list at https://dart-lang.github.io/linter/lints/ also lists which lints have an auto-fix available.

**Comment by marandaneto** [comment]
> You could additionally run `dart fix --apply`. That would also fix smaller issues, which can be automatically fixed. See [dart.dev/tools/dart-fix](https://dart.dev/tools/dart-fix). The list at [dart-lang.github.io/linter/lints](https://dart-lang.github.io/linter/lints/) also lists which lints have an auto-fix available.

Good idea, so not only the formatting but also fixing small issues :)
