### ISSUE TITLE
Flutter Web: stack trace is not minified

### ISSUE THREAD

**Issue by yerkejs** [getsentry/sentry-dart#1358]
_Platform:_
- [x]  Flutter Web

_IDE:_
- [x]  VSCode

_split-debug-info and obfuscate (Flutter Android or iOS) or CanvasKit (Flutter Web):_
- [x]  Enabled

_Platform installed with:_
- [x] pub.dev

The version of the SDK (See pubspec.lock):
Sentry: 6.20.1
sentry_dart_plugin: 1.0.0-beta.2

---
I have the following issue:

StackTrace is not minified well, I can't see context of code related to the exception. 
This is how we init SDK, release and dist is automatically bound. 
<img width="399" alt="Снимок экрана 2023-03-27 в 3 40 38 PM" src="https://user-images.githubusercontent.com/33483071/227931340-5ea51038-2674-478b-ae48-77f680e39a88.png">

But StackTrace is minified as seen in this screenshot.
<img width="1142" alt="Снимок экрана 2023-03-27 в 3 41 16 PM" src="https://user-images.githubusercontent.com/33483071/227931472-e818b4d1-aefa-4a55-a5a4-62b13f2d37d1.png">

We use `sentry_dart_plugin` with param `upload_source_maps: true`. What's wrong ?

**Comment by marandaneto** [comment]
Can you double check the [last item of this section](https://github.com/getsentry/sentry-dart-plugin#troubleshooting)?
Have you built your app using the `--source-maps` param?
The `release` and `dist` should match, can you link me to an sentry.io event?

**Comment by yerkejs** [comment]
@marandaneto yes I built with that command

**Comment by yerkejs** [comment]
@marandaneto 

https://wio-bank-pjsc.sentry.io/share/issue/f7905d4e2cfa4b5fac5d0734fd9aea1c/

**Comment by marandaneto** [comment]
@yerkejs for some reason this event does not have `release` nor `dist`, can you enable `debug: true` and check out the logs?
Check the `[LoadReleaseIntegration](https://github.com/getsentry/sentry-dart/blob/main/flutter/lib/src/integrations/load_release_integration.dart)` integration.
The `release` and `dist` of the event itself should match the one from the uploaded source maps.
I do see uploaded source maps, but the events don't have a release and dist.

**Comment by yerkejs** [comment]
sorry, this one: https://wio-bank-pjsc.sentry.io/share/issue/b6b15db346f741f38cff8aba73e912ab/

**Comment by yerkejs** [comment]
@marandaneto the release and dist are present

**Comment by marandaneto** [comment]
@yerkejs thanks, we'll check this out.
Does it happen for every error or just a few of them? What's your Flutter/Dart version?

**Comment by yerkejs** [comment]
To all of them, Flutter: 3.0.5

**Comment by kamilogorek** [comment]
We are not able to apply source context as `sourceContents` is missing from your map file, and uploaded source files doesnt match the values from `sources` array in the very sam sourcemap file. I have 0 knowledge about Flutter tooling, but this is the main cause.

**Comment by marandaneto** [comment]
@yerkejs can you try out locally, using the latest Flutter or providing a minimal reproducible example? we run our sample locally and sentry symbolicate everything correctly.

**Comment by marandaneto** [comment]
> We are not able to apply source context as `sourceContents` is missing from your map file, and uploaded source files doesnt match the values from `sources` array in the very sam sourcemap file. I have 0 knowledge about Flutter tooling, but this is the main cause.

Thanks @kamilogorek 
I can take it from here.

**Comment by yerkejs** [comment]
@marandaneto how `sourceContents` can be missing if we use sentry's plugin for uploading

**Comment by marandaneto** [comment]
@yerkejs that's why we need more info, maybe the source maps are corrupted or something.

**Comment by marandaneto** [comment]
@yerkejs any news here? can you provide more info? See https://github.com/getsentry/sentry-dart/issues/1358#issuecomment-1486994564

**Comment by marandaneto** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
