### ISSUE TITLE
SentryUserInteractionWidget: add support for PopupMenuButton and PopupMenuItem

### ISSUE THREAD

**Issue by sstasi95** [getsentry/sentry-dart#1360]
Currently SentryUserInteractionWidget doesn't support PopupMenuButton and PopupMenuItem, so breadcrumbs are not added when interacting with these widgets. It would be really nice to add support for them.

This feature is for Flutter only.

**Comment by marandaneto** [comment]
@sstasi95 thanks, we will take a look.
