### ISSUE TITLE
Errors are not reported in the apprunner function

### ISSUE THREAD

**Issue by BentEngbers** [getsentry/sentry-dart#1368]
_Platform:_
- [ ]  Dart
- [x]  Flutter Android or iOS
- [ ]  Flutter Web

_IDE:_
- [x]  VSCode
- [ ]  IntelliJ/AS
- [ ]  XCode
- [ ]  Other, which one?

_split-debug-info and obfuscate (Flutter Android or iOS) or CanvasKit (Flutter Web):_
- [ ]  Enabled
- [x]  Disabled

_Platform installed with:_
- [x] pub.dev
- [ ] GitHub

Output of the command `flutter doctor -v` below:
```
[✓] Flutter (Channel stable, 3.7.7, on macOS 13.1 22C65 darwin-arm64, locale en-NL)
    • Flutter version 3.7.7 on channel stable at /Users/bent/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2ad6cd72c0 (3 weeks ago), 2023-03-08 09:41:59 -0800
    • Engine revision 1837b5be5f
    • Dart version 2.19.4
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/bent/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.76.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.1 22C65 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 109.0.5414.87

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```
The version of the SDK (See pubspec.lock):
**7.1.0**

---
I have the following issue:

Sentry does not output errors in the console that are thrown in the `appRunner function`

**Steps to reproduce:**
- Throw an error in the appRunner, with debug on 
```dart
  await SentryFlutter.init(
    (options) {
      options.dsn = "DSN";
      options.tracesSampleRate = 1.0;
      options.diagnosticLevel = SentryLevel.info;
      options.debug = kDebugMode;
    },
    appRunner: () async {
      throw Error();
      });
```
**Actual result:**
- No output

**Expected result:**
- The error to be shown in the logs

**Comment by marandaneto** [comment]
@BentEngbers this is a known issue but it has to be like this because of Flutter <= 3.3 compatibility, `appRunner` has to be run within the `runZonedGuarded`, and at this moment the SDK isn't fully functional.

If you are using Flutter >= 3, you could skip the `appRunner` and run your app after the SDK is fully initiated because the `PlatformDispatcher.onError` does not have this limitation (this replaces the `runZonedGuarded`).
Can you try it out?

```
await SentryFlutter.init(
    (options) {
      options.dsn = "DSN";
      options.tracesSampleRate = 1.0;
      options.diagnosticLevel = SentryLevel.info;
      options.debug = kDebugMode;
    },
```

```
runApp(MyApp())
throw Error();
```

**Comment by BentEngbers** [comment]
I have updated sentry to 7.3.0, and i have removed the apprunner parameter, calling runApp after initialising sentry. 
Ive tried throwing an Error before and after runApp, but Sentry/flutter still does not report it.
I am running in debugMode ofcourse.

**Comment by marandaneto** [comment]
@BentEngbers I can't reproduce that, tried locally and it works out, can you provide a minimal reproducible example?

**Comment by BentEngbers** [comment]
Ive managed to track down the issue. Flutter did rebuild properly between builds. 
thanks for your time.
