### ISSUE TITLE
Version 7 broke web builds

### ISSUE THREAD

**Issue by mnordine** [getsentry/sentry-dart#1369]
```
$ webdev build
[WARNING] build_web_compilers:entrypoint on web/main.dart: Skipping compiling main|web/main.dart with dart2js because some of its
transitive libraries have sdk dependencies that are not supported on this platform:
sentry|lib/src/sentry_isolate_extension.dart
sentry|lib/src/sentry_isolate.dart
```
Note: Dart SDK `2.19.5`

**Comment by marandaneto** [comment]
@mnordine are you using the new extension directly into your code? this is not available for the Web so you have to do a conditional import.
The SDK itself does that for its usage, and we are compiling our web builds just fine, can you provide a minimal reproducible example if that's not the case?

**Comment by mnordine** [comment]
> are you using the new extension directly into your code?

No, we are not.

**Comment by ueman** [comment]
https://github.com/getsentry/sentry-dart/blob/f2db4ece59961760d0017bb7b0592fc561ab79f0/dart/lib/sentry.dart#L40-L41

should be moved into the `sentry_io.dart` file. Right now they are in the cross platform barrel file

**Comment by marandaneto** [comment]
> export 'src/sentry_isolate_extension.dart'; 
>  export 'src/sentry_isolate.dart';

this is just the export.

```
❯ webdev build
[INFO] Building new asset graph completed, took 1.6s
[INFO] Checking for unexpected pre-existing outputs. completed, took 0ms
[INFO] Running build completed, took 189ms
[INFO] Caching finalized dependency graph completed, took 217ms
[INFO] Creating merged output dir `build` completed, took 129ms
[INFO] Writing asset manifest completed, took 1ms
[INFO] Succeeded after 552ms with 0 outputs (3392 actions)
```

as long as you don't import it, it should be ok, can you provide a minimal reproducible example?

**Comment by mnordine** [comment]
No idea why you're asking me to give you an example, @ueman already showed you **exactly** what's wrong. You're not using conditional exports. You're just straight exporting a file with `dart:isolate` which isn't supported for the web.

> and we are compiling our web builds just fine

Given the above, I don't see how you could be.

**Comment by marandaneto** [comment]
@mnordine please check this comment https://github.com/getsentry/sentry-dart/issues/1369#issuecomment-1490203806
Also edit your issue description with the `Bug report` template with as much information as possible, as of now, I can't reproduce your issue.

**Comment by mnordine** [comment]
> I can't reproduce your issue.

What exactly did you try?

**Comment by mnordine** [comment]
```yaml
name: sentry_bug
description: An absolute bare-bones web app.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  sentry: ^7.4.0

dev_dependencies:
  build_runner: ^2.3.0
  build_web_compilers: ^3.2.0
  lints: ^2.0.0

```
```dart
import 'dart:html';
import 'package:sentry/sentry.dart';

void main() {
  querySelector('#output')?.text = 'Your Dart app is running.';
}
```
```
$ webdev build
[WARNING] build_web_compilers:entrypoint on web/main.dart: Skipping compiling sentry_bug|web/main.dart with dart2js because some of its
transitive libraries have sdk dependencies that are not supported on this platform:

sentry|lib/src/sentry_isolate_extension.dart
sentry|lib/src/sentry_isolate.dart
```
Note you get the same error with DDC and `webdev serve`

**Comment by marandaneto** [comment]
> > I can't reproduce your issue.
> 
> What exactly did you try?

With a bare-bones Fluter web app, apparently you're trying with a bare-bones Dart web app?
Can you try a Flutter web app?

**Comment by mnordine** [comment]
I didn't create the bug for Flutter. In fact, I didn't mention it anywhere. I don't use it at all. Are you not taking bugs for web unless Flutter is somehow used? Do you not test for dart web?

**Comment by marandaneto** [comment]
https://github.com/getsentry/sentry-dart/tree/main/dart/example_web is built during CI so we do test pure Dart web, but as you can see this is a `[WARNING]` and there's no flag such as `break-build-for-warnings`.

By using one of our templates https://github.com/getsentry/sentry-dart/blob/main/.github/ISSUE_TEMPLATE/BUG_REPORT.md all of this confusion could be avoided leading to a faster solution.

Flutter web is way more popular than Dart web hence that's what I've tested first and only.

Sharing a minimal reproducible example also speeds up the triaging, testing and eventually fixing, but it's hard with incomplete bug reports.

Appreciate the patience, I can reproduce this now, will review/merge tomorrow.
