### ISSUE TITLE
It is a ridiculouse mistake that transaction duration was more than one hour

### ISSUE THREAD

**Issue by philos3** [getsentry/sentry-dart#1376]
### Platform

Flutter Mobile

### Obfuscation

Enabled

### Debug Info

Enabled

### Doctor

[✓] Flutter (Channel stable, 3.3.9, on macOS 12.5 21G72 darwin-arm, locale zh-Hans-CN)
    • Flutter version 3.3.9 on channel stable at /Users/linzechi/fvm/versions/3.3.9
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (4 months ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/linzechi/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Library/Java/JavaVirtualMachines/temurin-11.jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment Temurin-11.0.16.1+1 (build 11.0.16.1+1)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.12.0

[!] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

### Version

7.0.0

### Steps to Reproduce

I dont know how to reproduct it 

### Expected Result

get transaction duration accuracy

### Actual Result

It is a ridiculouse mistake that transaction duration was more than one hour,I dont know how it happance

<img width="851" alt="image" src="https://user-images.githubusercontent.com/8424317/229364013-c49af2f9-b753-4bff-800d-3e17e08c37c5.png">

https://sentry.deepcoin.ski/api/0/projects/deepcoin/app/events/040ce2096a064e21a918a0bacf62f6cf/json/

### Are you willing to submit a PR?

None

**Comment by marandaneto** [comment]
@philos3 thanks for raising this.
Your event is self hosted so I cannot take a look.
Can you share more information, how are you initing the Sentry SDK and its integrations?
Can you reproduce the issue?
Does that happen only for this screen?
Can you share how you are moving from and out of this screen, maybe the screen is never receiving the commands `didPop`?
Transactions should not exceed 3 seconds, that's the default.
Do you create spans that never finish or something like this?

**Comment by marandaneto** [comment]
@philos3 any more info here?

**Comment by marandaneto** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
