### ISSUE TITLE
How to verify that Sentry.captureEvent() was called in a unit test?

### ISSUE THREAD

**Issue by GP4cK** [getsentry/sentry-dart#1380]
### Problem Statement

Assuming I have a function like this:

```dart
void emitEvent() {
  Sentry.captureEvent(...);
}
```

I would like to write a unit test to make sure that Sentry.captureEvent was called. However, since it's a static method, I can't mock it.

### Solution Brainstorm

I looked at the implementation of Sentry and all the `captureX()` methods use a Hub. It would be great if there was a setter decorated with `@visibleForTesting` which would allow to pass our own Mock and then verify whatever.

I looked at the existing tests at `dart/test/sentry_test.dart` but it seems I would need to copy/paste the entire class `MockSentryClient` which has a lot of internal stuff from the library. It seems a bit overkill for my use case...

### Are you willing to submit a PR?

Yes

**Comment by marandaneto** [comment]
@GP4cK Good question.
You can make a wrapper on top of `Sentry.captureEvent` and assert your wrapper instead.
Some testing frameworks are able to assert on static calls, but not all.
You can also do `Sentry.bindClient(client)` and mock the `client` and assert its calls, you have to mock the whole interface but it'd work.
`Hub` and `SentryClient` have a pretty similar interface so I believe this would work for you.

**Comment by GP4cK** [comment]
For future readers, I've made it work with `mocktail` in relatively a few lines of code:

```dart
class MockSentryClient extends Mock implements SentryClient {}

final sentryClient = MockSentryClient();
setUpAll(() async {
  registerFallbackValue(SentryEvent());
  registerFallbackValue(Scope(SentryOptions()));
  await Sentry.init((options) async {
    options.dsn = 'dsn';
  });
  Sentry.bindClient(sentryClient);
});

test('your test', () async {
  functionThatLogs();
  await Future.delayed(Duration.zero);
  verify(() => sentryClient.captureEvent(
     any(),
     stackTrace: any(named: 'stackTrace'),
     scope: any(named: 'scope'),
  )).called(1);
});
