### ISSUE TITLE
Contradicting info in the README about loadStructuredData in sentry_flutter

### ISSUE THREAD

**Issue by vincevargadev** [getsentry/sentry-dart#1381]
### Platform

Flutter

### Version

7.4.0

### Steps to Reproduce

It's somewhat confusing to me whether `loadStructuredData` is still experimental and whether using it could lead to bugs.

The [README in 7.4.0](https://pub.dev/documentation/sentry_flutter/7.4.0/) says:

> Tracing for AssetBundle.loadStructuredData() is currently disabled. It's hidden by the enableStructuredDataTracing flag and considered experimental. Using it could lead to bugs. We recognize the irony.

The [Docs](https://docs.sentry.io/platforms/flutter/performance/instrumentation/automatic-instrumentation/#assetbundle-instrumentation) says:

> The loadStructuredData is an opt-out feature. The following example shows how to disable it:

The [code](https://github.com/getsentry/sentry-dart/blob/4b488ab48bb730b3533894920fa72294405bf6a1/flutter/lib/src/sentry_asset_bundle.dart#L36-L40) says:

```dart
  SentryAssetBundle({
    // ...
    bool enableStructuredDataTracing = true,
  }) /* ... */;
```

The [changelog](https://pub.dev/packages/sentry_flutter/changelog#700) says (7.0.0)

> * Enable APM features by default ([#1217](https://github.com/getsentry/sentry-dart/pull/1217))
>    * Enable by default
>      * enableStructuredDataTracing

### Expected Result

I expect all sources say the same thing. Potentially outdated README?

**Comment by ueman** [comment]
That feature is considered stable as mentioned in the changelog, and the docs/readme are just not updated to reflect that.

**Comment by marandaneto** [comment]
Good catch, https://github.com/getsentry/sentry-dart/pull/1383
