### ISSUE TITLE
Argument error occured when set `dio.addSentry()` but not tracing settings

### ISSUE THREAD

**Issue by ostk0069** [getsentry/sentry-dart#1386]
### Platform

Flutter Mobile

### Obfuscation

Disabled

### Debug Info

Disabled

### Doctor

[✓] Flutter (Channel stable, 3.7.7, on macOS 12.5 21G72 darwin-arm64, locale ja-JP)
    • Flutter version 3.7.7 on channel stable at /Users/s11080/fvm/versions/3.7.7
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2ad6cd72c0 (5 weeks ago), 2023-03-08 09:41:59 -0800
    • Engine revision 1837b5be5f
    • Dart version 2.19.4
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/s11080/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode_14.0.1.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.76.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.5 21G72 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 112.0.5615.49

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

### Version

7.4.0

### Steps to Reproduce

1. add dependencies for sentry_dart, sentry_dio
2. set `dio.addSentry();` for http breadcrumbs
3. disable tracing (do not set any tracing settings)
4. Error occured
```
[app]: ../../../../../.pub-cache/hosted/pub.dev/sentry_dio-7.4.0/lib/src/tracing_client_adapter.dart:68:61: Error: The argument type 'int?' can't be assigned to the parameter type 'int' because 'int?' is nullable and 'int' isn't.
[app]:       span?.status = SpanStatus.fromHttpStatusCode(response.statusCode);
```

### Expected Result

do not have any error when set `dio.addSentry();` but not tracing setting setups

### Actual Result

```
[app]: ../../../../../.pub-cache/hosted/pub.dev/sentry_dio-7.4.0/lib/src/tracing_client_adapter.dart:68:61: Error: The argument type 'int?' can't be assigned to the parameter type 'int' because 'int?' is nullable and 'int' isn't.
[app]:       span?.status = SpanStatus.fromHttpStatusCode(response.statusCode);
```

### Are you willing to submit a PR?

None

**Comment by marandaneto** [comment]
@ostk0069 what's the version of your `dio` library? v5.1.1 `response.statusCode` is an `int` field and not `int?`.
`TracingClientAdapter` is only added if `isTracingEnabled`.
Can you share more context, for example, your SDK init code snippet, etc? Thanks.

**Comment by ostk0069** [comment]
dio version is `4.0.6`

**Comment by krystofwoldrich** [comment]
@ostk0069 SDK version `7.0.0` and later support only Dio v5. Can you upgrade?

**Comment by ostk0069** [comment]
thanks, I understood the problem.
