### ISSUE TITLE
enableBreadcrumbTrackingForCurrentPlatform seems not to work properly

### ISSUE THREAD

**Issue by mafreud** [getsentry/sentry-dart#1387]
### Platform

Dart

### Obfuscation

Disabled

### Debug Info

Disabled

### Doctor

```yaml
sdk: ">=2.19.6 <3.0.0"
```

### Version

7.3.0

### Steps to Reproduce

1. add options.enableBreadcrumbTrackingForCurrentPlatform();
2. check Sentry dashboard
3. no breadcrumbs are collected

### Expected Result

breadcrumbs, such as memory pressure or native data.

### Actual Result

nothing

### Are you willing to submit a PR?

None

**Comment by brustolin** [comment]
Hello @mafreud. Where in the dashboard are you checking for breadcrumbs?

Breadcrumbs are attached to issues or transactions, therefore, if there is no issue or performance transaction being created there will be no breadcrumbs.

**Comment by krystofwoldrich** [comment]
Just noticed the issue specifies `Dart` but I believe this is `Flutter` SDK option.
Related code https://github.com/getsentry/sentry-dart/blob/e2d89fc73b84c81801b638f4be7c488d53b7960d/flutter/lib/src/sentry_flutter_options.dart#L241

**Comment by marandaneto** [comment]
@mafreud `enableBreadcrumbTrackingForCurrentPlatform` is the default for Flutter, so no need to call it directly, mind explaining what's the issue about? can you link me to a sentry issue?

**Comment by marandaneto** [comment]
@mafreud any news here?

**Comment by marandaneto** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
