### ISSUE TITLE
Add ignoreTransactions and ignoreErrors

### ISSUE THREAD

**Issue by smeubank** [getsentry/sentry-dart#1391]
### Background:
To further simplfiy ignoring certain events from being sent to sentry, it is also suggested to provide `ignoreTransactions` and `ignoreErrors`

More info here develop docs updated: https://develop.sentry.dev/sdk/features/#event-sampling

- [ ] ignoreErrors
- [ ] ignoreTransactions
- [ ] SDK docs

Info: don't forget about client reports

**Comment by marandaneto** [comment]
Check out if this should be reported in client reports and how, the discussion is in the meta issue.
