### ISSUE TITLE
Use `getExtraContext` on iOS

### ISSUE THREAD

**Issue by krystofwoldrich** [getsentry/sentry-dart#1401]
### Description

`sentry-cocoa` has a new method for HybridSDKs which exposes extra context data that originally were available only in `sentry-cocoa` client. 

https://github.com/getsentry/sentry-cocoa/pull/2855

RN implementation: https://github.com/getsentry/sentry-react-native/pull/2984

**Comment by marandaneto** [comment]
https://github.com/getsentry/sentry-dart/pull/1402
