### ISSUE TITLE
Sentry extension erroring when email present in the URL when passed through the sanitiser

### ISSUE THREAD

**Issue by vlazdra** [getsentry/sentry-dart#1412]
### Platform

Dart

### Obfuscation

Disabled

### Debug Info

Disabled

### Doctor

[✓] Flutter (Channel stable, 3.7.12, on macOS 13.1 22C65 darwin-arm64, locale en-RS)
    • Flutter version 3.7.12 on channel stable at /Users/vlazdra/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d9e56e694 (9 days ago), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/vlazdra/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • ANDROID_HOME = /Users/vlazdra/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Brave Browser.app/Contents/MacOS/Brave Browser

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] IntelliJ IDEA Community Edition (version 2023.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 73.0.4
    • Dart plugin version 231.8109.91

[✓] VS Code (version 1.77.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 13 (API 33) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 13.1 22C65 darwin-arm64
    • Chrome (web)                • chrome        • web-javascript • Brave Browser 112.1.50.121

[✓] HTTP Host Availability
    • All required HTTP hosts are available

### Version

7.5.0

### Steps to Reproduce

It might be reproducable if the URL contains an email address, not 100% sure that it will do.
I receive an unknown Dio error with this message: `FormatException: Invalid character (at character 9)` https://[Filtered]@EXAMPLE.COM

Removing the Dio extension: dioClient.addSentry(); "fixes" the issue.

### Expected Result

The parsing is successful.
Again, not sure if the parsing part actually fails, but I do see that Dio returning an Unknown error because of it.

### Actual Result

The URL that is being process looks like this:
https://staging.server.com/api/v4/auth/password/reset/email@example.com

Possible regression of this PR: https://github.com/getsentry/sentry-dart/pull/1327

### Are you willing to submit a PR?

No

**Comment by marandaneto** [comment]
@vlazdra Thanks for reporting.
Can you give more details about when this happens and which features you have enabled?
Is it adding breadcrumbs?
Is it capturing client errors?
Is it when measuring performance? (spans)

Please share your SDK init code snippet and the code snippet of when setting up `dio`, thanks.

**Comment by marandaneto** [comment]
The result here is wrong: https://github.com/getsentry/sentry-dart/blob/c4f16212929767441bfd4e416717e4eb54f10633/dart/lib/src/utils/http_sanitizer.dart#L63-L75
The output is `https://[Filtered]@example.com` for `urlDetails?.urlOrFallback` but `@example.com` is part of the email and not the URL or userInfo.
It's not throwing `FormatException` tho.

**Comment by marandaneto** [comment]
@denrase can you check this? probably the same problem [here](https://github.com/getsentry/sentry-java/blob/main/sentry/src/main/java/io/sentry/util/UrlUtils.java).

**Comment by vlazdra** [comment]
Hey @marandaneto! 👋 

This is the setup of the Sentry SDK:
```dart
  await SentryFlutter.init((options) {
    options.dsn = 'dsn value';
    // Set tracesSampleRate to 1.0 to capture 100% of transactions for performance monitoring.
    // We recommend adjusting this value in production.
    options.tracesSampleRate = 1.0;
    options.attachScreenshot = true;
  });
```

Regarding the Dio setup, it's pretty basic, I'm adding 5 different Interceptors but when I do enable the Sentry extensions that when I get the FormatException. Even if I remove all of my custom Interceptors and just leave the basic Dio setup and the Sentry extensions, it still errors with FormatException.
```dart
_dioClient.addSentry();
```


The worst things is that I'm unable to catch where exactly the issue is ocuring. The closest I thought where something might go wrong is with the new change.

Also, I'm not using Breadcrumbs directly at this stage, and nor am I using the Transaction option at this stage as well as Performance tracing.


Version of Sentry: 7.5.0 (both dart and flutter packages)
Version of Dio: 5.1.1

**Comment by marandaneto** [comment]
@vlazdra right, it's probably a different URL then, maybe similar to `https://staging.server.com/api/v4/auth/password/reset/email@example.com` but not exactly, which fails during parsing, is there any way to be 100% sure of its format? via crumbs, debugging, etc?
We'll check if there's a need to at least wrap the whole thing in a try/catch, if not yet.

**Comment by vlazdra** [comment]
@marandaneto I think I got it. At least where it fails to parse and throws a FormatException.

In the end it's a completely different place than what was reported, as per usual when it comes to these type of issues. 😄 

This line is the problem: https://github.com/getsentry/sentry-dart/blob/c4f16212929767441bfd4e416717e4eb54f10633/dio/lib/src/breadcrumb_client_adapter.dart#L64

<img width="774" alt="Screenshot 2023-04-28 at 14 00 34" src="https://user-images.githubusercontent.com/6934014/235142412-69473f76-87e0-4d11-9c86-46ca2c634edd.png">

**Comment by vlazdra** [comment]
It was this change that was introduced a month ago. I just came around to update the dependencies in my project.

https://github.com/getsentry/sentry-dart/commit/24f71aae695d5763d7ad28592191d95841f59b40#diff-88768c3d418bb22a5112992f1828b4a2a9ffcca36f9080b9b5127e962f6880d8R85

**Comment by marandaneto** [comment]
@vlazdra Right, that makes sense.
https://github.com/getsentry/sentry-dart/pull/1414
This fixes the issue with the error, another PR has to follow up to fix the formatting.

**Comment by vlazdra** [comment]
Closing the issue since the PR (https://github.com/getsentry/sentry-dart/pull/1414) has been merged.
Thansk @marandaneto 🙌

**Comment by marandaneto** [comment]
@krystofwoldrich raise a new issue and assign it to @denrase , related to https://github.com/getsentry/sentry-dart/issues/1412#issuecomment-1525603470
The format exception is fixed but not the formatting, the output is still wrong, thanks.
