### ISSUE TITLE
Correctly filter URL with an email address in it

### ISSUE THREAD

**Issue by krystofwoldrich** [getsentry/sentry-dart#1418]
### Description

Based on https://github.com/getsentry/sentry-dart/issues/1412#issuecomment-1525603470

This function doesn't filter out email addresses in URLs correctly.

https://github.com/getsentry/sentry-dart/blob/c4f16212929767441bfd4e416717e4eb54f10633/dart/lib/src/utils/http_sanitizer.dart#L63-L75

Example URL: [staging.server.com/api/v4/auth/password/reset/email@example.com](https://staging.server.com/api/v4/auth/password/reset/email@example.com)

The output is `https://[Filtered]@example.com` but `@example.com` is part of the email and not the URL or userInfo.

**Comment by marandaneto** [comment]
Btw also add tests for other symbols that may break the parsing or Regex, maybe there are more cases besides `@`.
