### ISSUE TITLE
Align http span data to convention

### ISSUE THREAD

**Issue by stefanosiano** [getsentry/sentry-dart#1422]
### Description

There are few http data keys that are different from our [convention](https://develop.sentry.dev/sdk/performance/span-data-conventions/)
I’m talking mainly about `method` and `response_body_size` that should be `http.method` and `http.response_content_length` in [breadcrumb](https://github.com/getsentry/sentry-dart/blob/main/dart/lib/src/protocol/breadcrumb.dart#L60) and [http span](https://github.com/getsentry/sentry-dart/blob/main/dart/lib/src/http_client/tracing_client.dart#L42)

**Comment by marandaneto** [comment]
@stefanosiano would you like to take this PR? so you get a filling of the SDK, PRs, code reviews, how to run tests, etc? I can guide :) it should be pretty much a ctrl c - ctrl v + fixing test.

**Comment by stefanosiano** [comment]
yeah, sure!
