### ISSUE TITLE
[sentry_dio] Expose all classes used on `addSentry() `

### ISSUE THREAD

**Issue by diegog-sf** [getsentry/sentry-dart#1425]
### Problem Statement

I want to create a custom `SentryDioClientAdapter`, I could clone the original file, make the changes and inject it directly to DIO, but I still want to keep other features added on `dio.addSentry()` so to do that I would need to copy all files because they're private, which would force me to fork the repo (something that we don't want). It would be great if we could create our own `addSentry()` but we need access to the classes used there

### Solution Brainstorm

Expose all the classes used on addSentry() so that we can create our own setup.

### Are you willing to submit a PR?

Yes

**Comment by marandaneto** [comment]
@diegog-sf Thanks for raising this.
They are just not `export` by default but you can still use them by importing directly.

Before exporting them by default, would you mind describing your use case? why do you need a custom `SentryDioClientAdapter`? what do you wanna achieve exactly?

**Comment by HudsonProenca-sf** [comment]
> @diegog-sf Thanks for raising this. They are just not `export` by default but you can still use them by importing directly.
> 
> Before exporting them by default, would you mind describing your use case? why do you need a custom `SentryDioClientAdapter`? what do you wanna achieve exactly?

The spans created by sentry_dio cannot be queried directly without accessing the underlying transaction. We tried to start transactions in each API request, this way we have more control over the transactions and it makes it easier to query them and have a better API performance idea. We would like to still keep sentry_dio's implementation, but the inner spans attached from sentry_dio are not being attached to the correct outer transactions.

This line in `tracing_client_adapter.dart` gets the current span, which is the first item on the StackItem list inside the `Hub`
`final currentSpan = _hub.getSpan();`
Our desired behavior is if could get the current span based on the current transaction name/path.

Something like `final currentSpan = _hub.getSpan(options.path);`
Or by using the SentryHeaders to know the correct current span.

Thinking in this way, it would be helpful if `addSentry` method exposes as a parameter the `SentryDioClientAdapter` (similar to the way it exposes the `Hub`).
And also if the lib exported some default classes that would be useful when overriding these adapters.

**Comment by krystofwoldrich** [comment]
@HudsonProenca-sf Could you describe an example Transaction/Span where the current implementation doesn't work?

For example, navigations start -> Transaction gets created -> loading new page -> initiates HTTP request -> spans for the request are created and attached to the transaction X but should not be.

**Comment by HudsonProenca-sf** [comment]
> @HudsonProenca-sf Could you describe an example Transaction/Span where the current implementation doesn't work?
> 
> For example, navigations start -> Transaction gets created -> loading new page -> initiates HTTP request -> spans for the request are created and attached to the transaction X but should not be.

I tried to draw the flow on [miro](https://miro.com/app/board/uXjVMJzFPZ4=/?share_link_id=828506707022).

Let me know if that makes sense

**Comment by marandaneto** [comment]
@diegog-sf The problem is that Dart is single-threaded so the SDK has the concept of a single Scope, meaning that only one living transaction in the scope is allowed, maybe in your use case the best is creating the transaction yourself and passing the instance around, so the hierarchy of transactions and spans will be correct.

There's no way to do this automatically on the SDK side, figuring out if the span X belongs to transaction A or B.
There are a few ideas on how to do this with Zones but we have not done this yet, See https://github.com/getsentry/sentry-dart/issues/1343

Feel free to open a draft PR to showcase your idea, closing it in favor https://github.com/getsentry/sentry-dart/issues/1343 for now.
