### ISSUE TITLE
"extra" data is truncated for medium-sized strings such as a full stack trace

### ISSUE THREAD

**Issue by fzyzcjy** [getsentry/sentry-dart#1431]
### Platform

Flutter Mobile

### Obfuscation

Enabled

### Debug Info

Enabled

### Doctor

unrelated

### Version

https://github.com/fzyzcjy/sentry-dart

### Steps to Reproduce

Putting medium-sized string in `extra` field. In my case, it is just a full stack trace (see screenshot below for an example)

I have checked https://github.com/getsentry/sentry-dart/blob/main/dart/lib/src/sentry_options.dart but seems no option.

### Expected Result

see it

### Actual Result

truncated. For example:

![image](https://github.com/getsentry/sentry-dart/assets/5236035/9a79cb3f-dad0-4e95-b403-a79021c34a5f)
![image](https://github.com/getsentry/sentry-dart/assets/5236035/ee648e9a-d609-48d2-91ec-7c61b5142fe1)

### Are you willing to submit a PR?

Yes

**Comment by marandaneto** [comment]
@fzyzcjy is this truncated in the UI? If so, this should be moved to https://github.com/getsentry/sentry
You can always open the raw JSON in the sentry UI for copying the whole thing.

**Comment by fzyzcjy** [comment]
No, the raw JSON seems truncated: https://rzzsdxx.sentry.io/api/0/projects/xx/xx/events/xxxxx/json/

![image](https://github.com/getsentry/sentry-dart/assets/5236035/89e489c5-d98a-4e53-8621-7d3bfad96f39)

**Comment by marandaneto** [comment]
@fzyzcjy the backend probably truncates then, can you try setting it to `event.contexts` instead?
Again, the SDK sends it as it is, so it's a https://github.com/getsentry/sentry issue, probably internals, not sure where it'd make more sense, another option is sending it as attachments https://docs.sentry.io/platforms/flutter/enriching-events/attachments/

**Comment by fzyzcjy** [comment]
>  can you try setting it to event.contexts instead?

Will it have a larger limit? Indeed, I would appreciate it if I could know where those limits are documented.

Attachments look good, but I hope it can be viewed directly in the webpage, which is easier to copy and read, instead of having to download them ;)

**Comment by marandaneto** [comment]
@fzyzcjy you can preview some attachment types directly in the UI, just use the right format and extension when creating the attachment, a `txt` would do.
I am checking internally if we have the char limits documented somewhere.

**Comment by fzyzcjy** [comment]
Thanks!

> I am checking internally if we have the char limits documented somewhere.

Looking forward to the reply

**Comment by marandaneto** [comment]
@fzyzcjy I am following up here https://github.com/getsentry/relay/issues/2109 but I'm unsure about `contexts` yet, have you tried?
`contexts` have even a smaller bag size https://github.com/getsentry/relay/blob/c38cd0a32e1d9c8f27c3e50e1e599495e49e3ee3/relay-general/src/protocol/contexts/mod.rs#L120 but I am waiting for confirmation.

**Comment by fzyzcjy** [comment]
Thanks for the info! I have not tried it, but if it is "a even smaller bag size" then I will not bother to try ;)

**Comment by marandaneto** [comment]
https://github.com/getsentry/relay/issues/2110 is the issue to document all the fields, as of now, I will close this issue.
And for the original problem, let's keep discussing on https://github.com/getsentry/sentry-dart/issues/1429 since ideally you don't need to attach the stack trace as additional data, and attachments is an alternative if you really want.

**Comment by fzyzcjy** [comment]
Thank you!
