### ISSUE TITLE
Performance page has always been empty

### ISSUE THREAD

**Issue by NullCrazy** [getsentry/sentry-dart#1434]
### Platform

Flutter Mobile

### Obfuscation

Enabled

### Debug Info

Enabled

### Doctor

Flutter (Channel stable, 3.7.12, on macOS 13.0 22A8380 darwin-arm64, locale
    zh-Hans-CN)
    • Flutter version 3.7.12 on channel stable at /Users/xingguolei/flutter
    ! Warning: `dart` on your path resolves to
      /usr/local/Cellar/dart/2.17.6/libexec/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/xingguolei/flutter. Consider adding
      /Users/xingguolei/flutter/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d9e56e694 (3 weeks ago), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/xingguolei/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)

[✓] IntelliJ IDEA Community Edition (version 2022.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (3 available)
    • Mi 10 (mobile)  • bb8f12c2 • android-arm64  • Android 12 (API 31)
    • macOS (desktop) • macos    • darwin-arm64   • macOS 13.0 22A8380 darwin-arm64
    • Chrome (web)    • chrome   • web-javascript • Google Chrome 112.0.5615.137

### Version

sentry_flutter: ^7.5.2 

### Steps to Reproduce

runZonedGuarded(() async {
    await SentryFlutter.init(
      (options) {
        options.dsn =
            'https://273b300f85304bce91a6383bf0f4dc8a@o4505079180886016.ingest.sentry.io/4505079185276928';
        options.tracesSampleRate = 1.0;
        options.debug = true;
        options.sendDefaultPii = true;
        options.maxRequestBodySize = MaxRequestBodySize.small;
        options.maxResponseBodySize = MaxResponseBodySize.small;
      },
    );
    runApp(DefaultAssetBundle(
      bundle: SentryAssetBundle(),
      child: MyApp(),
    ));
  }, (exception, stackTrace) async {
    await Sentry.captureException(exception, stackTrace: stackTrace);
  });

### Expected Result

performance page  is no empty!

### Actual Result

![image](https://github.com/getsentry/sentry-dart/assets/11511208/5e556f99-b7b7-429e-bfde-d871e56ac98a)

### Are you willing to submit a PR?

None

**Comment by marandaneto** [comment]
@NullCrazy you don't need a `runZonedGuarded`, the SDK does it automatically.
To be able to see transactions, be sure to set up the routing instrumentation https://docs.sentry.io/platforms/flutter/performance/instrumentation/automatic-instrumentation/#routing-instrumentation or https://docs.sentry.io/platforms/flutter/performance/instrumentation/automatic-instrumentation/#gorouter-instrumentation
Probably https://docs.sentry.io/platforms/flutter/performance/instrumentation/automatic-instrumentation/#user-interaction-instrumentation and some other integrations that are able to create spans automatically as well.
Last case, you can set up your own transactions manually https://docs.sentry.io/platforms/flutter/performance/instrumentation/custom-instrumentation/

**Comment by NullCrazy** [comment]
Hello! @marandaneto 
This is my code.
import 'dart:async';

import 'package:dio/dio.dart';
import 'package:flutter/material.dart';
import 'package:sentry_dio/sentry_dio.dart';
import 'package:sentry_flutter/sentry_flutter.dart';

void main() async {
  await SentryFlutter.init(
    (options) {
      options.dsn =
          'https://273b300f85304bce91a6383bf0f4dc8a@o4505079180886016.ingest.sentry.io/4505079185276928';
      options.tracesSampleRate = 1.0;
      options.debug = true;
      options.sendDefaultPii = true;
      options.maxRequestBodySize = MaxRequestBodySize.small;
      options.maxResponseBodySize = MaxResponseBodySize.small;
    },
    appRunner: () => runApp(DefaultAssetBundle(
      bundle: SentryAssetBundle(),
      child: const MyApp(),
    )),
  );
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      navigatorObservers: [SentryNavigatorObserver()],
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() async {
    setState(() {
      _counter++;
    });
    final dio = Dio();
    dio.addSentry();

    final transaction = Sentry.startTransaction(
      'dio-web-request',
      'request',
      bindToScope: true,
    );

    try {
      final response =
          await dio.get<Map<String, Object?>>('https://api.github.com/search/users?q=aa');
      print(response.toString());
      transaction.status = SpanStatus.fromHttpStatusCode(response.statusCode ?? -1);
    } catch (exception) {
      print(">>>>$exception");
      transaction.throwable = exception;
      transaction.status = const SpanStatus.internalError();
    } finally {
      await transaction.finish();
    }

    await Sentry.close();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}
The exceptions I created can be reported，But I can't receive any performance information.Can you tell me what configuration issues there are?

![image](https://github.com/getsentry/sentry-dart/assets/11511208/7da0b149-bec2-4643-a921-3251a49ef3de)
![image](https://github.com/getsentry/sentry-dart/assets/11511208/b194a1da-c96f-4229-ade4-0f30f1ac0c4f)
The following are some logs.
[log.txt](https://github.com/getsentry/sentry-dart/files/11447582/log.txt)

**Comment by marandaneto** [comment]
@NullCrazy can you provide a git repository where I can just execute it?

**Comment by NullCrazy** [comment]
This is my code repository, and I'm not sure why I'm not getting performance data when it runs, but crash data is being uploaded successfully. Can you help me identify the issue? Thank you. @marandaneto 
[https://github.com/NullCrazy/test_sentry.git](url)

**Comment by marandaneto** [comment]
When using `SentryNavigatorObserver`
See https://docs.sentry.io/platforms/flutter/performance/instrumentation/automatic-instrumentation/#routing-instrumentation

> If the transaction has no spans, the transaction will be dropped and not sent to Sentry, the reason is that there's no callback to identify when the screen has been loaded, so we rely on the child spans.

Since you don't have spans in the screen `MyHomePage` loading, no HTTP requests nor anything, this transaction is dropped.

When you click on `_incrementCounter`, I see the `dio-web-request` transaction using my testing project, so it works normally.

Ps: you don't need to call `await Sentry.close();`, there's no reason for that unless you want to disable the SDK forever.

**Comment by marandaneto** [comment]
@NullCrazy can you link me to your org/project under sentry.io? I wanna check if your account has performance quota yet, or you can check yourself as well.

**Comment by NullCrazy** [comment]
Oh, I see where my mistake was now. I shouldn't have called await Sentry.close();. Thank you so much for your help. I can now see the network performance data. @marandaneto

**Comment by AhmedEzio47** [comment]
@marandaneto I've gone through the [performance documentation](https://docs.sentry.io/platforms/flutter/performance/?original_referrer=https%3A%2F%2Fwww.google.com%2F), and as far as I understood, all the features are enabled by default, including, for example, App Start Instrumentation, Slow and Frozen Frames, all I need to do is to set the sample rate like this `options.tracesSampleRate = 1.0;` and add `SentryNavigationObserver` to the list of observers. Am I missing something? Because the performance page is empty for me too. Thanks.

**Comment by marandaneto** [comment]
Likely because of [that](https://docs.sentry.io/platforms/flutter/performance/instrumentation/automatic-instrumentation/):

> If the transaction has no spans, the transaction will be dropped and not sent to Sentry, the reason is that there's no callback to identify when the screen has been loaded, so we rely on the child spans.

You either need to create spans manually or set up more auto instrumentation to create spans and not only transactions.
I believe the sample and docs have to address this better since it's a recurrent problem (it's just a hunch, though it can be something else).

I'm not part of the Sentry staff anymore so feel free to raise a new issue and check out with them.

**Comment by AhmedEzio47** [comment]
OK, thank you for the quick response, I'll try to raise a new issue.
