### ISSUE TITLE
iOS context not being attached

### ISSUE THREAD

**Issue by davidhsoftware** [getsentry/sentry-dart#1437]
### Platform

Flutter Mobile

### Obfuscation

Disabled

### Debug Info

Disabled

### Doctor

Dart 3.0.0
Flutter (Channel stable, 3.10.0, on macOS 12.6 21G115 darwin-arm64, locale en-AU)

### Version

7.5.2

### Steps to Reproduce

1. Run Sentry.captureException() on an iPhone 8 running the specified versions

### Expected Result

See iOS context attached in Sentry

### Actual Result

iOS context not attached in Sentry

`factory Contexts.fromJson(Map<String, dynamic> data)`  runs `SentryDevice.fromJson(Map.from(data[SentryDevice.type]))` which breaks on `type 'int' is not a subtype of type 'double?'`

~~It looks like `data["device"]["screen_height_pixels"]` and `data["device"]["screen_width_pixels"]` are `double`, being assigned to `SentryDevice.screenHeightPixels` and `SentryDevice.screenWidthPixels` which are `int?`~~

Edit: these are indeed already casted, will update when I have access to the stack trace

### Are you willing to submit a PR?

None

**Comment by marandaneto** [comment]
@davidhsoftware can you copy and paste the error? the full stack trace?
The code already cast it to `?.toInt()` so this should not be an issue, I can't reproduce it locally.

**Comment by kuhnroyal** [comment]
Maybe related to https://github.com/getsentry/sentry-dart/issues/1432 which is the same error message?

**Comment by ueman** [comment]
Yeah, but this one is talking about the screen resolution.

**Comment by kuhnroyal** [comment]
> It looks like ...

@davidhsoftware Is this on iOS 16.4 and do you have a stacktrace?

**Comment by davidhsoftware** [comment]
Hi @kuhnroyal @marandaneto 

I will send the stack trace and iOS version as soon as I am able (in ~13 hours). Thanks!

**Comment by marandaneto** [comment]
@ueman the screen resolution already had this issue in the past, and there are tests about that.

**Comment by davidhsoftware** [comment]
Apologies for the misleading guess, this was the same as the batteryLevel conversion issue in #1432
