### ISSUE TITLE
sentry_flutter 7.5.2 incompatible with package_info_plus 4.0.0

### ISSUE THREAD

**Issue by noti0nS** [getsentry/sentry-dart#1442]
### Platform

Dart

### Obfuscation

Enabled

### Debug Info

Enabled

### Doctor

[√] Flutter (Channel stable, 3.10.0, on Microsoft Windows [Version 10.0.22624.1755], locale en-US)
    • Flutter version 3.10.0 on channel stable at C:\Users\Desktop\fvm\versions\stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 84a1e904f4 (3 days ago), 2023-05-09 07:41:44 -0700
    • Engine revision d44b5a94c9
    • Dart version 3.0.0
    • DevTools version 2.23.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at C:\Users\Desktop\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.11.26)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.11.33529.622
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2022.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[√] VS Code (version 1.78.2)
    • VS Code at C:\Users\Desktop\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.64.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22624.1755]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 112.0.5615.138
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 113.0.1774.42

[√] Network resources
    • All expected network resources are available.

• No issues found!

### Version

7.5.2

### Steps to Reproduce

Create a flutter project where depends both sentry_flutter and package_info_plus. Both with your latest versions as well.

### Expected Result

Fetch all dependencies with success.

### Actual Result

Resolving dependencies...
Because sentry_flutter 7.5.2 depends on package_info_plus >=1.0.0 <4.0.0 and no versions of sentry_flutter match >7.5.2 <8.0.0, sentry_flutter ^7.5.2 requires package_info_plus >=1.0.0 <4.0.0.
So, because prodigy_app depends on both sentry_flutter ^7.5.2 and package_info_plus ^4.0.0, version solving failed.
exit code 1

### Are you willing to submit a PR?

None

**Comment by marandaneto** [comment]
Dupe https://github.com/getsentry/sentry-dart/pull/1440
