### ISSUE TITLE
Google pre-launch report crash on x86 Android devices: couldn't find "libflutter.so"

### ISSUE THREAD

**Issue by Ciock** [getsentry/sentry-dart#1443]
### Platform

Flutter Mobile

### Obfuscation

Enabled

### Debug Info

Enabled

### Doctor

✓] Flutter (Channel stable, 3.10.0, on macOS 13.1 22C65 darwin-arm64, locale it-IT)
    • Flutter version 3.10.0 on channel stable at /Users/lucaoropallo/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 84a1e904f4 (3 days ago), 2023-05-09 07:41:44 -0700
    • Engine revision d44b5a94c9
    • Dart version 3.0.0
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/lucaoropallo/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.78.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.64.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.1 22C65 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 113.0.5672.92

[✓] Network resources
    • All expected network resources are available.

• No issues found!

### Version

7.5.1

### Steps to Reproduce

1. `flutter build appbundle --release --flavor production -t lib/main_production.dart`
2. head to `/build/app/intermediates/merged_native_libs/productionRelease/out/lib`

Result missing `libflutter.so` and `libapp.so` from `x86` folder
<img width="271" alt="Screenshot 2023-05-12 alle 15 26 55" src="https://github.com/getsentry/sentry-dart/assets/35781302/cdda4f8a-5b71-4b42-b846-fac998678116">

<details><summary>My app/build.gradle</summary>
<p>

``` gradle
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
  keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

apply plugin: 'com.android.application'
// START: FlutterFire Configuration
apply plugin: 'com.google.gms.google-services'
apply plugin: 'com.google.firebase.crashlytics'
// END: FlutterFire Configuration
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    ndkVersion "24.0.8215888"

    compileSdkVersion 33

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        applicationId "com.xxxx.xxxx"
        minSdkVersion 21
        targetSdkVersion flutter.targetSdkVersion
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        multiDexEnabled true
    }

    flavorDimensions "default"

    productFlavors {
        production {
            getIsDefault().set(true)
            dimension "default"
            applicationIdSuffix ""
            resValue "string", "app_name", "xxxx"
            manifestPlaceholders = [uriPrefix: "xxxx"]
        }
        staging {
            dimension "default"
            applicationIdSuffix ".staging"
            versionNameSuffix "-staging"
            resValue "string", "app_name", "xxxx - Staging"
            manifestPlaceholders = [uriPrefix: "xxxx-staging"]
        }
        xyz {
            dimension "default"
            applicationIdSuffix ".xyz"
            versionNameSuffix "-xyz"
            resValue "string", "app_name", "xxxx - XYZ"
            manifestPlaceholders = [uriPrefix: "xxxx-xyz"]
        }
    }

    signingConfigs {
        release {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile keystoreProperties['storeFile'] ? file(keystoreProperties['storeFile']) : null
            storePassword keystoreProperties['storePassword']
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
            shrinkResources true
            minifyEnabled true
            ndk {
                debugSymbolLevel 'FULL'
            }
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
}

```

</p>
</details> 

### Expected Result

Without Sentry plugin:
<img width="274" alt="Screenshot 2023-05-12 alle 15 25 00" src="https://github.com/getsentry/sentry-dart/assets/35781302/4dae5aa7-eaf8-4a53-9b32-3b994299a30c">

### Actual Result

From Google pre-launch report:
Device:  Google Pixel 2 (virtual) Android 9 (SDK 28) x86

> java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/co.nibol.nibol-7k-DxSNBTsuTq_Y6vHRiEw==/base.apk", zip file "/data/app/co.nibol.nibol-7k-DxSNBTsuTq_Y6vHRiEw==/split_config.es.apk", zip file "/data/app/co.nibol.nibol-7k-DxSNBTsuTq_Y6vHRiEw==/split_config.x86.apk", zip file "/data/app/co.nibol.nibol-7k-DxSNBTsuTq_Y6vHRiEw==/split_config.xxhdpi.apk"],nativeLibraryDirectories=[/data/app/co.nibol.nibol-7k-DxSNBTsuTq_Y6vHRiEw==/lib/x86, /data/app/co.nibol.nibol-7k-DxSNBTsuTq_Y6vHRiEw==/base.apk!/lib/x86, /data/app/co.nibol.nibol-7k-DxSNBTsuTq_Y6vHRiEw==/split_config.es.apk!/lib/x86, /data/app/co.nibol.nibol-7k-DxSNBTsuTq_Y6vHRiEw==/split_config.x86.apk!/lib/x86, /data/app/co.nibol.nibol-7k-DxSNBTsuTq_Y6vHRiEw==/split_config.xxhdpi.apk!/lib/x86, /system/lib]]] couldn't find "libflutter.so"

### Are you willing to submit a PR?

None

**Comment by marandaneto** [comment]
@Ciock `x86` isn't supported by Flutter anyway
https://docs.flutter.dev/deployment/android#what-are-the-supported-target-architectures
