### ISSUE TITLE
Field 'wLanguage' cannot be nullable or have type 'Null' by package_info_plus_windows

### ISSUE THREAD

**Issue by nithsua** [getsentry/sentry-dart#1451]
### Platform

Flutter Mobile

### Obfuscation

Enabled

### Debug Info

Disabled

### Doctor

[!] Flutter (Channel stable, 3.10.0, on macOS 13.3.1 22E261 darwin-arm64, locale en-US)
    • Flutter version 3.10.0 on channel stable at /Users/nithsua/fvm/versions/stable
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/2.19.6/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/nithsua/fvm/versions/stable. Consider adding /Users/nithsua/fvm/versions/stable/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 84a1e904f4 (6 days ago), 2023-05-09 07:41:44 -0700
    • Engine revision d44b5a94c9
    • Dart version 3.0.0
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/nithsua/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.78.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.64.0

[✓] Connected device (3 available)
    • macOS (desktop)                     • macos                                • darwin-arm64   • macOS 13.3.1 22E261 darwin-arm64
    • Chrome (web)                        • chrome                               • web-javascript • Google Chrome 113.0.5672.92

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

### Version

7.4.2

### Steps to Reproduce

The codebase was working just fine before, but doesn't compile after upgrading flutter and works fine when I remove sentry from pubspec.yaml

1. flutter upgrade
2. flutter run

The issue is primarily cause by package_info_plus_windows dependency if sentry. but couldn't find a way to resolve it.

### Expected Result

Application is expected to run.

### Actual Result

Error: Field 'wLanguage' cannot be nullable or have type 'Null', it must be `int`, `double`, `Pointer`, or a subtype of `Struct` or `Union`.
file_version_info.dart:13
Could not build the application for the simulator.

### Are you willing to submit a PR?

None

**Comment by marandaneto** [comment]
Probably a dupe of https://github.com/fluttercommunity/plus_plugins/issues/1525
Raise an issue on https://github.com/fluttercommunity/plus_plugins since this is not related to Sentry's SDK.

**Comment by uxduck** [comment]
This issue will affect all users who have the latest stable flutter (i.e. run `flutter upgrade`) and had installed sentry more than 3 months ago. 

The solution is to run `flutter pub upgrade package_info_plus` to upgrade to `package_info_plus` to the latest **compatible** version `3.1.2`.
