### ISSUE TITLE
Sentry_flutter package is Incompatible with package_info_plus ^4.0.0

### ISSUE THREAD

**Issue by NaveenKumarV1607** [getsentry/sentry-dart#1453]
### Platform

Flutter Mobile

### Obfuscation

Enabled

### Debug Info

Enabled

### Doctor

[✓] Flutter (Channel stable, 3.10.0, on macOS 13.3.1 22E261 darwin-arm64, locale en-IN)
    • Flutter version 3.10.0 on channel stable at /Users/naveenvj/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 84a1e904f4 (7 days ago), 2023-05-09 07:41:44 -0700
    • Engine revision d44b5a94c9
    • Dart version 3.0.0
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/naveenvj/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_SDK_ROOT = /Users/naveenvj/Library/Android/sdk
    • Java binary at: /Applications/Android Studio-mac.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio-mac.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.76.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] VS Code (version 1.70.1)
    • VS Code at /Users/naveenvj/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.3.1 22E261 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 113.0.5672.92

[✓] Network resources
    • All expected network resources are available.

### Version

7.5.2

### Steps to Reproduce

Try using the latest package_info_plus 4.0.0 and Sentry flutter 7.5.2 it will show the error in the Expected Result

### Expected Result

Because sentry_flutter >=6.13.1 depends on package_info_plus >=1.0.0 <4.0.0 and ui_conqur_fitness depends on package_info_plus ^4.0.0, sentry_flutter
  >=6.13.1 is forbidden.
So, because ui_conqur_fitness depends on sentry_flutter ^7.5.2, version solving failed.

### Actual Result

Pub get must be updated without any incompatible version solving failure.

### Are you willing to submit a PR?

None

**Comment by marandaneto** [comment]
Dupe https://github.com/getsentry/sentry-dart/pull/1440

**Comment by luis-cruzt** [comment]
Hello, when is this fix going to be available on pub.dev? 

Thanks

**Comment by marandaneto** [comment]
Just waiting for approval https://github.com/getsentry/publish/issues/2237
