### ISSUE TITLE
Check why `ananlyze` commit script did not execute on feature branch

### ISSUE THREAD

**Issue by denrase** [getsentry/sentry-dart#1456]
### Description

- Check why the commit step was skipped on a feature branch

<img width="622" alt="Bildschirmfoto 2023-05-16 um 14 51 32" src="https://github.com/getsentry/sentry-dart/assets/3984453/1c12ec67-0def-4f0d-b95d-84277c27d5ee">

- Auto fix swiftlint issues

/cc @marandaneto

**Comment by marandaneto** [comment]
The script should run and push normally, if the CI does not run automatic because of security reasons, that is fine.
