### ISSUE TITLE
enableAutoPerformanceTracing and global fps monitor

### ISSUE THREAD

**Issue by seven-liujiang** [getsentry/sentry-dart#1459]
### Problem Statement

I expect to monitor the smoothness of my Flutter app by setting options.enableAutoPerformanceTracing to true. This will allow me to obtain the trigger duration for each frame and obtain corresponding stack information when there is a lag (greater than 60 milliseconds), ideally related to my widget information. I also hope to determine the probability of lag occurring at a specific location, and it would be great if there was a visual analysis tool available. Can enableAutoPerformanceTracing automate this process? Generally speaking, because Flutter is isolated, unlike Android which has an activity to oversee, there are three ways to obtain stack information for positioning. Which method does Sentry currently use? 1. Modify the SDK to collect Dart stack APIs, 2. Pause threads to collect Native stacks, 3. Collect Native stacks through signals.

If possible, could you provide a demo or key code snippets? Currently, I am unable to implement this feature using the SDK example code. thank！

### Are you willing to submit a PR?

None

**Comment by marandaneto** [comment]
We are tracking this here https://github.com/getsentry/team-mobile/issues/18 and something similar here https://github.com/getsentry/sentry-dart/issues/513
It's unclear how this would work for Flutter yet, but stay tuned.
We already collect slow and frozen frames btw https://docs.sentry.io/platforms/flutter/performance/instrumentation/automatic-instrumentation/#slow-and-frozen-frames
