### ISSUE TITLE
集成之后，提交应用市场过不了，隐私授权之前不允许调用，但是sentry启动app 就会调用sdk。请问有解决方案吗

### ISSUE THREAD

**Issue by YunFeng-Huang** [getsentry/sentry-dart#1461]
### Problem Statement

集成之后，提交应用市场过不了，隐私授权之前不允许调用，但是sentry启动app 就会调用sdk。请问有解决方案吗

### Are you willing to submit a PR?

None

**Comment by marandaneto** [comment]
https://docs.sentry.io/platforms/flutter/#configure
You can call `SentryFlutter` in any app's lifecycle, just omit the `appRunner` if necessary.
