### ISSUE TITLE
CocoaPods could not find compatible versions for pod "Sentry/HybridSDK"

### ISSUE THREAD

**Issue by uxduck** [getsentry/sentry-dart#1467]
### Platform

Flutter Mobile

### Obfuscation

Disabled

### Debug Info

Enabled

### Doctor

[✓] Flutter (Channel stable, 3.10.0, on macOS 13.1 22C5044e darwin-arm64, locale
    en-GB)
    • Flutter version 3.10.0 on channel stable at /opt/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 84a1e904f4 (13 days ago), 2023-05-09 07:41:44 -0700
    • Engine revision d44b5a94c9
    • Dart version 3.0.0
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/zen/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Users/zen/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.9971841/Andr
      oid Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Users/zen/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9619390/Andr
      oid Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] Android Studio (version 2022.2)
    • Android Studio at /Users/zen/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.9971841/Andr
      oid Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.78.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.64.0

[✓] Connected device (1 available)
    • iPhone 14 Pro Max (mobile) • C91664B6-8BCA-4A33-A111-2004DD7C2E49 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)

[✓] Network resources
    • All expected network resources are available.

### Version

7.6.1

### Steps to Reproduce

1. Set up flutter app with iOS deployment target of `11`. 
2. Install sentry_flutter
3. Try and run the app, but the build fails.

### Expected Result

Build succeeds

### Actual Result

Error:
```
    [!] CocoaPods could not find compatible versions for pod "Sentry/HybridSDK":
      In snapshot (Podfile.lock):
        Sentry/HybridSDK (= 7.31.2)

      In Podfile:
        sentry_flutter (from `.symlinks/plugins/sentry_flutter/ios`) was resolved to 0.0.1, which depends on
          Sentry/HybridSDK (= 8.7.1)

    Specs satisfying the `Sentry/HybridSDK (= 7.31.2), Sentry/HybridSDK (= 8.7.1)` dependency were found, but they required a higher minimum deployment target.
```

### Are you willing to submit a PR?

None

**Comment by marandaneto** [comment]
@ben-xD you have to upgrade your local pod.

```
cd ios
pod outdated
pod update
pod update Sentry
```

etc...
