### ISSUE TITLE
Support `http` >= 1.0.0

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-dart#1474]
### Description

https://pub.dev/packages/http

`http` v1 is finally released but it depends on Dart v3.
The Sentry SDK depends on the `http: ^0.13.0`

If we bump the `http` lib on the Sentry SDK, we also have to raise the min. version of the Dart and Flutter SDK/engine, which is a breaking change.

Current min. version:

```
environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=3.0.0'
```

We'd need to change it to:

```
environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'
```

Which is the latest release, released on May the 10th https://medium.com/flutter/whats-new-in-flutter-3-10-b21db2c38c73

Migrating to `HttpClient` https://api.dart.dev/stable/2.12.1/dart-io/HttpClient-class.html isn't possible either since there's no Web support, we'd need to interop with JS directly, but it's still experimental as well https://dart.dev/web/js-interop

**Comment by marandaneto** [comment]
@ueman ideas? :(
I didn't want to maintain v7 and v8 at the same time, but maybe it's the only way now.

**Comment by ueman** [comment]
As far as I can tell there are no breaking changes, so 
```yaml
http: >=0.13.0 < 2.0.0
```
might work fine.

In the min version test you can then constraint http to v0.13.0

**Comment by ueman** [comment]
Another solution would be to vendor http and making the http integration another package.

**Comment by kuhnroyal** [comment]
> As far as I can tell there are no breaking changes, so 
> ```yaml
> http: >=0.13.0 < 2.0.0
> ```

Yes I think this will work.

**Comment by marandaneto** [comment]
Damn, I need a coffee, I was quite sure that it'd not work because of the version resolver special case 0.x versions.
I did try to force on the example `http: 1.0.0` but it failed due to the constraints proving my wrong point above :D

Thank you both :)
