### ISSUE TITLE
Should `BeforeSendCallback` have non-nullable hint?

### ISSUE THREAD

**Issue by fzyzcjy** [getsentry/sentry-dart#1478]
When implementing the attachment mechanism suggested by @marandaneto in https://github.com/getsentry/sentry-dart/pull/683, I realize BeforeSendCallback has a nullable Hint. If the passed-in hint is null, I have no way to attach an attachment. On the other hand, I quickly glanced through the source code and it seems that it  guarantees it is not null (by providing a default value). So shall we mark it as non-null?

### Platform

Dart

### Obfuscation

Enabled

### Debug Info

Enabled

### Doctor

-

### Version

latest

### Steps to Reproduce

-

### Expected Result

-

### Actual Result

-

### Are you willing to submit a PR?

None

**Comment by marandaneto** [comment]
True, I don't recall why we've not made it non-nullable, @denrase maybe?
We can do it in the next major since it's a breaking change.
Thanks for the feedback @fzyzcjy

**Comment by fzyzcjy** [comment]
You are welcome and looking forward to the next release!

**Comment by marandaneto** [comment]
`Hint` should not be nullable, but it's an optional parameter anyway (so a user isn't forced to pass anything), the SDK automatically creates a `Hint` if necessary.
This should base on the v8 branch.

**Comment by denrase** [comment]
@marandaneto Don't recall either, maybe took the API design from another SDK and didn't think about this case. 🤔

**Comment by denrase** [comment]
@fzyzcjy Thanks for bringing this up. The new API will be part of the 8.0.0 release.

**Comment by fzyzcjy** [comment]
🎉
