### ISSUE TITLE
Sentry Instrumentation for Dart's io `HttpClient`

### ISSUE THREAD

**Issue by silverhairs** [getsentry/sentry-dart#1484]
### Problem Statement

Out of the box, when performing http request in things such as the `NetworkImage` widget or the `CachedNetworkImagePackage` flutter uses dart's io [HttpClient](https://api.flutter.dev/flutter/dart-io/HttpClient-class.html) class. Currently Sentry does not have a package to instrument that. It's easy to override the underlying `HttpClient` with a custom implementation by extending [HttpOverrides](https://api.flutter.dev/flutter/dart-io/HttpOverrides-class.html) and overriding the `createHttpClient` method; but there is no implementation of `HttpClient` with sentry, and we cannot pass [dio](https://pub.dev/packages/dio) and [http.Client](https://pub.dev/packages/http) as none of them implement `HttpClient`. 

I think it would be important for sentry to support the native classes before going into the 3rd party libraries, this will reduce dependency on external libraries, and developers will not be obliged to always depend on a 3rd parties if I just want to instrument all network requests.

### Solution Brainstorm

Extend `HttpClient` and `HttpOverrides` and make it easier for developers to perform instrumentations.

I could investigate this and submit a PR but I cannot really promise anything for now as I have little availability.

### Are you willing to submit a PR?

None

**Comment by marandaneto** [comment]
Dupe https://github.com/getsentry/sentry-dart/issues/539
