### ISSUE TITLE
Redundant api signatures

### ISSUE THREAD

**Issue by mnordine** [getsentry/sentry-dart#149]
`Client` method calls have redundant naming.

```dart
client.captureEvent(event: event);
```

should be:

```dart
client.captureEvent(event);
```

Same for `client.captureException()`

**Comment by marandaneto** [comment]
@mnordine this is solved on https://github.com/getsentry/sentry-dart/releases/tag/4.0.0-alpha.1

the principal and the mandatory parameter is not named, so one can do `Sentry.captureEvent(event);`

looking forward to your feedback, thanks.
