### ISSUE TITLE
[Feature Request] chopper support

### ISSUE THREAD

**Issue by JosephNK** [getsentry/sentry-dart#1492]
### Problem Statement

Looking at Sentry's [documentation](https://docs.sentry.io/platforms/flutter/), it seems that Http and dio support sentry.
Is there a way to apply a sentry to the chopper?
If not, it would be great if you could support it. :)

### Are you willing to submit a PR?

None

**Comment by ueman** [comment]
Chopper is kinda a wrapper around http, so it is already supported. Just use the http integration and pass it to chopper.

**Comment by marandaneto** [comment]
Yes, when creating `ChopperClient`, you can pass the `client` parameter.
https://docs.sentry.io/platforms/dart/configuration/integrations/http-integration
Just pass an instance of `SentryHttpClient` to `client` and everything should work.
