### ISSUE TITLE
Database instrumentation for Isar

### ISSUE THREAD

**Issue by silverhairs** [getsentry/sentry-dart#1501]
### Problem Statement

[Isar](https://isar.dev/) is getting more and more adoption in the space; maybe not as popular as sqflite yet but it still is one of the highest rated packages on pub.dev. I think it's  worth having a package that provides instrumentation for this, like [sentry_sqflite](https://pub.dev/packages/sentry_sqflite).

### Solution Brainstorm

Isar has a companion app called [Isar Inspector](https://github.com/isar/isar#isar-database-inspector) that acts as a database client and gives a visual representation of transactions being performed, I think it's worth looking at that side.

### Are you willing to submit a PR?

None

**Comment by marandaneto** [comment]
@silverhairs makes sense, I tried to investigate it here https://github.com/getsentry/sentry-dart/issues/1204 but that solution didn't work out (based on File support).
We'd need to do a wrapper on top of the Isar classes since they don't have the concept of interceptors or something like that, at least I've not found it last time I checked it.

**Comment by silverhairs** [comment]
> @silverhairs makes sense, I tried to investigate it here #1204 but that solution didn't work out (based on File support). We'd need to do a wrapper on top of the Isar classes since they don't have the concept of interceptors or something like that, at least I've not found it last time I checked it.

@marandaneto Thanks for trying  🙏  I don't exactly have time at the moment but when I get some time and this issue is still open I would like to take a look at this and I believe your experiment will be very valuable.

**Comment by denrase** [comment]
Reopened because we still need to implement breadcrumbs.

**Comment by buenaflor** [comment]
@denrase 

- [ ] update sentry-docs with Isar instrumentation
