### ISSUE TITLE
The stack track  can not parsed

### ISSUE THREAD

**Issue by cj3479** [getsentry/sentry-dart#1507]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Hi
   The Flutter stack track  can not parsed

![image](https://github.com/getsentry/sentry/assets/9412601/863b5a05-8e4b-4fc5-ae81-91ed33dde10d)

this link is [issue link](https://rocky-tp.sentry.io/issues/4228493485/?project=6572265&query=is%3Aunresolved&referrer=issue-stream&stream_index=2#exception)

I use local debug information to parse it , It is ok .  But the sentry console can not parse it 
<img width="1470" alt="image" src="https://github.com/getsentry/sentry/assets/9412601/87fe14cb-3b7e-4074-a93f-f08763d94ac1">

The debug is bf4aa6bc-937e-4a52-eb7a-06b4a63a2383
<img width="1195" alt="image" src="https://github.com/getsentry/sentry/assets/9412601/701038dc-74c5-4369-804a-50d6951a092e">

### Expected Result

<img width="1428" alt="image" src="https://github.com/getsentry/sentry/assets/9412601/680befab-c9fb-45f2-8ce9-f493c43fd2c3">

### Actual Result

<img width="1119" alt="image" src="https://github.com/getsentry/sentry/assets/9412601/739679db-5fdb-4f16-b9ad-fbea710995d2">

### Product Area

Unknown

### Link

https://rocky-tp.sentry.io/issues/4228493485/?project=6572265&query=is%3Aunresolved&referrer=issue-stream&stream_index=2#exception

**Comment by cj3479** [comment]
Can someone answer this question？

**Comment by therealarkin** [comment]
@smeubank are we doing something special for Flutter?

**Comment by marandaneto** [comment]
@cj3479 can you try at least the SDK version [6.10.0](https://github.com/getsentry/sentry-dart/releases/tag/6.10.0) or even better the [latest](https://github.com/getsentry/sentry-dart/releases/tag/7.7.0)?

The parsing of native stack traces was improved and this is fixed since 6.10.0.

This was caused due to small changes in how Flutter produces native stack traces when `split-debug-info` is enabled.
Also, mind sharing your Dart and Flutter versions?

**Comment by cj3479** [comment]
> @cj3479 can you try at least the SDK version [6.10.0](https://github.com/getsentry/sentry-dart/releases/tag/6.10.0) or even better the [latest](https://github.com/getsentry/sentry-dart/releases/tag/7.7.0)?
> 
> The parsing of native stack traces was improved and this is fixed since 6.10.0.
> 
> This was caused due to small changes in how Flutter produces native stack traces when `split-debug-info` is enabled. Also, mind sharing your Dart and Flutter versions?

<img width="846" alt="image" src="https://github.com/getsentry/sentry-dart/assets/9412601/8d4877eb-4058-4281-9ad9-d3d2320ce79c">

I use the SDK version is 6.0.1.  I will try the latest version  later

**Comment by marandaneto** [comment]
@cj3479 any news here?

**Comment by marandaneto** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated. There's a large chance that this issue has been solved since.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
