### ISSUE TITLE
Not receiving events in Sentry when running flutter apps on macOS

### ISSUE THREAD

**Issue by jamescrosswell** [getsentry/sentry-dart#1514]
### Platform

Flutter Desktop

### Obfuscation

Disabled

### Debug Info

Enabled

### Doctor

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.4, on macOS 13.3.1 22E772610a darwin-arm64, locale en-NZ)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.78.2)
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!

### Version

7.7.0

### Steps to Reproduce

Create a new flutter app:
`flutter create sftest`

Modify the main.dart file to include Sentry's boilerplate instrumentation:

```
import 'package:sentry_flutter/sentry_flutter.dart';

Future<void> main() async {
  await SentryFlutter.init(
    (options) {
      options.dsn = 'https://yoursentrydsnhere';
      // Set tracesSampleRate to 1.0 to capture 100% of transactions for performance monitoring.
      // We recommend adjusting this value in production.
      options.tracesSampleRate = 1.0;
    },
    appRunner: () => runApp(MyApp()),
  );

  // or define SENTRY_DSN via Dart environment variable (--dart-define)
}
```

Modify the `_incrementCounter` callback so it throws an exception:

```
  Future<void> _incrementCounter() async {
    setState(() {
      _counter++;
    });

    try 
    {
      UnimplementedError();
    } 
    catch (exception, stackTrace) 
    {
      await Sentry.captureException(
        exception,
        stackTrace: stackTrace,
      );
    }
  }
```

Run the app, choosing `macOS (darwin)` as the device to use.

### Expected Result

I'm expecting to see events come through to Sentry.io

### Actual Result

There's nothing in the Issues dashboard (even days later). 

However I noticed if I choose iOS as the device when doing `flutter run`, the issues come through to Sentry fine. 

So it seems to be an issue when running Flutter applications on desktop (or at least on my macbook). 

### Are you willing to submit a PR?

None

**Comment by marandaneto** [comment]
@jamescrosswell thanks for reporting, let me try this out.
Can you set `options.debug = true;` and check if you see something suspicious in the console?

**Comment by marandaneto** [comment]
@jamescrosswell I've tested it locally and I get errors from macOS normally, please enable `debug` mode and let us know what you see.

**Comment by jamescrosswell** [comment]
Hm, yes there is something in there (I stripped out the timestamps to make it easier to read). 

It looks like the request (presumably an HTTP Request) to Sentry is failing with `Operation not permitted`:

```
[SentryFileManager:332] Writing session: /Users/jamescrosswell/Library/Containers/com.example.sftest/Data/Library/Caches/io.sentry/45d155fbd750104ce4febfe817384e38ffae657e/session.current
Capturing session with status: {"errors":0,"status":"ok","started":"2023-06-12T21:55:00.890Z","did":"2D9EEBC0-CC6B-4410-9F54-2942979A7A8D","sid":"038CDC9A-295C-4420-8F26-610DE8C9C9E3","init":true,"timestamp":"2023-06-12T21:55:00.891Z","attrs":{"release":"com.example.sftest@1.0.0+1","environment":"debug"},"seq":1}
[SentryFileManager:405] Deleting LastInForeground at: /Users/jamescrosswell/Library/Containers/com.example.sftest/Data/Library/Caches/io.sentry/45d155fbd750104ce4febfe817384e38ffae657e/lastInForeground.timestamp
[SentryFileManager:244] Deleting /Users/jamescrosswell/Library/Containers/com.example.sftest/Data/Library/Caches/io.sentry/45d155fbd750104ce4febfe817384e38ffae657e/lastInForeground.timestamp
[SentryFileManager:262] Writing envelope to path: /Users/jamescrosswell/Library/Containers/com.example.sftest/Data/Library/Caches/io.sentry/45d155fbd750104ce4febfe817384e38ffae657e/envelopes/1686606900.891042-00001-EC8FDAC0-B8C0-407B-ADDC-769D9E2F7977.json
[SentryHttpTransport:267] sendAllCachedEnvelopes start.
[SentryHttpTransport:271] Already sending.

[SentryRequestOperation:34] Request status: 0
[SentryRequestOperation:38] Request response:
[SentryRequestOperation:42] Request failed: Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted" UserInfo={_NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <1559B33B-2F3F-4A6E-A308-F9E24C2F73CF>.<1>, _kCFStreamErrorDomainKey=1, _kCFStreamErrorCodeKey=1, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <1559B33B-2F3F-4A6E-A308-F9E24C2F73CF>.<1>"
), _NSURLErrorNWPathKey=satisfied (Path is satisfied), interface: en0[802.11], ipv4, dns}
```

**Comment by marandaneto** [comment]
@jamescrosswell are you using sentry.io or self-hosted? if the latter, is probably something in your server, I can move it to https://github.com/getsentry/self-hosted/ if that's the case.

**Comment by jamescrosswell** [comment]
Hey @marandaneto, I'm using sentry.io. 
```
options.dsn = 'https://d3062bd1855e4981a88bd566c4ecb036@o1197552.ingest.sentry.io/4505345955397632'
```

**Comment by marandaneto** [comment]
@jamescrosswell can you provide a minimal reproducible example?
does your network ping `sentry.io`?

@brustolin have you seen this before?

> [SentryRequestOperation:42] Request failed: Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted" UserInfo={_NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <1559B33B-2F3F-4A6E-A308-F9E24C2F73CF>.<1>, _kCFStreamErrorDomainKey=1, _kCFStreamErrorCodeKey=1, _NSURLErrorRelatedURLSessionTaskErrorKey=(

**Comment by brustolin** [comment]
I never saw this particular error. Researching a lil bit about it I couldn't find much.
My suspicion is that your app is running under App Sandbox.

Open you macos project with xcode and take a look if you have this:
![Screenshot 2023-06-14 at 11 03 09](https://github.com/getsentry/sentry-dart/assets/28265868/0cf3fc9b-d71d-410f-a67c-109f7da44690)

**Comment by jamescrosswell** [comment]
Hm, interesting. I've never done any xcode development but you're right... in the App Sandbox settings _Incoming Connections (Server)_ was enabled but _Outgoing Connections (Client)_ was not. When I enabled that, I started to get things coming through to Sentry. 

It's odd nobody else had bumped into this. I literally just followed the instructions in the [getting started docs](https://docs.sentry.io/platforms/flutter/). I also have a pretty clean machine (I reinstalled the OS about 4 weeks ago) so I think everything on my machine is pretty vanilla/default.

In any case, back on track - thank you!

**Comment by brustolin** [comment]
@marandaneto Probably worth looking into whether this option is enabled as Flutter defaults when creating a new project in order to write about it in the "Troubleshooting" section.

**Comment by marandaneto** [comment]
> @marandaneto Probably worth looking into whether this option is enabled as Flutter defaults when creating a new project in order to write about it in the "Troubleshooting" section.

Nope, it's not, I created an empty template already.

**Comment by jamescrosswell** [comment]
Is it potentially related to the verison of xcode I have installed? I'm thinking possibly if nothing is written to the workspace file (by flutter) some default could be used, which come from xcode or somewhere else, and so be different for me and @marandaneto. 

Potentially useful info re my setup:
```
XCode Version 14.3.1 (14E300c)
Flutter 3.10.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 796c8ef792 (6 days ago) • 2023-06-13 15:51:02 -0700
Engine • revision 45f6e00911
Tools • Dart 3.0.5 • DevTools 2.23.1
macOS 13.4 (22F66)
```

**Comment by marandaneto** [comment]
@jamescrosswell I'm not sure, this is not related to our SDK though, it's an environment issue, it's not related to Sentry at all.

**Comment by jamescrosswell** [comment]
Possibly. You do want to help people send data to Sentry... so if the defaults prevent that, it's not great. Anyways, if I'm the only one who's bumped into it, I guess I got struck by lightning. Not sure how (as I say, it's a pretty clean build of everything) but unless it pops up with other users, probably safe to ignore for the time being.

**Comment by bruno-garcia** [comment]
Low effort to throw this on the troubleshooting  page if this is the default experience

**Comment by marandaneto** [comment]
> Low effort to throw this on the troubleshooting page if this is the default experience

Its not as mentioned here https://github.com/getsentry/sentry-dart/issues/1514#issuecomment-1596787656
