### ISSUE TITLE
CocoaPods could not find compatible versions for pod "SentryPrivate"

### ISSUE THREAD

**Issue by prossion** [getsentry/sentry-dart#1515]
### Platform

Flutter Mobile

### Obfuscation

Disabled

### Debug Info

Enabled

### Doctor

[✓] Flutter (Channel stable, 3.10.2, on macOS 13.4 22F66 darwin-arm64, locale en-UA)
    • Flutter version 3.10.2 on channel stable at /Users/maximboyko/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9cd3d0d9ff (3 weeks ago), 2023-05-23 20:57:28 -0700
    • Engine revision 90fa3ae28f
    • Dart version 3.0.2
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/maximboyko/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.78.2)
    • VS Code at /Users/Visual Studio Code.app/Contents
    • Flutter extension version 3.66.0

[✓] Connected device (4 available)
    • Максим’s iPhone (mobile) • • ios • iOS 16.5 20F66
    • iPhone 14 (mobile)   •  • ios  • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)  • macos  • darwin-arm64   • macOS 13.4 22F66
      darwin-arm64
    • Chrome (web • chrome  • web-javascript • Google Chrome

[✓] Network resources
    • All expected network resources are available.

• No issues found!

### Version

7.7.0

### Steps to Reproduce

1. Set up flutter app with iOS deployment target of 12.
2. Install sentry_flutter
3. Try and run the app, but the build fails.

### Expected Result

Build succeeds

### Actual Result

Error:
   [!] CocoaPods could not find compatible versions for pod "SentryPrivate":
  In Podfile:
    reteno_plugin (from `.symlinks/plugins/reteno_plugin/ios`) was resolved to 0.0.1, which depends on
      Reteno (= 1.5.4) was resolved to 1.5.4, which depends on
        Sentry (= 8.2.0) was resolved to 8.2.0, which depends on
          SentryPrivate (= 8.2.0)

    sentry_flutter (from `.symlinks/plugins/sentry_flutter/ios`) was resolved to 0.0.1, which depends on
      Sentry/HybridSDK (= 8.7.3) was resolved to 8.7.3, which depends on
        SentryPrivate (= 8.7.3)

### Are you willing to submit a PR?

No

**Comment by marandaneto** [comment]
Hi @prossion 
You just have to update the pods, check https://github.com/getsentry/sentry-dart/issues/1467#issuecomment-1556692588

**Comment by prossion** [comment]
Hi @marandaneto 
Thanks for answer, but this action doesn't helped me ;(

**Comment by marandaneto** [comment]
@prossion delete all of your caching files, `flutter clean`, all lock files, etc.
Or provide a minimal reproducible example.

**Comment by SchillingSebastian** [comment]
I want to add in here again @marandaneto 
We have a build pipeline running and this builds app based on a branch. 
The branch was buildable a couple weeks back but now the same branch (no changes made) fails. The build server is always in a clean state. It gives us this same error: It can not find the Sentry/HybridSDK of version XY. 
Why does this happen. Do outdated versions get purged from a repository and if so in what timeframe?

**Comment by marandaneto** [comment]
@SchillingSebastian raise a new issue, its easier since this one is closed a long time ago, I'm no longer part of the Sentry staff.
