### ISSUE TITLE
Not sure about some result from the flutter dev tools cpu profiler

### ISSUE THREAD

**Issue by ahmdaeyz** [getsentry/sentry-dart#1519]
### Platform

Flutter Mobile

### Obfuscation

Disabled

### Debug Info

Enabled

### Doctor

[!] Flutter (Channel stable, 3.10.2, on macOS 12.6 21G115 darwin-arm64, locale en-EG)
    • Flutter version 3.10.2 on channel stable at /Users/ahmdaeyz/development/flutter
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/3.0.4/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/ahmdaeyz/development/flutter. Consider adding /Users/ahmdaeyz/development/flutter/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9cd3d0d9ff (3 weeks ago), 2023-05-23 20:57:28 -0700
    • Engine revision 90fa3ae28f
    • Dart version 3.0.2
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/ahmdaeyz/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /Users/ahmdaeyz/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.75.1)
    • VS Code at /Users/ahmdaeyz/Downloads/sympols/Visual Studio Code.app/Contents
    • Flutter extension version 3.64.0

[✓] VS Code (version 1.71.0)
    • VS Code at /Users/ahmdaeyz/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.64.0

[✓] Connected device (3 available)
    • T770H (mobile)  • cd1bd5a2 • android-arm64  • Android 11 (API 30)
    • macOS (desktop) • macos    • darwin-arm64   • macOS 12.6 21G115 darwin-arm64
    • Chrome (web)    • chrome   • web-javascript • Google Chrome 114.0.5735.106

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

### Version

7.7.0

### Steps to Reproduce

- Build the app in profile mode.
- Open the flutter dev tools.
- Open the CPU profiling tab.
- Start recording. 
- Use the app for a couple of minutes. 
- Stop recording samples.
- Go to the method table tab.
- Observe the total of sentry methods.

### Expected Result

We are not sure. But less total time?

### Actual Result

This is how our method tab from the CPU profiler look like: 
![image](https://github.com/getsentry/sentry-dart/assets/36048466/7f405bb9-7cac-410b-8741-c40752686fee)

We are not sure if this is fine or not to be honest. Should we be concerned?

### Are you willing to submit a PR?

None

**Comment by marandaneto** [comment]
@ahmdaeyz can you init the SDK with the `enableScopeSync` option disabled and try it out again?
It really depends on how heavily you call `addBreadcrumb` but the impact should be very low, what we do is sync the data between the Flutter layer and the Android/iOS layer so in case native events (Swift/Kotlin) happens, those events also include those breadcrumbs, but they are all simple serializable data, I guess, unless you are misusing with heavy stuff.
Can you provide more context?
Thanks.

**Comment by ahmdaeyz** [comment]
We only have one call to `Sentry.addBreadcrumb` in our codebase and it is only called on a specific error which rarely happens.
Here is the results with your instructions applied:
![image](https://github.com/getsentry/sentry-dart/assets/36048466/c58011de-06fe-4a57-a276-8782a3215188)
Here is our config, It might be relevant.
![image](https://github.com/getsentry/sentry-dart/assets/36048466/afdeaa74-9937-49bc-87e4-5be2b93953aa)

**Comment by marandaneto** [comment]
@ahmdaeyz I don't notice any slow down or dropped frames by doing this, do you?
The numbers are pretty similar to any other Flutter/Dart function.
Of course, sending the error/transaction has more impact since it has to serialize and send over the network, but still not noticeable, also you don't have to `await` the function anyway.

**Comment by ahmdaeyz** [comment]
Making sure this is normal and expected is the purpose of this issue. So I take from your wording that this is typical of any flutter app using the sentry sdk, right?

**Comment by marandaneto** [comment]
@ahmdaeyz I'd say so, we cannot profile in release mode (which is faster) but in profile mode, the time spent with all the features enabled is just a matter of a few 10s or 100s of MS (depending on the features enabled, etc), including sending the event, so unless it's dropping frames or something, I guess we are fine.
Can we close this? thanks for the feedback though.

**Comment by ahmdaeyz** [comment]
Thanks for your response.
