### ISSUE TITLE
Enums should not use its name, otherwise obfuscation will break everything

### ISSUE THREAD

**Issue by fzyzcjy** [getsentry/sentry-dart#1525]
When looking at https://github.com/getsentry/sentry-dart/pull/1506, I realize this may cause trouble for obfuscation. 

### Platform

Dart

### Obfuscation

Enabled

### Debug Info

Enabled

### Doctor

-

### Version

-

### Steps to Reproduce

-

### Expected Result

-

### Actual Result

-

### Are you willing to submit a PR?

None

**Comment by fzyzcjy** [comment]
Wow interesting: https://github.com/flutter/flutter/issues/94751 it seems that enum *names* are not obfuscated yet (though everything else is)! So this should work well today.

**Comment by marandaneto** [comment]
@fzyzcjy Thanks for raising this, good point, I recall checking that `enum.name` is currently not obfuscated.
