### ISSUE TITLE
StackOverflowError (no more info)

### ISSUE THREAD

**Issue by ahmdaeyz** [getsentry/sentry-dart#1526]
### Platform

Flutter Mobile

### Obfuscation

Disabled

### Debug Info

Disabled

### Doctor

[!] Flutter (Channel stable, 3.10.5, on macOS 12.6 21G115 darwin-arm64, locale en-EG)
    • Flutter version 3.10.5 on channel stable at /Users/ahmdaeyz/development/flutter
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/3.0.4/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/ahmdaeyz/development/flutter. Consider adding /Users/ahmdaeyz/development/flutter/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (7 days ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/ahmdaeyz/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /Users/ahmdaeyz/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.75.1)
    • VS Code at /Users/ahmdaeyz/Downloads/sympols/Visual Studio Code.app/Contents
    • Flutter extension version 3.64.0

[✓] VS Code (version 1.71.0)
    • VS Code at /Users/ahmdaeyz/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.64.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.6 21G115 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 114.0.5735.133

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

### Version

7.7.0

### Steps to Reproduce

This keeps popping in our dashboard. We thought it might get fixed with the latest version since it had this change log entry: 

> Improve SentryException#value, remove stringified stack trace ([##1470](https://github.com/getsentry/sentry-dart/pull/#1470))

I'm not able to get the stack trace from the dashboard, when I try to download it opens another page with only the word message in it.

Here is how it looks:

<img width="1217" alt="image" src="https://github.com/getsentry/sentry-dart/assets/36048466/7c1f0641-fe35-4efc-a07b-57a1bc73de5f">

This it the top of the stack in text:
```
(sentry_exception_factory.dart:44)
    // but only if attachStacktrace is enabled
    if (_options.attachStacktrace) {
      // TODO: snapshot=true if stackTrace is null
      // Requires a major breaking change because of grouping
      if (stackTrace == null || stackTrace == StackTrace.empty) {
        stackTrace = StackTrace.current;
      }
    }
    SentryStackTrace? sentryStackTrace;
    if (stackTrace != null) {
```

### Expected Result

Not get the error in the dashboard.

### Actual Result

We have several events with `StackOverflowError` 

### Are you willing to submit a PR?

None

**Comment by marandaneto** [comment]
@ahmdaeyz thanks for raising this.
It's unclear to me if this is an SDK issue, can you share more context of when you get this error and how? Sometimes the SDK fallback to `StackTrace.current` because either the exception had no stack trace or the `stackTrace` param wasn't used, and this stack trace can be arbitrary but that's the best we can do.

Can you provide a minimal reproducible example, a link to an event from sentry.io, or any more info? Thanks.

**Comment by ahmdaeyz** [comment]
Can this help?
![image](https://github.com/getsentry/sentry-dart/assets/36048466/a0cac5f2-4c24-4e0d-8e87-998c9d2b295d)

**Comment by marandaneto** [comment]
@ahmdaeyz do you know if the StackOverflowError is happening within your code or the Sentry SDK? still unclear since I don't have full access to the source code.
Are you using the Sentry Dio package and extensions? which version?
@ueman ideas?

**Comment by ahmdaeyz** [comment]
Yes, We are using sentry dio. Version is:   `sentry_dio: ^7.4.2`.

This is what I'm seeing in the dashboard:
<img width="1044" alt="image" src="https://github.com/getsentry/sentry-dart/assets/36048466/8be6996c-0ba3-4de8-b03f-98e15e18a143">

**Comment by marandaneto** [comment]
@ahmdaeyz that just links to https://github.com/getsentry/sentry-dart/blob/d1a80e0760508de40709dff1c53369cac825a2f4/dart/lib/src/sentry_exception_factory.dart#L44 as mentioned here https://github.com/getsentry/sentry-dart/issues/1526#issuecomment-1600714062
It does not mean that the SDK is throwing this error, this is probably within your app/and-or dio.
An error has been thrown and there was no stack trace, that's why it points out to that line of the code.
Can you provide a minimal reproducible example? otherwise it's not actionable.

**Comment by marandaneto** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
