### ISSUE TITLE
Network connection change breadcrumbs for Web

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-dart#1530]
### Description

https://github.com/getsentry/team-mobile/issues/82

**Comment by ueman** [comment]
I've done something like this in https://github.com/ueman/sentry-dart-tools/tree/main/sentry_connectivity

**Comment by marandaneto** [comment]
> I've done something like this in [ueman/sentry-dart-tools@`main`/sentry_connectivity](https://github.com/ueman/sentry-dart-tools/tree/main/sentry_connectivity?rgh-link-date=2023-06-22T14%3A26%3A42Z)

Yep, I was gonna link to https://github.com/getsentry/team-mobile/issues/82#issuecomment-1460796386
which uses https://pub.dev/packages/connectivity_plus

**Comment by stefanosiano** [comment]
you can have a look at https://github.com/getsentry/sentry-java/pull/2608 for reference
