### ISSUE TITLE
Slow route transitions with SentryNavigationObserver and SentryAssetBundle

### ISSUE THREAD

**Issue by fedorstepanovv** [getsentry/sentry-dart#1532]
### Platform

Flutter Mobile

### Obfuscation

Disabled

### Debug Info

Disabled

### Doctor

[✓] Flutter (Channel stable, 3.7.7, on macOS 13.4 22F66 darwin-arm64, locale
    en-US)
    • Flutter version 3.7.7 on channel stable at
      /Users/stepanovv/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2ad6cd72c0 (4 months ago), 2023-03-08 09:41:59 -0800
    • Engine revision 1837b5be5f
    • Dart version 2.19.4
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/stepanovv/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.0

[✗] Chrome - develop for the web (Cannot find Chrome executable at
    /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.68.1)
    • VS Code at /Users/stepanovv/Downloads/Visual Studio Code 2.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (2 available)
    • Pixel 3a XL (mobile) • 192.168.0.87:40447 • android-arm64 • Android 12
      (API 32)
    • macOS (desktop)      • macos              • darwin-arm64  • macOS 13.4
      22F66 darwin-arm64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

### Version

7.6.3

### Steps to Reproduce

I integrated sentry to Flutter project and it seems to be fine on Android, but on IOS right after the integration I faced a strange behavior with page transitions. That behavior can be seen when i start to use a private Flutter native plugin for some platform-specific needs. 
I have a page which is a flow to get an usb camera feed, there are some frame preprocessing stuff on a native side, Texture view and a few stream subscriptions to listen to native changes. 
It all works fine but when i start to close that page (with that flow) and come back again for more than a few times in a row, it suddenly starts to slow down the perfomance of my app. ALTHOUGH on the same env it works well without added SentryNavigationObserver and SentryAssetBundle. I thought that the reason is that i get many exceptions, but as i can see there are no Flutter or native exceptions at that time when it starts to slow down. It seems like this issue is somehow connected to SentryNavigationObserver and perhaps to SentryAssetBundle. 

PS: 
I test the application using TestFlight, because my environment doesnt allow me to test the described flow normally in DEBUG on IOS. 

### Expected Result

I expect it to work smoothly as it does on Android with Sentry and on IOS without SentryAssetBundle and SentryNavigationObserver.

### Actual Result

It just slows down each screen transition, screen loading etc. Here is an example:
![зображення](https://github.com/getsentry/sentry-dart/assets/52676610/5cd8754e-4e83-4c1a-908f-29ee3fc52a0b)

### Are you willing to submit a PR?

None

**Comment by marandaneto** [comment]
@fedorstepanovv Can you try without `SentryAssetBundle` only and later without `SentryNavigationObserver`? so we can pinpoint where the slowdown comes from.
Also, can you share your SDK code snippet?
Also a minimal reproducible example would help a lot.
There was a similar issue recently https://github.com/getsentry/sentry-dart/issues/1457 but I could not reproduce it locally either.

**Comment by fedorstepanovv** [comment]
@marandaneto, I tested it, and came to the conclusion that it works fine without SentryAssetBundle even though SentryNavigationObserver is still in my project. When it comes to sdk, its sadly against our company's privacy rules, but I can try to either execute some important code snippets or simply answer on the most important things that u need to request to solve that problem

**Comment by marandaneto** [comment]
@fedorstepanovv what if you init `SentryAssetBundle` with `enableStructuredDataTracing: false`? does it stop?

> When it comes to sdk, its sadly against our company's privacy rules

https://stackoverflow.com/help/minimal-reproducible-example
For the minimal-reproducible-example, just a new template app using `flutter create` is enough, which shows the problem, we don't need the source code of your app, the problem is that I cannot reproduce this locally.

**Comment by fedorstepanovv** [comment]
Hi, I know what a min-repr-example is, but its just impossible to recreate that issue using simply flutter create, because the project, where that crash occurs, is connected to the self-written package that handles video preprocessing, rendering, and its not that stable yet. I suppose that the key of the problem can be performance or some specific processes that I handle on the package's side (Like SurfaceTexture rendering). I will think of how I can try to show the working example of an issue. BTW I would like to know if SentryAssetBundle itself can have a big impact on the performance. Perhaps there are some specific cases when it can impact more.

**Comment by marandaneto** [comment]
@fedorstepanovv so far we've never found any performance impact, it's just a wrapper on top of its original class.
The overhead should be minimal, all in memory, https://github.com/getsentry/sentry-dart/blob/main/flutter/lib/src/sentry_asset_bundle.dart
I'll wait for a repro or some guidance on how to reproduce this otherwise it's not actionable.

**Comment by marandaneto** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
