### ISSUE TITLE
Add `before-capture-callback` and debouncing for screenshots/view hierarchy

### ISSUE THREAD

**Issue by krystofwoldrich** [getsentry/sentry-dart#1540]
### Description

Right now there's little control over when screenshots or view hierarchies are captured. This can have a negative impact on the app performance itself (capturing many screenshots, contribution to quota) as well as the usability of the feature itself (no control when a screenshot should be taken or not).

- backlink https://github.com/getsentry/team-mobile/issues/135

**Comment by krystofwoldrich** [comment]
User issue asking for this feature -> https://github.com/getsentry/sentry-dart/issues/1544

**Comment by achernoprudov** [comment]
Would be nice to have `SentryViewHierarchy` in the callback. 

In my case, I would like to capture screenshots only if there are no secure widgets in the view hierarchy. So BFS in view hierarchy can solve the issue.

In our banking app it's PII concern and we would like to protect our users sensitive information.

**Comment by buenaflor** [comment]
@achernoprudov hi! this issue is in our backlog. we will provide the `SentryEvent` and `Hint` in the callback. Hint includes the `viewHierarchy` although the `viewHierarchy` would already be serialized as a `SentryAttachment` so that might not help your use case much unless you can deserialize it. We will discuss this further internally

**Comment by buenaflor** [comment]
@achernoprudov after internal discussion, while these options will be standard in the callback, we will not provide an out of the box deserialization for this. What you will be able to do is use the bytes to convert it into a string (json): `hint?.viewHierarchy?.bytes -> to string` and check if your secure widget can be found in the view hierarchy.
