### ISSUE TITLE
Screenshot feature needs setBeforeScreenshotCaptureCallback

### ISSUE THREAD

**Issue by thinkocapo** [getsentry/sentry-dart#1544]
### Problem Statement

SDK's Screenshot feature does not have the callback setBeforeScreenshotCaptureCallback

Users were telling me they'd like to decide if they want to send the screenshot or not, based on data from the event in the callback (event,hint,debounce).

### Solution Brainstorm

Add the callback function as a feature, like how Android SDK has it.
https://docs.sentry.io/platforms/android/enriching-events/screenshots/

### Are you willing to submit a PR?

None

**Comment by krystofwoldrich** [comment]
Hi, thank you for the issue.

We are already tracking this here -> https://github.com/getsentry/sentry-dart/issues/1540
