### ISSUE TITLE
Exception logs are obfuscated

### ISSUE THREAD

**Issue by memishood** [getsentry/sentry-dart#1546]
### Platform

Flutter Web

### Obfuscation

Disabled

### Debug Info

Disabled

### Doctor

[✓] Flutter (Channel stable, 3.10.5, on macOS 13.4.1 22F82 darwin-arm64, locale en-TR)
    • Flutter version 3.10.5 on channel stable at /Users/emrememis/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (4 weeks ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/emrememis/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.79.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.4.1 22F82 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 114.0.5735.198

[✓] Network resources
    • All expected network resources are available.

• No issues found!

### Version

7.8.0

### Steps to Reproduce

pubspec.yaml:

```
dependencies:
  ...
  sentry_flutter: ^7.8.0
dev_dependencies:
  ...
  sentry_dart_plugin: ^1.4.0

sentry:
  upload_debug_symbols: true
  upload_sources: true
  upload_source_maps: true
  project: my-project
  org: my-org
  auth_token: my-auth-token
  wait_for_processing: true
  log_level: error
```

1. flutter build web --release --source-maps
2. dart run `sentry_dart_plugin`

console result for `sentry_dart_plugin`:
```
Building package executable... 
Built sentry_dart_plugin:sentry_dart_plugin.
[❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚] 0% reading config values..        
Downloading sentry-cli from https://downloads.sentry-cdn.com/sentry-cli/2.19.1/sentry-cli-Darwin-universal to .dart_tool/pub/bin/sentry_dart_plugin/sentry-cli

Downloaded Sentry CLI binary checksum verification passed successfully (hash: some hash).

Sentry CLI downloaded successfully.
☑ reading config values                                                             
☑ validating config values                                                             
[❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚] 18% uploading debug symbols..                                
> Found 2 debug information files

> Resolved source code for 0 debug information files

> Prepared debug information files for upload

> Nothing to upload, all files are on the server
☑ uploading debug symbols                                                             

Created release my-release@1.0.1+1
[❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚] 27% uploading source maps..                               
> Found 8 files

> Analyzing 8 sources

> Rewriting sources

> Adding source map references

> Bundled 8 files for upload
> Bundle ID: some bundle id

> Uploaded files to Sentry

> File processing complete
> Organization: my-org
> Project: my-project
> Release: my-release@1.0.1+1
> Dist: 1
> Upload type: artifact bundle

Source Map Upload Report
  Scripts
    ~/flutter.js
    ~/flutter_service_worker.js
  Minified Scripts
    ~/canvaskit/canvaskit.js (sourcemap at ../main.dart.js.map)
    ~/canvaskit/chromium/canvaskit.js (sourcemap at ../../main.dart.js.map)
    ~/canvaskit/skwasm.js (sourcemap at ../main.dart.js.map)
    ~/canvaskit/skwasm.worker.js (sourcemap at ../main.dart.js.map)
    ~/main.dart.js (sourcemap at main.dart.js.map)
  Source Maps
    ~/main.dart.js.map

> Found 148 files

> Analyzing 148 sources

> Rewriting sources
> Adding source map references

> Bundled 148 files for upload
> Bundle ID: some bundle id

> Uploaded files to Sentry

> File processing complete
> Organization: my-org
> Project: my-project
> Release: my-release@1.0.1+1
> Dist: 1
> Upload type: artifact bundle

Source Map Upload Report
  Scripts
    ~/lib/main.dart
☑ uploading source maps                                                             

Could not determine any commits to be associated with a repo-based integration. Proceeding to find commits from local git tree.

No commits found. Leaving release alone. If you believe there should be some, change commits range or initial depth and try again.

Finalized release my-release@1.0.1+1
```

### Expected Result

Logs are not hidden in sentry io

### Actual Result

Logs are still hidden for some reasons

<img width="609" alt="Screenshot 2023-07-12 at 21 51 17" src="https://github.com/getsentry/sentry-dart/assets/39571861/0e152d56-eb6e-4a4c-85d7-c8504d9c5111">

### Are you willing to submit a PR?

None

**Comment by krystofwoldrich** [comment]
Hi, 
thank you for the message,
the event titles are not symbolicated at the moment, but we are working on it, more information -> https://github.com/getsentry/sentry-dart/issues/2805.

Is the stack trace of the error symbolicated (not obfuscated)?

**Comment by memishood** [comment]
Hi, 
thanks for the answer,
stack trace is also obfuscated

<img width="1106" alt="Screenshot 2023-07-13 at 13 24 37" src="https://github.com/getsentry/sentry-dart/assets/39571861/3b53e1c5-9862-4f33-9538-77dde063599a">

**Comment by marandaneto** [comment]
@memishood can you link me to an issue on sentry.io so I can check if the metadata is correct?

**Comment by memishood** [comment]
@marandaneto sure, how can I figure out permissions stuff in order to you can see?

**Comment by marandaneto** [comment]
> @marandaneto sure, how can I figure out permissions stuff in order to you can see?

If it's a sentry.io issue, I have enough permission for debugging, no worries, just share the issue's url.

**Comment by memishood** [comment]
I have created a public link for the issue
https://webmob-ou.sentry.io/share/issue/324a1ed819d24adda94f19b43b4a180f/

**Comment by marandaneto** [comment]
> I have created a public link for the issue [webmob-ou.sentry.io/share/issue/324a1ed819d24adda94f19b43b4a180f](https://webmob-ou.sentry.io/share/issue/324a1ed819d24adda94f19b43b4a180f/)

Thanks, will look into it.

**Comment by marandaneto** [comment]
@memishood https://github.com/getsentry/sentry/pull/52868 should address this issue, let's wait for this to be merged/released, and then we can test it again.

**Comment by marandaneto** [comment]
Closed by https://github.com/getsentry/sentry/pull/52868
@loewenheim is this published already?
@memishood let us know in case you find any issues again.

**Comment by loewenheim** [comment]
It's deployed, yes.

**Comment by memishood** [comment]
I’ll test it and let you know asap, thanks for your interests

**Comment by memishood** [comment]
I just tested, I verify that is fixed now, thank you again.
