### ISSUE TITLE
Request for Custom SpanStatus Constuctor

### ISSUE THREAD

**Issue by ostk0069** [getsentry/sentry-dart#1548]
### Problem Statement

by looking at https://github.com/getsentry/sentry-dart/blob/main/dart/lib/src/protocol/span_status.dart ,
`SpanStatus` only support custom SpanStatus with `SpanStatus.fromString()`.
Our project has original HttpStatus to handle.
Is there any problem to create constructor for both `value` and `httpStatusCode`.

### Solution Brainstorm

add constructor for SpanStatus with 
```dart
/// Creates SpanStatus from both String and httpStatusCode.
  factory SpanStatus.custom(String value, int httpStatusCode) => SpanStatus._(value, httpStatusCode);
```

### Are you willing to submit a PR?

Yes

**Comment by ostk0069** [comment]
I would like to create a PR, if there is no problem with it 
So, please let me know.

**Comment by krystofwoldrich** [comment]
Hi,
thank you for the message,
what you are suggesting looks to me like `SpanStatus.fromHttpStatusCode(statusCode)`? Or did I misunderstand?

https://github.com/getsentry/sentry-dart/blob/77ab5a09b7fd9293a0324d9049039019844c2331/dart/lib/src/protocol/span_status.dart#L85

**Comment by ostk0069** [comment]
> what you are suggesting looks to me like SpanStatus.fromHttpStatusCode(statusCode)? Or did I misunderstand?

our project has original http status which is not included in https://github.com/getsentry/sentry-dart/blob/main/dart/lib/src/protocol/span_status.dart  😢

**Comment by marandaneto** [comment]
@ostk0069 the Sentry's span status is a sentry protocol, it does not map 1:1 to the HTTP spec.
https://develop.sentry.dev/sdk/event-payloads/span/
We will eventually simplify this: https://github.com/getsentry/develop/issues/383 but we are not there yet.
So you may use the one that is close enough and has the same meaning for now.
