### ISSUE TITLE
Add `appHangTimeoutInterval` option to SentryFlutterOptions

### ISSUE THREAD

**Issue by mat-sf** [getsentry/sentry-dart#1550]
### Problem Statement

Hello!
I noticed that in the documentation for Sentry, there is a feature called `appHangTimeoutInterval` which can be utilized when initializing the Sentry SDK. I observed that this feature is available for Apple platforms (iOS) as mentioned here: [link to iOS documentation](https://docs.sentry.io/platforms/apple/configuration/app-hangs/). Additionally, I found that it is also supported in React Native as indicated in this documentation: [link to React Native documentation](https://docs.sentry.io/platforms/react-native/configuration/app-hangs/).

However, upon checking the latest package sentry_flutter version `7.8.0`, I couldn't find the `appHangTimeoutInterval` option. I believe it might have been overlooked or omitted. Is it possible to consider adding this option to the `sentry_flutter` package?

I appreciate your help!

### Are you willing to submit a PR?

No

**Comment by marandaneto** [comment]
Thanks @mat-sf 
We have to add this field for Flutter.
