### ISSUE TITLE
My project is flutter module in ios native app by cocoapods, how can i use ffi make flutter invoke ios method,who has the demo

### ISSUE THREAD

**Issue by xulidegitHub** [getsentry/sentry-dart#1551]
### Problem Statement

My Ios project use flutter module by cocoapods, how can i use the ffi in my poroject ,how to integrate? do you have the demo?

### Are you willing to submit a PR?

None

**Comment by marandaneto** [comment]
@xulidegitHub I am not sure I understand the question and/or problem.
Can you elaborate on the `Problem Statement`?

**Comment by marandaneto** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
