### ISSUE TITLE
Add manual init option and extra init method

### ISSUE THREAD

**Issue by zanezhangzz** [getsentry/sentry-dart#1558]
### Problem Statement

Becase of Chinese government policy. The application is not allowed to obtain any information of the phone, until the user agrees to your privacy policy. I have to manual init after user click 'Agree User Privacy Policy'.

### Solution Brainstorm

Add a option like ```bool manualInit``` in ```SentryFlutterOptions```
Add a methed like ```manualInit()``` in ```Sentry``` class

### Are you willing to submit a PR?

None

**Comment by marandaneto** [comment]
You can init the SDKs manually using this config https://docs.sentry.io/platforms/flutter/native-init/

**Comment by zanezhangzz** [comment]
OK, I miss this.  I find an other simple way for anyone need. Do not init sentry at first app start. 🤣

> You can init the SDKs manually using this config https://docs.sentry.io/platforms/flutter/native-init/

**Comment by CatEatFishs** [comment]
> 好吧，我想念这个。我找到了另一种简单的方法来满足任何人的需要。不要在应用程序首次启动时初始化哨兵。🤣
> 
> > 您可以使用此配置手动初始化 SDK https://docs.sentry.io/platforms/flutter/native-init/

你好！你是怎么处理不在应用程序首次启动时初始化sentry_flutter？

**Comment by zanezhangzz** [comment]
@CatEatFishs  很简单，设定一个变量存储在本地，第一次启动的后写入一个true，启动的时候读去这个变量，不存在则说明是第一次启动。
