### ISSUE TITLE
missing SentrySdkInfo.h and SentryTraceContext.h while integrate a Flutter module into iOS 

### ISSUE THREAD

**Issue by datoutwo** [getsentry/sentry-dart#1578]
### Platform

Dart

### Obfuscation

Disabled

### Debug Info

Disabled

### Doctor

[✓] Flutter (Channel master, 3.13.0-16.0.pre.22, on macOS 13.0 22A380 darwin-arm64, locale en-DE)
    • Flutter version 3.13.0-16.0.pre.22 on channel master at /Users/delanwang/Work/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision dc4ab0f5df (7 hours ago), 2023-08-02 07:40:14 +0000
    • Engine revision 9dae7b708b
    • Dart version 3.2.0 (build 3.2.0-22.0.dev)
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/delanwang/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.80.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (3 available)
    • iPhone 14 Pro (mobile) • 2E1317F9-6350-4B51-B494-8248E4E67B29 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 13.0 22A380 darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 114.0.5735.198

[✓] Network resources
    • All expected network resources are available.

### Version

7.9.0

### Steps to Reproduce

1. Create flutter application and add sentry_flutter into `pubspec.yml`.  
2. Create an iOS App via xcode.
3. Following steps of integrate a Flutter module into iOS  - [Option B](https://docs.flutter.dev/add-to-app/ios/project-setup#option-b---embed-frameworks-in-xcode) to add xcframework 
4. Build (⌘ + b) will find the build error message in `SentryEnvelope.h`.: missing `SentrySdkInfo.h` and `SentryTraceContext.h` 
5. After adding manually build success.
![image](https://github.com/getsentry/sentry-dart/assets/16434858/53ffc40f-a296-432b-869e-0c0811d03726)

### Expected Result

Build success

### Actual Result

Build failed

### Are you willing to submit a PR?

None

**Comment by krystofwoldrich** [comment]
@datoutwo Thank you for the message and the details. Due to current vacations, the response time might be a bit longer. 

Would you be able to share a minimal reproducible example? That would help us speed up the investigation.

**Comment by datoutwo** [comment]
Hi, here's minimal reproducible example as zip below, please let me know if there's any other information I need to provide. 
Thanks.
  
[TestSentry.zip](https://github.com/getsentry/sentry-dart/files/12261790/TestSentry.zip)

**Comment by marandaneto** [comment]
@datoutwo any reason to not use cocoapods instead?
Via cocoapods, we just add the dependency and it works https://github.com/getsentry/sentry-dart/blob/main/flutter/ios/sentry_flutter.podspec#L15

Also on Sentry Cocoa, all listed classes are here https://github.com/getsentry/sentry-cocoa/blob/d3630c3fdded1034c22bc36cc781cdbb8ec70007/Sentry.podspec#L39-L45

Maybe take a look if you need to important something more?

**Comment by datoutwo** [comment]
@marandaneto currently we are using SPM not cocoaPods in our project, will investigate how to use both in our building environment.

**Comment by marandaneto** [comment]
> @marandaneto currently we are using SPM not cocoaPods in our project, will investigate how to use both in our building environment.

Ok, let me know if you find out anything.

**Comment by marandaneto** [comment]
@datoutwo any follow up here?

**Comment by datoutwo** [comment]
@marandaneto 
Currently, we tried the xcframeworks and add those missing header files manually, then it works fine. Is there any suggestion to avoid do it manually? Will there be a fix to add those missing files?
 
We test cocoaPods works fine with a simple project. Haven't try to add in the real environment with SPM yet.

**Comment by marandaneto** [comment]
@brustolin are the hybrid sdk files exported for spm? Or just cocoapods?

**Comment by brustolin** [comment]
> @brustolin are the hybrid sdk files exported for spm? Or just cocoapods?

No, hybrid SDK files are not available with SPM.

**Comment by stefanosiano** [comment]
@brustolin Does it make sense to support hybrid SDK files on SPM? If so, how long would it take?

**Comment by brustolin** [comment]
> @brustolin Does it make sense to support hybrid SDK files on SPM? If so, how long would it take?

Do you have any specific reason?
We don't have any hybrid SDK that depends on SPM, I don't see why we would do that.
Also, it can be tricky to get it to work with SPM.

**Comment by stefanosiano** [comment]
Hi @datoutwo 
Did you find a way to use cocoapods and SPM at the same time? Does it work for you?

**Comment by datoutwo** [comment]
Hi @stefanosiano, thank you for keeping update. We have just changed to use cocoaPods. Thanks again, closing this issue.
