### ISSUE TITLE
Streamline and align the "Getting Started" docs to fit in the new structure

### ISSUE THREAD

**Issue by priscilawebdev** [getsentry/sentry-dart#1585]
### Problem Statement

- The "Getting Started" documentation for all sentry-dart platforms may not conform to the newly defined format, which includes the steps "Install", "Configure", "Verify", and the optional "Next Steps".
    - The "Verify" step is not always available and it is a very important step that helps the user to verify that the installation and configuration were done correctly.
- New users onboarding with Sentry may find the existing documentation extensive and unclear. The "Getting Started" guide should cover the basics, while more advanced configurations shall live on the [sentry-docs website](https://docs.sentry.io/).
- Some copies and code snippets in the documentation may be outdated.

### Solution Brainstorm

The task goals are as follows:

- Thoroughly review all sentry-dart platform documentation, including less commonly used sections, and reorganize their content into structured headings: 'Install,' 'Configure,' 'Verify,' and the optional 'Next Steps.'
- The onboarding documentation should strictly focus on the basics to help users get started. Advanced configurations should be available in the complete documentation on the [sentry-docs website](https://docs.sentry.io/).
- Essential information for new users should be included under the new 'Notes' section in the onboarding documentation.
- Update code snippets and copies as necessary.
- If a "Verify" step is missing, include it in the documentation.

Please refer to the "Frontendend Handbook" guide in our "Sentry" main repository for assistance in adding and updating the getting started docs: [Frontendend Handbook](https://develop.sentry.dev/frontend/working-on-getting-started-docs/). 

**Project:** https://github.com/getsentry/team-sdks/issues/23

**Comment by denrase** [comment]
I looked through everything. `dart` and `flutter` are already in the list of migrated frameworks. They follow the new format, have sample code & icons. So everything should be there, at least as far as I can tell.

The only thing that `dart` & `flutter` do is they have extra sections after `Verify`, which are on the same hierarchy level, for example a description on how to setup `Performance`. Is this something we want to remove?

Only discovered a small improvement in the dart getting started sample, for which i created a PR: https://github.com/getsentry/sentry/pull/57348

@kahest @priscilawebdev Is there anything else that needs to be done to close this issue?

**Comment by kahest** [comment]
@ArthurKnaus @denrase currently looks like this 
![getting-started-dart](https://github.com/getsentry/sentry-dart/assets/2005158/b513394e-eecf-4cc0-90e0-f425a8a2cbeb)
![getting-started-flutter](https://github.com/getsentry/sentry-dart/assets/2005158/0de83fac-6f7b-4001-8d14-f2857db9dd0d)

To adhere to the generic structure, should the current sections `Performance` (Dart+Flutter) and `Debug Symbols` + `Source Context` (Flutter only) should go under a new section `Next Steps`?

**Comment by ArthurKnaus** [comment]
@kahest @denrase 
I am not familiar with the mobile SDK functionality. If this is required to get performance measurements / if there is no automatic instrumentation, I would keep it in there. Otherwise move it to "next steps".
If it makes sense please also move "Debug Symbols" and "Source context" to the next steps. We only want the minimal information to get the user started in these docs.

**Comment by kahest** [comment]
@ArthurKnaus Thanks for clarifying - there is no monkeypatching mechanism or similar in Flutter/Dart, so to get perf instrumentation, the user needs to at least add minimal init/wrapping, see [relevant docs](https://docs.sentry.io/platforms/flutter/performance/instrumentation/automatic-instrumentation).

@denrase My take is then that we should keep the `Performance` section for Flutter+Dart, but we can move `Debug Symbols` and `Source Context` under a `Next Steps` section similar to here on javascript: 

![getting-started-browser-javascript](https://github.com/getsentry/sentry-dart/assets/2005158/52d6fbb5-ead1-4d8c-8992-1688d74414e9)

**Comment by kahest** [comment]
@buenaflor I assume we can close this?

**Comment by denrase** [comment]
@kahest Yeas, the relevant PRs have been merged.
