### ISSUE TITLE
Image upload option during user feedback

### ISSUE THREAD

**Issue by sanalkv** [getsentry/sentry-dart#1593]
### Problem Statement

Would be great if there is an image upload option during the user feedback.

### Are you willing to submit a PR?

None

**Comment by marandaneto** [comment]
@sanalkv you can send images as attachments https://docs.sentry.io/platforms/flutter/enriching-events/attachments/
it's not part of the user feedback API but still possible.
Also, there's the screenshots feature https://docs.sentry.io/platforms/flutter/enriching-events/screenshots/ which takes the SS automatically if there's an error, does that help you?

**Comment by sanalkv** [comment]
For the time being i can try this out, but i was looking for something like what Instabug is having. Where use can report an issue and upload image or take screenshot and even add marks on the screenshot all through the sdk. I think this is something we can bring into sentry.

**Comment by marandaneto** [comment]
Ok, I will tag this as a feature request.

**Comment by Codel1417** [comment]
Sentry now supports attachments with User Feedback V2

- https://github.com/getsentry/sentry-javascript/pull/11428
- https://github.com/getsentry/sentry/issues/49946

Though the docs are missing

- https://github.com/getsentry/develop/issues/1206
- https://github.com/getsentry/develop/issues/1208

**Comment by buenaflor** [comment]
~This is part of `8.10.0-beta.1`~

**Comment by denrase** [comment]
Closing here due to [#2369](https://github.com/getsentry/sentry-dart/pull/2369) being merged.
