### ISSUE TITLE
[Starfish] Add db attributes to database span's span data

### ISSUE THREAD

**Issue by AbhiPrasad** [getsentry/sentry-dart#1594]
To get an overview of this work across all SDKs, please visit:
https://github.com/orgs/getsentry/projects/135

Parent issue: https://github.com/getsentry/team-sdks/issues/19

For the starfish db module it was determined that we need extra database attributes.

`db.name` should be set if possible, but is not required. `db.system` should match the list in [OpenTelemetry's well known conventions](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/database.md#notes-and-well-known-identifiers-for-dbsystem).

| Attribute  | Type | Description  | Examples  | Requirement Level |
|---|---|---|---|---|
| `db.system` | string | An identifier for the database management system (DBMS) product being used. | `sqlite` | Required |
| `db.name` | string | This attribute is used to report the name of the database being accessed. For commands that switch the database, this should be set to the target database (even if the command fails). | `customers`; `main` | Conditionally Required: If applicable. |

These values should be set on `span.data`.

### Motivation

This is being done for the Sentry's [new performance views for databases](https://sentry.sentry.io/starfish/database/). See a WIP example of the view below:

<img width="1251" alt="image" src="https://github.com/getsentry/sentry-laravel/assets/18689448/962c5fea-1b38-481c-ba22-7046a33ea454">

**Comment by buenaflor** [comment]
Should these attributes also be set on spans for opening/closing db? or strictly only for queries

**Comment by AbhiPrasad** [comment]
@buenaflor preferably only on the query span, but it's also fine to duplicate the attributes among all db related spans.
