### ISSUE TITLE
Hard to locate where the error issue is

### ISSUE THREAD

**Issue by betimer** [getsentry/sentry-dart#1595]
### Platform

Dart

### Obfuscation

Enabled

### Debug Info

Enabled

### Doctor

 Flutter (Channel stable, 3.10.5, on Microsoft Windows [Version 10.0.22621.2134], locale en-AU)
    • Flutter version 3.10.5 on channel stable at C:\xsrc\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (8 weeks ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

### Version

7.9

### Steps to Reproduce

Just any exception happens on flutter app (I am firstly checking web app)

### Expected Result

The error message and stack trace does not help to locate the exact line of error happening.

### Actual Result

![image](https://github.com/getsentry/sentry-dart/assets/8111748/0bf58ae2-5eb6-4a41-a965-57165e27be5d)

### Are you willing to submit a PR?

None

**Comment by marandaneto** [comment]
@betimer for Flutter web apps, you have to upload debug symbols (source maps) for the symbolication of the stack trace
https://docs.sentry.io/platforms/flutter/upload-debug/
