### ISSUE TITLE
Local scope not working properly

### ISSUE THREAD

**Issue by guilhermeagostinelli** [getsentry/sentry-dart#1597]
### Platform

Flutter Mobile

### Obfuscation

Enabled

### Debug Info

Enabled

### Doctor

[!] Flutter (Channel stable, 3.10.6, on Ubuntu 22.04.2 LTS 5.15.0-78-generic, locale en_US.UTF-8)
    • Flutter version 3.10.6 on channel stable at /home/guilherme/fvm/versions/3.10.6
    ! Warning: `flutter` on your path resolves to /home/guilherme/snap/flutter/common/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /home/guilherme/fvm/versions/3.10.6. Consider adding /home/guilherme/fvm/versions/3.10.6/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /home/guilherme/snap/flutter/common/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /home/guilherme/fvm/versions/3.10.6. Consider adding /home/guilherme/fvm/versions/3.10.6/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (4 weeks ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /home/guilherme/Android/Sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /home/guilherme/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✗] Linux toolchain - develop for Linux desktop
    ✗ clang++ is required for Linux development.
      It is likely available from your distribution (e.g.: apt install clang), or can be downloaded from https://releases.llvm.org/
    ✗ CMake is required for Linux development.
      It is likely available from your distribution (e.g.: apt install cmake), or can be downloaded from https://cmake.org/download/
    ✗ ninja is required for Linux development.
      It is likely available from your distribution (e.g.: apt install ninja-build), or can be downloaded from https://github.com/ninja-build/ninja/releases
    • pkg-config version 0.29.2

[✓] Android Studio (version 2022.1)
    • Android Studio at /home/guilherme/android-studio
    • Flutter plugin version 72.1.2
    • Dart plugin version 221.6103.1
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code
    • VS Code at /snap/code/current
    • Flutter extension version 3.70.0

[✓] Connected device (3 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 12 (API 31) (emulator)
    • Linux (desktop)              • linux         • linux-x64      • Ubuntu 22.04.2 LTS 5.15.0-78-generic
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 115.0.5790.110

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.

### Version

7.9.0

### Steps to Reproduce

```dart
Future<void> captureException({
    required Object exception,
    required StackTrace stackTrace,
    required Map<String, String>? tags,
  }) {
    return Sentry.captureException(
      exception,
      stackTrace: stackTrace,
      withScope: (scope) {
        for (final t in (tags ?? {}).entries) {
          scope.setTag(t.key, t.value);
        }
      },
    );
  }


void main() {
  runZonedGuarded(() async {
    await SentryFlutter.init(
      (options) {
        options.dsn = 'MY-DSN';
        options.tracesSampleRate = 1.0;
        options.attachScreenshot = true;
        options.environment = 'dev';
      },
    );

    runApp(
      const SentryScreenshotWidget(
        child: MyApp(),
      ),
    );
  }, (e, s) async {
    await captureException(
      exception: e,
      stackTrace: s,
    );
  });
}


// Then, once a button on a given page is clicked, the following is executed:
void buttonClicked() {
    try {
      throw Exception('test');
    } catch (e, s) {
      captureException(
        exception: e,
        stackTrace: s,
        tags: {'pkr_error_id':  'TEST-PREFIX-1'},
      );
    }
    try {
      throw Exception('test2');
    } catch (e, s) {
      captureException(
        exception: e,
        stackTrace: s,
      );
    }
    try {
      throw Exception('test3');
    } catch (e, s) {
      captureException(
        exception: e,
        stackTrace: s,
        tags: {'pkr_error_id':  'TEST-PREFIX-3'},
      );
    }
  }
```

### Expected Result

The exceptions are properly reported in the Sentry's Issues dashboard, and:
- 'test1' exception has the custom tag pkr_error_id: TEST-PREFIX-1
- **'test2' exception doesn't have the pkr_error_id custom tag**
- 'test3' exception has the custom tag pkr_error_id: TEST-PREFIX-3

### Actual Result

The exceptions are properly reported in the Sentry's Issues dashboard, and:
- 'test1' exception has the custom tag pkr_error_id: TEST-PREFIX-1
- **'test2' exception has the custom tag pkr_error_id: TEST-PREFIX-3**
- 'test3' exception has the custom tag pkr_error_id: TEST-PREFIX-3

I've also tried to change the code to:
```dart
Future<void> captureException({
    required Object exception,
    required StackTrace stackTrace,
    required Map<String, String>? tags,
    required Map<String, dynamic>? contexts,
  }) {
    return Sentry.captureException(
      exception,
      stackTrace: stackTrace,
      withScope: (scope) {
        if (tags?.isNotEmpty == true) {
          for (final t in tags!.entries) {
            scope.setTag(t.key, t.value);
          }
        } else {
          for (final t in scope.tags.entries) {
            scope.removeTag(t.key);
          }
        }
        for (final c in (contexts ?? {}).entries) {
          scope.setContexts(c.key, c.value);
        }
      },
    );
  }
```

but the error persisted

### Are you willing to submit a PR?

None

**Comment by buenaflor** [comment]
Hi! Thanks for creating an issue, we are looking into this.

**Comment by marandaneto** [comment]
> Hi! Thanks for creating an issue, we are looking into this.

did you debug this issue? any ideas?

**Comment by buenaflor** [comment]
@marandaneto The tags are set incorrectly when applying the event processors during `_runEventProcessors`. `_LoadContextsIntegrationEventProcessor` looks to be the culprit on iOS. However on Android this is not the case and it is still including the wrong tags.

**Comment by buenaflor** [comment]
Short update, it seems that local scopes are being merged together if capturing exceptions is executed directly after one another so this doesn't only concern tags. Still investigating the cause of this.

**Comment by denrase** [comment]
Glancing over it it may have to do with scope sync. We should not sync the scope to the bridge for scope clones created for specific events as far as i understand. Will try to reproduce this and check if this indeed is the issue.
