### ISSUE TITLE
Modify dsn after initialization 

### ISSUE THREAD

**Issue by ahmdt** [getsentry/sentry-dart#1603]
### Problem Statement

Hi, is there a way to modify the dsn after initialization?
China's Firewall slows down the traffic to our default domain and because of that we need a proxy.
User can activate the proxy in the app settings. 

### Solution Brainstorm

A setter or update function would be nice. Since you pass the appRunner, I'm afraid you just have to restart the whole app currently.

### Are you willing to submit a PR?

None

**Comment by stefanosiano** [comment]
Hi @ahmdt, sadly we currently don't support modifying the dsn after the SDK has been initialized.
You can either wait to init the SDK until a proxy is selected (if it's a viable option for you) or restart the whole app

**Comment by marandaneto** [comment]
You can also close the SDK and init it again.
The 2nd time you can skip the runner callback.

**Comment by krystofwoldrich** [comment]
As @marandaneto mentioned in https://github.com/getsentry/sentry-dart/issues/1603#issuecomment-1682524983 you can reinitialize the SDK with the new DSN and skip the runner callback the second time.

If you run into any problems related to this feel free to comment here and we can reopen the issue.
