### ISSUE TITLE
Fix integration test

### ISSUE THREAD

**Issue by vaind** [getsentry/sentry-dart#1605]
### Description

The integration test is currently broken. 

1. it's missing auth token
2. it fails with `'package:flutter_test/src/binding.dart': Failed assertion: line 954 pos 14: '_pendingExceptionDetails != null': A test overrode FlutterError.onError but either failed to return it to its original state, or had unexpected additional errors that it could not handle. Typically, this is caused by using expect() before restoring FlutterError.onError.`
3. it was timing out because of the exponential request delay growth (waiting for 17 minutes for a single request on the last retry...)

The third point was fixed by #1604, together with disabling the test in CI before it's fixed.

**Comment by vaind** [comment]
FYI @denrase - you're the one to have worked on this most recently AFAIK - maybe you know what the issue is right away

**Comment by denrase** [comment]
@vaind Thank you, i'll take a look

**Comment by denrase** [comment]
@vaind Here's another one. I'm also seeing flaky-ness when the tests run fine. From the logs it looks like the test device is prematurely shut down.

<img width="1170" alt="Bildschirmfoto 2023-08-28 um 16 26 50" src="https://github.com/getsentry/sentry-dart/assets/3984453/4b639f7d-25e0-4a7f-b285-e0cb715a1d6f">
