### ISSUE TITLE
refactor: use `pigeon` to create type-safe platform binding

### ISSUE THREAD

**Issue by vaind** [getsentry/sentry-dart#1608]
### Description

Instead of manually managing platform-specific function calls, using [Pigeon](https://docs.flutter.dev/platform-integration/platform-channels?tab=type-mappings-swift-tab#pigeon) type-safe code generator could help with maintenance.

**Comment by ueman** [comment]
An alternative to this could be to use [ffigen](https://pub.dev/packages/ffigen) and [jnigen](https://pub.dev/packages/jnigen).

**Comment by vaind** [comment]
> An alternative to this could be to use [ffigen](https://pub.dev/packages/ffigen) and [jnigen](https://pub.dev/packages/jnigen).

I was trying to address Flutter platform-specific code (via method channels), not native invocation (FFI) so I don't think those two help.

**Comment by ueman** [comment]
Both are direct replacements for MethodChannels. ffigen can bind to Swift code, so you could call the Sentry Cocoa SDK directly from Dart code. Same thing for the Kotlin code, which can then directly be used from Dart.

**Comment by marandaneto** [comment]
@vaind already thought about it, Firebase started recently using `pigeon` as well, an alternative is https://github.com/getsentry/sentry-dart/issues/1444
React Native is now also with the possibility of code generation for gluing the platform-specific -> native code calls.
There are trade-offs tho.

**Comment by vaind** [comment]
Thanks for the pointer, I've missed the new (in-development) interop since the last time I've actively worked on this.

In that case, I think that going with native interop without method channels would be preferable (performance-wise) so feel free to close this issue in favor of #1444.

**Comment by krystofwoldrich** [comment]
Close in favor of https://github.com/getsentry/sentry-dart/issues/1444
