### ISSUE TITLE
Accept Map<String, dynamic> in Hint class

### ISSUE THREAD

**Issue by nimi0112** [getsentry/sentry-dart#1610]
### Problem Statement

I want to send some data through `hint` in `Sentry.captureException`.

That data may be null but `Hint` class does not accept a Map with `<String,dynamic>` in `Hint.withMap` constructor.

At the end I just want to see the data I send through Map on the dashboard.

If feasible, please add it.

### Solution Brainstorm

Change to type from `final Map<String, Object> _internalStorage = {};` to `final Map<String, dynamic> _internalStorage = {};` in `lib/src/hint.dart:42`.

### Are you willing to submit a PR?

Yes

**Comment by kahest** [comment]
Hey @nimi0112 thanks for writing in with your suggestion, we will discuss and prio this!
