### ISSUE TITLE
Repository example doesn't remove obfuscation for web

### ISSUE THREAD

**Issue by ygotthilf** [getsentry/sentry-dart#1615]
### Platform

Flutter Web

### Obfuscation

Disabled

### Debug Info

Disabled

### Doctor

[✓] Flutter (Channel stable, 3.10.5, on macOS 13.3.1 22E772610a darwin-arm64, locale en-FR)
    • Flutter version 3.10.5 on channel stable at /Users/yg/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (3 months ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/yg/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.79.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.3.1 22E772610a darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 116.0.5845.110

[✓] Network resources
    • All expected network resources are available.

• No issues found!

### Version

7.9.0

### Steps to Reproduce

1. Create a new project on Sentry
2. Clone this repo
3. Open the `flutter/example` folder in your favorite IDE
4. Change the DSN in the `lib/main.dart`
5. Change the `org` property in the `pubspec.yaml` 
6. Run `./run.sh web`
7. Click on a bouton in the opened app

### Expected Result

The stacktrace should be not obfuscated in Sentry, but it is. I have tried the example because I have the same problem in my project. But both didn't work :/

Please note the example uploads two releases and cannot link the source map to the release of the exception.

### Actual Result

<img width="1447" alt="Screenshot 2023-08-29 at 10 24 31" src="https://github.com/getsentry/sentry-dart/assets/1472455/1424e834-bf5a-4c2f-9680-22b84fe8ead4">
<img width="1447" alt="Screenshot 2023-08-29 at 10 24 22" src="https://github.com/getsentry/sentry-dart/assets/1472455/4d421634-953d-4666-b3d2-2dd97158af27">
<img width="1449" alt="Screenshot 2023-08-29 at 10 23 51" src="https://github.com/getsentry/sentry-dart/assets/1472455/d6c35956-58d3-446c-ac03-394ab581239d">

### Are you willing to submit a PR?

No

**Comment by buenaflor** [comment]
Thank you for the issue, we will look into this

**Comment by denrase** [comment]
@buenaflor While I can reproduce, i'm not sure how to resolve this. Lets discuss this in person.

**Comment by denrase** [comment]
We have the same behaviour on version 7.0.0 of the SDK. Could not run lower version without changing code/dependencies.

**Comment by denrase** [comment]
Linking #1565 here, as it is relevant for this issue.

**Comment by buenaflor** [comment]
Web deobfuscation on a new flutter project works for me. However I can reproduce this error in the sample app. Do you have more information on why this might be happening in the sample? @denrase

**Comment by denrase** [comment]
@buenaflor Unfortunately I don't have more info on this. If it works for new projects, I don't see a reason why this is not working in our samaple app except that the SDK config might be different.

**Comment by buenaflor** [comment]
I identified the error.

`run.sh` creates a release based on the current date and the plugin will automatically attach the current version to it.

<img width="1168" alt="image" src="https://github.com/getsentry/sentry-dart/assets/23364143/a4cd244a-2de9-47b2-b9ab-19662effe7a1">

However the SDK itself will only create a release with the date without attaching the sdk version.

So there's a mismatch in sdk release and the release created from the dart plugin.

The fix is to add the version automatically similar to this:

```bash
VERSION=$(grep '^version:' pubspec.yaml | awk '{print $2}')
CURRENT_DATE=$(date +%Y-%m-%d_%H-%M-%S)

export SENTRY_RELEASE="$CURRENT_DATE"@"$VERSION"
```

I'll open a PR for that
