### ISSUE TITLE
Reporting on native crashes ?

### ISSUE THREAD

**Issue by matejkramny** [getsentry/sentry-dart#162]
1. Please describe the issue and how to reproduce it, or link to a small reproducible application:

We have a production app that crashes under certain conditions. The crash does not seem to be reported in Sentry.

2. Include the output of the command `flutter doctor` below:

not relevant

--

Would Sentry pick up a native code crash, f.e. something with a plugin or an exception not happening in dart/flutter?

I can see the source code asks for Sentry cocoa sdk to be installed and configured. Just wanted to double check before we go around adding native Sentry SDK libraries as well to catch additional errors.

Thanks!

**Comment by bruno-garcia** [comment]
@matejkramny support is being added in the next few days.

**Comment by matejkramny** [comment]
Ah ok perfect

**Comment by marandaneto** [comment]
https://github.com/getsentry/sentry-dart/releases/tag/4.0.0-alpha.2
