### ISSUE TITLE
Dependency conflict with uuid version 4.0.0

### ISSUE THREAD

**Issue by nwgiles** [getsentry/sentry-dart#1623]
### Platform

Dart

### Obfuscation

Enabled

### Debug Info

Enabled

### Doctor

[√] Flutter (Channel stable, 3.10.2, on Microsoft Windows [Version 10.0.22621.2134], locale en-US)
    • Flutter version 3.10.2 on channel stable at C:\Users\User\flutter_windows_3.10.2-stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9cd3d0d9ff (3 months ago), 2023-05-23 20:57:28 -0700
    • Engine revision 90fa3ae28f
    • Dart version 3.0.2
    • DevTools version 2.23.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at C:\Users\User\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.6.2)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Pixel 4 (mobile)  • 9B191FFAZ0079Z • android-arm64  • Android 13 (API 33)
    • Windows (desktop) • windows        • windows-x64    • Microsoft Windows [Version 10.0.22621.2134]
    • Chrome (web)      • chrome         • web-javascript • Google Chrome 116.0.5845.141
    • Edge (web)        • edge           • web-javascript • Microsoft Edge 114.0.1823.51

[√] Network resources
    • All expected network resources are available.

• No issues found!

### Version

7.9.0

### Steps to Reproduce

Upgrade uuid to version 4.0.0 and run flutter pub get

### Expected Result

Dependencies to be resolved

### Actual Result

Resolving dependencies...
Because sentry_flutter >=7.9.0 depends on sentry 7.9.0 which depends on uuid ^3.0.0, sentry_flutter >=7.9.0 requires uuid ^3.0.0.
So, because flutter_test_app depends on both uuid ^4.0.0 and sentry_flutter ^7.9.0, version solving failed.

### Are you willing to submit a PR?

None

**Comment by buenaflor** [comment]
hi! thank you for the issue, I'll look into it
