### ISSUE TITLE
Example folder can be found when using pacakge from pub.dev

### ISSUE THREAD

**Issue by guyluz11** [getsentry/sentry-dart#1634]
### Platform

Flutter Mobile

### Obfuscation

Enabled

### Debug Info

Enabled

### Doctor

$ flutter doctor -v
[✓] Flutter (Channel stable, 3.10.0, on Ubuntu 23.04 6.2.0-32-generic, locale en_IL)
    • Flutter version 3.10.0 on channel stable at /home/guy/Programs/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 84a1e904f4 (4 months ago), 2023-05-09 07:41:44 -0700
    • Engine revision d44b5a94c9
    • Dart version 3.0.0
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /home/guy/Programs/Android/jdk/
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /snap/android-studio/127/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 15.0.7
    • cmake version 3.25.1
    • ninja version 1.11.1
    • pkg-config version 1.8.1

[✓] Android Studio (version 2022.3)
    • Android Studio at /snap/android-studio/127/android-studio
    • Flutter plugin version 75.1.2
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] Android Studio (version 2022.2)
    • Android Studio at /snap/android-studio/126/android-studio
    • Flutter plugin version 75.1.1
    • Dart plugin version 222.4582
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code
    • VS Code at /snap/code/current
    • Flutter extension version 3.70.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 23.04 6.2.0-32-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 116.0.5845.179

[✓] Network resources
    • All expected network resources are available.

• No issues found!

### Version

^7.8.0

### Steps to Reproduce

1. Open project with the package  included
2. Go to Android Studio IDE
3. Search for alertDialog in your project

### Expected Result

Will find only my project search results, example folder of this project should not be downloaded.

### Actual Result

Example folder is downloaded and can be found in the search results.

As written here https://github.com/dart-lang/pub-dev/issues/5862 you need to manually add `example` folder to `.pubignore`

### Are you willing to submit a PR?

No

**Comment by buenaflor** [comment]
Thanks for the context. Seems to be a good idea to exclude it from the package.

**Comment by stefanosiano** [comment]
Let's not do it, after considerations from the [pub-dev issue](https://github.com/dart-lang/pub-dev/issues/5862#issuecomment-1741972533)
summary: removing example from package would remove its tab from pub.dev. IDEs and tools should fix their own searches and exclude pub.dev dependencies examples.
In case it becomes relevant again, feel free to reopen this issue and we will reevaluate it
