### ISSUE TITLE
Add `tracePropagationTargets` example to docs

### ISSUE THREAD

**Issue by maxlapides** [getsentry/sentry-dart#1652]
### Platform

Flutter Web

### Obfuscation

Enabled

### Debug Info

Enabled

### Doctor

[✓] Flutter (Channel stable, 3.13.4, on macOS 13.5.2 22G91 darwin-arm64, locale en-US)
    • Flutter version 3.13.4 on channel stable at /Users/maxlapides/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 367f9ea16b (8 days ago), 2023-09-12 23:27:53 -0500
    • Engine revision 9064459a8b
    • Dart version 3.1.2
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/maxlapides/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • ANDROID_HOME = /Users/maxlapides/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.82.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.72.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.5.2 22G91 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 116.0.5845.187

[✓] Network resources
    • All expected network resources are available.

• No issues found!

### Version

7.10.1

### Steps to Reproduce

I can't find any way to use the `tracePropagationTargets` feature with Sentry for Flutter. We need to be able to use this feature because right now Sentry is injecting headers into requests, which are breaking our app. For example, this is invalid syntax:

```
SentryFlutter.init(
    (options) {
      options.tracePropagationTargets = [''];
    },
    appRunner: () {
      ...
    },
  );
```

### Expected Result

Some documentation on how to use `tracePropagationHeaders` with Sentry for Flutter

### Actual Result

No documentation

### Are you willing to submit a PR?

None

**Comment by krystofwoldrich** [comment]
Hi,
thank you for the message, we will update the docs.

Here is an example of how you can use the `tracePropagationTargets` option:

```dart
  await SentryFlutter.init((options) {
    options.tracePropagationTargets.clear();
    options.tracePropagationTargets.addAll(["your-domain.com"]);
  }
```

**Comment by maxlapides** [comment]
Thanks so much @krystofwoldrich!
