### ISSUE TITLE
[iOS] Issues don't appear using real devices

### ISSUE THREAD

**Issue by wojciechzahradnikdeviniti** [getsentry/sentry-dart#1654]
### Platform

Dart

### Obfuscation

Disabled

### Debug Info

Disabled

### Doctor

[✓] Flutter (Channel stable, 3.10.6, on macOS 13.4.1 22F82 darwin-arm64, locale pl)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.82.2)
[✓] Connected device (4 available)
[✓] Network resources

### Version

7.10.1

### Steps to Reproduce

Hello I configured Sentry for Flutter.
When I build my app from VSCode then I can see issues in my sentry dashboard from android and iOS simulator. 
I also can see issues from Android and iOS real device.

But when I build my app using bitrise&fastlane to firebase app distribution then I have the problem with iOS real devices.
In bitrise I build my app using command:
```
flutter build ios --debug --flavor development --no-codesign --build-number=123
```
It works on Android so the problem is only with iOS. 

I also found that build from TestFlight
```
flutter build ios --release --flavor production --no-codesign --build-number=123
```
also have the same problem.

Maybe I do something wrong?

My code:
```
Future<void> main() async {
  await runZonedGuarded(
    () async {
      WidgetsFlutterBinding.ensureInitialized();

      await SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp]);

      _runAppLogger();

      await SentryFlutter.init(
        (options) {
          options
            ..dsn = Env.sentryProjectDns
            ..enableTracing = true
            ..tracesSampleRate = 1.0
            ..debug = kDebugMode;
        },
        appRunner: () => runApp(
          Application(),
        ),
      );
    },
    (error, stackTrace) => logSevere('Exception caught in presentation layer', error, stackTrace),
  );
}

void _runAppLogger() {
  Bloc.observer = AppBlocObserver();

  AppLogger.instance().configure(
    level: kDebugMode ? AppLogger.levelAll : AppLogger.levelSevere,
  );

  if (kDebugMode) {
    AppLogger.instance().enableConsoleOutput();
  }

  FlutterError.onError = (details) => logSevere(
        'FlutterError caught in app',
        details.exception,
        details.stack,
      );

  AppLogger.instance().output(
    (entry) async {
      if (entry.error != null) {
        await Sentry.captureException(
          entry.error,
          stackTrace: entry.stackTrace,
        );
      }
    },
  );
}
```

### Expected Result

I am able to see issues from iOS devices in my sentry dashboard.s

### Actual Result

I am not able to see issues from iOS devices in my sentry dashboard.

### Are you willing to submit a PR?

No

**Comment by ueman** [comment]
Half of the code of your example isn't needed. The `runZoneGuarded` is discouraged and not needed anymore since a couple of Flutter versions already. Settings `FlutterError.onError` yourself is also not needed as Sentry does that already. Sentry also calls `WidgetsFlutterBinding.ensureInitialized();`, so you don't need to.

Basically, you should try the following code and see whether it fixes your problem

```dart
await SentryFlutter.init(
  (options) {
    options
      ..dsn = Env.sentryProjectDns
      ..enableTracing = true
      ..tracesSampleRate = 1.0
      ..debug = kDebugMode;
  },
);

await SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp]);
Bloc.observer = AppBlocObserver();

runApp(Application());
```

I'm not quite sure what the `AppLogger` should do, so I left it out of the example. If it decides whether something should be logged to Sentry, try using the `beforeSend` callback and drop the events instead.

**Comment by wojciechzahradnikdeviniti** [comment]
Ok I solved it. All my code is fine. The problem was in AppLogger.
