### ISSUE TITLE
Improve the support for Flutter on Web

### ISSUE THREAD

**Issue by marianhlavac** [getsentry/sentry-dart#1661]
### Description

_I'd like to follow up on the issues https://github.com/getsentry/sentry-dart/issues/417 and https://github.com/flutter/flutter/issues/37875_

It [seems like from 2021](https://github.com/getsentry/sentry-dart/issues/417#issuecomment-897480519) the support for Flutter on Web has not improved and the default experience using Sentry with Flutter on web is, let's be honest, pretty terrible. At least when compared with how well Sentry works for Flutter on iOS and Android.

Android/iOS | Web
--- | ---
<img alt="Screenshot 2023-09-29 at 12 58 12" src="https://github.com/getsentry/sentry-dart/assets/3010503/a29d0a30-b7c8-4929-8bf8-0a1b0658c65f"> | <img alt="Screenshot 2023-09-29 at 12 58 24" src="https://github.com/getsentry/sentry-dart/assets/3010503/0c9cc46f-ea82-4468-b285-d4f9a45d4079">

**Namely the current issues:**
- The issue titles are missing completely, and contains only `minified:xx`
- Files in stacktrace are prefixed with `org-dartlang-sdk:///dart-sdk/lib/...`, or contain absolute URLs of the machine where the app was built, or similar issues
- The stacktraces are in an unpredictable order - see the screenshot, I have it as "newest first", yet `main.dart` is listed before `about_screen.dart`, and the rest is just a mess
- Tags contain "Flutter" with question mark icon, and empty tag with "Version unknown"
- [The guide in documentation on how to set-up debug symbols for Flutter](https://docs.sentry.io/platforms/flutter/upload-debug/) does not lead users to set-up the debug symbols upload successfully
  - Apparently, the _sentry_dart_plugin_ does not create sourcemaps correctly. Unless you follow steps mentioned [in this comment](https://github.com/flutter/flutter/issues/37875#issuecomment-685858456), the resulting stacktraces [look like this](https://github.com/getsentry/sentry-dart/assets/3010503/fed29a3e-3ba0-441f-9406-de257903c62e).
  - In [the known limitations](https://docs.sentry.io/platforms/flutter/troubleshooting/#known-limitations), documentation is mentioning [the Obfuscate caveat](https://docs.flutter.dev/deployment/obfuscate#caveat), which is irrelevant for web. The code is not obfuscated, it's minified. And Sentry is simply not using source maps correctly. 

There is a lot of information floating around in multiple issues, some are claiming it's Sentry's fault, some it's Flutter's fault. It would be great to consolidate information into a single issue to know what's preventing having support for Flutter on Web in Sentry. If the issue is on the Flutter side, we should clearly state why, so we can track it in this issue and open a well-described issue on Flutter repository.

**Is there a chance to bring attention of the Sentry team to work on making Sentry usable for Flutter Web developers?** Thanks! 🙏

**Comment by kahest** [comment]
Hi @marianhlavac - thanks for your interest and the detailled writeup! We already have an issue for this topic: https://github.com/getsentry/sentry-dart/issues/897
Please feel free to upvote that and leave more information 🙏
