### ISSUE TITLE
Feature Request: Access to Device Information or Context

### ISSUE THREAD

**Issue by bgoncharuck** [getsentry/sentry-dart#1675]
### Problem Statement

There's a valuable Context class in the [contexts.dart file](https://github.com/getsentry/sentry-dart/blob/main/dart/lib/src/protocol/contexts.dart) that contains intriguing device information. 
However, currently, it's not possible to access this information directly from the Sentry instance.

I propose enhancing the package to allow easier access to this device information and, ideally, the entire context. This would streamline the process and potentially eliminate the need for additional plugins such as battery_info_plus or device_info_plus.

Benefits:
- Simplified Integration: Simplifying access to device information through the Sentry instance would make it more intuitive and user-friendly.
- Reduced Dependencies: Reducing the reliance on external plugins like battery_info_plus and device_info_plus could lead to a more streamlined and efficient codebase.

### Solution Brainstorm

Create a method or property within the Sentry instance that exposes device information or the entire context.

### Are you willing to submit a PR?

None

**Comment by krystofwoldrich** [comment]
Hi @bgoncharuck 
Thank you for the message, we will have to discuss this.

I assume you want to read these values in your app and build some Sentry-unrelated logic on top of it? Is that correct? 

If you want to filter events/errors based on the context you can access it for example in the `beforeSend` callback.

**Comment by bgoncharuck** [comment]
"I assume you want to read these values in your app and build some Sentry-unrelated logic on top of it? Is that correct?"

Certainly, I intend to opt for Sentry over other packages primarily to reduce the app's size. The key reason behind this choice is that Sentry already collects the relevant information. Additionally, I have a practice of incorporating multiple logging libraries within a common facade, and having access to this information from Sentry can greatly enhance the effectiveness of my approach.

**Comment by buenaflor** [comment]
@krystofwoldrich do you know if other SDKs have access to this information directly?

**Comment by nosovk** [comment]
It would be nice to have some interface to be on a same line as Sentry plugin.

**Comment by buenaflor** [comment]
It's certainly possible to expose this and currently I'm not against it but I'll check back with the team if this is something we generally want to support. 

@bgoncharuck have you tried accessing this information with `beforeSend`?

**Comment by buenaflor** [comment]
We decided not to support this, however you can always access these information through the `beforeSend` callback:

```dart
FutureOr<SentryEvent?> beforeSend(SentryEvent event, {Hint? hint}) async {
  batteryLevel = event.contexts.device?.batteryLevel;
  brand = event.contexts.device?.brand;
  // ...
  return event;
}

Future<void> main() async {
  await SentryFlutter.init((options) {
      // ...
      options.beforeSend = beforeSend;
    },
    appRunner: () => runApp(const MyApp()),
  );
}
```

**Comment by nosovk** [comment]
Could we upvote it somehow, or just not close? It seems a good way to avoid doubling of functionality. Why we should carry more thaen a one way to handle Device Information gathering to users phone?

**Comment by buenaflor** [comment]
This is a very specific use case and the alternative is to get these values through the `beforeSend` callback, it should contain all the information that you like to use.
