### ISSUE TITLE
Symbolicate native stacktrace in android NDK

### ISSUE THREAD

**Issue by 0xConsumer** [getsentry/sentry-dart#1678]
### Platform

Flutter Mobile

### Obfuscation

Disabled

### Debug Info

Disabled

### Doctor

[✓] Flutter (Channel stable, 3.13.7, on Microsoft Windows [Version 10.0.22000.2538], locale en-US)
    • Flutter version 3.13.7 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2f708eb839 (4 days ago), 2023-10-09 09:58:08 -0500
    • Engine revision a794cf2681
    • Dart version 3.1.3
    • DevTools version 2.25.0

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\Ramin\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop Windows apps (Visual Studio Build Tools 2022 17.7.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools
    • Visual Studio Build Tools 2022 version 17.7.34031.279
    • Windows 10 SDK version 10.0.22000.0

[✓] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[✓] VS Code (version 1.83.1)
    • VS Code at C:\Users\Ramin\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.74.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.2538]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 117.0.5938.149
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 117.0.2045.43

[✓] Network resources
    • All expected network resources are available.

• No issues found!

### Version

7.10.1

### Steps to Reproduce

We're using gomobile to compile a go project. The resulting `aar` file is then put in `android/app/libs` directory and used in the app.
Flutter command to create release apk and aab do not include obfuscation and split debug info, though we still upload source etc. using sentry_dart_plugin.
The problem is that crash reports (involving this native lib) do not include readable stacktrace.
The project is open source, so I'll link relevant parts.
[pubspec.yaml with sentry config](https://github.com/hiddify/hiddify-next/blob/ac55b28d74b7dcd3c2d7926b203e812560d0a04a/pubspec.yaml#L167)
[Makefile command building apk and aab release](https://github.com/hiddify/hiddify-next/blob/ac55b28d74b7dcd3c2d7926b203e812560d0a04a/Makefile#L41)
[GitHub action uploading debug symbols](https://github.com/hiddify/hiddify-next/blob/ac55b28d74b7dcd3c2d7926b203e812560d0a04a/.github/workflows/build.yml#L130)
[Sentry's entrypoint in dart code](https://github.com/hiddify/hiddify-next/blob/ac55b28d74b7dcd3c2d7926b203e812560d0a04a/lib/bootstrap.dart#L52)
[build.gradle](https://github.com/hiddify/hiddify-next/blob/ac55b28d74b7dcd3c2d7926b203e812560d0a04a/android/app/build.gradle)
[Android manifest](https://github.com/hiddify/hiddify-next/blob/ac55b28d74b7dcd3c2d7926b203e812560d0a04a/android/app/src/main/AndroidManifest.xml)
[Go project's Makefile command](https://github.com/hiddify/hiddify-next-core/blob/22483886841c50dc2fea1a240e855f4b85deee87/Makefile#L19)
we have no special setup in android native code for sentry.

### Expected Result

Considering that we're uploading almost all possible information using sentry_dart_plugin, stack trace should be readable.

### Actual Result

![image](https://github.com/getsentry/sentry-dart/assets/132705824/42a396fe-5fe6-48df-beed-a18e65b00bfd)
![image](https://github.com/getsentry/sentry-dart/assets/132705824/7661b06a-0103-4006-907c-2cd9e5f285d0)

another example:
![image](https://github.com/getsentry/sentry-dart/assets/132705824/8252d72e-1cd7-49c7-be9d-94d6d2051e36)
![image](https://github.com/getsentry/sentry-dart/assets/132705824/f944ef79-45dd-4891-9481-b08ba66ba1a3)

### Are you willing to submit a PR?

None

**Comment by 0xConsumer** [comment]
I'm not sure if this is related, but at least in debug mode we get this exception:

```shell
D/Sentry  (18723): Class not available:androidx.compose.ui.node.Owner
D/Sentry  (18723): java.lang.ClassNotFoundException: androidx.compose.ui.node.Owner
D/Sentry  (18723): 	at java.lang.Class.classForName(Native Method)
D/Sentry  (18723): 	at java.lang.Class.forName(Class.java:536)
D/Sentry  (18723): 	at java.lang.Class.forName(Class.java:467)
D/Sentry  (18723): 	at io.sentry.android.core.LoadClass.loadClass(LoadClass.java:21)
D/Sentry  (18723): 	at io.sentry.android.core.LoadClass.isClassAvailable(LoadClass.java:39)
D/Sentry  (18723): 	at io.sentry.android.core.LoadClass.isClassAvailable(LoadClass.java:44)
D/Sentry  (18723): 	at io.sentry.android.core.AndroidOptionsInitializer.initializeIntegrationsAndProcessors(AndroidOptionsInitializer.java:147)
D/Sentry  (18723): 	at io.sentry.android.core.SentryAndroid.lambda$init$1(SentryAndroid.java:127)
D/Sentry  (18723): 	at io.sentry.android.core.SentryAndroid$$ExternalSyntheticLambda0.configure(Unknown Source:8)
D/Sentry  (18723): 	at io.sentry.Sentry.applyOptionsConfiguration(Sentry.java:176)
D/Sentry  (18723): 	at io.sentry.Sentry.init(Sentry.java:146)
D/Sentry  (18723): 	at io.sentry.android.core.SentryAndroid.init(SentryAndroid.java:89)
D/Sentry  (18723): 	at io.sentry.android.core.SentryAndroid.init(SentryAndroid.java:70)
D/Sentry  (18723): 	at io.sentry.flutter.SentryFlutterPlugin.initNativeSdk(SentryFlutterPlugin.kt:126)
D/Sentry  (18723): 	at io.sentry.flutter.SentryFlutterPlugin.onMethodCall(SentryFlutterPlugin.kt:57)
D/Sentry  (18723): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
D/Sentry  (18723): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
D/Sentry  (18723): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
D/Sentry  (18723): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
D/Sentry  (18723): 	at android.os.Handler.handleCallback(Handler.java:942)
D/Sentry  (18723): 	at android.os.Handler.dispatchMessage(Handler.java:99)
D/Sentry  (18723): 	at android.os.Looper.loopOnce(Looper.java:210)
D/Sentry  (18723): 	at android.os.Looper.loop(Looper.java:299)
D/Sentry  (18723): 	at android.app.ActivityThread.main(ActivityThread.java:8116)
D/Sentry  (18723): 	at java.lang.reflect.Method.invoke(Native Method)
D/Sentry  (18723): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
D/Sentry  (18723): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
D/Sentry  (18723): Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.compose.ui.node.Owner" on path: DexPathList[[zip file "/data/app/~~0SIRGukOoQDaEWTPwj9NJA==/app.hiddify.com-Apfsx-ut4csJELnVSp-yDQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~0SIRGukOoQDaEWTPwj9NJA==/app.hiddify.com-Apfsx-ut4csJELnVSp-yDQ==/lib/arm64, /data/app/~~0SIRGukOoQDaEWTPwj9NJA==/app.hiddify.com-Apfsx-ut4csJELnVSp-yDQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
D/Sentry  (18723): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
D/Sentry  (18723): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
D/Sentry  (18723): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
D/Sentry  (18723): 	... 27 more
```

This occurs after host restart or when foreground service is running and the app is manually closed and reopened (in sentry.init). Flutter clean had no effect here, as suggested in #1614.

**Comment by krystofwoldrich** [comment]
Hi,
thank you for the message,
we have not tested the Flutter SDK and Plugin with `gomobile`, so all the necessary debug files might not be picked up automatically.

I've checked the links you sent. It looks like you disable the dwarf files and symbols table on the gomobile compiler.

Does the app work without `-ldflags="-w -s"`? Do you know where the debug files are emitted to?

**Comment by 0xConsumer** [comment]
Sorry about late response. Thanks to your suggestion, I was able to fix this. I thought that removing `-ldflags="-w -s"` would result in a much bigger APK (like in windows), but these debug symbols are separated in AAR and a zip file in `--split-per-abi`.
Also [adding NDK version](https://github.com/hiddify/hiddify-next/blob/eb41c2ff6a9ab8ad73e1de30841cbf10c222799c/android/app/build.gradle#L49) and [debugSymbolLevel 'FULL'](https://github.com/hiddify/hiddify-next/blob/eb41c2ff6a9ab8ad73e1de30841cbf10c222799c/android/app/build.gradle#L105) helped packaging these. This is a [known issue](https://github.com/flutter/flutter/issues/98773).
Now, issues are show like this:

![image](https://github.com/getsentry/sentry-dart/assets/132705824/279f777c-3b3b-48b9-85f4-53ecfa9f4149)
![image](https://github.com/getsentry/sentry-dart/assets/132705824/2e8c1adb-850e-4b85-9ebc-43723f94890c)
