### ISSUE TITLE
Missing Sources Context in Sentry (Flutter web)

### ISSUE THREAD

**Issue by kean-fetchpet** [getsentry/sentry-dart#1686]
### Platform

Dart

### Obfuscation

Disabled

### Debug Info

Disabled

### Doctor

[✓] Flutter (Channel stable, 3.13.6, on macOS 13.3.1 22E261 darwin-arm64, locale en-AU)
    • Flutter version 3.13.6 on channel stable at /Users/keantan/Desktop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ead455963c (3 weeks ago), 2023-09-26 18:28:17 -0700
    • Engine revision a794cf2681
    • Dart version 3.1.3
    • DevTools version 2.25.0

### Version

7.10.1

### Steps to Reproduce

Run flutter packages pub run sentry_dart_plugin in github actions.

### Expected Result

cannot upload source maps to Sentry

### Actual Result

[❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚] 0% reading config values..        
Downloading sentry-cli from https://downloads.sentry-cdn.com/sentry-cli/2.[20](https://github.com/fetchpet/fetch_flutter/actions/runs/6544165519/job/17770088032#step:8:21).6/sentry-cli-Linux-x86_64 to .dart_tool/pub/bin/sentry_dart_plugin/sentry-cli

Downloaded Sentry CLI binary checksum verification passed successfully (hash: 043c1480ede8e8e093070fa705e2723b2b556763e5c10eaa020e3923fad2da20).

Sentry CLI downloaded successfully.

☑ reading config values                                                             

[❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚] 9% validating config values..                             
☑ validating config values                                                             

[❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚] 18% uploading debug symbols..                                
> Found 1 debug information file

> Resolved source code for 0 debug information files

> Prepared debug information file for upload

> Uploaded 1 missing debug information file

> File processing complete:

       OK 02c5f9d4-ea71-cd65-6560-897fe88f5b43 (sentry-cli; x86_64 debug companion)

☑ uploading debug symbols                                                             

Created release web_quote@1.0.0+1

[❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚] [27](https://github.com/fetchpet/fetch_flutter/actions/runs/6544165519/job/17770088032#step:8:28)% uploading source maps..                               
> Found 10 files
> Upload type: artifact bundle

Source Map Upload Report
  Scripts
    ~/lib/controller/controller.dart
    ~/lib/controller/ctm.dart
    ~/lib/controller/pages.dart
    ~/lib/controller/payment_intent.dart
    ~/lib/controller/pds.dart
    ~/lib/controller/plan_receipt.dart
    ~/lib/controller/welcome_to_club.dart
    ~/lib/fetch_web_quote.dart
    ~/lib/firebase_options.dart
    ~/lib/main.dart
    ~/lib/quote_and_buy.dart
    ~/lib/route/route_parser.dart
    ~/lib/route/router_delegate.dart

☑ uploading source maps                                                             

error: unsupported extension name extensions.worktreeconfig; class=Repository (6)

### Are you willing to submit a PR?

None

**Comment by buenaflor** [comment]
Hi, could you provide a minimal reproducible sample project? that would be great

**Comment by timnew** [comment]
It seems something wrong with the rust git library. The issue is exactly the same as described in this ticket: https://github.com/getsentry/sentry-cli/issues/1068

We tried the dart version and also the github action version(https://github.com/getsentry/action-release/tree/v1.4.1/), which I think uses node.js SDK underneath, both have the exactly same problem

**Comment by timnew** [comment]
A few more background context:
1. We cannot reproduce the issue locally, it only occurs on github pipeline. Maybe related to git version on github?
2. We tried to run the action with `SENTRY_LOG_LEVEL` to both `info` and `debug`. None of them are helpful, cause the error doesn't happen in Sentry.
3. We tried both dart version and docker version, which uses node.js SDK, both have the exactly same issue

**Comment by kean-fetchpet** [comment]
@buenaflor Hi we found out that if we use the sentry github action to upload source maps and skip commits, it works. But our logs are still minified. Just wondering if we need to upload all of our dart files to sentry? Currently, we only upload these files as the artifacte bundle. Thanks.

<img width="1030" alt="Screenshot 2023-10-27 at 1 10 35 am" src="https://github.com/getsentry/sentry-dart/assets/116161269/f463ebde-38d5-45b5-a9d6-c8e79ea0a563">

<img width="821" alt="Screenshot 2023-10-27 at 1 14 14 am" src="https://github.com/getsentry/sentry-dart/assets/116161269/2b59ce0d-92b8-4bc6-b2a9-e9a6f6a1c154">


<img width="815" alt="image" src="https://github.com/getsentry/sentry-dart/assets/116161269/a5172e79-db50-46d4-ae30-95f3e72748d8">

**Comment by cristiano2lopes** [comment]
> A few more background context:
> 
> 1. We cannot reproduce the issue locally, it only occurs on github pipeline. Maybe related to git version on github?
> 2. We tried to run the action with `SENTRY_LOG_LEVEL` to both `info` and `debug`. None of them are helpful, cause the error doesn't happen in Sentry.
> 3. We tried both dart version and docker version, which uses node.js SDK, both have the exactly same issue

My team has the same problem. Uploading from GitHub actions and despite matching release (on upload and dynamically), seeing the uploaded artefacts associated to the release still don't see the non minified stack traces and get the error on the events.

![2023-10-27_141934@2x](https://github.com/getsentry/sentry-dart/assets/1236193/bff95241-ce8f-4616-8bcc-8ae33dc9bb3e)

**Comment by kean-fetchpet** [comment]
@cristiano2lopes did you upload your dart code to sentry too? I found out that i need to upload my dart code so that sentry can map from the source maps to the source code. Hope that helps

**Comment by buenaflor** [comment]
@kean-fetchpet could you share your final config that worked for you?

**Comment by cristiano2lopes** [comment]
> @cristiano2lopes did you upload your dart code to sentry too? I found out that i need to upload my dart code so that sentry can map from the source maps to the source code. Hope that helps

This is my config.

    sentry:
        upload_debug_symbols: true
        upload_source_maps: true
        upload_sources: true
        project: "****"
        org: "****"
        wait_for_processing: false
        commits: auto
        ignore_missing: true

**Comment by buenaflor** [comment]
Closing this in favor of #1679 

@kean-fetchpet If you have an update to your config that worked, please feel free to share
