### ISSUE TITLE
COMPILE ERROR 

### ISSUE THREAD

**Issue by miguelangelflores1993** [getsentry/sentry-dart#1703]
### Platform

Flutter Mobile

### Obfuscation

Enabled

### Debug Info

Enabled

### Doctor

[✓] Flutter (Channel stable, 3.13.8, on macOS 14.0 23A344 darwin-arm64, locale es-BO)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.83.1)
[✓] Connected device (4 available)
[✓] Network resources

### Version

7.11.00

### Steps to Reproduce

fvm flutter build apk --flavor=production -t lib/main_production.dart --obfuscate --split-debug-info=build/app/outputs/symbols 

### Expected Result

I should let it compile

### Actual Result

/GeneratedPluginRegistrant.java:89: error: cannot find symbol
      flutterEngine.getPlugins().add(new io.sentry.flutter.SentryFlutterPlugin());
                                                          ^
  symbol:   class SentryFlutterPlugin
  location: package io.sentry.flutter

### Are you willing to submit a PR?

None

**Comment by buenaflor** [comment]
hi!

is this also happening on our SDK version `7.10.1`?

**Comment by alexandrim0** [comment]
Version 7.10.1 compiles well but 7.12.0 do not.

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.9, on Linux Mint 21.2 6.2.0-35-generic, locale ru_RU.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.84.0)
[✓] Connected device (3 available)
[✓] Network resources

**Comment by alexandrim0** [comment]
https://github.com/flutter/flutter/issues/78785
this fixed issue for me

**Comment by buenaflor** [comment]
Could you describe what fix you applied from the thread?

**Comment by alexandrim0** [comment]
> Could you describe what fix you applied from the thread?

`flutter clean` and removing `GeneratedPluginRegistrant.*`

**Comment by buenaflor** [comment]
Thank you! I do wonder why it happens in your case though. Could you prepare a reproducible sample of this?

**Comment by alexandrim0** [comment]
Sorry, but I have no this wrong files and any clue how they generated.

**Comment by buenaflor** [comment]
@alexandrim0 could you also check if this happens in a new project? I tested it on a new project and cannot reproduce this on `7.12.0` unfortunately

**Comment by issakr** [comment]
I get the same error on 7.13.1. I tried flutter clean and manually removing GeneratedPluginRegistrant.*

---
```
Flutter doctor:
[✓] Flutter (Channel stable, 3.13.9, on macOS 14.0 23A344 darwin-arm64, locale en-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.84.2)
[✓] Connected device (3 available)
[✓] Network resources
```

```
java --version
openjdk 17.0.4.1 2022-08-12
OpenJDK Runtime Environment Temurin-17.0.4.1+1 (build 17.0.4.1+1)
OpenJDK 64-Bit Server VM Temurin-17.0.4.1+1 (build 17.0.4.1+1, mixed mode)
```

**Comment by buenaflor** [comment]
@issakr did you manage to fix it or did cleaning and removing the generatedpluginregistrant not work?

**Comment by amebrahimi** [comment]
I have the same problem on 7.13.2. none of the above solutions fixed it
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.16.3, on Microsoft Windows [Version 10.0.22621.2715], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.8.0)
[√] Android Studio (version 2022.3)
[√] VS Code (version 1.85.0)
[√] Connected device (3 available)
[√] Network resources

• No issues found!
```
Gradle: 
```
 compileSdkVersion 34
    ndkVersion "25.1.8937393"

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        applicationId "com.test"
        minSdkVersion 23
        targetSdkVersion 34
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }
```

**Comment by buenaflor** [comment]
Do you have the `sentry_flutter` plugin installed?

**Comment by amebrahimi** [comment]
@buenaflor Yes of course. this is a running project I'm using Sentry in it and after the flutter update and packages update, I encountered this issue. This issue occurred only in the release version. I managed to solve it by deleting Firebase Crashlytics package and it was irrational but it did the trick for now.

**Comment by giantss** [comment]
flutter clean

**Comment by adrianvintu** [comment]
> GeneratedPluginRegistrant

What exactly did you delete, where?
