### ISSUE TITLE
I see my Tags in events created on iOS device and not on events created on Android device

### ISSUE THREAD

**Issue by kobimeridor** [getsentry/sentry-dart#1715]
### Platform

Dart

### Obfuscation

Enabled

### Debug Info

Enabled

### Doctor

[√] Flutter (Channel stable, 3.13.0, on Microsoft Windows [Version 10.0.22621.2428], locale he-IL)
    • Flutter version 3.13.0 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision efbf63d9c6 (3 months ago), 2023-08-15 21:05:06 -0500
    • Engine revision 1ac611c64e
    • Dart version 3.1.0
    • DevTools version 2.25.0

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\merid\AppData\Local\Android\sdk
    • Platform android-TiramisuPrivacySandbox, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio2\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2021.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio2
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)

[√] VS Code (version 1.78.0)
    • VS Code at C:\Users\merid\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.2428]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 118.0.5993.89
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 119.0.2151.44

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
Process finished with exit code 0

### Version

version: "7.12.0"

### Steps to Reproduce

In the Sentry with the following options
```
          (options) {
        options.dsn = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX';
        options.attachThreads = true ;
        options.attachViewHierarchy = true ;
        options.beforeSendTransaction = (SentryTransaction event, {Hint? hint}) {
          event.tags?.addAll({'email': sharedPreferencesUserMail});
          event.tags?.addAll({'Version': "${Versions.VERSION}-"});
          event.tags?.addAll({'DateTime': DateTime.now().toIso8601String()});
          return event;
        };
        options.enableAppLifecycleBreadcrumbs = true;
        options.enableTracing = true;
        options.sendDefaultPii = true;
        options.sampleRate = 1.0;
        options.sdk;
        options.tracesSampleRate = 1.0;
        options.appHangTimeoutInterval = Duration(seconds: int.parse(SystemConfig.initOptions.substring(27, 28)));
        options.enableAppHangTracking = (SystemConfig.initOptions.substring(28, 29) == 'Y');
        options.beforeSend = (SentryEvent event, {Hint? hint}) {
          event.tags?.addAll({'email': sharedPreferencesUserMail});
          event.tags?.addAll({'Version': "${Versions.VERSION}-"});
          event.tags?.addAll({'DateTime': DateTime.now().toIso8601String()});
          return event;
        };
      },
```
Create an exception that will reported to Sentry.io on iOS and Android devices

### Expected Result

The Tags associated with the Event will contains my tags that defined in the `options.beforeSend` like email

### Actual Result

I found my Tags only on events created on iOS device and not on Android device

### Are you willing to submit a PR?

None

**Comment by buenaflor** [comment]
Thank you for the issue! We'll take a look

**Comment by buenaflor** [comment]
I have identified the problem: this happens because the tags are initialized as null and if the tags haven't been set before (for example with `Sentry.configureScope`) they will remain null. Adding values to a null map doesn't work. 

We're working on a fix.

**Comment by buenaflor** [comment]
@kobimeridor 

is there the possibility to achieve what you are doing through?

```dart
  Sentry.configureScope((scope) {
    scope.setTag('tag', 'value');
    // ...
  });
```

That way you don't need the `beforeSend`

**Comment by kobimeridor** [comment]
Thanks,
Can I Add this before `init` like 

```
  Sentry.configureScope((scope) {
    scope.setTag('email', sharedPreferencesUserMail);
    scope.setTag('Version', "${Versions.VERSION}-");
    scope.setTag('DateTime', DateTime.now().toIso8601String());
  });
  await SentryFlutter.init(
          (options) {

```

**Comment by buenaflor** [comment]
You should do it after your init then it works as intended

**Comment by kobimeridor** [comment]
Thanks its working OK
