### ISSUE TITLE
Sentry Performance page is empty

### ISSUE THREAD

**Issue by AhmedEzio47** [getsentry/sentry-dart#1725]
### Platform

Flutter Mobile

### Obfuscation

Enabled

### Debug Info

Enabled

### Doctor

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0) 
    • Android SDK at C:\Users\Ahmed\AppData\Local\Android\Sdk                    
    • Platform android-34, build-tools 34.0.0                                    
    • ANDROID_HOME = C:\Users\Ahmed\AppData\Local\Android\Sdk                    
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java       
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.                                             
                                                                                 
[√] Chrome - develop for the web                                                 
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[√] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 14 (API 34) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.19045.3570]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 119.0.6045.124
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 119.0.2151.58

[√] Network resources
    • All expected network resources are available.

### Version

7.10.1

### Steps to Reproduce

Hi, I'm trying to set up the Sentry performance, so I've gone through the [performance documentation](https://docs.sentry.io/platforms/flutter/performance/?original_referrer=https%3A%2F%2Fwww.google.com%2F), and as far as I understood, all the features are enabled by default, including, for example, App Start Instrumentation, Slow and Frozen Frames, all I need to do is to set the sample rate like this options.tracesSampleRate = 1.0; and add SentryNavigationObserver to the list of observers. Am I missing something? Because the performance page is empty for me. Thanks.

### Expected Result

See some data on the performance page on my Sentry dashboard.

### Actual Result

The performance page is empty.

### Are you willing to submit a PR?

No

**Comment by buenaflor** [comment]
Hi, it could be that it would be dropped because the transaction has no span. You could try out creating some spans manually and go from there.

**Comment by buenaflor** [comment]
Also please see my comment [here](https://github.com/getsentry/sentry-dart/issues/1728#issuecomment-1814644821)

**Comment by buenaflor** [comment]
Feel free to comment if this still an issue
