### ISSUE TITLE
Flutter Web With Obfuscate, Sentry Performance (No Transaction) 

### ISSUE THREAD

**Issue by hendra61298** [getsentry/sentry-dart#1728]
### Platform

Dart

### Obfuscation

Enabled

### Debug Info

Disabled

### Doctor

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.10.6, on Microsoft Windows [Version 10.0.22621.2428], locale en-ID)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Professional 2022 17.6.5)
[√] Android Studio (version 2021.2)
[√] IntelliJ IDEA Ultimate Edition (version 2023.1)
[√] VS Code (version 1.82.2)
[√] Connected device (3 available)
[√] Network resources

### Version

7.12.0

### Steps to Reproduce

1. implement sentry_dio: ^7.12.0. 
2. Setup for auto instrument  
  ```
  
dio.addSentry();
  
 SentryNavigatorObserver(
            setRouteNameAsTransaction: true,
          ),
```

### Expected Result

1. There is transaction in performance tab

### Actual Result

1. There is no transaction 

### Are you willing to submit a PR?

None

**Comment by buenaflor** [comment]
See [docs](https://docs.sentry.io/platforms/dart/integrations/dio/): 
> The Dio integration starts a span out of the active span bound to the scope

that means if there is no active span Sentry will discard it.

minimal example:

```dart
// getSpan() retrieves the active span on the scope which might be created by an auto instrumentation
final transaction = Sentry.getSpan() ??
    Sentry.startTransaction(
      'dio-web-request',
      'request',
      bindToScope: true,
    );
Response<String>? response;
try {
  response = await dio.get<String>('https://jsonplaceholder.typicode.com/posts');
} catch (exception, stackTrace) {
  await Sentry.captureException(exception, stackTrace: stackTrace);
}
await transaction.finish();
```

This isn't extra clear in the docs so that should definitely be improved.

Also I do notice that our navigation observer doesn't properly function with dialogs, that's something to investigate

**Comment by hendra61298** [comment]
so that means, flutter web cannot use auto instrument right?
This code works in flutter mobile without obfuscate

**Comment by buenaflor** [comment]
@hendra61298 Sorry that's my bad, this example doesn't work for web because of CORS issues so it will fail the request, catch it and discard the transaction because there's no spans.

I updated the link to `https://jsonplaceholder.typicode.com/posts` which allows CORS.

**Comment by hendra61298** [comment]
oke thankyou sir

**Comment by buenaflor** [comment]
@hendra61298 Did it work for you?

**Comment by buenaflor** [comment]
Feel free to comment if this is still an issue.
