### ISSUE TITLE
Can not remove event context in EventProcessor

### ISSUE THREAD

**Issue by kuhnroyal** [getsentry/sentry-dart#1732]
### Platform

Flutter Mobile

### Obfuscation

Disabled

### Debug Info

Disabled

### Doctor

[✓] Flutter (Channel stable, 3.13.9, on macOS 14.1 23B74 darwin-arm64, locale de-DE)
    • Flutter version 3.13.9 on channel stable at /Users/user/fvm/versions/3.13.9@stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d211f42860 (vor 3 Wochen), 2023-10-25 13:42:25 -0700
    • Engine revision 0545f8705d
    • Dart version 3.1.5
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/user/Library/Android/sdk
    • Platform android-34, build-tools 33.0.2
    • ANDROID_HOME = /Users/user/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/user/Library/Android/sdk
    • Java binary at: /Users/userApplications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.14.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Users/user/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.5)
    • IntelliJ at /Users/user/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 76.3.4
    • Dart plugin version 232.10072.19

[✓] Connected device (4 available)
    • Pixel 6 Pro (mobile)                          • 19081FDEE002BY            • android-arm64  • Android 14 (API 34)
    • iPhone 14 Pro Max (mobile) 			• 00008120-000915393EE0201E • ios            • iOS 17.0.3 21A360
    • macOS (desktop)                               • macos                     • darwin-arm64   • macOS 14.1 23B74 darwin-arm64
    • Chrome (web)                                  • chrome                    • web-javascript • Google Chrome 119.0.6045.123

[✓] Network resources
    • All expected network resources are available.

• No issues found!

### Version

7.13.1

### Steps to Reproduce

```dart
class SentryRemoveStateProcessor implements EventProcessor {
  const SentryRemoveStateProcessor();

  @override
  Future<SentryEvent?> apply(SentryEvent event, {Hint? hint}) async {
    return event.copyWith(
      contexts: event.contexts..remove(stateKey),
    );
  }
}
```

### Expected Result

The context with the `stateKey` is not sent to Sentry.

### Actual Result

The context with the `stateKey` is sent to Sentry. Probably due to native scope sync.
Related https://github.com/getsentry/sentry-dart/issues/1658

### Are you willing to submit a PR?

None

**Comment by buenaflor** [comment]
Thx for the issue, I'll investigate this

**Comment by buenaflor** [comment]
Hi, any reason why you're not using `beforeSend` ? That way you'd guarantee that it would run after all other event processors have been run.

**Comment by buenaflor** [comment]
@kuhnroyal any updates here?

**Comment by kuhnroyal** [comment]
Hey, sorry, missed the notification.
Thanks, yes this works in the `beforeSend` callback, that is fine for me.
But I still find it odd that the processors changes are somehow ignored.

Feel free to close if that is expected behavior.

**Comment by buenaflor** [comment]
Where did you set the event processor, in the options or the scope?

**Comment by kuhnroyal** [comment]
In the options
