### ISSUE TITLE
Stacktraces are useless when set automatically with obfuscation

### ISSUE THREAD

**Issue by stefanosiano** [getsentry/sentry-dart#1745]
### Description

The stacktrace generated automatically using `Stacktrace.current` does not contain any in-app frames, except for the case when it's called with the `await` keyword. However, when the app is obfuscated, the stacktrace has literally no in-app frames, regardless of `await`.
Here there is an example [without deobfuscation](https://stefanosiano-test.sentry.io/issues/4635928329/?project=4506201251053569&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=24h&stream_index=0) which works fine (as long as the Sentry API is called using `await`, otherwise it doesn't even contain that last line).
Here is an example [with obfuscation](https://stefanosiano-test.sentry.io/issues/4635966487/?project=4506201251053569&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=24h&stream_index=0) for the same function

**Comment by buenaflor** [comment]
Do you have an idea why this happens regarding with/without obfuscation?

**Comment by stefanosiano** [comment]
I tried again multiple times, cleaning the app and creating completely new issues. 
Stacktraces are working fine in obfuscated builds, too (with `await`).
Maybe it was a problem of issues grouping, as I was using the same message (and stacktrace) for different tries, like with/without obfuscation, captureMessage and captureEvent, etc
We can close this issue
