### ISSUE TITLE
After integrating sentry, the white screen takes too long to start the app, with a delay of about 3 seconds.

### ISSUE THREAD

**Issue by xntop** [getsentry/sentry-dart#1750]
### Platform

Dart

### Obfuscation

Disabled

### Debug Info

Disabled

### Doctor

[!] Flutter (Channel unknown, 3.7.0, on macOS 14.0 23A344 darwin-x64, locale
    zh-Hans-CN)
    ! Flutter version 3.7.0 on channel unknown at /Users/anker/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an
      official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions
      at https://flutter.dev/docs/get-started/install.
    ! Unknown upstream repository.
      Reinstall Flutter by following instructions at
      https://flutter.dev/docs/get-started/install.
    • Framework revision b06b8b2710 (10 months ago), 2023-01-23 16:55:55 -0800
    • Engine revision b24591ed32
    • Dart version 2.19.0
    • DevTools version 2.20.1
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/anker/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.84.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.76.0

### Version

7.9.0

### Steps to Reproduce

```
Future<void> setupSentry(AppRunner appRunner, String dsn,
    {bool isIntegrationTest = false,
    BeforeSendCallback? beforeSendCallback}) async {
  await SentryFlutter.init((options) {
    options.dsn = dsn;
    options.tracesSampleRate = 1.0;
    options.addInAppInclude('charging');
    options.considerInAppFramesByDefault = false;
    options.attachThreads = true;
    options.attachStacktrace = true;

    // We can enable Sentry debug logging during development. This is likely
    // going to log too much for your app, but can be useful when figuring out
    // configuration issues, e.g. finding out why your events are not uploaded.
    options.debug = true;
    options.maxRequestBodySize = MaxRequestBodySize.always;
    options.maxResponseBodySize = MaxResponseBodySize.always;

    options.environment = serverEnv.toString();
  },
      // Init your App.
      appRunner: appRunner);
}

```
### Expected Result

After integrating sentry, the app starts without a white screen.

### Actual Result

After integrating sentry, the white screen takes too long to start the app, with a delay of about 3 seconds.

### Are you willing to submit a PR?

No

**Comment by buenaflor** [comment]
Hi, are you able to try out the latest `7.13.2` and see if this problem persists?

Also which platforms are affected by this?

**Comment by xntop** [comment]
> Hi, are you able to try out the latest `7.13.2` and see if this problem persists?
> 
> Also which platforms are affected by this?

After upgrading to the latest version 7.13.2, it was found that it was a device problem.
