### ISSUE TITLE
maxCacheItems not respected for offline usage on Android

### ISSUE THREAD

**Issue by hgadalrab** [getsentry/sentry-dart#1753]
### Platform

Flutter Mobile

### Obfuscation

Disabled

### Debug Info

Enabled

### Doctor

[✓] Flutter (Channel stable, 3.13.9, on macOS 14.0 23A344 darwin-arm64, locale
    en-AT)
    • Flutter version 3.13.9 on channel stable at /Users/user1/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d211f42860 (4 weeks ago), 2023-10-25 13:42:25 -0700
    • Engine revision 0545f8705d
    • Dart version 3.1.5
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/hgadalrab/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.14.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 14 (API 34) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 14.0 23A344 darwin-arm64
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 119.0.6045.159

[✓] Network resources
    • All expected network resources are available.

• No issues found!

### Version

7.13.2

### Steps to Reproduce

1. to be used offline

Future<void> start() async {
  await SentryFlutter.init(
    (options) {
      options
        ..dsn = dsn
        ..addIntegration(LoggingIntegration(minEventLevel: Level.FINE));
    },
  );
  Timer.periodic(const Duration(seconds: 3), (timer) {
    _logger.fine('new message at ${DateTime.now()}');
  });
}

### Expected Result

maximum outbox files/events are 30 (default maxCacheItems)

### Actual Result

no limit is applied

### Are you willing to submit a PR?

None

**Comment by buenaflor** [comment]
Hi!

How did you test this?
Does it only happen on Android?

**Comment by hgadalrab** [comment]
I only tested it on Android. I will try to test the same behaviour on iOS.

To test it, I ran the code mentioned in the "Steps to Reproduce" in the main method. I tested this on an android emulator, and checked the app's cache folder under /data/user/0/com.package.name/cache/sentry/outbox/

**Comment by hgadalrab** [comment]
I just tried it on iOS and the default limit is respected.

I tried it also on a real android device, but the issue is still reproducible.

**Comment by buenaflor** [comment]
@denrase do you know if this is fixed in v8?

**Comment by denrase** [comment]
@buenaflor I don't know of a specific fix for this or any other issue in 8.0 that might positively impact this. I can try to reproduce this on the v8 branch.

**Comment by stefanosiano** [comment]
just check if this issue still occurs in v8. The way it should work in v8 is it enriches the envelopes itself, and rely on Android just for sending them, while now it saves the envelopes to disk (without checks on maxCacheItems) and rely on Android to enrich them and send them

**Comment by denrase** [comment]
@stefanosiano Just checked. We are not doing anything with `options.maxCacheItems` within the Flutter SDK, except passing it down to native. On V8 Android the envelopes are calling the native API directly, and we are not just writing to disk anymore. Logs also indicate that errors/attachments were dropped when trying to reproduce the issue reported by @hgadalrab. So this issue should be resolved in once V8 is released.

```
D/Sentry  ( 8620): 	"discarded_events": [
D/Sentry  ( 8620): 		{
D/Sentry  ( 8620): 			"reason": "cache_overflow",
D/Sentry  ( 8620): 			"category": "error",
D/Sentry  ( 8620): 			"quantity": 4
D/Sentry  ( 8620): 		},
...
```

**Comment by buenaflor** [comment]
This will be fixed in v8
