### ISSUE TITLE
Only send debug images referenced in the stacktrace for events

### ISSUE THREAD

**Issue by buenaflor** [getsentry/sentry-dart#1755]
### Description

Ref: https://github.com/getsentry/team-mobile/issues/158

```[tasklist]
### Blocked by
- [x] Sentry Cocoa `8.39.0`
```

**Comment by buenaflor** [comment]
Can be implemented for cocoa debug images similar to how [react native](https://github.com/getsentry/sentry-react-native/blob/59a53cbd0983e4bc111169feedd7c8d7d19df9b6/ios/RNSentry.mm#L263) does it which requires the instruction addresses to be passed to the cocoa flutter plugin. Relevant code part for Flutter is [here](https://github.com/getsentry/sentry-dart/blob/24b6e601e2c8a3bc70ac06d1d0293067d3df5351/flutter/ios/Classes/SentryFlutterPluginApple.swift#L250)

**Comment by philipphofmann** [comment]
@buenaflor replace `getDebugImagesForAddresses` with either `SentryDebugImageProvider.getDebugImagesFromCacheForFrames` or `SentryDebugImageProvider.getDebugImagesFromCacheForThreads` added in https://github.com/getsentry/sentry-cocoa/pull/4435, which will ship with Cocoa 8.39.0. `getDebugImagesForAddresses` is slow and caused AppHangs on iOS; see https://github.com/getsentry/sentry-cocoa/issues/4399.

**Comment by kahest** [comment]
this is unblocked now, 8.39.0 is out  https://github.com/getsentry/sentry-cocoa/releases/tag/8.39.0
