### ISSUE TITLE
Sentry logs not printted inside console [IOS]

### ISSUE THREAD

**Issue by saharvx9** [getsentry/sentry-dart#1757]
### Platform IOS only

Dart

### Obfuscation

Enabled

### Debug Info

Enabled

### Doctor

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] IntelliJ IDEA Community Edition (version 2021.3.2)
[✓] VS Code (version 1.84.2)
[✓] Connected device (4 available)
[✓] Network resources

### Version

7.12.1

### Steps to Reproduce

```
    await SentryFlutter.init(
      (options) {
        options..dsn = envConfig.sentryDsn
        ..tracesSampleRate = envConfig.sentryTracesSampleRate
        ..environment = appConfig.appFlavor.name
        ..dist = "name"
        ..debug = true;
      },
      appRunner: appRunner,
    );
```

When i am reporting 
`sentryConfig.report(error, stackTrace)`
Its not print to console inside the ide

### Expected Result

Printed into console

### Actual Result

Nothing printed

### Are you willing to submit a PR?

None

**Comment by buenaflor** [comment]
Hi!

could you show what `sentryConfig.report(error, stackTrace)` contains?

Is that a function that calls `Sentry.captureException`?

**Comment by buenaflor** [comment]
However, I can confirm though that it doesn't work.

Our Flutter logger works fine but we also rely on the native SDKs to log more information.
On Android it works where the native SDK prints logs but not the native iOS SDK.

@saharvx9 I have found [this relevant post](https://stackoverflow.com/questions/66564659/native-ios-logs-not-showing-in-flutter-project). You could try running the app in Xcode as it seems to be a Flutter limitation.

**Comment by buenaflor** [comment]
@krystofwoldrich have you ever encountered something similar in react-native?

**Comment by buenaflor** [comment]
Any updates here? @saharvx9

**Comment by buenaflor** [comment]
I'm closing this, feel free to comment if you still have questions
