### ISSUE TITLE
Hide misleading source context errors from Dart/Flutter SDK for Flutter Web

### ISSUE THREAD

**Issue by buenaflor** [getsentry/sentry-dart#1764]
### Description

source context is automatically enabled on Flutter web when using the `sentry_dart_plugin`.

When correctly using the plugin it will upload sourcemaps and sources which leads to the source code of the own app displayed inbetween minified third party package code.

![image](https://github.com/getsentry/sentry-dart/assets/23364143/efb13424-3b2e-4478-81cb-ffc2d8114f95)

However, the issue will still show misleading `missing_source_context` errors which are irrelevant because they refer to sources not from inApp but the flutter/dart sdk.

![image](https://github.com/getsentry/sentry-dart/assets/23364143/32b0e3a0-78fe-45c8-a619-c39fb59a630d)

**Comment by buenaflor** [comment]
@lforst do you have a suggestion on how to approach this - do we just conditionally hide it if they're not relevant? Also feel free to tag someone else who knows better

**Comment by lforst** [comment]
@loewenheim I feel like symbolicator should not be emitting the error here. Looks like everything got mapped correctly. I'd assume flutter web uses inline-source maps.

**Comment by buenaflor** [comment]
@lforst release builds generate a sourcemap that we also upload 

example:



![Image](https://github.com/getsentry/sentry-dart/assets/23364143/f391ca6e-9f99-40d5-8b85-17779ced7810)

**Comment by lforst** [comment]
Just saw that the source maps references always point to main.dart.js.map. Generally speaking all js files need to have their own .map files. This looks off.

**Comment by buenaflor** [comment]
Hm, this is the only sourcemap generated by flutter, what do you think about disabling the error messages manually for now until we can investigate this more? It's pretty bad for the ux currently

**Comment by lforst** [comment]
If the error messages are not actionable, not informative or even wrong we should hide them for sure!

**Comment by buenaflor** [comment]
Closing - this issue is now fixed, these errors do not appear anymore

**Comment by momrak** [comment]
I am getting these in my Flutter web app. Should this issue be reopened, or is it caused by something else?
![CleanShot 2024-03-07 at 12 56 02](https://github.com/getsentry/sentry-dart/assets/6552049/3c59656e-fb03-480b-8beb-cbfbf288a3ae)

**Comment by buenaflor** [comment]
@momrak thx for the report, I'll try to repo but it looks like we should also ignore these in the event page

**Comment by momrak** [comment]
Is it possible to upload these source maps to get better error messages here, or is this related to https://github.com/getsentry/sentry-dart/issues/2805 and can first be fixed once that is done?

**Comment by thomasmechessa891** [comment]
I also uploaded my source map for flutter web, made sure release and dist match but I keep seeing the `Missing Source Context` error. Any resolutions for this?

I have tried uploading the source maps both manually and using the dart sentry plugin. Both methods do upload the source map into the project on sentry, I have verified that,

![Image](https://github.com/user-attachments/assets/f46ec52c-13d0-4adb-b36e-cf470bfed9a7)

**Comment by loewenheim** [comment]
Hi @thomasmechessa891 , do you have a link to an example I can look at?

**Comment by thomasmechessa891** [comment]
> Hi [@thomasmechessa891](https://github.com/thomasmechessa891) , do you have a link to an example I can look at?

I can create another empty flutter project and share a link. Would that work for you?

**Comment by loewenheim** [comment]
Sure, that would work!
