### ISSUE TITLE
Malware TROJ_GEN.R002V01JK23 detected

### ISSUE THREAD

**Issue by FlawLessx** [getsentry/sentry-dart#1770]
### Platform

Dart

### Obfuscation

Enabled

### Debug Info

Enabled

### Doctor

[!] Flutter (Channel stable, 3.10.5, on macOS 13.2.1 22D68 darwin-x64, locale en-ID)
    • Flutter version 3.10.5 on channel stable at /Users/flawlessx/fvm/versions/3.10.5
    ! Warning: `flutter` on your path resolves to /Users/flawlessx/fvm/versions/3.10.3/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/flawlessx/fvm/versions/3.10.5. Consider adding /Users/flawlessx/fvm/versions/3.10.5/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /usr/local/Cellar/dart/3.0.3/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/flawlessx/fvm/versions/3.10.5. Consider adding /Users/flawlessx/fvm/versions/3.10.5/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (6 months ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/flawlessx/Library/Android/sdk
    • Platform android-34, build-tools 33.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.84.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.76.0

[✓] Connected device (1 available)
    • macOS (desktop) • macos • darwin-x64 • macOS 13.2.1 22D68 darwin-x64

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.

### Version

7.13.2

### Steps to Reproduce

1. Use flutter counter app
2. Use sentry package
3. Build release mode
4. Upload to virus total

### Expected Result

No malware detected

### Actual Result

My app got rejected from play store due to malware detected causing my account banned. When i checked it with virus total it is return TROJ_GEN.R002V01JK23 from TrendMicro-HouseCall i know this is a false postive, but still play store or app store won't accept this. The root cause is from libsentry-android.so. You can check more detail [here](https://www.virustotal.com/gui/file/7b144524b45017ffff0e54fb68d9cb2e92c71948b2ab944e15c2f5bfab5c8774/relations)

This is the result without sentry [here](https://www.virustotal.com/gui/file/94e61773b78526656af7f8a9322f27be2ba2b92cbbf35f2021d87da3f5889a11?nocache=1)

### Are you willing to submit a PR?

None

**Comment by buenaflor** [comment]
Hi, have you had successful releases on the playstore with the Sentry SDK before?

But yes, this is a false positive.

**Comment by FlawLessx** [comment]
@buenaflor yes i do had successful releases on the playstore with older version

**Comment by buenaflor** [comment]
@FlawLessx which version was the last one you used for a successful release?

**Comment by FlawLessx** [comment]
@buenaflor version 7.8.0

**Comment by buenaflor** [comment]
fyi virustotal.com also flags `libsqlite3.so`

**Comment by kahest** [comment]
@FlawLessx did you receive any more information from Play Store? Something you can share with us via email? If so, please send to karl.struggl@sentry.io

**Comment by FlawLessx** [comment]
@buenaflor my app also used sqflite but don't know why the .so file not get scanned. @kahest email sent maybe check your spam folder, i'm also appealing this as false positive to google reviewer, i'll update when there is a reply

**Comment by kahest** [comment]
@FlawLessx your app is now down to 0/60 detections per the virustotal.com link you provided, and we didn't receive any other reports about this. I hope everything resolves for you with Play Store and thank you for reporting this.
