### ISSUE TITLE
Disable Error Screenshot per Screen

### ISSUE THREAD

**Issue by GustavoFigueira** [getsentry/sentry-dart#1774]
### Problem Statement

Hi,

Is it possible to **disable screenshot** on **specific screens/widgets**?
I didn't find anything about this in the documentation.

This requirement is important in scenarios where **sensitive information** is captured and saved in an screenshot, something that should not happen in sensitive apps such as banks, for example.

Is there a workaround for this? Without disabling screenshots in the entire app?

### Solution Brainstorm

My suggestion would be to have another widget where the children below it would not be captured or would be blurred, or something like that. 

Something like the Smartlook SDK for Flutter does:
```
SentryTrackingWidget({
    required this.child,
    this.isSensitive = true
  });
```

### Are you willing to submit a PR?

Yes

**Comment by buenaflor** [comment]
Hi!

We have this tracked [here](https://github.com/getsentry/sentry-dart/issues/1540) and is in our backlog

The idea is to add a `beforeCapture` callback where you can either accept or drop the screenshot right before it is sent to Sentry

**Comment by GustavoFigueira** [comment]
Oh, nice! Thanks, closing the PR now.
