### ISSUE TITLE
How should I use Sentry sentry _dio

### ISSUE THREAD

**Issue by lcm1475** [getsentry/sentry-dart#1776]
### Problem Statement

I cannot view the detailed information of network errors on the console. How can I set up to view the specific return information and reasons for network request errors? Below is my code and console situation. How can I modify the code to see the detailed information of network errors on the console

      transaction = Sentry.startTransaction(
          'dio-web-request',
          'request',
          bindToScope: true,
          description: body.toString()
        );
        try{
          response = await _dio.post(
            replacedUri.toString(),
            data: body,
            options: Options(
              contentType: contentType,
              headers: headers,
              responseType: responseType,
            ),
          );
          transaction.status = SpanStatus.fromHttpStatusCode(response.statusCode ?? -1);

        }catch(exception, stackTrace){
          response = Response(requestOptions: RequestOptions(path: ''));
          transaction.setData("request_data_error", body);
          transaction.setData("request_data_error1", jsonEncode(body));
          transaction.throwable = exception;
          transaction.status = SpanStatus.internalError();
          await Sentry.captureException(exception, stackTrace: stackTrace);
          showCenterToast("网络开小差了 请稍后再试~");
        }finally{

          await transaction.finish();
        }

<img width="910" alt="image" src="https://github.com/getsentry/sentry-dart/assets/9637601/c7246e3f-2414-4f1b-b9c5-154037527264">

### Are you willing to submit a PR?

None

**Comment by buenaflor** [comment]
Hi!

We have a `debug` option you can set to true in `SentryFlutter.init` if you want to log more information in general. See [here](https://docs.sentry.io/platforms/flutter/configuration/options/#debug).

e.g
```dart
await SentryFlutter.init(
  (options) => options
    // other options
    ..debug = true,
  appRunner: () => runApp(MyApp()),
```

**Comment by ueman** [comment]
You're trying to record a transaction but the screenshot shows the breadcrumbs.

Breadcrumbs for dio are automatically added when you init dio like this:
```dart
  final dio = Dio();
  /// This *must* be the last initialization step of the Dio setup, otherwise
  /// your configuration of Dio might overwrite the Sentry configuration.
  dio.addSentry(/* configure sentry_dio with the available options to your liking */);
```

**Comment by lcm1475** [comment]
I have already set this up, and I hope to see the detailed information of the error in the console when there is an error in the network request

**Comment by buenaflor** [comment]
@lcm1475 for clarification, the `console` you are referring to is the [breadcrumb](https://docs.sentry.io/product/issues/issue-details/breadcrumbs/) view? or are you referring to the IDE console?
