### ISSUE TITLE
Support configuring the enableCaptureFailedRequests integration in Flutter SDK

### ISSUE THREAD

**Issue by btrautmann** [getsentry/sentry-dart#1777]
### Problem Statement

Similar to the `enableAppHangTracking` integration (which we experienced false positives on, see https://github.com/getsentry/sentry-cocoa/issues/2803), we'd like to be able to _disable_ the `enableCaptureFailedRequests` integration that was turned on by default with iOS SDK 8.0.0. Since 99% of our requests are made in dart, we are generally not concerned with native HTTPClient errors (as most of that code is legacy code, and 5xx errors are not something particularly actionable by our front-end team). We already have hooks into monitoring these errors on the backend.

### Solution Brainstorm

I don't imagine this requires much brainstorming 😃 I would expect there to be a way to configure this similar to the app hanging API.

### Are you willing to submit a PR?

No

**Comment by buenaflor** [comment]
Hi,

we have the option `options.captureFailedRequests` which you can set to `false`. Does it not disable on Cocoa? in that case it would be a bug.

**Comment by btrautmann** [comment]
Oh man, I missed that because I expected the same naming convention as the app hanging integration. Sorry about that. I'll re-open/file new if it doesn't work, but the API does indeed exist. Thank you!
