### ISSUE TITLE
Disabling Sentry Trace and baggage headers to prevent CORS from third party sites

### ISSUE THREAD

**Issue by gd08xxx** [getsentry/sentry-dart#1778]
### Platform

Flutter Web

### Obfuscation

Enabled

### Debug Info

Disabled

### Doctor

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.2, on macOS 14.1.2 23B2091 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.5)
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!

### Version

7.13.2

### Steps to Reproduce

I cannot disable Sentry trace and baggage headers for an http request that goes to a third party website in a functional level.

If I use the following options with SentryHttpClient().send, the sentry-trace header will be created
```
    options
      ..dsn = dsn
      ..debug = instance.debug
      ..environment = instance.environment.name
      ..sampleRate = 0.25
      ..tracesSampleRate = 0.25
      ..attachScreenshot = true
      //Currently in beta, 21/9/23
      ..attachViewHierarchy = true
      **..enableTracing = true
      ..captureFailedRequests = true**
      ..maxRequestBodySize = MaxRequestBodySize.always;
```
If I use the following options with SentryHttpClient().send, the sentry-trace header will **not be** created
```
    options
      ..dsn = dsn
      ..debug = instance.debug
      ..environment = instance.environment.name
      ..sampleRate = 0.25
      ..tracesSampleRate = 0.25
      ..attachScreenshot = true
      //Currently in beta, 21/9/23
      ..attachViewHierarchy = true
      **..enableTracing = false
      ..captureFailedRequests = false**
      ..maxRequestBodySize = MaxRequestBodySize.always;
```
This works, however I cannot disable the headers in a functional level

### Expected Result

I can disable the headers in a functional level

### Actual Result

I cannot find any options in the SentryHttpClient that allows me to do this.
I saw that it takes a hub parameter, however hub.option is internal use only.

### Are you willing to submit a PR?

None

**Comment by buenaflor** [comment]
Hi!

If I understand your use case correctly, then you should be able to adjust the `options.tracePropagationTargets` which is set to `['.*']` by default. If the request (e.g. your third party website) does not match the regex set inside then tracing headers will not be appended.
