### ISSUE TITLE
Errors event has DROPPED

### ISSUE THREAD

**Issue by glj0209** [getsentry/sentry-dart#1794]
### Platform

Dart

### Obfuscation

Enabled

### Debug Info

Enabled

### Doctor

[!] Flutter (Channel [user-branch], 3.13.10-0.0.pre.1, on macOS 13.0 22A380 darwin-x64, locale
    zh-Hans-CN)
    ! Flutter version 3.13.10-0.0.pre.1 on channel [user-branch] at /Users/gaolijun/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at
      https://flutter.dev/docs/get-started/install.
    ! Upstream repository git@codeup.aliyun.com:xxx/app/flutter.git is not a
      standard remote.
      Set environment variable "FLUTTER_GIT_URL" to
      git@codeup.aliyun.com:xxx/app/flutter.git to dismiss this error.
    • Framework revision f07d5d1357 (1 year, 5 months ago), 2022-07-26 14:22:22 +0800
    • Engine revision 0545f8705d
    • Dart version 3.1.5
    • DevTools version 2.25.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to
      use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/gaolijun/Library/Android/sdk
    • Platform android-34, build-tools 32.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 31.3.2
    • Dart plugin version 182.3569.4

[✓] VS Code (version 1.84.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.0 22A380 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 120.0.6099.109

[!] Network resources
    ✗ A network error occurred while checking "https://maven.google.com/": Operation timed out

### Version

7.8.0

### Steps to Reproduce

All error times have been dropped since December 20, and we cannot collect any error times.

<img width="1194" alt="WechatIMG17260" src="https://github.com/getsentry/sentry-dart/assets/8816552/af0f9e47-da69-4f19-bd48-8c205c52d4fc">

### Expected Result

Capture all error messages so we can track the problem easily.

### Actual Result

We don't see any error events.
<img width="1190" alt="WechatIMG17261" src="https://github.com/getsentry/sentry-dart/assets/8816552/21504a8c-266b-47c1-aed7-5f2b0cbe5552">

### Are you willing to submit a PR?

None

**Comment by buenaflor** [comment]
Hi, are events also dropped when you test them locally as well?

**Comment by glj0209** [comment]
> Hi, are events also dropped when you test them locally as well?

Yes,  events also dropped when test in locally.
ex. 
`Sentry.captureException({"ds":"ddd"});`

**Comment by buenaflor** [comment]
@glj0209 for clarification, are you by chance located in China?

**Comment by glj0209** [comment]
> @glj0209 for clarification, are you by chance located in China?

Yes, but our service is not subscription, it's hosting.

**Comment by buenaflor** [comment]
Do you know if other SDKs are affected by this or are you only using the Flutter SDK?

**Comment by glj0209** [comment]
> Do you know if other SDKs are affected by this or are you only using the Flutter SDK?

This is our only using.
`sentry_flutter: 7.8.0
  sentry_dio: 7.8.0`
