### ISSUE TITLE
Error in play store

### ISSUE THREAD

**Issue by JoseDRojasA** [getsentry/sentry-dart#1798]
### Platform

Dart

### Obfuscation

Enabled

### Debug Info

Enabled

### Doctor

[✓] Flutter (Channel stable, 3.16.5, on macOS 14.2.1 23C71 darwin-arm64, locale en-CO)
    • Flutter version 3.16.5 on channel stable at /opt/homebrew/Caskroom/flutter/3.16.0/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 78666c8dc5 (8 days ago), 2023-12-19 16:14:14 -0800
    • Engine revision 3f3e560236
    • Dart version 3.2.3
    • DevTools version 2.28.4

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/joserojas/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C65
    • CocoaPods version 1.14.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.85.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.80.0

[✓] Connected device (4 available)
    • sdk gphone64 arm64 (mobile)   • emulator-5554             • android-arm64  • Android 14 (API 34) (emulator)
    • iPhone de Jose david (mobile) • 00008120-001E70821463C01E • ios            • iOS 17.1.2 21B101
    • macOS (desktop)               • macos                     • darwin-arm64   • macOS 14.2.1 23C71 darwin-arm64
    • Chrome (web)                  • chrome                    • web-javascript • Google Chrome 120.0.6099.129

[✓] Network resources
    • All expected network resources are available.

• No issues found!

### Version

7.14.0

### Steps to Reproduce

Add Sentry to main class like this:

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  await configureNotifications();

  MobileAds.instance.initialize();
  await SentryFlutter.init(
    (options) {
      options.dsn = globalConfiguration.sentryDns;
      options.tracesSampleRate = 1.0;
    },
    appRunner: () => runApp(const MyApp()),
  );
}

When you run the app in local, It works as expected but when you upload the app to play store. It shows this error:

<img width="1148" alt="Screenshot 2023-12-27 at 2 43 32 PM" src="https://github.com/getsentry/sentry-dart/assets/25036583/8778d3bc-d9f2-4e17-8fba-df7b1e7e6e5e">

### Expected Result

Don't show the error when I upload to the play store

### Actual Result

This is what I get from the play store
<img width="1148" alt="Screenshot 2023-12-27 at 2 43 32 PM" src="https://github.com/getsentry/sentry-dart/assets/25036583/a2d4859a-3028-4c46-a999-bbb3563ca39e">

I removed Sentry from my build and It disappears so I'm sure It's related with Sentry

### Are you willing to submit a PR?

None

**Comment by buenaflor** [comment]
Hi, did you use Sentry before. was this a problem in previous versions as well?

**Comment by JoseDRojasA** [comment]
@buenaflor No sir, this is the first time I use sentry with flutter

**Comment by buenaflor** [comment]
What are your dependencies? It could be that one of them conflicts with our Sentry SDK, have you tried removing others?

**Comment by JoseDRojasA** [comment]
These are my current dependencies

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  csv: ^5.1.1
  json_annotation: ^4.8.1
  flutter_bloc: ^8.1.3
  adaptive_breakpoints: ^0.1.6
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.2.2
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  permission_handler: ^11.1.0
  fluttertoast: ^8.2.4
  go_router: ^12.1.1
  json_serializable: ^6.7.1
  universal_io: ^2.2.2
  photo_view: ^0.14.0
  showcaseview: ^2.0.3
  share_plus: ^7.2.1
  awesome_notifications: ^0.8.2
  intl: ^0.18.1
  firebase_core: ^2.24.2
  firebase_analytics: ^10.7.4
  google_mobile_ads: ^4.0.0
  app_tracking_transparency: ^2.0.4
  in_app_purchase: ^3.1.11
  google_sign_in: ^6.2.1
  sign_in_button: ^3.2.0
  flutter_secure_storage: ^9.0.0
  dio: ^5.4.0
  sign_in_with_apple: ^5.0.0
  jwt_decoder: ^2.0.1

**Comment by buenaflor** [comment]
@markushi do you know what might cause this? sounds odd that it works locally but not on the play store

**Comment by buenaflor** [comment]
@JoseDRojasA Did you also test it in release mode locally?

**Comment by JoseDRojasA** [comment]
@buenaflor yes sir, It works too. The only place where I see that issue is when I upload the version to the play store

**Comment by buenaflor** [comment]
What's the command you use to build your apk?

**Comment by buenaflor** [comment]
Hey this seems to be a common problem with flutter, can you check out this work around and see if it works for you?

https://github.com/flutter/flutter/issues/83596#issuecomment-1257209669

**Comment by buenaflor** [comment]
Dup of https://github.com/getsentry/sentry-dart/issues/1823
