### ISSUE TITLE
Docs pointers to platforms/dart

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dart#180]
We currently only have docs and wizard for Flutter.

Once we add dart: https://docs.sentry.io/platforms/dart/ we need to change:

Link to the docs on the footer: https://github.com/getsentry/sentry-dart/blob/main/dart/README.md#L63
pubspec homepage URL: https://github.com/getsentry/sentry-dart/blob/main/dart/pubspec.yaml#L6 to the docs.

**Comment by marandaneto** [comment]
true, should be done by #102 btw, will get it done next few days
