### ISSUE TITLE
Privacy permissions

### ISSUE THREAD

**Issue by CatEatFishs** [getsentry/sentry-dart#1808]
### Problem Statement

Becase of Chinese government policy. The application is not allowed to obtain any information of the phone, until the user agrees to your privacy policy. I have to manual init after user click 'Agree User Privacy Policy'.

### Solution Brainstorm

Add a option like bool manualInit in SentryFlutterOptions
Add a methed like manualInit() in Sentry class
i see this method 【You can init the SDKs manually using this config https://docs.sentry.io/platforms/flutter/native-init/】，but is difficult for me，What should I do？

### Are you willing to submit a PR?

None

**Comment by buenaflor** [comment]
Hi, can you not move `SentryFlutter.init` to after the user clicks the privacy policy?

**Comment by buenaflor** [comment]
Another alternative: you can also use [beforeSend](https://docs.sentry.io/platforms/dart/configuration/filtering/#using-platformidentifier-namebefore-send-) to not send events if the privacy has not been clicked yet.

```dart
FutureOr<SentryEvent?> beforeSend(SentryEvent event, {Hint? hint}) async {
  if (privacyAgreeHasBeenClicked) {
    return event;
  }
  return null;
}

Future<void> main() async {
  await Sentry.init((options) => options.beforeSend = beforeSend);
}
```

**Comment by CatEatFishs** [comment]
> Another alternative: you can also use [beforeSend](https://docs.sentry.io/platforms/dart/configuration/filtering/#using-platformidentifier-namebefore-send-) to not send events if the privacy has not been clicked yet.
> 
> ```dart
> FutureOr<SentryEvent?> beforeSend(SentryEvent event, {Hint? hint}) async {
>   if (privacyAgreeHasBeenClicked) {
>     return event;
>   }
>   return null;
> }
> 
> Future<void> main() async {
>   await Sentry.init((options) => options.beforeSend = beforeSend);
> }
> ```

thanks，I'll try it

**Comment by buenaflor** [comment]
@CatEatFishs any update?
