### ISSUE TITLE
Need to Remove ndk - abiFilters from the defaultConfig(build.gradle). 

### ISSUE THREAD

**Issue by DhavalRKansara** [getsentry/sentry-dart#1823]
### Description

Hi Team, We are using the sentry package in one of my projects, where I have submitted the application on the Play Store and am facing the below error under the stability section. 

> java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/system/framework/android.test.mock.jar", zip file "/data/app/androidx.test.tools.crawler-w5t15CaOamFGCJdQ6Qbx2Q==/base.apk", zip file "/data/app/xyz.timelesswallet.aa-_NjvaAs7bukIYKQ0ZeEcmw==/base.apk", zip file "/data/app/xyz.timelesswallet.aa-_NjvaAs7bukIYKQ0ZeEcmw==/split_config.pl.apk", zip file "/data/app/xyz.timelesswallet.aa-_NjvaAs7bukIYKQ0ZeEcmw==/split_config.x86.apk", zip file "/data/app/xyz.timelesswallet.aa-_NjvaAs7bukIYKQ0ZeEcmw==/split_config.xxhdpi.apk"],nativeLibraryDirectories=[/data/app/androidx.test.tools.crawler-w5t15CaOamFGCJdQ6Qbx2Q==/lib/x86, /data/app/xyz.timelesswallet.aa-_NjvaAs7bukIYKQ0ZeEcmw==/lib/x86, /data/app/androidx.test.tools.crawler-w5t15CaOamFGCJdQ6Qbx2Q==/base.apk!/lib/x86, /data/app/xyz.timelesswallet.aa-_NjvaAs7bukIYKQ0ZeEcmw==/base.apk!/lib/x86, /data/app/xyz.timelesswallet.aa-_NjvaAs7bukIYKQ0ZeEcmw==/split_config.pl.apk!/lib/x86, /data/app/xyz.timelesswallet.aa-_NjvaAs7bukIYKQ0ZeEcmw==/split_config.x86.apk!/lib/x86, /data/app/xyz.timelesswallet.aa-_NjvaAs7bukIYKQ0ZeEcmw==/split_config.xxhdpi.apk!/lib/x86, /system/lib]]] couldn't find "libflutter.so"

When I checked for the same issue with Flutter, I found there might be a chance it's happening because of the abiFilters setup in build.gradle. Also, while checking the comments in the issues, I found one of the comments: https://github.com/flutter/flutter/issues/83596#issuecomment-1455829874 which says if one of the dependencies applied the filter, there is a chance this error might come.

It will be really helpful if you guys can look into this on the priority.

**Comment by buenaflor** [comment]
Hey it seems like there is a work around mentioned in the thread: https://github.com/flutter/flutter/issues/83596#issuecomment-1257209669

Have you tried that yet?

**Comment by DhavalRKansara** [comment]
@buenaflor but as mentioned in the https://github.com/flutter/flutter/issues/83596#issuecomment-1455829874, `If you run flutter build appbundle and then unzip generated app-release.aab file. You will notice that it contains the following folders: base/lib/arm64-v8a, armeabi-v7a, x86, x86_64.` So I guess we should remove the abiFilters from here as well if it's not making any issues now.

**Comment by buenaflor** [comment]
I'll look into it more and get back to you very soon
https://docs.flutter.dev/deployment/android#what-are-the-supported-target-architectures

**Comment by buenaflor** [comment]
x86 still doesn't generate a `libflutter.so`, not sure if removing the abifilters will solve this

<img width="258" alt="image" src="https://github.com/getsentry/sentry-dart/assets/23364143/a7705ab3-4ec4-44ff-843a-06cb407a8dc9">

**Comment by denrase** [comment]
So I tried creating an app bundle in our Flutter example app.

`Build -> Flutter -> Build App Bundle`

The example app has the same `abiFilters` as the `defaultConfig` of Sentry Flutter.

```gradle
ndk {
    // Flutter does not currently support building for x86 Android (See Issue 9253).
    abiFilters("armeabi-v7a", "x86_64", "arm64-v8a")
}
```

As expected this would only produce folders "armeabi-v7a", "x86_64", "arm64-v8a", all of which contain `libflutter.so`

<img width="231" alt="Bildschirmfoto 2024-01-29 um 15 33 39" src="https://github.com/getsentry/sentry-dart/assets/3984453/b7e90cb8-cba9-4b9d-8359-235cc832b90a">

When removing `abiFilter`, there's also the "x86" folder, but without `libflutter.so`.

<img width="246" alt="Bildschirmfoto 2024-01-29 um 15 35 24" src="https://github.com/getsentry/sentry-dart/assets/3984453/9cd39120-b01d-449b-b55b-fe1d236a6b59">

How would removing the filters resolve the issue where `libflutter.so` is missing on `x86` devices?

**Comment by denrase** [comment]
Also, the `abiFilter` has to be present in the applications `build.gradle`. The `x86` folder with missing `libflutter.so` will still be created when there is no `abiFilter` in the app, regardless of what sentry has defined in its `defaultConfig`.

<img width="2551" alt="Bildschirmfoto 2024-01-29 um 16 08 02" src="https://github.com/getsentry/sentry-dart/assets/3984453/9f3ed25b-8344-49cf-9b10-40e925a31cba">

**Comment by denrase** [comment]
Also tried creating an empty sample app with only sentry as dependency and removing the `abiFilter` from sentry. The `x86` folder is still created.

<img width="235" alt="Bildschirmfoto 2024-01-29 um 16 33 35" src="https://github.com/getsentry/sentry-dart/assets/3984453/de807e94-d1b2-45cb-b2bd-89bde12e954c">

So it seems users need to define `abiFilters` on the application level in oder to not have the `x86` folder included in the app bundle.

**Comment by denrase** [comment]
- [x] Check behaviour with most recent flutter version.

**Comment by buenaflor** [comment]
As @denrase said, the best advice we can give here is to apply these abi filters on your application directly as well. I'll add it to our troubleshooting sentry-docs. After he checked if this problem remains for other flutter versions as well we will close this issue.

- [ ] Add to sentry-docs troubleshooting

**Comment by denrase** [comment]
@buenaflor The behaviour is the same with the most recent Flutter version (3.16.9).
