### ISSUE TITLE
[sentry] Support for HTTP breadcrumbs

### ISSUE THREAD

**Issue by ueman** [getsentry/sentry-dart#183]
I would like to request support for HTTP breadcrumbs for Sentry-Dart.

A possible solution could look like this:
```dart
import 'package:http/http.dart' as http;
import 'package:http/http.dart';
import 'package:sentry/sentry.dart';

class SentryHttpClient extends http.BaseClient {
  SentryHttpClient(this._inner);

  final http.Client _inner;

  @override
  Future<StreamedResponse> send(BaseRequest request) async {
    final response = await _inner.send(request);
    Sentry.addBreadcrumbs(
      Breadcrumb(
        message: null,
        type: 'http',
        data: {
          'url': request.url.toString(),
          'method': request.method,
          'status_code': response.statusCode.toString(),
          'reason': response.reasonPhrase,
        },
      ),
    );
    return response;
  }
}

```

**Comment by marandaneto** [comment]
@ueman thanks for this.

what's more common in the Dart/Flutter world, the `http` package or https://api.dart.dev/dev/2.12.0-51.0.dev/dart-io/HttpClient-class.html ?

**Comment by ueman** [comment]
[DIO](https://pub.dev/packages/dio) is another really popular library, just to make your list of HTTP clients complete. I think it uses the [http](https://pub.dev/packages/http) package under the hood.
But I'm not really sure what the most popular solution is.

However as Sentry already depends on the http package this would be a nice addition to the package.

**Comment by ueman** [comment]
This is now possible due to #226
