### ISSUE TITLE
Add textScale(r) value to Flutter context

### ISSUE THREAD

**Issue by kuhnroyal** [getsentry/sentry-dart#1832]
### Problem Statement

Text scale changes currently only lead to breadcrumbs but especially with screenshots it would be helpful to see the current "global" text scale in Sentry.

In Flutter the text scale can be different for different widgets but in most cases, the system provided scale is enough.

### Solution Brainstorm

I would suggest something like `MediaQuery.maybeTextScalerOf(context)?.toString()` to be added to the context.
The output would be:

```dart
  @override
  String toString() => textScaleFactor == 1.0 ? 'no scaling' : 'linear (${textScaleFactor}x)';
```

This feature requires a context/widget so I would suggest to let the screenshot widget handle this.

### Are you willing to submit a PR?

None

**Comment by buenaflor** [comment]
hey,

hm it would seem odd to me to add this to the screenshot integration. we have added a `navigatorKey` option [here](https://github.com/getsentry/sentry-dart/pull/1724) to grab context so we could potentially use that

**Comment by kuhnroyal** [comment]
Hmm, not sure. That would probably work but the navigator key in general looks like the wrong path.
It would be better to use a custom widget tbh.

```dart
MaterialApp(
	builder: (context, child) {
		return SomeSentryHelperWidget(
			child: child,
		);
	},
)
```

That would work anywhere in flutter even if you don't use `MaterialApp` or `Navigator`.

**Comment by buenaflor** [comment]
I guess one con of this is that it is very 'invasive' (lack of better word) for such small use case.

@denrase didn't we talk about creating one widget that includes the features of the other widgets such as `SentryScreenshotWidget`, `SentryUserInteractionWidget` etc... so we don't have to nest so many of them? is that possible?

**Comment by denrase** [comment]
@buenaflor Yeah, I remember that the Idea was to create a `SentryWidget` which brings all others under one umbrella.
