### ISSUE TITLE
Mask sensitive fields while screenshot capturing 

### ISSUE THREAD

**Issue by mohamedzakaria974** [getsentry/sentry-dart#1834]
### Problem Statement

In mobile application development, there exists a critical privacy concern related to the inadvertent capture of sensitive information through screenshots. When users take screenshots, especially in apps that handle confidential data, such as personal information or passwords, there is a risk of exposing this sensitive content. This poses a significant security threat, as it may lead to unauthorized access or compromise of sensitive information.

### Solution Brainstorm

ScreenshotMask Widget:
- The ScreenshotMask widget would be designed to overlay sensitive fields in the Flutter app.
- It should be easily integrated into existing widgets, allowing developers to wrap sensitive fields with the ScreenshotMask widget.

### Are you willing to submit a PR?

None

**Comment by buenaflor** [comment]
Hey, we've recently merged a PR that allows you to filter the screenshots: https://github.com/getsentry/sentry-dart/pull/1805 (not released yet)

that means that based on some criteria you can decide to upload the screenshot or not. it is not as granular as your suggested method though

**Comment by mohamedzakaria974** [comment]
already check the opened/closed tickets and I saw this as well as checking the PR code this is to send screenshot or not.
what if the requirement to attach a screenshot but masking any sensitive data such a user password or any payment info?

**Comment by buenaflor** [comment]
We need to develop this feature anyway to mask/redact sensitive elements for our session replay feature in #1193

**Comment by buenaflor** [comment]
Duplicate: closing this in favour of https://github.com/getsentry/sentry-dart/issues/1956
