### ISSUE TITLE
Release and User ID does not appear anymore

### ISSUE THREAD

**Issue by carpentierchloe** [getsentry/sentry-dart#1858]
### Platform

Dart

### Obfuscation

Disabled

### Debug Info

Disabled

### Doctor

[✓] Flutter (Channel stable, 3.16.9, on macOS 14.2.1 23C71 darwin-arm64, locale fr-FR)
    • Flutter version 3.16.9 on channel stable at /Users/chloecarpentier/Documents/Outils/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 41456452f2 (11 days ago), 2024-01-25 10:06:23 -0800
    • Engine revision f40e976bed
    • Dart version 3.2.6
    • DevTools version 2.28.5

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/chloecarpentier/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.15.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

### Version

7.16.0

### Steps to Reproduce

Future main() async {

await Sentry.init((options) {
        options.dsn = 'https://xxxxxxxxxx';
        options.tracesSampleRate = 1.0;
      });

runApp...

 await Sentry.configureScope((scope) => scope.setUser(SentryUser(id: firebaseUser.uid, email: firebaseUser.email)));

### Expected Result

Show all informations with release and user id as it was working before

<img width="846" alt="Capture d’écran 2024-02-05 à 10 51 18" src="https://github.com/getsentry/sentry-dart/assets/61030036/a89a5011-ab17-403f-811e-096c43456b4a">

### Actual Result

No informations

<img width="892" alt="Capture d’écran 2024-02-05 à 10 48 28" src="https://github.com/getsentry/sentry-dart/assets/61030036/3cc86a45-bc78-4216-a3d4-dc5acd9bdf61">

### Are you willing to submit a PR?

None

**Comment by buenaflor** [comment]
Does `7.15.0` work as usual?

**Comment by buenaflor** [comment]
I am also seeing this `Sentry.init` what's the reason you're not using `SentryFlutter.init` ?

**Comment by carpentierchloe** [comment]
Thanks a lot, it is working with SentryFlutter !
