### ISSUE TITLE
`drift` integration should not impose a `flutter` dependency

### ISSUE THREAD

**Issue by prefanatic** [getsentry/sentry-dart#1865]
### Problem Statement

As a developer, I'd like to be able to use Sentry's Drift integration on a Dart backend, without having Flutter implicitly pulled in as a dependency.

### Solution Brainstorm

This might be as simple as not including Flutter bits in `pubspec.yaml` but I haven't tested this theory. 

### Are you willing to submit a PR?

Yes

**Comment by buenaflor** [comment]
hey, thanks for the issue, you're 100% correct, apologies for that oversight, it should be fine to just remove the dep from pubspec.yaml

**Comment by buenaflor** [comment]
the fix is now part of [7.16.1](https://github.com/getsentry/sentry-dart/releases/tag/7.16.1)
