### ISSUE TITLE
App freeze on iOS with "arithmetic overflow" error in sentry swift

### ISSUE THREAD

**Issue by zvikarp** [getsentry/sentry-dart#1872]
### Platform

Dart

### Obfuscation

Disabled

### Debug Info

Disabled

### Doctor

[✓] Flutter (Channel stable, 3.16.2, on macOS 14.2.1 23C71 darwin-arm64, locale
    en-IL)
    • Flutter version 3.16.2 on channel stable at
      /Users/zvikarp/.asdf/installs/flutter/3.16.2-stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9e1c857886 (10 weeks ago), 2023-11-30 11:51:18 -0600
    • Engine revision cf7a9d0800
    • Dart version 3.2.2
    • DevTools version 2.28.3

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/zvikarp/Library/Android/sdk
    • Platform android-34, build-tools 32.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.15.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.83.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.82.0

[✓] VS Code (version 1.86.0-insider)
    • VS Code at /Applications/Visual Studio Code - Insiders.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
  *******

[✓] Network resources
    • All expected network resources are available.

• No issues found!

### Version

7.14.0

### Steps to Reproduce

I'm not sure, this issue started happening recently, it is hard for me to understand why it is happening, sometimes it works and sometimes I get an error in xcode:

![recording_2024-02-07_9 -29-18](https://github.com/getsentry/sentry-dart/assets/13397207/05d3f90f-59c5-4732-9739-5019220c7b67)

To get to this error I run the app and at some stage it just freezes, hot reload stops working and the error above appears in xcode. seems like that the result of the selected line is negative but we are using unit here and this is the cause of the error.

### Expected Result

Not to freeze

### Actual Result

App freezes

### Are you willing to submit a PR?

None

**Comment by buenaflor** [comment]
Hi, do you know if you can reproduce that consistently?

**Comment by zvikarp** [comment]
No. It often happens in debug mode when navigating from a loading screen to a screen with a lot of data. It happened to me on testflight only the first time I installed it from it. On testflight the app just crashes.

**Comment by denrase** [comment]
Looked into this, avoiding this error should be a simple thing, but it does not solve the underlying issue. Judging from a debug session, it looks like begin/end is not called symmetrically when using sentry navigator observer. I will further investigate and see if i can fix the root issue.

<img width="324" alt="Bildschirmfoto 2024-02-12 um 11 25 00" src="https://github.com/getsentry/sentry-dart/assets/3984453/360e575a-f811-496a-89b2-a3e5f29ef972">

/cc @buenaflor

**Comment by zvikarp** [comment]
Thank you @denrase I really appreciate it 🙏

**Comment by buenaflor** [comment]
the fix is included in `7.16.1`
