### ISSUE TITLE
Add a dedupe integration

### ISSUE THREAD

**Issue by rodolfoBee** [getsentry/sentry-dart#1892]
### Problem Statement

Some of Sentry SDKs have a dedupe integration which prevents the SDK from sending multiple instances of the same exception.
JS: https://docs.sentry.io/platforms/javascript/configuration/integrations/dedupe/
Python: https://docs.sentry.io/platforms/python/integrations/default-integrations/#deduplication

### Solution Brainstorm

Create the same integration for flutter to not send duplicated events.

### Are you willing to submit a PR?

None

**Comment by ueman** [comment]
This is already implemented in the Dart SDK: https://github.com/getsentry/sentry-dart/blob/main/dart/lib/src/event_processor/deduplication_event_processor.dart

**Comment by buenaflor** [comment]
@rodolfoBee did the flutter dedup not work for you?
