### ISSUE TITLE
Can't compile example_web - sentry_io dependency leaked back somehow?

### ISSUE THREAD

**Issue by daniel-v** [getsentry/sentry-dart#1893]
### Platform

Dart Web

### Obfuscation

Disabled

### Debug Info

Disabled

### Doctor

<details><summary>Dart version</summary>
<p>

```
Dart SDK version: 3.3.0 (stable) (Tue Feb 13 10:25:19 2024 +0000) on "linux_x64"
```

</p>
</details> 

### Version

7.16.1

### Steps to Reproduce

```
git clone https://github.com/getsentry/sentry-dart
git switch 7.16.1
cd sentry-dart/example_web
dart pub upgrade
dart run build_runner serve web
```

### Expected Result

Example to compile successfully with DDC and serve `main.dart.js` file

### Actual Result

```
[WARNING] build_web_compilers:entrypoint on web/main.dart:
Skipping compiling sentry_dart_web_example|web/main.dart with ddc because some of its
transitive libraries have sdk dependencies that not supported on this platform:

sentry|lib/src/sentry_isolate_extension.dart
sentry|lib/src/sentry_isolate.dart
sentry|lib/src/sentry_attachment/io_sentry_attachment.dart

https://github.com/dart-lang/build/blob/master/docs/faq.md#how-can-i-resolve-skipped-compiling-warnings
```

### Are you willing to submit a PR?

Yes

### Extra info:

This might be related: https://github.com/getsentry/sentry-dart/issues/1369
However, this issue has been fixed by https://github.com/getsentry/sentry-dart/pull/1371/files

So I'm a bit confused as following the dependency chain shows that I should NOT import `_io` version of anything. :confused:

**Comment by daniel-v** [comment]
**Extra info:** I've successfully compiled the `example_web` project in the with version 2.19.6 after updating `pubspec.yaml`. 

It however broke with 3.2.6 (just like with 3.3.0).

Seems to be cause by this line: https://github.com/getsentry/sentry-dart/blob/7.16.1/dart/lib/sentry.dart#L14

**Extra info 2:** `dart2js` alternative `dart compile js` on `main.dart` in example project does the trick, it compiles it. It is as though `dart.library.io` is set falsely by ... something.

**Comment by daniel-v** [comment]
I'm happy to say that I found the cause of the issue. It has luckily nothing to do with how conditional imports work (or don't). It is a case of transitive dependencies that cause the breakage in sentry package (TransportUtils). 

I'll be submitting a PR with the fix in the coming days.

**Comment by daniel-v** [comment]
I was wondering how this issue might have gone unnoticed so I dug into the tests a little bit.

I noticed that the tests are being run with `dart test -p "chrome"` for browsers, which in turn call `dart compile js` or `dart2js` internally. 

An interesting observation is that dart2js allows for `dart:io` or `dart:isolate` imports BUT `build_web_compilers` does not.

This piece of code will compile with `dart compile js` and **WILL THROW** a runtime error.

```dart
import 'dart:io';

void main() {  
  stdout.writeln('Will it work with dart compile js?');  
}
```

This same code will fail to compile with `build_web_compilers` with a _[WARNING]_

```
transitive libraries have sdk dependencies that are not supported on this platform:
```

This results in a situation where projects relying on `package:sentry`, such as the one residing in `example_web`, will fail to compile with the above warning in case of `build_runner` compilation OR will compile and fail at runtime if `dart compile js` is used.

The tests do not currently provide feedback about this situation. 

Am I missing something here?

**Comment by buenaflor** [comment]
hey @daniel-v thanks for the find! looks like I sneaked it in there 😓
