### ISSUE TITLE
Cocoapods repository availability after new release

### ISSUE THREAD

**Issue by SchillingSebastian** [getsentry/sentry-dart#1928]
### Description

Hey there 👋 
we are using an automated CI/CD pipeline to build iOS apps and push them to Testflight. 
We now had several occurrences where we were unable to build an older release and the reason was always the sentry repository. One example for this:
``` Text
CocoaPods could not find compatible versions for pod "Sentry/HybridSDK"
In snapshot (Podfile.lock):
        Sentry/HybridSDK (= 8.20.0)

      In Podfile:
        sentry_flutter (from `.symlinks/plugins/sentry_flutter/ios`) was resolved to 0.0.1, which depends on
          Sentry/HybridSDK (= 8.21.0)


    You have either:
     * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
     * changed the constraints of dependency `Sentry/HybridSDK` inside your development pod `sentry_flutter`.
       You should run `pod update Sentry/HybridSDK` to apply changes you've made.
```
I did find #1515 and #1467 and yes of course we can update the repository and then create a "new" old release, but I think from a development perspective it would be nice to not having to do that. Especially if we want the build to be the exactly the same.
To me it looks like the `sentry_flutter 0.0.1`, which is the same for every sentry version, is updated with every new release and automatically points to the new `Sentry/HybridSDK`. This of course conflicts with the `Podfile.lock`.
Is there a way how we can build older versions? 

Thanks a lot in advance!

**Comment by buenaflor** [comment]
Hey, what we can do is update the version in the podspec to the version of our sdk release instead of keeping it at 0.0.1 which might solve your issue.

We're doing the same on our react native sdk: https://github.com/getsentry/sentry-react-native/blob/main/RNSentry.podspec#L2-L3

**Comment by SchillingSebastian** [comment]
That would be very nice!

**Comment by buenaflor** [comment]
@SchillingSebastian this change is now out with `7.19.0` pls check if it solved your case

**Comment by SardorbekR** [comment]
@SchillingSebastian similar error I'm having now, on CI/CD pod install failing with similar error, although on CI it fresh installs the flutter. I've tried pushing pubspeck.lock and podfile.lock as well because it's working on my local machine. but no luck I'm absolutely fed up of this error
