### ISSUE TITLE
Unknown platform 

### ISSUE THREAD

**Issue by JeffOlajos** [getsentry/sentry-dart#1936]
### Description

Sorry to bug you. How did you end up fixing this issue? I have the same issue with package FML. Any help would be appreciated!!!

**Comment by kahest** [comment]
@JeffOlajos can you provide more information - what issue are you referring to? If you feel this is a bug, please open a [new bug report](https://github.com/getsentry/sentry-dart/issues/new?assignees=&labels=Platform%3A+Dart%2Cbug&projects=&template=BUG_REPORT.yml).
