### ISSUE TITLE
Clear all breadcrumbs, caches

### ISSUE THREAD

**Issue by phuocbitmark** [getsentry/sentry-dart#1937]
### Problem Statement

Hi, I want to delete all breadcrumbs, caches, everything that may contain user data. Is there any way to do it.
I found 
```
SentryAssetBundle().clear(); 
```
but not sure what it would do
Thanks.

### Are you willing to submit a PR?

None

**Comment by kahest** [comment]
@phuocbitmark PII/sensitive data can be in a lot of places, depending on how you use and configure the SDK. A lot of automatic scrubbing is performed already by Sentry on the server side. For more granular control, see the [docs on how to scrub sensitive data](https://docs.sentry.io/platforms/flutter/data-management/sensitive-data/). More information on specific SDK APIs to scrub e.g. breadcrumbs, context etc. can be found in the docs:
- https://docs.sentry.io/platforms/flutter/enriching-events/scopes/#configuring-the-scope
- https://docs.sentry.io/platforms/flutter/enriching-events/identify-user/

Also, `SentryAssetBundle().clear();` is part of our AssetBundle instrumentation and not related to removal of PII or sensitive data.
