### ISSUE TITLE
Revisit pubspecs and general information on pub.dev

### ISSUE THREAD

**Issue by kahest** [getsentry/sentry-dart#1952]
### Platforms

Currently, we don't specify the [supported platforms](https://dart.dev/tools/pub/pubspec#platforms) (only exception is [`sentry-flutter`](https://github.com/getsentry/sentry-dart/blob/29297d43a910bfd6a6932ecb456e70aac411508a/flutter/pubspec.yaml#L35) using the [plugin declarations](https://docs.flutter.dev/packages-and-plugins/developing-packages#plugin-platforms)). Pub.dev has auto-detection but that can be flaky. Consider adding the platforms explicitely in pubspec.

### Licenses

The main package currently uses [BSD](https://pub.dev/packages/sentry/license) while the other packages use [MIT](https://pub.dev/packages/sentry_flutter/license). Is this on purpose/correct?

### More tbd

Verify pub.dev info, especially stuff that's auto-detected, find out if we can/should add explicit info in pubspec.

**Comment by ueman** [comment]
The main package is BSD since it was originally developed by Google as far as I remember.
