### ISSUE TITLE
Sentry plugin cause app crashes in windows with special characters in hostname

### ISSUE THREAD

**Issue by Prathiv7** [getsentry/sentry-dart#1953]
### Platform

Flutter Desktop

### Obfuscation

Enabled

### Debug Info

Enabled

### Doctor

[√] Flutter (Channel stable, 3.16.9, on Microsoft Windows [Version 10.0.22000.2538], locale en-US)
    • Flutter version 3.16.9 on channel stable at C:\dev\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 41456452f2 (9 weeks ago), 2024-01-25 10:06:23 -0800
    • Engine revision f40e976bed
    • Dart version 3.2.6
    • DevTools version 2.28.5
 
[√] Windows Version (Installed version of Windows is version 10 or higher)
 
[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.
 
 
[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe
 
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.8.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.8.34330.188
    • Windows 10 SDK version 10.0.22621.0
 
[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
 
[√] VS Code (version 1.87.2)
    • VS Code at C:\Users\sundar\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.84.0
 
[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.2538]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 123.0.6312.59
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 123.0.2420.53
 
[√] Network resources
    • All expected network resources are available.

### Version

  sentry_flutter: ^7.9.0

### Steps to Reproduce

1. Change device hostname  -> desktop-äöü
2. Launch sentry example app 
3. App crashes when any exceptions occurs

![image](https://github.com/getsentry/sentry-dart/assets/145538094/bfd2fa81-7427-4a82-9a2f-76b9582f238a)
![image (1)](https://github.com/getsentry/sentry-dart/assets/145538094/7eadbbde-cfd8-476f-aea6-315382897ae5)

### Expected Result

Sentry need to log the error 

### Actual Result

App crashes 

### Are you willing to submit a PR?

Yes

**Comment by kahest** [comment]
Hey @Prathiv7 thanks for the report - do you have more information on the crash, like a stack trace or similar? In any case, we'll need to investigate this.

**Comment by denrase** [comment]
So i tried to reproduce this, but with no luck. The example app keeps working and crashes are reported on sentry.io

I guess we can close this @kahest if there isn't any new info? 

![Image](https://github.com/user-attachments/assets/9d643f75-1c45-44b9-86a1-4b43990c5d70)

**Comment by kahest** [comment]
@denrase thanks for looking into that!

@Prathiv7 I'm closing this now. Feel free to comment with more details if the issue persists so we can reopen.
