### ISSUE TITLE
Issues don't fully deofuscate

### ISSUE THREAD

**Issue by feinstein** [getsentry/sentry-dart#1955]
### Platform

Dart

### Obfuscation

Enabled

### Debug Info

Enabled

### Doctor

[✓] Flutter (Channel stable, 3.16.9, on macOS 14.4 23E214 darwin-arm64, locale en-AU)
    • Flutter version 3.16.9 on channel stable at /Users/user/.puro/envs/stable/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 41456452f2 (9 weeks ago), 2024-01-25 10:06:23 -0800
    • Engine revision f40e976bed
    • Dart version 3.2.6
    • DevTools version 2.28.5

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/user/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/user/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] IntelliJ IDEA Community Edition (version 2023.2.5)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 76.3.4
    • Dart plugin version 232.10248

[✓] VS Code (version 1.85.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.80.0

[✓] Connected device (3 available)
    • iPhone 15 Pro (mobile) • E37C05EC-694C-4EDF-928A-4D162D46673E • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-2 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 14.4 23E214 darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 123.0.6312.86

[✓] Network resources
    • All expected network resources are available.

• No issues found!

### Version

7.16.1

### Steps to Reproduce

1. Obfuscate your app and compile it with these flags: 

```console
--obfuscate --split-debug-info=build/app/outputs/symbols \
--extra-gen-snapshot-options=--save-obfuscation-map=build/app/outputs/obfuscation_map.json \
```

3. Upload the symbols
4. Generate an exception
5. Open the Sentry Issues Screen
6. See something like this:

![image](https://github.com/getsentry/sentry-dart/assets/8120472/6b2f329d-8cf4-486e-9107-da746735a518)

### Expected Result

All symbols will be deofuscated, regardless of where they are shown in the Sentry UI.

### Actual Result

I keep seeing weird names like `dw` in many of my Sentry issues. I imagine Sentry is not deofuscating some symbols, or the tool is not uploading them correctly, or it's not finding the folder where my symbols where stored.

### Are you willing to submit a PR?

None

**Comment by stefanosiano** [comment]
This is already tracked by https://github.com/getsentry/sentry-dart/issues/2805
This is a known issue and we have to plan how to fix it, at least for AOT apps.
