### ISSUE TITLE
Provide a way to disable TTID

### ISSUE THREAD

**Issue by wenyue** [getsentry/sentry-dart#1960]
### Problem Statement

TTID is enabled by default, please provide a way to disable it.

### Are you willing to submit a PR?

None

**Comment by buenaflor** [comment]
@wenyue hey! any specific reason you want to disable it?

**Comment by wenyue** [comment]
I only want to use sentry to collect errors, and I don't need the profile feature

**Comment by buenaflor** [comment]
@wenyue if you only need error, you can also disable performance entirely via the `tracesSampleRate` option.

**Comment by wenyue** [comment]
Okey, thanks
