### ISSUE TITLE
Upgrade package_info_plus to 6.X

### ISSUE THREAD

**Issue by bawahakim** [getsentry/sentry-dart#1961]
### Problem Statement

Sentry flutter relies on `package_info_plus` to be lower or equal to 5.0.1. There's been a recent release of 6.0.0, would be great if sentry can support it.

### Are you willing to submit a PR?

No

**Comment by albaschez** [comment]
I am facing the same issue. This is currently blocking my release as other dependencies do need `package_info_plus` being 6.0.0

**Comment by kuhnroyal** [comment]
This has already been fixed on main. Please check for existing issue before creating new ones.
Duplicate of https://github.com/getsentry/sentry-dart/issues/1944
