### ISSUE TITLE
there is a conflict with package_info_plus v6.0.0 and sentry

### ISSUE THREAD

**Issue by mahdiqdi** [getsentry/sentry-dart#1966]
### Description

i can't import both package_info_plus v6.0.0 and sentry v7.18.0
please fix this issue

**Comment by davidpanic** [comment]
[Bruh](https://github.com/getsentry/sentry-dart/pull/1948).

**Comment by mahdiqdi** [comment]
@davidpanic thanks

**Comment by kahest** [comment]
As pointed out, the required change has been merged and will be released soon.
