### ISSUE TITLE
There is no data on page performance App Starts and Screen Loads

### ISSUE THREAD

**Issue by bytebubbles** [getsentry/sentry-dart#1987]
### Platform

Flutter Mobile

### Obfuscation

Enabled

### Debug Info

Enabled

### Doctor

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.3, on macOS 14.4 23E214 darwin-arm64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS and macOS development.
      Download at: https://developer.apple.com/xcode/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] Connected device (3 available)
[✓] Network resources

### Version

7.19.0

### Steps to Reproduce

1. Operate according to document： https://docs.sentry.io/platforms/flutter/integrations/app-start-instrumentation/
2. Try cold starting the app multiple times
3. performance App Starts and Screen Loads page is empty
![AppStarts](https://github.com/getsentry/sentry-dart/assets/33546683/b62ff947-7860-45ef-bd5b-0e99f191d046)
![screenLoads](https://github.com/getsentry/sentry-dart/assets/33546683/bae99685-6732-41be-844b-742cde78dce1)

### Expected Result

performance App Starts and Screen Loads page have data

### Actual Result

performance App Starts and Screen Loads page is empty

### Are you willing to submit a PR?

None

**Comment by buenaflor** [comment]
Hi, the app start module is still very new and is not yet enabled for Flutter. You should see the transaction under the [performance module](https://docs.sentry.io/platforms/flutter/integrations/app-start-instrumentation/#2-locate-your-transaction). 

As for screen loads, this requires using the [routing instrumentation](https://docs.sentry.io/platforms/flutter/integrations/routing-instrumentation/)
