### ISSUE TITLE
Incompatibility between package_info_plus v7.0.0 and sentry v7.19.0

### ISSUE THREAD

**Issue by nikolaybiaivanov** [getsentry/sentry-dart#1993]
### Problem Statement

Can someone take a look and possibly make latest sentry compatible package_info_plus v7.0.0? 
Thanks.

### Are you willing to submit a PR?

None

**Comment by kuhnroyal** [comment]
Duplicate of https://github.com/getsentry/sentry-dart/issues/1974

**Comment by kuhnroyal** [comment]
Maybe someone from the Sentry team can rename the other issue so it is easier to find.

**Comment by buenaflor** [comment]
hey we will do a 7.20.0 release today so this should be out very soon

**Comment by buenaflor** [comment]
Fixed now in `7.20.0`
