### ISSUE TITLE
Support package_info_plus 8.x.x

### ISSUE THREAD

**Issue by scopendo** [getsentry/sentry-dart#2013]
### Platform

Dart

### Obfuscation

Enabled

### Debug Info

Enabled

### Doctor

[✓] Flutter (Channel stable, 3.19.6, on macOS 14.4.1 23E224 darwin-arm64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2024.1)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!

### Version

8.0.0

### Steps to Reproduce

Add sentry_flutter as a dependency to a project with package_info_plus: ^8.0.0

### Expected Result

Dependencies should be compatible

### Actual Result

> Because every version of mat_common from path depends on package_info_plus ^8.0.0 and sentry_flutter >=8.0.0 depends on
  package_info_plus >=1.0.0 <8.0.0, mat_common from path is incompatible with sentry_flutter >=8.0.0.
So, because mat_mobile depends on both sentry_flutter ^8.0.0 and mat_common from path, version solving failed.

### Are you willing to submit a PR?

Yes

**Comment by scopendo** [comment]
PR https://github.com/getsentry/sentry-dart/pull/2010 has already been merged in.  Leaving this issue open to close when there's a new version of sentry_flutter on pub.dev.

**Comment by buenaflor** [comment]
We've got some CI failures that's blocking a release, I'm looking into it

meanwhile you can do

```yaml
dependency_overrides:
  package_info_plus: ^8.0.0
```

**Comment by buenaflor** [comment]
Currently released in `7.20.1`. `8.1.0` will follow

**Comment by buenaflor** [comment]
Now released on both `7.20.1` and `8.1.0`
