### ISSUE TITLE
Using GoRouter with pageBuilder doesn't capture the destination ("to") page in the navigation breadcrumb

### ISSUE THREAD

**Issue by Jonny1987** [getsentry/sentry-dart#2014]
### Platform

Dart

### Obfuscation

Disabled

### Debug Info

Disabled

### Doctor

[✓] Flutter (Channel stable, 3.19.6, on Ubuntu 22.04.4 LTS 6.5.0-26-generic, locale en_US.UTF-8)
    • Flutter version 3.19.6 on channel stable at /home/john/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 54e66469a9 (8 days ago), 2024-04-17 13:08:03 -0700
    • Engine revision c4cd48e186
    • Dart version 3.3.4
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /home/john/Android/Sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /opt/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 14.0.0-1ubuntu1.1
    • cmake version 3.22.1
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2023.1)
    • Android Studio at /opt/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.88.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.86.0

[✓] Connected device (3 available)
    • sdk gphone x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • Linux (desktop)            • linux         • linux-x64      • Ubuntu 22.04.4 LTS 6.5.0-26-generic
    • Chrome (web)               • chrome        • web-javascript • Google Chrome 123.0.6312.86

[✓] Network resources
    • All expected network resources are available.

• No issues found!

### Version

8.0.0

### Steps to Reproduce

1) Create a route for GoRouter which uses a pageBuilder.

eg:
```
GoRoute(
  path: 'venue-details/:venueId',
  name: AppRoute.venueDetails.name,
  pageBuilder: (context, state) {
    final venueId = int.parse(state.pathParameters['venueId']!);
    return MaterialPage(
      key: state.pageKey,
      fullscreenDialog: true,
      child: VenueDetailsPage(
        venueId: venueId,
      ),
    );
  },
),
```

2) Trigger the route navigation

### Expected Result

It should show the navigation breadcrumb with the "to" parameter like so (this is the actual result when changing the route to use pageBuilder instead:
```
{
  from: home,
  from_arguments: {
    venueId: 106
  },
  state: didPush,
  to: venueDetails,
  to_arguments: {
    venueId: 106
  }
}
```

### Actual Result

```
{
  from: home,
  from_arguments: {
    venueId: 106
  },
  state: didPush
}
```

### Are you willing to submit a PR?

None

**Comment by buenaflor** [comment]
Hi has this been an issue with older versions as well?

**Comment by Jonny1987** [comment]
I only have experience with the latest version

**Comment by buenaflor** [comment]
Got it, thanks for the issue, we'll take a look

**Comment by denrase** [comment]
@Jonny1987 I got it to work when providing the `SentryNavigatorObserver` to the Go router instead of the `MaterialApp`. and I also used `context.go("/go")` for navigation.

```dart
final _router = GoRouter(
  routes: [
    GoRoute(
      path: '/',
      builder: (context, state) => const MainScaffold(),
    ),
    GoRoute(
      path: "/go",
      builder: (context, state) => SentryDisplayWidget(child: const AutoCloseScreen())
    )
  ],
  observers: [
    SentryNavigatorObserver()
  ]
);

...

void onPress(BuildContext context) {
  context.go("/go")
}
```

Then the methods of the navigator were called and I could see the breadcrumb.

<img width="1595" alt="Bildschirmfoto 2024-05-06 um 17 32 37" src="https://github.com/getsentry/sentry-dart/assets/3984453/18014b88-8412-411a-811e-030364d7039b">

Could you check if this setup works for you?

**Comment by buenaflor** [comment]
@Jonny1987 we have [docs](https://docs.sentry.io/platforms/flutter/integrations/routing-instrumentation) of usage with go router as well

feel free to comment if there's any other issue

**Comment by vishalbaps** [comment]
Dear @denrase  i have also getting same issue .

specifically when i m using ShellRoute.

its working  fine if  route declare outside of ShellRoute as your above given example.

but not working with ShellRoute

![Image](https://github.com/user-attachments/assets/bfc603bf-530a-4698-b52b-34e63680a410)

![Image](https://github.com/user-attachments/assets/cc94ff88-99e4-48e2-889e-e2c0f3aac3ff)

**Comment by denrase** [comment]
@vishalbaps Thx for the infos! Looking into this rn.

**Comment by denrase** [comment]
We also have to provide a `SentryNavigatorObserver` to the `ShellRoute`. This however cannot be the same instance, or it will crash internally. I tried with separate instances, and got the following result:

<img width="1892" alt="Image" src="https://github.com/user-attachments/assets/8867a786-452a-48d9-b383-1d2d3069e2d7" />

So all routes are recorded, but the route from Login to the Shell has an empty target. You could try to play around with this setup to see if it is good enough. We'd also need to check what implications it has to use two separate instances of `SentryNavigatorObserver`. \cc @buenaflor 

```dart
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'package:sentry_flutter/sentry_flutter.dart';

void main() async {
  await SentryFlutter.init(
        (options) {
      options.dsn = 'YOUR DSN'; // Replace with your Sentry DSN
      options.tracesSampleRate = 1.0;
    },
    appRunner: () => runApp(MyApp()),
  );
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      routerConfig: _router,
    );
  }
}

final GoRouter _router = GoRouter(
  observers: [SentryNavigatorObserver()],
  routes: [
    GoRoute(
      path: '/',
      name: 'Login',
      builder: (context, state) => const LoginScreen(),
    ),
    ShellRoute(
      observers: [SentryNavigatorObserver()],
      builder: (context, state, child) {
        return Scaffold(
          appBar: AppBar(title: Text('Shell Example')),
          bottomNavigationBar: BottomNavigationBar(
            currentIndex: _calculateSelectedIndex(state.location),
            onTap: (index) {
              switch (index) {
                case 0:
                  context.go('/home');
                  break;
                case 1:
                  context.go('/search');
                  break;
              }
            },
            items: const [
              BottomNavigationBarItem(icon: Icon(Icons.home), label: 'Home'),
              BottomNavigationBarItem(icon: Icon(Icons.search), label: 'Search'),
            ],
          ),
          body: child, // Displays the child route's content
        );
      },
      routes: [
        GoRoute(
          path: '/home',
          name: 'Home',
          builder: (context, state) => const HomeScreen(),
        ),
        GoRoute(
          path: '/search',
          name: 'Search',
          builder: (context, state) => const SearchScreen(),
        ),
      ],
    ),

  ],
);

int _calculateSelectedIndex(String location) {
  if (location.startsWith('/home')) {
    return 0;
  }
  if (location.startsWith('/search')) {
    return 1;
  }
  return 0;
}

class HomeScreen extends StatelessWidget {
  const HomeScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Center(
      child: Text('Home Screen'),
    );
  }
}

class SearchScreen extends StatelessWidget {
  const SearchScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Center(
      child: ElevatedButton(
        onPressed: () => Sentry.captureMessage("Error!!!"),
        child: Text('Error!!!'),
      ),
    );
  }
}

class LoginScreen extends StatelessWidget {
  const LoginScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Center(
      child: ElevatedButton(
        onPressed: () => context.go('/home'),
        child: Text('Login'),
      ),
    );
  }
}
```

**Comment by vishalbaps** [comment]
Ok @denrase  Thanks for your valuable time . I will check  this solution.
