### ISSUE TITLE
Update fingerprint via beforeSend callback 

### ISSUE THREAD

**Issue by invipal** [getsentry/sentry-dart#2029]
### Problem Statement

Hello,

First of all thank you for this great service and it's SDKs. 

In the Flutter/Dart SDK, we are unable to update the fingerprint with the beforeSend Callback because the value is defined as final. According to your documentation, this feature is available in the SDKs for other languages (Example: https://docs.sentry.io/platforms/apple/usage/sdk-fingerprinting/). Did you intentionally disable this feature, or was it an oversight?

![sentry](https://github.com/getsentry/sentry-dart/assets/7427108/a405d6b9-bbf4-4746-94d5-0a5672f6d6fb)

### Are you willing to submit a PR?

None

**Comment by ueman** [comment]
You'll have to do it like this

```
return event.copyWith(
  fingerprint: ...
);
```

**Comment by invipal** [comment]
Thank you @ueman, I was so focused on it being final defined that I didn't even think of copyWith.
