### ISSUE TITLE
Codecov action is broken 

### ISSUE THREAD

**Issue by vaind** [getsentry/sentry-dart#2043]
### Description

The latest report is from three months ago: https://app.codecov.io/gh/getsentry/sentry-dart/commits

action fails with `Error: Codecov token not found. Please provide Codecov token with -t flag.`

**Comment by buenaflor** [comment]
ah thanks, we're looking into it

**Comment by buenaflor** [comment]
should be fixed now

**Comment by vaind** [comment]
> should be fixed now

Still/again doesn't work: 
https://github.com/getsentry/sentry-dart/actions/runs/9582784189/job/26422535255#step:8:34

**Comment by buenaflor** [comment]
dang, thx for noticing

**Comment by buenaflor** [comment]
https://github.com/getsentry/sentry-dart/pull/2046 the issue was I only added the fix for the flutter workflow, I need to add it to every other that uses codecov as well

**Comment by vaind** [comment]
I get it
consider merging #2114 first :)
