### ISSUE TITLE
Error when building using sentry_flutter 8.2.0

### ISSUE THREAD

**Issue by Jonny1987** [getsentry/sentry-dart#2078]
### Platform

Dart

### Obfuscation

Disabled

### Debug Info

Disabled

### Doctor

[✓] Flutter (Channel stable, 3.22.0, on Ubuntu 22.04.4 LTS 6.5.0-28-generic, locale en_US.UTF-8)
    • Flutter version 3.22.0 on channel stable at /home/john/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5dcb86f68f (3 weeks ago), 2024-05-09 07:39:20 -0500
    • Engine revision f6344b75dc
    • Dart version 3.4.0
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /home/john/Android/Sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /opt/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 14.0.0-1ubuntu1.1
    • cmake version 3.22.1
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2023.3)
    • Android Studio at /opt/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] VS Code (version 1.88.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.90.0

[✓] Connected device (3 available)
    • Pixel 3a (mobile) • 192.168.1.2:42743 • android-arm64  • Android 12 (API 32)
    • Linux (desktop)   • linux             • linux-x64      • Ubuntu 22.04.4 LTS 6.5.0-28-generic
    • Chrome (web)      • chrome            • web-javascript • Google Chrome 123.0.6312.86

[✓] Network resources
    • All expected network resources are available.

• No issues found!

### Version

8.2.0

### Steps to Reproduce

Build app using `flutter build apk --release lib/main.dart`

### Expected Result

No error

### Actual Result

```
e: file:///home/john/.pub-cache/hosted/pub.dev/sentry_flutter-8.2.0/android/src/main/kotlin/io/sentry/flutter/SentryFlutterPlugin.kt:36:39 Unresolved reference: SentryFlutter
e: file:///home/john/.pub-cache/hosted/pub.dev/sentry_flutter-8.2.0/android/src/main/kotlin/io/sentry/flutter/SentryFlutterPlugin.kt:50:7 Unresolved reference: SentryFlutter

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':sentry_flutter:compileReleaseKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details
```

### Are you willing to submit a PR?

None

**Comment by buenaflor** [comment]
Hi is this still a problem even after cleaning caches?

**Comment by Jonny1987** [comment]
> Hi is this still a problem even after cleaning caches?

Yes it works after clearing the cache by doing the following before building again (I'm not sure if all were necessary):

```
flutter clean
flutter pub cache clean
cd android
./gradlew clean
cd ../
flutter packages get
flutter pub get
```
