### ISSUE TITLE
SentryExceptionFactory.getSentryException

### ISSUE THREAD

**Issue by rabejarano** [getsentry/sentry-dart#2080]
### Platform

Flutter Mobile

### Obfuscation

Enabled

### Debug Info

Enabled

### Doctor

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.6, on macOS 14.1.2 23B92 darwin-arm64,
    locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version
    34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.2)
[✓] VS Code (version 1.89.1)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!

### Version

8.2.0

### Steps to Reproduce

i dont know how reproduce

### Expected Result

I hope that when I have a poor internet connection, Sentry will report the TimeOut error.

### Actual Result

I am receiving a TimeOut error from Sentry, but I am unable to replicate the issue. I have tried forcing the error by using a poor internet connection, no internet at all, and denying permissions, but I still cannot reproduce the error.

From what I understand, Sentry is unable to capture the event. I would like to know if you can help me identify the problem or if the issue lies with Sentry itself.

Please let me know if I am reporting the error incorrectly so that I can make the necessary corrections.

![1](https://github.com/getsentry/sentry-dart/assets/100733565/6602bd82-3267-4510-8d82-f43ba06095e2)
![2](https://github.com/getsentry/sentry-dart/assets/100733565/612edb78-559f-4abc-963e-1033f13bba9d)
![3](https://github.com/getsentry/sentry-dart/assets/100733565/7e241fcc-59cc-4ef9-88d6-8131945da7bd)
![4](https://github.com/getsentry/sentry-dart/assets/100733565/48f8c46b-e05d-4499-8d38-c5a4adc954ee)

### Are you willing to submit a PR?

None

**Comment by buenaflor** [comment]
As far as I can see the stacktrace is a bit misleading this is because we've recently included SDK frames in the stacktrace so we can filter whether the app crashed because of our sdk ( https://github.com/getsentry/sentry-dart/pull/2050) so ideally the stacktrace should not set those frames as `inApp`, we have a PR open for that: https://github.com/getsentry/sentry/pull/71549

**Comment by rabejarano** [comment]
Ok, as I understand you, should I wait for the next release?  Because I have 8.2.0. Thanks for answer

**Comment by buenaflor** [comment]
Not necessarily, as soon as https://github.com/getsentry/sentry/pull/71549 is merged and live we can observe if this issue still remains

**Comment by rabejarano** [comment]
Thank you very much, I'm waiting. This error makes a lot of noise in my metrics.

**Comment by philipphofmann** [comment]
I merged https://github.com/getsentry/sentry/pull/71549 right now. It could take a couple of hours for this to be live and fully deployed. Please reopen if your problem still persists.

**Comment by ueman** [comment]
It seems that https://github.com/getsentry/sentry/pull/71549 is missing a couple packages that should be considered Sentry stack frames here https://github.com/getsentry/sentry/blob/a5e4c3f654cb30d8d6b1752edb2aaf45365103fa/src/sentry/grouping/enhancer/enhancement-configs/newstyle%402023-01-11.txt#L83-L88

In particular, it's missing:
```
sentry_logging
sentry_dio
sentry_file
sentry_hive
sentry_isar
sentry_sqflite
sentry_drift
```

**Comment by philipphofmann** [comment]
Thanks for pointing that out @ueman. I opened a PR https://github.com/getsentry/sentry/pull/72109.

**Comment by philipphofmann** [comment]
Fixed with https://github.com/getsentry/sentry/pull/71549 and https://github.com/getsentry/sentry/pull/72109.
