### ISSUE TITLE
Sentry Upgrade in flutter causing other testcases to fail.

### ISSUE THREAD

**Issue by pvermaDM** [getsentry/sentry-dart#2126]
### Platform

Dart

### Obfuscation

Enabled

### Debug Info

Enabled

### Doctor

flutter doctor -v
[√] Flutter (Channel stable, 3.22.2, on Microsoft Windows [Version 10.0.22631.3737], locale en-IN)
    • Flutter version 3.22.2 on channel stable at C:\flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (3 weeks ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Android\Sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11572160)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2023.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11572160)

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22631.3737]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 126.0.6478.63
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 125.0.2535.92

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

### Version

8.3.0

### Steps to Reproduce

We are updating our sentry dependency from 7.17.0 to 8.3.0.
This upgrade is causing our existing test cases to fail.

### Expected Result

The test cases should pass as before the upgrade of the sentry package.

### Actual Result

I am getting this error when running our test cases after doing the upgrade in pubspec.

Pending timers:
Timer (duration: 0:00:30.000000, periodic: false), created:
#0      new FakeTimer._ (package:fake_async/fake_async.dart:308:62)
#1      FakeAsync._createTimer (package:fake_async/fake_async.dart:252:27)
#2      FakeAsync.run.<anonymous closure> (package:fake_async/fake_async.dart:185:19)
#6      NativeAppStartIntegration.getAppStartInfo (package:sentry_flutter/src/integrations/native_app_start_integration.dart:51:10)
#7      SentryNavigatorObserver._startTimeToDisplayTracking (package:sentry_flutter/src/navigation/sentry_navigator_observer.dart:335:62)
#8      SentryNavigatorObserver.didPush (package:sentry_flutter/src/navigation/sentry_navigator_observer.dart:155:5)
#9      _NavigatorPushObservation.notify (package:flutter/src/widgets/navigator.dart:3372:14)
#10     List.forEach (dart:core-patch/growable_array.dart:416:8)
#11     NavigatorState._flushObserverNotifications (package:flutter/src/widgets/navigator.dart:4368:27)
#12     NavigatorState._flushHistoryUpdates (package:flutter/src/widgets/navigator.dart:4330:5)
#13     NavigatorState.restoreState (package:flutter/src/widgets/navigator.dart:3672:5)
#14     RestorationMixin._doRestore (package:flutter/src/widgets/restoration.dart:924:5)
#15     RestorationMixin.didChangeDependencies (package:flutter/src/widgets/restoration.dart:910:7)
#16     NavigatorState.didChangeDependencies (package:flutter/src/widgets/navigator.dart:3690:11)
#17     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5636:11)
#18     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5463:5)
...     Normal element mounting (67 frames)

### Are you willing to submit a PR?

None

**Comment by buenaflor** [comment]
hey thanks for the issue, we'll look into that

do you have a minimal reproducible sample test that you could share?

**Comment by buenaflor** [comment]
I've added a quick fix for this here https://github.com/getsentry/sentry-dart/issues/2103

Closing this as a duplicate
