### ISSUE TITLE
IllegalStateException: buffer is inaccessible

### ISSUE THREAD

**Issue by FantaMagier** [getsentry/sentry-dart#2147]
### Platform

Dart

### Obfuscation

Enabled

### Debug Info

Disabled

### Doctor

[✓] Flutter (Channel stable, 3.22.2, on macOS 14.5 23F79 darwin-arm64, locale de-DE)
    • Flutter version 3.22.2 on channel stable at /opt/homebrew/Caskroom/flutter/3.10.6/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (5 weeks ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/USER/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.91.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.92.0

[✓] Connected device (3 available)
    • macOS (desktop)                 • macos                 • darwin-arm64   • macOS 14.5 23F79 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 14.5 23F79 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript • Google Chrome 126.0.6478.127

[✓] Network resources
    • All expected network resources are available.

• No issues found!

### Version

8.3.0

### Steps to Reproduce

No idea, I could not reproduce it, but it occurs with some users as a major error with Sentry.

### Expected Result

No Error :D

### Actual Result

PlatformException: PlatformException(IllegalStateException, Caught IllegalStateException: buffer is inaccessible, null, null)

PlatformException: PlatformException(IllegalStateException, Caught IllegalStateException: buffer is inaccessible, null, null)
  File "stacktrace_utils.dart", line 10, in getCurrentStackTrace
  File "sentry_exception_factory.dart", line 45, in SentryExceptionFactory.getSentryException
  File "sentry_client.dart", line 201, in SentryClient._prepareEvent
  File "sentry_client.dart", line 95, in SentryClient.captureEvent
  File "hub.dart", line 114, in Hub.captureEvent

### Are you willing to submit a PR?

None

**Comment by buenaflor** [comment]
hi

thanks we will take a look!

**Comment by buenaflor** [comment]
this is related to #2148 

seems like stacktraces are being truncated

**Comment by buenaflor** [comment]
we've merged the fix that gives you the proper stacktrace (will be out next release `8.5.0`) so you can debug it.
