### ISSUE TITLE
SDK crash detection events are not actionable

### ISSUE THREAD

**Issue by buenaflor** [getsentry/sentry-dart#2148]
### Description

When receiving crash reports which should indicate an issue within the Sentry SDK, we currently cannot really determine what is wrong since the stacktrace for example is very vague and doesn't tell the whole context.

<img width="1116" alt="image" src="https://github.com/getsentry/sentry-dart/assets/23364143/1b62bdc3-714d-43d7-bafd-0f2d2dd0e5ce">

### Reason

When an error happens and the stacktrace we get is either empty or null we call StackTrace.current to grab it but it is truncated because
the async nature of the error handling in the integration might be creating a new execution context, losing the original stack.

**Comment by buenaflor** [comment]
Fixed by #2152

**Comment by hao1208hao** [comment]
stacktrace_utils.dart 位置 getCurrentStackTrace 行 10 在 sentry
sentry_client.dart 位置 SentryClient._prepareEvent 行 270 在 sentry
sentry_client.dart 位置 SentryClient.captureEvent 行 117 在 sentry
sentry_client.dart 位置 SentryClient.captureMessage 行 335 在 sentry
hub.dart 位置 Hub.captureMessage 行 226 在 sentry


sentry  version   8.7.0  

![Image](https://github.com/user-attachments/assets/a192e103-2588-4d0d-9f49-9d3be688ef36)
