### ISSUE TITLE
App freezes when using autoAppStart=false

### ISSUE THREAD

**Issue by shinayser** [getsentry/sentry-dart#2160]
### Platform

Dart

### Obfuscation

Enabled

### Debug Info

Enabled

### Doctor

`Dart SDK version: 3.3.4 (stable) (Tue Apr 16 19:56:12 2024 +0000) on "windows_x64"`

### Version

7.18.0

### Steps to Reproduce

Setting autoAppStart=false frezes the app after the first screen of the app. 

### Expected Result

App should proceed

### Actual Result

In our case we have an loading animation that freezes on final frame and then the app doesn't proceed. Turning autoAppStart back to `true` backs everything to normal.

We also using the  `SentryFlutter.setAppStartEnd( ... )` but doesn't help.

### Are you willing to submit a PR?

None

**Comment by buenaflor** [comment]
hey this is a bug in your used sentry version, try out `7.20.2` which should include one of the fixes https://github.com/getsentry/sentry-dart/pull/2045

if you still have problems then I can also suggest removing the integration for now

```dart
// ignore: implementation_imports
import 'package:sentry_flutter/src/integrations/native_app_start_integration.dart';

options.removeIntegration(options.integrations.firstWhere((e) => e is NativeAppStartIntegration));
 ```

**Comment by shinayser** [comment]
@buenaflor amazing to hear! I will try it tomorrow and give you feedback!

**Comment by shinayser** [comment]
Thanks for the help. It worked with 7.20.2!
