### ISSUE TITLE
[sentry_flutter] sentry_flutter only one version in 'pub.dev'

### ISSUE THREAD

**Issue by chvin** [getsentry/sentry-dart#217]
sentry_flutter versions: https://pub.dev/packages/sentry_flutter/versions
Only 1 version: 4.0.0-alpha.2. Alpha meaning not safe.I can't use safe 3.x version

Compare dio versions: https://pub.dev/packages/dio/versions
Dio has all versions.

**Comment by marandaneto** [comment]
@chvin `sentry_flutter` is a new package and it's built on top of the https://pub.dev/packages/sentry/versions package, which does have more versions.

our docs https://docs.sentry.io/platforms/flutter/ mention that this is a `Prerelease`, also its released under a Prerelease tag on `pub.dev` and also `GH releases`, how can we make it clearer that this is indeed, a Prerelease?

so feel free to wait a bit more and use once it's GA.
