### ISSUE TITLE
Provide a way to cause an example native crash from Flutter

### ISSUE THREAD

**Issue by kuhnroyal** [getsentry/sentry-dart#219]
I am trying to migrate from the flutter_sentry package which has this option.
In hindsight I found myself using this often to test the correct integration.

It would be great if there was something like `SentryFlutter.nativeCrash()` which would use the method channel to create an example crash on the native side.

**Comment by marandaneto** [comment]
that sounds reasonable, our Native SDKs do that already

See the Apple SDK: https://github.com/getsentry/sentry-cocoa/blob/master/Sources/Sentry/SentrySDK.m#L202-L206
I'd just need to add a new method in the bridge and call them accordingly :)

**Comment by marandaneto** [comment]
if you need this right now, you can get inspiration from here https://github.com/getsentry/sentry-dart/blob/main/flutter/example/android/app/src/main/kotlin/io/sentry/samples/flutter/MainActivity.kt

and here https://github.com/getsentry/sentry-dart/blob/main/flutter/example/ios/Runner/AppDelegate.swift

We do have this in our built-in samples.

**Comment by bruno-garcia** [comment]
It's a good idea and we should probably use that on our Wizards at Sentry

**Comment by tomas-dorda** [comment]
I would really appreciate that for testing! Any progress on this one?

**Comment by bruno-garcia** [comment]
Looks like @buenaflor assigned himself 🥳 

For reference, how C# does it: https://github.com/getsentry/sentry-dotnet/blob/bea3fcf35dc0a2787dbf9c96931ec9895989907c/src/Sentry/SentrySdk.cs#L675-L723
