### ISSUE TITLE
TTID is greater than TTFD

### ISSUE THREAD

**Issue by tapas-tw** [getsentry/sentry-dart#2191]
### Platform

Dart

### Obfuscation

Disabled

### Debug Info

Enabled

### Doctor

Flutter (Channel [user-branch], 3.13.1, on macOS 14.5 23F79 darwin-arm64, locale en-IN)
Dart version 3.1.0
DevTools version 2.25.0

### Version

8.2.0

### Steps to Reproduce

Add automatic traces using route observer and then go to the discover tab, add the filter for the data we are looking for.

### Expected Result

TTID should be lesser than TTFD. As both start from the 0 and then TTID stop when the first frame drawn but TTFD stop when the full widget loads. So TTFD can't be lesser than TTID. 

In the attached imaged, TTID is clearly visible that it's lesser than the TTFD which is ideal but while doing the avg(measurements.time_to_initial_display) & avg(measurements.time_to_full_display) is giving unexpected result. 

![Image](https://github.com/user-attachments/assets/ff207e1f-163d-48e5-8608-845a55ef20d8)

### Actual Result

![Image](https://github.com/user-attachments/assets/84204cce-1ab1-4ca0-ab95-adbdb81e3eee)

### Are you willing to submit a PR?

None

**Comment by buenaflor** [comment]
hey thanks for raising this issue!

@narsaynorath could you take a quick look here? I'm not sure if it is an SDK issue, the trace itself looks fine

**Comment by narsaynorath** [comment]
Hey @tapas-tw, I'd like to take a look at what's going on but to do that I need a little more info. Specifically which org and project you're using. Would you mind posting the relevant DSN here as a comment to help with that?

If you're uncomfortable posting it in a comment here, you are also welcome to submit a support ticket [here](https://sentry.zendesk.com/hc/en-us/requests/new) and mention this GH issue and my username so I can get that information.
