### ISSUE TITLE
Error collect flushbar toast istead of current page

### ISSUE THREAD

**Issue by Korpyc** [getsentry/sentry-dart#2205]
### Problem Statement

Hi there, I have next problem:

I'm using another_flushbar package to show toast messages when errors occurred.
This package show those toast as a new route with route name "/flushbarRoute".
Because of it in issue reports I don't see page where issue occurred.

I found `routeNameExtractor` param in `SentryNavigatorObserver`, but it not contains stack, only current "/flushbarRoute" route.

How can I resolve this problem?

### Are you willing to submit a PR?

None

**Comment by buenaflor** [comment]
Hi, thanks for raising this issue, I'll take a look

**Comment by buenaflor** [comment]
So essentially you need Sentry to report the 'latest' route that is not the toast correct?

**Comment by Korpyc** [comment]
Yes

Need to filter out this toast route which is extended from OverlayRoute

**Comment by buenaflor** [comment]
can you upload a screenshot example here or even send me the event link to giancarlo.buenaflor@sentry.io so I can take a look directly

**Comment by buenaflor** [comment]
What we could do is add a configurable array that ignores routes that you can define, e.g 
```dart
SentryNavigatorObserver(ignoreRoutes: ['flushbarRoute'])
```

**Comment by Korpyc** [comment]
I like this solution, would be useful
