### ISSUE TITLE
Could provide a version adapted for Android 15 with a 16KB size limit?

### ISSUE THREAD

**Issue by wyqlxf** [getsentry/sentry-dart#2237]
### Problem Statement

https://developer.android.com/guide/practices/page-sizes?hl=zh-cn

### Are you willing to submit a PR?

None

```[tasklist]
### Depends on
- [ ] https://github.com/getsentry/sentry-java/issues/3657
```

**Comment by buenaflor** [comment]
hi we'll have a look

**Comment by buenaflor** [comment]
Currently blocked by https://github.com/getsentry/sentry-java/issues/3657

**Comment by kahest** [comment]
there's a prerelease out on Android ([7.17.0-alpha.1](https://github.com/getsentry/sentry-java/releases/tag/7.17.0-alpha.1)) for testing

**Comment by denrase** [comment]
I checked with Android `7.17.0-alpha.1` with the [scrip](https://developer.android.com/guide/practices/page-sizes#alignment-use-script) provided by google. It was broken but after playing around, i was able to fix it.

The page sizes are aligned for our Android dependency, but we need to check `Isar` and `SQLite` dependencies. This was the sample app. I'm not sure where `libnative-sample` is coming from.

Results are the same for arch `arm64-v8a` and `armeabi-v7a`.

```
=== ELF alignment ===
app-release/lib/arm64-v8a
libapp.so		libnative-sample.so	libsqlite3.so
libflutter.so		libsentry-android.so
libisar.so		libsentry.so
app-release/lib/arm64-v8a/libsentry.so: \e[32mALIGNED\e[0m (2**14)
app-release/lib/arm64-v8a/libflutter.so: \e[32mALIGNED\e[0m (2**16)
app-release/lib/arm64-v8a/libapp.so: \e[32mALIGNED\e[0m (2**16)
app-release/lib/arm64-v8a/libsentry-android.so: \e[32mALIGNED\e[0m (2**14)
app-release/lib/arm64-v8a/libisar.so: \e[31mUNALIGNED\e[0m (2**12)
app-release/lib/arm64-v8a/libnative-sample.so: \e[31mUNALIGNED\e[0m (2**12)
app-release/lib/arm64-v8a/libsqlite3.so: \e[31mUNALIGNED\e[0m (2**12)
```

**Comment by markushi** [comment]
FYI: We shipped the 16kb support with the `7.18.0` release of the Android SDK.

**Comment by denrase** [comment]
I updated our [sample app to support 16kb pages](https://github.com/getsentry/sentry-dart/pull/2445) by bumping NDK to 27 and updating the `app/build.gradle` as described in [here](https://developer.android.com/guide/practices/page-sizes#compile-r27) . I works on a 16KB emulator device, also with our Isar and SQFlite packages. This only works where we have Sentry Android `7.18.0` SDK, so users also need to upgrade to Sentry `8.11.0-beta.1`

**Comment by buenaflor** [comment]
@denrase perfect, so it's a matter of documenting it and using at least `8.11.0-beta.1` 👍

**Comment by denrase** [comment]
@buenaflor We support it from `8.11.0-beta.1`.  Apart from that, the setup for 16 KB pages is unrelated to Sentry, so i don't think we should provide additional documentation, apart from stating that we support it. WDYT?

**Comment by buenaflor** [comment]
@denrase I think we should at least say that the setup is required (and link there)
