### ISSUE TITLE
Change sentry default Ip Address

### ISSUE THREAD

**Issue by tazik561** [getsentry/sentry-dart#225]
I install self host sentry by docker. In my flutter Application by using `runZonedGuarded`:
```
void main() => runZonedGuarded(() async {
      await SentryFlutter.init(
        (options) {
          options.dsn =
              "http://2f4c84df6ec249dab1fe96c1b8309f7e@127.0.0.1:9000/2";
          options.debug = true;
        },
        appRunner: () => runApp(MyApp()),
      );
    }, (exception, StackTrace stackTrace) async {
      await Sentry.captureException(
        exception,
        stackTrace: stackTrace,
      );
    });
```

I am trying to report exception on Android emulator but i got:
`java.net.ConnectException: Failed to connect to /127.0.0.1:9000`

How can i change 127.0.0.1 on sentry ?It is possible to change from dashboard?

**Comment by marandaneto** [comment]
@tazik561 2 things here.

1. you don't need a `runZonedGuarded` if using an `appRunner` callback as you do, we run your app automatically on a `runZonedGuarded`

2. you don't need to change the IP, you need to copy the DSN from the dashboard which already has probably your network IP, questions related to the Sentry server would be better asked on this repo https://github.com/getsentry/sentry

**Comment by bruno-garcia** [comment]
Dupe: https://forum.sentry.io/t/change-sentry-default-ip-address/12044
