### ISSUE TITLE
Update generated isar code in flutter sample

### ISSUE THREAD

**Issue by denrase** [getsentry/sentry-dart#2261]
### Description

We ned to update the generated code.

![Image](https://github.com/user-attachments/assets/3d9da318-7751-459d-b4f7-543013d6186a)

**Comment by buenaflor** [comment]
@denrase is this still relevant? I've updated the isar dep to the isar community one https://github.com/getsentry/sentry-dart/pull/2358

**Comment by denrase** [comment]
@denrase let me check..

**Comment by denrase** [comment]
Yup, still the same, i'll make a PR with the needed updates.

![Image](https://github.com/user-attachments/assets/93b69f16-2286-4ad9-8deb-d101f0391272)

**Comment by buenaflor** [comment]
@denrase okay, you can also update my linked PR directly

**Comment by denrase** [comment]
@buenaflor done 👍
