### ISSUE TITLE
Exceptions dont print to console

### ISSUE THREAD

**Issue by dannnnthemannnn** [getsentry/sentry-dart#2273]
### Platform

Flutter Mobile

### Obfuscation

Disabled

### Debug Info

Disabled

### Doctor

I am seeing my uncaught exceptions properly in sentry but they do not print to the console when I am running on android. I know I can enable debug = true, but then it shows all kinds of breadcrumbs and other stuff and the error reports dont show the error message, they just show some debug info about sending something to sentry. 

### Version

8.8.0

### Steps to Reproduce

Throw an exception that is not caught. 

### Expected Result

Some way to see exceptions in the console. 

### Actual Result

It does not show up in the console 

### Are you willing to submit a PR?

None

**Comment by buenaflor** [comment]
hey I believe uncaught exceptions are automatically printed to the console by flutter is it not?



![Image](https://github.com/user-attachments/assets/877d51a2-e799-49f6-aa1a-87d8c26a23ee)

**Comment by MindStudioOfficial** [comment]
I have a similar issue.

Unhandled exceptions pop up in the sentry dashboard but nothing is visible in the debug console.

```dart
await SentryFlutter.init(
    (options) {
      options
        ..dsn = AppConstants.sentryDSN
        ..tracesSampleRate = 1.0
        ..profilesSampleRate = 1.0
        ..autoAppStart = false
        ..environment = kDebugMode ? 'debug' : 'production'
        ..release = AppConfig.version
        ..debug = kDebugMode
        ..beforeSend = (event, hint) {
          if (event.throwable is FlutterError &&
              event.throwable.toString().contains('overflowed')) {
            return null;
          }
          event.contexts.addAll(
            {
              'logs': {
                'value': Logger.getLastEntries(AppConstants.sentryLogCount),
              },
            },
          );
          return event;
        };
    },
    appRunner: () => runApp(
      const ProviderScope(
        child: MainWindowManager(),
      ),
    ),
  );
```

It looks like sentry is catching all exceptions and prevents flutter from printing them to the console.


... I am trying to debug a SocketException (probably file or directory access denied)

```
SocketException: SocketException: Zugriff verweigert

 (OS Error: Zugriff verweigert, errno = 5), port = 0
  #0      PlatformDispatcher._dispatchError (dart:ui/platform_dispatcher.dart:1326:23)
  #1      _onError (dart:ui/hooks.dart:288:38)
```

... but the stacktrace in sentry doesn't show a lot.
