### ISSUE TITLE
Sentry failed to fetch errors with little information on failed event and miscellaneous stacktrace.

### ISSUE THREAD

**Issue by rutvik-at-pieces** [getsentry/sentry-dart#2276]
### Platform

Dart Web

### Obfuscation

Enabled

### Debug Info

Enabled

### Doctor

Dart SDK version: 3.5.0-180.3.beta (beta) 

### Version

7.7.0

### Steps to Reproduce

Not able to reproduce myself.

### Expected Result

Reported error should've some more information on which fetch requests are failing.

### Actual Result

Following error has been flooding our sentry dashboard since last 2 days. Thousands of such reports have been coming in. The error indicates that a fetch request is failing but doesn't really give any more info into which fetch requests are failing and why. Also, the stacktrace is pointing to some Sentry error reporting apis which has me confused as to whats actually going on here. 

```
JSObject: TypeError: Failed to fetch
  at Object.StackTrace_current(content.dart.js:6034:38)
  at SentryClient._prepareEvent$2$stackTrace(content.dart.js:72094:28)
  at <fn>(content.dart.js:71954:43)
  at _wrapJsFunctionForAsync_closure.$protected(content.dart.js:4347:15)
  at _wrapJsFunctionForAsync_closure.call$2(content.dart.js:32401:12)
  at Object._asyncStartSync(content.dart.js:4311:20)
  at SentryClient.captureEvent$4$hint$scope$stackTrace(content.dart.js:72032:16)
  at <fn>(content.dart.js:70375:48)
  at _wrapJsFunctionForAsync_closure.$protected(content.dart.js:4347:15)
  at _wrapJsFunctionForAsync_closure.call$2(content.dart.js:32401:12)
```

### Are you willing to submit a PR?

None

**Comment by buenaflor** [comment]
is there a possibility to upgrade your sdk version? we've done some minor changes to stacktrace fetching so it might help

but for some context: sometimes unhandled errors simply do not have stacktraces attached so we do our best by calling `StackTrace.current` but in some cases for example async it won't capture the whole context which I suspect has happened here.

**Comment by rutvik-at-pieces** [comment]
@buenaflor Thanx for the info! We're shipping a new build with latest sentry version `8.8.0`. Will let u know if it helps in anyway.

**Comment by rutvik-at-pieces** [comment]
@buenaflor Upgrading to the latest sentry version didn't gave any new information on the failed fetch errors. But we found out the root cause of the issue. Some requests to our local server were failing which was causing this issue. 

Though the issue is resolved on our end, I would love to see the improvements I mentioned in the future releases of sentry. With that said, I'm not sure if you wanna keep the issue open to track this particular issue I mentioned about capturing more info on such errors or if you wanna close this issue if this is being tracked somewhere else. I'm good both ways.

**Comment by buenaflor** [comment]
would you mind sending me such an issue to giancarlo.buenaflor@sentry.io

**Comment by rutvik-at-pieces** [comment]
@buenaflor Just shared the feedback in the mail. Feel free to close the issue if you're handling these anywhere else.

**Comment by buenaflor** [comment]
Thanks, I'll have a look

**Comment by buenaflor** [comment]
@rutvik-pieces hey dunno if my email is not working right but your feedback text is empty on my end. It'd be great if you could include the link to an example sentry issue in the email
