### ISSUE TITLE
Value of type 'SentryReplayOptions' has no member 'onErrorSampleRate'

### ISSUE THREAD

**Issue by Charles045** [getsentry/sentry-dart#2288]
### Platform

Flutter Mobile

### Obfuscation

Disabled

### Debug Info

Disabled

### Doctor

[✓] Flutter (Channel stable, 3.24.0, on macOS 14.6 23G80 darwin-arm64, locale zh-Hans-CN)
    • Flutter version 3.24.0 on channel stable at /Users/xxxxx/FlutterSDK/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 80c2e84975 (6 weeks ago), 2024-07-30 23:06:49 +0700
    • Engine revision b8800d88be
    • Dart version 3.5.0
    • DevTools version 2.37.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/xxxxxx/Library/Android/sdk
    • Platform android-34-ext11, build-tools 34.0.0
    • ANDROID_HOME = /Users/xxxxxx/Library/Android/sdk
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk-17.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 17.0.10+11-LTS-240)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/to/macos-android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2023.3.7)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 81.0.1
    • Dart plugin version 233.15325.11

[✓] VS Code (version 1.92.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.96.0

[✓] Connected device (3 available)
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 14.6 23G80 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 14.6 23G80 darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 128.0.6613.137

[✓] Network resources
    • All expected network resources are available.

### Version

8.9.0

### Steps to Reproduce

await SentryFlutter.init((option) {
      option.dsn = GGRunEnv.shared.sentryDsn;
      option.environment = GGRunEnv.env.value;
      option.release = 'test@$version';
      option.sampleRate = 1.0;
      option.reportPackages = false;
      option.enablePrintBreadcrumbs = false;
      option.considerInAppFramesByDefault = false;
      option.enableDartSymbolication = true;
      option.reportSilentFlutterErrors = true;
      option.tracesSampleRate = GGRunEnv.shared.sentryTraces;
      option.maxRequestBodySize = MaxRequestBodySize.always;
      option.maxResponseBodySize = MaxResponseBodySize.always;
      option.navigatorKey = GGAdaptor.navigatorKey;
      if (GGRunEnv.env == GGEnvType.dev) {
        option.debug = true;
      }
    }, appRunner: runner);

### Expected Result

Swift Compiler Error (Xcode): Value of type 'SentryReplayOptions' has no member 'onErrorSampleRate'
/Users/xxxxx/.pub-cache/hosted/pub.flutter-io.cn/sentry_flutter-8.9.0/ios/Classes/SentryFlutter.swift:111:47

### Actual Result

Swift Compiler Error (Xcode): Value of type 'SentryReplayOptions' has no member 'onErrorSampleRate'
/Users/xxxxx/.pub-cache/hosted/pub.flutter-io.cn/sentry_flutter-8.9.0/ios/Classes/SentryFlutter.swift:111:47

Uncategorized (Xcode): Command SwiftCompile failed with a nonzero exit code

### Are you willing to submit a PR?

None

**Comment by buenaflor** [comment]
I noticed you use this: `option.enableDartSymbolication = true`. This is not necessary when using `SentryFlutter.init` and will be auto disabled by our SDK. This is only needed if you use `Sentry.init`.

I think this needs to be more clear in the variable name and documentation

**Comment by Charles045** [comment]
this issue is caused by Sentry/HybridSDK not update latest version

**Comment by buenaflor** [comment]
Oh yes, my comment was only meant as a side note about your config
