### ISSUE TITLE
Session Replay crashing iOS application

### ISSUE THREAD

**Issue by stayallive** [getsentry/sentry-dart#2295]
### Platform

Flutter Mobile

### Obfuscation

Enabled

### Debug Info

Enabled

### Doctor

```
[✓] Flutter (Channel stable, 3.24.2, on macOS 15.0 24A335 darwin-arm64, locale en-US)
    • Flutter version 3.24.2 on channel stable at /Users/alexbouma/sdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cf269e36d (13 days ago), 2024-09-03 14:30:00 -0700
    • Engine revision a6bd3f1de1
    • Dart version 3.5.2
    • DevTools version 2.37.2
```

### Version

8.9.0

### Steps to Reproduce

1. Enable Session Replay:
    ```dart
    ..experimental.replay.sessionSampleRate = 0.0
    ..experimental.replay.onErrorSampleRate = 1.0,
    ```
2. Open application, not observed when debugging yet only on Testflight

### Expected Result

No crash and replays 😄 

### Actual Result

Sometimes: https://recommendly.observ.app/share/issue/be0bb992d3d24c9cb1cf95c7b4621c4d/

Doesn't seem to be consistent. No replays sent yet either. Disabled the feature for now.

**Comment by buenaflor** [comment]
cc @vaind

**Comment by vaind** [comment]
Thanks for reporting this, I'll have a look into reproducing. 

@stayallive any device logs available?

**Comment by stayallive** [comment]
Okay this gonna sound a bit daft maybe but I have a screenshot 🙈

![Image](https://github.com/user-attachments/assets/4ce78f91-c870-4d61-a90c-ed0311c48d91)

(interestingly this screenshot is way more detailed/helpful I'd imagine then the Sentry report...)

I also do have a Crash Point File but unsure how useful that might be to you since I'm assuming it's specific to my application.

I have no logs from the device other than this as far as I can find.

Hopefully this is helpful, but if not please let me know what I should do to help out!

**Comment by vaind** [comment]
@stayallive thanks for reporting this, a fix will come in the next release.
