### ISSUE TITLE
Add support for isar community fork for `sentry_isar` package

### ISSUE THREAD

**Issue by sbordeyne** [getsentry/sentry-dart#2296]
### Problem Statement

The main `isar` package seems to have gone unmaintained, thankfully the community has picked up the slack and supports it through https://github.com/isar-community/isar.

The problem is that even though there seems to be 100% compatibility with the main `isar` package, sentry's isar integration depends on isar, which causes problems : the community fork is not hosted on pub.dev hence pub flags it as incompatible

### Solution Brainstorm

I think the only way to actually support it is to add a new package : `sentry_isar_community` which doesn't depend on isar, but instead on the forked version. The code can remain the same, except for the generated code which needs to be regenerated to fit the changes and bug fixes in the community fork.

### Are you willing to submit a PR?

Yes

**Comment by ueman** [comment]
Why doesn't the community supports the Sentry integration?

**Comment by kahest** [comment]
As discussed [here](https://github.com/getsentry/sentry-dart/pull/2297#issuecomment-2358093361), there is currently no need for a separate package. Closing this for now, feel free to follow up here if there's problems or questions
