### ISSUE TITLE
[iOS] Error on Xcode 16

### ISSUE THREAD

**Issue by mduccc** [getsentry/sentry-dart#2303]
### Platform

Flutter Mobile

### Obfuscation

Disabled

### Debug Info

Enabled

### Doctor

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.12, on macOS 14.5 23F79 darwin-arm64, locale en-VN)
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more
      details.
[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
[✓] Chrome - develop for the web
[!] Android Studio (version 2023.2)
    ✗ Unable to find bundled Java version.
[✓] VS Code (version 1.93.1)
[✓] Connected device (4 available)
    ! Error: Browsing on the local area network for iPhone 12pro max test kvonline
      😁😁😁_|~}qẻ1. Ensure the device is unlocked and attached with a cable or
      associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] HTTP Host Availability

! Doctor found issues in 2 categories.

### Version

6.22.0

### Steps to Reproduce

1. flutter pub get
2. flutter run 

### Expected Result

Run IOS success

### Actual Result

```
 ** BUILD FAILED **
Xcode's output:
↳
    Writing result bundle at path:
    	/var/folders/js/2qmlk4w15m7fsdhghcx4xwlr74_ykf/T/flutter_tools.mvqYe5/flutter_ios_build_temp_diruOYvNZ/temporary_xcresult_bundle
    /Users/duc.nm4/Documents/Projects/xxx/example/ios/Pods/Sentry/Sources/SentryCrash/Recording/Monitors/SentryCrashMonitor_CPPException.cpp:59:13: error: no type named 'terminate_handler' in namespace 'std'
       59 | static std::terminate_handler g_originalTerminateHandler;
```

### Are you willing to submit a PR?

None

**Comment by rirjkl19** [comment]
Same issue. Any temporary fix?

**Comment by kahest** [comment]
Hey @mduccc @rirjkl19 for building with Xcode 16, a number of changes had to be made to the underlying sentry-cocoa SDK. These changes are all included in `sentry-dart 8.8.0` or newer.

**Comment by Klucherev** [comment]
Same issue

**Comment by buenaflor** [comment]
> Same issue

Have you tried the mentioned fix above? Using sentry dart version 8.8.0 or higher

**Comment by Klucherev** [comment]
> > Same issue
> 
> Have you tried the mentioned fix above? Using sentry dart version 8.8.0 or higher

I'm using 8.9.0 from pub.dev

**Comment by buenaflor** [comment]
@denrase ~apparently it still does not work even on 8.9.0, ptal~

It works starting from 8.8.0

**Comment by denrase** [comment]
So i cannot reproduce this, building works for me with the current Xcode `Version 16.0 (16A242d)`.  

This is my `flutter doctor`:

```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.3, on macOS 14.5 23F79 darwin-arm64, locale de-AT)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.2)
[✓] IntelliJ IDEA Community Edition (version 2022.2)
[✓] VS Code (version 1.93.1)
[✓] Connected device (4 available)
    ! Error: Browsing on the local area network for Wohnzimmer. Ensure the device is unlocked and associated with
      the same local area network as this Mac. (code -27)
    ! Error: Browsing on the local area network for iPad Pro. Ensure the device is unlocked and attached with a
      cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources

• No issues found!
```

@Klucherev Could you try the following:

- Updating your Flutter version

```bash
flutter upgrade
```

- Delete the `DerivedData` folder of Xcode, there might be old build artefacts left.

```bash
rm -rf ~/Library/Developer/Xcode/DerivedData/*
```

- Then run again

```bash
flutter pub get
flutter run
```

Please report back if this resolves your issue. Thank you.

**Comment by Klucherev** [comment]
After cleaning project it's working now!
flutter clean
flutter pub get
pod update

**Comment by denrase** [comment]
@Klucherev Nice, so it was probably the usual Xcode hickups, glad it's working for you.

**Comment by dilraj007** [comment]
is there any fix for **SDK 6.22.0** ? 
I can only use this version as my Flutter app is.
```
Flutter 2.10.5 • channel unknown • unknown source
Framework • revision 5464c5bac7 (2 years, 5 months ago) • 2022-04-18 09:55:37 -0700
Engine • revision 57d3bac3dd
Tools • Dart 2.16.2 • DevTools 2.9.2
```

**Comment by buenaflor** [comment]
@dilraj007 I haven't tried it or checked it out but the only thing that comes to my mind is if you somehow manage to override the Sentry Cocoa pod dependency to the latest version (if even possible).

Even if you successfully do that, there's no guarantee for any stability in the SDK

**Comment by dilraj007** [comment]
@buenaflor I see, thanks for the reply. 

If it's breaks on Xcode 16, does it mean right now my app that are using this Sentry SDK version is not running on IOS 18? 
So it will not send data from these IOS 18 devices.

**Comment by buenaflor** [comment]
No, it only reports an error when compiling with xcode 16 because apple changed things although I cannot tell you which exact changes were relevant - thats why we had to make adjustments in our Sentry Cocoa SDK. Your existing apps in prod using the SDK are fine. Those two are unrelated

**Comment by Mugilan-Codes** [comment]
So, what is the solution for this?

**Comment by rirjkl19** [comment]
Update the pods. 

If not working

Sentry package. Or update your flutter version 😁

**Comment by IKRAMULHAQ786** [comment]
I was able to resolve this issue by following steps:

- Go in the project-navigator, select your project
- Select Build Phasestab
- In Compile Sources section, check for the file(s) that Xcode is complaining of in this case 
- Notice that the file(s) have the wrong path, and delete them by clicking on the minus icon
- Re-add the file(s) by clicking the plus icon and search in the project. (when promted click on `Create Groups` option
- Product > Clean Build Folder
- Build

Another solution might be to simply delete the file and then never add it because it is not needed.
