### ISSUE TITLE
GDPR Cookie / Consent Solution

### ISSUE THREAD

**Issue by FantaMagier** [getsentry/sentry-dart#2310]
### Problem Statement

I would like to get the user consent to send his crash reports. As soon as the user has given me the ok, I can send the crash reports and co. to Sentry.

### Solution Brainstorm

Is there a function to activate or deactivate tracking at any time?

### Are you willing to submit a PR?

None

**Comment by buenaflor** [comment]
Using [beforeSend](https://docs.sentry.io/platforms/dart/configuration/filtering/#using-before-send) will allow you to do this.
This code snippet will prevent any data from being sent before the consent:

```dart
await SentryFlutter.init((options) {
  options.beforeSend = (event, hint) async {
    if (consentGiven) {
        return event;
    }
    return null;
  };
});
```

**Comment by FantaMagier** [comment]
Thanks!
