### ISSUE TITLE
`enabled` flag

### ISSUE THREAD

**Issue by danilofuchs** [getsentry/sentry-dart#2313]
### Problem Statement

I want to enable Sentry only in production builds
In other Sentry SDKs there is an `enabled` option

### Are you willing to submit a PR?

None

**Comment by buenaflor** [comment]
It's a workaround but you can do this for now

```dart
await SentryFlutter.init((options) {
  options.beforeSend = (event, hint) async {
    if (kDebugMode) {
        return null;
    }
    return event;
  };
});
```

Let's see if we can do this more cleanly and easier

**Comment by buenaflor** [comment]
which enable option do you refer to in other SDKs?

**Comment by danilofuchs** [comment]
In JS SDK there's an `enabled` flag:

![Image](https://github.com/user-attachments/assets/9fceb4bc-d7ca-45ff-8bd7-dae37597f5cc)

**Comment by buenaflor** [comment]
Gotcha, I will discuss this internally

**Comment by buenaflor** [comment]
What exactly are you trying to accomplish / expecting, just not send the event in debug builds?

**Comment by danilofuchs** [comment]
> What exactly are you trying to accomplish / expecting, just not send the event in debug builds?

Exactly! When developing, I will inevitably develop some runtime errors, and I don't want Sentry to be populated with these events, as they can become noise when debugging actual production issues.

For instance, we are notified in Slack for each new issue.

**Comment by buenaflor** [comment]
In that case I'd use the snippet that I posted above with beforeSend which will achieve exactly what you're trying to do.

We don't have the enabled option in other mobile sdks as well and I want to keep the feature set similar. So I don't think we should add this option now.

**Comment by kuhnroyal** [comment]
Only setting the DSN in production should do the trick?

**Comment by buenaflor** [comment]
either setting dsn in prod or using beforeSend, both work - whatever you prefer

if you want to minimize the overhead in general you could conditionally use `SentryFlutter.init` only on prod

**Comment by buenaflor** [comment]
We've decided not to go ahead with this, please use either `beforeSend`, empty dsn in debug or conditionally execute `SentryFlutter.init` only on prod
