### ISSUE TITLE
Package `stack_trace` has now support for parsing WASM frames

### ISSUE THREAD

**Issue by ueman** [getsentry/sentry-dart#2335]
### Description

The `stack_trace` package was updated to support parsing WASM frames, see https://pub.dev/packages/stack_trace/changelog

However, it then requires Dart 3.4

This is more of a FYI, than an actual issue :D

**Comment by buenaflor** [comment]
Thanks for the heads up!

We are also waiting on https://github.com/dart-lang/sdk/issues/56718 to unblock us for wasm symbolication

**Comment by buenaflor** [comment]
I added comment [here](https://github.com/getsentry/sentry-dart/issues/1480) 

thx for bringing this up
