### ISSUE TITLE
Improvements when capture methods are called in tight loops

### ISSUE THREAD

**Issue by denrase** [getsentry/sentry-dart#2379]
### Problem Statement

Relates to #2371

When capturing in tight loops (awaiting the SDK methods), we run into memory issues (screenshot integration) on iOS and the watchdog might be killing the app. This probably happens because of screenshot widget, but there also might be other bottlenecks thought the SDK.

> @buenaflor Still need to test this on an actual iOS device. In the meantime, can the user in question use something like exponential backoff until we come up with a solution? Think this PR here is good in itself, no need to do processing for dropped tasks, but it will not solve the issue of too many awaited tasks in a loop. Here we are still attaching screenshots.
> 
> Come to think of it, what if we cache the screenshot for some time? That way every event would still get a screenshot attached, but we could probably also relieve a bit of CPU/Memory pressure.

https://github.com/getsentry/sentry-dart/pull/2371#issuecomment-2444400216

### Solution Brainstorm

- Further investage where we have bottlenecks that can be improved.
- Use a short-lived cashed screenshot to avoid making hundreds of screenshots if the SDK is called in a tight loop.

### Are you willing to submit a PR?

Yes

**Comment by denrase** [comment]
> generally looks good, got one question
> 
> ![image](https://private-user-images.githubusercontent.com/23364143/380653415-92abb755-2fc2-47b0-9eb9-b7d46323f5fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3MzEzMDEsIm5iZiI6MTczMDczMTAwMSwicGF0aCI6Ii8yMzM2NDE0My8zODA2NTM0MTUtOTJhYmI3NTUtMmZjMi00N2IwLTllYjktYjdkNDYzMjNmNWZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA0VDE0MzY0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2MGRkYzYzYzQ2YTgyMTg2ZTIyNTM4ZGZhODQ5OGFmMTk0NTgzY2YzN2M1MzE1ZjQ1YzI4ZTlhNjFjZTMxNGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6cYWu2fMdUqQtDTqHit8bOXT7aKRlICVmBGR59qP5jY)
> 
> so these are not dropped since we await each call but according to the user this example can somewhat reproduce watchdog killing the app on ios.
> 
> can you reproduce this?

@buenaflor Just checked this again. The tasks are actually **not** awaiting on each other, so our code to handle is being called in this particular example. Woking on the cached screenshots now where i use a plain for loop, then the tasks are awaited.

**Comment by buenaflor** [comment]
oh good 👍
