### ISSUE TITLE
[sentry_flutter] Lifecycle breadcrumb is kinda wrong

### ISSUE THREAD

**Issue by ueman** [getsentry/sentry-dart#240]
[This breadcrumb](https://github.com/getsentry/sentry-dart/blob/main/flutter/lib/src/widgets_binding_observer.dart#L43-L57) should be analog to [this Android breadcrumb](https://github.com/getsentry/sentry-java/blob/main/sentry-android-core/src/main/java/io/sentry/android/core/LifecycleWatcher.java#L119-L128).
Currently it is more like an Activity-Lifecycle event despite being an application wide lifecycle event.
I've stumbled across this, while researching [this](https://github.com/getsentry/develop/issues/213#issuecomment-743026394).

**Comment by marandaneto** [comment]
@ueman good catch, it's more about App's lifecycle (background/foreground), maybe it makes sense to just toggle the Android option `enableAppLifecycleBreadcrumbs` if using the WidgetsBinding then.
Would you like to contribute? :)

We probably need to fix here the naming of the options (Which is checked by our WidgetsBinding wrapper), enabling/disabling the correct fields on the Native SDKs and also docs.

**Comment by ueman** [comment]
Yeah, but it could take some time until I come around to it.

**Comment by marandaneto** [comment]
on Android, we could disable only this one instead https://github.com/getsentry/sentry-java/blob/main/sentry-android-core/src/main/java/io/sentry/android/core/SentryAndroidOptions.java#L27-L28

If using the WidgetsBinding wrapper.
