### ISSUE TITLE
App Replay Type Error: "'Null' is not a subtype of type 'String'"

### ISSUE THREAD

**Issue by Swepilot** [getsentry/sentry-dart#2412]
### Platform

Flutter Mobile

### Obfuscation

Disabled

### Debug Info

Disabled

### Doctor

[✓] Flutter (Channel stable, 3.24.3, on macOS 15.0 24A335 darwin-arm64, locale en-SE)
    • Flutter version 3.24.3 on channel stable at /opt/homebrew/Caskroom/flutter/2.10.0/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (9 weeks ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/xxx/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16B40
    • CocoaPods version 1.16.2

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)

[✓] VS Code (version 1.95.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.100.0

[✓] Network resources
    • All expected network resources are available.

• No issues found!

### Version

8.10.1

### Steps to Reproduce

Run a Flutter app which is configured to use the beta feature App Replay

### Expected Result

No TypeError

### Actual Result

_TypeError (type 'Null' is not a subtype of type 'String' in type cast) on line

[https://github.com/getsentry/sentry-dart/blob/bd75526eb4d0af3be65a50ae60113b36ca139a9b/flutter/lib/src/native/sentry_native_channel.dart#L216](https://github.com/getsentry/sentry-dart/blob/bd75526eb4d0af3be65a50ae60113b36ca139a9b/flutter/lib/src/native/sentry_native_channel.dart#L216)

### Are you willing to submit a PR?

None

**Comment by buenaflor** [comment]
hi how does your init config look like?

**Comment by Swepilot** [comment]
> hi how does your init config look like?

@buenaflor like this:
```
 await SentryFlutter.init((options) {
    options.dsn =
        'https://........ingest.sentry.io/.......';

    // Set tracesSampleRate to 1.0 to capture 100% of transactions for performance monitoring.
    // We recommend adjusting this value in production.
    options.tracesSampleRate = 1.0;

    options.experimental.replay.sessionSampleRate = 1.0;
    options.experimental.replay.onErrorSampleRate = 1.0;

  }, appRunner: () => runApp(App()));
```

**Comment by nelsoncampos-cloudwalk** [comment]
Same issue here for me

**Comment by buenaflor** [comment]
does this happen both on iOS and Android?

**Comment by nelsoncampos-cloudwalk** [comment]
I can confirm that is happing in iOS @buenaflor

**Comment by buenaflor** [comment]
I believe this issue has something to do with hot-restart, I can't reproduce it when I cold start an app but as soon as I hot-restart then the error starts popping up (which indicates the `replayId` is null)

@vaind maybe you know more here

**Comment by vaind** [comment]
The issue, as mentioned by @buenaflor, happens during development when flutter does a "hot-restart". This causes our native iOS SDK (sentry-cocoa) integration to restart as well but the native replay integration doesn't restart. We'll need to make adjustments either in our calls to the native SDK or in the native SDK itself (TBD). I'll keep this issue updated when fixes are in place.

**Comment by nelsoncampos-cloudwalk** [comment]
@vaind @buenaflor Hi there! Do you have an estimated timeline for when this fix might be completed? We're really eager to start using the Sentry Replays features.

**Comment by buenaflor** [comment]
@nelsoncampos-cloudwalk we're working in a fix
