### ISSUE TITLE
Text is not masked when text is dynamic

### ISSUE THREAD

**Issue by ozalisky** [getsentry/sentry-dart#2454]
### Platform

Flutter Mobile iOS

### Obfuscation

Disabled

### Debug Info

Disabled

### Doctor

[✓] Flutter (Channel stable, 3.24.5, on macOS
    15.1.1 24B2091 darwin-arm64, locale en-US)
    • Flutter version 3.24.5 on channel stable
      at /Users/oleksandrzaliskyi/flutter
    • Upstream repository
      https://github.com/flutter/flutter.git
    • Framework revision dec2ee5c1f (2 weeks
      ago), 2024-11-13 11:13:06 -0800
    • Engine revision a18df97ca5
    • Dart version 3.5.4
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android
    devices (Android SDK version 33.0.1)
    • Android SDK at
      /Users/oleksandrzaliskyi/Library/Android/
      sdk
    • Platform android-34, build-tools 33.0.1
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin
      /java
    • Java version OpenJDK Runtime Environment
      (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode
    16.1)
    • Xcode at
      /Applications/Xcode.app/Contents/Develope
      r
    • Build 16B40
    • CocoaPods version 1.16.2

[✗] Chrome - develop for the web (Cannot find
    Chrome executable at /Applications/Google
    Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting
      CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨
      https://plugins.jetbrains.com/plugin/9212
      -flutter
    • Dart plugin can be installed from:
      🔨
      https://plugins.jetbrains.com/plugin/6351
      -dart
    • Java version OpenJDK Runtime Environment
      (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.95.3)
    • VS Code at /Applications/Visual Studio
      Code.app/Contents
    • Flutter extension version 3.100.0

[✓] Connected device (4 available)
    • Oleksandr’s iPhone (mobile)     •
      00008130-0010642A3C13803A
      • ios          • iOS 18.2 22C5142a
    • John’s iPhone (mobile)          •
      ed8ce3983570a6e0b115365d11866d2b99868735
      • ios          • iOS 15.8.3 19H386
    • macOS (desktop)                 • macos
      • darwin-arm64 • macOS 15.1.1 24B2091
      darwin-arm64
    • Mac Designed for iPad (desktop) •
      mac-designed-for-ipad
      • darwin       • macOS 15.1.1 24B2091
      darwin-arm64

[✓] Network resources
    • All expected network resources are
      available.

### Version

8.10.1

### Steps to Reproduce

1. Setup Error Session Replay
2. Set `experimental.replay.maskAllText = true`
3. Widget uses method to get the string:
```
Text(
    getLastMessage(),
```
4. Throw an error

### Expected Result

All text is masked

### Actual Result

Text is not masked
![Image](https://github.com/user-attachments/assets/f67bc719-42bc-4590-884c-a768c2cb9b00)

### Are you willing to submit a PR?

None

**Comment by buenaflor** [comment]
hi, we'll look into it

**Comment by vaind** [comment]
Hey @ozalisky thanks for reaching out. Can you please provide a reproducible example? I couldn't reproduce this with the info in the description.

**Comment by vaind** [comment]
I've reproduced the issue and a fix is coming in #2472
