### ISSUE TITLE
Session replay not working without native integration

### ISSUE THREAD

**Issue by datoutwo** [getsentry/sentry-dart#2458]
### Platform

Flutter Mobile iOS, Flutter Mobile Android

### Obfuscation

Enabled

### Debug Info

Disabled

### Doctor

[✓] Flutter (Channel stable, 3.24.3, on macOS 15.0 24A335 darwin-arm64, locale en-DE)
    • Flutter version 3.24.3 on channel stable 
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (3 months ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

### Version

8.9.0

### Steps to Reproduce

Enable replay and not working. https://docs.sentry.io/platforms/flutter/session-replay/ 

### Expected Result

Enable replay and should work 

### Actual Result

No sentry session replay result. 

### Are you willing to submit a PR?

None

**Comment by buenaflor** [comment]
hey how does your init config look like

**Comment by vaind** [comment]
Also please make sure to try with the latest version (currently https://pub.dev/packages/sentry_flutter/versions/8.11.0-beta.2)

**Comment by datoutwo** [comment]
Hi @buenaflor  
This is the initial code of sentry 
``` dart
Future<void> call(String dsn, FutureOr<void> Function() runner) async {
  await SentryFlutter.init(
    (options) {
      options
        ..dsn = dsn
        ..autoInitializeNativeSdk = false
        ..beforeSend = beforeSend
        ..tracesSampleRate = 0.1;
      options.experimental.replay.sessionSampleRate = 1.0;
      options.experimental.replay.onErrorSampleRate = 1.0;
    },
    appRunner: runner,
  );
}

FutureOr<SentryEvent?> beforeSend(SentryEvent event, Hint hint) async {
  // info and warning events should not be converted
  if (event.level != SentryLevel.error && event.level != SentryLevel.fatal) {
    return event;
  }
  final throwable = event.throwableMechanism;
  if (throwable is ThrowableMechanism) {
    final isHandled = throwable.mechanism.handled ?? false;
    return isHandled ? event.copyWith(level: SentryLevel.error) : event;
  } else {
    return event;
  }
}
``` 

Do we have to update to the latest one? The document mentioned it supports in 8.9.0

**Comment by vaind** [comment]
>         ..autoInitializeNativeSdk = false

Why do you disable this and how do you init the native SDK then? Replay relies on the native SDK

**Comment by datoutwo** [comment]
Our project is migrating to Flutter but still have native and flutter using in the same time, this is the init for iOS part.  
iOS sentry version is 8.36.0 which is also fit the [pre-requisites](https://docs.sentry.io/platforms/apple/guides/ios/session-replay/#pre-requisites)
``` Swift
SentrySDK.start { options in
    let performanceRate = performanceTraceRate()
    options.dsn = sentryDSN
    options.tracesSampleRate = performanceRate as NSNumber?
    options.environment = environment
    options.enableAppHangTracking = enableSentryHangAnalysis()
    options.debug = true
    options.experimental.sessionReplay.onErrorSampleRate = 1.0
    options.experimental.sessionReplay.sessionSampleRate = 1.0
}

**Comment by vaind** [comment]
I see what the problem is. Starting native separately doesn't actually achieve the same thing. The Flutter SDK comes with quite a bit of "glue" code to integrate with the native SDK and if you launch the native SDK yourself directly in native, this glue code doesn't come into play. I am not sure it's feasible to try and make this work in your situation. You'd need adapt the binding code to your situation and init procedures:
- dart parts: https://github.com/getsentry/sentry-dart/tree/main/flutter/lib/src/native
- native parts: https://github.com/getsentry/sentry-dart/tree/main/flutter/ios/Classes

Plus there would likely need to be changes in the Flutter SDK to allow you to plug in your custom code.

**Comment by datoutwo** [comment]
Please correct me if I'm wrong.  
So, if we enable the native `autoInitializeNativeSdk` and not trigger SentrySDK in native. 
This should `glue` automatically?

**Comment by vaind** [comment]
Really hard to tell because I don't know your exact setup, which as you're saying is not a typical Flutter app, but yes, that's the idea.

**Comment by buenaflor** [comment]
should we document this as a limitation?

**Comment by vaind** [comment]
> should we document this as a limitation?

Maybe worth adding but not related to replay because it applies generally to the Flutter SDK. Many of the features require the native integration so yeah we should probably mention together with https://docs.flutter.dev/add-to-app

**Comment by buenaflor** [comment]
👍 

> but not related to replay because it applies generally to the Flutter SDK

do you know which other features don't work properly when initializing the native SDK manually?

**Comment by vaind** [comment]
I'd say anything relying on https://github.com/getsentry/sentry-dart/blob/main/flutter/lib/src/native/sentry_native_binding.dart

e.g. native breadcrumbs and contexts sync, symbolication of obfuscated apps, profiling, app hang tracking, etc

**Comment by datoutwo** [comment]
We will try this future again when we fully migrate to Flutter, thanks for the speedy reply.

**Comment by vaind** [comment]
Followup issue to update docs is #2466

Closing this one as it's currently not planned to support session replay without native integration
