### ISSUE TITLE
Sentry configureScope in flutter is throwing Error in the 'configureScope' callback.

### ISSUE THREAD

**Issue by ganeshrvel** [getsentry/sentry-dart#246]
1. Please describe the issue and how to reproduce it, or link to a small reproducible application:

I am trying to setup sentry for flutter and while configuring the configureScope it throws 
```shell
[error] Error in the 'configureScope' callback.
```

Code:

`sentry_flutter: ^4.0.0`

main.dart:
```dart
import 'package:sentry_flutter/sentry_flutter.dart';
  await SentryFlutter.init((options) {
    options.dsn = ServiceKeys.SENTRY_DSN;
    options.useFlutterBreadcrumbTracking();
    options.useNativeBreadcrumbTracking();
  });
```

log.dart
```dart
    import 'package:sentry_flutter/sentry_flutter.dart';

    Sentry.configureScope((scope) => scope
      ..setTag('App version', '1.1.1+1')
      ..user = User(
              id: '1234',
              email: 'abc@xyz.com',
            );

    Sentry.captureException(
      _errorBody,
      stackTrace: stackTrace,
    );
```

Interestingly, the errors aren't showing up in the sentry dashboard when I use sentry_flutter package, but when I use the sentry package, instead, the exceptions are getting logged and the `configureScope` works perfectly alright.

What do I do?

2. Include the output of the command `flutter doctor` below:

```sh
[✓] Flutter (Channel stable, 1.22.3, on Mac OS X 10.15.6 19G73, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version
    29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Connected device (1 available)
```

**Comment by marandaneto** [comment]
@ganeshrvel thanks for raising this.

I just tested it (stable and beta) and it worked out.

You're not passing the `appRunner` to `SentryFlutter.init` which is not mandatory but recommended, could you try using it just to test it out?

Edit: I've tried it without the `appRunner` and it worked out as well.

Also, you are doing:

```
options.useFlutterBreadcrumbTracking();
options.useNativeBreadcrumbTracking();
```

you need to choose one or the other, both don't make sense, but this should not cause the issue I guess.

**Comment by ueman** [comment]
Sidenote:
```
options.​useFlutterBreadcrumbTracking​();
options.​useNativeBreadcrumbTracking​();
```
Those two options aren't designed to be used together. They disable each other. 
See the docs at https://pub.dev/documentation/sentry_flutter/latest/sentry_flutter/SentryFlutterOptions/useFlutterBreadcrumbTracking.html and https://pub.dev/documentation/sentry_flutter/latest/sentry_flutter/SentryFlutterOptions/useNativeBreadcrumbTracking.html

**Comment by marandaneto** [comment]
@ganeshrvel where are you placing the `SentryFlutter.init` and `Sentry.configureScope`? which App's scope/lifecycle?

I invite you to take a look at our docs https://docs.sentry.io/platforms/flutter/

**Comment by ganeshrvel** [comment]
@marandaneto 
`SentryFlutter.init` is set in the main.dart file.
I am setting the userid, email and extras using `Sentry.configureScope` just before `Sentry.captureException` is called. 

Are there any better way of doing it? I would want to attach the userId and email to sentry logs

**Comment by marandaneto** [comment]
@ganeshrvel you just need to call them after `SentryFlutter.init`, I copied and pasted your code snippets in my sample app and they worked out, there's something fishy in your environment or you are setting up it wrongly.

would you mind sharing a repro sample on GH? So I can debug it myself.

**Comment by ganeshrvel** [comment]
Sure, will setup a sample repo.

Even after using initializing the `MyApp()` using `appRunner` as `appRunner: () => runApp(MyApp()),` I am still getting the `Error in the 'configureScope' callback.` error.
I just noticed that, in our app, the helper function to capture the exceptions resides within a singleton class.

Something like this:
```dart
@lazySingleton
class CrashesService {
  CrashesService();

  void capture({
    @required String title,
    @required dynamic error,
  }) {
    Sentry.configureScope((scope) =>
    scope
      ..setTag('App version', '1.1.1+1')
      ..user = User(
        id: '1234',
        email: 'abc@xyz.com',
      ));

    Sentry.captureException(
      _errorBody,
      stackTrace: stackTrace,
    );
  }
}

```

I am using `injectable` and `get_it` packages to create this singleton class.


The error reporting works just fine if I use the sentry package instead of the sentry_flutter package

**Comment by marandaneto** [comment]
cool, I will wait for the sample repo, thanks.

**Comment by marandaneto** [comment]
@ganeshrvel did you manage to get it working or creating a sample repo? thanks

**Comment by ganeshrvel** [comment]
@marandaneto It is working now. 

Btw, is it possible to send 'extras' along with each exception?
I can attach extras in `Sentry.configureScope` but this will add the extras in the global scope. I want to send some extra information along with each exception that we send to sentry.
How can I get this done?

**Comment by marandaneto** [comment]
@ganeshrvel would you mind sharing with us what was the issue? so if somebody else is having the same issue, they could just learn from this issue :)

**Comment by marandaneto** [comment]
> Btw, is it possible to send 'extras' along with each exception?
> I can attach extras in `Sentry.configureScope` but this will add the extras in the global scope. I want to send some extra information along with each exception that we send to sentry.
> How can I get this done?

use `captureEvent` instead:

```
  // build the event with the throwable and any other field, like extra
  // the event extra will be merged along with the extra from the global scope
  final event = SentryEvent(
    throwable: ArgumentError('test'),
    extra: ['a': 'b']
  );
  // the error stack trace
  final st = StackTrace();
  // capture the event
  Sentry.captureEvent(
    event,
    stackTrace: st,
  );
```

**Comment by ganeshrvel** [comment]
> @ganeshrvel would you mind sharing with us what was the issue? so if somebody else is having the same issue, they could just learn from this issue :)


Initially, I had declared Sentry as a singleton which kind of messed up the scope. 

Something like: 


```dart
final _sentryDi = getIt<Sentry>();

_sentryDi.configureScope((scope) =>
    scope
      ..setTag('App version', '1.1.1+1')
      ..user = User(
        id: '1234',
        email: 'abc@xyz.com',
      ));

    _sentryDi.captureException(
      _errorBody,
      stackTrace: stackTrace,
    );

```

To fix the issue I just had to remove the dependency injection and call the method directly.
