### ISSUE TITLE
FormatException: getCurrentStackTrace throws inside the package

### ISSUE THREAD

**Issue by PcolBP** [getsentry/sentry-dart#2468]
### Platform

Flutter Mobile Android

### Obfuscation

Enabled

### Debug Info

Enabled

### Doctor

[✓] Flutter (Channel stable, 3.24.5, on macOS 15.1.1 24B91 darwin-arm64 (Rosetta), locale en-US)
    • Flutter version 3.24.5 on channel stable at /Users/piotrbobinski/fvm/versions/3.24.5
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision dec2ee5c1f (4 weeks ago), 2024-11-13 11:13:06 -0800
    • Engine revision a18df97ca5
    • Dart version 3.5.4
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/piotrbobinski/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16B40
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)

[✓] VS Code (version 1.94.2)
    • VS Code at /Users/piotrbobinski/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.102.0

[✓] Connected device (4 available)            
    • Piotr’s iPhone (mobile)         • 00008120-001170211AF0201E • ios            • iOS 17.7.1 21H216
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 15.1.1 24B91 darwin-arm64 (Rosetta)
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 15.1.1 24B91 darwin-arm64 (Rosetta)
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 131.0.6778.109

[✓] Network resources
    • All expected network resources are available.

• No issues found!

### Version

8.9.0

### Steps to Reproduce

None

### Expected Result

currentStackTrace does not throw

Include null stacktrace in case if throw? 

### Actual Result

currentStackTrace did throw
![Image](https://github.com/user-attachments/assets/004ee5ff-7f65-4b1d-853b-b8e4edb38c75)
![Image](https://github.com/user-attachments/assets/e6e7034a-e033-469c-95b3-83f148bc2b30)

```

FormatException: FormatException: Unexpected character (at character 1)
a0S2rkuaR3CJdj098N3nKucFYVD0tkkByG5DQU5oFzP6OBBUu/gOf80HSl15d8/R9zUBaToKvKo...
^
  base.apk            0x71dc051c7c getCurrentStackTrace (stacktrace_utils.dart:10)
  base.apk            0x71dc051c7c OnErrorIntegration.call.<T> (on_error_integration.dart:82)
  base.apk            0x71dc0aeea8 PlatformDispatcher._dispatchError (platform_dispatcher.dart:1318)
  base.apk            0x71dbc83ac8 _onError (hooks.dart:288)
  base.apk            0x71dbc83b04 _onError
```

### Are you willing to submit a PR?

No

**Comment by buenaflor** [comment]
Hey this is not a crash in the SDK, but this issue is fixed/improved in https://github.com/getsentry/sentry-dart/pull/2351

Read [this for more context](https://github.com/getsentry/sentry-dart/issues/2268#issuecomment-2406038837)

The fix is currently out for `8.11.0-beta.2` and will also be part of `8.11.0` soon
