### ISSUE TITLE
Generic class names

### ISSUE THREAD

**Issue by vanfresh** [getsentry/sentry-dart#250]
Version 4.0.1 is not user friendly.  A lot generic class names such as App and Message is taken by Sentry and will show an _import conflict_ when imported.  These generic class names should not be taken up by Sentry.

**Comment by marandaneto** [comment]
@vanfresh thanks for that, besides `App` and `Message`, do you see any other class that might conflict?

https://github.com/getsentry/sentry-dart/tree/main/dart/lib/src/protocol

**Comment by marandaneto** [comment]
@vanfresh would you mind sharing with us if there are more class names that would conflict with your experience? so we do the renaming at once, thanks.

**Comment by Jhellsten** [comment]
One that I noticed was **User**

**Comment by bruno-garcia** [comment]
I added Sentry's HttpClient for crumbs and when I imported sentry it conflicted with `Request` class.
Worth changing that on the next major too.

**Comment by marandaneto** [comment]
@ueman I guess it'd make sense to work on this PR too along with the null safety bits, as its a breaking change, so we don't need to bump a major twice :)

**Comment by ueman** [comment]
Yeah definitely
