### ISSUE TITLE
CURL: Required feature AsynchDNS is not found

### ISSUE THREAD

**Issue by kjxbyz** [getsentry/sentry-dart#2504]
### Platform

Flutter Desktop Linux

### Obfuscation

Disabled

### Debug Info

Disabled

### Doctor

```
[✓] Flutter (Channel stable, 3.27.0, on Ubuntu 22.04.5 LTS 6.5.0-1025-azure, locale C.UTF-8)
    • Flutter version 3.27.0 on channel stable at /opt/hostedtoolcache/flutter/stable-3.27.0-x64
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 8495dee1fd (6 days ago), 2024-12-10 14:23:[39](https://github.com/picguard/picguard/actions/runs/12350582872/job/34463750271#step:6:40) -0800
    • Engine revision 83bacfc525
    • Dart version 3.6.0
    • DevTools version 2.[40](https://github.com/picguard/picguard/actions/runs/12350582872/job/34463750271#step:6:41).2

[!] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /usr/local/lib/android/sdk
    • Platform android-35-ext14, build-tools 35.0.0
    • ANDROID_HOME = /usr/local/lib/android/sdk
    • ANDROID_SDK_ROOT = /usr/local/lib/android/sdk
    ✗ Android SDK file not found: adb.
    • Try re-installing or updating your Android SDK,
      visit https://flutter.dev/to/linux-android-setup for detailed instructions.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 14.0.0-1ubuntu1.1
    • cmake version 3.31.2
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/to/linux-android-setup for detailed instructions).

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 22.04.5 LTS 6.5.0-1025-azure
    • Chrome (web)    • chrome • web-javascript • Google Chrome 131.0.6778.139

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

### Version

8.11.1

### Steps to Reproduce

8.10.x can be built successfully

### Expected Result

8.11.x can be built successfully

### Actual Result

```
Building Linux application...                                   
CMake Error at /usr/local/share/cmake-3.31/Modules/FindCURL.cmake:1[9](https://github.com/picguard/picguard/actions/runs/12350582872/job/34463750271#step:8:10)7 (message):
  CURL: Required feature AsynchDNS is not found
Call Stack (most recent call first):
  /home/runner/work/picguard/picguard/build/linux/x64/release/_deps/sentry-native-src/CMakeLists.txt:290 (find_package)
```

### Are you willing to submit a PR?

None

**Comment by vaind** [comment]
v8.11 added Linux native error & obfuscation support (https://github.com/getsentry/sentry-dart/pull/2431)

I believe installing `libcurl4-openssl-dev` should resolve the issue.

**Comment by kjxbyz** [comment]
It works for me. Thank you!

**Comment by Andro999b** [comment]
Can this be disabled?

**Comment by vaind** [comment]
> Can this be disabled?

As the error is coming from compiling the native crash handler, yes. It's now disabled by default since [v8.11.2](https://github.com/getsentry/sentry-dart/blob/main/CHANGELOG.md#8112). The default will switch back on in a next major release.

**Comment by NikitaPnch** [comment]
Hi! I have the same problem, but on the AlmaLinux 8.10 (Red Hat).

curl --version returns
Feature: AsynchDNS IDN IPv6 ...

What i do wrong?

**Comment by vaind** [comment]
> Hi! I have the same problem, but on the AlmaLinux 8.10 (Red Hat).
> 
> curl --version returns Feature: AsynchDNS IDN IPv6 ...
> 
> What i do wrong?

1. what version fo the sentry-flutter SDK are you using?
2. `curl` binary is different than `libcurl` - libraries used to compile sentry-native and, transitively, sentry-flutter. Have you tried `sudo dnf -y install libcurl-devel`?

**Comment by NikitaPnch** [comment]
> > Hi! I have the same problem, but on the AlmaLinux 8.10 (Red Hat).
> > curl --version returns Feature: AsynchDNS IDN IPv6 ...
> > What i do wrong?
> 
>     1. what version fo the sentry-flutter SDK are you using?
> 
>     2. `curl` binary is different than `libcurl` - libraries used to compile sentry-native and, transitively, sentry-flutter. Have you tried `sudo dnf -y install libcurl-devel`?

Hi, i use sentry_flutter sentry_flutter: ^8.9.0 sentry_dio: ^8.9.0 sentry_drift: ^8.10.1

`sudo dnf -y install libcurl-devel`

[cgp@vbox cg_app]$ sudo dnf -y install libcurl-devel
[sudo] password for cgp: 
AlmaLinux 8 - BaseOS                                                            6.5 kB/s | 3.8 kB     00:00    
AlmaLinux 8 - BaseOS                                                            6.7 MB/s |  19 MB     00:02    
AlmaLinux 8 - AppStream                                                         786  B/s | 4.3 kB     00:05    
AlmaLinux 8 - AppStream                                                         7.5 MB/s |  17 MB     00:02    
AlmaLinux 8 - Extras                                                            7.0 kB/s | 3.3 kB     00:00    
AlmaLinux 8 - Extras                                                             26 kB/s |  14 kB     00:00    
AlmaLinux 8 - PowerTools                                                        8.1 kB/s | 4.2 kB     00:00    
AlmaLinux 8 - PowerTools                                                        4.6 MB/s | 4.4 MB     00:00    
Visual Studio Code                                                              7.8 kB/s | 1.5 kB     00:00    
Visual Studio Code                                                              5.8 MB/s | 6.8 MB     00:01    
Package libcurl-devel-7.61.1-34.el8_10.3.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!

if i use flutter run got error

CMake Error at /usr/share/cmake/Modules/FindCURL.cmake:176 (message):
  CURL: Required feature AsynchDNS is not found
Call Stack (most recent call first):
  /home/cgp/cg_app/build/linux/x64/debug/_deps/sentry-native-src/CMakeLists.txt:301 (find_package)


curl --version
curl 7.61.1 (x86_64-redhat-linux-gnu) libcurl/7.61.1 OpenSSL/1.1.1k zlib/1.2.11 brotli/1.0.6 libidn2/2.2.0 libpsl/0.20.2 (+libidn2/2.2.0) libssh/0.9.6/openssl/zlib nghttp2/1.33.0
Release-Date: 2018-09-05
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz brotli TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL

**Comment by vaind** [comment]
Firstly, you specify ^8.9.0, but we can't tell just from that dependency rule which version you're actually using (it depends on the time you've check last updated deps or checked out the project). The latest version on v8 is 8.14.1. Updating to the latest version should resolve your issue for now, because v8.11.2 disabled the sentry-native crash handler by default.

I'm saying "for now" because with v9, i.e. the next major version, we'll enable it back on. If you'd like to get support for native crashes, your development environment would need to be able to compile https://github.com/getsentry/sentry-native
From my experience, Flutter doesn't do a good job at showing the whole picture with underlying cmake builds. You could try following the first few steps in https://github.com/getsentry/sentry-native#building-and-installation
- `cmake -B build -DCMAKE_BUILD_TYPE=RelWithDebInfo`
- `cmake --build build --parallel`
and see if you can resolve the errors that come up - it should also fail with the same error.

If you don't care about native crash capture in your flutter apps, you can set `SENTRY_NATIVE_BACKEND=none` env var (still requires you to update to 8.11.2 or higher) and if you have that set explicitly, it should also work for sentry-flutter v9
