### ISSUE TITLE
Sentry cause crash on Android while build using `--target-platform=android-arm`

### ISSUE THREAD

**Issue by lanistor** [getsentry/sentry-dart#258]
_Platform:_
- [ ]  Dart
- [X]  Flutter Android
- [ ]  Flutter Web

_IDE:_
- [X]  VSCode
- [ ]  IntelliJ/AS
- [ ]  XCode
- [ ]  Other, which one?

_split-debug-info and obfuscate (Flutter Android or iOS) or CanvasKit (Flutter Web):_
- [ ]  Enabled
- [X]  Disabled

_Platform installed with:_
- [x] pub.dev
- [ ] GitHub

Output of the command `flutter doctor -v` below:
```
[✓] Flutter (Channel stable, 1.22.1, on Mac OS X 10.15.7 19H15, locale zh-Hans-CN)
    • Flutter version 1.22.1 at /Users/vifird/.fvm/versions/1.22.1-stable
    • Framework revision f30b7f4db9 (3 months ago), 2020-10-08 10:06:30 -0700
    • Engine revision 75bef9f6c8
    • Dart version 2.10.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn
```

The version of the SDK (See pubspec.lock):
**4.0.1**

---
I have the following issue:
Build apk on Android platform, debug works fine, `run --release` works fine, `build apk` works fine, build `flutter build apk --target-platform=android-arm` will cause crash while starting app.

We wanted the minimize size of package, so we need to specify the arch of package. 

**Steps to reproduce:**
- Add sentry_flutter package
- Init Sentry in flutter
- Run `flutter build apk --target-platform=android-arm`
- Install apk on Android (Huawei)
- Start app, then will crash.

**Actual result:**
- App crashed.

**Expected result:**
- Run normally.

**Comment by marandaneto** [comment]
@lanistor thanks for raising this.

Does it work if you don't add sentry_flutter?

I could reproduce it but it throws a `libflutter.so` error and not a Sentry one.

> 2020-12-26 11:30:27.192 9881-9881/? E/FlutterLoader: Flutter initialization failed.
>     java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dlopen failed: library "libflutter.so" not found

looks like an engine error.

**Comment by marandaneto** [comment]
ok I guess I know what it is, you are compiling a 32 bit apk using `android-arm`.
which device or emulator are you trying to run? also a 32 bit phone?

if you are trying to install and run on a 64 bit phone it won't work of course as the built apk is for 32 bit.
if your phone is 64 bit, use `android-arm64` instead.

Let me know if that works, thanks.

**Comment by lanistor** [comment]
@marandaneto My phone's CPU is `hisilicon kirin 955` of 64bit, and 32 bit  apks will be always able to run on 64 bit devices, this is compatible.
If i remove sentry_flutter, it works fine. I had lots of plugins.

**Comment by marandaneto** [comment]
@lanistor `sentry_flutter` has NDK support and depends on specific binary per CPU architecture, any library built for 32 bit won't work for 64 bit ootb.
Try to use `android-arm64` and test it out, I can only reproduce the issue if I install a 32 bit on a 64 bit phone, using the 64 bit apk works normally and App does not crash.

You can also open the APK using `Analyze APK` feature from Android studio and inspect the `lib` folder where the binaries `.so` files are.
You can see that even `libapp` and `libflutter` (not Sentry related) exist only under the compiled CPU architecture folder.

related to: https://github.com/flutter/flutter/issues/18494

**Comment by lanistor** [comment]
@marandaneto Finally i found a easy way to resolve it.

The problem is that: Sentry builds all abis apk, won't recognize `--target-platform=android-arm` argument, but flutter will, so these extra abis' folders don't have flutter's so file, this cause crash. here is the abis' folder show:
![error apk content show](https://raw.githubusercontent.com/lanistor/assets/master/imgs/sentry-build-abis-error.png)

To resolve it, just add `--split-per-abi`, to force split abis and only build for the target abi:
```
flutter build apk --target-platform=android-arm --split-per-abi
```

**Comment by bruno-garcia** [comment]
Sounds like worth going on our docs

**Comment by marandaneto** [comment]
not sure, `--target-platform` is a flutter CLI cmd only, not meant to be used by 3rd parties.
as stated on the flutter issue above, every SDK that supports NDK and has binaries per CPU arch. would have the same problem.

**Comment by bruno-garcia** [comment]
https://github.com/getsentry/sentry-docs/pull/2844

**Comment by lanistor** [comment]
@bruno-garcia @marandaneto 
Got another problem: what if want to build one package contains two archs?
Such as `flutter build apk --target-platform=android-arm,android-arm64`, in this case you cannot use `--split-per-abi`.

**Comment by bruno-garcia** [comment]
> @bruno-garcia @marandaneto
> Got another problem: what if want to build one package contains two archs?
> Such as `flutter build apk --target-platform=android-arm,android-arm64`, in this case you cannot use `--split-per-abi`.

I'm not sure what the question is, could you please clarify?

If you run `flutter build apk --target-platform=android-arm,android-arm64`, what's the output? Why can't you use `--split-per-abi`?

Maybe I'm missing the end goal. Is it to have 2 apk's one per ABI? If so, could you do:

```
flutter build apk --target-platform=android-arm --split-per-abi
flutter build apk --target-platform=android-arm64 --split-per-abi
```

**Comment by marandaneto** [comment]
@lanistor for that you'd probably need to customize your `build.gradle` file and `abiFilters` -> https://developer.android.com/ndk/guides/abis#gc
this isn't an SDK issue.
