### ISSUE TITLE
Get `Contexts` in Flutter

### ISSUE THREAD

**Issue by fzyzcjy** [getsentry/sentry-dart#264]
Hi thanks for the lib! I need the `Contexts` data (e.g. operating system, battery, resolution, ...) in Flutter. Thus, how can I get them?

I see `LoadContextsIntegration` says that, in Android, those contexts seems not to exist in the Flutter side but only exist in the native side. Thus, I wonder whether there are some easy ways to achieve my goal? Thanks!

**Comment by marandaneto** [comment]
@fzyzcjy please use always the issue template.

Android/iOS events should contain the Contexts data automatically, you don't need to do anything, capture an event and you'll get it for free, you should be using the https://pub.dev/packages/sentry_flutter package

If there's an issue, happy to reopen after filling the issue template, so I can dig with more information.
