### ISSUE TITLE
Release Health sessions are not marked `errored` on iOS

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dart#268]
Currently the iOS SDK isn't counting erroed sessions from Flutter. Since Flutter apps don't crash on unhandled errors, this is critical for Flutter apps.

**Comment by marandaneto** [comment]
Related to https://github.com/getsentry/sentry-cocoa/issues/861

**Comment by marandaneto** [comment]
It does mark a session as Crashed if the App crashes, the issue is related to Errored sessions, where the App won't crash but an uncaught exception happened, as a Flutter App. almost never crashes, this is critical.
