### ISSUE TITLE
Error: The argument type 'Registrar' can't be assigned to the parameter type 'BinaryMessenger'

### ISSUE THREAD

**Issue by ajbarry** [getsentry/sentry-dart#276]
_Platform:_
- [x]  Flutter Web

_IDE:_
- [x]  VSCode

_split-debug-info and obfuscate (Flutter Android or iOS) or CanvasKit (Flutter Web):_
- [x]  CanvasKit Disabled

_Platform installed with:_
- [x] pub.dev

<details>
<summary>flutter doctor -v</summary>

[✓] Flutter (Channel unknown, 1.24.0-10.2.pre, on macOS 11.1 20C69 darwin-x64, locale en-US)
    • Flutter version 1.24.0-10.2.pre at /usr/local/flutter
    • Framework revision 022b333a08 (9 weeks ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/adam/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (3 available)
    • Web Server (web)       • web-server                               • web-javascript • Flutter Tools
    • Chrome (web)           • chrome                                   • web-javascript • Google Chrome 87.0.4280.141

• No issues found!

</details>

The version of the SDK (See pubspec.lock):
**4.0.2**

---
I have the following issue:

Attempting to run a flutter web debug build on chrome, I get the following compile time failure:

```console
Launching lib/main.dart on Chrome in debug mode...
../../../.pub-cache/hosted/pub.dartlang.org/sentry_flutter-4.0.2/lib/src/sentry_flutter_web.dart:12:7: Error: The argument type 'Registrar' can't be assigned to the parameter type 'BinaryMessenger'.
 - 'Registrar' is from 'package:flutter_web_plugins/src/plugin_registry.dart' ('/usr/local/flutter/packages/flutter_web_plugins/lib/src/plugin_registry.dart').
 - 'BinaryMessenger' is from 'package:flutter/src/services/binary_messenger.dart' ('/usr/local/flutter/packages/flutter/lib/src/services/binary_messenger.dart').
      registrar,
      ^

Failed to compile application.
Exited (sigterm)
```

**Steps to reproduce:**
I encountered this issue after running `flutter pub upgrade` with `sentry_flutter: ^4.0.1` in pubspec.yaml ... pubspec.lock now has:
```yaml
  sentry_flutter:
    dependency: "direct main"
    description:
      name: sentry_flutter
      url: "https://pub.dartlang.org"
    source: hosted
    version: "4.0.2"
```

Pinning to exact version 4.0.1 is a work-around.

**Comment by marandaneto** [comment]
hey @ajbarry thanks for this, have you tried upgrading your flutter env? it should not be an issue on the latest beta

**Comment by ajbarry** [comment]
Hrm... ok. Thanks for the update. We're kinda pinned down to Flutter 1.24.0-10.2.pre due to a number of null-safety dependencies that Flutter 1.25+ has dragged in with it. I will lump this into our watchlist of issues we need to resolve ourselves.

Thanks again for letting me know. I'll close the issue.

**Comment by marandaneto** [comment]
@ajbarry https://github.com/getsentry/sentry-dart/releases/tag/4.0.5 we've reverted that change, so it'd not be an issue anymore

**Comment by ajbarry** [comment]
@marandaneto Thanks for the heads-up! We'll give it a spin.
