### ISSUE TITLE
Fix diagnosticLevel level from Dart to Cocoa

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-dart#277]
Context: https://github.com/getsentry/sentry-dart/pull/274/files#r560983525

Ideally done along with https://github.com/getsentry/sentry-cocoa/issues/911 but could also be done alone.

**Comment by marandaneto** [comment]
this is unblocked now, need to wait for a release though

**Comment by ueman** [comment]
This requires Sentry-Cocoa v7.x. It's currently in a prerelease.

**Comment by marandaneto** [comment]
> This requires Sentry-Cocoa v7.x. It's currently in a prerelease.

yep, let's wait for GA then and put this task in the freezer for a while.
