### ISSUE TITLE
Question: SentryEvent vs configureScope

### ISSUE THREAD

**Issue by mohammadne** [getsentry/sentry-dart#284]
hi,
I was studding sentry docs, but after that I can't figure out what is difference between `SentryEvent` and `configureScope`.

I hope you can clarify that,
thanks

**Comment by marandaneto** [comment]
well, `SentryEvent` is the data class that represents the JSON object sent over to Sentry.
https://develop.sentry.dev/sdk/event-payloads/

`configureScope` is a method that allows you to mutate the current Scope.
https://develop.sentry.dev/sdk/unified-api/#scope

so let's say that you add a tag to the Scope using the `configureScope` method.
https://docs.sentry.io/platforms/dart/enriching-events/tags/

Every captured exception will append the Scope's tag to the raised `SentryEvent`.
