### ISSUE TITLE
Add Attachment support

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dart#289]
The native SDKs (sentry-android, sentry-cocoa) added support to Attachments.

The [spec is in the develop docs](https://develop.sentry.dev/sdk/features/#attachments).

Thumbs up if this is the feature you've been waiting for.

**Comment by marandaneto** [comment]
If we want to make it working with the standalone sentry package, we need to migrate the transport with the `envelope` endpoint.
