### ISSUE TITLE
CocoaPods could not find compatible versions for pod - after updating to 4.0.2 of sentry_flutter

### ISSUE THREAD

**Issue by tajchert** [getsentry/sentry-dart#290]
_Platform:_
- [ ]  Dart
- [x]  Flutter Android or iOS
- [ ]  Flutter Web

_IDE:_
- [ ]  VSCode
- [ ]  IntelliJ/AS
- [ ]  XCode
- [x]  Other, Flutter Command line (pod install)

_split-debug-info and obfuscate (Flutter Android or iOS) or CanvasKit (Flutter Web):_
- [ ]  Enabled
- [x]  Disabled

_Platform installed with:_
- [x] pub.dev
- [ ] GitHub

Output of the command `flutter doctor -v` below:

Flutter (Channel stable, 1.22.6, on macOS 11.1 20C69 darwin-x64, locale en-PL)
    • Flutter version 1.22.6 at /Users/mtajchert/flutter/flutter
    • Framework revision 9b2d32b605 (11 days ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

The version of the SDK (See pubspec.lock):
**4.0.2**

---
I have the following issue:

After upgrading `sentry_flutter` to 4.0.2 (from 4.0.1) I have following error while executing `pod install`:
![image](https://user-images.githubusercontent.com/2962633/106674269-38b6fd80-65b3-11eb-8503-41908d48c084.png)
same error as a text for those searching for this stacktrace:
`
[!] CocoaPods could not find compatible versions for pod "Sentry":
  In snapshot (Podfile.lock):
    Sentry (= 6.0.12, ~> 6.0.10)

  In Podfile:
    sentry_flutter (from `.symlinks/plugins/sentry_flutter/ios`) was resolved to 0.0.1, which depends on
      Sentry (~> 6.1.3)

Specs satisfying the `Sentry (= 6.0.12, ~> 6.0.10), Sentry (~> 6.1.3)` dependency were found, but they required a higher minimum deployment target.`

putting `platform :ios, '14.4'` in my Podfile doesn't solve this.

My pubspec.lock:
`  sentry:
    dependency: transitive
    description:
      name: sentry
      url: "https://pub.dartlang.org"
    source: hosted
    version: "4.0.2"
  sentry_flutter:
    dependency: "direct main"
    description:
      name: sentry_flutter
      url: "https://pub.dartlang.org"
    source: hosted
    version: "4.0.2"`

If I downgrade `sentry_flutter` to 4.0.1 it fetches CocoaPods just fine.

**Steps to reproduce:**
Upgrade `sentry_flutter` to 4.0.2
Execute `pod install`

**Actual result:**
`CocoaPods could not find compatible versions for pod`

**Expected result:**
Success in fetching CocoaPods.

**Comment by marandaneto** [comment]
@tajchert thanks for reporting this.
have you tried upgrading to the latest stable version?

sentry_flutter https://pub.dev/packages/sentry_flutter 4.0.4
Cocoapods seems correct https://cocoapods.org/pods/Sentry -> 6.1.4

**Comment by tajchert** [comment]
Hi, yes.
There is same issue. Then I tried to downgrade to last stable version (we jumped from 4.0.0), and found out problem starts to appear in 4.0.2

**Comment by marandaneto** [comment]
<img width="1009" alt="Screenshot 2021-02-03 at 11 16 05" src="https://user-images.githubusercontent.com/5731772/106732624-36838c00-6611-11eb-8dd8-919d5357e6c1.png">

I've just created a fresh flutter ios App using `flutter create ios`, integrated the SDK and everything works.

maybe delete your `.lock` files, `flutter clean` and try again?

please set up a sample repo if the problem persists, thanks.

**Comment by tajchert** [comment]
I tried to update local pod as artifact [is available ](https://cocoapods.org/pods/Sentry#614)
Deleting Podfile + Podfile.lock and executing `pod repo update` (inside /ios) solved my issue. Sorry to bother.

**Comment by omidraha** [comment]
I have same issue.
I tried to delete these files:
```
ios/Podfile 
ios/Podfile.lock
```
And running this command (inside /ios):
```
$ pod repo update
```
Output:
```
Ignoring ffi-1.12.2 because its extensions are not built. Try: gem pristine ffi --version 1.12.2
Updating spec repo `trunk`

CocoaPods 1.10.1 is available.
To update use: `gem install cocoapods`

For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.10.1
```

Sentry version:
```
sentry_flutter: ^4.0.6
```

Full traceback:
```
Running pod install...
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Fetching external sources
    -> Fetching podspec for `Flutter` from `Flutter`
    -> Fetching podspec for `flutter_image_compress` from `.symlinks/plugins/flutter_image_compress/ios`
    -> Fetching podspec for `flutter_statusbarcolor` from `.symlinks/plugins/flutter_statusbarcolor/ios`
    -> Fetching podspec for `image_picker` from `.symlinks/plugins/image_picker/ios`
    -> Fetching podspec for `keyboard_visibility` from `.symlinks/plugins/keyboard_visibility/ios`
    -> Fetching podspec for `package_info` from `.symlinks/plugins/package_info/ios`
    -> Fetching podspec for `path_provider` from `.symlinks/plugins/path_provider/ios`
    -> Fetching podspec for `sentry_flutter` from `.symlinks/plugins/sentry_flutter/ios`
    -> Fetching podspec for `shared_preferences` from `.symlinks/plugins/shared_preferences/ios`
    -> Fetching podspec for `sqflite` from `.symlinks/plugins/sqflite/ios`
    -> Fetching podspec for `uni_links` from `.symlinks/plugins/uni_links/ios`
    -> Fetching podspec for `url_launcher` from `.symlinks/plugins/url_launcher/ios`
    -> Fetching podspec for `video_player` from `.symlinks/plugins/video_player/ios`
    -> Fetching podspec for `wakelock` from `.symlinks/plugins/wakelock/ios`
    -> Fetching podspec for `webview_flutter` from `.symlinks/plugins/webview_flutter/ios`

    Resolving dependencies of `Podfile`
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: all_pods_versions_5_d_c.txt exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/5/d/c/Mantle/2.1.6/Mantle.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: all_pods_versions_e_9_d.txt exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/e/9/d/SDWebImageWebPCoder/0.8.3/SDWebImageWebPCoder.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: all_pods_versions_c_7_9.txt exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/c/7/9/Reachability/3.2/Reachability.podspec.json exists! Returning local because checking is only perfomed in repo update
    [!] CocoaPods could not find compatible versions for pod "sentry_flutter":
      In Podfile:
        sentry_flutter (from `.symlinks/plugins/sentry_flutter/ios`)

    Specs satisfying the `sentry_flutter (from `.symlinks/plugins/sentry_flutter/ios`)` dependency were found, but they required a higher minimum deployment target.

    /usr/local/Cellar/cocoapods/1.9.1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:328:in `raise_error_unless_state'
    /usr/local/Cellar/cocoapods/1.9.1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:310:in `block in unwind_for_conflict'
    /usr/local/Cellar/cocoapods/1.9.1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:in `tap'
    /usr/local/Cellar/cocoapods/1.9.1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:in `unwind_for_conflict'
    /usr/local/Cellar/cocoapods/1.9.1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:684:in `attempt_to_activate'
    /usr/local/Cellar/cocoapods/1.9.1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:254:in `process_topmost_state'
    /usr/local/Cellar/cocoapods/1.9.1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:182:in `resolve'
    /usr/local/Cellar/cocoapods/1.9.1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in `resolve'
    /usr/local/Cellar/cocoapods/1.9.1/libexec/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:94:in `resolve'
    /usr/local/Cellar/cocoapods/1.9.1/libexec/gems/cocoapods-1.9.1/lib/cocoapods/installer/analyzer.rb:1065:in `block in resolve_dependencies'
    /usr/local/Cellar/cocoapods/1.9.1/libexec/gems/cocoapods-1.9.1/lib/cocoapods/user_interface.rb:64:in `section'
    /usr/local/Cellar/cocoapods/1.9.1/libexec/gems/cocoapods-1.9.1/lib/cocoapods/installer/analyzer.rb:1063:in `resolve_dependencies'
    /usr/local/Cellar/cocoapods/1.9.1/libexec/gems/cocoapods-1.9.1/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
    /usr/local/Cellar/cocoapods/1.9.1/libexec/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:410:in `analyze'
    /usr/local/Cellar/cocoapods/1.9.1/libexec/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:235:in `block in resolve_dependencies'
    /usr/local/Cellar/cocoapods/1.9.1/libexec/gems/cocoapods-1.9.1/lib/cocoapods/user_interface.rb:64:in `section'
    /usr/local/Cellar/cocoapods/1.9.1/libexec/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:234:in `resolve_dependencies'
    /usr/local/Cellar/cocoapods/1.9.1/libexec/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:156:in `install!'
    /usr/local/Cellar/cocoapods/1.9.1/libexec/gems/cocoapods-1.9.1/lib/cocoapods/command/install.rb:52:in `run'
    /usr/local/Cellar/cocoapods/1.9.1/libexec/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
    /usr/local/Cellar/cocoapods/1.9.1/libexec/gems/cocoapods-1.9.1/lib/cocoapods/command.rb:52:in `run'
    /usr/local/Cellar/cocoapods/1.9.1/libexec/gems/cocoapods-1.9.1/bin/pod:55:in `<top (required)>'
    /usr/local/Cellar/cocoapods/1.9.1/libexec/bin/pod:23:in `load'
    /usr/local/Cellar/cocoapods/1.9.1/libexec/bin/pod:23:in `<main>'

Error output from CocoaPods:
↳
    Ignoring ffi-1.12.2 because its extensions are not built. Try: gem pristine ffi --version 1.12.2

    [!] Automatically assigning platform `iOS` with version `8.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.


```

Any suggestion?

**Update**:

Fixed by uncommenting this line from [here](https://github.com/CocoaPods/CocoaPods/issues/7314):
```
platform :ios, '9.0'
```

**Comment by samthui** [comment]
The solution at the end of @omidraha works for me. :|
What a stupid mistake. I commented that line out earlier then keep trying to edit the platform version without uncommenting it =))))

**Comment by jimykhan** [comment]
same issue i am facing update cocoapods to 1.11 and try to make hope it will work for u.

**Comment by fuadreza** [comment]
I have the same issue.

In my case, 

I tried running 
```
$ pod repo update
```
but then it fails, and from here you should check what is the error. And from me it's using the wrong architecture. `have x86_64 but need arm64`.

So what I do is reinstall the cocoapods.

First uninstall all installed cocoapods packages:
```
$ gem list --local | grep cocoapods | awk '{print $1}' | xargs sudo gem uninstall
```
then I would try to install new version of cocoapods with brew
```
$ brew install cocoapods
```
after successfully install cocoapods. now I could run 
```
$ pod repo update
```
after that I would just run `pod install`
```
$ pod install
```

**Comment by sosualfred** [comment]
I just updated the ios platform from 10.0 to 11.0(current minimum supported ios version) in Podfile

```
# Uncomment this line to define a global platform for your project

platform :ios, '11.0'
```
