### ISSUE TITLE
Add a README to the Flutter sample

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dart#297]
The [`crashy` repo was archived](https://github.com/flutter/crashy) and points to the [Flutter example in this repository](https://github.com/getsentry/sentry-dart/tree/main/flutter/example).

We could add to [this README](https://github.com/getsentry/sentry-dart/blob/main/flutter/example/README.md) some information about running the sample and what to expect from it. Some images or gif are also great resources.

Some examples:

* [log4net](https://github.com/getsentry/sentry-dotnet/tree/main/samples/Sentry.Samples.Log4Net)
* [AWS Lambda](https://github.com/getsentry/sentry-dotnet/tree/main/samples/Sentry.Samples.Aws.Lambda.AspNetCoreServer)

**Comment by ueman** [comment]
We could also link to the Flutter example which is hosted via GitHub pages: https://getsentry.github.io/sentry-dart/

**Comment by bruno-garcia** [comment]
The link could be nice but the readme for a sample can be more educational (check the links in the description of this issue).

Very often ppl come to this repo without knowing what Sentry is, or just browse the sample trying to figure out what it does. A readme clarifying that and actually show casing the result of the sample (not just a stack of buttons) is a great way to get ppl interested in trying Sentry further, passed the passive browsing of this GH repo.
