### ISSUE TITLE
beforeSend filtering based on exception type does not work 

### ISSUE THREAD

**Issue by mnordine** [getsentry/sentry-dart#304]
_Platform:_
- [ ]  Dart
- [x] Dart Web
- [ ]  Flutter Android or iOS
- [ ]  Flutter Web

_Platform installed with:_
- [x] pub.dev
- [ ] GitHub

The version of the SDK (See pubspec.lock):
**4.0.5**

---
I have the following issue:

The following example straight from your documentation at https://docs.sentry.io/platforms/dart/configuration/filtering/ does not work:

```dart
import 'package:sentry/sentry.dart';

SentryEvent beforeSend(SentryEvent event, {dynamic hint}) {
  if (event.exception is DatabaseException) {
    event = event.copyWith(fingerprint: ['database-connection-error']);
  }
  return event;
}

Future<void> main() async {
  await Sentry.init((options) => options.beforeSend = beforeSend);
}
```

First of all, `event.exception is DatabaseException` will not work on any Dart platform, since `event.exception` is a `SentryException`. So this line will always be `false`. 

I have adapted the above code so we won't report any of our `ServerException`s.:

```dart
SentryEvent beforeSend(SentryEvent event, {hint}) {
  if (event.exception is ServerException) return null;
  return event;
}
```

As stated above, this will never work, on any Dart platform. You may say, "oh, `SentryException` has a `type` field, just compare that, like so:

```dart
SentryEvent beforeSend(SentryEvent event, {hint}) {
  if (event.exception.type == 'ServerException') return null;
  return event;
}
```

This will work on Dart VM, and perhaps AOT, but crucially, **will not** work using `dart2js`. It will minify the type, so it could be something like `minified:ht`, and the comparison will always return `false`. Perhaps the original exception should be stored on the `SentryException`? Then, this would work everywhere:

```dart
SentryEvent beforeSend(SentryEvent event, {hint}) {
  if (event.exception.original is ServerException) return null;
  return event;
}
```

**Comment by marandaneto** [comment]
@mnordine thanks for reporting, indeed it should be:

`if (event.throwable is ServerException)`

as `event.throwable` is the original exception, this code snippet is about using `fingerprint` and not dropping the event.
to drop the event, you need to return null, this is said in this sentence: https://docs.sentry.io/platforms/dart/configuration/filtering/#using-beforesend

> so you can use that to modify the event’s data or drop it completely (by returning null) based on custom logic and the data available on the event

we'll fix the docs :)

**Comment by mnordine** [comment]
Ah, I did not realize that. 

But when I try this, it still fails:

```dart
SentryEvent beforeSend(SentryEvent event, {hint}) {
  if (event.throwable is ServerException) return null;
  return event;
}
```

That's because `event.throwable` is a `ThrowableMechanism`.

I have to do this hack to get it to work:

```dart
SentryEvent beforeSend(SentryEvent event, {hint}) {
  if ((event.throwable as ThrowableMechanism).throwable is ServerException) return null;
  return event;
}
```

Not sure if this is relevant, but I'm using `AppRunner`, something like this:

```dart
await Sentry.init((config) => config
  ..dsn = '{my-dsn}'
  ..beforeSend = beforeSend,
  appRunner: appRunner,
);
```

**Comment by mnordine** [comment]
I've also confirmed the above workaround works with `dart2js`.

**Comment by marandaneto** [comment]
@mnordine true, sometimes the throwable is wrapped in a `ThrowableMechanism` class, we'll need to do like we do on Java
https://github.com/getsentry/sentry-java/blob/main/sentry/src/main/java/io/sentry/SentryBaseEvent.java#L101-L123

be aware that not always `event.throwable` is a `ThrowableMechanism`, so you should check that first or your cast will fail.

**Comment by mnordine** [comment]
Yep, I'm doing the check first 👍

**Comment by mnordine** [comment]
@marandaneto What was the fix here? Am I able to just do the following with `4.0.6`?

```dart
SentryEvent beforeSend(SentryEvent event, {hint}) {
  if (event.throwable is DatabaseException) return null;
  return event;
}
```

I see that is what the documentation now says: https://docs.sentry.io/platforms/dart/configuration/filtering/
