### ISSUE TITLE
`captureMessage` defaults to level `error`.

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dart#305]
I'm using `sentry.dart` 4.0.5 on a server app. I tried a `captureMessage` but the `level comes up as `error`:

`Sentry.captureMessage('test from pub client with crumbs');`

As a result the last crumb, which becomes the message itself, also has level `error`:

![image](https://user-images.githubusercontent.com/1633368/108631350-94004100-7437-11eb-94d4-13b23f6cba24.png)

[Sample on sentry.io](https://sentry.io/organizations/bruno-garcia/issues/2229790948/?project=1857674&query=is%3Aunresolved)

Also, note `was active: false`. Is this the correct behavior?

**Comment by marandaneto** [comment]
capture defaults to `SentryLevel.info` https://github.com/getsentry/sentry-dart/blob/main/dart/lib/src/hub.dart#L153
I'll check that, thanks

**Comment by marandaneto** [comment]
default param values are only taken if the param is not passed at all, as we need to pass the params from method to method, the para is always passed and most probably as `null`, this causes the issue, good catch.
