### ISSUE TITLE
Add BrowserTracing Integration

### ISSUE THREAD

**Issue by mnordine** [getsentry/sentry-dart#312]
For Dart web. For JavaScript, you can do something like:

```js
import * as Sentry from "@sentry/browser";
import { Integrations } from "@sentry/tracing";

Sentry.init({
  dsn: "https://examplePublicKey@o0.ingest.sentry.io/0",
  integrations: [new Integrations.BrowserTracing()],
});
```

Even though I see an `Integration` class, I only see the one, default integration. It's weird, because there's an `SentryOptions.addIntegration()`, but I don't see any integrations to add. 

Perhaps these integrations exist as separate packages, but I can't find them on `pub`.

**Comment by marandaneto** [comment]
We don't have it yet, not for Dart Web nor Flutter, Subscribe and upvote to #78, please

**Comment by mnordine** [comment]
Done.
