### ISSUE TITLE
Annoying plugin registrant warning in flutter web

### ISSUE THREAD

**Issue by gummicq** [getsentry/sentry-dart#314]
_Platform:_
- [ ]  Dart
- [ ]  Flutter Android or iOS
- [x]  Flutter Web

_IDE:_
- [x]  VSCode
- [ ]  IntelliJ/AS
- [ ]  XCode
- [ ]  Other, which one?

_split-debug-info and obfuscate (Flutter Android or iOS) or CanvasKit (Flutter Web):_
- [ ]  Enabled
- [x]  Disabled

_Platform installed with:_
- [x] pub.dev
- [ ] GitHub

Output of the command `flutter doctor -v` below:

[✓] Flutter (Channel beta, 1.26.0-17.6.pre, on macOS 11.2 20D64 darwin-x64, locale en-GB)
    • Flutter version 1.26.0-17.6.pre at /Users/gummi/development/flutter
    • Framework revision a29104a69b (7 days ago), 2021-02-16 09:26:56 -0800
    • Engine revision 21fa8bb99e
    • Dart version 2.12.0 (build 2.12.0-259.12.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/gummi/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 88.0.4324.182

• No issues found!

The version of the SDK (See pubspec.lock):
**4.0.4**

---
I have the following issue:

There is an annoying warning showing up in the generated_plugin_registrant.dart. This is caused by the plugin being referenced from within the src folder which the linter does not approve of. Please add the plugin to your main barrel file to remove this warning. As this file is autogenerated then this warning always appears again event if you try to ignore it.

Thanks
Gummi

<img width="710" alt="Screenshot 2021-02-23 at 10 34 10" src="https://user-images.githubusercontent.com/79209697/108831936-bc687680-75c2-11eb-8a79-4d2af6bb4bab.png">

**Comment by marandaneto** [comment]
@gummicq thanks for reporting this.

> This is caused by the plugin being referenced from within the src folder which the linter does not approve

is there a convention about this that I am unaware of? could you link me to the linter issue? what's the name of the rule?

> Please add the plugin to your main barrel file to remove this warning

the plugin class should have the implementation of the features, so it'd be normal to go under `src`, I'll check what other plugins do

**Comment by komritza** [comment]
Information about linter rule #346
