### ISSUE TITLE
Add Dart and Flutter to release-registry

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-dart#318]
This is a subpart of https://github.com/getsentry/sentry-dart/issues/285

@bruno-garcia how do you feel doing that? :) it's a quick-win

**Comment by bruno-garcia** [comment]
I can take this

**Comment by bruno-garcia** [comment]
https://github.com/getsentry/sentry-release-registry/pull/46

**Comment by bruno-garcia** [comment]
Packages already added with the right format:
https://github.com/getsentry/sentry-dart/blob/ec06863dea493366e746ca3b54c51558302ab0f8/flutter/lib/src/sentry_flutter.dart#L124
https://github.com/getsentry/sentry-dart/blob/dd380f283576cbf816c19b358aacf9f76bf4c963/dart/lib/src/sentry_options.dart#L212
