### ISSUE TITLE
Parse PlatformException and create a mixed stack trace with Dart and Java frames

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-dart#321]
Parse PlatformException and create a mixed stack trace with Dart and Java frames

<img width="1042" alt="Screenshot 2021-02-26 at 08 31 29" src="https://user-images.githubusercontent.com/5731772/109269806-5de30880-780d-11eb-99c9-797c151ad3bc.png">

We get this message as a String and not as a StackTrace object, so we don't parse it and log it as it is, but the exception itself has frames as you can see below in the image, ideally, we could parse it out and create a mixed stack trace with Dart and Java code, this would make the experience much better.
As you can see, the Java bits has ProGuard enabled, we need to take this into consideration.

**Comment by ueman** [comment]
See https://api.flutter.dev/flutter/services/PlatformException/stacktrace.html

We could also do this for other platforms if applicable.

**Comment by marandaneto** [comment]
yep, but that's the problem, it's a String, we need to convert to https://github.com/getsentry/sentry-dart/blob/main/dart/lib/src/protocol/sentry_stack_trace.dart so Sentry can display the stack trace nicely, and symbolicate if necessary (eg proguard), right now it displays as a message String

**Comment by bruno-garcia** [comment]
@lucas-zimerman did something similar on Xamarin with iOS stacktraces. Not sure symbolication was added there though

**Comment by marandaneto** [comment]
@ueman does the logic from https://github.com/ueman/stack_trace_parser would work here too?

**Comment by ueman** [comment]
> @ueman does the logic from https://github.com/ueman/stack_trace_parser would work here too?

Yeah, but I haven't tested how good it works:  https://gist.github.com/ueman/ceb1b261ebf5cc5d01fcfbb18c833476

On Android you can produce a `PlatformException` if you're passing something on a MethodChannel from Android to Dart which can't be serialized by the MethodChannel. No idea what other cases produce `PlatformException` with stacktraces and I also haven't looked into the other platforms yet.

**Comment by marandaneto** [comment]
@ueman Nice,I only found `throw PlatformException` [here](https://github.com/flutter/flutter/blob/299d484903c05182f28bccd6126c0f7384c49635/packages/flutter/lib/src/services/message_codecs.dart#L155).

Another example is if you cause an NPE exception on Java/Kotlin, Flutter wraps up into a PlatformException and does not crash the App.
Parsing the `PlatformException` should be specific per platform, indeed, nothing blocks us from adding 1 by 1 depending on priorities.

**Comment by marandaneto** [comment]
When doing this, consider addressing https://github.com/getsentry/sentry-dart/issues/518 which is making the native exception as a chained exception, so we have the Dart and the Native stack trace.

**Comment by ueman** [comment]
> When doing this, consider addressing https://github.com/getsentry/sentry-dart/issues/518 which is making the native exception as a chained exception, so we have the Dart and the Native stack trace.

That already works with the gist I've posted above.

**Comment by ueman** [comment]
@marandaneto I guess this issue can be closed now
