### ISSUE TITLE
User data missing in native crash report

### ISSUE THREAD

**Issue by vppysk** [getsentry/sentry-dart#324]
Thank you for providing sentry_flutter!

I'm using sentry_flutter 4.0.4

I want to get the user data of the app side in the native crash report.
Now, I have written the following code, but it does not work.

```
Future<void> initializeSentryService() async {
    SentryEvent beforeSend(SentryEvent event, {dynamic hint}) {
      return event.copyWith(user: User(username: 'test user', id: 'test id'));
    }

    await SentryFlutter.init(
      (SentryFlutterOptions options) => options
        ..dsn = 'https://XXXXX'
        ..beforeSend = beforeSend,
    );
  }
```

For errors on the flutter side, I can get following user data.
`User(username: 'test user', id: 'test id')`

However, in the case of a native crash, I will not get them.
Is there any way to make it work well for me?

Thank you!

**Comment by ueman** [comment]
This is because https://github.com/getsentry/sentry-dart/issues/194 is still missing.

**Comment by vppysk** [comment]
@ueman 
Sorry, I didn't check #194.

Thank you for your answer.
I hope that feature will be added!

**Comment by marandaneto** [comment]
I'll close it as a dup, thanks.
