### ISSUE TITLE
Incompatibility between http 0.13.0 and Sentry 4.0.6

### ISSUE THREAD

**Issue by renanbueno** [getsentry/sentry-dart#332]
_Platform:_
- [ ]  Dart
- [ ]  Flutter Android or iOS
- [X]  Flutter Web

_IDE:_
- [X]  VSCode
- [ ]  IntelliJ/AS
- [ ]  XCode
- [ ]  Other, which one?

_split-debug-info and obfuscate (Flutter Android or iOS) or CanvasKit (Flutter Web):_
- [ ]  Enabled
- [ ]  Disabled

_Platform installed with:_
- [X] pub.dev
- [ ] GitHub

Output of the command `flutter doctor -v` below:

[√] Flutter (Channel stable, 2.0.0, on Microsoft Windows [versÃ£o 10.0.19042.804], locale pt-BR)
    • Flutter version 2.0.0 at C:\Flutter
    • Framework revision 60bd88df91 (18 hours ago), 2021-03-03 09:13:17 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] VS Code (version 1.53.2)
    • VS Code at C:\Users\renan\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 88.0.4324.190
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 88.0.705.68

! Doctor found issues in 2 categories.

The version of the SDK (See pubspec.lock):
**4.0.6**

---
I have the following issue:

Incompatibility between Firebase Auth 1.0.0 and Sentry Flutter 4.0.6 due to:

Because firebase_auth 1.0.0 depends on firebase_auth_web ^1.0.0 and no versions of firebase_auth_web match >1.0.0 <2.0.0, firebase_auth 1.0.0 requires firebase_auth_web 1.0.0.

And because firebase_auth_web 1.0.0 depends on http_parser ^4.0.0 and http >=0.11.3+17 <0.13.0-nullsafety.0 depends on http_parser >=0.0.1 <4.0.0, firebase_auth 1.0.0 is incompatible with http >=0.11.3+17 <0.13.0-nullsafety.0.

And because sentry_flutter >=4.0.0 depends on sentry ^4.0.0 which depends on http ^0.12.0, firebase_auth 1.0.0 is incompatible with sentry_flutter >=4.0.0.

So, because client depends on both sentry_flutter 4.0.6 and firebase_auth 1.0.0, version solving failed.
pub get failed (1; So, because client depends on both sentry_flutter 4.0.6 and firebase_auth 1.0.0, version solving failed.)
exit code 1

Since http 0.13.0 implements Null Safety and no breaking changes, upgrading Sentry http to 0.13.0 should fix the issue if there is no problem with it.

**Steps to reproduce:**
- Use both Sentry Flutter and Firebase Auth on latest versions.

**Actual result:**
- Version solving failed.

**Expected result:**
- No version solving problems.

**Comment by krispypen** [comment]
http 0.13.0 uses Uri's everywhere instead of String for urls, so don't think it's just a pubspec change, but indeed, having the same issue here...

**Comment by ueman** [comment]
You can track the progress [on this issue](https://github.com/getsentry/sentry-dart/issues/247) and [this branch](https://github.com/getsentry/sentry-dart/tree/feat/null-safety).

**Comment by marandaneto** [comment]
dup of #247
