### ISSUE TITLE
Flutter version for http 0.13.0?

### ISSUE THREAD

**Issue by eripe970** [getsentry/sentry-dart#338]
Hey, 

Is there any version available for http: ^0.13.0? Getting some problems to use this library with a lot of other packages that need http 0.13.0.

**Comment by zeusbaba** [comment]
having similar issues as well...  
for example:  
```
sentry-4.0.6/lib/src/transport/http_transport.dart:56:12: 
Error: The argument type 'String' can't be assigned to the parameter type 'Uri'
```
as I know, this is related to `http 0.13.0`

**Comment by ueman** [comment]
This is already being worked on in https://github.com/getsentry/sentry-dart/issues/247 and  https://github.com/getsentry/sentry-dart/pull/335

**Comment by zeusbaba** [comment]
I just created PR #339 as a candidate fix, which I validated in my apps.

**Comment by marandaneto** [comment]
dup of ongoing work #247

**Comment by manish7flutterdev** [comment]
> 
> 
> having similar issues as well...
> for example:
> 
> ```
> sentry-4.0.6/lib/src/transport/http_transport.dart:56:12: 
> Error: The argument type 'String' can't be assigned to the parameter type 'Uri'
> ```
> 
> as I know, this is related to `http 0.13.0`

i had the same issue.....i think its http: ^0.13.0 package bug.....

try http: ^0.12.2 ...it will work

PS :  if you are using google font package make sure install  below version 2.0.0 .....else it will conflict with the previous http package

**Comment by marandaneto** [comment]
or use https://github.com/getsentry/sentry-dart/releases/tag/4.1.0-nullsafety.0

**Comment by manish7flutterdev** [comment]
thanks buddy..
