### ISSUE TITLE
Implement Envelope based transport

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dart#344]
In order to support [attachments](https://github.com/getsentry/sentry-dart/issues/289), and user [feedback](https://github.com/getsentry/sentry-dart/issues/215) without the need of a native layer (web, windows, linux) we need a transport in Dart that supports [envelopes](https://develop.sentry.dev/sdk/envelopes/).

**Comment by marandaneto** [comment]
there's no specs for rate-limiting yet but other SDKs already implemented it, eg Java https://github.com/getsentry/sentry-java/blob/main/sentry/src/main/java/io/sentry/transport/RateLimiter.java

**Comment by bruno-garcia** [comment]
There's also some info here: https://github.com/getsentry/develop/pull/171

**Comment by ueman** [comment]
It could be worth to look into [Darts convert library](https://api.dart.dev/stable/2.10.5/dart-convert/dart-convert-library.html) for the serialization process.

**Comment by marandaneto** [comment]
> It could be worth to look into [Darts convert library](https://api.dart.dev/stable/2.10.5/dart-convert/dart-convert-library.html) for the serialization process.

we already use `dart:convert` for ser/deser, but this is a Sentry spec that contains JSON or binary data within a file, so not really related to it

**Comment by marandaneto** [comment]
iOS is a bit split up:
https://github.com/getsentry/sentry-cocoa/blob/master/Sources/Sentry/SentryDefaultRateLimits.m
https://github.com/getsentry/sentry-cocoa/blob/master/Sources/Sentry/SentryEnvelopeRateLimit.m
https://github.com/getsentry/sentry-cocoa/blob/master/Sources/Sentry/SentryConcurrentRateLimitsDictionary.m
https://github.com/getsentry/sentry-cocoa/blob/master/Sources/Sentry/SentryRateLimitCategoryMapper.m
https://github.com/getsentry/sentry-cocoa/blob/master/Sources/Sentry/SentryRateLimitParser.m

**Comment by denrase** [comment]
Thanks for all the links and help!
