### ISSUE TITLE
CI complains about Flutter valid archies

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-dart#348]
Context https://github.com/getsentry/sentry-dart/pull/345#issuecomment-795726263

**Comment by marandaneto** [comment]
@denrase just reading your comment, tbh I'm not sure what to do either, we need to be able to run on the simulator, that's for sure.

**Comment by marandaneto** [comment]
when I run the pod lint locally, it works `sentry_flutter passed validation.`, Flutter v2.0.1

**Comment by denrase** [comment]
I also ran it locally and it failed for me. Flutter `2.0.1` and Dart `2.12.0`.

**Comment by marandaneto** [comment]
@denrase maybe you could have a look at it then, cus I can't reproduce it, I've opened a PR to test it out on CI but it didn't help :(

**Comment by denrase** [comment]
@marandaneto 

No luck so far, still get the error when building with `'VALID_ARCHS[sdk=iphonesimulator*]' => 'x86_64'`, as the `Flutter.xcframework` contains `ios-x86_64-simulator ios-armv7_arm64` slices, and somehow the matching between them fails. When i change the iphonesimulator valid archs to `ios-x86_64-simulator`, pod lint is successful, but I still have warnings:

```
 -> sentry_flutter (0.0.1)
    - NOTE  | xcodebuild:  note: Using new build system
    - NOTE  | xcodebuild:  note: Building targets in parallel
    - NOTE  | xcodebuild:  note: Using codesigning identity override: -
    - NOTE  | [iOS] xcodebuild:  note: Planning build
    - NOTE  | [iOS] xcodebuild:  note: Constructing build description
    - NOTE  | [iOS] xcodebuild:  warning: None of the architectures in ARCHS (arm64, x86_64, i386) are valid. Consider setting ARCHS to $(ARCHS_STANDARD) or updating it to include at least one value from VALID_ARCHS (ios-x86_64-simulator). (in target 'sentry_flutter' from project 'Pods')
    - NOTE  | [iOS] xcodebuild:  warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.4.99. (in target 'Flutter' from project 'Pods')
    - NOTE  | [iOS] xcodebuild:  warning: [CP] Unable to find matching .xcframework slice in 'Flutter/Flutter.xcframework Flutter framework ios-x86_64-simulator ios-armv7_arm64' for the current build architectures (arm64 x86_64 i386).
```

Also checked out  #349, it's the same either way.

Somewhere the matching between `x86_64` and `ios-x86_64-simulator` seems to fail. And Flutter versions below 2 seem to have the slices for `arm64 x86_64 i386` in the `Flutter.xcframework`, as the last warning is not displayed when setting the Flutter version to `1.22.4` in the podspec.

**Comment by marandaneto** [comment]
I see, well, I don't know what to do either, nothing about that (flutter repo)?

**Comment by marandaneto** [comment]
I commented out for now https://github.com/getsentry/sentry-dart/commit/82ef2abed5cf256b47aeb45f56dc2f51fa7843db
as it does change the functionality of the SDK anyway.

**Comment by ueman** [comment]
We should also add linting for the macOS podspec file.
