### ISSUE TITLE
Name conflict with custom class named `App`

### ISSUE THREAD

**Issue by ricbermo** [getsentry/sentry-dart#350]
_Platform:_
- [ ]  Dart
- [x]  Flutter Android or iOS
- [ ]  Flutter Web

_IDE:_
- [ ]  VSCode
- [ ]  IntelliJ/AS
- [ ]  XCode
- [x]  Other, which one? does it matter? (VIM)

_split-debug-info and obfuscate (Flutter Android or iOS) or CanvasKit (Flutter Web):_
- [ ]  Enabled
- [ ]  Disabled
- [x] no idea

_Platform installed with:_
- [x] pub.dev
- [ ] GitHub

Output of the command `flutter doctor -v` below:

[✓] Flutter (Channel stable, 1.22.6, on Mac OS X 10.15.7 19H2
    darwin-x64, locale es-419)
    • Flutter version 1.22.6 at /Users/ricbermo/.fluter-dev/flutter
    • Framework revision 9b2d32b605 (7 weeks ago), 2021-01-22 14:36:39
      -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[✓] Android toolchain - develop for Android devices (Android SDK version
    29.0.2)
    • Android SDK at /Users/ricbermo/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/ricbermo/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific
      functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (1 available)
    • iPhone 12 Pro Max (mobile) • 56045043-2EF2-4113-9E02-882CE17C1379
      • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)

! Doctor found issues in 1 category.

The version of the SDK (See pubspec.lock):
**4.0.6**

---
I have the following issue:
It looks like there's one class called `App` in `sentry_flutter` which may create a conflict if you also have an `App` class.

**Steps to reproduce:**
-Install flutter_sentry
-create an `App` class and use it in `runApp`

**Actual result:**
- 
![image](https://user-images.githubusercontent.com/2601363/110812724-dc03ce00-8255-11eb-8c31-900e90295918.png)

**Expected result:**
- compile success.

**Comment by marandaneto** [comment]
Dup #250
