### ISSUE TITLE
Null safety update prevents processors nulling out events

### ISSUE THREAD

**Issue by mjohnsullivan** [getsentry/sentry-dart#351]
We use the following processor to stop events being sent to Sentry in debug/development:

```dart
Future<void> initializeSentry(String release, String environment, String dsn,
        {FutureOr<void> Function() runApp, Transport transport}) =>
    Sentry.init(
      (options) => options
        ..dsn = dsn
        ..release = release
        ..environment = environment
        ..transport = transport ?? options.transport
        ..addEventProcessor(_noEventInDebug),
      appRunner: runApp,
    );

SentryEvent _noEventInDebug(SentryEvent event, {dynamic hint}) {
  return isInDebugMode || disableSentry ? null : event;
}
```

Prior to null safety this worked as expected, with this test passing:

```dart

class MockTransport extends Mock implements Transport {}

  test('No sentry events should be sent in debug mode', () async {
    expect(isInDebugMode, isTrue);
    expect(overrideDisableSentry, isNull);

    await initializeSentry('release', 'env', fakeDsn, transport: transport);

    expect(Sentry.isEnabled, isTrue);

    final event = SentryEvent();
    await Sentry.captureEvent(event);

    final callCount = verifyNever(
      transport.send(captureAny),
    ).callCount;

    expect(callCount, 0);
  });
```

However, when upgrading to null safety version of the package, this test now fails.

**Comment by marandaneto** [comment]
@mjohnsullivan thanks for reporting.

please update your issue with the issue template, so we can better understand your tooling.

why does it fail? if you run your App events still get sent?

for that, you don't even need an Event processor btw, you could simply use a beforeSend callback https://docs.sentry.io/platforms/dart/configuration/filtering/#using-beforesend

**Comment by mjohnsullivan** [comment]
Thanks for the quick reply. It fails on the verifyNever, in that an event gets sent when we expect it not to. In pre null-safety no event was sent; in null safety it looks like it now sends an event.

And thanks for pointing out the beforeSend function; I'll test that and update our code to use it.

**Comment by marandaneto** [comment]
I can confirm that, working on a fix, thanks
