### ISSUE TITLE
[bug] (with 1-line-of-code fix) the `hint` is not passed to processors

### ISSUE THREAD

**Issue by fzyzcjy** [getsentry/sentry-dart#355]
Hi thanks for the lib! The `hint` provided from `captureEvent` is not passed to processors. This can be solved by one line of code:

In https://github.com/getsentry/sentry-dart/blob/82ef2abed5cf256b47aeb45f56dc2f51fa7843db/dart/lib/src/sentry_client.dart#L72

Replace 

```
    preparedEvent = await _processEvent(
      preparedEvent,
      eventProcessors: _options.eventProcessors,
    );
```

with 

```
    preparedEvent = await _processEvent(
      preparedEvent,
      eventProcessors: _options.eventProcessors,
     hint:hint, //THIS!
    );
```

**Comment by marandaneto** [comment]
@fzyzcjy thanks, good catch btw :)

**Comment by fzyzcjy** [comment]
@marandaneto You are welcome! This one also released on Monday right? :)

**Comment by marandaneto** [comment]
> @marandaneto You are welcome! This one also released on Monday right? :)

yes
