### ISSUE TITLE
Basic Flutter package support for Desktop

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dart#362]
The `dart` package supports them all:
![image](https://user-images.githubusercontent.com/1633368/111191456-759ce980-858e-11eb-9fb7-1cde52135805.png)

`sentry_flutter` doesn't:

![image](https://user-images.githubusercontent.com/1633368/111191484-7e8dbb00-858e-11eb-8bb3-190705753bd8.png)

Probably a matter of adding the platforms here: https://github.com/getsentry/sentry-dart/blob/7ca0d10ca4985dbf928958e715bc695bfe1d3045/flutter/pubspec.yaml#L33-L41

To at least explicitly support it. Device context etc can come later.

**Comment by ueman** [comment]
Ideally this should be done together with #288 to get basic breadcrumb support out of the box.

**Comment by JigneshWorld** [comment]
These [`plus plugins`](https://github.com/fluttercommunity/plus_plugins) maintained by flutter community can help to add device or package context info by replacing currently used `package_info` plugin.


> Important: As of January 2021, the Flutter team is no longer accepting non-critical PRs for the original set of plugins in flutter/plugins, and instead they should be submitted in this project. You can read more about this announcement here. as well as in the Flutter 2 announcement blog post.

**Comment by ueman** [comment]
Links for reference: 
https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md#important-note
https://medium.com/flutter/whats-new-in-flutter-2-0-fe8e95ecc65

**Comment by bruno-garcia** [comment]
> These [`plus plugins`](https://github.com/fluttercommunity/plus_plugins) maintained by flutter community can help to add device or package context info by replacing currently used `package_info` plugin.
> 
> > Important: As of January 2021, the Flutter team is no longer accepting non-critical PRs for the original set of plugins in flutter/plugins, and instead they should be submitted in this project. You can read more about this announcement here. as well as in the Flutter 2 announcement blog post.

Yes plus plugins is the way to go.
Particularly on the next major bump, we should make the switch.
