### ISSUE TITLE
Documentation is not in sync with stable release

### ISSUE THREAD

**Issue by danilofuchs** [getsentry/sentry-dart#368]
_Platform:_
- [x]  Dart
- [x]  Flutter Android or iOS
- [ ]  Flutter Web

_Platform installed with:_
- [x] pub.dev
- [ ] GitHub

The version of the SDK (See pubspec.lock):
**4.0.6**

---
I have the following issue:

The official documentation for the `dsn` option states that using an empty DSN will disable the SDK.
This was implemented on version `4.1.0-nullsafety.0` and is not available on stable release. As a matter of fact, in stable, using `''` freezes the app (https://github.com/getsentry/sentry-dart/issues/326)

![image](https://user-images.githubusercontent.com/17657014/111328380-f3bfc580-864c-11eb-9269-bae81e6bf253.png)

**Comment by marandaneto** [comment]
@danilofuchs indeed, the bug is fixed, its been released as a prerelease because of major changes, the docs are correct, you could either wait a little bit or try the prerelease and give us feedback, thanks
