### ISSUE TITLE
App uses non certified ad SDK

### ISSUE THREAD

**Issue by hongfeiyang** [getsentry/sentry-dart#371]
I used Sentry in an app that's designed for kids, and Google is telling me that Sentry is a non-certified ad SDK and has been constantly rejecting my app. Is there any plan in the future to make this SDK compliant? I don't even know this SDK has ads feature...

**Comment by marandaneto** [comment]
@hongfeiyang this SDK isn't an ad SDK, also, we don't run ads at all, we are a crash reporting and we'll be scaling this, thanks for reporting.

**Comment by marandaneto** [comment]
@hongfeiyang a quick update, our legal team is already in contact with Google trying to figure this out

**Comment by hongfeiyang** [comment]
@marandaneto I know this is not an ad SDK, I am just shocked by the fact that google treats this as an ad SDK. Thanks for the update, please reply in this thread once this is approved by Google. My Flutter app's future depends on this 🙏

**Comment by derek-meeco** [comment]
I am also on the project with @hongfeiyang .. very frustrating; but it is hard to argue with the google play app review on behalf of Sentry.io; so I hope Sentry.io can self certify via this form: 
https://support.google.com/googleplay/android-developer/?p=adnet

For the record, here is the email from Google Play Developer Support:

`
Status: App not available on Google Play

I’ve reviewed your appeal request and found that your app still violates Google Play Policy. I’ve included details below about the specific issue with your app and what you can do to get your app back on Google Play.

Step 1: Fix the policy violation with your app, XXX app (xxx.xxx.xxx)

We have detected that your app includes non-certified ad SDKs and/or SDKs that are not approved for use in child-directed services. Any SDKs used in the app must be appropriate for use in child-directed services. Additionally, apps that solely target children must not contain any SDKs that are not approved for use in child-directed services, including ads SDKs. Apps in the Designed for Families program must only use ad SDKs that have certified their compliance with the Families Ads Program[1].

We have detected the use of Sentry SDK, which is not allowed in apps that are in the Families program. An ad SDK is not allowed if it has not self-certified its compliance with Play’s Families Ads Program (certified ad SDKs), or it is non-COPPA compliant per its own public documentation. Please note, the status of SDKs often changes and it is your responsibility to review documentation of all SDKs used in your app to ensure compliance with Families policies.

Please update your app to fix this issue. Before resubmitting your app for further review, please make sure to DEACTIVATE the non-compliant APK and increment the version number of the APK. Kindly note that all active APK versions need to be compliant.
`

REF: 
[1] https://support.google.com/googleplay/android-developer/answer/9283445

**Comment by marandaneto** [comment]
@derek-meeco as I said, we are already in contact with Google, unfortunately, we don't know what sort of trigger they have to detect this as an ad SDK.

We can't certify the SDK for a feature that we don't have, our SDKs are open-source, you are free to help us to figure out what's going on.

**Comment by derek-meeco** [comment]
@marandaneto self certifying a none existent feature is the easiest thing ever; you answer "no" to everything :) - sometimes you just gotta work within the system ;)

**Comment by victoriaSh** [comment]
Is there any news? I use "@sentry/react-native" in my app and got rejection too:

> "We have detected the use of Sentry SDK, which is not allowed in apps that are in the Families program"

**Comment by marandaneto** [comment]
no afaik, @mitsuhiko is in contact with Google, he will update us once there's news from their side.

**Comment by marandaneto** [comment]
we have an update, Apps that have been rejected due to the Sentry SDK are now free to submit again, thanks for the patience.

We're going to work on [docs](https://github.com/getsentry/sentry-docs/issues/3344) to be more specific about PII on our SDKs

**Comment by marandaneto** [comment]
https://docs.sentry.io/product/security/mobile-privacy/
