### ISSUE TITLE
CI should compile examples for Dart/Dart Web and Flutter

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-dart#374]
I guess this is a regression, we need to check it out

**Comment by ueman** [comment]
Could be done together with https://github.com/getsentry/sentry-dart/issues/334

**Comment by marandaneto** [comment]
I guess when I've added the `exclude` section to the `analysis_options`file, this kinda bypassed the build of the examples folder, its something we could check out, maybe just fixing the linting for the examples and removing that would already work, or, last case, we add a new Job to the CI that compiles the examples
