### ISSUE TITLE
Flutter Beta builds are broken on CI

### ISSUE THREAD

**Issue by ueman** [getsentry/sentry-dart#377]
_Platform:_
- [ ]  Dart
- [x]  Flutter Android or iOS
- [ ]  Flutter Web

See the following PRs: 
- https://github.com/getsentry/sentry-dart/pull/376
- https://github.com/getsentry/sentry-dart/pull/375
- https://github.com/getsentry/sentry-dart/pull/370

iOS complains about a missing Podfile on beta.
Android has a problem with references/imports in the MainActivity.kt

 flutter/flutter#78785

**Comment by marandaneto** [comment]
@ueman please prioritize this then, let me know if you need any help

**Comment by ueman** [comment]
I'm already on it

**Comment by ueman** [comment]
I think Flutter beta is broken.
On Android I also get errors similar to iOS.
```
/sentry-dart/flutter/example/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java:17: error: package io.sentry.flutter does not exist
    flutterEngine.getPlugins().add(new io.sentry.flutter.SentryFlutterPlugin());
/sentry-dart/flutter/example/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java:16: error: package io.flutter.plugins.packageinfo does not exist
    flutterEngine.getPlugins().add(new io.flutter.plugins.packageinfo.PackageInfoPlugin());
```

which is also from `GeneratedPluginRegistrant`.

But I have no idea why :(

**Comment by marandaneto** [comment]
> I think Flutter beta is broken.
> On Android I also get errors similar to iOS.
> 
> ```
> /sentry-dart/flutter/example/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java:17: error: package io.sentry.flutter does not exist
>     flutterEngine.getPlugins().add(new io.sentry.flutter.SentryFlutterPlugin());
> /sentry-dart/flutter/example/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java:16: error: package io.flutter.plugins.packageinfo does not exist
>     flutterEngine.getPlugins().add(new io.flutter.plugins.packageinfo.PackageInfoPlugin());
> ```
> 
> which is also from `GeneratedPluginRegistrant`.
> 
> But I have no idea why :(

if you create a sample project from scratch and add an Android/iOS plugin (eg packageinfo), does it compile for Android and iOS? using the beta channel obviously.
if they have changed the structure of eg Gradle or Pod files or something like that, it'd be broken and it'd need to be fixed, just a hunch here, maybe worth adding a comment to that Flutter issue about the broken Android build too

**Comment by ueman** [comment]
Creating a new Flutter project and just adding Sentry as a dependency from scratch works. I haven't looked into the differences yet, though.

**Comment by ueman** [comment]
https://github.com/flutter/flutter/issues/78785 was answered. Seems like an easy fix.
