### ISSUE TITLE
No logs (breadcrumbs) for C code, Android code and iOS code

### ISSUE THREAD

**Issue by fzyzcjy** [getsentry/sentry-dart#381]
Thanks for the lib!

Related to https://github.com/getsentry/sentry-dart/issues/380, I have crashs on my FFI c/c++ code, my android code and ios code. But they do not have breadcrumbs.

You know, breadcrumbs are very useful to understand what is happening and debug the issues.

It would be best if the breadcrumbs of *c/c++ and android and ios and flutter* can be all shared together.

**Comment by marandaneto** [comment]
@fzyzcjy thanks for reporting, indeed, this is a dup of https://github.com/getsentry/sentry-dart/issues/194 please upvote so we can prioritize.

**Comment by fzyzcjy** [comment]
@marandaneto Hmm a bit not that duplicate. My issue is about breadcrumbs :)

**Comment by marandaneto** [comment]
it is, see the issue's title, breadcrumbs sit in the Scope, and the Scope should be synced down to the native layers, that would solve the problem for good, instead of having an issue for each field set in the Scope (user, breadcrumbs, etc...)
