### ISSUE TITLE
Replace removed methods from sentry-cocoa with public APIs

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-dart#383]
Context: https://github.com/getsentry/sentry-cocoa/pull/1019

Still an alpha, so we can wait for GA.

**Comment by marandaneto** [comment]
@jennmueng create for RN :)

**Comment by ueman** [comment]
Dart has `Sentry.currentHub` too: https://github.com/getsentry/sentry-dart/blob/ff1bbe4a6f87d965b33cab9c74e74619097d90eb/dart/lib/src/sentry.dart#L29

**Comment by marandaneto** [comment]
yeah good catch, lets remove in the next major version too
