### ISSUE TITLE
During CI, publish iOS app to TestFlight

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dart#387]
This setup exists on `sentry-cocoa` and is useful to do some "manual testing" before a release without the need to build locally and run on a device.

A failed attempt here: https://github.com/getsentry/sentry-dart/pull/340

Potential to extra the work done on https://github.com/getsentry/sentry-cocoa into a git repo that can be added via gittree or submodule to be reused/maintained across repos. We'd like to see this in also with other repos such as Unity, Flutter, Cordova, React Native and Xamarin.

**Comment by denrase** [comment]
@kahest Someone would need to create the app with bundle id `io.sentry.flutter.example` and name `Sentry Flutter Example` on AppStore Connect, as I do not have the permissions to do so.

**Comment by denrase** [comment]
@kahest Any update here?

**Comment by kahest** [comment]
@denrase created with app id `io.sentry.flutter.sample` and name `Sentry Flutter Sample`

**Comment by denrase** [comment]
@buenaflor We sill need the PP in the match repo (if it was not added in the meantime), any update?
