### ISSUE TITLE
Debouncing of SentryWidgetsBindingObserver.didChangeMetrics.

### ISSUE THREAD

**Issue by ueman** [getsentry/sentry-dart#400]
_Platform:_
- [ ]  Dart
- [x]  Flutter Android or iOS
- [ ]  Flutter Web

_IDE:_
- [ ]  VSCode
- [ ]  IntelliJ/AS
- [ ]  XCode
- [ ]  Other, which one?

The version of the SDK (See pubspec.lock):
**5.0.0**

---

SentryWidgetsBindingObserver.didChangeMetrics gets called way too often. As seen in [this crash report](https://sentry.io/organizations/sentry-sdks/issues/2149575550/?query=is%3Aunresolved) it gets called way too much.

**Comment by marandaneto** [comment]
@ueman the linked issue does not have any breadcrumb with `device.screen` category, could you double-check, please?

**Comment by marandaneto** [comment]
I'd chose between `bug` or `enhancement` btw, it can't be both though, sounds like it does its job so maybe debouncing would be an enhancement to not make it too noisy

**Comment by ueman** [comment]
It is an older event of the same exception
https://sentry.io/organizations/sentry-sdks/issues/2149575550/events/0fb9c693eea84858b8b0a6986a7e16e6/?project=5428562

**Comment by marandaneto** [comment]
indeed, thanks, let's debouce it and take the last then, what would be a reasonable timeout for deboucing? 1-3s?

**Comment by ueman** [comment]
Yeah, that time span seems reasonable

**Comment by ueman** [comment]
On Linux this also seems to be a problem even without resizing the window:
https://sentry.io/share/issue/014e554f41e449298005bc120e1641da/
