### ISSUE TITLE
Read OS and device information in Dart code

### ISSUE THREAD

**Issue by ueman** [getsentry/sentry-dart#401]
In order to better support all the different platforms we need something like the `Enricher` from the dotnet guys:
https://github.com/getsentry/sentry-dotnet/blob/674627baf25e24eb2634443960adece3c25aab96/src/Sentry/Internal/Enricher.cs

It's also needed in order to not go through message channels after https://github.com/getsentry/sentry-dart/issues/344 is implemented and for platforms which have no native integration.

This way we can get all the environment, OS and device information.

There are a couple ways to get some of the information:

1. Dart's Platform class has some information (this would also work for non Flutter projects)
2. https://pub.dev/packages/device_info_plus

**Comment by marandaneto** [comment]
it's sort of a dup of https://github.com/getsentry/sentry-dart/issues/262
that issue is Web-specific, but the concept is pretty much the same

**Comment by ueman** [comment]
Oh yeah, I'll close this in favor of the other one.
