### ISSUE TITLE
Bump Sentry-Cocoa to v7

### ISSUE THREAD

**Issue by ueman** [getsentry/sentry-dart#404]
Once Sentry-Cocoa is v7 is GA we need to do the following things:

- [x] Use `SentrySDK.close()` instead of [this](https://github.com/getsentry/sentry-dart/blob/ff1bbe4a6f87d965b33cab9c74e74619097d90eb/flutter/ios/Classes/SwiftSentryFlutterPlugin.swift#L127-L133). See https://github.com/getsentry/sentry-cocoa/issues/934
- [x] https://github.com/getsentry/sentry-dart/issues/383
- [x] https://github.com/getsentry/sentry-dart/issues/379
- [x] https://github.com/getsentry/sentry-dart/issues/277

**Comment by marandaneto** [comment]
thanks for that @ueman
