### ISSUE TITLE
Remove `Sentry.currentHub` in v6.0.0

### ISSUE THREAD

**Issue by ueman** [getsentry/sentry-dart#405]
`Sentry.currentHub` should not be used anymore:

https://github.com/getsentry/sentry-dart/blob/ff1bbe4a6f87d965b33cab9c74e74619097d90eb/dart/lib/src/sentry.dart#L29

**Comment by marandaneto** [comment]
the idea is that everything is accessible via the Sentry static class, so you don't have to rely on the `currentHub`
