### ISSUE TITLE
Transport Backpressure support

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-dart#408]
Similar to Java https://github.com/getsentry/sentry-java/blob/main/sentry/src/main/java/io/sentry/transport/QueuedThreadPoolExecutor.java

The idea is that events get queued up to X number and dropped if the limit gets exceeded, so we don't overload the app's main isolate if they capture events very fast in a tight loop.

**Comment by marandaneto** [comment]
We should do it to avoid issues when calling e.g. `captureException` in a tight loop, since it returns a Future and the throwable is not serializable, we cannot offload the event pipeline in a different Isolate, we could tho try to use a counter and bailout if the queue is exceeded.
Also, you cannot call MethodChannels in the main isolate.

**Comment by marandaneto** [comment]
Consider doing https://github.com/getsentry/sentry-dart/issues/536 as well

**Comment by denrase** [comment]
Closed by #1868
