### ISSUE TITLE
add android.useAndroidX=true to gradle.properties for profile builds

### ISSUE THREAD

**Issue by markfili** [getsentry/sentry-dart#409]
my Flutter profile APK build first failed with a warning to add android.useAndroidX=true to gradle.properties and passed when I did so. please consider this.

https://github.com/getsentry/sentry-dart/blob/4d42b29de33d7003a55b652230bb929f7eda5715/flutter/android/gradle.properties#L1

![image](https://user-images.githubusercontent.com/3738182/114068576-5b5cdf80-989e-11eb-899f-ea1126c3868b.png)

**Comment by marandaneto** [comment]
@markfili thanks for raising this.

this goes to the final App's `gradle.properties` and not 3rd party libs, have you tried that?

**Comment by markfili** [comment]
@marandaneto thank you for responding so quickly.

I have another picture that's worth at least 10 words:
![image](https://user-images.githubusercontent.com/3738182/114071283-3ae25480-98a1-11eb-8860-d03df48e25d7.png)

**Comment by markfili** [comment]
this might be a local problem, I'm having issues building apps lately, so if you consider this valid, please try with your setup and this repository. if not, I'm sure it will solve itself soon.

**Comment by marandaneto** [comment]
@markfili if you have any `androidx` lib in your project, you must have it in your App's gradle.properties file.

https://developer.android.com/jetpack/androidx/migrate#migrate_an_existing_project_using_android_studio

if you create an empty project using `flutter create android`, it already comes with such flag already set to App's gradle.properties, so it's not a Sentry SDK issue.

this is from a fresh and empty project:

> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':app:checkDebugAarMetadata'.
> > This project uses AndroidX dependencies, but the 'android.useAndroidX' property is not enabled. Set this property to true in the gradle.properties file and retry.
>   The following AndroidX dependencies are detected: androidx.core:core:1.1.0, androidx.fragment:fragment:1.1.0, androidx.versionedparcelable:versionedparcelable:1.1.0, androidx.lifecycle:lifecycle-common:2.2.0, androidx.lifecycle:lifecycle-common-java8:2.2.0, androidx.customview:customview:1.0.0, androidx.lifecycle:lifecycle-livedata:2.0.0, androidx.lifecycle:lifecycle-viewmodel:2.1.0, androidx.loader:loader:1.0.0, androidx.lifecycle:lifecycle-livedata-core:2.0.0, androidx.activity:activity:1.0.0, androidx.collection:collection:1.1.0, androidx.viewpager:viewpager:1.0.0, androidx.arch.core:core-runtime:2.0.0, androidx.arch.core:core-common:2.1.0, androidx.savedstate:savedstate:1.0.0, androidx.annotation:annotation:1.1.0, androidx.lifecycle:lifecycle-runtime:2.2.0
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 2s
