### ISSUE TITLE
Work around PackageInfo Limitations

### ISSUE THREAD

**Issue by ueman** [getsentry/sentry-dart#410]
Linux und Windows have a few limitations. Notably:
- Linux has no package name
- Windows has an empty distribution

We need to figure out what a sensible default value is, if we can not work around those limitations.

**Comment by marandaneto** [comment]
Current linux release: `@0.1.2+3`
Current windows release: `sentry_flutter_example\u0000@1.0.0\u0000+` -> https://www.fileformat.info/info/unicode/char/0000/index.htm

**Comment by marandaneto** [comment]
macOS does it nicely `io.sentry.flutter.sentryFlutterExample@0.1.2+3`

**Comment by marandaneto** [comment]
windows issue https://github.com/fluttercommunity/plus_plugins/issues/182 and https://github.com/flutter/flutter/issues/73652

**Comment by marandaneto** [comment]
linux issue https://github.com/fluttercommunity/plus_plugins/issues/203

**Comment by ueman** [comment]
https://www.github.com/fluttercommunity/plus_plugins/tree/main/packages%2Fpackage_info_plus_linux%2Flib%2Fsrc%2Fpackage_info.dart

https://www.github.com/fluttercommunity/plus_plugins/tree/main/packages%2Fpackage_info_plus_web%2Flib%2Fpackage_info_plus_web.dart

Web is also missing the package identifier like linux. Maybe we could use the app name if no package identifier is available.

**Comment by marandaneto** [comment]
@ueman sounds a good idea
there are a few chars not allowed chars though, https://docs.sentry.io/platforms/flutter/configuration/releases/#bind-the-version
`packageName` does not allow such chars, so we have not used a regex or so, maybe with App's name this might be necessary.

**Comment by ueman** [comment]
On web and linux and windows the name given in the pubspec.yaml gets used as appName: https://dart.dev/tools/pub/pubspec#name

I'm not sure though about windows and what UWP uses though.

**Comment by marandaneto** [comment]
to close this issue I suggest the following:

take the Windows example:

`sentry_flutter_example\u0000@1.0.0\u0000+`

trim null chars `\u0000`;
only concat `+` if the `buildNumber` is non-empty;

result should be: `sentry_flutter_example@1.0.0`

other than that, on Windows support, we should document that the `release` should be set by either `options.release` or `SENTRY_RELEASE` env. var.

**Comment by ueman** [comment]
Do we want to do 

> trim null chars \u0000;

ourself or do we fix it in package_info_plus?

**Comment by marandaneto** [comment]
@ueman we can't control user's `package_info_plus` version, so we have to trim ourselves, I believe, otherwise we'd force people to a min. version which is the latest and might not be what they want.
