### ISSUE TITLE
Add request duration to HTTP breadcrumbs

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dart#412]
[badges.bar](https://github.com/bruno-garcia/badges.bar) calls an API to retrieve scores from pub.dev.

Would be nice to see how long these requests took. Perhaps as `data` to show under the status code:

![image](https://user-images.githubusercontent.com/1633368/114430658-ab80be00-9b8c-11eb-8de9-1543529635c9.png)

**Comment by ueman** [comment]
I also left this as a todo in the code when I added this feature:
https://github.com/getsentry/sentry-dart/blob/4d42b29de33d7003a55b652230bb929f7eda5715/dart/lib/src/http_client/sentry_http_client.dart#L44-L47

What should happen if an exception gets thrown? 
How would one test that the measured duration is correct?

**Comment by bruno-garcia** [comment]
> I also left this as a todo in the code when I added this feature:
> https://github.com/getsentry/sentry-dart/blob/4d42b29de33d7003a55b652230bb929f7eda5715/dart/lib/src/http_client/sentry_http_client.dart#L44-L47
> 
> What should happen if an exception gets thrown?
> How would one test that the measured duration is correct?

Would it work to just stop the stopwatch on a `finally` block? if the method returned or throw shouldn't affect the ability to track its duration, right?

**Comment by ueman** [comment]
I think it should work. I wondered if it the duration shouldn't be tracked if the request fails, but after thinking twice that doesn't make much sense.
