### ISSUE TITLE
Sentry Flutter does not report offset within line

### ISSUE THREAD

**Issue by fzyzcjy** [getsentry/sentry-dart#415]
_Platform:_
- [ ]  Dart
- [x]  Flutter Android or iOS
- [ ]  Flutter Web

_IDE:_
- [ ]  VSCode
- [x]  IntelliJ/AS
- [ ]  XCode
- [ ]  Other, which one?

_split-debug-info and obfuscate (Flutter Android or iOS) or CanvasKit (Flutter Web):_
- [ ]  Enabled
- [x]  Disabled

_Platform installed with:_
- [x] pub.dev
- [ ] GitHub

Output of the command `flutter doctor -v` below:

The version of the SDK (See pubspec.lock):
latest

---
I have the following issue:

Hi thanks for the lib! it seems that Sentry Flutter does not report offset within line. For example:

![image](https://user-images.githubusercontent.com/5236035/114552330-10c0d600-9c97-11eb-88ff-54466ec9b8ef.png)

But indeed the raw error is:

![image](https://user-images.githubusercontent.com/5236035/114552363-19b1a780-9c97-11eb-8bdb-f9cf820e6242.png)

Notice there is offset within line, e.g. `:1544:47` instead of only `1544`.

This information is quite important, because when multiple position at the same line can trigger the same error, I have completely no idea which one *actually* triggers the error. For example:

```
final int codeUnit = text!.codeUnitAt(i)!; // line 1544
```

How to know the _CastError is from `text!` or `...codeUnitAt()!`!

**Steps to reproduce:**
- Step

**Actual result:**
- Actual

**Expected result:**
- Result

**Comment by marandaneto** [comment]
@fzyzcjy thanks for reporting, indeed.

I'm wondering if this is available at runtime for every case, are you running on Android or iOS?

See the code:
https://github.com/getsentry/sentry-dart/blob/main/dart/lib/src/sentry_stack_trace_factory.dart#L93-L95

I just looked up a few old events and they do contain line:column, maybe it's specific to `_CastError`? would you mind checking the raw JSON on sentry and see if it contains the `colno` field in the JSON?

**Comment by marandaneto** [comment]
<img width="671" alt="Screenshot 2021-04-13 at 14 54 16" src="https://user-images.githubusercontent.com/5731772/114555644-31256c00-9c68-11eb-9c9a-bf198e59458f.png">

**Comment by fzyzcjy** [comment]
@marandaneto I guess no colno in json:

![image](https://user-images.githubusercontent.com/5236035/114555699-89756180-9c9a-11eb-81fc-3411c2552dfc.png)

Other errors also does not have column number.

Given the explanations above, maybe it is because, the colno is not given by the `stack-trace` library or flutter StackTrace? (then it is not the problem of sentry)

it is on release mode that I do not see colno. not sure whether caused by this.

**Comment by marandaneto** [comment]
yes indeed, no colno for Release builds on Android, but actually, not even the standard console has it, so its a limitation of Dart & Flutter, hence not a Sentry issue.

<img width="975" alt="Screenshot 2021-04-13 at 14 59 47" src="https://user-images.githubusercontent.com/5731772/114556469-0982d380-9c69-11eb-9e29-8f8e1fd38b00.png">

**Comment by fzyzcjy** [comment]
@marandaneto Thanks!
