### ISSUE TITLE
Log calls to `print()` as Breadcrumbs

### ISSUE THREAD

**Issue by ueman** [getsentry/sentry-dart#423]
One can add a [`PrintHandler`](https://api.dart.dev/stable/2.12.4/dart-async/PrintHandler.html) to a [`Zone`](https://api.dart.dev/stable/2.12.4/dart-async/Zone/print.html). This allows us to intercept all(?) calls to `print()` and log them as Breadcrumbs. 

Also see https://api.dart.dev/stable/2.12.4/dart-async/runZonedGuarded.html

Also see https://github.com/getsentry/sentry-dart/projects/1#card-50166788

**Comment by marandaneto** [comment]
we should offer an option to disable it (options.enablePrintHandlerBreadcrumbs = false), as it can be very noisy/verbose.

naming `enablePrintHandlerBreadcrumbs` is just a suggestion though
