### ISSUE TITLE
Check Flutter's updated error handling page

### ISSUE THREAD

**Issue by ueman** [getsentry/sentry-dart#429]
There was an update to Flutter's error handling docs.

See https://flutter.dev/docs/testing/errors , 
https://github.com/flutter/website/pull/5612
and https://twitter.com/FlutterDev/status/1385669763595214856?s=19

We should check if there's something new which we currently don't do.

**Comment by marandaneto** [comment]
nice, after a quick read, apparently everything is alright, but worth double-checking

**Comment by ueman** [comment]
Yup, we are already doing everything correctly.
