### ISSUE TITLE
captureException may fail on Web and release mode, on Chrome, if you do stackTrace.toString works but not on Safari

### ISSUE THREAD

**Issue by ueman** [getsentry/sentry-dart#431]
https://github.com/getsentry/sentry-dart/pull/187#discussion_r530467479

Edit: This was previously tracked as a card on the kanban board and just converted to an issue.

**Comment by ueman** [comment]
Chrome and Safari both record exceptions with `Sentry.captureException`: https://sentry.io/organizations/sentry-sdks/issues/2363318841/events/?project=5428562
One event is from chrome and the other one is from safari.

**Comment by ueman** [comment]
Relevant example code: https://github.com/getsentry/sentry-dart/blob/main/flutter/example/lib/main.dart#L178-L184

**Comment by ueman** [comment]
Firefox also works

**Comment by marandaneto** [comment]
@ueman just to be sure, run https://github.com/getsentry/sentry-dart/tree/main/dart/example_web which isn't the same example as tested before, on release mode.

**Comment by marandaneto** [comment]
another thing to test is, if its actually using the given `stackTrace` or if it's actually getting `StackTrace.current`, what I mean is,  we just need to be sure it works correctly, when this was tested, we were not using `StackTrace.current` if `stackTrace` was null or something

**Comment by ueman** [comment]
I tested the following scenarios:

## 1
Flutter example at https://getsentry.github.io/sentry-dart/ on Chrome, Safari and Firefox (all on macOS)

## 2
from Dart's web example, on Chrome, Safari, Firefox (all on macOS)
```dart
try {
    await buildCard();
  } catch (error, stackTrace) {
    final sentryId = await Sentry.captureException(
      error,
      stackTrace: stackTrace,
    );
  }
``` 

## 3
Modified 2 to the following
from Dart's web example, on Chrome, Safari, Firefox (all on macOS)
```dart
try {
    await buildCard();
  } catch (error, stackTrace) {
    final sentryId = await Sentry.captureException(
      error,
      stackTrace: null,
    );
  }
``` 

## 3
Modified 2 to the following
from Dart's web example, on Chrome, Safari, Firefox (all on macOS)
```dart
try {
    await buildCard();
  } catch (error, stackTrace) {
    final sentryId = await Sentry.captureException(
      error,
      stackTrace: StackTrace.current,
    );
  }
``` 

## 4
Modified 2 to the following
from Dart's web example, on Chrome, Safari, Firefox (all on macOS)
```dart
try {
    await buildCard();
  } catch (error, stackTrace) {
    final sentryId = await Sentry.captureException(
      error,
      stackTrace: stackTrace.toString(),
    );
  }
``` 

All scenarios work as expected.

Test setup:

- Firefox v86.0.1
- Safari Version 14.0.3 (16610.4.3.1.7)
- Chrome Version 90.0.4430.85
- macOS Version 11.2.3

**Comment by ueman** [comment]
Crash Reports on sentry.io: https://sentry.io/organizations/sentry-sdks/issues/?project=5428562&query=is%3Aunresolved++%22This+is+a+test+error%22&statsPeriod=14d

**Comment by marandaneto** [comment]
Let's just close it then @ueman , users will come to it if they see something like that, could be either an oversight during the test at that time or even an older dart/flutter issue on 1.x which isn't there anymore, thanks for testing
