### ISSUE TITLE
Support `split-debug-info` for Flutter Desktop (Linux and Windows)

### ISSUE THREAD

**Issue by ueman** [getsentry/sentry-dart#433]
We need to test 
- [x] `split-debug-info` and `obfuscate` on macOS
- [x] #2431 `split-debug-info` and `obfuscate` on Linux
- [x] #2286 `split-debug-info` and `obfuscate` on Windows

Those options have not been tested. They might require changes in the SDK and/or on the server.
It could be that they already work, and in this case we don't need to do anything.

We need to update the docs after this has been tested.

**Comment by marandaneto** [comment]
let's add the windows/macos/linux support to this script

https://github.com/getsentry/sentry-dart/blob/main/flutter/example/run.sh

the way of uploading debug files is the same as iOS/Android -> https://github.com/getsentry/sentry-dart/blob/main/flutter/example/run.sh#L58-L60

we need to see if frames are symbolicated, file/function names are available and line number is also correct.

I believe macOS won't work if Flutter has the same format as iOS debug files, but let's try.

@bruno-garcia you may need to help us on Windows, would you be willing to do so? :)

**Comment by bruno-garcia** [comment]
Didn't seem to work: https://sentry.io/organizations/sentry-sdks/issues/2367778946/?project=5428562&query=is%3Aunresolved

We would need to add the debug_meta with the DLL's build_id of sorts. @jan-auer might have pointers.

![image](https://user-images.githubusercontent.com/1633368/116334065-99189e00-a7a2-11eb-8cb3-283d235caa7d.png)

**Comment by bruno-garcia** [comment]
![image](https://user-images.githubusercontent.com/1633368/116334232-db41df80-a7a2-11eb-8e5c-4487ad565fc9.png)

`.so` on Windows? They really went all in with ELF it seems

**Comment by marandaneto** [comment]
indeed, we'd need to install the `LoadAndroidImageListIntegration` integration for Flutter Desktop, but not only, on Android, `sentry-native` is also responsible for loading that.
That means, either we ship sentry-native for Linux/Windows or we find a way to do it via Native code or `ffi`

macOS requires that too, so Sentry Cocoa needs to expose a way of getting the debug image list.
https://github.com/getsentry/sentry-cocoa/issues/1089

**Comment by ueman** [comment]
The [Flutter docs](https://flutter.dev/docs/deployment/obfuscate) state that `obfuscate` is not supported on Windows and Linux.

**Comment by bruno-garcia** [comment]
Makes it easier. On Windows and Linux we only need to bundle `sentry-native` to capture native crashes.

**Comment by marandaneto** [comment]
Removed `obfuscate` from the title since it's not supported by the tooling anyway.

**Comment by marandaneto** [comment]
@ueman I believe this is now possible? https://docs.flutter.dev/deployment/obfuscate#supported-targets
`macOS` should work already, I believe, since we already use the Sentry Cocoa SDK as well, after uploading debug symbols of course.

**Comment by ueman** [comment]
Yes, it seems like it's now possible 🥳

**Comment by marandaneto** [comment]
Ok removed the limitation https://github.com/getsentry/sentry-docs/pull/7156/files
This has been tested already https://github.com/getsentry/sentry-dart/blob/8ccf7824c7322eebfda677dcce9d0ee25614b31a/flutter/example/run.sh#L33

**Comment by Ghelwig** [comment]
Is there any update on this now that `obfuscate` is supported on windows? 
https://docs.flutter.dev/deployment/obfuscate#supported-targets

**Comment by bruno-garcia** [comment]
I imagine we'd need to add `sentry-native` to the SDK and capture loaded image info. That with PDB uploading etc. @vaind might know how much work this would entails

**Comment by alexvoina** [comment]
interested

**Comment by Ghelwig** [comment]
@bruno-garcia thanks for looking into this, any updates greatly appreciated :)

**Comment by bruno-garcia** [comment]
I'm not involved directly so I don't think this is planned to be honest, but I'm sure we're happy to get contributions if folks want to get support. @kahest will know what's going on

**Comment by Ghelwig** [comment]
Just to confirm @kahest is this something that will only be supported with outside contributions or is this something that the Sentry team plans on supporting?

**Comment by kahest** [comment]
Hey @Ghelwig - we're interested in supporting this, but currently don't have the bandwidth internally. We're happy to work with folks interested in contributing!

**Comment by JesseRiemens** [comment]
We would really love to see support for `flutter build bundle` as well. The only way currently is to build a debug build, which is a heavy penalty on an embedded target.

**Comment by vaind** [comment]
> We would really love to see support for `flutter build bundle` as well. The only way currently is to build a debug build, which is a heavy penalty on an embedded target.

@JesseRiemens what is your use-case for `flutter build bundle` builds? I've never had to use these but AFAIU they only bundle assets so I'm not sure how that's relevant to symbolication (and specifically Windows and Linux desktop support, which is what this issue is about). Could you please clarify and/or create a reproducible example? Ideally in a new issue if it's not related to windows/linux support

**Comment by JesseRiemens** [comment]
> > We would really love to see support for `flutter build bundle` as well. The only way currently is to build a debug build, which is a heavy penalty on an embedded target.
> 
> @JesseRiemens what is your use-case for `flutter build bundle` builds? I've never had to use these but AFAIU they only bundle assets so I'm not sure how that's relevant to symbolication (and specifically Windows and Linux desktop support, which is what this issue is about). Could you please clarify and/or create a reproducible example? Ideally in a new issue if it's not related to windows/linux support

We use Yocto with meta-flutter, in a kiosk-like touch screen application. It uses a custom embedder, flutter-pi. We have now resorted to not obfuscating release builds, as a sort of middle ground. 

Do you need a more concrete example? I reckon I could set up a MWE repo if that's needed.

Does it require a new issue? This is Linux after all :)

**Comment by vaind** [comment]
> Do you need a more concrete example? I reckon I could set up a MWE repo if that's needed.

A repository with a minimal repro would go a long way towards getting this working - it may be a simple change in the SDK or the `sentry_dart_plugin`, but it's hard to tell since I have no experience with custom flutter embedders & using bundles with them. I can't promise anything but if it's simple to try this out with your repro, I may be able to have a look while testing out linux support in general.

**Comment by JesseRiemens** [comment]
> > Do you need a more concrete example? I reckon I could set up a MWE repo if that's needed.
> 
> A repository with a minimal repro would go a long way towards getting this working - it may be a simple change in the SDK or the `sentry_dart_plugin`, but it's hard to tell since I have no experience with custom flutter embedders & using bundles with them. I can't promise anything but if it's simple to try this out with your repro, I may be able to have a look while testing out linux support in general.

Do you have experience / access to a raspberry pi? I think it would be able to do it with that.

**Comment by vaind** [comment]
> > > Do you need a more concrete example? I reckon I could set up a MWE repo if that's needed.
> > 
> > 
> > A repository with a minimal repro would go a long way towards getting this working - it may be a simple change in the SDK or the `sentry_dart_plugin`, but it's hard to tell since I have no experience with custom flutter embedders & using bundles with them. I can't promise anything but if it's simple to try this out with your repro, I may be able to have a look while testing out linux support in general.
> 
> Do you have experience / access to a raspberry pi? I think it would be able to do it with that.

I do have a pi zero lying around _somewhere..._

**Comment by ymmtyuhei** [comment]
Are split-debug-info and obfuscated Flutter Desktop applications supported now?
[The documentation](https://docs.sentry.io/platforms/flutter/upload-debug/) doesn't seem to be updated, how can I use it? 
I would like to check the stack trace of Windows applications.

**Comment by vaind** [comment]
> Are split-debug-info and obfuscated Flutter Desktop applications supported now? [The documentation](https://docs.sentry.io/platforms/flutter/upload-debug/) doesn't seem to be updated, how can I use it? I would like to check the stack trace of Windows applications.

You need to upload the debug symbols after a build - the steps and docs are pretty much the same as for mobile (https://docs.sentry.io/platforms/flutter/upload-debug/). I'll update the docs soon but the changes would likely be just removing windows/linux as not supported.
