### ISSUE TITLE
Support onCrashedLastRun

### ISSUE THREAD

**Issue by jguz88** [getsentry/sentry-dart#441]
I'm using `sentry_flutter 5.0.0` and the new functionality is proposed for Flutter. I would like to enrich crash report by adding custom data. Unfortunately, existing `beforeSend` callback is never called if a Flutter application launched again after a crash. 

```
SentryEvent beforeSend(SentryEvent event, {dynamic hint}) {
  if (event.level == SentryLevel.fatal) {
    event = event.copyWith(environment: '', tags: ..., extra: ...);
  }
  return event;
}

await SentryFlutter.init((options) {
    options.dsn = ...;
    options.beforeSend = beforeSend;
});
```

### Proposal 1

Invoke the `beforeSend` callback inside the SDK in case of opening a Flutter application just after a crash.

### Proposal 2

Create separate callback which is called if the Flutter application crashed last time.
For instance, in a similar way as it's now for native iOS SDK

```
SentryEvent onCrashedLastRun(SentryEvent event) {
   return event.copyWith(environment: '', tags: ..., extra: ...);
}

await SentryFlutter.init((options) {
    options.dsn = ...;
    options.onCrashedLastRun = onCrashedLastRun;
});
```

Thank you for your brilliant work so far!

**Comment by marandaneto** [comment]
@jguz88 indeed, thanks for raising this.

we'd go probably with `onCrashedLastRun` as its the way how we do it on other SDKs, but Flutter rarely hard crashes and when it does, it does via signal handlers which are not handled by the Flutter SDK but the underlying SDKs, either sentry-cocoa or sentry-native

**Comment by bruno-garcia** [comment]
As a work around, you can write a `beforeSend` in Java. There's an issue tracking a better way to allow you initialize the Android SDK programatically: #265 
Until this one is solved it's a bit complicated to "go manual".

**Comment by jguz88** [comment]
Yes, I did this in that way and provide a ```beforeSend``` in Java as soon as an application started. But this configuration will be overwritten in the ```initNativeSdk``` method  which also invokes ```SentryAndroid.init```. I would like to preserve your configuration and add my changes upon that. I also realize it's not so simple.

**Comment by larssn** [comment]
Would this allow us to enrich native crashes?

It's a challenge currently to figure out, say, who was logged into Firebase if there's a hard crash.

**Comment by bruno-garcia** [comment]
> Yes, I did this in that way and provide a `beforeSend` in Java as soon as an application started. But this configuration will be overwritten in the `initNativeSdk` method which also invokes `SentryAndroid.init`. I would like to preserve your configuration and add my changes upon that. I also realize it's not so simple.

The alternative is to have a way to initialize manually the native layers. This way you're also guaranteed to capture crashes that happen before Flutter itself starts (except perhaps on Android if a content provider (e.g: flutter?) crashes before Sentry's `init` is called. There's an issue: #265 

> Would this allow us to enrich native crashes?
> It's a challenge currently to figure out, say, who was logged into Firebase if there's a hard crash.

Do you know that in Dart at some point? You could add the tag via Dart and that should be synchronized down to all native layers. So even if it crashes in a library written in C in either iOS or Android, the value should be in the event.

**Comment by marandaneto** [comment]
> > Yes, I did this in that way and provide a `beforeSend` in Java as soon as an application started. But this configuration will be overwritten in the `initNativeSdk` method which also invokes `SentryAndroid.init`. I would like to preserve your configuration and add my changes upon that. I also realize it's not so simple.
> 
> The alternative is to have a way to initialize manually the native layers. This way you're also guaranteed to capture crashes that happen before Flutter itself starts (except perhaps on Android if a content provider (e.g: flutter?) crashes before Sentry's `init` is called. There's an issue: #265
> 
> > Would this allow us to enrich native crashes?
> > It's a challenge currently to figure out, say, who was logged into Firebase if there's a hard crash.
> 
> Do you know that in Dart at some point? You could add the tag via Dart and that should be synchronized down to all native layers. So even if it crashes in a library written in C in either iOS or Android, the value should be in the event.

The last point won't work tho due to #194 not being addressed yet.

**Comment by marandaneto** [comment]
If the reason is missing data when the App crashed, this should be addressed by https://github.com/getsentry/sentry-dart/issues/194
So whenever you configure the scope, this data is synced down to the Native SDKs.
