### ISSUE TITLE
Rename enableSessionTracking to enableAutoSessionTracking in Android native integration

### ISSUE THREAD

**Issue by ueman** [getsentry/sentry-dart#448]
See https://github.com/getsentry/sentry-java/pull/1457 and https://github.com/getsentry/sentry-java/issues/1189

I guess we want to rename the option in this SDK too.

**Comment by marandaneto** [comment]
its already called `enableAutoSessionTracking` on Dart/Flutter SDK, we just need to call the Android SDK with the non-deprecated setter

**Comment by marandaneto** [comment]
I need to cut an Android release, will do that tomorrow if possible.

**Comment by marandaneto** [comment]
we could open a PR calling the new setter method, bumping the SDK to beta-2, CI fails because its not published, but it'd work as soon as its released

**Comment by marandaneto** [comment]
Android beta-2 is published, so this issue can be worked on
