### ISSUE TITLE
Add option for Android device ID generation

### ISSUE THREAD

**Issue by ueman** [getsentry/sentry-dart#449]
See https://github.com/getsentry/sentry-java/pull/1455#issuecomment-831257971

**Comment by ueman** [comment]
We can point users to this:
https://github.com/fluttercommunity/plus_plugins/blob/fb24bf40089cc3dcae757db2a5b64d0a860b0138/packages/device_info_plus/android/src/main/java/dev/fluttercommunity/plus/device_info/MethodCallHandlerImpl.java#L99-L109

If it works we don't need to do anything but document it.

**Comment by marandaneto** [comment]
yep, we could just tell people to define a `beforeSendCallback` and mutate the `event.contexts.user.id` and `event.contexts.device.id`, let's just run this ourselves and guarantees that it works, if it does, we add to our breaking changes docs

**Comment by bruno-garcia** [comment]
It's a good thing to note on the migration page and release notes on GH.

**Comment by marandaneto** [comment]
Android beta-2 is published, so this issue can be worked on

**Comment by ueman** [comment]
`beforeSend` wouldn't work because it's not async but eventProcessors should work.

**Comment by marandaneto** [comment]
@ueman can we get a code snippet of a simple event processor doing that + SDK init adding the event processor? if that works, we can add it to the migration page, also, there should be a condition to add the event processor or to execute the event processor, it should be only for Android, not iOS

**Comment by ueman** [comment]
In Dart there's no `Device.Id` and the docs https://develop.sentry.dev/sdk/event-payloads/contexts/#device-context also don't list it. Though Android does have it. For Device we would have to add the field. 

A snippet for the user is coming.

**Comment by marandaneto** [comment]
> In Dart there's no `Device.Id` and the docs https://develop.sentry.dev/sdk/event-payloads/contexts/#device-context also don't list it. Though Android does have it. For Device we would have to add the field.
> 
> A snippet for the user is coming.

no need, ignore it
