### ISSUE TITLE
1000 log lines / minute?

### ISSUE THREAD

**Issue by tamoyal** [getsentry/sentry-dart#455]
I'm currently getting around 1000 log lines / minute from this plugin. Beyond this being so noisy my logs are now useless, it just seems like something is wrong. Here is a taste:
```
I/com.rype.go( 2680): The ClassLoaderContext is a special shared library.
I/System.out( 2680): [OkHttp] sendRequest>>
I/System.out( 2680): [OkHttp] sendRequest<<
D/Sentry ( 2680): Envelope sent successfully.
D/Sentry ( 2680): Envelope flushed
D/Sentry ( 2680): Marking envelope submission result: true
D/Sentry ( 2680): File '/data/user/0/com.rype.go/cache/sentry/outbox/85ba450f-d402-4ac7-a5ca-58e2fe7ad36b' is done.
D/Sentry ( 2680): onEvent fired for EnvelopeFileObserver with event type 8 on path: /data/user/0/com.rype.go/cache/sentry/outbox for file 650c5148-e179-481d-9bda-747fd9e6968d.
D/Sentry ( 2680): Processing Envelope with 1 item(s)
D/Sentry ( 2680): Capturing event: 85ca311c2ab84792a1855825375c785c
I/Sentry ( 2680): Not possible to read external files directory
D/Sentry ( 2680): Captured Envelope is already cached
2
I/Sentry ( 2680): 1 items will be dropped due rate limiting.
D/Sentry ( 2680): Item 1 is being captured.
2
D/OpenSSLLib( 2680): OpensslErr:Module:12(177:); file:external/boringssl/src/crypto/asn1/asn1_lib.c ;Line:168;Function:ASN1_get_object
I/com.rype.go( 2680): The ClassLoaderContext is a special shared library.
I/System.out( 2680): [OkHttp] sendRequest>>
I/System.out( 2680): [OkHttp] sendRequest<<
D/Sentry ( 2680): Envelope sent successfully.
D/Sentry ( 2680): Envelope flushed
D/Sentry ( 2680): Marking envelope submission result: true
D/Sentry ( 2680): File '/data/user/0/com.rype.go/cache/sentry/outbox/650c5148-e179-481d-9bda-747fd9e6968d' is done.
D/Sentry ( 2680): onEvent fired for EnvelopeFileObserver with event type 8 on path: /data/user/0/com.rype.go/cache/sentry/outbox for file ca91af08-9c60-4fc2-b323-66d7a1cc88c0.
D/Sentry ( 2680): Processing Envelope with 1 item(s)
D/Sentry ( 2680): Capturing event: 769f85ab931e445d9eaf67ae415de574
I/Sentry ( 2680): Not possible to read external files directory--
```

**Comment by marandaneto** [comment]
@tamoyal thanks for reporting.

Please update your issue with one of our issue templates https://github.com/getsentry/sentry-dart/issues/new/choose

after that, have you enabled the `debug` mode of the Sentry SDK? you don't have to, so you don't see any logs.
if you are running on debug mode, the `debug` mode is enabled automatically, you can turn it off when initing the SDK or changing the `diagnosticLevel` to `SentryLevel.error` for example.

**Comment by bruno-garcia** [comment]
I think it's best we don't set the Sentry SDK in debug mode automatically even if the user is in debug mode

**Comment by marandaneto** [comment]
> I think it's best we don't set the Sentry SDK in debug mode automatically even if the user is in debug mode

the problem is that when the option callback is triggered, Sentry already did some work and this won't be logged out unless its turned on by default if running on debug mode.

**Comment by bruno-garcia** [comment]
> the problem is that when the option callback is triggered, Sentry already did some work and this won't be logged out unless its turned on by default if running on debug mode.

I see. Can we use dart define to pass opt-in for debug mode? What does the SDK log out before the user callback runs?

**Comment by marandaneto** [comment]
using dart-define would work, not sure if its user friendly though, requires running via CLI or adding the extra conf. to launch.json probably manually

**Comment by marandaneto** [comment]
@tamoyal did it help to disable `debug` mode or changing `diagnosticLevel` ?

**Comment by tamoyal** [comment]
@marandaneto `debug: false` worked! thanks

**Comment by matejkramny** [comment]
`debug` seems to be off by default, but we keep seeing messages like this?

The histogram legend shows ~3500 messages in the span of one second.

![Screenshot_20210821_154031](https://user-images.githubusercontent.com/797608/130325412-64b59bc7-855e-403f-8c77-d058171d2161.png)

**Comment by marandaneto** [comment]
@matejkramny please raise a new issue for that with more context, like SDK version, debug or release? OS? does the device have a connection or not? are you capturing multiple events per second? etc, thanks
