### ISSUE TITLE
Change method signature of the logger to match Dart's log method

### ISSUE THREAD

**Issue by ueman** [getsentry/sentry-dart#462]
The method signature of the Sentry Logger should match (or map closely) to the [Dart log method](https://api.dart.dev/stable/2.12.4/dart-developer/log.html).

**Comment by bruno-garcia** [comment]
Would be worth throwing some suggestions on this issue before raising a PR?

**Comment by ueman** [comment]
One reason is that we can explicitly pass exceptions and stacktraces. Which makes it easier for us and the user to pinpoint issues. Having a `name` is also nice. The rest is more of a nice to have.

Just for reference, the method signature is:

```dart
void log(
  String message, {
  DateTime? time,
  int? sequenceNumber,
  int level = 0,
  String name = '',
  Zone? zone,
  Object? error,
  StackTrace? stackTrace,
});
```

**Comment by marandaneto** [comment]
I'd go with the `message`, obviously.
`time` is already inferred automatically by the console I guess
`sequenceNumber` I don't see as any useful
`level` for sure
`name` is sort of useless if we log ourselves anyway, could be hardcoded `sentry`
`zone` also not really necessary, we only run stuff in the main/default zone anyway
`error` and `stackTrace` yes.

worth noting that this is a log API for Sentry SDK itself
