### ISSUE TITLE
Add missing Protocol Properties

### ISSUE THREAD

**Issue by ueman** [getsentry/sentry-dart#464]
See 
- [x] https://github.com/getsentry/develop/pull/335 Already in spec but not documented
- [x] https://github.com/getsentry/develop/pull/330 Theme can also be worked on. It's for dark vs light mode.
- [ ] https://github.com/getsentry/develop/pull/329 `Culture` context.

**Comment by marandaneto** [comment]
just a heads up, changing the protocol requires a bit more changes than develop docs, adding to ingestion (relay), custom labels on UI, and also agreement with our API committee as they should make sense across SDKs, the protocol is already flexible to accept custom key/values
