### ISSUE TITLE
sendDefaultPii stops sending of scope.user details

### ISSUE THREAD

**Issue by JamesMcIntosh** [getsentry/sentry-dart#466]
Platform: Dart
SDK: **5.0.0**

---

I tried enabling `SentryOptions.sendDefaultPii` due to the recommendation in the docs and also using `Sentry.configureScope` to set the `user` details.
When sendDefaultPii is enabled the scope.user details are never sent in error reports.

```
Sentry.init(
  (SentryOptions options) async {
    options
      ..dsn = dsn
      ..sendDefaultPii = true;
  },
);
Sentry.configureScope(
  (scope) => scope.user = SentryUser(username: "Tester")
);
```

The cause is [/dart/lib/src/scope.dart#L159 - applyToEvent](https://github.com/getsentry/sentry-dart/blob/main/dart/lib/src/scope.dart#L159) as the user with Pii details have already been created in SentryClient._prepareEvent
```
event = event.copyWith(
...
user: event.user ?? user,
...
);
```

My expectation is that this would have attempted to merge the details, in my case scoped user details would have more precedence.

If this is expected behaviour a note in the docs would have saved a lot of time.

Many thanks!

**Comment by marandaneto** [comment]
@JamesMcIntosh thanks for reporting, its actually an oversight, it should have been merged with the non set fields
