### ISSUE TITLE
Use latest options from hub instead of using private options set on init

### ISSUE THREAD

**Issue by jennmueng** [getsentry/sentry-dart#470]
This would not be a major issue for Flutter now as it does not look like there is an equivalent of `autoInitNativeSdk` option here, but there was an issue over on RN regarding the user initing the native SDK themselves elsewhere and the outbox path not being correctly retrieved when writing envelopes causing error handling to not work.

Relevant issues and PR over on RN: https://github.com/getsentry/sentry-react-native/pull/1516 https://github.com/getsentry/sentry-react-native/pull/1529

https://github.com/getsentry/sentry-dart/blob/bece2c266231f291e970c667fb203a42951de538/flutter/android/src/main/kotlin/io/sentry/flutter/SentryFlutterPlugin.kt#L49-L58

**Comment by marandaneto** [comment]
might be an issue when doing https://github.com/getsentry/sentry-dart/issues/265

**Comment by marandaneto** [comment]
instead of caching `options` to a global var and checking `options.isInitialized`, we could read from `HubAdapter.getInstance().getOptions().getOutboxPath()`, same for `options.debugImagesLoader`
