### ISSUE TITLE
Bump Cocoa to 7.1.3 and use PrivateSentrySDKOnly instead of the private headers

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-dart#477]
This is a private class for our SDK that exposes some stuff that is needed, eg for envelopes https://github.com/getsentry/sentry-dart/pull/391
that are more things that can be removed I guess eg the private header

**Comment by ueman** [comment]
I think @denrase already done it in https://github.com/getsentry/sentry-dart/commit/60cde6dc13e00fdb771fc93f56d78897891e10e3

**Comment by denrase** [comment]
Yeah, needed to bump in order to use the new API.

**Comment by marandaneto** [comment]
The new class has more methods used by the sdk, so the bump is indeed done but not removing the old private header hacky solution

**Comment by marandaneto** [comment]
eg https://github.com/getsentry/sentry-dart/blob/main/flutter/ios/Classes/SentrySDK%2BFlutterPrivate.h could be removed in favor of `PrivateSentrySDKOnly`

**Comment by marandaneto** [comment]
I know the bump has been done already on https://github.com/getsentry/sentry-dart/pull/391 but that PR lands only on v6 and I'd like to bring this improvement into 5.1 too
