### ISSUE TITLE
When is FeedBack and Attachment is available for Dart and Flutter

### ISSUE THREAD

**Issue by Sparsh218** [getsentry/sentry-dart#478]
Feedback and Attachment feature is not available for Dart and Flutter and it is too much complex to apply them in JS.

**Comment by ueman** [comment]
For user feedback please see https://github.com/getsentry/sentry-dart/issues/215 and for attachements see https://github.com/getsentry/sentry-dart/issues/289

Please upvote them if they're important to you.
We plan to have them available in v6.

**Comment by Sparsh218** [comment]
Yes, they are important to me.
