### ISSUE TITLE
DeduplicationEventProcessor

### ISSUE THREAD

**Issue by ueman** [getsentry/sentry-dart#480]
In order to remove duplicated events, for example caused by [this](https://github.com/getsentry/sentry-dart/pull/473#discussion_r638492342) we need an event processor which removes duplicated events.

See https://github.com/getsentry/sentry-java/blob/b45944c93d53f68bc1e64f5ac4c9a5400b252d44/sentry/src/main/java/io/sentry/DuplicateEventDetectionEventProcessor.java for reference

Depends on https://github.com/getsentry/sentry-dart/issues/479

**Comment by bruno-garcia** [comment]
The Java one was based on this but for reference: https://github.com/getsentry/sentry-dotnet/blob/626d9966d600615a125da5d90cf8d25931aefb94/src/Sentry/Internal/DuplicateEventDetectionEventProcessor.cs#L15

**Comment by marandaneto** [comment]
Dart does not have a WeakRef type so we'd need to figure this out
