### ISSUE TITLE
Don't enable `print()` breadcrumbs by default on Flutter

### ISSUE THREAD

**Issue by ueman** [getsentry/sentry-dart#492]
_Platform:_
- [ ]  Dart
- [x]  Flutter Android or iOS
- [x]  Flutter Web

`Sentry Flutter Version 5.1.0`

By default Flutter calls [`dumpErrorToConsole`](https://api.flutter.dev/flutter/foundation/FlutterError/dumpErrorToConsole.html) for every exceptions which it catches. If you go down the rabbit hole, you'll end up [here](https://github.com/flutter/flutter/blob/02c026b03c/packages/flutter/lib/src/foundation/print.dart#L29). As you can see it calls `print()`. 

This results in pretty bad breadcrumbs because each stacktrace frame is written as a single breadcrumb.
![Bildschirmfoto 2021-06-10 um 09 18 01](https://user-images.githubusercontent.com/1270149/121481766-c3c65b00-c9cc-11eb-8601-72c161bfde85.png)

This seems to be an issue on debug and release builds.

**Comment by ueman** [comment]
It should be disabled by default (or just on Flutter).
I haven't come around to do this yet, though. The documentation should probably mention this behavior, too, in case a user manually enables this.

I don't think we need further investigation as the reason for this behavior is already explained in the issue. Or do you mean something else?

**Comment by marandaneto** [comment]
@ueman I meant, we should fix this, sorry :D
