### ISSUE TITLE
Sentry Build Plugin

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-dart#493]
The idea is that https://docs.sentry.io/platforms/flutter/upload-debug/#uploading-for-ios-and-macos and https://docs.sentry.io/platforms/flutter/upload-debug/#uploading-for-android-ndk is done automatically when somebody does `flutter build`.
on Android, we have a Gradle plugin https://github.com/getsentry/sentry-android-gradle-plugin
on iOS, its possible either via Bitcode or Fastlane https://github.com/getsentry/sentry-fastlane-plugin -> https://docs.sentry.io/platforms/apple/dsym/

I know that dart/flutter has the capability of executing a dart file when the build is invoked, it's a good candidate to start with
edit: iirc https://dart.dev/tools/pub/pubspec#executables

**Comment by ueman** [comment]
We can't do it at build time and also not fully automatically :(

So our build tool would have to be run after build, kind similar to the [msix](https://pub.dev/packages/msix) package.

That being said:
1. We would need a new package for that functionality
2. The user needs to use it as dev dependency
3. The user needs to execute it after build

This could also do some code generation for us, so it could help with https://github.com/getsentry/sentry-dart/issues/416

**Comment by marandaneto** [comment]
that's ok, the Gradle plugin should also be set up, they also need to configure the user token/project and org, its also ok to run after the build, after all the symbols are generated, what we'd like to do is: people don't need to run sentry-cli manually every time, but rather setting up only once, and looks like it's sort of possible.

**Comment by ueman** [comment]
@marandaneto Can this be closed or moved into the other repo?

**Comment by marandaneto** [comment]
its done :P https://github.com/getsentry/sentry-dart-plugin
