### ISSUE TITLE
App does not start if no DSN is configured

### ISSUE THREAD

**Issue by ueman** [getsentry/sentry-dart#499]
_Platform:_
- [ ]  Dart
- [x]  Flutter Android or iOS
- [ ]  Flutter Web

I haven't tested pure Dart or Flutter web yet, but I imagine it's similar.

_IDE:_
It's independend of the IDE

_split-debug-info and obfuscate (Flutter Android or iOS) or CanvasKit (Flutter Web):_
- [ ]  Enabled
- [x]  Disabled

_Platform installed with:_
- [x] pub.dev
- [ ] GitHub

The version of the SDK (See pubspec.lock):
**5.1.0** 

---
I have the following issue:

App shows a white screen.

**Steps to reproduce:**
- Use Sentry
- Initialize Sentry without a DSN at all, so no env variable and no setting in the options callback.

**Actual result:**
- App does not start

**Expected result:**
- App at least starts

Maybe we throw in debug mode and just disable Sentry in release mode?
Or is this working as intended?

**Comment by marandaneto** [comment]
@ueman this is fine, if you set an empty dsn, `dsn = ''`, it should work otherwise it's a bug.
empty dsn means Sentry is disabled.
no dsn at all, it's misconfigured, this is written in our docs.

**Comment by jamesdixon** [comment]
I'm on the latest 4.x version of the SDK and I can confirm that this doesn't work. I've tried with both a `null` and empty DSN (`''`).

My app will not start if there's no DSN configured.

Apologies if I'm missing something but not sure why this is closed?

**Comment by marandaneto** [comment]
it was fixed, see changelog https://github.com/getsentry/sentry-dart/releases/tag/4.1.0-nullsafety.0
please use the latest SDK.

**Comment by jamesdixon** [comment]
@marandaneto thanks for that

**Comment by zeeshan-webelight** [comment]
same thing happened with me, finally resolved. I added one demo Sentry DNS for temporary purpose, but in the release build my app was not working.

**Comment by faizan-jivani** [comment]
same thing happened with me, finally resolved. I added one demo Sentry DNS for temporary purpose, but in the release build my app was not working.
