### ISSUE TITLE
Tests seems to be somewhat flaky

### ISSUE THREAD

**Issue by ueman** [getsentry/sentry-dart#500]
The following tests run for 12 minutes until they timeout:

```
sentry-dart/flutter/test/load_android_image_list_test.dart
sentry-dart/flutter/test/native_sdk_integration_test.dart
sentry-dart/flutter/test/sentry_flutter_options_test.dart
sentry-dart/flutter/test/sentry_flutter_options_test.dart
sentry-dart/flutter/test/not_initialized_widgets_binding_test.dart
sentry-dart/flutter/test/sentry_flutter_test.dart
```

We should fix them, though I'm not sure yet what they have in common.
If we can't fix them, we should reduce the timeout.

**Comment by marandaneto** [comment]
@ueman did we figure out the issue?

**Comment by ueman** [comment]
No, but it seems better recently.

**Comment by ueman** [comment]
I'm still unable to reproduce this locally.

The only thing they have in common, as far as I can tell, is that they are Flutter tests and mostly (always?) fail on macOS due to timeouts in the test framework.

Links to a example failing builds:
https://github.com/getsentry/sentry-dart/runs/3348163366?check_suite_focus=true

Looking through the past workflow runs, it seems to have improved recently.

**Comment by marandaneto** [comment]
The issue isn't only macOS anymore, it happens on Windows and Linux too.
So the fix https://github.com/getsentry/sentry-dart/pull/743 didn't help.
I don't really know what's going on, and I can't reproduce it locally.

**Comment by marandaneto** [comment]
Runnings Chrome tests only on Linux seems to help.

**Comment by vaind** [comment]
No tests currently for `dart` and `flutter` dirs currently run on macOS. Having this long-term doesn't look like a good idea. Maybe reopen and re-scope this issue to try & bring them back?
