### ISSUE TITLE
Add test suite to `flutter/tests`

### ISSUE THREAD

**Issue by ueman** [getsentry/sentry-dart#501]
In order to not be surprised by new breaking changes of Flutter, we'd like to have our tests run on [`flutter/tests`](https://github.com/flutter/tests).

We do need a file like (pseudo code)
```
contact=email
fetch=git clone https://github.com/getsentry/sentry-dart flutter/test
fetch=git -C tests checkout {git_sha}
update=.
test=flutter analyze --no-fatal-infos
test=flutter test
```

Who should I add as a contact?
@marandaneto  @bruno-garcia

**Comment by bruno-garcia** [comment]
Please use `sdks at sentry dot eye oo` :)

**Comment by marandaneto** [comment]
as we run CI on stable, beta and dev channels, not a super important issue right now, but nice to have

**Comment by bruno-garcia** [comment]
The goal is to have their CI break if somehow they build something incompatible to our bits. Which is arguably better than having them merge it and ship in the 'dev' or 'beta' channel and break our CI.

That said agree it's a nice to have

**Comment by marandaneto** [comment]
We've not found the need to do this, the current stable/beta CI builds are working well and we are reacting pretty fast with the breaking changes that are usually landing on master first.
Also doing this now has tighter conditions https://github.com/flutter/tests/pull/280
