### ISSUE TITLE
Hints should be a data bag instead of a single `dynamic`

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-dart#510]
Similar to Java https://github.com/getsentry/sentry-java/blob/3f8d7b1cc869bb056c9db99b459e43f6c375784a/sentry/src/main/java/io/sentry/Hint.java

**Comment by NANASHI0X74** [comment]
I might add that the hint parameter for methods such as captureexception should be documented

**Comment by marandaneto** [comment]
This issue will enable https://github.com/getsentry/sentry-dart/issues/1127
This should be on top of the https://github.com/getsentry/sentry-dart/tree/v7.0.0 branch
