### ISSUE TITLE
[WEB] Sourcemaps not getting processed

### ISSUE THREAD

**Issue by shripal17** [getsentry/sentry-dart#512]
_Platform:_
- [ ]  Dart
- [ ]  Flutter Android or iOS
- [x]  Flutter Web

_IDE:_
- [ ]  VSCode
- [x]  IntelliJ/AS
- [ ]  XCode
- [ ]  Other, which one?

_split-debug-info and obfuscate (Flutter Android or iOS) or CanvasKit (Flutter Web):_
- [ ]  Enabled
- [x]  Disabled

_Platform installed with:_
- [x] pub.dev
- [ ] GitHub

Output of the command `flutter doctor -v` below:
```
❯ flutter doctor -v
[✓] Flutter (Channel stable, 2.2.2, on macOS 11.4 20F71 darwin-x64, locale en-IN)
    • Flutter version 2.2.2 at /Users/shripaljain/fvm/versions/stable
    • Framework revision d79295af24 (2 weeks ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/shripaljain/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 211.7233

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (3 available)
    • POCO X2 (mobile) • be95071d • android-arm64  • Android 11 (API 30)
    • macOS (desktop)  • macos    • darwin-x64     • macOS 11.4 20F71 darwin-x64
    • Chrome (web)     • chrome   • web-javascript • Google Chrome 91.0.4472.114

! Doctor found issues in 1 category.
```

The version of the SDK (See pubspec.lock):
**5.1.0**

---
I have the following issue:
This issue started after migrating to null-safety and upgrading sentry SDK to v5.1.0 (together)
Sentry is not processing my sourcemaps properly. As far as I have observed, it only processes and traces the first issue/error for a release using the sourcemap and source files.
All other subsequent issues are traced to dart code, they just show stacktrace of `main.dart.js`

I use this script in GitHub Actions whenever a new version of my Flutter Web app is deployed. This script, nor the Action build workflow has been changed for the null safety migration.
```bash
# $1 = version
# $2 = env (dev/prod)

echo "Doing sentry release for version $1 env $2"
sentry-cli releases new "$1"
sentry-cli releases set-commits "$1" --auto
sentry-cli releases files "$1" upload-sourcemaps . --ext dart --rewrite
sentry-cli releases files "$1" upload-sourcemaps ../lms_content/ --ext dart --rewrite --url-prefix '~/lms_content/'
sentry-cli releases files "$1" upload-sourcemaps ./build/web/ --ext map --ext js --rewrite
sentry-cli releases finalize "$1"
sentry-cli releases deploys "$1" new -e $2
```
This script works properly without any errors even before and after null safety migration.

Point to note: Last proper Flutter version when sentry always processed the sourcemaps was: v2.0.3. After the migration, we upgraded to the latest flutter version v2.2.2.

**Steps to reproduce:**
I am not sure how you would be able to reproduce this, but the only thing which comes to my mind is the null safety migration. So you can try creating a non-null-safe project, create a release with sourcemaps on sentry, deploy it, produce a synthetic error. And then, do the same process after migrating the project to null safety.

**Actual result:**
As mentioned earlier, Sentry processed and traced only the first issue for this release, subsequent releases don't trace through the sourcemap and just refer to `main.dart.js`
![image](https://user-images.githubusercontent.com/16012350/123393284-90362400-d5bb-11eb-9c40-8e1f7768a7fc.png)

**Expected result:**
Sentry should process all errors for a release, and not just the first one.

**Comment by marandaneto** [comment]
@shripal17 we'd need to investigate this, as we haven't spent much time on the web integration yet.

the issue's titles though should be because of https://github.com/getsentry/sentry-dart/issues/261#issuecomment-868265652

**Comment by marandaneto** [comment]
our test script is similar to yours https://github.com/getsentry/sentry-dart/blob/main/flutter/example/run.sh#L40-L53 so its probably a Dart/Flutter tooling issue (that may have changed) or the server-side symbolication.

> it only processes and traces the first issue/error for a release using the sourcemap and source files.

> All other subsequent issues are traced to dart code, they just show stacktrace of main.dart.js

can you link us if using sentry.io to some issues that exemplify the cases above? it'd be easier to understand and debug, thanks :)

**Comment by shripal17** [comment]
> can you link us if using sentry.io to some issues that exemplify the cases above? it'd be easier to understand and debug, thanks :)

These links are from the screenshot:
1. First issue/error which processed successfully:
https://sentry.io/organizations/i-am-in-world/issues/2474284909/?environment=dev&project=5751903&query=is%3Aunresolved+dist%3A119&statsPeriod=14d
2. Second issue/error which is fundamentally the same as the first one, but the sourcemap was not processed:
https://sentry.io/organizations/i-am-in-world/issues/2474304494/?environment=dev&project=5751903&query=is%3Aunresolved+dist%3A119&statsPeriod=14d

**Comment by marandaneto** [comment]
@shripal17 you are setting a `dist` to your events (options.dist during SDK init), but not passing it when uploading the source maps, so try to to call `sentry-cli` passing the `--dist` param and value too, that will match your events, your events contain `dist=119` for reference.
so please try that, compile again with a new dist, upload source maps using the `--dist` param and give it a try.

**Comment by shripal17** [comment]
@marandaneto 
> @shripal17 you are setting a `dist` to your events (options.dist during SDK init), but not passing it when uploading the source maps, 
I am not passing `dist` to sentry sdk:
```dart
await SentryFlutter.init(
        (options) {
          options.dsn = 'dsn_here';
          options.environment = env;
          options.release = version;
        },
      );
```
version is for e.g. dev-v1.0.0, env is dev/prod

> so try to to call sentry-cli passing the --dist param and value too, that will match your events, your events contain dist=119 for reference.
so please try that, compile again with a new dist, upload source maps using the --dist param and give it a try.

I am confused with this, which commands should I add this param to? Can you change it in the above mentioned script for me please?

**Comment by marandaneto** [comment]
@shripal17 `dist` is the equivalent of the builder number, its automatically set by the `package_info_plus` plugin if not set.

https://github.com/fluttercommunity/plus_plugins/blob/main/packages/package_info_plus/package_info_plus_web/lib/package_info_plus_web.dart
`options.dist = '123'; // or let `package_info_plus` does the job.`

**Comment by marandaneto** [comment]
@shripal17 
every time you call `sentry-cli releases files "$1" upload-sourcemaps`
always append also the `--dist` param, eg.

`sentry-cli releases files "$1" upload-sourcemaps . --ext dart --rewrite --dist "123"`

the dist here should match either the one set automatically by the SDK via `package_info_plus` or set yours manually in the `options` callback as mentioned in the message above.

**Comment by marandaneto** [comment]
I've raised docs about it https://github.com/getsentry/sentry-docs/issues/4006
just tested everything and it works, please raise a new issue if you still face issues, thanks
