### ISSUE TITLE
Flutter Frame Tracking Integration

### ISSUE THREAD

**Issue by ueman** [getsentry/sentry-dart#513]
Flutter allows the developer to read how long it took for a frame to draw. See [FrameTiming](https://api.flutter.dev/flutter/dart-ui/FrameTiming-class.html).

It would be nice if Sentry attaches a listener and sends events or add breadcrumbs if a frame took to long to draw.

Since there's no performance tracing yet, I can imagine that it's not that useful since you don't really know what caused dropped frames. Though the NavigatorObserver should help with that.

**Comment by marandaneto** [comment]
I don't think this as events or breadcrumbs are useful as they won't know where/how to fix it, this would fit either our measurements or metrics product which is being worked on as we speak.
See eg https://github.com/getsentry/sentry-cocoa/pull/1123
it requires the performance API so its blocked by it

**Comment by ueman** [comment]
In one of the recent Flutter versions (either 2.5 or 2.8) your now able to read the current [frame number](https://api.flutter.dev/flutter/dart-ui/FrameData/frameNumber.html) and `FrameTiming` also got a [frame number](https://api.flutter.dev/flutter/dart-ui/FrameTiming/frameNumber.html) property. 

This should make it possible to get at least somewhat useful metrics.

**Comment by ueman** [comment]
There's also https://api.flutter.dev/flutter/scheduler/SchedulerBinding/addPersistentFrameCallback.html which gets called every frame.

**Comment by ueman** [comment]
After raising the min versions of Dart and Flutter, the detection of slow and frozen frames is possible in pure Dart code without having to rely on native code. Thus that feature could be implemented for Linux and Windows. (Maybe on the canvaskit renderer on web too?) I believe the current implementation needs some changes to enable that though.

**Comment by marandaneto** [comment]
> After raising the min versions of Dart and Flutter, the detection of slow and frozen frames is possible in pure Dart code without having to rely on native code. Thus that feature could be implemented for Linux and Windows. (Maybe on the canvaskit renderer on web too?) I believe the current implementation needs some changes to enable that though.

Yes, I believe that would be the goal, getting the values directly from `Skia` instead of the Native SDKs.

**Comment by marandaneto** [comment]
PR is closed due to https://github.com/getsentry/sentry-dart/pull/1271#issuecomment-1562970140

**Comment by marandaneto** [comment]
Closed because of https://github.com/getsentry/sentry-dart/pull/1271#issuecomment-1562970140
We can reevaluate this in case we learn more or find out that this is actually possible within our current data model.
