### ISSUE TITLE
UI integration Tests for Flutter

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-dart#514]
the idea is that we do an E2E test where we capture an event and verify it's actually sent and ingested by sentry (in case the payload is broken/malformed).

react-native already does it https://github.com/getsentry/sentry-react-native/blob/master/.github/workflows/e2e.yml
it starts an emulator, captures an event and query the sentry API to verify its ingested.

I guess it'd be rather easy to do it with the `sentry` package because it can run in a normal test environment.

it'd be a bit harder with the native integrations, we need to verify that `sentry_flutter` has written the envelope to the disk, the envelope has been picked up and sent by the native layer.

we could start with the `sentry` package, learn and iterate over it, so when doing the `sentry_flutter`, we already know better how things would work.

**Comment by ueman** [comment]
Do we want an E2E Test for each platform?
I imagine that web and desktop could be easier than mobile because we don't need an emulator/simulator.

**Comment by marandaneto** [comment]
@ueman lets start with the `sentry` package, so no emulator for now.
not for all the platforms but I'd say environments that have a different setup or specialized code.

eg an E2E test for `sentry` on Web and non-Web.
later, E2E test for `sentry_flutter` on Android and iOS (macOS will be the same), they will run on emulators

**Comment by ueman** [comment]
Current status:

- [x] Dart application
- [ ] Flutter Web
- [ ] Flutter Mobile
- [ ] Flutter Desktop

**Comment by marandaneto** [comment]
yeah, no need for Dart Web, what really matters is that we do an E2E with the generated JS code, so Flutter Web would be fine.
I suggest doing Flutter Mobile next

**Comment by bruno-garcia** [comment]
Would be nice to verify things on the fetched event. Like:

* Does it include any processing errors (I expect those to be under `_errors` or something, we can ask the ingest team for details)
* Does it have symbolicated stack traces (i.e; any frame has file.path.endsWith('.dart') or something)
* Some basic sanity check on the event that we can extend over time

**Comment by marandaneto** [comment]
as we have the `exception` instance at runtime, we can assert that as well

**Comment by marandaneto** [comment]
We could do UI integration tests running on an emulator since E2E tests are very flaky, maybe we can do a full E2E test when its possible to run a local relay on CI.

**Comment by marandaneto** [comment]
We'd need to guarantee that all the 4 SDKs work well, no round trip serialization issues, etc...

**Comment by marandaneto** [comment]
Being done by https://github.com/getsentry/sentry-dart/pull/1061/files as well

**Comment by marandaneto** [comment]
We can actually do this with `integration_test.dart` and do something similar to `e2e_test.dart` so we know that the generated file is also valid and accepted by Relay.

**Comment by marandaneto** [comment]
I think we could do this similar to RN, which is calling Sentry's API and waiting for the response, and asserting that the data sent is actually what we're expecting.
KMP also did this recently, example https://github.com/getsentry/sentry-kotlin-multiplatform/pull/78

**Comment by marandaneto** [comment]
Right now this runs only on Android and iOS emulators, let's try to make it platform agnostic, also running on Desktop/Web, or do that later on in a different PR.
Let's focus first on get the current implementation working, and expanding on Desktop/Web later.

**Comment by denrase** [comment]
@marandaneto Should we close this or expand with more tests?
