### ISSUE TITLE
Update erickzanardo/flutter-gh-pages action

### ISSUE THREAD

**Issue by ueman** [getsentry/sentry-dart#517]
There's a new release of `erickzanardo/flutter-gh-pages`, see https://github.com/erickzanardo/flutter-gh-pages/releases

**Comment by bruno-garcia** [comment]
It's also very straight forward: https://github.com/erickzanardo/flutter-gh-pages/blob/main/action.yml

What about we just copy over the steps into a new workflow and drop the action?
Or please pin the version instead of using `v6`

**Comment by ueman** [comment]
> What about we just copy over the steps into a new workflow and drop the action?

That's fine for me, too.
