### ISSUE TITLE
Report `PlatformExceptions` with stacktraces from Dart and the native platform as 'chained exception'

### ISSUE THREAD

**Issue by ueman** [getsentry/sentry-dart#518]
[`PlatformException`](https://api.flutter.dev/flutter/services/PlatformException-class.html)s can have a native stacktrace.

As per [doc](https://develop.sentry.dev/sdk/event-payloads/exception/) an event should be able to report a chained exception, see the [examples](https://develop.sentry.dev/sdk/event-payloads/exception/#examples).

Ideally this is done with https://github.com/getsentry/sentry-dart/issues/321

Java implementation for reference: https://github.com/getsentry/sentry-java/blob/a33afef96fc5d051b27ffc81f2bb429585b3488a/sentry/src/main/java/io/sentry/SentryEvent.java#L39

**Comment by marandaneto** [comment]
@ueman this sounds like a dup of https://github.com/getsentry/sentry-dart/issues/321 to me, or what would be the difference?

**Comment by ueman** [comment]
I understood #321 like the parsing step of it, appending the stacktrace and sending it as one stacktrace.
Also we need to add the possibility of having multiple exceptions/stacktraces at all.

Though I'm fine with closing this as a dupe.

**Comment by marandaneto** [comment]
@ueman ok got it, its a more specialized issue then, on what to do with the `PlatformExceptions`, that makes sense if a PlatformExceptions can hold another native stack trace, I'm fine, and they are linked already.

**Comment by marandaneto** [comment]
Closing this one in favor of https://github.com/getsentry/sentry-dart/issues/321
