### ISSUE TITLE
sentry_flutter: Invoke default FlutterError.onError even if reportSilentFlutterErrors is false

### ISSUE THREAD

**Issue by hpoul** [getsentry/sentry-dart#522]
Right now the original FlutterError.onError is only called for **silent** errors if `reportSilentFlutterErrors` is true. This is a bit weird, I would expect that the error messages are simply passed through, always.

https://github.com/getsentry/sentry-dart/blob/679dce91d23ebcf2c0ee405add942685c32d3a20/flutter/lib/src/default_integrations.dart#L54-L68

I suggest to move `_defaultOnError!(errorDetails);` basically to the start of the method.. maybe surrounded in a try{} block?

**Comment by ueman** [comment]
Assuming `errorDetails.silent` equals `false`, the given check results to `true` because `false != true` is `true`.

So this
> Right now the original FlutterError.onError is only called for non-silent errors if reportSilentFlutterErrors is true. This is a bit weird, I would expect that the error messages are simply passed through, always.

should not happen. Could you provide an example which reproduces this?

Or do you want to just change the default value from `reportSilentFlutterErrors` to `true`? So that it, by default, always reports errors, even if they are silent?


For example, silent errors are for example raised if `Image.network` failed to load an image. However, people often have a fallback image defined, which makes this error basically a handled error. This option makes it possible to ignore this kind of problems.

**Comment by hpoul** [comment]
for silent errors the check will be false, imho the original `FlutterError.onError` should decide on it's own whether silent errors should be ignored or not, independent of sentry. Afaik the default handler will report silent errors in debug mode, but not in release mode. Why should this change when I integrate sentry?

https://api.flutter.dev/flutter/foundation/FlutterErrorDetails/silent.html

> If this is true, then the default error handler would only dump this error to the console in checked mode. In release mode, the error is ignored.

**Comment by ueman** [comment]
> for silent errors the check will be false

Yes, that's right. I thought you were talking about non-silent errors because you mentioned them in the issue.

So what you want is that silent errors are printed to console? It is not about reporting to Sentry? Please correct me if I misunderstood.

**Comment by hpoul** [comment]
ah yes, sorry, it's about seeing silent errors during development in my error console. I guess I could just completely disable sentry during development though 🤔️ I basically just want sentry *in addition* to my other logging, not instead of it.

(I wrote non-silent in the original description 🤦️ sorry for that.. I meant silent errors, fixed the description)

**Comment by ueman** [comment]
Okay, it's clear now and makes sense, so we'll keep it open until it's fixed.

**Comment by marandaneto** [comment]
@ueman looks like this is an easy one right, always calling `_defaultOnError` independently of `errorDetails.silent` or `reportSilentFlutterErrors`
