### ISSUE TITLE
Improve JSON serialization

### ISSUE THREAD

**Issue by ueman** [getsentry/sentry-dart#523]
Currently, the tests, which serialize to JSON, just include each classes `toJson()` method. However, that won't catch mistakes like https://github.com/getsentry/sentry-dart/issues/521 from happening.

We should also do 
```dart
final map = ogEvent.toJson();
final jsonString = json.encode(map);
final event = Event.fromJson(json.decode(jsonString));
...
```

**Comment by ueman** [comment]
I wonder what happens if someone adds a non serializable object to an event (or breadcrumb).
Does that break serialization?

**Comment by bruno-garcia** [comment]
> I wonder what happens if someone adds a non serializable object to an event (or breadcrumb).
> Does that break serialization?

In some SDKs it breaks the event completely where ideally we'd deal with those particular cases by logging it out and continuing with the capture. Missing data in an event is easier to troubleshoot that a missing event (users won't even know their events are not getting in). Similar situation to [this issue in the .NET SDK](https://github.com/getsentry/sentry-dotnet/issues/962). One of the proposed improvements there is: 

> Don't drop the whole event if serializing `Extra` or `Context`: We can log the error and continue

**Comment by marandaneto** [comment]
agreed with Brunos comment

**Comment by ueman** [comment]
As per docs
https://api.dart.dev/stable/2.13.4/dart-convert/JsonCodec/encode.html
we can pass a function which allows us to do that.

Something like 
```dart
final json = SentryEvent.toJson();
jsonEncode(json, toEncodable: (dynamic object) {
   return object.toString()
});
```
That would just call `toString()` on all not serializable classes, if that's ok, too?
