### ISSUE TITLE
User choice to turn on/off Error reporting

### ISSUE THREAD

**Issue by lxmirmsh1811** [getsentry/sentry-dart#547]
is it possible to turn off error reporting with a toggle? I cannot find documentation for this anywhere.
Currently I do not see a setter for "isEnabled"

**Comment by ueman** [comment]
You can set the DSN to an empty DSN (`options.dsn = "";`). This disables error reporting.
See https://pub.dev/documentation/sentry/latest/sentry/SentryOptions/dsn.html

Does this resolve your question?

**Comment by lxmirmsh1811** [comment]
> You can set the DSN to an empty DSN (`options.dsn = "";`). This disables error reporting.
> See https://pub.dev/documentation/sentry/latest/sentry/SentryOptions/dsn.html
> 
> Does this resolve your question?

Yes it does! thank you :)
