### ISSUE TITLE
Provide a toggle for error-reporting [sentry_flutter]

### ISSUE THREAD

**Issue by nachtmaar** [getsentry/sentry-dart#550]
I recently switched from an own error-reporting integration using only the sentry sdk to the `sentry_flutter` package.

What I am missing is a feature to `turn off all the integrations`. The reason this is required is that a `user` may `disallow` the `reporting of errors`. In this case, it would be nice to disable error-reporting without restarting the app (currently I have a toggle in the main method).

With all the integrations that sentry_flutter provides, runZonedGuarded etc., I feel it is hard to turn error-reporting off without having this as a feature directly baked into the SDK.

**Comment by kuhnroyal** [comment]
You could use the before send callback. Not sure what it is called exactly and return null.

**Comment by ueman** [comment]
Yep, you can do it like @kuhnroyal said.

Just set `options.beforeSend` and return null.
See https://pub.dev/documentation/sentry/latest/sentry/SentryOptions/beforeSend.html

In the Sentry app it's done like this: https://github.com/getsentry/sentry-mobile/blob/main/lib/redux/middleware/sentry_sdk_middleware.dart

Does this answer your question?

**Comment by nachtmaar** [comment]
Thank you @kuhnroyal and @ueman. Yes that does answer my question. Didn"t see that option before. Thanks a lot :)

**Comment by nachtmaar** [comment]
Tested it and it works fine :)

Here is the code for reference:

```dart
import 'package:glutyfree_app/constants.dart';
import 'package:glutyfree_app/ioc.dart';
import 'package:sentry_flutter/sentry_flutter.dart';
import 'package:shared_preferences/shared_preferences.dart';

/// An absraction over the [sentry_flutter] library
class SentryService {
  SharedPreferences sharedPreferences;
  SentryService({SharedPreferences sharedPreferences}) {
    this.sharedPreferences =
        injector.get<SharedPreferences>(key: kInjectorSharedPreferences);
  }

  Future init(AppRunner appRunner, String dsn) async {
    await SentryFlutter.init(
      (options) {
        options.dsn = dsn;
        options.beforeSend = (SentryEvent event, {dynamic hint}) {
          // send error to Sentry
          if (sharedPreferences.getBool(kSettingsWidgetErrorReporting)) {
            return event;
          }
          // do not report the error
          return null;
        };
      },
      appRunner: appRunner,
    );
  }

  void reportError(dynamic error, dynamic stackTrace) {
    Sentry.captureException(error, stackTrace: stackTrace);
  }
}
```

**Comment by markfili** [comment]
yeah, beforeSend is useful if you want to do something with the event before sending it, but what about disabling Sentry from the start of the app?

could it be possible to set the toggle somewhere closer to `init`? something like:

```
SentryFlutter.init(
    (options) {...},
    enabled: !kDebugMode,
    appRunner: ...
);
```
so that it just skips initialisation and goes directly to the appRunner but internally?

**Comment by ueman** [comment]
You can set `options.dsn` to an empty string, to disable the SDK: https://pub.dev/documentation/sentry/latest/sentry_io/SentryOptions/dsn.html

**Comment by markfili** [comment]
> You can set `options.dsn` to an empty string, to disable the SDK: https://pub.dev/documentation/sentry/latest/sentry_io/SentryOptions/dsn.html

Ah! Brilliant! I tried omitting it if a condition is true, but Sentry did not like that 😆
