### ISSUE TITLE
Support screenshot feature (via attachments)

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-dart#556]
@bruno-garcia is gonna link to the develop docs (with the specification)

the idea is that basically, it takes a SS when an event is captured and attach it to the event (via attachments).
the feature is opt-in and it should be turned on via options.

**Comment by marandaneto** [comment]
we can either implement it natively or use a plugin like https://github.com/nusanet/flutter-native-screenshot
dependencies are never a good idea though, so let's figure this out.

**Comment by ueman** [comment]
This can be done kinda easily just in Flutter. That way it's also available for all platforms (except the HTML web based renderer).

See https://api.flutter.dev/flutter/rendering/RenderRepaintBoundary/toImage.html


The drawback is that it requires a bit of manual code by the user.

**Comment by marandaneto** [comment]
nice, we can add support only for flutter non-web then, but the idea is to add it automatically.

**Comment by tryadelion** [comment]
this sounds awesome.  between this and widget tree, would it mean we'd have complete lifecycle tracing, right?

**Comment by ueman** [comment]
> this sounds awesome. between this and widget tree, would it mean we'd have complete lifecycle tracing, right?

What exactly do you mean by that? We already have complete lifecycle tracing?

**Comment by tryadelion** [comment]
not at performance level yet right? unless my pubspec has missed some big update.

**Comment by bruno-garcia** [comment]
Currently in a PR: https://github.com/getsentry/develop/pull/422/

**Comment by RobertBrunhage** [comment]
As this has now been announced here: https://blog.sentry.io/2022/07/07/introducing-mobile-screenshots-and-suspect-commits

This would be really nice to have here as well!

**Comment by ueman** [comment]
It's mostly done already in https://github.com/getsentry/sentry-dart/pull/576. Someone from Sentry or another OSS contributer just needs to pick it up and finish it. It's not on my priority list at the moment.

**Comment by AsjadSiddiqui** [comment]
Any update on this?

**Comment by ueman** [comment]
> Any update on this?

I'll repeat myself and say

> It's mostly done already in https://github.com/getsentry/sentry-dart/pull/576. Someone from Sentry or another OSS contributer just needs to pick it up and finish it. It's not on my priority list at the moment.

So, if you want, you can bring https://github.com/getsentry/sentry-dart/pull/576 up to date with develop, fix any remaining issues and it should be good to go. It shouldn't be too much work, since most of the groundwork is already done.

**Comment by denrase** [comment]
@AsjadSiddiqui We have a PR in the works, so expect an update on this soon(ish).

**Comment by ggirotto** [comment]
Is this supported in the latest build? The [docs](https://docs.sentry.io/platforms/flutter/enriching-events/screenshots/#enabling-screenshots) says to use `attachScreenshoot` option, but it seems to not exist in the latest version.

**Comment by denrase** [comment]
@ggirotto This is supported, you set this boolean flag on the `SentryFlutterOptions` when initializing the SDK. We do this in the [example app](https://github.com/getsentry/sentry-dart/blob/584e03b8d2a914665493d9ebb5202908f85ef9a0/flutter/example/lib/main.dart#L59) in this repository.

**Comment by ggirotto** [comment]
That's my bad. I was using `Sentry.init` instead `SentryFlutter.init`. Thanks for the reply

**Comment by nrajput05** [comment]
I use flutter web with `--web-renderer html`. Is that not supported for Sentry screenshots?
