### ISSUE TITLE
Check if String.fromEnvironment works

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-dart#557]
as Ive used `Platform.environment` to make it work on the Sentry Dart Plugin, maybe `String.fromEnvironment` only works for dart-defines and not machine env. var., we have to check it.

**Comment by ueman** [comment]
Should dart defines take precedence over environment variables if both are given?

**Comment by kuhnroyal** [comment]
Yea `String.from/hasEnvironment` only works for Dart defines. Thats why it returns a `const`.

**Comment by marandaneto** [comment]
> Should dart defines take precedence over environment variables if both are given?

I'd say so, fallback is the env. var.
