### ISSUE TITLE
flutter: [error] Failed to save envelope:

### ISSUE THREAD

**Issue by flutter-painter** [getsentry/sentry-dart#570]
Dear Sentry Flutter team, 
First, thanks for sharing this package !
I'm only getting started and receiving messages in sentry, yet I see an error that keeps popping up in the log : 

> flutter: [error] Failed to save envelope: MissingPluginException(No implementation found for method captureEnvelope on channel sentry_flutter)

i'm on sentry_flutter: ^4.0.6

Could it be the cause for this 'error' ?

**Comment by marandaneto** [comment]
@926 can you try to update to the latest stable version?
https://github.com/getsentry/sentry-dart/releases/tag/5.1.0

many things have been fixed, maybe that's one of them

**Comment by marandaneto** [comment]
if not, please edit your issue with the bug template https://github.com/getsentry/sentry-dart/issues/new?assignees=&labels=&template=BUG_REPORT.md so we know how your environment looks like, thanks

**Comment by marandaneto** [comment]
@926 any news?

**Comment by flutter-painter** [comment]
Hi @marandaneto,

Thanks for the reply and sorry for the delay due to holidays,
Unfortunately I cannot updated to the latest version yet, 
The app is still trailing back before null-safety, I will retry once it is upgraded and closes this.
