### ISSUE TITLE
Ability to get options.beforeSend event for native crashes

### ISSUE THREAD

**Issue by AlexBacich** [getsentry/sentry-dart#575]
When native code crash happens Sentry is capturing it into file and next app launch it sends crash report. 

Problem is that I cannot know when this happens programmatically. I can only do that for Flutter native crashes like this: 

```
SentryFlutter.init(
    (SentryFlutterOptions options) {
      options.dsn = 'my_dsn';
      options.beforeSend = (SentryEvent event, {dynamic hint}) {
        print('SENTRY EVENT INTERCEPTED');
        return event;
      };
      return options;
    },
```

What I need to do is to put my own logic before sending crash report after native crash recovery

**Comment by marandaneto** [comment]
thanks for reporting @AlexBacich 
related to #265

**Comment by ueman** [comment]
This is probably a duplicate of https://github.com/getsentry/sentry-dart/issues/441

**Comment by marandaneto** [comment]
We've decided that the solution would be initing the Native SDKs manually and implement your beforeSend callback also in the Native SDKs, this is already tracked by https://github.com/getsentry/sentry-dart/issues/265
So I'm closing this issue, please upvote the other one.
