### ISSUE TITLE
Change Flutter init to provide a way to hook into the widget tree

### ISSUE THREAD

**Issue by ueman** [getsentry/sentry-dart#577]
Currently the setup for Flutter works like this:

```dart
import 'package:flutter/widgets.dart';
import 'package:sentry_flutter/sentry_flutter.dart';

typedef AppRunner = FutureOr<void> Function();

Future<void> main() async {
  await SentryFlutter.init(
    (options) {
      options.dsn = 'https://example@sentry.io/add-your-dsn-here';
    },
    // Init your App.
    appRunner: () => runApp(MyApp()),
  );
}
```

If we change it to 

```dart
import 'package:flutter/widgets.dart';
import 'package:sentry_flutter/sentry_flutter.dart';

typedef AppRunner = FutureOr<Widget?> Function();

Future<void> main() async {
  await SentryFlutter.init(
    (options) {
      options.dsn = 'https://example@sentry.io/add-your-dsn-here';
    },
    // Init your App.
    appRunner: () => MyApp(),
  );
}

// inside SentryFlutter.init
final widget = await appRunner();
if(widget != null) {
  runApp(SentryWidget(child: widget));
}
```

we can wrap the users widget and call runApp ourself.
If the user doesn't want to do that, he can still call `runApp` himself and return null.
[`runApp`](https://api.flutter.dev/flutter/widgets/runApp.html) returns just void and is a fire and forget method, so it should work.

This would enable us to hook into the widget tree for the Screenshot feature (https://github.com/getsentry/sentry-dart/issues/556) and also for the dialog for crashes on the last run (https://github.com/getsentry/sentry-dart/issues/441)

**Comment by RohanSengupta326** [comment]
I would like to work on this issue .

**Comment by marandaneto** [comment]
the other option is just to use your own `runZonedGuarded`, but we'd ship in the SDK the `SentryWidget` class so its less boilerplate for people, how does that sound @ueman and @RohanSengupta326 ?

the example using a custom `runZonedGuarded` can be seen in the readme https://github.com/getsentry/sentry-dart/tree/main/flutter

**Comment by ueman** [comment]
I would say that at the current state of the SDK this is not needed.
It's becomes useful as soon as the Sentry SDK should provide #556 and #441 .

Shipping a widget is also a very good way to hook into the widget tree. I think that people would actually prefer that.

@marandaneto  I'm not quite sure what you mean by using your own `runZonedGuarded`?

**Comment by marandaneto** [comment]
@ueman if you have your own `runZonedGuarded`, you can call `runApp(SentryWidget(child: widget));` yourself, hence we don't do a breaking change in the SDK init that would affect literally everyone upgrading the SDK

**Comment by marandaneto** [comment]
@ueman doing that before allows people to do #556 and other features manually before we land them natively, so it still makes sense if contributed by an external contributor.

**Comment by ueman** [comment]
Ahh, I see. But that also works without your own runZoneGuarded:

```dart
import 'package:flutter/widgets.dart';
import 'package:sentry_flutter/sentry_flutter.dart';

typedef AppRunner = FutureOr<void> Function();

Future<void> main() async {
  await SentryFlutter.init(
    (options) {
      options.dsn = 'https://example@sentry.io/add-your-dsn-here';
    },
    // Init your App.
    appRunner: () => runApp(SentryWidget(MyApp())),
  );
}
```

**Comment by marandaneto** [comment]
oh yeah indeed, you're right, I was thinking that the SDK calls `runApp` automatically too.
so if we ship `SentryWidget` within the SDK and write docs/samples about it, its already a good start instead of breaking people's code, I will discuss that.

**Comment by bruno-garcia** [comment]
The idea of documenting the addition of `SentryWidget` by the user to get the feature makes sense.

**Comment by marandaneto** [comment]
If the linked issues need to hook up in the widget tree, that's fine, we're not changing how the SDK init works, but rather give them the option to call `runApp` with our `SentryWidget` wrapper and their own `MyApp`, hence closing this issue.
