### ISSUE TITLE
because flutter_br depends on both cached_network_image ^3.1.0 and sentry 4.0.0, version solving failed.

### ISSUE THREAD

**Issue by guanbo123456** [getsentry/sentry-dart#581]
_Platform:_
 Flutter Android or iOS

_IDE:_
 IntelliJ/AS

_split-debug-info and obfuscate (Flutter Android or iOS) or CanvasKit (Flutter Web):_
Disabled

_Platform installed with:_
 pub.dev

Output of the command `flutter doctor -v` below:

The output goes here...

The version of the SDK (See pubspec.lock):
**6.0.0**

---
I have the following issue:

Because sentry >=4.0.0-alpha.1 <4.1.0-nullsafety.0 depends on uuid ^2.0.0 and flutter_cache_manager >=3.0.0-nullsafety.0 depends on uuid ^3.0.0, sentry >=4.0.0-alpha.1 <4.1.0-nullsafety.0 is incompatible with flutter_cache_manager >=3.0.0-nullsafety.0.
And because cached_network_image 3.1.0 depends on flutter_cache_manager ^3.0.0 and no versions of cached_network_image match >3.1.0 <4.0.0, sentry >=4.0.0-alpha.1 <4.1.0-nullsafety.0 is incompatible with cached_network_image ^3.1.0.
So, because flutter_br depends on both cached_network_image ^3.1.0 and sentry 4.0.0, version solving failed.

pub get failed (1; So, because flutter_br depends on both cached_network_image ^3.1.0 and sentry 4.0.0, version solving failed.)

**Steps to reproduce:**
- Step

**Actual result:**
- Actual

**Expected result:**
- Result

**Comment by ueman** [comment]
You need to update your Sentry version. I think since version 5 Sentry uses `uuid: ^3.0.0`.

**Comment by marandaneto** [comment]
yep, just bump the Sentry SDK
