### ISSUE TITLE
What is the purpose of sentryClientName

### ISSUE THREAD

**Issue by M123-dev** [getsentry/sentry-dart#584]
I just came across the `sentryClientName` in the `SentryOptions` and while looking at the implementation I noticed that this value is not used anywhere in this package. Did I miss something or can the field be removed / deprecated?

**Comment by marandaneto** [comment]
indeed, the SDK is using `options.sdk.identifier` instead of `options.sentryClientName`, I'd say `options.sdk.identifier` can be removed in favor of `options.sentryClientName`, and `sentryClientName` is used as `User-Agent` when making API requests to Sentry

**Comment by marandaneto** [comment]
This should be on top of the [v7.0.0](https://github.com/getsentry/sentry-dart/tree/v7.0.0?rgh-link-date=2022-11-14T13%3A25%3A50Z) branch
