### ISSUE TITLE
Prevent duplicate issues

### ISSUE THREAD

**Issue by jin-dub** [getsentry/sentry-dart#587]
We want to ensure that a single user can not flood the Sentry server with the same issue (or many issues) over and over.

like scrollEvent error

`options.maxDeduplicationItems` option is not work for me

**Comment by marandaneto** [comment]
@jin-dub only works for the very same exception (instance reference), since we don't want to subreport exceptions, we can't do it automatically, but you can do it yourself using the `beforeSend` callback, See https://docs.sentry.io/platforms/flutter/configuration/filtering/
