### ISSUE TITLE
With Flutter 2.5, sentry-cli cannot be used - it thinks there is no debug information files when build with split-debug-info

### ISSUE THREAD

**Issue by fzyzcjy** [getsentry/sentry-dart#591]
_Platform:_
- [ ]  Dart
- [x]  Flutter Android or iOS
- [ ]  Flutter Web

_IDE:_
- [ ]  VSCode
- [x]  IntelliJ/AS
- [ ]  XCode
- [ ]  Other, which one?

_split-debug-info and obfuscate (Flutter Android or iOS) or CanvasKit (Flutter Web):_
- [x]  Enabled
- [ ]  Disabled

_Platform installed with:_
- [x] pub.dev
- [ ] GitHub

Output of the command `flutter doctor -v` below:

```
[✓] Flutter (Channel stable, 2.5.0, on Mac OS X 10.15.7 19H1323 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.5.0 at /Users/tom/opt/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (10 天前), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tom/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Users/tom/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.1.3)
    • IntelliJ at /Users/tom/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.60.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (3 available)
    • M2104K10AC (mobile) • zdfueipf99t4hmpn                     • android-arm64  • Android 11 (API 30)
    • iPhone 8 (mobile)   • 2B6C1189-40D3-4E60-898F-2A5E58ACAA3D • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4
      (simulator)
    • Chrome (web)        • chrome                               • web-javascript • Google Chrome 93.0.4577.82

! Doctor found issues in 1 category.
```

The version of the SDK (See pubspec.lock):
```
  sentry:
    dependency: "direct main"
    description:
      name: sentry
      url: "https://pub.flutter-io.cn"
    source: hosted
    version: "5.0.0"
  sentry_flutter:
    dependency: "direct main"
    description:
      name: sentry_flutter
      url: "https://pub.flutter-io.cn"
    source: hosted
    version: "5.0.0"
```

---
I have the following issue:

Hi thanks for the lib! However, sentry-cli thinks there is no debug information files when build with split-debug-info in flutter 2.5.

**Steps to reproduce:**
- `flutter clean`
- `flutter build apk --split-per-abi --obfuscate --split-debug-info myfolder --release --verbose`
- `/usr/local/bin/sentry-cli upload-dif --org rzzsdxx --project rzzsdxx --log-level=debug myfolder`

**Actual result:**

No files are uploaded!

```
  INFO    2021-09-18 11:46:44.425159 +08:00 Loaded config from /Users/tom/.sentryclirc
  DEBUG   2021-09-18 11:46:44.426030 +08:00 sentry-cli version: 1.63.1, platform: "darwin", architecture: "x86_64"
  INFO    2021-09-18 11:46:44.426059 +08:00 sentry-cli was invoked with the following command line: "/usr/local/bin/sentry-cli" "upload-dif" "--org" "rzzsdxx" "--project" "rzzsdxx" "--log-level=debug" "/Users/tom/QAPMain/Development/frontend/yplusplus/build/split-debug-info/"
  INFO    2021-09-18 11:46:44.427068 +08:00 Issuing a command for Organization: rzzsdxx Project: rzzsdxx
  DEBUG   2021-09-18 11:46:44.428406 +08:00 request GET https://sentry.io/api/0/organizations/rzzsdxx/chunk-upload/
  DEBUG   2021-09-18 11:46:44.428683 +08:00 using token authentication
  DEBUG   2021-09-18 11:46:44.428702 +08:00 retry number 0, max retries: 0
  DEBUG   2021-09-18 11:46:45.410247 +08:00 > GET /api/0/organizations/rzzsdxx/chunk-upload/ HTTP/1.1
  DEBUG   2021-09-18 11:46:45.410272 +08:00 > Host: sentry.io
  DEBUG   2021-09-18 11:46:45.410277 +08:00 > Accept: */*
  DEBUG   2021-09-18 11:46:45.410281 +08:00 > Connection: TE
  DEBUG   2021-09-18 11:46:45.410284 +08:00 > TE: gzip
  DEBUG   2021-09-18 11:46:45.410288 +08:00 > User-Agent: sentry-cli/1.63.1
  DEBUG   2021-09-18 11:46:45.410684 +08:00 > Authorization: Bearer 3d29e651***
  DEBUG   2021-09-18 11:46:45.669344 +08:00 < HTTP/1.1 200 OK
  DEBUG   2021-09-18 11:46:45.669385 +08:00 < Server: nginx
  DEBUG   2021-09-18 11:46:45.669398 +08:00 < Date: Sat, 18 Sep 2021 03:46:45 GMT
  DEBUG   2021-09-18 11:46:45.669414 +08:00 < Content-Type: application/json
  DEBUG   2021-09-18 11:46:45.669438 +08:00 < Content-Length: 297
  DEBUG   2021-09-18 11:46:45.669449 +08:00 < Connection: keep-alive
  DEBUG   2021-09-18 11:46:45.669457 +08:00 < allow: GET, POST, HEAD, OPTIONS
  DEBUG   2021-09-18 11:46:45.669466 +08:00 < access-control-allow-methods: GET, POST, HEAD, OPTIONS
  DEBUG   2021-09-18 11:46:45.669484 +08:00 < access-control-allow-headers: X-Sentry-Auth, X-Requested-With, Origin, Accept, Content-Type, Authentication, Authorization, Content-Encoding
  DEBUG   2021-09-18 11:46:45.669495 +08:00 < access-control-expose-headers: X-Sentry-Error, Retry-After
  DEBUG   2021-09-18 11:46:45.669504 +08:00 < access-control-allow-origin: *
  DEBUG   2021-09-18 11:46:45.669512 +08:00 < vary: Accept-Language, Cookie
  DEBUG   2021-09-18 11:46:45.669521 +08:00 < content-language: en
  DEBUG   2021-09-18 11:46:45.669529 +08:00 < x-frame-options: deny
  DEBUG   2021-09-18 11:46:45.669537 +08:00 < x-content-type-options: nosniff
  DEBUG   2021-09-18 11:46:45.669545 +08:00 < x-xss-protection: 1; mode=block
  DEBUG   2021-09-18 11:46:45.669553 +08:00 < x-envoy-attempt-count: 1
  DEBUG   2021-09-18 11:46:45.669562 +08:00 < x-envoy-upstream-service-time: 34
  DEBUG   2021-09-18 11:46:45.669570 +08:00 < x-served-by: getsentry-web-default-production-79f56bf547-tg6zq
  DEBUG   2021-09-18 11:46:45.669590 +08:00 < x-served-by: lb-8
  DEBUG   2021-09-18 11:46:45.669598 +08:00 < Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
  DEBUG   2021-09-18 11:46:45.669629 +08:00 response status: 200
  DEBUG   2021-09-18 11:46:45.669647 +08:00 body: {"url":"https://sentry.io/api/0/organizations/rzzsdxx/chunk-upload/","chunkSize":8388608,"chunksPerRequest":64,"maxFileSize":2147483648,"maxRequestSize":33554432,"concurrency":8,"hashAlgorithm":"sha1","compression":["gzip"],"accept":["debug_files","release_files","pdbs","sources","bcsymbolmaps"]}
  DEBUG   2021-09-18 11:46:45.673374 +08:00 searching location /Users/tom/QAPMain/Development/frontend/yplusplus/build/split-debug-info/
  DEBUG   2021-09-18 11:46:45.674936 +08:00 trying to parse dif app.android-x64.symbols
  DEBUG   2021-09-18 11:46:45.676061 +08:00 trying to parse dif app.android-arm64.symbols
  DEBUG   2021-09-18 11:46:45.676216 +08:00 trying to parse dif app.android-arm.symbols
  DEBUG   2021-09-18 11:46:45.676287 +08:00 finished location /Users/tom/QAPMain/Development/frontend/yplusplus/build/split-debug-info/
> Found 0 debug information files
> No debug information files found
  DEBUG   2021-09-18 11:46:45.676376 +08:00 request POST https://sentry.io/api/0/projects/rzzsdxx/rzzsdxx/reprocessing/
  DEBUG   2021-09-18 11:46:45.676393 +08:00 using token authentication
  DEBUG   2021-09-18 11:46:45.676406 +08:00 retry number 0, max retries: 0
  DEBUG   2021-09-18 11:46:45.676605 +08:00 > POST /api/0/projects/rzzsdxx/rzzsdxx/reprocessing/ HTTP/1.1
  DEBUG   2021-09-18 11:46:45.676627 +08:00 > Host: sentry.io
  DEBUG   2021-09-18 11:46:45.676637 +08:00 > Accept: */*
  DEBUG   2021-09-18 11:46:45.676645 +08:00 > Connection: TE
  DEBUG   2021-09-18 11:46:45.676652 +08:00 > TE: gzip
  DEBUG   2021-09-18 11:46:45.676660 +08:00 > User-Agent: sentry-cli/1.63.1
  DEBUG   2021-09-18 11:46:45.676684 +08:00 > Authorization: Bearer 3d29e651***
  DEBUG   2021-09-18 11:46:45.676694 +08:00 > Content-Length: 0
  DEBUG   2021-09-18 11:46:45.938299 +08:00 < HTTP/1.1 200 OK
  DEBUG   2021-09-18 11:46:45.938327 +08:00 < Server: nginx
  DEBUG   2021-09-18 11:46:45.938336 +08:00 < Date: Sat, 18 Sep 2021 03:46:45 GMT
  DEBUG   2021-09-18 11:46:45.938345 +08:00 < Content-Length: 0
  DEBUG   2021-09-18 11:46:45.938352 +08:00 < Connection: keep-alive
  DEBUG   2021-09-18 11:46:45.938358 +08:00 < allow: POST, OPTIONS
  DEBUG   2021-09-18 11:46:45.938364 +08:00 < access-control-allow-methods: POST, OPTIONS
  DEBUG   2021-09-18 11:46:45.938373 +08:00 < access-control-allow-headers: X-Sentry-Auth, X-Requested-With, Origin, Accept, Content-Type, Authentication, Authorization, Content-Encoding
  DEBUG   2021-09-18 11:46:45.938381 +08:00 < access-control-expose-headers: X-Sentry-Error, Retry-After
  DEBUG   2021-09-18 11:46:45.938388 +08:00 < access-control-allow-origin: *
  DEBUG   2021-09-18 11:46:45.938394 +08:00 < vary: Accept-Language, Cookie
  DEBUG   2021-09-18 11:46:45.938400 +08:00 < content-language: en
  DEBUG   2021-09-18 11:46:45.938406 +08:00 < x-frame-options: deny
  DEBUG   2021-09-18 11:46:45.938412 +08:00 < x-content-type-options: nosniff
  DEBUG   2021-09-18 11:46:45.938418 +08:00 < x-xss-protection: 1; mode=block
  DEBUG   2021-09-18 11:46:45.938424 +08:00 < x-envoy-attempt-count: 1
  DEBUG   2021-09-18 11:46:45.938430 +08:00 < x-envoy-upstream-service-time: 33
  DEBUG   2021-09-18 11:46:45.938437 +08:00 < x-served-by: getsentry-web-default-production-79f56bf547-hxmnl
  DEBUG   2021-09-18 11:46:45.938443 +08:00 < x-served-by: lb-8
  DEBUG   2021-09-18 11:46:45.938449 +08:00 < Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
  DEBUG   2021-09-18 11:46:45.938468 +08:00 response status: 200
  DEBUG   2021-09-18 11:46:45.938483 +08:00 body: 
```

**Expected result:**

Before upgrading to flutter 2.5, it can find and upload the debug info files!

p.s. the files *are* there

```
ls -al myfolder
total 40472
drwxr-xr-x   5 tom  staff      160  9 18 11:43 .
drwxr-xr-x  45 tom  staff     1440  9 18 11:46 ..
-rw-r--r--   1 tom  staff  6315664  9 18 11:43 app.android-arm.symbols
-rw-r--r--   1 tom  staff  7201872  9 18 11:43 app.android-arm64.symbols
-rw-r--r--   1 tom  staff  7199048  9 18 11:43 app.android-x64.symbols
```

**Comment by alex-myznikov** [comment]
Having this issue in my project as well after upgrading Flutter to 2.5.

**Comment by marandaneto** [comment]
@fzyzcjy thanks for reporting, checking it

**Comment by marandaneto** [comment]
I'm not sure if Flutter has changed something or its a regression, since it works with the older Flutter version and the very same sentry-cli version:

eg: sentry-cli difutil check app.android-arm.symbols

> Debug Info File Check
>   Type: elf
>   Contained debug identifiers:
>   Contained debug information:
>     > none
>   Usable: no (missing debug identifier, likely stripped)

I don't find any issue related to that here https://flutter.dev/docs/development/tools/sdk/release-notes/release-notes-2.5.0 or here https://flutter.dev/docs/release/breaking-changes#released-in-flutter-25

**Comment by fzyzcjy** [comment]
@marandaneto You are welcome. I also do find sentry works happily with older version.

**Comment by marandaneto** [comment]
my first hunch is that Flutter outputs the stripped symbols instead (so where are the unstripped files?), but I will get some help from our native team, thanks for reporting.

**Comment by fzyzcjy** [comment]
@marandaneto Looking forward to seeing it be resolved!

**Comment by alex-myznikov** [comment]
Any progress on that?

**Comment by marandaneto** [comment]
not yet, waiting our native team to have a look

**Comment by alex-myznikov** [comment]
Oh, could you please ask them to put it on top priority? This issue ruins our experience in prod mode. And as our team is on a paid plan, the management is definitely not happy about the situation :(

**Comment by mitsuhiko** [comment]
We're tracking this issue. As is stands both sentry-cli and our server side infrastructure cannot deal with this file at the moment.

**Comment by alex-myznikov** [comment]
Is there a workaround for now to get raw stack traces for logged events in format, that can be used with `flutter symbolize`?

**Comment by davidmartos96** [comment]
Is there any link to the commit in the Flutter/Dart SDK that originated this change in behavior?

**Comment by marandaneto** [comment]
no changes here https://github.com/flutter/flutter/blame/76db0d7428f73fcf2d0b4de8fb493bb4ca056380/packages/flutter_tools/lib/src/commands/symbolize.dart

there was a change in May here -> https://github.com/dart-lang/sdk/commits/main/pkg/native_stack_traces

but I'm unsure what exactly has changed.

**Comment by dnfield** [comment]
It would be helpful for someone to bisect to a specific version of Flutter where this stopped working. I am not familiar with sentry and would not be the right person to do this. However, if a specific revision can be identified it should be easier to determine what is broken or what needs to be updated.

**Comment by davidmartos96** [comment]
@dnfield I found the culprit commit to be this one. https://github.com/flutter/flutter/commit/f190bfbd8526d91866950a4c3863a561c9e2787a

I bisected with 2.2.3 counter app as a base up to 2.5.0 
The output of the upload goes from this output in the previous commit
```
Running Gradle task 'bundleRelease'...                             17.5s
✓ Built build/app/outputs/bundle/release/app-release.aab (5.3MB).
> Found 1 debug information file
> Prepared debug information file for upload
```

to not finding the debug info in the referenced culprit commit
```
Running Gradle task 'bundleRelease'...                             15.1s
✓ Built build/app/outputs/bundle/release/app-release.aab (5.3MB).
> Found 0 debug information files
> No debug information files found
```

The script I used to help with the bisect was this one. Hopefully this is enough to dig into the cause of the problem. Probably there is a better way to reproduce without running sentry-cli, but I don't have much experience with debug symbols. 
```sh
flutter clean
rm -rf debug_info
flutter build appbundle --target-platform=android-arm64 --obfuscate --split-debug-info=debug_info

# Upload check
output=$(sentry-cli --auth-token $AUTHTOKEN upload-dif --org $ORG --project $PROJECT --wait debug_info)
echo "$output"
echo ""
echo "RESULT"


if echo $output | grep -q 'No debug information files found' || echo $output | grep -q 'internal server error'; then
  echo "BAD: No debug info"
else
  echo "GOOD: With debug info"
fi
```

**Comment by dnfield** [comment]
That would be https://dart.googlesource.com/sdk.git/+log/f860b70c98d0..559da0f2d2a4

I'd suspect one of the elf related changes in there.

**Comment by fzyzcjy** [comment]
Hmm searching for "elf" results in several interesting commits in @dnfield 's link. Any updates?

**Comment by fzyzcjy** [comment]
For example: https://dart.googlesource.com/sdk.git/+/2362cd5508b7d74e40e29b5274bcc92ae445e2b7

> ... Thus, we reorder them so that writable, non-executable allocated
sections come first (due to requirements by some loaders to not sandwich
writable segments between non-writable ones), followed by non-writable,
non-executable allocated sections, followed by non-writable, executable
sections, and finally unallocated sections (to avoid differences in
memory offsets between snapshots and separate debugging information).
This ordering minimizes the number of segments that need to be created
(5 or 6, depending on whether a build ID exists).

**Comment by fzyzcjy** [comment]
Hmm searching for "elf" results in several interesting commits in @dnfield 's link. Any updates?

For example: https://dart.googlesource.com/sdk.git/+/2362cd5508b7d74e40e29b5274bcc92ae445e2b7

> ... Thus, we reorder them so that writable, non-executable allocated
sections come first (due to requirements by some loaders to not sandwich
writable segments between non-writable ones), followed by non-writable,
non-executable allocated sections, followed by non-writable, executable
sections, and finally unallocated sections (to avoid differences in
memory offsets between snapshots and separate debugging information).
This ordering minimizes the number of segments that need to be created
(5 or 6, depending on whether a build ID exists).
Since we can reorder, we also delay the creation of the build ID (if
generated) and BSS sections until finalization, instead of creating them
up front in the constructor.

I am not familiar with native. Is "build id" related to sentry's logic?

**Comment by mitsuhiko** [comment]
I will let others reply to this but the current state of affairs is that what flutter generates is definitely a broken file. This is me summarzing what @relaxolotl found out:

The generated `.dynamic` section includes bad `DT_HASH`, `DT_STRTAB` and `DT_SYMTAB` records that point to virtual addresses which are not in a valid segment. Unfortunately our ELF library ([goblin](https://github.com/m4b/goblin)) treats these as fatal whereas some other tools can skip over this.

You can however see that llvm-readelf will also complain about this:

```
/usr/local/Cellar/llvm/12.0.1/bin/llvm-readelf: warning: 'app.android-arm(flutter2.5).symbols': unable to parse DT_HASH: virtual address is not in any segment: 0x17a420
/usr/local/Cellar/llvm/12.0.1/bin/llvm-readelf: warning: 'app.android-arm(flutter2.5).symbols': unable to parse DT_STRTAB: virtual address is not in any segment: 0x17a338
/usr/local/Cellar/llvm/12.0.1/bin/llvm-readelf: warning: 'app.android-arm(flutter2.5).symbols': unable to parse DT_SYMTAB: virtual address is not in any segment: 0x17a3c0
```

The commit that introduces the reordering is this one: https://github.com/dart-lang/sdk/commit/2362cd5508b7d74e40e29b5274bcc92ae445e2b7

**Comment by fzyzcjy** [comment]
@mitsuhiko What about creating an issue in dart sdk?

**Comment by mitsuhiko** [comment]
Thanks for filing. We were not sure yet now to approach this ourselves. Ideally we don't fail fatally for things like this so there is definitely something we should do on our side to make Sentry (or even better goblin) more resilient to broken files.

**Comment by relaxolotl** [comment]
To expand on the nice summary in https://github.com/getsentry/sentry-dart/issues/591#issuecomment-927668789; The info below goes into detail about the content of the emitted debug file.

### What're ELF readers doing?
[goblin](https://github.com/m4b/goblin) and LLVM's object reading/dumping tools (llvm-readobj, llvm-dumpobj, llvm-readelf) all use the same general implementation to convert a virtual memory address (vaddr) to a "physical" address (paddr) on a file: 

Calculate the offset of the of the given vaddr from its parent segment's starting vaddr, and then add that offset to the parent segment's paddr to get the paddr you're looking for.

This makes a key assumption that **v**addr<sub>section</sub> - **v**addr<sub>parent segment</sub> = **p**addr<sub>section</sub> - **p**addr<sub>parent segment</sub>

In goblin, the logic can be found in https://github.com/m4b/goblin/blob/master/src/elf/dynamic.rs#L584-L594, and in you can find the corresponding LLVM implementation at https://github.com/llvm/llvm-project/blob/master/llvm/lib/Object/ELF.cpp#L607-L612. You can see one of the warning messages from the LLVM implementation emitted in the example output in the https://github.com/getsentry/sentry-dart/issues/591#issuecomment-927668789.

This is a pretty important detail when it comes to the `PT_DYNAMIC` segment, which contains a mapping of sections to their vaddrs. goblin and LLVM use this mapping in `PT_DYNAMIC` as a starting point to discover sections related to dynamic linking, and specifically LLVM only falls back to scanning through the sections directly if its unable to find this metadata.

### How does this relate to the Dart SDK changes?
The linked Dart SDK commit involves some work that merges segments together. I'll present things by order of discovery, which means it'll take a little bit of windup to get to why this point is important.

What I'd noticed by dumping a segment-section mapping of an example debug file is that `SHT_NOBITS` (occupies 0 space on file but >0 space in memory, which are `.rodata` or `.ehframe` below) sections are being inserted before non-`SHT_NOBITS` sections in a single segment:

```
 Section to Segment mapping:
  Segment Sections...
   00     
   01     .note.gnu.build-id .rodata .eh_frame .dynstr .dynsym .hash 
   02     .text 
   03     .bss .dynamic 
   04     .note.gnu.build-id 
   05     .dynamic 
   None   .shstrtab .debug_abbrev .debug_info .debug_line .strtab .symtab 
```

By inserting `SHT_NOBITS` sections before non-`SHT_NOBITS` sections in the same segment, the approach described above in deriving a paddr from a vaddr is broken, because the `SHT_NOBITS` sections aren't zero-filled in on the file in the exact spot they occupy. In other words, if you were to try to calculate the position of `.dynstr` on the file using the logic defined in the previous section, you'd end up reading bytes from an incorrect spot somewhere in the middle of, or even past the end of the file. This breaks the assumption described in the previous section.

I'm guessing this behaviour is happening as a result of the merge logic introduced in the linked Dart commit based off of my understanding of its diff. I may have gotten some details incorrect, so I'm open to any corrections on anything written above or below.

Again, assuming that my understanding of the diff is correct, the culprit could be one of three things:
- Sections aren't being re-ordered in a segment at all, and are directly written as-is to the file. There's some missing sorting that includes logic like placing `SHT_NOBITS` sections at the end of the segment if they share that segment with other non-`SHT_NOBITS` sections.
- New segments need to be created at every section boundary between a `SHT_NOBITS` and a non-`SHT_NOBITS` section (e.g. .dynstr .dynsym .hash should be their own segment in the above example.)
- The file should be zero-filled in all the spots where `SHT_NOBITS` sections exist so the absolute offsets in vaddrs and paddrs are identical.

### What does this mean for sentry though?
We're currently exploring an approach that fails more elegantly when we encounter these broken boundaries, but ideally the debug files would be fixed up at the source. We could produce a partial result and warn about missing symbols.

**Comment by ueman** [comment]
A fix is up for review by the Dart team: https://github.com/dart-lang/sdk/issues/47289#issuecomment-929060221

**Comment by ueman** [comment]
[The fix for the Dart SDK was released.](https://github.com/dart-lang/sdk/blob/main/CHANGELOG.md#2143---2021-09-30). I'm assuming a Flutter hotfix should arrive shortly.

**Comment by bruno-garcia** [comment]
[senty-cli was just released too](https://github.com/getsentry/sentry-cli/releases/tag/1.69.0).

It includes a 'bump symbolic' which in turn includes this PR: https://github.com/getsentry/sentry-cli/pull/1033

So for those relying on `sentry-cli` directly things should be OK. For the (~[Fastlane](https://github.com/getsentry/sentry-fastlane-plugin) and~ doesn't install it by itself) [Android Gradle](https://github.com/getsentry/sentry-android-gradle-plugin) plugins we'll need additional PRs. Ultimately there's also the [Dart plugin](https://github.com/getsentry/sentry-dart-plugin)

**Comment by ueman** [comment]
https://github.com/flutter/flutter/wiki/Hotfixes-to-the-Stable-Channel#252-september-30-2021

It's now fixed in the latest Flutter version.

**Comment by marandaneto** [comment]
using latest flutter (2.5.2) works :)

> > Found 3 debug information files
> > Prepared debug information files for upload
> > Uploading completed in 7.606s
> > Uploaded 3 missing debug information files
> > File upload complete:
> 
>   PENDING 110ce7c6-5a78-164e-9aba-b59308ce4479 (app.android-x64.symbols; x86_64 debug companion)
>   PENDING 1c13cc07-3cf3-e50a-8360-352554153463 (app.android-arm64.symbols; arm64 debug companion)
>   PENDING 8baeac1d-6c0d-9539-7b96-6ce6d489cc4e (app.android-arm.symbols; arm debug companion)
