### ISSUE TITLE
Enrich events with isolate name

### ISSUE THREAD

**Issue by kuhnroyal** [getsentry/sentry-dart#597]
Events should contain the name of the isolate they originate from.
This can be achieved via `Isolate.current.debugName`. The name is not guaranteed to be unique but could be helpful in some scenarios.

This is not Flutter specific and should probably be done by default in the Dart plugin.

**Comment by marandaneto** [comment]
isn't the `debugName` null when built in release mode?

**Comment by kuhnroyal** [comment]
Good question, I hope not :)
Will check that.

**Comment by kuhnroyal** [comment]
It's definitely there in release mode.

**Comment by ueman** [comment]
How do you setup additional isolates?

It should be pretty straight forward to just add somewhere around here:
https://github.com/getsentry/sentry-dart/blob/6ebc78025a2546edd2beea73ee653724473ee6c2/dart/lib/src/enricher/io_enricher_event_processor.dart#L90

That's in the io enricher so no need to check if isolates are available.

Even if it's null or empty in release mode it could be useful to include in debug mode.

**Comment by kuhnroyal** [comment]
Could probably add this to the `dart_context`. I can create a PR for this.

**Comment by kuhnroyal** [comment]
> How do you setup additional isolates?

`Isolate.spawn` or `compute`

**Comment by ueman** [comment]
> > How do you setup additional isolates?
> 
> `Isolate.spawn` or `compute`

Exceptions thrown in an isolate created by `compute` are basically catched and rethrown in the isolate which called `compute`. So there's nothing to gain.

**Comment by ueman** [comment]
> Could probably add this to the `dart_context`. I can create a PR for this.

Yeah, exactly. That would be awesome.
