### ISSUE TITLE
Upgrade from version 5 to 6 migration

### ISSUE THREAD

**Issue by joaovirgilicw** [getsentry/sentry-dart#601]
In version 5 we used to do something like these:
```
return SentryEvent(
        release: (await PackageInfo.fromPlatform()).version,
        environment: 'production',
        extra: extraParams,
        exception: exception,
        stackTrace: stackTrace,
      );
```
`exception` and `stackTrace` are not available anymore. Is there a migration guide?

**Comment by ueman** [comment]
The migration guide is [here](https://docs.sentry.io/platforms/dart/migration/).
SentryEvent now supports a list of exceptions and the stacktraces is now a property of SentryThread. 
See https://pub.dev/documentation/sentry/latest/sentry_io/SentryEvent/SentryEvent.html constructor.

I hope that helps.

May I ask why you create the event yourself?

**Comment by marandaneto** [comment]
you can still call:

```
var event = SentryEvent(
  throwable: throwable,
);
```

and call `Sentry.captureEvent(event, stackTrace: stackTrace)`

**Comment by joaovirgilicw** [comment]
@ueman Sorry, I hadn't seen that before. I looked at this, but we don't have `stackTrace` property anymore.

> May I ask why you create the event yourself?

It wasn't me, I'm refactoring this. Isn't this the expected way?
I see in docs this way `Sentry.captureException(exception, stackTrace: stackTrace)` but I guess in our way we pass more infos.

**Comment by marandaneto** [comment]
@joaovirgilicw take a look at the official docs, `release` and `environment` can be passed only once during SDK init btw (SDK detects a few things automatically already eg. `release`).
`extra` can be set by the `Sentry.configureScope` API (see docs)

let us know if that helps then we can close the issue, thanks

**Comment by joaovirgilicw** [comment]
@marandaneto `release`, `environment` and  `extra` aren't the problem. My problem is that `exception` and `stackTrace` aren't available anymore. 
But the `exception` I can pass via `exceptions` new property as `exceptions: [exception]`, right?

**Comment by marandaneto** [comment]
@joaovirgilicw as stated before, `stackTrace` is a method param from the capture methods eg `Sentry.captureException(event, stackTrace: stackTrace)`

if your exception is of the type `SentryException`, then yes `exceptions: [exception]`, otherwise, see my comment above https://github.com/getsentry/sentry-dart/issues/601#issuecomment-927797526

if you want to capture the `exception` that comes from the `catch` blocks, you can use the `throwable` field from the `SentryEvent` ctor.

**Comment by marandaneto** [comment]
@joaovirgilicw did it work for you? let us know, thanks

**Comment by joaovirgilicw** [comment]
@marandaneto I didn't have time to test it, sorry. I will do it asap

**Comment by marandaneto** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated. There's a large chance that this issue has been solved since.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
