### ISSUE TITLE
Documentation improvement: Initialisation

### ISSUE THREAD

**Issue by ken-ng-esotec** [getsentry/sentry-dart#602]
Could you please add a few lines in the documentation to explain the differences / pros and cons of option 1 and 2. It is a bit unclear why you might want to run your own error zone. Does doing option 2 tackle something missing from option 1?

Thanks

```
import 'package:flutter/widgets.dart';
import 'package:sentry_flutter/sentry_flutter.dart';

Future<void> main() async {
  await SentryFlutter.init(
    (options) {
      options.dsn = 'https://example@sentry.io/add-your-dsn-here';
    },
    // Init your App.
    appRunner: () => runApp(MyApp()),
  );
}
```
Or, if you want to run your app in your own error zone runZonedGuarded:
```
import 'dart:async';

import 'package:flutter/widgets.dart';
import 'package:sentry_flutter/sentry_flutter.dart';

Future<void> main() async {
  runZonedGuarded(() async {
    await SentryFlutter.init(
      (options) {
        options.dsn = 'https://example@sentry.io/add-your-dsn-here';
      },
    );

    runApp(MyApp());
  }, (exception, stackTrace) async {
    await Sentry.captureException(exception, stackTrace: stackTrace);
  });
}
```

**Comment by marandaneto** [comment]
@ken-ng-esotec there's no difference, they behave exactly the same, the idea is that if you wanna have control of your own runZonedGuarded or not, execute more stuff within it or not, there are plenty of use cases, but it's up to the final App to decide.

not sure how to word it though, suggestions? wanna contribute with a PR?

**Comment by ken-ng-esotec** [comment]
Understood, i'll put in a PR request with suggestions. Thanks

**Comment by ken-ng-esotec** [comment]
I tried to push a branch but I'm getting a 403. If you'd like to add it I propose the following:

Or, if you want to run your app in your own error zone ([runZonedGuarded](https://api.flutter.dev/flutter/dart-async/runZonedGuarded.html)) in order to capture the exception in a custom way and/or run other callbacks desired:

```dart
import 'dart:async';

import 'package:flutter/widgets.dart';
import 'package:sentry_flutter/sentry_flutter.dart';

Future<void> main() async {
  runZonedGuarded(() async {
    await SentryFlutter.init(
      (options) {
        options.dsn = 'https://example@sentry.io/add-your-dsn-here';
      },
    );

    runApp(MyApp());
  }, (exception, stackTrace) async {
    await Sentry.captureException(exception, stackTrace: stackTrace);
    // other custom callbacks desired
  });
}
```

**Comment by kuhnroyal** [comment]
> I tried to push a branch but I'm getting a 403.

Github uses a fork based workflow. You fork the repository into your own user-space and push the branch there. Then you create a PR from your fork into this repository.

**Comment by marandaneto** [comment]
yep, please do it @ken-ng-esotec :)

**Comment by marandaneto** [comment]
We're planning on adding a disclaimer that explains the differences between them, which is if you want to run some code before initiating the Flutter SDK, errors won't be captured in that code.

**Comment by marandaneto** [comment]
Closing this since `runZonedGuarded` isn't recommended anymore anyway
