### ISSUE TITLE
Empty traces can't be captured on Android

### ISSUE THREAD

**Issue by ueman** [getsentry/sentry-dart#605]
_Platform:_
- [ ]  Dart
- [x]  Flutter Android or iOS
- [ ]  Flutter Web

_IDE:_
- [x]  VSCode
- [ ]  IntelliJ/AS
- [ ]  XCode
- [ ]  Other, which one?

_split-debug-info and obfuscate (Flutter Android or iOS) or CanvasKit (Flutter Web):_
- [ ]  Enabled
- [x]  Disabled

_Platform installed with:_
- [x] pub.dev
- [ ] GitHub

Flutter Version 2.5.1

The version of the SDK (See pubspec.lock):
**6.1.0-alpha.2**

---
I have the following issue:

On Android there's an exception when sending performance traces.

**Steps to reproduce:**
Finish an empty transaction without any spans.
```dart
final transaction = Sentry.startTransaction(
      'getNewsFromWebSite',
      'load',
    );
await transaction.finish();
```

**Actual result:**
```
D/Sentry  ( 3355): onEvent fired for EnvelopeFileObserver with event type 8 on path: /data/user/0/org.example.app/cache/sentry/outbox for file a7aecfa5-7f50-4e28-a5dc-9019fffeb02d.
D/Sentry  ( 3355): Processing Envelope with 1 item(s)
D/Sentry  ( 3355): Capturing transaction: 9e15e2b3adfb41a7a34eea645e2b40a6
E/Sentry  ( 3355): Error while capturing transaction with id: 9e15e2b3adfb41a7a34eea645e2b40a6
E/Sentry  ( 3355): java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
E/Sentry  ( 3355): 	at io.sentry.SentryClient.processTransaction(SentryClient.java:473)
E/Sentry  ( 3355): 	at io.sentry.SentryClient.captureTransaction(SentryClient.java:436)
E/Sentry  ( 3355): 	at io.sentry.Hub.captureTransaction(Hub.java:564)
E/Sentry  ( 3355): 	at io.sentry.HubAdapter.captureTransaction(HubAdapter.java:162)
E/Sentry  ( 3355): 	at io.sentry.OutboxSender.processEnvelope(OutboxSender.java:166)
E/Sentry  ( 3355): 	at io.sentry.OutboxSender.processFile(OutboxSender.java:70)
E/Sentry  ( 3355): 	at io.sentry.OutboxSender.processEnvelopeFile(OutboxSender.java:103)
E/Sentry  ( 3355): 	at io.sentry.android.core.EnvelopeFileObserver.onEvent(EnvelopeFileObserver.java:59)
E/Sentry  ( 3355): 	at android.os.FileObserver$ObserverThread.onEvent(FileObserver.java:163)
E/Sentry  ( 3355): 	at android.os.FileObserver$ObserverThread.observe(Native Method)
E/Sentry  ( 3355): 	at android.os.FileObserver$ObserverThread.run(FileObserver.java:113)
D/Sentry  ( 3355): Item 1 is being captured.
W/Sentry  ( 3355): Timed out waiting for event id submission: 9e15e2b3adfb41a7a34eea645e2b40a6
D/Sentry  ( 3355): File '/data/user/0/org.example.app/cache/sentry/outbox/a7aecfa5-7f50-4e28-a5dc-9019fffeb02d' is done.
```

**Expected result:**
Transaction is being send.

**Comment by marandaneto** [comment]
@ueman can you share the code snippet of your transaction/span? just tried and it works

**Comment by ueman** [comment]
Sure.

```dart
final transaction = Sentry.startTransaction(
      'getNewsFromWebSite',
      'load',
    );
await transaction.finish();
```

I've also edited the original description.

As soon as a child span is added it works, so this works:
```dart 
final transaction = Sentry.startTransaction(
      'getNewsFromWebSite',
      'load',
    );
var child = transaction.startChild('foo');
await child.finish();
await transaction.finish();
```

**Comment by marandaneto** [comment]
@ueman could not reproduce either, a transaction came thru, would you like to debug it? maybe check if your deps are up to date since alpha2 has been released with fixes

**Comment by marandaneto** [comment]
E/Sentry  ( 3355): 	at io.sentry.SentryClient.processTransaction(SentryClient.java:473)
E/Sentry  ( 3355): 	at io.sentry.SentryClient.captureTransaction(SentryClient.java:436)

those line numbers are off for Sentry Android 5.2.0 btw, maybe you have cache of older versions?

**Comment by ueman** [comment]
Yep, you're right. Sentry was somehow the right version but Sentry_flutter was not. So sentry_android was still the old version. Thanks!
