### ISSUE TITLE
Provide functionality to make catching errors of other isolates easier

### ISSUE THREAD

**Issue by ueman** [getsentry/sentry-dart#608]
> This comes out of a discussion from https://github.com/getsentry/sentry-dart/issues/607

Currently it's not that easy to catch exceptions and errors in isolates spawned by the user.
It would be nice, if this can be made easier.

A couple of ideas:

## 1. Create a `SentrySendPort`
An isolate can be spawned by [`Isolate.spawn(entryPoint, "message");`](https://api.dart.dev/stable/2.14.3/dart-isolate/Isolate/spawn.html). It's possible to add a parameter for the `onError`-SendPort. By adding a `SentrySendPort` we can then do something like `Isolate.spawn(entryPoint, "message", onError: SentrySendPort());`.

## 2. Create extension method for isolates
Add an extension for isolates so that you can do `isolate.catchExceptionsWithSentry();` (must be called on an isolate instance). This can be achieved by using the `SentrySendPort` and [`addErrorListener(SendPort)`](https://api.dart.dev/stable/2.14.3/dart-isolate/Isolate/addErrorListener.html). 
Dart has no static extension methods, so something like `Isolate.spawnWithSentry(...)` is not possible.

**Comment by marandaneto** [comment]
`IsolateErrorIntegration` already does something similar for the main isolate, the goal here is to extract into an extension so it's easier for people to add the error listener to other isolates.
The `IsolateErrorIntegration` could use the new extension as well to simplify the integration.
