### ISSUE TITLE
License mis-match between pub.dev and Github repo

### ISSUE THREAD

**Issue by insertjokehere** [getsentry/sentry-dart#610]
_Platform:_
- [ ]  Dart
- [x]  Flutter Android or iOS
- [ ]  Flutter Web

_IDE:_
- [x]  VSCode
- [ ]  IntelliJ/AS
- [ ]  XCode
- [ ]  Other, which one?

_split-debug-info and obfuscate (Flutter Android or iOS) or CanvasKit (Flutter Web):_
- [ ]  Enabled
- [x]  Disabled

_Platform installed with:_
- [x] pub.dev
- [ ] GitHub

Output of the command `flutter doctor -v` below:

```
[✓] Flutter (Channel stable, 2.0.6, on Microsoft Windows [Version 10.0.19043.1237], locale en-NZ)
    • Flutter version 2.0.6 at C:\Users\WilliamHughes\Projects\flutter
    • Framework revision 1d9032c7e1 (5 months ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\WilliamHughes\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Android Studio
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[✓] VS Code (version 1.60.2)
    • VS Code at C:\Users\WilliamHughes\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.25.0

[✓] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 94.0.4606.61
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 94.0.992.38

• No issues found!
```

The version of the SDK (See pubspec.lock):
**6.0.1**

---

As part of a routine license audit, I noticed that on the pub.dev listing the Sentry package [is listed](https://pub.dev/packages/sentry/license) as being covered by a 3-clause BSD license, with a copyright notice that states "Copyright 2014 The Chromium Authors. All rights reserved.", whereas the LICENSE file in the repo appears to be an MIT license with a copyright notice of "Copyright (c) 2020 Sentry". I suspect the BSD license to be an error, but I'd think you might want to clarify which license you intend to cover this package?

**Steps to reproduce:**
- Navigate to https://pub.dev/packages/sentry/license
- Navigate to https://github.com/getsentry/sentry-dart/blob/main/LICENSE

**Actual result:**
- The license statements are different

**Expected result:**
- The license statements to match

**Comment by marandaneto** [comment]
Hi @insertjokehere thanks for raising this.

Initially, the package `sentry` was developed by Google and it was under their `flutter` org and later transferred to ours, we've taken ownership and rewritten most of it, that's why the license is BSD https://github.com/getsentry/sentry-dart/blob/main/dart/LICENSE and I'm not sure that we're allowed to change it, I'll check it internally, thanks.

The package `sentry_flutter` is written by Sentry only, so the license is MIT https://github.com/getsentry/sentry-dart/blob/main/flutter/LICENSE

The license of the repo is also MIT since it's written and maintained by Sentry https://github.com/getsentry/sentry-dart/blob/main/LICENSE

**Comment by insertjokehere** [comment]
Ah! That makes sense. Thanks for clarifying
