### ISSUE TITLE
Something appear recently in my app - Sentry is the cause 

### ISSUE THREAD

**Issue by mustafa-707** [getsentry/sentry-dart#612]
already opened an issues before reproduce the issue :
https://github.com/googleads/googleads-mobile-flutter/issues/393
https://github.com/flutter/flutter/issues/91194
https://github.com/HMS-Core/hms-flutter-plugin/issues/118

**Comment by marandaneto** [comment]
@mustafa-707 can you share a minimal reproducible example? why do you think it's sentry? sentry is an error monitoring SDK and there's no sentry UI/widget or anything, not sure how it could be related to sentry itself.

**Comment by mustafa-707** [comment]
After much investigation I found sentry cause the problem and after removing it the issues gone , yes idk why sentry root function is doing with ui , but it's only appears when upgrade to flutter 2.5.x , the  minimal reproducible  is just put sentry with this 2 kind of plugins examples
[huawei_account] or [google_mobile_ads]

**Comment by marandaneto** [comment]
@mustafa-707 can you remove either `huawei_account` or `google_mobile_ads` from your project and see if it still happens? I just want to isolate the problem before spending time on it, I don't see how Sentry could be doing it, the other 2 SDKs do have UI stuff.

Also, I need the code snippet of your Sentry SDK init code, I need to check which features you have enabled or disabled

**Comment by mustafa-707** [comment]
```
 runZonedGuarded(() async {
        await SentryFlutter.init(
       (options) {
     options.dsn = 'https://xxx@xxx.ingest.sentry.io/xxxx';
   },
    appRunner: () => runApp(
        //Phoenix(child: 
        MultiProvider(
          providers: [
            ChangeNotifierProvider<MainProvider>(create: (context) => MainProvider()),
            ChangeNotifierProvider<LocationProvider>(create: (context) => LocationProvider()),
            ChangeNotifierProvider<TabBarProvider>(create: (context) => TabBarProvider()),
            ChangeNotifierProvider<Provider1>(create: (context) => Provider1()),
          ],
          child:AppLifecycleReactor()
      ),
   // )
    ),
     );
  },(error, stackTrace) {
   FirebaseCrashlytics.instance.recordError(error, stackTrace);
  });
```

the problem is with the `huawei_account` or `google_mobile_ads` functions and UI because two of them is using their native UX , i already before opening this issue I thought it was from them but after it we found that sentry effect their functionality ,so if i removed this two packages the problem for sure will gone , I want this two packages and for me it's more importante than keeping sentry , but sentry is a good tool and ofc its good to be using it all

**Comment by marandaneto** [comment]
@mustafa-707 please follow our readme here https://github.com/getsentry/sentry-dart/tree/main/flutter

if you are using a custom `runZonedGuarded`, you cannot use the SDK `appRunner` callback, see the section:

> Or, if you want to run your app in your own error zone runZonedGuarded

also, if you call `FirebaseCrashlytics` in your error callback, what for are you adding sentry?

please fix your code that uses a `runZonedGuarded` and try again, maybe that fixes the issue, otherwise, we will need a minimal reproducible example since I cannot reproduce myself.

**Comment by mustafa-707** [comment]
i tried to do that before and it didn't fix the issue .

**Comment by marandaneto** [comment]
@mustafa-707 so again, I need a minimal reproducible example otherwise I have to close the issue since I can't reproduce it

**Comment by marandaneto** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
