### ISSUE TITLE
`event.origin` tag should be `apple` or `ios` and `macos` instead of `ios` for both platforms

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-dart#614]
https://github.com/getsentry/sentry-dart/blob/main/flutter/ios/Classes/SentryFlutterPluginApple.swift#L243

https://github.com/getsentry/sentry-docs/pull/4234/files#r723878494

**Comment by bruno-garcia** [comment]
Since we're on the native layer, we could check if we're running on mac or iOS and if it's mac or ios. And be specific about it.
Make sure to update the docs (linked in the description) to include the new tag
