### ISSUE TITLE
(options.httpClient): Monitor http events 

### ISSUE THREAD

**Issue by Santi92** [getsentry/sentry-dart#617]
_Platform:_
- [x]  Dart
- [x]  Flutter Android or iOS
- [ ]  Flutter Web

_IDE:_
- [ ]  VSCode
- [x]  IntelliJ/AS
- [ ]  XCode
- [ ]  Other, which one?

_Platform installed with:_
- [x] pub.dev
- [ ] GitHub

Output of the command `flutter doctor -v` below:

```bash
[✓] Flutter (Channel unknown, 2.5.1, on macOS 11.2.3 20D91 darwin-x64, locale
    en-CO)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
[✓] VS Code (version 1.61.0)
[✓] VS Code (version 1.57.0)
[✓] VS Code (version 1.56.2)
[✓] Connected device (2 available)

• No issues found!

```

The output goes here...

The version of the SDK (See pubspec.lock):
**6.0.1**

---
I have the following issue:

Hi Team Sentry.

I have inquired about what Sentry offers for our workflow, but I have a couple of doubts, I don't know if it really is a Bug or I really am missing something.

Well the point is to be able to populate Sentry without so much effort in a real Flutter application.

For example, the HttpClient, in order to have a record of the requests, transactions must be created such as:
import 'package: sentry / sentry.dart';

```dart
final transaction = Sentry.startTransaction (
  'webrequest',
  'request',
  bindToScope: true,
);

var client = SentryHttpClient (networkTracing: true);
try {
var uriResponse = await client.post ('https://example.com/whatsit/create',
     body: {'name': 'doodle', 'color': 'blue'});
 print (await client.get (uriResponse.bodyFields ['uri']));
} finally {
 client.close ();
}

await transaction.finish (status: SpanStatus.ok ());
````

[Link Documentation ](https://docs.sentry.io/platforms/dart/usage/advanced-usage/#performance-monitoring-for-http-requests)

What I am going to do is that to obtain these HTTP measurements, the previous code must be implemented in each request?

For example, if my httpCliente passes it in the options, shouldn't this be done automatically?
For instance :

```dart
  await SentryFlutter.init(
      (options) {
        options.dsn = sentryDsn;
        options.debug = false;
        options.httpClient = myHttpClient;
      },
    );

```

**Steps to reproduce:**
- Step

**Actual result:**
- Actual

**Expected result:**
- Result

**Comment by marandaneto** [comment]
@Santi92 thanks for raising.

No, `options.httpClient` is something else, it's the Client for Sentry's transport, which is sending events to the Sentry server, you should not touch this unless you know what you are doing (a custom transport for some reason).

about the code snippet, that is just a code snippet, a real case would be:

// starts a transaction when you are about to load/loading a new screen
final transaction = Sentry.startTransaction (
  'nameOfMyScreen',
  'ui.load',
  bindToScope: true,
);

// renders widgets
// does HTTP requests (using SentryHttpClient)
// query database
// etc

// finishes the transaction when the screen is loaded

for all of your HTTP requests, you have to use always the `SentryHttpClient` which is creating spans automatically for you as a child of the transaction `nameOfMyScreen`.
