### ISSUE TITLE
Update warning for iOS

### ISSUE THREAD

**Issue by danielgomezrico** [getsentry/sentry-dart#628]
Using `sentry_flutter: 6.0.1`

In your dashboard I see this warning:

![image](https://user-images.githubusercontent.com/76348/139067939-d5b0e012-d599-4dcc-8cd8-a59f75ef381f.png)

**Comment by ueman** [comment]
It'll be in the next version: https://github.com/getsentry/sentry-dart/pull/627

**Comment by marandaneto** [comment]
exactly what @ueman said.

**Comment by jscarl** [comment]
can we know when an exact date for the next release?
