### ISSUE TITLE
Serialization error for enums in transactions

### ISSUE THREAD

**Issue by kuhnroyal** [getsentry/sentry-dart#632]
_Platform:_
- [ ]  Dart
- [x]  Flutter Android or iOS
- [ ]  Flutter Web

_IDE:_
- [ ]  VSCode
- [x]  IntelliJ/AS
- [ ]  XCode
- [ ]  Other, which one?

_split-debug-info and obfuscate (Flutter Android or iOS) or CanvasKit (Flutter Web):_
- [ ]  Enabled
- [x]  Disabled

_Platform installed with:_
- [x] pub.dev
- [ ] GitHub

Output of the command `flutter doctor -v` below:

The output goes here...

The version of the SDK (See pubspec.lock):
**6.1.0**

---
I have the following issue:

Debug logging reveals that my transactions are not sent to the server due to a serialization error due to enum usage.
This was previously also the case for events but has been fixed, the same fix probably needs to be applied for transactions.

```
[sentry] [error] Error while capturing transaction with id: f6dc944ee9b24889818ba0bfcd6dbad5
         Converting object to an encodable object failed: Instance of 'ConnectivityResult'
```

In this case I am enriching the event with the `ConnectivityResult` from the `connectivity_plus` package, the same enricher works for normal events.

**Expected result:**
I expect the transaction to be correctly serialized.

**Comment by marandaneto** [comment]
will have a look, thanks @kuhnroyal

**Comment by marandaneto** [comment]
@kuhnroyal where are you setting this object? how can I reproduce it? SentryTransaction inherits `toJson` from SentryEvent, wondering how this would happen

**Comment by kuhnroyal** [comment]
Not doing anything special. The enum is added in an event processor. All events contain the correctly serialized enum and they show up in Sentry.

Yesterday I started playing around with transactions but nothing showed up. After enabling debug Logs I saw this error.

When I remove the event processor the transaction shows up in Sentry.

I am not manually adding anything to the scope or transaction.

**Comment by marandaneto** [comment]
@kuhnroyal yep but I'd like to know where exactly are you adding the enum to, event.contexts, event.extra, so I can debug it

**Comment by marandaneto** [comment]
ok I've found it how it could happen, thanks

**Comment by marandaneto** [comment]
@kuhnroyal please try it out :)

**Comment by kuhnroyal** [comment]
Works, thanks for the quick release!
