### ISSUE TITLE
e2e tests should run on min. supported sdk versions

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-dart#636]
running on the min. supported SDK version, we'd be able to catch back-compatibility during CI run and avoid #634 similar issues

**Comment by ueman** [comment]
Currently you can't run the tests in the Flutter SDK on Flutter 2.0.x up until at least 2.2.3

**Comment by marandaneto** [comment]
> Currently you can't run the tests in the Flutter SDK on Flutter 2.0.x up until at least 2.2.3

why so? do we use features on tests that are not available under the min. supported Dart/Flutter SDK? if so, we'd need to adjust the tests then.

**Comment by ueman** [comment]
It's because of the dev_dependencies having higher requirements than the minimal supported Flutter version.

**Comment by marandaneto** [comment]
> It's because of the dev_dependencies having higher requirements than the minimal supported Flutter version.

Gotcha, we'd need to downgrade then to make it work, it's better to detect issues on CI in advance rather than using the latest tooling on dev deps.
