### ISSUE TITLE
Consider making Dart stack trace available in events

### ISSUE THREAD

**Issue by kuhnroyal** [getsentry/sentry-dart#640]
I want to log some events to console in the `beforeSend` callback (for example from the `runZonedGuarded` integration) but the original `StackTrace` is not available and I can't find a good way to log the `SentryStackTrace`.

Does this make sense?

**Comment by marandaneto** [comment]
@kuhnroyal the exception should have its stack trace, eg `(event.throwable as Error).stackTrace`, it could be probably null or not an `Error` but it should be in most the cases.

the other option is not initing the SDK for debug builds, so the standard `runZonedGuarded` will log to the console.

does that help?

**Comment by kuhnroyal** [comment]
The `event.throwable.stackTrace` may work in some cases but not for errors in the isolate/runZonedGuarded integrations.

> the other option is not initing the SDK for debug builds, so the standard runZonedGuarded will log to the console.

I know this would work but we capture a lot of stuff even in debug builds and use a custom `logging` integration (hopefully this can be replaced soon) to also log everything to console.

So basically all our code uses the `logging` package and gets written to console and converted to sentry events.
The only thing we are missing locally are the isolate/runZonedGuarded errors.

**Comment by ueman** [comment]
>  use a custom `logging` integration (hopefully this can be replaced soon) 

You might want to take a look (and leave feedback) at https://github.com/getsentry/sentry-dart/pull/631

**Comment by kuhnroyal** [comment]
@ueman Yes, I have seen this, that's why I am hopeful to remove the custom integration :)

**Comment by marandaneto** [comment]
we could technically call `options.logger(args)` to the integrations that capture events automatically, if `debug` is enabled, the `dartLogger` is assigned and it will print out using `log` from `dart.developer`, how does that sound?

**Comment by marandaneto** [comment]
RunZonedGuardedIntegration, IsolateErrorIntegration, FlutterErrorIntegration and FailedRequestClient would benefit

**Comment by kuhnroyal** [comment]
That sounds good, I could configure a custom `SentryLogger` then.

**Comment by marandaneto** [comment]
would you like to submit a PR @kuhnroyal ? adding such logs before calling `hub.captureEvent`?
