### ISSUE TITLE
DSN Argument error

### ISSUE THREAD

**Issue by purplenoodlesoop** [getsentry/sentry-dart#647]
Hello!

There seems to be an incorrect level of response to the missing DSN. [The problem is located here](https://github.com/getsentry/sentry-dart/blob/main/dart/lib/src/hub.dart#L51).

In my opinion, missing DSN should be addressed using an assertion, and not an `ArgumentError`. The assertion will be still visible in the debug mode, but will not affect the behavior of the application in the release mode.

I will be more than happy to submit a PR :)

**Comment by marandaneto** [comment]
@purplenoodlesoop thanks for the feedback.
DSN is mandatory to initialize the SDK, in case you want to call the SDK init, but keep it deactivated, set it to empty, `''`

**Comment by purplenoodlesoop** [comment]
@marandaneto got it, thanks for the response!
