### ISSUE TITLE
Error uploading attachment on Android

### ISSUE THREAD

**Issue by brandonwatkins** [getsentry/sentry-dart#648]
_Platform:_
- [ ]  Dart
- [X]  Flutter Android or iOS
- [ ]  Flutter Web

_IDE:_
- [ ]  VSCode
- [X]  IntelliJ/AS
- [ ]  XCode
- [ ]  Other, which one?

_split-debug-info and obfuscate (Flutter Android or iOS) or CanvasKit (Flutter Web):_
- [ ]  Enabled
- [X]  Disabled

_Platform installed with:_
- [X] pub.dev
- [ ] GitHub

Output of the command `flutter doctor -v` below:

`[✓] Flutter (Channel stable, 2.5.3, on macOS 11.5.2 20G95 darwin-x64, locale en-AU)
    • Flutter version 2.5.3 at /Users/brandonwatkins/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (7 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/brandonwatkins/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.1.4)
    • IntelliJ at /Users/brandonwatkins/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/201.8743.12/IntelliJ IDEA CE.app
    • Flutter plugin version 48.0.3
    • Dart plugin version 201.8538.45

[✓] IntelliJ IDEA Community Edition (version 2020.1.4)
    • IntelliJ at /Users/brandonwatkins/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/201.8743.1/IntelliJ IDEA CE.app
    • Flutter plugin version 48.0.3
    • Dart plugin version 201.8538.45

[✓] VS Code (version 1.62.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • SM G965F (mobile)      • 23c0de1c180c7ece                     • android-arm64  • Android 10 (API 29)
    • iPhone 12 Pro (mobile) • 652B2D0F-1FE5-4633-BD2B-407425E3B312 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64     • macOS 11.5.2 20G95 darwin-x64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 96.0.4664.55

• No issues found!
`

The version of the SDK (See pubspec.lock):
**6.1.2**

---
I have the following issue:

I am trying to upload a local sqlite database to Sentry as an attachment. I have been able to successfully do this with iOS devices but Android is failing.

**Steps to reproduce:**
`
final dbFolder = await getApplicationDocumentsDirectory();
final file = File(p.join(dbFolder.path, 'app_data.sqlite'));

final attachment = SentryAttachment.fromUint8List(
          file.readAsBytesSync(), 'app_data.sqlite',
          contentType: 'application/x-sqlite3');

 await Sentry.captureMessage(
        "Database upload",
        params: params,
        withScope: (scope) {
          scope.addAttachment(attachment);
        },
      );

`

**Actual result:**

Code completes however an error is thrown and the message is never sent to Sentry

`
I/flutter (31744): Uploading database...
I/m.mm.panpac.ua(31744): NativeAlloc concurrent copying GC freed 263082(12MB) AllocSpace objects, 70(9532KB) LOS objects, 67% free, 2954KB/9098KB, paused 896us total 116.787ms
D/Sentry  (31744): onEvent fired for EnvelopeFileObserver with event type 8 on path: /data/user/0/com.mm.panpac.uat/cache/sentry/outbox for file 9dc94b90-5f14-4d4e-a7c9-5a9e50a1e334.
I/flutter (31744): Uploaded database successfully
D/Sentry  (31744): Processing Envelope with 2 item(s)
E/Sentry  (31744): Item failed to process.
E/Sentry  (31744): com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected STRING but was BEGIN_OBJECT at path $.params[0]
E/Sentry  (31744): 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
E/Sentry  (31744): 	at com.google.gson.TypeAdapter.fromJsonTree(TypeAdapter.java:285)
E/Sentry  (31744): 	at io.sentry.UnknownPropertiesTypeAdapterFactory$UnknownPropertiesTypeAdapter.read(UnknownPropertiesTypeAdapterFactory.java:128)
E/Sentry  (31744): 	at io.sentry.UnknownPropertiesTypeAdapterFactory$UnknownPropertiesTypeAdapter.read(UnknownPropertiesTypeAdapterFactory.java:58)
E/Sentry  (31744): 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
E/Sentry  (31744): 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
E/Sentry  (31744): 	at com.google.gson.TypeAdapter.fromJsonTree(TypeAdapter.java:285)
E/Sentry  (31744): 	at io.sentry.UnknownPropertiesTypeAdapterFactory$UnknownPropertiesTypeAdapter.read(UnknownPropertiesTypeAdapterFactory.java:128)
E/Sentry  (31744): 	at io.sentry.UnknownPropertiesTypeAdapterFactory$UnknownPropertiesTypeAdapter.read(UnknownPropertiesTypeAdapterFactory.java:58)
E/Sentry  (31744): 	at com.google.gson.Gson.fromJson(Gson.java:927)
E/Sentry  (31744): 	at com.google.gson.Gson.fromJson(Gson.java:865)
E/Sentry  (31744): 	at io.sentry.GsonSerializer.deserialize(GsonSerializer.java:116)
E/Sentry  (31744): 	at io.sentry.OutboxSender.processEnvelope(OutboxSender.java:125)
E/Sentry  (31744): 	at io.sentry.OutboxSender.processFile(OutboxSender.java:70)
E/Sentry  (31744): 	at io.sentry.OutboxSender.processEnvelopeFile(OutboxSender.java:103)
E/Sentry  (31744): 	at io.sentry.android.core.EnvelopeFileObserver.onEvent(EnvelopeFileObserver.java:59)
E/Sentry  (31744): 	at android.os.FileObserver$ObserverThread.onEvent(FileObserver.java:163)
E/Sentry  (31744): 	at android.os.FileObserver$ObserverThread.observe(Native Method)
E/Sentry  (31744): 	at android.os.FileObserver$ObserverThread.run(FileObserver.java:113)
E/Sentry  (31744): Caused by: java.lang.IllegalStateException: Expected STRING but was BEGIN_OBJECT at path $.params[0]
E/Sentry  (31744): 	at com.google.gson.internal.bind.JsonTreeReader.nextString(JsonTreeReader.java:180)
E/Sentry  (31744): 	at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:402)
E/Sentry  (31744): 	at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:390)
E/Sentry  (31744): 	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
E/Sentry  (31744): 	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
E/Sentry  (31744): 	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
E/Sentry  (31744): 	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:63)
E/Sentry  (31744): 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
E/Sentry  (31744): 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
E/Sentry  (31744): 	... 18 more
`

**Expected result:**
Code completes without errors and the message with the attachment is successfully uploaded to Sentry

**Comment by marandaneto** [comment]
@brandonwatkins thanks for reporting.
based on the logs, it's not related to the attachment but rather the event itself, since it fails during event deserialization.
could you please enable the `debug` false during SDK init and copy-paste the logs?
also please, set up a `beforeSend` callback, https://docs.sentry.io/platforms/flutter/configuration/filtering/#filtering-error-events
and log in the console `event.toJson()` so I can debug the payload on my end, thanks a lot.

**Comment by marandaneto** [comment]
@brandonwatkins any news here? thanks

**Comment by marandaneto** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
