### ISSUE TITLE
Transform LogRecord#time to UTC

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-dart#652]
https://github.com/getsentry/sentry-dart/blob/main/logging/lib/src/extension.dart#L12

timestamp should be UTC and the loggingtime gets local time

**Comment by marandaneto** [comment]
@ueman would you like to have a look at it? thanks

**Comment by ueman** [comment]
It's probably just `time.toUtc()` but I'll have to double check.

**Comment by marandaneto** [comment]
> It's probably just `time.toUtc()` but I'll have to double check.

yep, I guess so, https://github.com/dart-lang/logging/blob/master/lib/src/log_record.dart#L37
so calling `toUtc` should do :)
