### ISSUE TITLE
Logging integration is only showing 'severe' category logs in Sentry

### ISSUE THREAD

**Issue by SogoGolf** [getsentry/sentry-dart#654]
Just tried the new ```sentry_logger``` package. All installed fine etc. 

When we tried some test log messages, the only one that made it through to Sentry was the "severe" category message. Is this by design ? Or do we need to set something up in Sentry to allow the different log categories to show up ?

```
var test = Logger("TestLoggerForSentry");
test.warning("does this show in sentry ?");   
test.severe("some severe message!");  //this is only message that appeared in Sentry
test.fine("a fine message");
test.finer("a finer message");
test.finest("a finest message");
test.info("an info message");
test.shout("a shout message");
```

**Comment by ueman** [comment]
By default, the minimal log level which is recorded should be `info`. See https://github.com/getsentry/sentry-dart/blob/6b2a874e794068597bfe9778888d4cf3ed349069/logging/lib/src/logging_integration.dart#L17-L21 Did you configure it differently?

**Comment by marandaneto** [comment]
@ueman we might need to change the logic of comparing log levels, we compare the int value of the level right, but eg `OFF` has the value of 2000, so it'd log but its rather wrong, we should bail if it's `OFF`.

**Comment by marandaneto** [comment]
> Just tried the new `sentry_logger` package. All installed fine etc.
> 
> When we tried some test log messages, the only one that made it through to Sentry was the "severe" category message. Is this by design ? Or do we need to set something up in Sentry to allow the different log categories to show up ?
> 
> ```
> var test = Logger("TestLoggerForSentry");
> test.warning("does this show in sentry ?");   
> test.severe("some severe message!");  //this is only message that appeared in Sentry
> test.fine("a fine message");
> test.finer("a finer message");
> test.finest("a finest message");
> test.info("an info message");
> test.shout("a shout message");
> ```

everything below `severe` is just a breadcrumb, so it won't be reported to sentry unless you capture a message or exception.

eg:

```
var test = Logger("TestLoggerForSentry");
test.warning("does this show in sentry ?");  // its a breadcrumb
test.fine("a fine message"); // wont be a breadcrumb, since its less than INFO
test.finer("a finer message"); // wont be a breadcrumb, since its less than INFO
test.finest("a finest message"); // wont be a breadcrumb, since its less than INFO
test.info("an info message");  // its a breadcrumb
test.shout("a shout message"); // it captures an error event
test.severe("some severe message!"); // it captures an error event
 Sentry.captureMessage('message'); // it captures a message event 
```

**Comment by kuhnroyal** [comment]
What about `test.info("an info message", error, stackTrace);`?
Does this automatically create an event?

**Comment by ueman** [comment]
> What about `test.info("an info message", error, stackTrace);`? Does this automatically create an event?

No, but it does log the exception and stacktrace in addition to the message as a breadcrumb.

**Comment by marandaneto** [comment]
> @ueman we might need to change the logic of comparing log levels, we compare the int value of the level right, but eg `OFF` has the value of 2000, so it'd log but its rather wrong, we should bail if it's `OFF`.

@ueman should we create an issue for that? or does the logging library bail `off` automatically and the sentry integration will never be called?

**Comment by ueman** [comment]
I would say we create a ticket, because we can just close it, if it's not relevant :D

**Comment by marandaneto** [comment]
> I would say we create a ticket, because we can just close it, if it's not relevant :D

https://github.com/getsentry/sentry-dart/issues/656

**Comment by marandaneto** [comment]
@sogogolf any news here?

**Comment by SogoGolf** [comment]
Thanks for the follow up. Im a little confused by the thread above - is this considered a bug or is it behaving as intended ?

**Comment by marandaneto** [comment]
> Thanks for the follow up. Im a little confused by the thread above - is this considered a bug or is it behaving as intended ?

The thread above is already solved thru https://github.com/getsentry/sentry-dart/issues/656 so please ignore it.

https://github.com/getsentry/sentry-dart/issues/654#issuecomment-988569402 and https://github.com/getsentry/sentry-dart/issues/654#issuecomment-988612554 require your input tho, thanks.

**Comment by marandaneto** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated. There's a large chance that this issue has been solved since.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
