### ISSUE TITLE
Make sentry_logging JS friendly

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-dart#655]
https://pub.dev/packages/sentry_logging/score

the extension class imports `import 'package:sentry/sentry_io.dart';`

**Comment by marandaneto** [comment]
@ueman was the import a mistake or intentional?

**Comment by ueman** [comment]
It's by mistake :( I've already seen it, too. I'll hope to find some time in the next few days to fix the `logging` issues.
