### ISSUE TITLE
Fix all `unnecessary_import` with the new `analyze` tooling from Dart 2.15

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-dart#659]
that blocks us of releasing https://github.com/getsentry/sentry-dart/pull/658 and other bug fixes

a workaround could be adding an exception to the analyze rules for now

**Comment by marandaneto** [comment]
likely addressed by https://github.com/getsentry/sentry-dart/pull/643

**Comment by ueman** [comment]
This can be closed as #643 is merged @marandaneto, right?

**Comment by marandaneto** [comment]
@ueman almost, need a PR to remove all the `unnecessary_import: ignore` now, that's all we need to do likely.
