### ISSUE TITLE
`ConcurrentModificationError` in when finishing span

### ISSUE THREAD

**Issue by Kavantix** [getsentry/sentry-dart#662]
I have a lot of reports of a `ConcurrentModificationError` coming from this for loop:
https://github.com/getsentry/sentry-dart/blob/58de5ac0943ec9bd5e15a4fdcd7a4b5ae9411585/dart/lib/src/sentry_tracer.dart#L31-L35

I believe this happens when a new span starts before the finish method is done.
It is hard to reproduce manually, but a fix I see is to make a copy of children before starting to iterate over them.

**Comment by marandaneto** [comment]
@Kavantix thanks, will check that
can you link me to a sentry issue or copy-paste the stack trace?

**Comment by Kavantix** [comment]
@marandaneto that’s actually the most annoying part.
In sentry the only thing in the stacktrace is the line of the ListIterator that throws the exception nothing else.
Had to get it manually reproduced with unhandled exceptions turned on to find that it originated from the for statement I linked.
So for a few weeks I have thousands of these errors with basically no stack traces.

**Comment by Kavantix** [comment]
@marandaneto btw, the notification I got from you message did not include the part you edited so it is by chance that I see your question🙈

**Comment by Kavantix** [comment]
This is the stacktrace in sentry:
```
ConcurrentModificationError: Concurrent modification during iteration: Instance(length:15) of '_GrowableList'.
  File "iterable.dart", line 336, col 7, in ListIterator.moveNext
```

**Comment by marandaneto** [comment]
thanks @Kavantix 
did you manage to reproduce manually? how? that would help fixing it, thanks

**Comment by marandaneto** [comment]
I see that we've missed a few safe guards eg
if `finish` was already called, we should not allow calling it again, eg Java https://github.com/getsentry/sentry-java/blob/main/sentry/src/main/java/io/sentry/Span.java#L138-L141

if `finish` was called, we should not allow calling `startChild`, so we'd avoid such problems.
thanks for pointing it out.

**Comment by marandaneto** [comment]
@Kavantix are you calling the span `finish` and `startChild` from different Isolates? or how is your code structured to make it possible? thanks

**Comment by Kavantix** [comment]
I’m using the httpclient tracking and setting the global scope in parts of the app.
So it’s possible for a new transaction to start before finish is done (I’m also on purpose not awaiting the finish)

**Comment by marandaneto** [comment]
@Kavantix thanks, 2 questions.

What do you mean by `setting the global scope in parts of the app`?
Also, do you mean -> for a new `span` to start before the finish is done, right?

What I'm trying to understand is how the method `finish` and `startChild` runs in parallel since Dart is single-threaded.
Even if you don't `await` the finish, it's still an event loop that runs code synchronously.

**Comment by ueman** [comment]
For a [`ConcurrentModificationError`](https://api.dart.dev/stable/2.15.0/dart-core/ConcurrentModificationError-class.html) to be thrown, there doesn't necessarily need to be a concurrent access. It could also happen when you're adding or removing things to the collection you're currently iterating.

**Comment by Kavantix** [comment]
@marandaneto I meant the bindToScope parameter
And yes that’s what I mean and that runs concurrently because of the awaits inside the loop (which is not the same as in parallel)

**Comment by bruno-garcia** [comment]
Does it make sense to just clone the list when we're going to iterate it to create the transaction?

**Comment by marandaneto** [comment]
> For a [`ConcurrentModificationError`](https://api.dart.dev/stable/2.15.0/dart-core/ConcurrentModificationError-class.html) to be thrown, there doesn't necessarily need to be a concurrent access. It could also happen when you're adding or removing things to the collection you're currently iterating.

Yep, that's clear, but we don't do that, so I'm trying to understand how it happens in the first place.

**Comment by marandaneto** [comment]
> Does it make sense to just clone the list when we're going to iterate it to create the transaction?

Yes but I'd not solve it this way, I'd solve it as suggested on https://github.com/getsentry/sentry-java/issues/1840
No need of creating a new span, allocate memory, and not use it at all, just bail if the method `finish` was already called.

**Comment by marandaneto** [comment]
> @marandaneto I meant the bindToScope parameter And yes that’s what I mean and that runs concurrently because of the awaits inside the loop (which is not the same as in parallel)

gotcha, that makes sense, since you're not `awaiting` the `finish` method, that could happen, thanks.

**Comment by marandaneto** [comment]
Draft for discussion https://github.com/getsentry/sentry-dart/pull/664
