### ISSUE TITLE
Expose auto transaction idle time via options

### ISSUE THREAD

**Issue by denrase** [getsentry/sentry-dart#667]
- Provide the duration via sentry options.

Discussion: https://github.com/getsentry/sentry-dart/pull/643#discussion_r768815516

Relates to #643

**Comment by marandaneto** [comment]
Let's check if the JS SDK has it and if not, maybe we don't need it, we can always add it later, but it's always harder to remove it.

**Comment by marandaneto** [comment]
Exists on RN https://github.com/getsentry/sentry-react-native/blob/main/src/js/tracing/reactnativetracing.ts#L37-L53

**Comment by denrase** [comment]
@marandaneto I had the same issue when trying to introduce debug logs: How could we best provide access to `SentryOptions` in the `SentryNavigatorObserver`? We _only_ have access to the `Hub`, which holds a private reference to the options.

**Comment by marandaneto** [comment]
@denrase what if `SentryNavigatorObserver` takes an optional param `autoFinishAfter: Duration = Duration(seconds: 3)`?

**Comment by denrase** [comment]
Yeah, would work if we just keep it locally and not involve the options at all.
