### ISSUE TITLE
Auto Transactions: Duration Trimming

### ISSUE THREAD

**Issue by denrase** [getsentry/sentry-dart#668]
- Trim duration of auto transactions when (all) children have finished before the default idle duration.

Relates to #643

**Comment by marandaneto** [comment]
JS likely does the same, let's check with them and align the approach, that still makes sense since we don't have Mobile vitals for Flutter, so the duration of the transaction is likely more important now.

**Comment by marandaneto** [comment]
JS does it, so we'd ideally implement it on Flutter as well.
