### ISSUE TITLE
Is there a way to delay the initialization of sdk?

### ISSUE THREAD

**Issue by rockyoung** [getsentry/sentry-dart#671]
Recently in China, all apps need to pass the checking of the privacy policy, otherwise they will not be allowed to publish the app to the market. One of the core points of this checking is that in the case where the user does not have explicit consent (when the application is opened for the first time, a pop-up window is required to inform the user), the application is not allowed to obtain any device-related personal user information.

**Comment by brustolin** [comment]
Well,  you can initialize it any time you want. Sentry recommends to do it on app startup, but nothing bad will happen if you start it later. 
And since this postpone will be done only on the first run this is definitely not a problem IMO.

**Comment by marandaneto** [comment]
what @brustolin said, the only downside is that you won't be able to capture crashes before the SDK has been initialized.
you can also instead filter events out https://docs.sentry.io/platforms/flutter/configuration/filtering/ instead of delaying the init. of the SDK

**Comment by CatEatFishs** [comment]
> any time

hello ，how any time to initialize sentry？
