### ISSUE TITLE
(PR created) Allow attachments to be bound to exception more easily

### ISSUE THREAD

**Issue by fzyzcjy** [getsentry/sentry-dart#682]
## Why I need this (very much!)

My code is like:

```dart
void main_function() {
  try {
    inner_function(); // indeed, functions calling functions calling functions... so the calling stack is deep
  } catch (e,s) {
    Sentry.captureException(e, s);
  }
}

void inner_function() {
  var my_data = ...;
  try {
    do_some_work_that_can_throw_exception(my_data);
  } catch (e,s) {
     Sentry.pleaseBindAttachmentToException(e, my_data); // <-- !!
     rethrow;
  }
}
```

Notice the `Sentry.pleaseBindAttachmentToException`, where I want to bind attachment to exception.

However, as we know, we cannot do it. I can create some code to bind `extra` to exception, because `extra` can be modified in EventProcessors (so I can manually create a static map holding some extras and bind to exception in my own EventProcessor). However, EventProcessors cannot modify or add attachments. So I have no way to do it :(

## Proposed solution

Say, add a field to `SentryOptions`, e.g. `void Function(Scope)? withScopeWhenCapture`. Then, in `Hub.captureException` and similar places, call that callback. This is very simple and I will implement it if you like.

related: https://github.com/getsentry/sentry-dart/issues/646

Hi @marandaneto could you please have a look (since this thread is strongly related to #646)? Thanks! And @ueman could you please also have a look? Thanks!

**Comment by fzyzcjy** [comment]
Hi @marandaneto @ueman could you please suggest whether this is acceptable? If so I will make a PR. This is a blocking issue on our app...

**Comment by ueman** [comment]
If I'm not mistaken you can already do something like this:
```dart
Sentry.captureException(exception: ex, withScope:(scope) {
    scope.addAttachment(attachment);
});
```

I'm not sure if that already works, but you might try that. If not @marandaneto probably appreciates a PR which enable scoped attachments. I'm not a maintainer of this SDK anymore.

Currently is also Christmas season, so most people are probably out of office.

**Comment by fzyzcjy** [comment]
@ueman No I cannot do that...Notice that I `captureException` in a outer function, while I `addAttachment` in a inner function. For example, outer_function() calls func1() which calls func2() which calls func3(), ..., which calls func100() which calls inner_function().

> Currently is also Christmas season, so most people are probably out of office.

Ah I did not realized that (I have been doing my project for 2 years without using holidays ;) ). Sorry for disturbing.

**Comment by ueman** [comment]
Oh I see. In that case the solution would probably be similar to [.NETs `local scopes`](https://docs.sentry.io/platforms/dotnet/enriching-events/scopes/#local-scopes). Dart hasn't gotten support for that yet but that would probably the solution for your problem.

**Comment by fzyzcjy** [comment]
@ueman Well that is a bit the inverse. In my case I want to bind attachment in *inner* function and capture exception in *outer*. With the proposed modification, that can be implemented trivially.

**Comment by ueman** [comment]
Yeah, with mine, too. The code would be something like this:
```dart
void main_function() {
Sentry.withScope((scope) {
// within this scope, the attachment is added to the capture exception
  try {
    inner_function(); // indeed, functions calling functions calling functions... so the calling stack is deep
  } catch (e,s) {
    Sentry.captureException(e, s);
  }
}
// here the attachment isn't added to the exception anymore
Sentry.captureException(ex); // this exception has no attachment
}

void inner_function() {
  var my_data = ...;
  try {
    do_some_work_that_can_throw_exception(my_data);
  } catch (e,s) {
     Sentry.addAttachment(my_data);
     rethrow;
  }
}
```

**Comment by fzyzcjy** [comment]
Agree. Since that is a bit complex (read: can introduce bugs), I will firstly implement a simpler solution

**Comment by fzyzcjy** [comment]
PR made: https://github.com/getsentry/sentry-dart/pull/683

**Comment by marandaneto** [comment]
I'm on vacay, maybe @bruno-garcia can help

**Comment by fzyzcjy** [comment]
@marandaneto No problem, I can wait for it

**Comment by marandaneto** [comment]
I'll discuss that internally and get back to you, but I agree with @ueman , the solution could be using local scopes, it'd be confusing to have a `beforeSend` callback without `Scope`, and a `beforeCaptureWithScope`, our public APIs are aligned and documented https://develop.sentry.dev/sdk/unified-api/ so we'd need a bit of discussion before going forward.

**Comment by fzyzcjy** [comment]
@marandaneto Sure. I have used it in my app in production and my implementation seems quite good.

**Comment by bruno-garcia** [comment]
You could solve this today by throwing a new exception that holds the reference to your attachment and the inner exception.

pseudocode:

```
void main_function() {
  try {
    inner_function(); // indeed, functions calling functions calling functions... so the calling stack is deep
  } catch (e,s) {
    if (e is AttachmentException) {
      attachEx - (AttachmentException)e;
      Sentry.captureException(attachEx.Exception, attachEx.Stacktrace, scope: (s) => s.addAttachment(attachEx.Attachment));
    }
  }
}

void inner_function() {
  var my_data = ...;
  try {
    do_some_work_that_can_throw_exception(my_data);
  } catch (e,s) {
     throw new AttachmentException(e,s,my_data);
```

**Comment by fzyzcjy** [comment]
@bruno-garcia Sounds interesting, thanks

**Comment by fzyzcjy** [comment]
> I'll discuss that internally and get back to you

Hi, is there any updates?

**Comment by marandaneto** [comment]
> > I'll discuss that internally and get back to you
> 
> Hi, is there any updates?

Yes, but we're going to experiment on sentry-java first, which is using `hints` as the way to hold and filter attachments before being sent.
https://github.com/getsentry/sentry-java/pull/1929

You could e.g. `Sentry.captureException(exception, ["attachments": myAttachment])` or something similar to that, I will update this issue once we have a design for the API.
You'll be able to remove an attachment using the `beforeSend` as well via hints, so #711 would have a workaround as well.

**Comment by fzyzcjy** [comment]
Thanks for the update! As long as the goal mentioned in the first post of the issue is solved it, any method is great

**Comment by fzyzcjy** [comment]
@marandaneto Hi is there any updates?

**Comment by fzyzcjy** [comment]
> You could solve this today by throwing a new exception that holds the reference to your attachment and the inner exception.
> 
> pseudocode:
> 
> ```
> void main_function() {
>   try {
>     inner_function(); // indeed, functions calling functions calling functions... so the calling stack is deep
>   } catch (e,s) {
>     if (e is AttachmentException) {
>       attachEx - (AttachmentException)e;
>       Sentry.captureException(attachEx.Exception, attachEx.Stacktrace, scope: (s) => s.addAttachment(attachEx.Attachment));
>     }
>   }
> }
> 
> void inner_function() {
>   var my_data = ...;
>   try {
>     do_some_work_that_can_throw_exception(my_data);
>   } catch (e,s) {
>      throw new AttachmentException(e,s,my_data);
> ```

Btw this has a big drawback: the exception type is changed. e.g. if outer function only knows to catch MyException, it will not look at AttachmentException at all.

**Comment by marandaneto** [comment]
@fzyzcjy yes, we are experimenting with a new API for `hints` on the Java repo and this will likely be the solution here as well if it works well. https://github.com/getsentry/sentry-java/pull/2045
Via hints you'll be able to add and remove attachments for specific events.

**Comment by fzyzcjy** [comment]
Looking forward to it!

**Comment by fzyzcjy** [comment]
@marandaneto Hi is there any updates? Thanks

**Comment by marandaneto** [comment]
Yeah the approach taken on sentry-java worked well, now it's a matter of doing it on Dart/Flutter, not planning on this Quarter tho.

**Comment by marandaneto** [comment]
#1136 is going to unblock this via `hints`

**Comment by marandaneto** [comment]
It's now possible via [hints](https://github.com/getsentry/sentry-dart/blob/b5f0119a9d344b3dc0217487bddbd3557a554784/dart/lib/src/hint.dart).
We should introduce a new property in the `Hint` class that takes `attachments`, so you can add/remove them on the fly either when capturing events or thru `beforeSend` in the `hints` param.
