### ISSUE TITLE
Allow passing SentryFlutterOptions to SentryFlutter.init

### ISSUE THREAD

**Issue by kuhnroyal** [getsentry/sentry-dart#689]
I am wrapping some custom handling around `SentryFlutter.init` and need to pass a partially pre-configured options instance to it.
Basically I want to pass a subclass of `SentryFlutterOptions` in the same way `SentryFlutter.init` does with `Sentry.init`.

This is a simple change, I can create a PR if this is considered.

**Comment by ueman** [comment]
Can't you just copy the values of your subclass to the options of the callback? 

Probably not because you wouldn't ask if it were that easy, so I'm wondering why you need to subclass the options?

**Comment by kuhnroyal** [comment]
I just want to pass a subclass with a couple custom properties without copying everything from the `SentryFlutterOptions` in the callback.

I can probably do without this but it would be much cleaner with it. And since `Sentry.init` allows it, why shouldn't `SentryFlutter.init`.

**Comment by marandaneto** [comment]
> I just want to pass a subclass with a couple custom properties without copying everything from the `SentryFlutterOptions` in the callback.
> 
> I can probably do without this but it would be much cleaner with it. And since `Sentry.init` allows it, why shouldn't `SentryFlutter.init`.

before going ahead, why do you need to pass a custom `SentryFlutterOptions`? wondering if this would make sense to be built in the `SentryFlutterOptions` itself, or if it's a special case, mind describing?

If it's a matter of being cleaner, copying all the attributes in a method, or creating a derived SentryFlutterOptions and setting the values of it would be no different, just want to understand your use case beforehand.

**Comment by kuhnroyal** [comment]
The properties I want to add are specific to my apps, some custom analytics/app configuration.
I will actually close this. I can work around it, just thought it would make it consistent with `Sentry.init`.

**Comment by marandaneto** [comment]
Gotcha, the difference is just the nature of both SDKs, Flutter depends on the pure Dart one and requires setting some fields in a specific order, otherwise, it'd not be possible either.
There's a comment about it in the code https://github.com/getsentry/sentry-dart/blob/main/dart/lib/src/sentry.dart#L37-L39
