### ISSUE TITLE
Reduce logging to console.

### ISSUE THREAD

**Issue by robertflesch** [getsentry/sentry-dart#691]
Specifically Flutter Android or iOS
I love Sentry, it has helped me a number of times in the last two weeks, BUT

Currently Sentry spews TONs of data to my console, so much so that it makes seeing my own data very difficult.
While I understand some of this info might be useful, I would prefer not seeing intermediate steps, really I just want to see problems that a plugin has encountered, not internal data used by developers.

**Comment by ueman** [comment]
You should be able to set `options.debug` to false. I'm not sure if it disables logs completely, but it should at least reduce logs significantly.

**Comment by kuhnroyal** [comment]
Should seriously consider making this default :)

**Comment by robertflesch** [comment]
I agree that debug = false should be default.

**Comment by ueman** [comment]
> I agree that debug = false should be default.

@robertflesch do you mind opening a PR for that?

**Comment by AliAkberAakash** [comment]
Is this available? I'd like to make a PR

**Comment by marandaneto** [comment]
@AliAkberAakash please do it :)

**Comment by AliAkberAakash** [comment]
I can't seem to find it, It is already set to false in SentryOptions. Could you help me locate this please? @marandaneto

**Comment by marandaneto** [comment]
@AliAkberAakash We'd need to remove this -> https://github.com/getsentry/sentry-dart/blob/main/dart/lib/src/sentry_options.dart#L270-L275
