### ISSUE TITLE
Sentry SDK incompatibility with other packages

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dart#694]
> Sentry latest version is incompatible with http plugin and if another version of sentry is used then it is also not compatible with rest of the other already used packages in project. Even without version I tried to get its compatible version but this also not worked.
> Sentry SDK version 6.2.2. flutter version used - 2.5.3 and http plugin version used - 0.12.2 – 

From: https://stackoverflow.com/questions/70679984/sentry-version-incompatibility?noredirect=1#comment124970388_70679984

**Comment by ueman** [comment]
This is because Sentry uses `http: ^0.13.0` because that's the earliest version which is null safe. The user uses a pretty outdated version of `http`.

**Comment by marandaneto** [comment]
Yep, what @ueman said, feel free to use https://github.com/getsentry/sentry-dart/releases/tag/4.0.6 which is non-null-safety.
