### ISSUE TITLE
Update sentry-cocoa because of OOM error

### ISSUE THREAD

**Issue by Swiek** [getsentry/sentry-dart#695]
Hello,

We are having some issues with out of memory sentries.
I looks like the issue that is resolved in this version of sentry-cocoa:

https://github.com/getsentry/sentry-cocoa/blob/7.5.4/CHANGELOG.md

At the moment the latest release of sentry-dart is on 7.5.1.

Is there any expectation when it will get updated to at least 7.5.4?

Kind regards,

Erwin

**Comment by kuhnroyal** [comment]
This is probably the OOM I have in my Sentry from all the apps 👍  Was wondering where it was coming from. Looking forward to this!

**Comment by luzannew** [comment]
When can we expect this change in a new release? We are seeing quite a lot of these errors in our logs.
