### ISSUE TITLE
Auto performance monitoring for widgets

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-dart#706]
https://api.flutter.dev/flutter/widgets/GestureDetector-class.html

**Comment by marandaneto** [comment]
Similar to https://github.com/getsentry/sentry-java/issues/1412

**Comment by brustolin** [comment]
Let's split this issue in two,  performance and breadcrumbs.

**Comment by ueman** [comment]
This needs to be tested throughout with [PlatformViews](https://docs.flutter.dev/development/platform-integration/platform-views) as a global

**Comment by ueman** [comment]
This needs to be tested with Platform Views (webviews, maps, videos, camera, etc) as a global Gesture Detector can lead to weird behavior while interacting with them. Just had such a bug myself.

**Comment by marandaneto** [comment]
@ueman thanks for the heads up, mind clarifying this weird behavior? so we can check it out during the testing.

**Comment by ueman** [comment]
In my case it lead to being unable to scroll in [`flutter_inappwebview`](https://pub.dev/packages/flutter_inappwebview). Not sure why yet, as the global GestureDetector comes out of closed source third party code, which makes it tricky to figure out.
