### ISSUE TITLE
Flutter `app start` performance measurement

### ISSUE THREAD

**Issue by ueman** [getsentry/sentry-dart#708]
The [`time to initial display`](https://developer.android.com/topic/performance/vitals/launch-time#time-initial) (TTID) is 

> The time to initial display (TTID) metric measures the time it takes for an application to produce its first frame, including process initialization (if a cold start), activity creation (if cold/warm), and displaying first frame.

This one should be pretty easy to measure. The native SDK already knows when the app starts. The end timestamp is set when [`SchedulerBinding.addPostFrameCallback()`](https://api.flutter.dev/flutter/scheduler/SchedulerBinding/addPostFrameCallback.html) is called.
The time difference is the TTID.

Also see https://docs.flutter.dev/perf/metrics

**Comment by ueman** [comment]
I've just noticed this is the same as your definition of an `app start` according to https://blog.sentry.io/2021/08/23/mobile-vitals-four-metrics-every-mobile-developer-should-care-about .

**Comment by marandaneto** [comment]
Indeed, and we intend to bring Mobile Vitals along with the other measurements soon.

**Comment by ueman** [comment]
I would also like to see the `time to full display` measurement as outlined [here](https://developer.android.com/topic/performance/vitals/launch-time#time-full).

**Comment by philipphofmann** [comment]
Consider using a similar approach as on react-native.
