### ISSUE TITLE
`Sentry.captureTransaction` should return `Future<SentryId?>` instead of `Future<SentryId>`

### ISSUE THREAD

**Issue by ueman** [getsentry/sentry-dart#712]
_Platform:_
- [x]  Dart
- [x]  Flutter Android or iOS
- [x]  Flutter Web

_IDE:_
- [x]  VSCode
- [ ]  IntelliJ/AS
- [ ]  XCode
- [ ]  Other, which one?

_split-debug-info and obfuscate (Flutter Android or iOS) or CanvasKit (Flutter Web):_
- [ ]  Enabled
- [x]  Disabled

_Platform installed with:_
- [x] pub.dev
- [ ] GitHub

The version of the SDK (See pubspec.lock):
**6.3.0 beta3**

---
I have the following issue:

`Sentry.captureTransaction` should return `Future<SentryId?>` instead of `Future<SentryId>`.
If the transport, for whatever reason, returns null, which is allowed, Sentry crashes because 
it does a force unwrap here
https://github.com/getsentry/sentry-dart/blob/ea5c7336e558a0535ae1f276830935db86cb16b0/dart/lib/src/sentry_client.dart#L264

**Comment by marandaneto** [comment]
Indeed, it should be `return id ?? SentryId.empty();` as `captureEvent`, a transaction always has an `id` or its `empty` so clients don't need to handle NPE.
