### ISSUE TITLE
After the Demo is minimized, click the window menu to restore and the program does not respond on the macOS platform.

### ISSUE THREAD

**Issue by Leheih** [getsentry/sentry-dart#714]
_Platform:_
- [ ]  Dart
- [x]  Flutter Android or iOS
- [ ]  Flutter Web

_IDE:_
- [ ]  VSCode
- [x]  IntelliJ/AS
- [ ]  XCode
- [ ]  Other, which one?

_split-debug-info and obfuscate (Flutter Android or iOS) or CanvasKit (Flutter Web):_
- [ ]  Enabled
- [ ]  Disabled

_Platform installed with:_
- [x] pub.dev
- [ ] GitHub

Output of the command `flutter doctor -v` below:

[✓] Flutter (Channel stable, 2.5.0, on macOS 11.6 20G165 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.5.0 at /Users/jiajunwei/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (5 months ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/jiajunwei/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.59.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.27.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.6 20G165 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 97.0.4692.99

The version of the SDK (See pubspec.lock):
**6.3.0-beta.4**

---
I have the following issue:

After the Demo is minimized, click the window menu to restore and the program does not respond on the macOS platform.
I have the same problem with version 6.2.2 used in my project.

**Steps to reproduce:**
1. Run the demo
2. Minimize
3. Click the button at the bottom of the window menu to restore the window

**Actual result:**

After the window is restored, the program is not responding

**Expected result:**

After the window is restored, the program can run normally

**Comment by marandaneto** [comment]
@grassInSpring which `Demo` do you mean? can you elaborate a bit more? why do you think its a Sentry issue? thanks

**Comment by Leheih** [comment]
The demo path is sentry-dart/flutter/example.
After running the sample program, minimize it, and then click the button to restore the window as shown in the picture below. This problem will also occur after creating a new project to integrate Sentry, but I am not sure if it is a Sentry issue, but the phenomenon I see is like this, if I use it wrong, please let me know. thanks
<img width="546" alt="image" src="https://user-images.githubusercontent.com/17791894/151303749-090e0369-e55a-4763-8983-55994a7e8c84.png">

**Comment by marandaneto** [comment]
Ok, I could reproduce it.

> *** Assertion failure in -[FlutterViewController listenForMetaModifiedKeyUpEvents], ../../flutter/shell/platform/darwin/macos/framework/Source/FlutterViewController.mm:392

The very same issue happens if you remove Sentry, so it's not related to Sentry.
