### ISSUE TITLE
Fix sdk reporting of `sentry_logging`

### ISSUE THREAD

**Issue by ueman** [getsentry/sentry-dart#717]
Looks like this should not be set https://github.com/getsentry/sentry-dart/blob/main/logging/lib/src/logging_integration.dart#L49-L50
Since its an Integration rather than a top-level package, adding to the package list https://github.com/getsentry/sentry-dart/blob/main/logging/lib/src/logging_integration.dart#L54
Adding to the integration list https://github.com/getsentry/sentry-dart/blob/main/logging/lib/src/logging_integration.dart#L38 and setting the logger https://github.com/getsentry/sentry-dart/blob/main/logging/lib/src/extension.dart#L27 should have been enough.
Would you like to submit a PR @kuhnroyal ?

_Originally posted by @marandaneto in https://github.com/getsentry/sentry-dart/pull/631#discussion_r792709472_

**Comment by kuhnroyal** [comment]
Yea I can probably do that later.

**Comment by marandaneto** [comment]
Worth adding the `dio` package to the `options` too, Similar to the logging package, https://github.com/getsentry/sentry-dart/blob/main/logging/lib/src/logging_integration.dart#L54
Somewhere here https://github.com/getsentry/sentry-dart/blob/main/dio/lib/src/sentry_dio_client_adapter.dart#L61
That would require changes from https://github.com/getsentry/sentry-dart/pull/716 which is exposing the `options` thru the `Hub`.

Not really related to this issue, but I wanted to confirm if it makes sense.
