### ISSUE TITLE
Trace transactions across isolates

### ISSUE THREAD

**Issue by blaugold** [getsentry/sentry-dart#721]
This is a feature that is relevant to Dart and Flutter apps.

I would like to have the ability to trace transactions that perform some work in another isolate and therefore create child spans in that second isolate.

The [`TimelineTask`](https://api.dart.dev/stable/2.15.1/dart-developer/TimelineTask-class.html) from `dart:developer` for example can be used to track tasks that have child tasks in multiple isolates.

**Comment by marandaneto** [comment]
Indeed, for now, there's a workaround.

// your span Isolate A
`final header = spanIsolateA.toSentryTrace()`

// pass header to Isolate B
You can use the `final spanIsolateB = Sentry.startTransactionWithContext(SentryTransactionContext.fromSentryTrace(header))`.

So you are able to continue a transaction from different contexts, that's used for Frontend and Backend stuff, but it works.

**Comment by blaugold** [comment]
@marandaneto 
Thanks for that workaround!

**Comment by marandaneto** [comment]
We'll do an investigation on how this class Timeline task works and how we could use that to our benefit.
Users could benefit from creating fine-grained spans out of the given transaction/span.
We'll write an update as soon as we come to it.

**Comment by marandaneto** [comment]
Closing it in favor of https://github.com/getsentry/sentry-dart/issues/1343
Not really the very same thing but the very same symptom.
I believe we can address both together.
