### ISSUE TITLE
Support for binding hubs and scopes to zones

### ISSUE THREAD

**Issue by blaugold** [getsentry/sentry-dart#724]
I would like to be able to create a `Hub` and make it replace the root `Hub` within a Dart `Zone`, and similarly make a span the current span within a `Zone`.

Creating composable functions, that create child spans to trace themselves, requires manually passing the current parent span around. Binding a span to the scope of the root `Hub` does not work for asynchronous code. Multiple asynchronous transactions can be ongoing at the same time and interleave each other. 

Here is a bit of code to demonstrate what I would like to be able to do:

```dart
Future<T> runAppTransaction<T>(String name, Future<T> Function() fn) async {
  final span = Sentry.startTransaction(name, 'task');

  try {
    return await Sentry.runWithSpan(span, fn);
  } catch (e) {
    span.throwable = e;
    span.status = const SpanStatus.internalError();
    rethrow;
  } finally {
    await span.finish();
  }
}

Future<T> runAppOperation<T>(String name, Future<T> Function() fn) async {
  final span = Sentry.getSpan()!.startChild(name);

  try {
    return await Sentry.runWithSpan(span, fn);
  } catch (e) {
    span.throwable = e;
    span.status = const SpanStatus.internalError();
    rethrow;
  } finally {
    await span.finish();
  }
}

final httpClient = SentryHttpClient(networkTracing: true);

Future<String> fetchFooModel() =>
    // We can transparently trace this function, without having to pass in the parent span.
    runAppOperation('get.foo', () async {
      final response =
          // This HTTP request will be transparently traced as a child span of the `get.foo` span.
          await httpClient.get(Uri.parse('https://example.com/foo'));
      if (response.statusCode != 200) {
        throw Exception('Failed to fetch foo.');
      }
      return Foo.fromJson(jsonDecode(response.body));
    });

Future<void> printFooName() async =>
    await runAppTransaction('printFooName', () async {
      final foo = await fetchFooModel();
      print(foo.name);
    });

Future<void> main() => Sentry.runWithClone(() async {
      Sentry.configureScope((scope) {
        scope.setTag('printing', 'foo.name');
      });

      await printFooName();
    });
```

I'd be happy to work on a PR to implement this.

**Update**: Modified example to show how functions from PR #726 would be used.

**Comment by ueman** [comment]
This type of usage of Zones doesn't work well with tests and Flutter:

https://github.com/flutter/flutter/issues/96939

https://github.com/flutter/flutter/issues/93676

Introducing something like this should be really well tested.

**Comment by marandaneto** [comment]
That was previously discussed here https://github.com/getsentry/sentry-java/issues/1154
Sounds like the very same thing, we've not agreed on doing it or not yet as a public API.
`runAppTransaction` and `runAppOperation` could be easily shared functions in your App.

**Comment by blaugold** [comment]
@ueman 
Interesting, I didn't know about those issues. Thanks for bringing them up. I still think that this would be a valid and necessary use of Zones. Those issues seem to be about with which Zone the Flutter framework invokes callbacks. Using custom Zones which wrap a whole Flutter app is an edge case IMHO, but I might be wrong.

---
@marandaneto 
> `runAppTransaction` and `runAppOperation` could be easily shared functions in your App.

Sorry if that wasn't clear, but that's how I envisioned those functions, too. They just demonstrate how `Sentry.runWithSpan`, or a similar function, would be used.

Maybe I don't fully understand the design of `Hub` and `Hub.getSpan`, but this is how I see the current situation:
After `Sentry.init`, an app has a single global `Hub`, to which calls from `Sentry` are delegated. A single span (and therefore transaction) can be bound to a `Hub`. Integrations like `SentryHttpClient` indirectly use `Sentry.getSpan` to transparently add spans to the current span. Because there is only one global `Hub` there can only be one current span at any given moment.

Even though Dart has a single threaded execution model, concurrency is still possible. Multiple logical transactions can be ongoing at the same time as async functions, whose execution can interleave. Take, for example, a page where a user can post comments and like something. A user may submit a comment and click the like button in quick succession, causing transactions `likeFoo` and `postComment` to run in parallel. If both transaction set their respective root spans as the current span, one will override the other and HTTP calls through `SentryHttpClient` are added to the wrong transaction.

I probably should have stated my problem instead of a solution :)

**Comment by ueman** [comment]
> Using custom Zones which wrap a whole Flutter app is an edge case IMHO, but I might be wrong.

I would guess that's pretty common as zones are often used as a global error handler. Sentry does that too.


> Even though Dart has a single threaded execution model, concurrency is still possible. Multiple logical transactions can be ongoing at the same time as async functions, whose execution can interleave. Take, for example, a page where a user can post comments and like something. A user may submit a comment and click the like button in quick succession, causing transactions `likeFoo` and `postComment` to run in parallel. If both transaction set their respective root spans as the current span, one will override the other and HTTP calls through `SentryHttpClient` are added to the wrong transaction.

That's not concurrency, though, as that is only possible with isolates, but your point is still valid. 
I also don't have any other better idea. Except for passing the span around which isn't necessarily better and in the case of the http client not even possible.

**Comment by blaugold** [comment]
>> Using custom Zones which wrap a whole Flutter app is an edge case IMHO, but I might be wrong.
>
> I would guess that's pretty common as zones are often used as a global error handler. Sentry does that too.

You're totally right. I meant using zones specifically for the purpose of providing context through `zoneValues`.

**Comment by marandaneto** [comment]
Thank you for your comments, I'd need some time to review and think about this.
Since this changes the Public API as well, it requires a larger discussion, I'd also ask @bruno-garcia for help here.

**Comment by marandaneto** [comment]
Closing it in favor of https://github.com/getsentry/sentry-dart/issues/1343
