### ISSUE TITLE
Support sample rate

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dart#73]
Add sample rate to the client: https://docs.sentry.io/error-reporting/configuration/#sample-rate

Example: https://github.com/getsentry/sentry-dotnet/blob/ba4e1f46c843eec57f1e93a2376b533b8d84ebfd/src/Sentry/SentryClient.cs#L107-L113

**Comment by marandaneto** [comment]
https://github.com/getsentry/sentry-dart/pull/127
