### ISSUE TITLE
E2E tests should do a dry run or not run at all for external contributors otherwise fails CI every time

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-dart#733]
We could do something similar to the Android Gradle Plugin -> https://github.com/getsentry/sentry-android-gradle-plugin/blob/main/buildSrc/src/main/java/Dependencies.kt#L34-L39
Or, if not possible, add a conditional step to the CI workflow to not run if the token isn't available.

**Comment by marandaneto** [comment]
We'd do the same way as the SAGP, we just don't run if the token is really needed.

**Comment by AliAkberAakash** [comment]
I have no idea how github workfllows work but would like to work on this and get familiar with the topic.

**Comment by marandaneto** [comment]
@AliAkberAakash an example is to do this: https://github.com/getsentry/sentry-android-gradle-plugin/blob/main/.github/workflows/test-publish.yaml#L36
So the jobs don't get triggered if `SENTRY_AUTH_TOKEN` isn't available, otherwise, it'd fail anyway.

**Comment by AliAkberAakash** [comment]
So I have read a bit about workflows,  just adding `if: env.SENTRY_AUTH_TOKEN != null` at the end of the `run` commands will do the job?

**Comment by marandaneto** [comment]
Yeah, likely only here -> https://github.com/getsentry/sentry-dart/blob/d9ee9c790e59433186ea75e2b6b61cb71dc7305f/.github/workflows/e2e_dart.yml#L28-L32

I believe this one can be removed -> https://github.com/getsentry/sentry-dart/blob/d9ee9c790e59433186ea75e2b6b61cb71dc7305f/.github/workflows/flutter.yml#L92-L93
I don't see it being used.
