### ISSUE TITLE
Sentry doesn't reports String

### ISSUE THREAD

**Issue by subzero911** [getsentry/sentry-dart#737]
This made me turn gray :)

I tested Sentry with `throw 'error';`
Sentry doesn't notice this error!
But  `throw Exception('error')` will work.
Seems like Sentry doesn't understand a naked String without a wrapper exception class.

**Comment by marandaneto** [comment]
<img width="1004" alt="Screenshot 2022-02-03 at 09 18 58" src="https://user-images.githubusercontent.com/5731772/152305658-bb411d25-aeea-4016-a4e5-d59404552cec.png">

@subzero911 just tested it out and it works.
Please update your issue with the [bug report template](https://github.com/getsentry/sentry-dart/issues/new?assignees=&labels=&template=BUG_REPORT.md) and give us more context or a minimal reproducible example, thanks.

**Comment by subzero911** [comment]
_Platform:_
- [ ]  Dart
- [X]  Flutter Android or iOS
- [ ]  Flutter Web

_IDE:_
- [X]  VSCode
- [ ]  IntelliJ/AS
- [ ]  XCode
- [ ]  Other, which one?

_split-debug-info and obfuscate (Flutter Android or iOS) or CanvasKit (Flutter Web):_
- [ ]  Enabled
- [X]  Disabled

_Platform installed with:_
- [X] pub.dev
- [ ] GitHub

Output of the command `flutter doctor -v` below:

![image](https://user-images.githubusercontent.com/12999702/152306221-a33fd84e-1f69-4fe4-a69d-f4fbb906ab16.png)

The version of the SDK (See pubspec.lock):
**6.2.2**

I have the following issue:

When I throw the string, it is not caught by Sentry
But Error / Exception classes are.

**Steps to reproduce:**
1. initialize
```dart
  await SentryFlutter.init(
    (options) {
      options
        ..dsn = config.sentryDsn
        ..tracesSampleRate = 1.0
        ..environment = config is ProductionConfig ? 'Prod' : 'Uat';
    },
    appRunner: () => runApp(PushkaApp(navigatorKey: navKey)),
  );
```

2. somewhere in code:
```dart
try {
      throw 'fatal error';
    } catch (e, s) {
      Sentry.captureException(e, stackTrace: s);
      log.e(e);
    }
```

Expected result:
event is captured in Sentry console
Actual result:
Sentry doesn't notice the event

But if I change this line `throw 'fatal error';`
to `throw Exception('fatal error');`
it will do.
![image](https://user-images.githubusercontent.com/12999702/152307292-dcba1d6f-32bf-43fa-b74c-7911fff9683b.png)

**Comment by marandaneto** [comment]
@subzero911 please enable the debug flag if not on Debug mode and copy-paste the logs, I suspect that it's not reporting due to https://github.com/getsentry/sentry-dart/blob/main/dart/lib/src/event_processor/deduplication_event_processor.dart#L55-L59

**Comment by marandaneto** [comment]
@subzero911 please try the latest beta, https://github.com/getsentry/sentry-dart/releases/tag/6.3.0-beta.4
It could be because of https://github.com/getsentry/sentry-dart/pull/692 which is fixed already.

**Comment by marandaneto** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated. There's a large chance that this issue has been solved since.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
