### ISSUE TITLE
Flutter Support

### ISSUE THREAD

**Issue by MrMoronIV** [getsentry/sentry-dart#74]
It would be nice if sentry got official Flutter support, they support it as mentioned over here:  https://flutter.dev/docs/cookbook/maintenance/error-reporting

**Comment by bruno-garcia** [comment]
Just to clarify, we support Flutter.
it's on [our docs](https://docs.sentry.io/platforms/flutter/), and on the onboarding wizard (when you create a project in Sentry, select Flutter).

We're working on improving the support gratefully in Q4 now though. We'll update this issue with news.

**Comment by marandaneto** [comment]
https://github.com/getsentry/sentry-dart/releases/tag/4.0.0-alpha.2
