### ISSUE TITLE
V 6.3.0 cause flutter build error: CocoaPods could not find compatible versions for pod "Sentry"

### ISSUE THREAD

**Issue by Sally-Xu** [getsentry/sentry-dart#746]
_Platform:_
- [ ]  Dart
- [x]  Flutter Android or iOS
- [x]  Flutter Web

_IDE:_
- [x]  VSCode
- [ ]  IntelliJ/AS
- [x]  XCode
- [ ]  Other, which one?

_split-debug-info and obfuscate (Flutter Android or iOS) or CanvasKit (Flutter Web):_
- [x]  Enabled
- [ ]  Disabled

_Platform installed with:_
- [x] pub.dev
- [ ] GitHub

Output of the command `flutter doctor -v` below:

[✓] Flutter (Channel stable, 2.10.0, on macOS 12.1 21C52 darwin-arm, locale en-US)
    • Flutter version 2.10.0 at /Users/sallyxu/Devtools/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5f105a6ca7 (7 days ago), 2022-02-01 14:15:42 -0800
    • Engine revision 776efd2034
    • Dart version 2.16.0
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/sallyxu/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.64.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

The version of the SDK (See pubspec.lock):
**4.x.x**

---
I have the following issue:
_**After updated sentry_flutter to v 6.3.0,  ios build is broken. Getting the error**_:
CocoaPods could not find compatible versions for pod "Sentry".

_**I tried to delete the Pods and Podfile.lock, and run pod install --repo-update, then got**_ 
[!] Oh no, an error occurred.

_**have to reverse back to v 6.2.2.**_ 

Following is the output from flutter build ios command:

Building com.xxx.ttpkpi for device (ios-release)...
Automatically signing iOS for device deployment using specified development team in Xcode project:
2Q9HT7X674
Running pod install...                                             751ms
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Finding Podfile changes
      - Flutter
      - connectivity
      - geolocator_apple
      - google_maps_flutter
      - package_info_plus
      - sentry_flutter
      - shared_preferences_ios
      - url_launcher_ios

    Fetching external sources
    -> Fetching podspec for `Flutter` from `Flutter`
    -> Fetching podspec for `connectivity` from `.symlinks/plugins/connectivity/ios`
    -> Fetching podspec for `geolocator_apple` from `.symlinks/plugins/geolocator_apple/ios`
    -> Fetching podspec for `google_maps_flutter` from `.symlinks/plugins/google_maps_flutter/ios`
    -> Fetching podspec for `package_info_plus` from `.symlinks/plugins/package_info_plus/ios`
    -> Fetching podspec for `sentry_flutter` from `.symlinks/plugins/sentry_flutter/ios`
    -> Fetching podspec for `shared_preferences_ios` from `.symlinks/plugins/shared_preferences_ios/ios`
    -> Fetching podspec for `url_launcher_ios` from `.symlinks/plugins/url_launcher_ios/ios`

    Resolving dependencies of `Podfile`
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only
      performed in repo update
      CDN: trunk Relative path: all_pods_versions_c_7_9.txt exists! Returning local because checking is only
      performed in repo update
      CDN: trunk Relative path: Specs/c/7/9/Reachability/3.2/Reachability.podspec.json exists! Returning
      local because checking is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_a_d_d.txt exists! Returning local because checking is only
      performed in repo update
      CDN: trunk Relative path: Specs/a/d/d/GoogleMaps/6.0.1/GoogleMaps.podspec.json exists! Returning local
      because checking is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_a_b_d.txt exists! Returning local because checking is only
      performed in repo update
      CDN: trunk Relative path: Specs/a/b/d/Sentry/7.7.0/Sentry.podspec.json exists! Returning local because
      checking is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_4_2_c.txt exists! Returning local because checking is only
      performed in repo update
      CDN: trunk Relative path: Specs/4/2/c/FlutterMacOS/2.5/FlutterMacOS.podspec.json exists! Returning
      local because checking is only performed in repo update
    [!] CocoaPods could not find compatible versions for pod "Sentry":
      In snapshot (Podfile.lock):
        Sentry (= 7.5.4, ~> 7.5.1)

      In Podfile:
        sentry_flutter (from `.symlinks/plugins/sentry_flutter/ios`) was resolved to 0.0.1, which depends on
          Sentry (~> 7.9.0)

    Specs satisfying the `Sentry (= 7.5.4, ~> 7.5.1), Sentry (~> 7.9.0)` dependency were found, but they
    required a higher minimum deployment target.

    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:317:in
    `raise_error_unless_state'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:299:in `block in
    unwind_for_conflict'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:297:in `tap'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:297:in `unwind_for_conflict'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:257:in `process_topmost_state'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:182:in `resolve'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolver.rb:43:in `resolve'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/resolver.rb:94:in `resolve'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:1078:in `block in
    resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:1076:in
    `resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:416:in `analyze'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:241:in `block in
    resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:240:in `resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:161:in `install!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/command/install.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:23:in `load'
    /usr/local/bin/pod:23:in `<main>'

Error running pod install

The description goes here ...

**Steps to reproduce:**
- Step

**Actual result:**
- Actual

**Expected result:**
- Result

**Comment by marandaneto** [comment]
@Sally-Xu It's probably caching issues, try to `flutter clean`, `flutter pub get`, `pod update`, `pod install` and friends

**Comment by kuhnroyal** [comment]
Usually deleting the `Podfile.lock` helps.

**Comment by Sally-Xu** [comment]
I tried all of the above suggestions before I posted the issue.
delete Pods, Podfile.lock

flutter clean,
flutter pub get
pod install --repo-update

None of them solved the problem.
Now I have fix the version of sentry_flutter to 6.2.2.  
sentry_flutter: 6.2.2

**Comment by marandaneto** [comment]
@Sally-Xu it is an environmental issue, please double check it, I've tried on a new project and upgraded from an old one, both worked well.

**Comment by Sally-Xu** [comment]
@marandaneto ,

Could you point me a direction to check?  I just tried to create a new flutter project without adding any code, just by adding same sentry_flutter package would have the same problem:


```
flutter create myapp
cd myapp
flutter pub add sentry_flutter
flutter build ios

```

Getting error on pod install step: 

Error output from CocoaPods:
↳

    [!] Automatically assigning platform `iOS` with version `9.0` on target `Runner` because no platform
    was specified. Please specify a platform for this target in your Podfile. See
    `https://guides.cocoapods.org/syntax/podfile.html#platform`.

Error running pod install



If I change the sentry_flutter version to 6.2.2, the error is gone, build went through without a problem.

My machine is a brand new (less than a month old) MacBook Pro, all the softwares are up-to-date.

**Comment by kuhnroyal** [comment]
Add something like this to the top of your `Podfile`:

```ruby
# Uncomment this line to define a global platform for your project
platform :ios, '12.0'
```

**Comment by Sally-Xu** [comment]
@kuhnroyal 

I did. same error.

**Comment by marandaneto** [comment]
@Sally-Xu that's not a Sentry's issue, sadly.
As I said, I've created an empty project and it worked out.

**Comment by b099l3** [comment]
These steps suggested by @marandaneto worked for me, specifically `pod update`:

deleting the `Podfile.lock` then:
```zsh
flutter clean
flutter pub get
pod update
pod install
```
had to run another `flutter pub get` from VSCode but works fine now.

**Comment by fonstack** [comment]
I had the same issue... Moving to the new version 6.4.0 solved it!
