### ISSUE TITLE
Improve mocks by overriding `noSuchMethod`

### ISSUE THREAD

**Issue by ueman** [getsentry/sentry-dart#747]
There are a couple of handwritten mocks which override each method, even those we don't care for. 
Instead of overriding each method, we should override `noSuchMethod` so we don't have to update the mocks in case unrelated stuff gets added or removed.

**Comment by AliAkberAakash** [comment]
can I take this?

**Comment by marandaneto** [comment]
@AliAkberAakash yes please :)

**Comment by AliAkberAakash** [comment]
Should I just override in all the handwritten mocks in every module? And should I override them like the following code? : 
`class Person {
    @override  //overring noSuchMethod
     noSuchMethod(Invocation invocation) => 'Method ${invocation.memberName} was called with arguments ${invocation.positionalArguments}';
}`

Also, can I create a mixin that overrides this method and then extend every handwritten mocks with that mixin?

**Comment by AliAkberAakash** [comment]
like this: 
`
mixin NoSuchMethodProvider {
  @override
  void noSuchMethod(Invocation invocation) {
    'Method ${invocation.memberName} was called '
        'with arguments ${invocation.positionalArguments}';
  }
}`
and then on the mock class:
`class MockSentryClient with NoSuchMethodProvider implements SentryClient`

**Comment by marandaneto** [comment]
@AliAkberAakash That would address the DRY principle, so yes.
