### ISSUE TITLE
[sentry_flutter] Define API entrypoint

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dart#75]
PR getsentry/sentry-flutter#1 was attempting that but became stale.
I've attempted using this on a dogfooding project which so far seems like my prefered API:

https://github.com/bruno-garcia/badges.bar/blob/main/lib/src/sentry/sentry.dart

**Comment by marandaneto** [comment]
@bruno-garcia this is only about the `runZonedGuarded` thingie right? we already support the Sentry.init(options => {...})

**Comment by bruno-garcia** [comment]
This is more for `Flutter`.
I'm hoping we can offer a `SentryFlutter.init(() => runApp(App()), options` so we can capture app init errors.

Instead of documenting: `try, catch, runZoneGuarded, integratiosn etc`

**Comment by marandaneto** [comment]
Draft for this ##158
