### ISSUE TITLE
Remove parameter from manual setup classes

### ISSUE THREAD

**Issue by ueman** [getsentry/sentry-dart#750]
Since the `SentryOptions` are now accessible via `Hub`, parameters for the following classes aren't needed anymore, as they can be read from the options.

- SentryHttpClient: https://github.com/getsentry/sentry-dart/blob/main/dart/lib/src/http_client/sentry_http_client.dart#L82-L87
- SentryNavigationObserver: https://github.com/getsentry/sentry-dart/blob/main/flutter/lib/src/navigation/sentry_navigator_observer.dart#L60-L61

There are probably more cases, as I haven't looked through all classes.

**Comment by marandaneto** [comment]
Makes sense, since it's a breaking change, it'd go within the next major.
Not all properties belong to the SentryOptions tho.

**Comment by AliAkberAakash** [comment]
Would like to work on this.

**Comment by marandaneto** [comment]
@AliAkberAakash That's awesome, please create a feature branch for that.

**Comment by AliAkberAakash** [comment]
So I should look for classes that have 'Hub' object as parameter and remove the other parameters that are available through `Hub` ? If thats the case, is it guaranteed that the name of the parameters will always be same both in `Hub` class and the classes that are using it along with other parameters?

**Comment by marandaneto** [comment]
Yes, if you take the first example, you can access the `sendDefaultPii` via `_hub.options.sendDefaultPii`

**Comment by ueman** [comment]
Also flags for enabling performance monitoring are good candidates to look for.

**Comment by AliAkberAakash** [comment]
I found this class 
`abstract class Integration<T extends SentryOptions> {
  /// A Callable method for the Integration interface
  FutureOr<void> call(Hub hub, T options);

  /// NoOp by default : only closeable integrations need to override
  FutureOr<void> close() {}
}`

the `call()` method takes both a `Hub` object and an `Options` object as parameter, so I am only passing `Hub` here and access `options` via `hub`, on the implementations of this class. I'm also changing the class signature (removing `<T extends SentryOptions>`.

**Comment by AliAkberAakash** [comment]
I'm getting the warning `The member 'options' can only be used within its package. ` when using `hub.options` in the flutter module, Should I remove `@internal` from here 
` @internal
  SentryOptions get options => _options;`

**Comment by marandaneto** [comment]
> I'm getting the warning `The member 'options' can only be used within its package. ` when using `hub.options` in the flutter module, Should I remove `@internal` from here ` @internal SentryOptions get options => _options;`

@AliAkberAakash I'd say to not touch this, that's ok, the most important part is the user-facing configuration, when they need to pass the values manually instead during the SDK init.
The `Integration` class is created by the SDKs automatically so that would be ok.
It's also ok to remove the options from the `Integration` class but you'll have a bunch of warnings, broken tests, if you are ok fixing all of them.

**Comment by AliAkberAakash** [comment]
Hi, I'm not changing the `Integration` class.

I'm getting a bit lost while finding all the places where `hub` is being used. Could you please tell me how do I find which classes are related to user-facing configuration?

**Comment by ueman** [comment]
A few classes/methods that come to my mind are SentryHttpClient, addSentry() extension method from the dio integration, SentryNavigationObserver, SentryAssetBundle. I believe that's already the majority of the relevant items. You can also look through the documentation as only the public API has the documentation available.

**Comment by AliAkberAakash** [comment]
Thanks I will  change this classes and look through the api docs

**Comment by AliAkberAakash** [comment]
I could not find any usage of SentryOptions parameters in `SentryNavigationObserver` , `addSentry()` extension method and `SentryAssetBundle` . I found them in `SentryHttpClient` and `failed_request_client` and made according changes. I don't know if I'm missing something here.

**Comment by marandaneto** [comment]
> I could not find any usage of SentryOptions parameters in `SentryNavigationObserver` , `addSentry()` extension method and `SentryAssetBundle` . I found them in `SentryHttpClient` and `failed_request_client` and made according changes. I don't know if I'm missing something here.

Thanks, I will review and do a quick check as well, thanks for doing this.
