### ISSUE TITLE
[Dio] Add option for custom parent span

### ISSUE THREAD

**Issue by ueman** [getsentry/sentry-dart#751]
What do you think about adding a way to pass a custom parent span to a request via Dio's `extra` map, that the `TracingClientAdapter` will use by default and fallback to `Sentry.getSpan()` if it is not set?

Like so:
```dart
  @override
  Future<ResponseBody> fetch(
    RequestOptions options,
    Stream<Uint8List>? requestStream,
    Future? cancelFuture,
  ) async {
    // see https://develop.sentry.dev/sdk/performance/#header-sentry-trace
    final currentSpan = options.extra['sentrySpan'] is SentrySpan ? options.extra['sentrySpan']! as SentrySpan : _hub.getSpan();
    final span = currentSpan?.startChild(
      'http.client',
      description: '${options.method} ${options.uri}',
    );
```

_Originally posted by @kuhnroyal in https://github.com/getsentry/sentry-dart/issues/718#issuecomment-1035303636_

**Comment by ueman** [comment]
@kuhnroyal What's the reasoning behind this request?

**Comment by kuhnroyal** [comment]
I am making multiple parallel requests using `Future.wait` with some chained database access and I want to group network/database/processing together per request.

So I create a parent span and want to nest the children. Otherwise I don't know which belongs to which.

**Comment by kuhnroyal** [comment]
Actually I think we need a more general approach, I have a similar problem with my database queries that I want to trace and I can't pass a parent span to every query.

I experimented a bit with using `Zone` values which seems to work pretty well.

```dart
const sentrySpanKey = #ISentrySpan;
````

```dart
 final customSpan = Sentry.getSpan()!.startChild('Custom span');

await runZoned(() {
    // actual code you want to trace
    dio.get();
  },
  zoneValues: {sentrySpanKey: customSpan},
);
```

And then finally use it:
```dart
final currentSpan = Zone.current[sentrySpanKey] as ISentrySpan? ?? Sentry.getSpan();
```

**Comment by ueman** [comment]
Maybe https://github.com/getsentry/sentry-dart/pull/726 is what you want

**Comment by marandaneto** [comment]
`Zones` still don't run parallel requests, only `Isolates`, right.
Looks similar to #726 indeed.
Nested children may be grouped wrongly due to having a single Scope, the timeline of the spans is correct tho since they use a timestamp.
The best way of doing it right now is using the [Custom instrumentation](https://docs.sentry.io/platforms/dart/performance/instrumentation/custom-instrumentation/) so you have control over the transaction and its children.
This is an issue across other SDKs as well when they have a single thread system like JavaScript.

**Comment by kuhnroyal** [comment]
Yea #726 is what I need, I actually implemented pretty much the same thing last night. Completely missed that PR.

**Comment by kuhnroyal** [comment]
@ueman I think you can close this

**Comment by kuhnroyal** [comment]
@marandaneto Custom instrumentation is what I tried to use but there is no way to get the HTPP spans attached to it.
The `runWithSpan` will solve this.
