### ISSUE TITLE
Support local scopes with/push

### ISSUE THREAD

**Issue by kuhnroyal** [getsentry/sentry-dart#752]
I am looking for a way to use some form of local scopes similar to javascript https://docs.sentry.io/platforms/javascript/enriching-events/scopes/#local-scopes and API docs https://develop.sentry.dev/sdk/unified-api/#scope where I can override the transaction and a couple other things without touching the main Hub/Context.

**Comment by marandaneto** [comment]
@kuhnroyal What's the use case for using local scopes? does it work using the [withScope](https://docs.sentry.io/platforms/dart/enriching-events/scopes/#local-scopes) callback?

**Comment by kuhnroyal** [comment]
Well, `withScope` does only effect one event or everything after calling it.

`pushScope` according to the Unified API docs would allow to use a cloned scope for a block of code without effecting everything outside this block.

For my scenario, the changes from #726 `runWithClone` will work.
But it is not exactly the same as one clones the full Hub and the other just pushes a new scope on top.

**Comment by kuhnroyal** [comment]
@marandaneto This can be closed if you don't see any further value for a local scope(stack). I'll leave that up to you.

**Comment by marandaneto** [comment]
@kuhnroyal Thanks, we'll discuss if it makes sense to add the other methods from the Unified API in the Dart SDK.

**Comment by marandaneto** [comment]
The `Sentry.withSope` method is obsolete in favor of the `withScope` callback which is already supported by this SDK.
See the [.NET SDK](https://github.com/getsentry/sentry-dotnet/pull/1412)
The `withScope` callback also does not touch the main Scope, so the following events won't be affected either.
