### ISSUE TITLE
DioErrorType.receiveTimeout 

### ISSUE THREAD

**Issue by philos3** [getsentry/sentry-dart#757]
_Platform:_
- [x]  Dart
- [x]  Flutter Android 

_IDE: AS

_split-debug-info and obfuscate (Flutter Android or iOS) or CanvasKit (Flutter Web):_
- [x]  Enabled

_Platform installed with:_
- [x] pub.dev

Output of the command `flutter doctor -v` below:

[√] Flutter (Channel stable, 2.8.0, on Microsoft Windows [Version 10.0.19044.1526], locale zh-CN)
    • Flutter version 2.8.0 at D:\flutter\flutter_2.5.3\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cf44000065 (2 months ago), 2021-12-08 14:06:50 -0800
    • Engine revision 40a99c5951
    • Dart version 2.15.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\Dong\AppData\Local\Android\Sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio2\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio2
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] VS Code (version 1.64.2)
    • VS Code at C:\Users\Dong\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.34.0

[√] Connected device (3 available)
    • RMX1991 (mobile) • b813d84b • android-arm64  • Android 11 (API 30)
    • Chrome (web)     • chrome   • web-javascript • Google Chrome 98.0.4758.102
    • Edge (web)       • edge     • web-javascript • Microsoft Edge 98.0.1108.50

The version of the SDK (See pubspec.lock):
 sentry:
    dependency: transitive
    description:
      name: sentry
      url: "https://pub.flutter-io.cn"
    source: hosted
    version: "6.3.0"
  sentry_dio:
    dependency: "direct main"
    description:
      name: sentry_dio
      url: "https://pub.flutter-io.cn"
    source: hosted
    version: "6.3.0"
  sentry_flutter:
    dependency: "direct main"
    description:
      name: sentry_flutter
      url: "https://pub.flutter-io.cn"
    source: hosted
    version: "6.3.0"
  sentry_logging:
    dependency: "direct main"
    description:
      name: sentry_logging
      url: "https://pub.flutter-io.cn"
    source: hosted
    version: "6.3.0"

---

I have the following issue:
the sentry returns a lot of dio time out error,  but all the http response ok。
what is the problem? for detail info in the below url .
[The description goes here ...](http://101.35.8.44:9090/share/issue/ee59acabd63e4d1285b751fc760d1cd9/)

**Comment by philos3** [comment]
![image](https://user-images.githubusercontent.com/8424317/154256218-fe33d5ca-1012-4eb5-9444-5f6b47141af5.png)

**Comment by ueman** [comment]
That could come from previous successful HTTP requests as 10s are less than the 60s timeout.

Dio also never really cancels any HTTP request, it just stops listening for the result of the request. (The same is also true for the `http` package.)

**Comment by marandaneto** [comment]
@philos3 Not sure if we can do something about it, Sentry reports the errors thrown by `dio`.
What would you suggest?

Feel free to filter events out https://docs.sentry.io/platforms/dart/configuration/filtering/

**Comment by marandaneto** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
