### ISSUE TITLE
missing fallback userId

### ISSUE THREAD

**Issue by mj-hd** [getsentry/sentry-dart#759]
According to the document, the SDK uses a random `installationId` as a fallback for the user ID.

https://github.com/getsentry/sentry-docs/pull/4201
https://docs.sentry.io/platforms/flutter/enriching-events/identify-user/

However, I could not find an implementation of this and the reported issue seems to be tagged as `Unknown User`.

![image](https://user-images.githubusercontent.com/6854255/154602803-29c43ca0-6a5b-49f8-aa85-4eb870c4dac6.png)

Is this behavior unimplemented? Or if I've missed something, please let me know.

**Comment by marandaneto** [comment]
@mj-hd thanks for reporting, is that Android or iOS?

**Comment by kuhnroyal** [comment]
I am seeing this as well on iOS - Android always has an ID

**Comment by marandaneto** [comment]
It could be related to https://github.com/getsentry/sentry-cocoa/issues/1554
@brustolin Reading the code snippet https://github.com/getsentry/sentry-dart/blob/main/flutter/ios/Classes/SentryFlutterPluginApple.swift#L74-L91
Which Class/Field should I read the userId? Is the userId that falls back to the installation Id also set in the scope?

**Comment by mj-hd** [comment]
@marandaneto I tried this on iOS. On Android, the issues are tagged with a unique user ID.

**Comment by marandaneto** [comment]
It's a bug then, we'll take care of that.

**Comment by kuhnroyal** [comment]
I was really looking forward to this but this suffers from the same effect that as soon as I set some other user fields, the cocoa SDK no longer adds the its fields to the context. 

So on Android I always hav a unique user ID unless I set/remove it with something different. On iOS I only hav a user ID if I don't do anything with the user.
