### ISSUE TITLE
Releases & Health

### ISSUE THREAD

**Issue by duniapay** [getsentry/sentry-dart#76]
Do you plan on adding this [feature](https://docs.sentry.io/platforms/apple/guides/ios/configuration/releases/) for the flutter package ?

**Comment by bruno-garcia** [comment]
We sure do. @duniapay This will be coming in one of the first next releases since it relies on the native integration we'll offer.

**Comment by duniapay** [comment]
Thanks for the feedback @bruno-garcia any idea of when I should expect the next release ?

**Comment by bruno-garcia** [comment]
In the up coming weeks. Sorry, we're working on a timeline and prioritization at the moment. Updates soon.

**Comment by marandaneto** [comment]
https://github.com/getsentry/sentry-dart/releases/tag/4.0.0-alpha.2
