### ISSUE TITLE
Setting device context in Android prevents native device context from being set

### ISSUE THREAD

**Issue by kuhnroyal** [getsentry/sentry-dart#766]
_Platform:_
- [ ]  Dart
- [x]  Flutter Android or iOS
- [ ]  Flutter Web

_IDE:_
- [ ]  VSCode
- [x]  IntelliJ/AS
- [ ]  XCode
- [ ]  Other, which one?

_split-debug-info and obfuscate (Flutter Android or iOS) or CanvasKit (Flutter Web):_
- [ ]  Enabled
- [x]  Disabled

_Platform installed with:_
- [x] pub.dev
- [ ] GitHub

Output of the command `flutter doctor -v` below:

The output goes here...

The version of the SDK (See pubspec.lock):
**6.3.0**

---
I have the following issue:

Setting device context in Android prevents native device context from being set.

**Steps to reproduce:**
- Create an `EventProcessor` and set the device context
Something like this:

```dart
class ConnectivityEventProcessor implements EventProcessor {
  const ConnectivityEventProcessor();

  @override
  Future<SentryEvent> apply(SentryEvent event, {dynamic hint}) async {
    final connectivity = await Connectivity().checkConnectivity();
    return event.copyWith(
      contexts: event.contexts.copyWith(
        device: (event.contexts.device ?? const SentryDevice()).copyWith(
          // online flag ist not being set on iOS by default
          online: event.contexts.device?.online ?? connectivity != ConnectivityResult.none,
        ),
      ),
    );
  }
}
```

**Actual result:**
- Sentry only shows the `online` or whatever was set in the processor for Android devices
- Sentry shows everything for iOS devices

**Expected result:**
- Sentry shows everything for both OSes

**Comment by marandaneto** [comment]
Yep, we don't merge field per field (Should we?) but rather only set the object if not set at all.
This should be addressed by https://github.com/getsentry/sentry-cocoa/issues/1235 instead which is adding the missing context for iOS.

**Comment by kuhnroyal** [comment]
> (Should we?)

Not sure, that is kinda what I expected.
It behaves differently for iOS/Android. For iOS I can set additional information and it shows up, but not for Android. That is confusing.

**Comment by marandaneto** [comment]
@kuhnroyal it is, and the reason is the way how the SDKs provide the context to the Hybrid SDKs, it's a flaw and indeed needs to be fixed, it's a known issue already tracked by another issue IIRC.
In your case, the connectivity status needs to be added by the iOS SDK anyway.

**Comment by kuhnroyal** [comment]
Ok thanks, I can work around this and can follow the Cocoa issue.
Feel free to close if the general problem ist tracked somewhere else (I remember something about it in my head but didn't find a ticket).

**Comment by ueman** [comment]
This also affects the `operating system` context on macOS. As soon as one value is set in it, the native side is not filling in the remaining information.

> Should we?

Yeah, that's also what I would expect.

**Comment by marandaneto** [comment]
The downside of merging field per field is that: let's say that you have a specific field set by you or this SDK (let's call device.id) and you delete this data using `beforeSend` or an event processor, the Native SDK may still add it back if we merge field per field since that field won't be set anymore.
So this change is not trivial and it'd require a specific strategy to avoid that happening.
We acknowledge it's a gap in the SDK design for Hybrid SDKs.

**Comment by ueman** [comment]
Isn't that why there's this https://github.com/getsentry/sentry-dart/blob/2b4d628ad0ee28d8c5b2cb5cc364befb6ce4839b/flutter/lib/src/default_integrations.dart#L137-L251 integration? That solves the problem in most cases. 

One could easily change that to be an event processor and it would solve the problem in all cases.

**Comment by marandaneto** [comment]
@ueman we don't have for Android yet, it works differently and there's another issue tracking that.
on Android, the events get enriched on the Native SDK.

**Comment by marandaneto** [comment]
Closing this in favor of https://github.com/getsentry/team-mobile/issues/11
