### ISSUE TITLE
Does sentry dart have ignoreErrors ?

### ISSUE THREAD

**Issue by devalensio** [getsentry/sentry-dart#769]
i used to filter errors using ignoreErrors in javascript, when i work on flutter and want to filter errors, the documentation says using beforeSend hook to filter, but here https://docs.sentry.io/platforms/dart/configuration/filtering/ does not clarify how to filter errors.

**Comment by marandaneto** [comment]
@devalensio 

> It receives the event object as a parameter, so you can use that to modify the event’s data or drop it completely (by returning null) based on custom logic and the data available on the event.

So just returning `null` would drop the event, you can use the `SentryEvent#throwable` to access the original exception.

I guess you are talking about [InboundFilters](https://docs.sentry.io/product/accounts/quotas/manage-event-stream-guide/#inboundfilters)
If so, we don't support it yet, upvote the [issue](https://github.com/getsentry/sentry-dart/issues/626) please.
