### ISSUE TITLE
Performance Monitoring SDK for Flutter

### ISSUE THREAD

**Issue by poom201211** [getsentry/sentry-dart#78]
There is very little support for Flutter web at the moment. However, just want to know if its possible for there to be a support for Flutter SDK. The performance monitoring feature is a amazing and I would like to implementing it in my Flutter web project.

**Comment by bruno-garcia** [comment]
The SDK currently supports Flutter Web but given that it's still in the beta channel, it might take a bit longer than adding support for Android and iOS. It's definitely a goal for us but it's likely something for Q1 2021 only.

**Comment by poom201211** [comment]
That's great! Thank you for your reply Bruno.

**Comment by bruno-garcia** [comment]
Let's keep this open until we shit the support. Thanks for raising!

**Comment by poom201211** [comment]
Sure thing, I'm looking forward to the implementation.

**Comment by mnordine** [comment]
I'd like to have this for Dart web.

**Comment by ueman** [comment]
A couple of ideas for performance monitoring:
- Something like [Android's activity tracing](https://docs.sentry.io/platforms/android/performance/included-instrumentation/#androids-activity-instrumentation) but with [SentryNavigatorObserver](https://github.com/getsentry/sentry-dart/blob/dcdbe20f441e21c3fcc626a08dd3f82b09fc16af/flutter/lib/src/navigation/sentry_navigator_observer.dart) and [WidgetsBindingObserver](https://github.com/getsentry/sentry-dart/blob/dcdbe20f441e21c3fcc626a08dd3f82b09fc16af/flutter/lib/src/widgets_binding_observer.dart)
- [MethodChannel](https://api.flutter.dev/flutter/services/MethodChannel-class.html) tracking. For example how long does it take to go from Dart to native to Dart. Or just from Dart to native or vice versa. The [onPlatformMessage()](https://api.flutter.dev/flutter/dart-ui/SingletonFlutterWindow/onPlatformMessage.html) method seems like a good candidate to test.
- A SentryGlobalKey (see [GlobalKey](https://api.flutter.dev/flutter/widgets/GlobalKey-class.html)) to track the lifetime of widgets and get its state in crash reports. I don't actually know if it's possible, but have this idea floating around in my mind.
- SentryHttpClient integration
- Frame duration tracking, see [FrameTiming](https://api.flutter.dev/flutter/dart-ui/FrameTiming-class.html) and [how it should be monitored](https://flutter.dev/docs/perf/metrics)

**Comment by Lawati97** [comment]
I am curious if the Performance feature is available as I was not able to find it in the dart in the documentation.

**Comment by marandaneto** [comment]
its not available, upvote and follow this issue, thanks

**Comment by pepusz** [comment]
hi, do you have a timeline for this feature?

**Comment by bruno-garcia** [comment]
We want to start looking at this soon. We should have something up for you to try by the end of October.

**Comment by Lawati97** [comment]
> A couple of ideas for performance monitoring:
> 
> * Something like [Android's activity tracing](https://docs.sentry.io/platforms/android/performance/included-instrumentation/#androids-activity-instrumentation) but with [SentryNavigatorObserver](https://github.com/getsentry/sentry-dart/blob/dcdbe20f441e21c3fcc626a08dd3f82b09fc16af/flutter/lib/src/navigation/sentry_navigator_observer.dart) and [WidgetsBindingObserver](https://github.com/getsentry/sentry-dart/blob/dcdbe20f441e21c3fcc626a08dd3f82b09fc16af/flutter/lib/src/widgets_binding_observer.dart)
> * [MethodChannel](https://api.flutter.dev/flutter/services/MethodChannel-class.html) tracking. For example how long does it take to go from Dart to native to Dart. Or just from Dart to native or vice versa. The [onPlatformMessage()](https://api.flutter.dev/flutter/dart-ui/SingletonFlutterWindow/onPlatformMessage.html) method seems like a good candidate to test.
> * A SentryGlobalKey (see [GlobalKey](https://api.flutter.dev/flutter/widgets/GlobalKey-class.html)) to track the lifetime of widgets and get its state in crash reports. I don't actually know if it's possible, but have this idea floating around in my mind.
> * SentryHttpClient integration
> * Frame duration tracking, see [FrameTiming](https://api.flutter.dev/flutter/dart-ui/FrameTiming-class.html) and [how it should be monitored](https://flutter.dev/docs/perf/metrics)

Maybe include API health measures so it will help you as a developer to know which of the API takes the longest time until it receives the data

**Comment by estevejm** [comment]
> A couple of ideas for performance monitoring:
> 
> * Something like [Android's activity tracing](https://docs.sentry.io/platforms/android/performance/included-instrumentation/#androids-activity-instrumentation) but with [SentryNavigatorObserver](https://github.com/getsentry/sentry-dart/blob/dcdbe20f441e21c3fcc626a08dd3f82b09fc16af/flutter/lib/src/navigation/sentry_navigator_observer.dart) and [WidgetsBindingObserver](https://github.com/getsentry/sentry-dart/blob/dcdbe20f441e21c3fcc626a08dd3f82b09fc16af/flutter/lib/src/widgets_binding_observer.dart)
> * [MethodChannel](https://api.flutter.dev/flutter/services/MethodChannel-class.html) tracking. For example how long does it take to go from Dart to native to Dart. Or just from Dart to native or vice versa. The [onPlatformMessage()](https://api.flutter.dev/flutter/dart-ui/SingletonFlutterWindow/onPlatformMessage.html) method seems like a good candidate to test.
> * A SentryGlobalKey (see [GlobalKey](https://api.flutter.dev/flutter/widgets/GlobalKey-class.html)) to track the lifetime of widgets and get its state in crash reports. I don't actually know if it's possible, but have this idea floating around in my mind.
> * SentryHttpClient integration
> * Frame duration tracking, see [FrameTiming](https://api.flutter.dev/flutter/dart-ui/FrameTiming-class.html) and [how it should be monitored](https://flutter.dev/docs/perf/metrics)

Maybe include tracing header to connect with backend services?

**Comment by marandaneto** [comment]
@estevejm that's gonna be part of SentryHttpClient

**Comment by marandaneto** [comment]
https://github.com/getsentry/sentry-dart/releases/tag/6.1.0-alpha.1
