### ISSUE TITLE
How filter failed requests in sentry_dio?

### ISSUE THREAD

**Issue by Overman775** [getsentry/sentry-dart#787]
_Platform:_
- [X]  Dart
- [ ]  Flutter Android or iOS
- [ ]  Flutter Web

_IDE:_
- [X]  VSCode
- [ ]  IntelliJ/AS
- [ ]  XCode
- [ ]  Other, which one?

_split-debug-info and obfuscate (Flutter Android or iOS) or CanvasKit (Flutter Web):_
- [ ]  Enabled
- [X]  Disabled

_Platform installed with:_
- [X] pub.dev
- [ ] GitHub

The version of the SDK (See pubspec.lock):
**6.4.0**

I have the following issue: 

After update version from 6.3.0 to 6.4.0 `dio.addSentry` extension don't support `failedRequestStatusCodes`. How filter failed requests in 6.4.0?

**Comment by marandaneto** [comment]
@Overman775 the option `captureFailedRequests` will either enable or disable the feature.
`dio` itself throws or not depending on the HTTP error code, so no need to filter by `failedRequestStatusCodes` anymore.
You can also use the `beforeSend` callback to filter events https://docs.sentry.io/platforms/flutter/configuration/filtering/
