### ISSUE TITLE
Allow custom instrumentation to collect slow and frozen frames

### ISSUE THREAD

**Issue by ueman** [getsentry/sentry-dart#789]
I would like to be able to use the frames integration on macOS. Currently that's not possible because it depends on native code, which is also not able to provide frame information. 

However I could gather frame informations in pure Flutter code, based on https://github.com/getsentry/sentry-dart/pull/699 . That would also enable that feature on Linux and Windows and it's compatible from Flutter 2.0 onwards.

Therefore, I would like to have a way to somehow achieve this.

**Comment by marandaneto** [comment]
@ueman we're experimenting with a new public API for adding custom measurements, See https://github.com/getsentry/sentry-python/pull/1359
Not sure if we will make `SentryNative` flexible enough, but rather give you a proper way to report any measurement based on your own way.

**Comment by ueman** [comment]
Yeah, but then I would also have to write my own NavigationObserver and so on. The support for custom metrics is pretty exciting.

**Comment by philipphofmann** [comment]
We will make an abstraction in the API that when you use the custom instrumentation, slow and frozen frames are attached automatically.
