### ISSUE TITLE
dependencies:   sentry: ">=4.0.0 <5.0.0" not working

### ISSUE THREAD

**Issue by jalpesh** [getsentry/sentry-dart#79]
1. Please describe the issue and how to reproduce it, or link to a small reproducible application:

Added version in flutter project

dependencies:
  sentry: ">=4.0.0 <5.0.0"

However am getting the error 
Because app depends on sentry ^4.0.0 which doesn't match any versions, version solving failed.
pub get failed (1; Because app depends on sentry ^4.0.0 which doesn't match any versions, version solving failed.)

2. Include the output of the command `flutter doctor` below:

```sh



```

**Comment by bruno-garcia** [comment]
The README already lists the latest version which wasn't published yet.
We should have a version out soon. End of quarter so it's a bit delayed.

Please use version 3.0.1 for now

**Comment by jalpesh** [comment]
Ok great thank you.

**Comment by marandaneto** [comment]
https://github.com/getsentry/sentry-dart/releases/tag/4.0.0-alpha.2
