### ISSUE TITLE
Catch StateError in sentry_dio

### ISSUE THREAD

**Issue by Overman775** [getsentry/sentry-dart#790]
_Platform:_
- [X]  Dart
- [ ]  Flutter Android or iOS
- [ ]  Flutter Web

_IDE:_
- [X]  VSCode
- [ ]  IntelliJ/AS
- [ ]  XCode
- [ ]  Other, which one?

_split-debug-info and obfuscate (Flutter Android or iOS) or CanvasKit (Flutter Web):_
- [ ]  Enabled
- [X]  Disabled

_Platform installed with:_
- [X] pub.dev
- [ ] GitHub

Output of the command `flutter doctor -v` below:

[√] Flutter (Channel stable, 2.10.1, on Microsoft Windows [Version 10.0.22000.556], locale ru-RU)
    • Flutter version 2.10.1 at G:\Flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db747aa133 (5 weeks ago), 2022-02-09 13:57:35 -0600
    • Engine revision ab46186b24
    • Dart version 2.16.1
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc1)
    • Android SDK at G:\AndroidSdk
    • Platform android-31, build-tools 31.0.0-rc1
    • ANDROID_HOME = G:\AndroidSdk
    • ANDROID_SDK_ROOT = G:\AndroidSdk
    • Java binary at: G:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2021.1)
    • Android Studio at G:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] VS Code, 64-bit edition (version 1.65.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.36.0

[√] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 12 (API 31) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.22000.556]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 99.0.4844.51
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 96.0.1054.62

[√] HTTP Host Availability
    • All required HTTP hosts are available

The version of the SDK (See pubspec.lock):
**6.4.0**

---
I have the following issue:

Sentry fll 

**Steps to reproduce:**

Init:
```
  await SentryFlutter.init(
    (options) {
      options
        ..dsn = 'someDSN'
        ..debug = true
        ..tracesSampleRate = 1.0;
    },
    appRunner: () => runApp(
     .....
    ),
  );
}
```
```
  dio.addSentry(
    maxRequestBodySize: MaxRequestBodySize.medium,
    captureFailedRequests: true, // <==== Enable
  );
```
```
final response = await dio.get<Map<String, Object?>>('/some_wrong_url'); // catch 404 status code
```

**Actual result:**
```
[sentry] [debug] Could not convert DioError to SentryException
.....
[sentry] StateError (Bad state: No element)
[sentry] #0      Iterable.first (dart:core/iterable.dart:624:7)
#1      DioEventProcessor._removeDioErrorStackTraceFromValue
package:sentry_dio/src/dio_event_processor.dart:78
#2      DioEventProcessor.apply
package:sentry_dio/src/dio_event_processor.dart:48
#3      SentryClient._processEvent
package:sentry/src/sentry_client.dart:289
           <asynchronous suspension>
#4      SentryClient.captureTransaction
package:sentry/src/sentry_client.dart:246
           <asynchronous suspension>
#5      Hub.captureTransaction
package:sentry/src/hub.dart:467
           <asynchronous suspension>
#6      SentryTracer.finish
package:sentry/src/sentry_tracer.dart:103
           <asynchronous suspension>
#7      new SentryTracer.<anonymous closure>
package:sentry/src/sentry_tracer.dart:50
           <asynchronous suspension>

```

**Expected result:**

There should be no `StateError`

**Comment by ueman** [comment]
Which sentry_dio version are you using?

I guess this error is cause by this method https://github.com/getsentry/sentry-dart/blob/66bd83d41c87048a1ba9b60504db9619fdfdb0d6/dio/lib/src/dio_event_processor.dart#L72

That should be a pretty straight forward fix.

**Comment by Overman775** [comment]
> Which sentry_dio version are you using?

6.4.0 from pub.dev

**Comment by marandaneto** [comment]
@Overman775 can you provide a minimal reproducible example on GH? I tried to reproduce it and it didn't happen.

![Screenshot 2022-03-20 at 11 29 54](https://user-images.githubusercontent.com/5731772/159158184-aa81210d-48a1-40b5-b0f2-22ecf950cabe.png)

**Comment by kuhnroyal** [comment]
Do you have obfuscation on?
`element.type == dioError.runtimeType.toString()` will probably fail here: https://github.com/getsentry/sentry-dart/blob/main/dio/lib/src/dio_event_processor.dart#L77

**Comment by ueman** [comment]
> Do you have obfuscation on? `element.type == dioError.runtimeType.toString()` will probably fail here: https://github.com/getsentry/sentry-dart/blob/main/dio/lib/src/dio_event_processor.dart#L77

Hm, that should work even with obfuscation, because `type` is set from the runtime type?

**Comment by kuhnroyal** [comment]
Hmm, true. 

Then the function is called with an empty list: `List<SentryException>.from(event.exceptions ?? <SentryException>[])` so that  `.first` fails.
So the event has a throwable but not exceptions, not sure how this can happen, maybe a manually constructed event?

**Comment by marandaneto** [comment]
Yeah, strange, let's wait for the minimal example, but for the sake of defensive programming, we should check if the list isn't empty anyway before calling `first`.

**Comment by Overman775** [comment]
Failed to reproduce the bug in the minimal example. I'll try again and let you know the result
