### ISSUE TITLE
Before send not working 

### ISSUE THREAD

**Issue by jaumard** [getsentry/sentry-dart#800]
_Platform:_
- [ ]  Dart
- [ ]  Flutter Android or iOS
- [*]  Flutter Web

Output of the command `flutter doctor -v` below:

[✓] Flutter (Channel stable, 2.10.3, on macOS 12.3 21E230 darwin-x64, locale fr-FR)
    • Flutter version 2.10.3 at /Users/jaumard/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (3 weeks ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

The version of the SDK (See pubspec.lock):
  sentry_flutter: ^6.4.0
  sentry_dio: ^6.4.0
  sentry_logging: ^6.4.0

---
I have the following issue:

I have setup a beforesend hook where I want to filter Dio errors with specific http status code I don't care in sentry. But I still get them in sentry, look like the beforesend is not called. 

**Steps to reproduce:**
Here is how I setup Sentry:

```
FutureOr<SentryEvent?> beforeSend(SentryEvent event, {dynamic hint}) async {
  event.breadcrumbs?.add(Breadcrumb(message: 'beforeSend called!'));
  if (event.throwable is ErrorResultException && event.throwable.cause != ErrorResult.internal) {
    return null;
  } else if (event.throwable is DioError && (event.throwable.statusCode == 401 || event.throwable.statusCode == 403 || event.throwable.statusCode == 400)) {
    Logger('beforeSend').info('DIO ERROR SHOULD BE SKIPPED ${event.toJson()}');
    event.breadcrumbs?.add(Breadcrumb(message: 'DIO ERROR SHOULD BE SKIPPED!'));
    return null;
  }
  event.breadcrumbs?.add(Breadcrumb(message: 'NOT A DIO ERROR!'));
  Logger('beforeSend').info('Send ${event.toJson()}');
  return event;
}

SentryFlutter.init(
    (options) {
      options.dsn = kIsProductionMode ? 'https://..../2' : '';
      options.tracesSampleRate = .1;
      options.addIntegration(LoggingIntegration());
      options.beforeSend = beforeSend;
    },
    appRunner: () => runApp(const MyApp()),
  );
```

**Actual result:**
I still getting reports for http status 401; 403...

**Expected result:**
I should not receive report for those.

Here is what I get on breadcrumb, which is weird 
![Capture d’écran 2022-03-23 à 14 39 04](https://user-images.githubusercontent.com/2970449/159712674-b0fb990f-a62a-45b5-90dd-d32a88d50b3e.png)

**Comment by marandaneto** [comment]
@jaumard I believe the problem is your business logic to filter out the event.
Dio adds an event processor and we have to do some workarounds to report it nicely otherwise it does not look good in the UI, see this https://github.com/getsentry/sentry-dart/blob/main/dio/lib/src/dio_event_processor.dart
Can you confirm?

**Comment by marandaneto** [comment]
```
      options.beforeSend = (event, {hint}) {
        final error = event.throwable;
        if (error is DioError) {
          if (error.response?.statusCode == 404) {
            return null;
          }
        }
        return event;
      };
```

Works for me, the problem is your `beforeSend` logic.
Also, doing this does not make sense:

```
    event.breadcrumbs?.add(Breadcrumb(message: 'DIO ERROR SHOULD BE SKIPPED!'));
    return null;
```

Adding a breadcrumb to the event and dropping the event by returning null, the breadcrumb will never be there anyway.

**Comment by jaumard** [comment]
In fact the issue was that I noted the callback `async`, once removed it works... Not sure why having a future will totally ignore the fact that null is returned... 

The breadcrumb was just me trying to debug why that event is still sent event when sending null, I was kind of desperate lol
