### ISSUE TITLE
The page or path of the error source file is not displayed.

### ISSUE THREAD

**Issue by miguelflores1993** [getsentry/sentry-dart#805]
_Platform:_

- [x]  Flutter Android or iOS

_IDE:_
- [x]  VSCode

_split-debug-info and obfuscate (Flutter Android or iOS) or CanvasKit (Flutter Web):_
- [x]  Enabled
- [ ]  Disabled

_Platform installed with:_
- [x] pub.dev
- [ ] GitHub

Output of the command `flutter doctor -v` below:

The output goes here...

The version of the SDK (See pubspec.lock):
**6.4.0**

Hello good.
I am trying to see that the errors that originate in my application, the page or the origin route is not shown.

Do I need any extra configuration in the library?

![image](https://user-images.githubusercontent.com/67565934/160138610-fbbfeb0c-9300-4a49-9f30-db645619a70b.png)
![image](https://user-images.githubusercontent.com/67565934/160138637-0f9e1f46-bbd6-424d-ace9-757fd6768d32.png)
![image](https://user-images.githubusercontent.com/67565934/160138660-5aff3a41-425c-47d7-82cd-8dce8576a930.png)

**Comment by marandaneto** [comment]
Hi @miguelflores1993 
Can you link me to a sentry.io issue so I can investigate the metadata of the event? It's hard to say since the screenshot does not show much.
Are you using the `dio` integration? looks similar to https://github.com/getsentry/sentry-dart/issues/757

**Comment by miguelflores1993** [comment]
> Hola @miguelflores1993 ¿Puedes vincularme a un problema de sentry.io para que pueda investigar los metadatos del evento? Es difícil de decir ya que la captura de pantalla no muestra mucho. ¿Estás usando la `dio`integración? se parece al #757

https://sentry.io/share/issue/c211940fbb4e43949ceb75e877980f30/
https://sentry.io/share/issue/a19982a412e546d0bf88e79e1ba220ec/
https://sentry.io/share/issue/0d087fbe3a6a430483d26b752906186f/

that is the shared error, I have several logs, which do not say the origin of the file

**Comment by marandaneto** [comment]
You are missing debug symbols because your App is minified https://docs.sentry.io/platforms/flutter/upload-debug/#when-to-upload

**Comment by miguelflores1993** [comment]
> Te faltan símbolos de depuración porque tu aplicación está minimizada https://docs.sentry.io/platforms/flutter/upload-debug/#when-to-upload

I have uploaded the native debugging symbols to the play store appbundle, does that help me? I just did it.
https://developer.android.com/studio/build/shrink-code#native-crash-support

**Comment by marandaneto** [comment]
No, you've to upload debug symbols to Sentry, if you are using Sentry :)
