### ISSUE TITLE
iOS Native OOM 

### ISSUE THREAD

**Issue by kuhnroyal** [getsentry/sentry-dart#814]
_Platform:_
- [ ]  Dart
- [x]  Flutter Android or iOS
- [ ]  Flutter Web

_IDE:_
- [ ]  VSCode
- [x]  IntelliJ/AS
- [ ]  XCode
- [ ]  Other, which one?

_split-debug-info and obfuscate (Flutter Android or iOS) or CanvasKit (Flutter Web):_
- [ ]  Enabled
- [x]  Disabled

_Platform installed with:_
- [x] pub.dev
- [ ] GitHub

Output of the command `flutter doctor -v` below:

```
[✓] Flutter (Channel stable, 2.10.3, on macOS 12.2.1 21D62 darwin-x64, locale de-DE)
    • Flutter version 2.10.3 at /Users/.../fvm/versions/2.10.3@stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (vor 4 Wochen), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2
```

The version of the SDK (See pubspec.lock):
**6.4.0-beta.3**

---
I have the following issue:

I have a lot of new iOS native crashes with OOM and a Sentry log message before that. This only seems to happen in production so it is hard for me to give more information.
The Flutter SDK doesn't seem to be initialized, not sure when this is happening (app start or close).

![Bildschirmfoto 2022-03-30 um 10 33 51](https://user-images.githubusercontent.com/1260818/160788752-4b2b0947-6d9b-499a-8283-98a4c4b8e3f7.png)

Looking for help to figure out whats wrong here.

**Steps to reproduce:**
- not sure, only updated Sentry libraries

**Actual result:**
- see above

**Expected result:**
- no crash

**Comment by marandaneto** [comment]
@kuhnroyal please try out the https://github.com/getsentry/sentry-dart/releases/tag/6.5.0-alpha.2
Sentry Cocoa 7.11 has improvements for that.

**Comment by kuhnroyal** [comment]
Thanks, I updated, need to roll into production to see if that changes anything.

**Comment by kuhnroyal** [comment]
Still getting this with `7.11.0`/`6.5.0-beta.1` sadly

**Comment by marandaneto** [comment]
@kuhnroyal maybe disable the feature for now then, and watch this issue: https://github.com/getsentry/sentry-cocoa/issues/1618

**Comment by kuhnroyal** [comment]
> @kuhnroyal maybe disable the feature for now then, and watch this issue: [getsentry/sentry-cocoa#1618](https://github.com/getsentry/sentry-cocoa/issues/1618)

Thanks, i'll watch that issue. You are talking about the `enableOutOfMemoryTracking` right?

**Comment by marandaneto** [comment]
yes

**Comment by markuswahl-2** [comment]
We are also seeing this with 7.11.0. One difference we see when we upgraded from 7.9.0 to 7.11.0 is that we no longer get the information about APP Start Time. With 7.9.0 we see that all such OOM events occur in the same second that the app was started. After having upgraded to 7.10.2 or 7.11.0 we no longer get that piece of information.

**Comment by markuswahl-2** [comment]
Since this bug is closed, and the problem is till there I have opened a new bug, but this time in Sentry Cocoa, since we only get this problem for iOS: https://github.com/getsentry/sentry-cocoa/issues/1852
