### ISSUE TITLE
Sending the console output when using dart:developer.log

### ISSUE THREAD

**Issue by matiszz** [getsentry/sentry-dart#817]
_Platform:_
- [x]  Dart
- [x]  Flutter Android or iOS
- [ ]  Flutter Web

_IDE:_
- [ ]  VSCode
- [x]  IntelliJ/AS
- [ ]  XCode
- [ ]  Other, which one?

_split-debug-info and obfuscate (Flutter Android or iOS) or CanvasKit (Flutter Web):_
- [ ]  Enabled
- [x]  Disabled

_Platform installed with:_
- [x] pub.dev
- [ ] GitHub

Output of the command `flutter doctor -v` below:

```
[✓] Flutter (Channel stable, 2.10.2, on macOS 12.2.1 21D62 darwin-arm, locale es-ES)
    • Flutter version 2.10.2 at /Users/myuser/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 097d3313d8 (6 weeks ago), 2022-02-18 19:33:08 -0600
    • Engine revision a83ed0e5e3
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/myuser/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.65.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • iPhone SE (3rd generation) (mobile) • 3231DF37-C87D-XXXX-XXXX-XXXXXXXX • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-4 (simulator)
    • Chrome (web)                        • chrome                               • web-javascript • Google Chrome
      99.0.4844.84

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```
The version of the SDK (See pubspec.lock):
**6.0.1**

---
I have the following issue:

As [Flutter documentation says](https://docs.flutter.dev/testing/code-debugging#logging), my team logs debugging information such as requests, clicks, or loaded components using `developer.log()` from the `dart:developer` library. While `print()` is sent together with the stack trace to Sentry when an error occurs, `developer.log()` console doesn't appear to be sent along.

This is **extremely important** for us to correctly debug errors that appear in Sentry, since sometimes the information shown is very limited.

**Steps to reproduce:**
- Add some `developer.log()` logs.
- Add some `print()` logs.
- Generate an exception so it's sent to Sentry. 

**Actual result:**
- Only the `print()` logs are shown in the _Breadcrumbs_ of Sentry's web dashboard.

**Expected result:**
- Also `developer.log()` logs should be shown.

**Comment by marandaneto** [comment]
Thanks, that's a feature request, You could also consider using the `logging` package https://github.com/getsentry/sentry-dart/tree/main/logging

The problem with `dart:developer.log` is that it offers different mechanisms depending on the platform, e.g. for Flutter Web, it forwards to `console.log`, so we'd need to build an integration for each platform.

**Comment by matiszz** [comment]
I see. I added it as a bug because I supposed that the main recommended way to log things in Flutter should be supported by Sentry. Is there a way in the Sentry integration to specify which logger should recognize? Thanks.

**Comment by ueman** [comment]
The `dart:developer` package is stripped in release mode. See also this SO post: https://stackoverflow.com/questions/66507923/are-logs-drom-dartdeveloper-are-visible-in-release-mode-of-flutter-app

So even if it would be possible to intercept those, it wouldn't have any benefit in release mode.

**Comment by marandaneto** [comment]
That makes sense, thanks @ueman 
Closing it as not possible then.

**Comment by marandaneto** [comment]
> I see. I added it as a bug because I supposed that the main recommended way to log things in Flutter should be supported by Sentry. Is there a way in the Sentry integration to specify which logger should recognize? Thanks.

As mentioned before, you can use `print` since it's not stripped in release mode, you can use the https://pub.dev/packages/logging package and its Sentry integration, or even the Sentry SDK directly.
