### ISSUE TITLE
Missing information with iOS integration

### ISSUE THREAD

**Issue by kuhnroyal** [getsentry/sentry-dart#819]
_Platform:_
- [ ]  Dart
- [x]  Flutter Android or iOS
- [ ]  Flutter Web

_IDE:_
- [ ]  VSCode
- [x]  IntelliJ/AS
- [ ]  XCode
- [ ]  Other, which one?

_split-debug-info and obfuscate (Flutter Android or iOS) or CanvasKit (Flutter Web):_
- [ ]  Enabled
- [x]  Disabled

_Platform installed with:_
- [x] pub.dev
- [ ] GitHub

Output of the command `flutter doctor -v` below:

The output goes here...

The version of the SDK (See pubspec.lock):
**6.1.1+?/main**

---
I have the following issue:

Looking back in my Sentry instance (90 days) I can't find any native breadcrumbs for iOS devices, although they are activated by default (and I also call `enableBreadcrumbTrackingForCurrentPlatform()`).
So I checked out the current main example app and I have the same problem there.
A couple of the native iOS crashes from the example app also do not result in events.

**Steps to reproduce:**
- Run the example on iOS

**Actual result:**
- No native iOS breadcrumbs and some missing crashes

**Expected result:**
- Breadcrumbs and crashes should be in Sentry

**Comment by marandaneto** [comment]
@kuhnroyal Yes, this is being fixed here https://github.com/getsentry/sentry-dart/pull/761
We're blocked by a change on the iOS SDK, cc @philipphofmann https://github.com/getsentry/sentry-cocoa/issues/1665

**Comment by marandaneto** [comment]
https://github.com/getsentry/sentry-cocoa/issues/1665 isn't a blocker for this issue btw, my bad.
