### ISSUE TITLE
Sentry not working in Flutter Web

### ISSUE THREAD

**Issue by vinay416** [getsentry/sentry-dart#821]
I added the Sentry as per the documentation in my code.
https://pub.dev/packages/sentry_flutter

Flutter version 2.10.0

* If I give the project DNS (URL) then the app won't start correctly and keep loading.
* If I do not give any project DNS (URL) as an empty string it works perfectly for me.

Please provide a solution so I can run Flutter web with the sentry.

**Comment by marandaneto** [comment]
@vinay416 https://getsentry.github.io/sentry-dart/ is deployed on every release and it works just fine, mind providing logs or more context? SDK code snippet?
Also please update your bug report with the bug template https://github.com/getsentry/sentry-dart/issues/new?assignees=&labels=&template=BUG_REPORT.md

**Comment by vinay416** [comment]
@marandaneto Can you please your code snippet for sentry flutter web?

**Comment by marandaneto** [comment]
> @marandaneto Can you please your code snippet for sentry flutter web?

This is the repo and it's open-source.

**Comment by marandaneto** [comment]
Please provide a minimal reproducible example in case there's something wrong, and I will happily reopen the issue.
