### ISSUE TITLE
Sentry_flutter type mismatch when adding package

### ISSUE THREAD

**Issue by Goldfive** [getsentry/sentry-dart#825]
_Platform:_
- [ ]  Dart
- [x]  Flutter Android or iOS
- [x]  Flutter Web

_IDE:_
- [ ]  VSCode
- [x]  IntelliJ/AS
- [ ]  XCode
- [x]  Terminal

_split-debug-info and obfuscate (Flutter Android or iOS) or CanvasKit (Flutter Web):_
- [ ]  Enabled
- [x]  Disabled

_Platform installed with:_
- [x] pub.dev
- [ ] GitHub

Output of the command `flutter doctor -v` below:

flutter doctor -v                
[✓] Flutter (Channel master, 2.13.0-0.0.pre.222, on Fedora 34 (KDE Plasma) 5.16.14-100.fc34.x86_64, locale en_US.UTF-8)
    • Flutter version 2.13.0-0.0.pre.222 at /home/hq/lib/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 250c3407f4 (3 weeks ago), 2022-03-23 12:50:10 -0400
    • Engine revision 4fbff7a511
    • Dart version 2.17.0 (build 2.17.0-227.0.dev)
    • DevTools version 2.11.4

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc2)
    • Android SDK at /home/hq/Android/Sdk
    • Platform android-31, build-tools 33.0.0-rc2
    • ANDROID_HOME = /home/hq/Android/Sdk
    • ANDROID_SDK_ROOT = /home/hq/Android/Sdk
    • Java binary at: /home/hq/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/211.7628.21.2111.8193401/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 12.0.1 (Fedora 12.0.1-1.fc34)
    • cmake version 3.20.5
    • ninja version 1.10.2
    • pkg-config version 1.7.3

[✓] Android Studio (version 2021.1)
    • Android Studio at /home/hq/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/211.7628.21.2111.8193401
    • Flutter plugin version 65.2.2
    • Dart plugin version 211.7808
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.2)
    • IntelliJ at /usr/bin/intellij
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3)
    • IntelliJ at /home/hq/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/213.6777.52
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.50.1)
    • VS Code at /usr/share/code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Linux (desktop)                    • linux         • linux-x64      • Fedora 34 (KDE Plasma) 5.16.14-100.fc34.x86_64
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 99.0.4844.74

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

The version of the SDK (See pubspec.lock):
  sentry_flutter:
    dependency: "direct main"
    description:
      name: sentry_flutter
      url: "https://pub.dartlang.org"
    source: hosted
    version: "6.4.0"

---
I have the following issue:

I want to use the Sentry_flutter package, but when adding the package and running `flutter run`, I get an error about type mismatches. I have succesfully been able to install the package without flutter (https://pub.dev/packages/sentry). I would however like the extra functionality the Flutter package brings.

**Steps to reproduce:**
- flutter create sentry_test && cd sentry_test
- flutter pub add sentry_flutter

**Actual result:**
- `flutter run                   
Running "flutter pub get" in sentry_test...                        403ms
Using hardware rendering with device Android SDK built for x86. If you notice graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
Launching lib/main.dart on Android SDK built for x86 in debug mode...
e: /home/hq/.pub-cache/hosted/pub.dartlang.org/sentry_flutter-6.4.0/android/src/main/kotlin/io/sentry/flutter/SentryFlutterPlugin.kt: (67, 21): Type mismatch: inferred type is Map<String, Any>? but Map<String, Any> was expected
e: /home/hq/.pub-cache/hosted/pub.dartlang.org/sentry_flutter-6.4.0/android/src/main/kotlin/io/sentry/flutter/SentryFlutterPlugin.kt: (124, 21): Type mismatch: inferred type is List<Any>? but List<Any> was expected

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':sentry_flutter:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 13s
Running Gradle task 'assembleDebug'...                             14.1s
Exception: Gradle task assembleDebug failed with exit code 1`

**Expected result:**
- Succesfully ran the APK on my emulator since no code changes were made.

**Comment by kuhnroyal** [comment]
Use the matching version to your `sentry` package. Both should be `6.4.0`.

**Comment by marandaneto** [comment]
@Goldfive you're using Flutter in the beta channel and there were breaking changes, e.g. min. Kotlin version.
So you have to use our latest beta for that https://github.com/getsentry/sentry-dart/releases/tag/6.5.0-beta.1
See https://github.com/getsentry/sentry-dart/pull/786
