### ISSUE TITLE
Configure user scope does not work

### ISSUE THREAD

**Issue by zuboje** [getsentry/sentry-dart#832]
_Platform:_
- [ ]  Dart
- [x]  Flutter Android or iOS
- [ ]  Flutter Web

_IDE:_
- [x]  VSCode
- [ ]  IntelliJ/AS
- [ ]  XCode
- [ ]  Other, which one?

_split-debug-info and obfuscate (Flutter Android or iOS) or CanvasKit (Flutter Web):_
- [ ]  Enabled
- [x]  Disabled

_Platform installed with:_
- [x] pub.dev
- [ ] GitHub

Output of the command `flutter doctor -v` below:

```
[√] Flutter (Channel stable, 2.10.4, on Microsoft Windows [Version 10.0.22000.613], locale en-US)
    • Flutter version 2.10.4 at C:\Users\ivanp\source\repos\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (4 weeks ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\ivanp\AppData\Local\Android\sdk
    • Platform android-31, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.66.2)
    • VS Code at C:\Users\ivanp\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.38.1

[√] Connected device (1 available)
    • G80 (mobile) • 1080308020406374 • android-arm64 • Android 9 (API 28)

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

The version of the SDK (See pubspec.lock):
**6.4.0**

---
I have the following issue:

After the user logs in to my app I configure the scope for the user but when issues are generated dashboard does not show any information about the user. Unfortunately, I cannot do this during the init phase because the user is not logged in yet. Am I missing something or I have to use `withScope` in every single call for method `Sentry.captureException`?

**Steps to reproduce:**
Execute anywhere in the app after your user logs in:

```
Sentry.configureScope(
      (Scope scope) => scope.user = SentryUser(
        id: userId,
        username: userName,
        email: userEmail,
      ),
    );
```

**Actual result:**
Sentry dashboard does not identify user

**Expected result:**
Sentry dashboard should identify user by id, username or email address.

**Comment by marandaneto** [comment]
Nope, That's all you need: https://docs.sentry.io/platforms/dart/enriching-events/identify-user/
Is it Android or iOS? can you provide a minimal reproduction example? here everything works.

**Comment by zuboje** [comment]
I think I figured it out, my login function executes before Sentry is initialized. Is it possible to initialize sentry, configure scope and then run the app? This I believe would not be a problem if a user did not log in, but if a user is already logged in, the initial screen is different compared to when they are not.

```
bool isLoggedIn = await initialize();

await SentryFlutter.init(
    (SentryFlutterOptions options) {
      options.dsn = **my dsn value**
      options.tracesSampleRate = 1.0;
    },
    appRunner: () => runApp(
      MyApp(loggedIn: isLoggedIn),
),
```

**Comment by ueman** [comment]
Just move the `await initialize();` call inside the `appRunner` callback and everything should work.

**Comment by zuboje** [comment]
I think I tried that and it didn't work, but I just tested it and it works! Thanks and sorry for wasting your time, this should've been caught by me
