### ISSUE TITLE
Package Analysis step in CI does not upload results for contributors

### ISSUE THREAD

**Issue by ueman** [getsentry/sentry-dart#840]
From https://github.com/getsentry/sentry-dart/runs/6113791214?check_suite_focus=true

> Warning:  It seems that this action doesn't have the required permissions to call the GitHub API with the token you gave. This can occur if this repository is a fork, as in that case GitHub reduces the GITHUB_TOKEN's permissions for security reasons. Consequently, no report will be made on GitHub. Check this issue for more information: https://github.com/axel-op/dart-package-analyzer/issues/2

**Comment by marandaneto** [comment]
@ueman that's fine, it does not fail because of that tho, it fails because of https://github.com/dart-lang/pana/issues/1020
It's still useful to run `pana` from forks, or do you mean something else?

**Comment by ueman** [comment]
The issue is, that a contributer doesn't really know what's wrong if it fails because the result isn't uploaded.

**Comment by vaind** [comment]
I'm voting to close this - the CI job prints failure to logs - all the info is there for contributors to see and fix. Yes, it's not easy to read, but it's actionable. This could maybe be improved in the dependent action if it is really troublesome to many people but I wouldn't track it in this repo.
