### ISSUE TITLE
`Thread`s are not correctly attached to events

### ISSUE THREAD

**Issue by ueman** [getsentry/sentry-dart#841]
_Platform:_
- [x]  Dart
- [x]  Flutter Android or iOS
- [x]  Flutter Web

The version of the SDK (See pubspec.lock):
**6.5.x**

---
I have the following issue:

I want to attach a `Thread` for an `Exception`

The description goes here ...

**Steps to reproduce:**
1. Add exception to event with an id of 1
2. Add thread to event with an id of 1
3. Thread does not get serialized

**Actual result:**
- Thread is not attached

**Expected result:**
- Thread should get attached

---

I suppose the culprit is [this code](https://github.com/getsentry/sentry-dart/blob/e93430abb2ac24b30bb175ad3a54cb80d7671262/dart/lib/src/protocol/sentry_event.dart#L368-L385) and the fix could be:

```diff
-    final threadIds =
-        exceptions?.map((element) => element.threadId).toList(growable: false);
+    // create a set of every thread id of all exceptions
+    final threadIds = exceptions
+        ?.map((element) => element.threadId)
+        .where((element) => element != null)
+        .toSet();

    final threadJson = threads
-        ?.where((element) => !(threadIds?.contains(element.id) ?? false))
+        // only send threads wich has a matching exception
+        ?.where((element) => threadIds?.contains(element.id) ?? false)
        .map((e) => e.toJson())
        .where((e) => e.isNotEmpty)
        .toList(growable: false);
```

**Comment by marandaneto** [comment]
@ueman would you like to submit a Draft PR with a unit test that fails for this use case? I'm not quite sure I did understand the issue.
