### ISSUE TITLE
Remove deprecated device context fields

### ISSUE THREAD

**Issue by ueman** [getsentry/sentry-dart#842]
There are a couple of fields which are deprecated in the device context. Those fields should be removed in v7.0. Follow up from #838

**Comment by philipphofmann** [comment]
@ueman, could you point out the deprecated fields in the description, please?

**Comment by ueman** [comment]
Here's the list:
```
device.language
device.timezone
device.screenResolution
device.theme
```

Speaking of removing deprecated fields, there are a couple more candidates:
- https://github.com/getsentry/sentry-dart/blob/6ae0ef03535461e6a75d1eb297e71376eaeed749/dart/lib/src/enricher/io_enricher_event_processor.dart#L95-L96 since it was moved to `event.thread.name` and can be enabled by `options.attachThreads`
- This runtime key https://github.com/getsentry/sentry-dart/blob/6ae0ef03535461e6a75d1eb297e71376eaeed749/dart/lib/src/enricher/io_enricher_event_processor.dart#L58 since it doesn't add much value as name is already indicating what it is
- Same for this key https://github.com/getsentry/sentry-dart/blob/6ae0ef03535461e6a75d1eb297e71376eaeed749/flutter/lib/src/flutter_enricher_event_processor.dart#L224 since it doesn't add much value as name is already indicating what it is

**Comment by ueman** [comment]
https://github.com/getsentry/sentry-dart/pull/934 introduced attaching http response data, so the MaxRequestBodySize and MaxResponseBodySize enums can be consolidated.
