### ISSUE TITLE
Connecting Self Hosted Sentry with application

### ISSUE THREAD

**Issue by Lawati97** [getsentry/sentry-dart#845]
_Platform:_
-   Dart

_IDE:_
-  VSCode
- 
_split-debug-info and obfuscate (Flutter Android or iOS) or CanvasKit (Flutter Web):_
- [Disabled

_Platform installed with:_
-  pub.dev

The version of the SDK (See pubspec.lock):
**6.1.0**

---
I have the following issue:
I am trying to connect my app with self-hosted sentry but whenever I try to send a message to the sentry I get 403 error. Moreover, I was told to include the security token but am not sure where to do it

**Comment by marandaneto** [comment]
@Lawati97 What's the version of your Sentry server?
You don't need a token for the SDK, only the `DSN`. https://docs.sentry.io/product/sentry-basics/dsn-explainer/#where-to-find-your-dsn

I advice you asking help on https://github.com/getsentry/self-hosted

**Comment by marandaneto** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
