### ISSUE TITLE
Automatic instrumentation does not work as expect but custom on does

### ISSUE THREAD

**Issue by arquadrado** [getsentry/sentry-dart#859]
_Platform:_
- [ ]  Dart
- [x]  Flutter Android or iOS
- [ ]  Flutter Web

_IDE:_
- [x]  VSCode
- [ ]  IntelliJ/AS
- [ ]  XCode
- [ ]  Other, which one?

_split-debug-info and obfuscate (Flutter Android or iOS) or CanvasKit (Flutter Web):_
- [ ]  Enabled
- [x]  Disabled

_Platform installed with:_
- [x] pub.dev
- [ ] GitHub

Output of the command `flutter doctor -v` below:

[✓] Flutter (Channel stable, 2.10.5, on Pop!_OS 21.04 5.15.8-76051508-generic, locale en_US.UTF-8)
    • Flutter version 2.10.5 at /home/academiadecodigo/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (3 weeks ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/academiadecodigo/Android/Sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /usr/local/share/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[✓] Android Studio (version 2020.3)
    • Android Studio at /usr/local/share/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.63.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.36.0

[✓] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Linux (desktop)                    • linux         • linux-x64      • Pop!_OS 21.04 5.15.8-76051508-generic
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 100.0.4896.75

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

The version of the SDK (See pubspec.lock):
**6.5.1**

---
I have the following issue:

Hi guys, I am looking for an error tracking and performance monitoring tool for my company's app, written in flutter,  and i've spent the day trying Sentry.

It looks very good but I encountered a problem that I was unable to solve so far. Error tracking works great out of the box and custom tracing works just fine as well but I was unable to use the automatic instrumention.

From what I read in the docs it appears that I should have AppStart tracing out of the box but nothing appears related to that in the Performance tab. 

Same for AssetBundle instrumentation and  Dio integration. 

Any clue of what might be the issue?

Here's the init code in the main function:

```
await SentryFlutter.init(
    (options) {
      options
        ..dsn =
            'https://Xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx';
      // Set tracesSampleRate to 1.0 to capture 100% of transactions for performance monitoring.
      // We recommend adjusting this value in production.
      options.tracesSampleRate = 1.0;
    },
    appRunner: () => runApp(
      DefaultAssetBundle(
        bundle: SentryAssetBundle(enableStructuredDataTracing: true),
        child: const MyApp(),
      ),
    ),
  );

```
the usage for Dio:

```
dio.addSentry(captureFailedRequests: true);
await dio.get(path, queryParameters: query)
```

and the custom tracing:

```
final transaction = Sentry.startTransaction('test', 'task');
    try {

      throw Exception('Some very cool exception');
    } catch (exception, stackTrace) {
      transaction.throwable = exception;
      transaction.status = const SpanStatus.internalError();
      await Sentry.captureException(
        exception,
        stackTrace: stackTrace,
      );
    } finally {
      await transaction.finish();
    }
```

**Steps to reproduce:**

Run the app with the above configurations

**Actual result:**

Nothing appears on the performance dashboard except the custom tracing.

**Expected result:**

See both the custom transaction and the automatic ones displayed in the performance dashboard

**Comment by ueman** [comment]
Are you using the SentryNavigationObserver?

**Comment by marandaneto** [comment]
App start https://docs.sentry.io/platforms/flutter/performance/instrumentation/automatic-instrumentation/#app-start-instrumentation and Slow and frozen frames https://docs.sentry.io/platforms/flutter/performance/instrumentation/automatic-instrumentation/#slow-and-frozen-frames require setting up a Routing instrumentation, either https://docs.sentry.io/platforms/flutter/performance/instrumentation/automatic-instrumentation/#routing-instrumentation or https://docs.sentry.io/platforms/flutter/performance/instrumentation/automatic-instrumentation/#gorouter-instrumentation
You can also create your own transaction and bind it to the scope https://docs.sentry.io/platforms/flutter/performance/instrumentation/custom-instrumentation/#connect-errors-with-spans

**Comment by AhmedEzio47** [comment]
I've added the `SentryNavigatorObserver` to the list of observers and still got the performance page empty.
