### ISSUE TITLE
Test the latest Flutter version and see if everything works fine

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-dart#86]
the latest version shipped Android 11 and iOS 14 support, we need to test it

**Comment by rxlabz** [comment]
In debug mode : 
- [ ] throw null => no NullThrownException catched by the Dart Global ErrorHandler
- [ ] assertion error => no AssertionError catched by the Dart Global ErrorHandler
- [x] fail in microtask
- [x] fail in Isolate

In release mode : 
- [x] throw null
~~[ ] assertion error~~
- [x] fail in microtask
- [x] fail in Isolate

@marandaneto @bruno-garcia Is it worth investigating why the NullThrownException and AssertionError are not catched in debug mode ? ( it seems not related to Sentry )

**Comment by marandaneto** [comment]
@rxlabz time box this just to be sure it's not a bug on our end, also pay attention at the sample, could be that we are overwriting the error handler and swallowing the exception? just a guess though.

**Comment by rxlabz** [comment]
Well,  it's related to a Flutter known issue https://github.com/flutter/flutter/issues/48972 : the framework catch too much errors when a debugger is attached. I added a warning and the link to the issue in a comment.

**Comment by marandaneto** [comment]
thanks @rxlabz

**Comment by JaminZhou** [comment]
> * fail in Isolate

How to test 'fail in Isolate'. Is there a sample code? I've tried a few and they all get caught in runZonedGuarded.onError
