### ISSUE TITLE
The function 'runZonedGuarded' isn't defined

### ISSUE THREAD

**Issue by hkmsadek** [getsentry/sentry-dart#87]
1. Please describe the issue and how to reproduce it, or link to a small reproducible application:
I am trying to use sentry and i am getting the error undefined method. 
`The function 'runZonedGuarded' isn't defined.
Try importing the library that defines 'runZonedGuarded', correcting the name to the name of an existing function, or defining a function named 'runZonedGuarded'`

2. Include the output of the command `flutter doctor` below:

```sh
[✓] Flutter (Channel beta, 1.20.2, on Mac OS X 10.14.5 18F132, locale en-GB)
 
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[!] Android Studio (version 3.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Connected device (1 available)

! Doctor found issues in 2 categories.


```

**Comment by bruno-garcia** [comment]
We were missing the `import 'dart:async'` at the top of the docs. We've updated the docs [just now](https://github.com/getsentry/sentry-docs/pull/2444).

```dart
import 'dart:async'; // <- Add this

// Wrap your 'runApp(MyApp())' as follows:

void main() async {
  runZonedGuarded(
    () => runApp(MyApp()),
    (error, stackTrace) {
      await sentry.captureException(
        exception: error,
        stackTrace: stackTrace,
      );
    },
  );
}
```
