### ISSUE TITLE
Internet Connection Problem After Adding Sentry Package to Flutter Project

### ISSUE THREAD

**Issue by nastaran-mohammadi** [getsentry/sentry-dart#874]
Hello!
My application loses the internet connection in the device after adding sentry to the project. In an emulator, it is ok, but the connection fails in the device.

**Comment by marandaneto** [comment]
@Bunny1376 I'm pretty sure this is not related to the Sentry's SDK.
Do you have an error message or something to look at?
Thanks.

**Comment by marandaneto** [comment]
@Bunny1376 any news here?

**Comment by marandaneto** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
