### ISSUE TITLE
Error: The non-abstract class 'SentryAssetBundle' is missing implementations for these members:

### ISSUE THREAD

**Issue by matrixccp** [getsentry/sentry-dart#875]
../../.pub-cache/hosted/pub.flutter-io.cn/sentry_flutter-6.6.0-alpha.2/lib/src/sentry_asset_bundle.dart:32:7: Error: The non-abstract class 'SentryAssetBundle' is missing implementations for these members:
 - AssetBundle.loadBuffer
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class SentryAssetBundle implements AssetBundle {
      ^^^^^^^^^^^^^^^^^
../../flutter/packages/flutter/lib/src/services/asset_bundle.dart:62:30: Context: 'AssetBundle.loadBuffer' is defined here.
  Future<ui.ImmutableBuffer> loadBuffer(String key) async {

**Comment by ueman** [comment]
Which Flutter version are you using?

**Comment by ueman** [comment]
I've just looked it up, that method is only available on master: https://master-api.flutter.dev/flutter/services/AssetBundle/loadBuffer.html

The fix is pretty easy, just use the same approach as 

https://github.com/getsentry/sentry-dart/blob/b1f0ff68f91916d27d6083bc914bebad77ab08a8/flutter/lib/src/sentry_asset_bundle.dart#L163-L178

```dart
@override 
// This is an override on Flutter 3.1 (I guess) and later 
// ignore: override_on_non_overriding_member 
Future<ImmutableBuffer> loadBuffer(String key) { 
  try { 
    // TODO add performance tracing here
    return (_bundle as dynamic).loadBuffer(key); 
  } on NoSuchMethodError catch (_) { 
    // The clear method exists as of Flutter 3.1
    // Previous versions don't have it, but later versions do. 
    // We can't use `extends` in order to provide this method because this is 
    // a wrapper and thus the method call must be forwarded. 
    // On Flutter version before 2.8 we can't forward this call and 
    // just catch the error which is thrown. On later version the call gets 
    // correctly forwarded. 
  } 
} 
// or since the implementation of the method is pretty easy

@override 
// This is an override on Flutter 3.1 (I guess) and later 
// ignore: override_on_non_overriding_member 
Future<ImmutableBuffer> loadBuffer(String key) { 
  // Tracing is already done in the `load(key)` method.
  final ByteData data = await load(key);
  return ui.ImmutableBuffer.fromUint8List(data.buffer.asUint8List());
 } 
```

**Comment by matrixccp** [comment]
> Which Flutter version are you using?

3.1

**Comment by aJerezGit** [comment]
Hi guys, this same problem is happening in the latest stable version 3.3.3

**Comment by EzeBera** [comment]
same issue is happening to me in 3.3.3 and 3.3.4

**Comment by aJerezGit** [comment]
> same issue is happening to me in 3.3.3 and 3.3.4

Hey, i fixed it updating to latest version of sentry :)

**Comment by EzeBera** [comment]
me too,
 That worked, thanks
