### ISSUE TITLE
sentry_flutter not recognized

### ISSUE THREAD

**Issue by Narven** [getsentry/sentry-dart#878]
_Platform:_
- [ ]  Dart
- [x]  Flutter Android or iOS
- [ ]  Flutter Web

_IDE:_
- [x]  VSCode
- [ ]  IntelliJ/AS
- [ ]  XCode
- [ ]  Other, which one?

_split-debug-info and obfuscate (Flutter Android or iOS) or CanvasKit (Flutter Web):_
- [ ]  Enabled
- [ ]  Disabled

_Platform installed with:_
- [x] pub.dev
- [ ] GitHub

Output of the command `flutter doctor -v` below:
❯ flutter doctor -v
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.3.1 21E258 darwin-x64, locale en-GB)
    • Flutter version 3.0.1 at /usr/local/Caskroom/flutter/2.2.3/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • FLUTTER_GIT_URL = https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (3 weeks ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc2)
    • Android SDK at /Users/pedroluz/Library/Android/sdk
    • Platform android-32, build-tools 33.0.0-rc2
    • ANDROID_HOME = /Users/pedroluz/Library/Android/sdk
    • Java binary at: /Users/pedroluz/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/212.5712.43.2112.8609683/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Users/pedroluz/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/212.5712.43.2112.8609683/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] Android Studio (version 2021.2)
    • Android Studio at /Users/pedroluz/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/212.5712.43.2112.8512546/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (3 available)
    • Pedro's iFodas (mobile) • 8bcbadc6fc517c318b274a9ca9dbf57a320b79e0 • ios            • iOS 15.5 19F77
    • macOS (desktop)         • macos                                    • darwin-x64     • macOS 12.3.1 21E258 darwin-x64
    • Chrome (web)            • chrome                                   • web-javascript • Google Chrome 102.0.5005.61
    ! Error: Pedro's iFodas is not connected. Xcode will continue when Pedro's iFodas is connected. (code -13)
    ! Error: Pedro's iFodas is busy: Fetching debug symbols for Pedro's iFodas. Xcode will continue when Pedro's iFodas is finished. (code -10)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!  

The version of the SDK (See pubspec.lock):
**6.5.1**

---
I have the following issue:
I would like to know why is that after instalation nothing of sentry_flutter is recognized.

The description goes here ...

**Steps to reproduce:**
- add to `sentry_flutter: ^6.5.1` to pubspec
- flutter pub get
- add `package:sentry_flutter/sentry_flutter.dart'.` anywhere in your code
- FAIL

**Actual result:**

`Target of URI doesn't exist: 'package:sentry_flutter/sentry_flutter.dart'.`
Undefined name 'SentryFlutter'.

**Expected result:**
- Not complaning, recognize the import, work without making me waste 3 days.

**Comment by marandaneto** [comment]
@Narven can you provide a repro? it works for me.

**Comment by Narven** [comment]
Manage to fix the problem. Looks like it was a issue with `Dart Analysis Server` on vscode. but running the restart command... is now work.

Thanks @marandaneto
