### ISSUE TITLE
iOS crash: SentryANRTracker.m line 67

### ISSUE THREAD

**Issue by OHeroJ** [getsentry/sentry-dart#884]
io.sentry.anr-tracker
0  libsystem_kernel.dylib         0x1a2c __semwait_signal + 8
1  libsystem_c.dylib              0x50e4 nanosleep + 220
2  Foundation                     0x7bd08 +[NSThread sleepForTimeInterval:] + 160
3  Runner                         0x119adc -[SentryANRTracker detectANRs] + 67 (SentryANRTracker.m:67)
4  Foundation                     0x6943c __NSThread__start__ + 808
5  libsystem_pthread.dylib        0x19ac _pthread_start + 148
6  libsystem_pthread.dylib        0xe68 thread_start + 8

**Comment by brustolin** [comment]
Hi @OHeroJ. Thanks for sharing this with us. Before we investigate it can you share more information with us?
- Sentry SDK version you are using
- iOS version where the crash happened
- Options you are using to initialise Sentry SDK
- Does it happened every run, or at random?

**Comment by marandaneto** [comment]
@OHeroJ any news here?

**Comment by marandaneto** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
