### ISSUE TITLE
cant see my human readable errors in self hosted

### ISSUE THREAD

**Issue by mahdiqdi** [getsentry/sentry-dart#893]
hi guys
i have a problem with sentry
2 month ago i configured sentry in my project and we used self hosted sentry.i could'nt see any human readable error so i uploaded my debug-files and mapping.txt file as proguard and i could see a human readable error and everything was okay for a month(when i realsed a new version of my app i uploaded debug-files and mapping.txt and everything was okay).its about a month i can not see any human readable errors even if i uplaod new debug-files or mapping.txt and i cant find any solution to solve my problem.i used sentry v6.5.1.can anyone help me

**Comment by marandaneto** [comment]
@mahdiqdi please edit your issue description with more context using our bug template https://github.com/getsentry/sentry-dart/issues/new?assignees=&labels=&template=BUG_REPORT.md
right now I don't know what's wrong nor your setup, thanks.

**Comment by mahdiqdi** [comment]
Okay.i thought someone could help me with my description.i will make a issue with your template later.thanks🙏

**Comment by marandaneto** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
