### ISSUE TITLE
_TypeError (type '_InternalLinkedHashMap<Object?, Object?>' is not a subtype of type 'Map<String, dynamic>?') 

### ISSUE THREAD

**Issue by AndriiMatkivskyiSecurrency** [getsentry/sentry-dart#898]
_Platform:_
- [ ]  Dart
- [x]  Flutter Android or iOS
- [ ]  Flutter Web

_IDE:_
- [x]  VSCode
- [ ]  IntelliJ/AS
- [ ]  XCode
- [ ]  Other, which one?

_split-debug-info and obfuscate (Flutter Android or iOS) or CanvasKit (Flutter Web):_
- [ ]  Enabled
- [x]  Disabled

_Platform installed with:_
- [x] pub.dev
- [ ] GitHub

Output of the command `flutter doctor -v` below:

```
[✓] Flutter (Channel stable, 3.0.3, on macOS 12.4 21F79 darwin-arm, locale en-UA)
    • Flutter version 3.0.3 at /Users/andriymatkivskiy/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 676cefaaff (5 days ago), 2022-06-22 11:34:49 -0700
    • Engine revision ffe7b86a1e
    • Dart version 2.17.5
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/andriymatkivskiy/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.68.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.43.20220621

[✓] Connected device (1 available)
    • iPhone 13 Pro (mobile) • 1EAA4E2B-DB63-4741-9744-F8A08FE60B21 • ios • com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

The version of the SDK (See pubspec.lock):
**6.6.0**

---
I have the following issue:

When running the app on an iOS simulator I got this in the debug console: 

```
[sentry] [error] loadContextsIntegration failed
[sentry] _TypeError (type '_InternalLinkedHashMap<Object?, Object?>' is not a subtype of type 'Map<String, dynamic>?')
[sentry] #0      new Breadcrumb.fromJson
package:sentry/…/protocol/breadcrumb.dart:136
#1      _LoadContextsIntegrationEventProcessor.apply
package:sentry_flutter/src/default_integrations.dart:268
           <asynchronous suspension>
#2      SentryClient._processEvent
package:sentry/src/sentry_client.dart:345
           <asynchronous suspension>
#3      SentryClient.captureEvent
package:sentry/src/sentry_client.dart:85
           <asynchronous suspension>
#4      Hub.captureException
package:sentry/src/hub.dart:144
           <asynchronous suspension>
```

**Steps to reproduce:**
- Install Sentry pub package (6.6.0) to the app
- Run the app

**Actual result:**
- error stack trace in the debug console

**Expected result:**
- no errors in the debug console

Added some logging and found that this happens for such breadcrumb data: 
- ` {data: {screen: UICompatibilityInputViewController}, type: navigation, category: ui.lifecycle, timestamp: 2022-06-27T10:22:32.652Z, level: info}`
- `{"data":{"request_body_size":400,"response_body_size":9,"method":"POST","reason":"no error","url":"https://firebaselogging-pa.googleapis.com/v1/firelog/legacy/batchlog","status_code":200},"type":"http","category":"http","level":"info","timestamp":"2022-06-27T09:38:24.921Z"}`

**Comment by marandaneto** [comment]
@AndriiMatkivskyiSecurrency thanks for reporting.
Can you share the SDK code snippet and integration you are using so I can try to reproduce it? Thanks.

**Comment by AndriiMatkivskyiSecurrency** [comment]
@marandaneto  This is the only Sentry-related code we have: 
```
SentryFlutter.init(
    (option) {
      option
        ..dsn = EnvironmentConfig.config.sentryDns
        ..debug = kDebugMode
        ..enableAutoNativeBreadcrumbs = false
        ..enableAppLifecycleBreadcrumbs = true
        ..enableBreadcrumbTrackingForCurrentPlatform()
        ..enablePrintBreadcrumbs = EnvironmentConfig.config.trackPrints;
    },
    appRunner: () => runApp(Phoenix(child: const AppWidget())),
  );
```
And sometimes we track errors like this: 

`Sentry.captureException(error);`

**Comment by shripal-lean-ix** [comment]
I am also getting this error in the console. Using latest version 6.6.1. Fresh install of sentry in the project.

**Comment by ueman** [comment]
According to the stacktrace from the first post, it's coming from these lines: https://github.com/getsentry/sentry-dart/blob/188f470e31373330826f17547b0aa93d01cb3316/flutter/lib/src/default_integrations.dart#L175-L315

And more specifically from this line https://github.com/getsentry/sentry-dart/blob/188f470e31373330826f17547b0aa93d01cb3316/flutter/lib/src/default_integrations.dart#L266

But there could also be errors in the following lines which do not yet show since they're shadowed.


I guess the issue is, that `jsonDecode` returns a `Map<String, dynamic>` in most cases, but maps returned from MethodChannels are typically `Map<Object?, Object?>` (or `Map<Object, Object?>`?), but `Breadcrumb.fromJson()` only accepts `Map<String, dynamic>`. So the fix is to change it to `Breadcrumb.fromJson(Map<dynamic, dynamic>)`? 

This probably didn't show up in test because it's mocked and the return type in test from the MethodChannel is also `Map<String, dynamic>`.

**Comment by marandaneto** [comment]
@ueman The `keys` are always `String`, so it should not be an issue.

https://github.com/getsentry/sentry-dart/blob/7cf74d7379e48b82611d63c422a450a8c4478457/dart/test/mocks/mock_transport.dart#L34-L42

I ran only into these but only during tests.

@AndriiMatkivskyiSecurrency can you provide a minimal reproduction example and steps to reproduce it? I can't locally.

**Comment by AndriiMatkivskyiSecurrency** [comment]
Hi @marandaneto 
I've created a sample repo to demonstrate it. So the way to reproduce it is to rotate device

So I found that issue can be reproduced by rotating device: 


https://user-images.githubusercontent.com/93131457/176426049-bc36e103-55fe-4bf5-98c2-3d3c418729ca.mov

here is the link for the sample https://github.com/AndriiMatkivskyiSecurrency/sentry-issue

This breadcrumb is ok:
`flutter: newBreadcrumb: {category: started, level: info, message: Breadcrumb Tracking, type: debug, timestamp: 2022-06-29T10:45:24.354Z}`

This breadcrumb causes issue:
`flutter: newBreadcrumb: {data: {position: landscape}, category: device.orientation, timestamp: 2022-06-29T10:45:26.259Z, type: navigation, level: info}`

**Comment by marandaneto** [comment]
@AndriiMatkivskyiSecurrency thank you very much, that helps a lot.

**Comment by marandaneto** [comment]
https://github.com/getsentry/sentry-dart/pull/935
