### ISSUE TITLE
pod update issue

### ISSUE THREAD

**Issue by bawantha** [getsentry/sentry-dart#902]
[!] CocoaPods could not find compatible versions for pod "Sentry":
  In snapshot (Podfile.lock):
    Sentry (= 7.11.0, ~> 7.11.0)

  In Podfile:
    sentry_flutter (from `.symlinks/plugins/sentry_flutter/ios`) was resolved to 0.0.1, which depends on
      Sentry (~> 7.18.0)

You have either:
 * changed the constraints of dependency `Sentry` inside your development pod `sentry_flutter`.
   You should run `pod update Sentry` to apply changes you've made.

**Comment by marandaneto** [comment]
@bawantha you have just to `pod update` and likely `pod install` again, it's not a Sentry issue.
This should be done in the `ios` folder of your app likely.
