### ISSUE TITLE
bug: user feedback with attachment

### ISSUE THREAD

**Issue by mrverdant13** [getsentry/sentry-dart#903]
_Platform:_
- [ ]  Dart
- [x]  Flutter Android or iOS
- [ ]  Flutter Web

_IDE:_
- [x]  VSCode
- [ ]  IntelliJ/AS
- [ ]  XCode
- [ ]  Other, which one?

_split-debug-info and obfuscate (Flutter Android or iOS) or CanvasKit (Flutter Web):_
- [ ]  Enabled
- [x]  Disabled

_Platform installed with:_
- [x] pub.dev
- [ ] GitHub

Output of the command `flutter doctor -v` below:

```sh
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.0.1, on Microsoft Windows [Version 10.0.22000.739], locale en-US)
Checking Android licenses is taking an unexpectedly long time...[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.6)
[√] Android Studio (version 4.1)
[√] VS Code (version 1.68.1)
[√] Connected device (4 available)
[√] HTTP Host Availability

• No issues found!
```

The version of the SDK (See pubspec.lock):
**`^6.6.1`**

---
I have the following issue:

User feedback with attachments result in errors on the Sentry dashboard, but no errors get logged on the terminal.

**Steps to reproduce:**

Tap on a button with the following implementation:

```dart
	try {
      final id = await Sentry.captureMessage(
        message,
        level: SentryLevel.warning,
        withScope: (scope) {
          scope
            ..setTag('feedback', 'true')
            ..fingerprint = ['feedback-${uuid()}']
            ..addAttachment(
              SentryAttachment.fromUint8List(
                screenshot,
                'screenshot.png',
                contentType: 'image/png',
              ),
            );
        },
      );
      await Sentry.captureUserFeedback(
        SentryUserFeedback(
          eventId: id,
          comments: message,
        ),
      );
      print('User feedback sent');
    } catch (e, st) {
      print('Failed to send user feedback\n$e\n$st');
    }
```
	
Where `message` is a `String` and `screenshot` is the `Uint8List` representation of a PNG screenshot.

**Actual result:**
- No error messages are logged
- A new Sentry issue is created
- No feedback entry is created nor linked to the issue
- Plus, the Sentry dashboard displays the following:

<img width="355" alt="image" src="https://user-images.githubusercontent.com/42245236/176313036-c2f7dc01-cb85-4548-abaf-138e6379694a.png">

**Expected result:**
A new event on the Sentry issues view and a new entry on the Sentry user feedback view.

**Comment by marandaneto** [comment]
@mrverdant13 thanks for the report, are you using `sentry` or `sentry_flutter`? Android or iOS?

**Comment by mrverdant13** [comment]
@marandaneto 
I am using `sentry_flutter` and I've tested the package with a couple of Android devices.

PS I've updated the _actual result_ in the bug report:
> **Actual result:**
>
> - No error messages are logged
> - A new Sentry issue is created
> - No feedback entry is created nor linked to the issue
> - Plus, the Sentry dashboard displays the following:
>     ...

**Comment by marandaneto** [comment]
@mrverdant13 I've tried myself and the event, user feedback, and attachment came thru, is the issue only about the `contexts.runtimes`?
The user feedback may take a few seconds/minutes to be there in the Feedback tab because it's sent in a different request and the event ingestion could be busy and not visible right away, can you try again and let me know?

**Comment by mrverdant13** [comment]
@marandaneto 

Well I tested this again by sending two reports

As you can see here, both of them (**_khe_** and **_testing again_**) are listed within the issues page.
Also, they both include the user data, as expected.
<img width="394" alt="image" src="https://user-images.githubusercontent.com/42245236/177208318-de7739ea-3924-483a-a8d1-e6f3b358057a.png">

However, the user feedback page only shows the _**khe**_ feedback.

<img width="582" alt="image" src="https://user-images.githubusercontent.com/42245236/177208724-ca6ac5bf-6b99-4d4a-9243-6eaa3576f2d7.png">

---

Here I include the issue event details

<img width="562" alt="image" src="https://user-images.githubusercontent.com/42245236/177208993-4fe52f89-74c1-46a2-b30b-5887024bf01b.png">

<img width="561" alt="image" src="https://user-images.githubusercontent.com/42245236/177209133-d6a86547-e3c9-4d5b-a132-9eb7850be4d5.png">

**Comment by marandaneto** [comment]
@mrverdant13 can you provide a minimal reproduction example? an empty project that shows the problem, I can't reproduce myself, thanks.

**Comment by marandaneto** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
