### ISSUE TITLE
[dio] dio.addSentry hangs if dsn is an empty string

### ISSUE THREAD

**Issue by dsimon-dev** [getsentry/sentry-dart#908]
_Platform:_
- [ ]  Dart
- [x]  Flutter Android or iOS
- [ ]  Flutter Web

_IDE:_
- [x]  VSCode
- [ ]  IntelliJ/AS
- [ ]  XCode
- [ ]  Other, which one?

_split-debug-info and obfuscate (Flutter Android or iOS) or CanvasKit (Flutter Web):_
- [ ]  Enabled
- [x]  Disabled

_Platform installed with:_
- [x] pub.dev
- [ ] GitHub

Output of the command `flutter doctor -v` below:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.3, on Arch Linux 5.18.7-arch1-1, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2021.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
```

The version of the SDK (See pubspec.lock):
**6.6.1**

---
I have the following issue:

When setting `options.dsn = ""` in debug mode, the call `dio.addSentry()` causes the app to hang indefinitely. 

**Steps to reproduce:**

```dart
await SentryFlutter.init((options) {
    options.dsn = "";
});
dio.addSentry();
```

**Actual result:**
The whole app hangs until hard restarted.

**Expected result:**
The `dio.addSentry()` call succeeds and events are not sent because of the empty dsn.

**Comment by marandaneto** [comment]
@dsimon-dev the app hangs or crashes? your description and issue's title aren't synced.
Please enable `options.debug = true` and copy/paste the logs to understand what's going on.

**Comment by dsimon-dev** [comment]
Hi! The app hangs, sorry for the incorrect title, I have updated it accordingly. I will try the debug flag on Thursday and report back.
