### ISSUE TITLE
Always getting empty eventId from captureEvent | 'eventId != SentryId.empty()': is not true.

### ISSUE THREAD

**Issue by ikramhasan** [getsentry/sentry-dart#911]
_Platform:_
- [ ]  Dart
- [x]  Flutter Android or iOS
- [ ]  Flutter Web

_IDE:_
- [x]  VSCode
- [ ]  IntelliJ/AS
- [ ]  XCode
- [ ]  Other, which one?

_split-debug-info and obfuscate (Flutter Android or iOS) or CanvasKit (Flutter Web):_
- [ ]  Enabled
- [ ]  Disabled

_Platform installed with:_
- [x] pub.dev
- [ ] GitHub

Output of the command `flutter doctor -v` below:

[✓] Flutter (Channel stable, 2.10.3, on Microsoft Windows [Version 10.0.22000.739], locale en-US)
    • Flutter version 2.10.3 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (4 months ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\Users\IkramHasan\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.0.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.0.32112.339
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[✓] VS Code (version 1.68.1)
    • VS Code at C:\Users\IkramHasan\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.42.0

[✓] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.22000.739]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 103.0.5060.66
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 103.0.1264.37

[✓] HTTP Host Availability
    • All required HTTP hosts are available

The version of the SDK (See pubspec.lock):
**6.6.1**

---
I have the following issue:

I don't get any logs, bug reports, or user feedback in the sentry dashboard. This is the sentry id that I get: 00000000000000000000000000000000

For the bug report, it doesn't even show me any error. But while trying to upload feedback, I get this error:
I/flutter (19769): 'package:sentry/src/sentry_user_feedback.dart': Failed assertion: line 9 pos 15: 'eventId != SentryId.empty()': is not true.
I/flutter (19769): Failed to send user feedback

**Comment by marandaneto** [comment]
@ikramhasan Did you initialize the SDK?
Did the event get sent?
Can you share the code snippet of the SDK init, how you capture the event, and the userfeedback? thanks.

**Comment by ikramhasan** [comment]
**Did you initialize the SDK?**
: Yes

**Did the event get sent?**
: How do I check it? I logged the eventId that I got after sending the event. The id was: 00000000000000000000000000000000. Also, discard what I said about bugs and issues, those are reported fine. I just had to wait a while. It's just user feedback with attachments that's causing the problem. I think this issue is also similar: https://github.com/getsentry/sentry-dart/issues/903

**Can you share the code snippet of the SDK init, how you capture the event, and the userfeedback?**
:
await SentryFlutter.init(
    (options) {
      options.dsn =
          'https://xxxxxxxxx';
      // Set tracesSampleRate to 1.0 to capture 100% of transactions for performance monitoring.
      // We recommend adjusting this value in production.
      options.tracesSampleRate = 1.0;
    },
    appRunner: () => runApp(
      App(),
    ),
  );

**Comment by marandaneto** [comment]
@ikramhasan please enable `options.debug = true` and copy/paste the logs to understand what's going on.
Also can you share the code snippet of capturing an event and userfeedback? so I can check your API calls, thanks.

**Comment by marandaneto** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
