### ISSUE TITLE
Do not want PII rule in Sentry add extra

### ISSUE THREAD

**Issue by AugustWangVeeva** [getsentry/sentry-dart#912]
_Platform:_
- [ ]  Dart
- [✔️]  Flutter Android or iOS
- [ ]  Flutter Web

_IDE:_
- [ ✔️]  VSCode
- [ ]  IntelliJ/AS
- [ ]  XCode
- [ ]  Other, which one?

_split-debug-info and obfuscate (Flutter Android or iOS) or CanvasKit (Flutter Web):_
- [ ]  Enabled
- [ ✔️]  Disabled

_Platform installed with:_
- [ ✔️] pub.dev
- [ ] GitHub

Output of the command `flutter doctor -v` below:
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.8.0, on macOS 11.6.7 20G630 darwin-x64, locale zh-Hans-CN)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.1.3)
[✓] VS Code (version 1.68.1)
[✓] VS Code (version 1.68.1)
[✓] Connected device (2 available)

! Doctor found issues in 2 categories.
The output goes here...

The version of the SDK (See pubspec.lock):
**4.x.x**

---
I have the following issue:
I use Sentry.captureException(error, stackTrace: stackTrace, withScope: (scope) {
      scope.setExtra('taest','https://open.baacbusfa.com/api/clm/auth-config/?name=clm,fsfsfdfsfsdfs');
    });

The description goes here ...

**Steps to reproduce:**
- Step

**Actual result:**
- Actual
In Senty I got the message is filtered

taest | [Filtered]
![image](https://user-images.githubusercontent.com/52688144/176865711-7ff6c842-2d8e-45ea-946d-f93b7a474b46.png)

-- | --

**Expected result:**
- Result
I want to show message 'https://open.baacbusfa.com/api/clm/auth-config/?name=clm,fsfsfdfsfsdfs', and do not want it to be filtered by @password:filter

**Comment by marandaneto** [comment]
@AugustWangVeeva you can config your [server-side scrubbing](https://docs.sentry.io/product/data-management-settings/scrubbing/server-side-scrubbing/) or change the value that does not match the pattern, it's not an SDK issue.
it's likely because of the word `auth` or `name`.
