### ISSUE TITLE
Remove `experimental` annotation of `sentry_dio`

### ISSUE THREAD

**Issue by ueman** [getsentry/sentry-dart#913]
I believe it's fair to remove the `experimental` annotation from `sentry_dio`. It's been multiple months without any reported bugs, even though it has a popularity of 91%.

**Comment by ueman** [comment]
@kuhnroyal Any objections from your side?

**Comment by kuhnroyal** [comment]
> @kuhnroyal Any objections from your side?

No go ahead. Have been using it for a while. 👍
