### ISSUE TITLE
[sentry_dio] Add version test

### ISSUE THREAD

**Issue by ueman** [getsentry/sentry-dart#919]
sentry_dio has currently no version test. Ideally, this should be added.
See https://github.com/getsentry/sentry-dart/pull/914#discussion_r912664032

Version test is something like this

https://github.com/getsentry/sentry-dart/blob/d75a8c698a4942816336f3bae9a50c87fa6be0a8/dart/test/version_test.dart#L1-L21

**Comment by marandaneto** [comment]
https://github.com/getsentry/sentry-dart/pull/1306/files
