### ISSUE TITLE
Issues reported as "Unknown OS"

### ISSUE THREAD

**Issue by vaind** [getsentry/sentry-dart#942]
Looks like iOS/macOS issues are missing the OS info. Examples:

* https://sentry.io/organizations/sentry-sdks/issues/3410159820/?project=5428562&query=is%3Aunresolved
* https://stackoverflow.com/questions/72853304/sentry-doesnt-provide-operating-system-on-events

**Comment by bruno-garcia** [comment]
Thanks for raising Ivan. We need to look into this.

**Comment by marandaneto** [comment]
The issue is that we have to merge all the context items instead of adding them only if it does not exist:
https://github.com/getsentry/sentry-dart/blob/bdc6e0f4a5b73c4bbf6e24054076f8d6cf88106e/flutter/lib/src/default_integrations.dart#L190-L192

**Comment by ueman** [comment]
See also https://github.com/getsentry/sentry-dart/issues/766
