### ISSUE TITLE
Duplicated `BreadCrumbs`

### ISSUE THREAD

**Issue by Lorenzohidalgo** [getsentry/sentry-dart#946]
_Platform:_
- [ ]  Dart
- [X]  Flutter Android or iOS
- [ ]  Flutter Web

_IDE:_
- [X]  VSCode
- [ ]  IntelliJ/AS
- [ ]  XCode
- [ ]  Other, which one?

_split-debug-info and obfuscate (Flutter Android or iOS) or CanvasKit (Flutter Web):_
- [ ]  Enabled
- [ ]  Disabled

_Platform installed with:_
- [X] pub.dev
- [ ] GitHub

Output of the command `flutter doctor -v` below:
```logs
[√] Flutter (Channel stable, 3.0.4, on Microsoft Windows [Versi¢n 10.0.19044.1806], locale es-ES)
    • Flutter version 3.0.4 at C:\DEVELOPMENT\SRC\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 85684f9300 (2 weeks ago), 2022-06-30 13:22:47 -0700
    • Engine revision 6ba2af10bb
    • Dart version 2.17.5
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)     
    • Android SDK at C:\Users\Lorenzo HG\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)    
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Visual Studio Build Tools 2017 15.9.30)     
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools
    • Visual Studio Build Tools 2017 version 15.9.28307.1321
    • Windows 10 SDK version 10.0.17763.0
    X Visual Studio 2019 or later is required.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 4.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code, 64-bit edition (version 1.69.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.44.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Versi¢n 10.0.19044.1806]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 103.0.5060.114
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 98.0.1108.50

[√] HTTP Host Availability
    • All required HTTP hosts are available
```

The version of the SDK (See pubspec.lock):
**6.5.1**

---
I have the following issue:
I've started testing the `BreadCrumbs` feature and I've observed that they are either:
1. sent duplicated
2. The Web UI shows them duplicated

**Steps to reproduce:**
- Add a `BreadCrumb` to be added when a button is pressed
- Throw a Exception

**Actual result:**
- Web UI shows the `BreadCrumb` twice
- ![image](https://user-images.githubusercontent.com/22448611/179184181-ba6f8844-c7dc-4ff7-b1f7-3c746d6808d9.png)

**Expected result:**
- Only one `BreadCrumb` should be sent/shown, since there is no need to duplicate it

**Comment by bruno-garcia** [comment]
@Lorenzohidalgo what was the SDK name in the bottom of the event detail page? I suspect this is a native event and somehow we're applying the breadcrumbs from the Dart layer + adding the scope data from native and hence duplicating crumbs.

**Comment by Lorenzohidalgo** [comment]
here is the screenshot @bruno-garcia :
![image](https://user-images.githubusercontent.com/22448611/179909149-927a395e-dd6c-41e6-a29a-49c2caba6163.png)

**Comment by marandaneto** [comment]
@Lorenzohidalgo Is this Android only or iOS too? I believe its related to https://github.com/getsentry/sentry-dart/issues/952

**Comment by Lorenzohidalgo** [comment]
Hi @marandaneto, I've only tested it on android. We've not implemented the breadcrumbs yet.

**Comment by marandaneto** [comment]
https://github.com/getsentry/sentry-dart/releases/tag/6.7.0
