### ISSUE TITLE
NoClassDefFoundError io.sentry.flutter.b

### ISSUE THREAD

**Issue by miguelflores1993** [getsentry/sentry-dart#956]
_Platform:_
- [ ]  Dart
- [x ]  Flutter Android or iOS
- [ ]  Flutter Web

_IDE:_
- [ ]  VSCode
- [ ]  IntelliJ/AS
- [ x]  XCode
- [ ]  Other, which one?

_split-debug-info and obfuscate (Flutter Android or iOS) or CanvasKit (Flutter Web):_
- [x ]  Enabled
- [ ]  Disabled

_Platform installed with:_
- [ x] pub.dev
- [ ] GitHub

Output of the command `flutter doctor -v` below:

The output goes here...

The version of the SDK (See pubspec.lock):
**6.7.0**

---
I have the following issue:

```
Android
Versión:6.0
HUAWEI MLA-L13
Modelo:HUAWEIMLA-L13
```

Currently a user can't login to my application it closes immediately, so I sentry I log an error, and I think it's related to the library

**Steps to reproduce:**
A user opens the application and it closes immediately and Sentry logs the error

**Actual result:**
Error real https://sentry.io/share/issue/eb0fe6e0b10a4aae95019eb24d489545/)

**Expected result:**
I should let him use the app

**Comment by marandaneto** [comment]
@miguelflores1993 Something in your configuration is wrong, you said that you are using the SDK `6.7.0` which depends on the Android SDK [6.3.0](https://github.com/getsentry/sentry-dart/blob/13f275e07bc7caa650478008f6a42f0627247903/flutter/android/build.gradle#L57).
The linked issue is with the `6.1.2` version of the Android SDK, please check which version of the Flutter SDK you are using, is it 6.7.0 for that version of your app?
This issue looks similar to https://github.com/getsentry/sentry-dart/issues/916 which already has been fixed.

**Comment by miguelflores1993** [comment]
> @miguelflores1993Algo en su configuración está mal, dijo que está usando el SDK `6.7.0`que depende del SDK de Android [6.3.0](https://github.com/getsentry/sentry-dart/blob/13f275e07bc7caa650478008f6a42f0627247903/flutter/android/build.gradle#L57) . El problema vinculado es con la `6.1.2`versión del SDK de Android, verifique qué versión del SDK de Flutter está usando, ¿es 6.7.0 para esa versión de su aplicación? Este problema se parece al [n.º 916](https://github.com/getsentry/sentry-dart/issues/916) que ya se solucionó.


My mistake in putting the version of sentry the report.

Thank you for the correction.
