### ISSUE TITLE
I'm using Sentry 6.4.0 but from one hour I started get this error 

### ISSUE THREAD

**Issue by alaakhaled** [getsentry/sentry-dart#964]
../../../.pub-cache/hosted/pub.dartlang.org/sentry_flutter-6.8.1/lib/src/integrations/on_error_integration.dart:33:59: Error: Property 'platformDispatcher' cannot be accessed on 'WidgetsBinding?' because it is potentially null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../FlutterWS/flutter/packages/flutter/lib/src/widgets/binding.dart').
Try accessing using ?. instead.
        PlatformDispatcherWrapper(WidgetsBinding.instance.platformDispatcher);
                                                          ^^^^^^^^^^^^^^^^^^

**Comment by ueman** [comment]
This line 
https://github.com/getsentry/sentry-dart/blob/aad9fc7df5fab761b18ca02b546fd5786192f705/flutter/lib/src/integrations/on_error_integration.dart#L33

should be using 

https://github.com/getsentry/sentry-dart/blob/aad9fc7df5fab761b18ca02b546fd5786192f705/flutter/lib/src/binding_utils.dart#L6

This mistake would have been caught by https://github.com/getsentry/sentry-dart/issues/636.
