### ISSUE TITLE
Detect shader compilation jank

### ISSUE THREAD

**Issue by ueman** [getsentry/sentry-dart#971]
The idea is to detect shader compilation jank and then tell users, that they can improve it by following https://docs.flutter.dev/perf/shader.

Shader compilation only happens on a cold app start. Which means, comparing framedata from a cold start vs a warm start could give some indication? But that comparison is also just meaningful if the user of the app does the same thing after both app starts. Maybe some clever heuristic paired with the navigation observer does the trick?

There's https://api.flutter.dev/flutter/dart-ui/FrameTiming-class.html but only on newer Flutter versions (> 2.5 or 2.8 I believe. Also properties of that class are less on older versions). That can be used to do the calculation. 
You can do some assumption regarding which framephases (https://api.flutter.dev/flutter/dart-ui/FramePhase.html) take too much time.

Since manual shader compilation is quite some work, there should be a way to opt-in/out, depending on the default.

**Comment by marandaneto** [comment]
@ueman Maybe this is less relevant now since `Impeller` will likely replace Skia and shaders will be compiled at compile time, does that make sense?

**Comment by ueman** [comment]
I mean it would still be nice to be able to detect it, but I don't mind closing this. I've opened this issue after Bruno asked me to.

**Comment by marandaneto** [comment]
Lets see how `Impeller` is going to play out before working on this, I do agree it makes sense, but if working on this means deprecating it soonish, it does not make much sense.

**Comment by marandaneto** [comment]
Closed in favor of https://github.com/getsentry/sentry-dart/issues/1106
Profiling would give this for free whenever is available/possible on Flutter.
