### ISSUE TITLE
[sentry-flutter] Help Wanted: add custom headers property on report message request

### ISSUE THREAD

**Issue by KeterVM** [getsentry/sentry-dart#973]
hi, how can i add custom headers property on report message request?

**Comment by marandaneto** [comment]
@KeterVM please edit your Pr description with one of the templates https://github.com/getsentry/sentry-dart/issues/new/choose
I am not sure what you mean by your question.

**Comment by KeterVM** [comment]
ok, i will open another issue and try to explain my question clearer
