### ISSUE TITLE
Breadcrumbs stopped working on Chrome

### ISSUE THREAD

**Issue by mnordine** [getsentry/sentry-dart#979]
Using Dart `2.17.6`, Sentry `6.9.0` on the web, breadcrumbs stopped working on Chrome and Firefox. They still work fine on Safari.

It seems to be affecting all Chrome versions.

I'm not sure when it stopped working, perhaps around Sentry `6.0.0`, but not sure.

Just going to go ahead and pre-empt the inevitable question: This has nothing to do with Flutter. It's a Dart web app, that's it.

**Comment by marandaneto** [comment]
@mnordine can you elaborate on what's not working means?
Can you provide your SDK init code snippet? Thanks.

**Comment by mnordine** [comment]
They don't show up in the event page, at all. The html section where you'd expect them to be is completely gone. Not an empty list, it's just not there.

**Comment by mnordine** [comment]
```dart
await init(() => App().start());

Future<void> init(AppRunner appRunner) async {
  try {
    await Sentry.init((config) => config
      ..dsn = {dsn_here}
      ..release = clientVersion
      ..enablePrintBreadcrumbs = !debug
      ..environment = env
      ..debug = debug
      ..beforeSend = beforeSend
      ..addEventProcessor(_EventProcessor()),
      appRunner: appRunner,
    );
}
```

**Comment by marandaneto** [comment]
@mnordine how are you adding breadcrumbs? can you provide a minimal reproducible example? it works on my end.

**Comment by marandaneto** [comment]
@mnordine any news here?

**Comment by marandaneto** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!

**Comment by mnordine** [comment]
I'm still not sure what's going on here. I haven't changed any code, and it stopped working on Chrome after updating this library at some point. Still works fine in FF and Safari.

The only thing I can really add is that this is how we log breadcrumbs:
```dart
void addDebugEvent({String? message, String? category, Map<String, dynamic>? data, SentryLevel level = SentryLevel.info, String? type}) {
  final crumb = Breadcrumb(message: message, category: category, data: data, level: level, type: type);
  Sentry.addBreadcrumb(crumb);
}
```

**Comment by mnordine** [comment]
@marandaneto @denrase This has indeed been broken all along: https://github.com/getsentry/sentry-dart/commit/fe6fcc88fceca69bd854b9edb25f65ceee76ec0a#diff-982a51a78ca76fe98e2ab778df380b3b941867390fbe700a9a556d94e5aa354bR119

Fix in PR above.
