### ISSUE TITLE
Add a changelog in both packages to satisfy the pub.dev analyzer

### ISSUE THREAD

**Issue by rxlabz** [getsentry/sentry-dart#98]
the pub.dev analysis score removes 5 points when there is no changelog file in a package.
cf. #96

**Comment by bruno-garcia** [comment]
We could use a symlink (if pub publish supports that). And have a shared CHANGELOG.
Otherwise we'll need to maintain two changelogs, I'm afraid.

**Comment by rxlabz** [comment]
Once the Flutter package will use the native plugins, will both packages be impacted by the same changes ?

**Comment by marandaneto** [comment]
we already have symlinks, if `pub publish` doesn't support it, we'll reopen it
