### ISSUE TITLE
Notifiy user of invalid trace rate setting

### ISSUE THREAD

**Issue by ueman** [getsentry/sentry-dart#981]
Performance tracing doesn't work if both the tracesSampler and the traceSampler rate is set. There should be some sort of error when the user does it.

This enlightenment come out of a recent discussion on Discord.

**Comment by marandaneto** [comment]
The docs states `// OR` but yeah it could be improved, an extra log on the SDK side might help.

**Comment by marandaneto** [comment]
Align that between SDKs, should we just log in to the console if the traces rate is out of the range or if both are set and they should not? will follow up later.
JS documents which one has precedence in case both are set.
Android throws if its out of range, if you set both, sampler callback has precedence over the other one, JS is the same.
