### ISSUE TITLE
Out of Memory Crash Report Has sdk.integrations: Discarded invalid value （）

### ISSUE THREAD

**Issue by philos3** [getsentry/sentry-dart#985]
Environment
Flutter (Channel stable, 3.0.5, on macOS 12.1 21C52 darwin-x64, locale zh-Hans-CN)
• Flutter version 3.0.5 at /Users/zby0520/fvm/versions/stable
• Upstream repository https://github.com/flutter/flutter.git
• Framework revision f1875d570e (6 weeks ago), 2022-07-13 11:24:16 -0700
• Engine revision e85ea0e79c
• Dart version 2.17.6
• DevTools version 2.12.2
• Pub download mirror https://pub.flutter-io.cn/
• Flutter download mirror https://storage.flutter-io.cn/
Checking Android licenses is taking an unexpectedly long time...[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
• Android SDK at /Users/zby0520/Library/Android/sdk
• Platform android-32, build-tools 32.0.0
• ANDROID_SDK_ROOT = /Users/zby0520/Library/Android/sdk
• Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
• Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
• All Android licenses accepted.

sentry_flutter: ^6.9.1
sentry_logging: ^6.9.1
sentry_dio: ^6.9.1

Steps to Reproduce
![image](https://user-images.githubusercontent.com/8424317/186664055-4fe02798-426b-412b-860a-2b7568518b8f.png)

OutOfMemory
The OS most likely terminated your app because it overused RAM.

Actual Result
sentry cause iOS app crash
https://sentry.deepcoin.ski/share/issue/44d64605ca514a8189d151e712132ab4

**Comment by philos3** [comment]
any updates

**Comment by marandaneto** [comment]
Dupe https://github.com/getsentry/sentry-dart-plugin/issues/37
