### ISSUE TITLE
flutter 3.3.0 migration failed

### ISSUE THREAD

**Issue by sejun2** [getsentry/sentry-dart#992]
_Platform:_
- [ ]  Dart
- [x]  Flutter Android or iOS
- [ ]  Flutter Web

_IDE:_
- [ ]  VSCode
- [x]  IntelliJ/AS
- [ ]  XCode
- [ ]  Other, which one?

_split-debug-info and obfuscate (Flutter Android or iOS) or CanvasKit (Flutter Web):_
- [x]  Enabled
- [ ]  Disabled

_Platform installed with:_
- [x] pub.dev
- [ ] GitHub

Output of the command `flutter doctor -v` below:

The output goes here...

The version of the SDK (See pubspec.lock):
6.5.1

---
I have the following issue:

After flutter upgraded 3.3.0 from 3.0.5, build fails with such errors.

```
class SentryAssetBundle implements AssetBundle {
      ^^^^^^^^^^^^^^^^^
../../../fvm/versions/3.3.0/packages/flutter/lib/src/services/asset_bundle.dart:64:30: Context: 'AssetBundle.loadBuffer' is defined here.
  Future<ui.ImmutableBuffer> loadBuffer(String key) async {
                             ^^^^^^^^^^

```

**Comment by sejun2** [comment]
uum, after upgrade package verison to 6.9.1, it works fine now.

**Comment by ueman** [comment]
This was already fixed in https://github.com/getsentry/sentry-dart/pull/877
